-- Top 100 public vocabulary content v1, part 4.
-- Split into smaller files to keep D1 migration statements manageable.

UPDATE core_vocabulary SET word = 'well', meaning_zh = '好地；顺利地；健康地', definition_en = 'in a good, successful, or satisfactory way', primary_part_of_speech = 'adverb', phonetic_us = '/wɛl/', phonetic_uk = '/wel/', updated_at = CURRENT_TIMESTAMP WHERE id = 'well';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/wɛl/' WHEN 'uk' THEN '/wel/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'well' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('well-sense-1', 'well', 'well', 'well', 'adverb', '好地；顺利地；健康地', 'in a good, successful, or satisfactory way', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('well-example-1', 'well', 'well', 'well', 'well-sense-1', 'You did very well today.', '你今天做得很好。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('well-collocation-1', 'well', 'well', 'well', 'well-sense-1', 'do well', 'do well', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('well-collocation-2', 'well', 'well', 'well', 'well-sense-1', 'well done', 'well done', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('well-collocation-3', 'well', 'well', 'well', 'well-sense-1', 'as well', 'as well', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('well', 'well', 'well', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('well', 'well', 'well', 'work', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('well', 'well', 'well', 'emotion', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'because', meaning_zh = '因为', definition_en = 'used to give the reason for something', primary_part_of_speech = 'conjunction', phonetic_us = '/bɪˈkɔz, bɪˈkʌz/', phonetic_uk = '/bɪˈkɒz/', updated_at = CURRENT_TIMESTAMP WHERE id = 'because';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/bɪˈkɔz, bɪˈkʌz/' WHEN 'uk' THEN '/bɪˈkɒz/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'because' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('because-sense-1', 'because', 'because', 'because', 'conjunction', '因为', 'used to give the reason for something', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('because-example-1', 'because', 'because', 'because', 'because-sense-1', 'I stayed home because it rained.', '因为下雨，我待在家里。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('because-collocation-1', 'because', 'because', 'because', 'because-sense-1', 'because of', 'because of', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('because-collocation-2', 'because', 'because', 'because', 'because-sense-1', 'just because', 'just because', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('because-collocation-3', 'because', 'because', 'because', 'because-sense-1', 'because I can', 'because i can', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('because', 'because', 'because', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('because', 'because', 'because', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'very', meaning_zh = '非常；很', definition_en = 'used to emphasize an adjective or adverb', primary_part_of_speech = 'adverb', phonetic_us = '/ˈvɛri/', phonetic_uk = '/ˈveri/', updated_at = CURRENT_TIMESTAMP WHERE id = 'very';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈvɛri/' WHEN 'uk' THEN '/ˈveri/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'very' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('very-sense-1', 'very', 'very', 'very', 'adverb', '非常；很', 'used to emphasize an adjective or adverb', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('very-example-1', 'very', 'very', 'very', 'very-sense-1', 'The lesson was very helpful.', '这节课非常有帮助。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('very-collocation-1', 'very', 'very', 'very', 'very-sense-1', 'very good', 'very good', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('very-collocation-2', 'very', 'very', 'very', 'very-sense-1', 'very much', 'very much', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('very-collocation-3', 'very', 'very', 'very', 'very-sense-1', 'very well', 'very well', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('very', 'very', 'very', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('very', 'very', 'very', 'emotion', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'just', meaning_zh = '只是；刚刚；正好', definition_en = 'only, exactly, or a very short time ago', primary_part_of_speech = 'adverb', phonetic_us = '/dʒʌst/', phonetic_uk = '/dʒʌst/', updated_at = CURRENT_TIMESTAMP WHERE id = 'just';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/dʒʌst/' WHEN 'uk' THEN '/dʒʌst/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'just' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('just-sense-1', 'just', 'just', 'just', 'adverb', '只是；刚刚；正好', 'only, exactly, or a very short time ago', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('just-example-1', 'just', 'just', 'just', 'just-sense-1', 'I just finished my work.', '我刚完成工作。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('just-collocation-1', 'just', 'just', 'just', 'just-sense-1', 'just now', 'just now', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('just-collocation-2', 'just', 'just', 'just', 'just-sense-1', 'just a little', 'just a little', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('just-collocation-3', 'just', 'just', 'just', 'just-sense-1', 'just like', 'just like', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('just', 'just', 'just', 'time', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('just', 'just', 'just', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'come', meaning_zh = '来；到来', definition_en = 'to move toward or arrive at a place', primary_part_of_speech = 'verb', phonetic_us = '/kʌm/', phonetic_uk = '/kʌm/', updated_at = CURRENT_TIMESTAMP WHERE id = 'come';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/kʌm/' WHEN 'uk' THEN '/kʌm/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'come' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('come-sense-1', 'come', 'come', 'come', 'verb', '来；到来', 'to move toward or arrive at a place', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('come-example-1', 'come', 'come', 'come', 'come-sense-1', 'Can you come here for a minute?', '你能过来一会儿吗？', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('come-collocation-1', 'come', 'come', 'come', 'come-sense-1', 'come here', 'come here', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('come-collocation-2', 'come', 'come', 'come', 'come-sense-1', 'come from', 'come from', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('come-collocation-3', 'come', 'come', 'come', 'come-sense-1', 'come back', 'come back', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('come', 'come', 'come', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('come', 'come', 'come', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'could', meaning_zh = '可以；能够；可能', definition_en = 'used to talk about past ability, possibility, or polite requests', primary_part_of_speech = 'modal', phonetic_us = '/kʊd, kəd/', phonetic_uk = '/kʊd, kəd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'could';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/kʊd, kəd/' WHEN 'uk' THEN '/kʊd, kəd/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'could' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('could-sense-1', 'could', 'could', 'could', 'modal', '可以；能够；可能', 'used to talk about past ability, possibility, or polite requests', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('could-example-1', 'could', 'could', 'could', 'could-sense-1', 'Could you open the window?', '你可以打开窗户吗？', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('could-collocation-1', 'could', 'could', 'could', 'could-sense-1', 'could be', 'could be', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('could-collocation-2', 'could', 'could', 'could', 'could-sense-1', 'could you', 'could you', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('could-collocation-3', 'could', 'could', 'could', 'could-sense-1', 'could not', 'could not', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('could', 'could', 'could', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'work', meaning_zh = '工作；事情；作品', definition_en = 'a job, task, activity, or effort done to achieve something', primary_part_of_speech = 'noun', phonetic_us = '/wɝk/', phonetic_uk = '/wɜːk/', updated_at = CURRENT_TIMESTAMP WHERE id = 'work';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/wɝk/' WHEN 'uk' THEN '/wɜːk/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'work' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('work-sense-1', 'work', 'work', 'work', 'noun', '工作；事情；作品', 'a job, task, activity, or effort done to achieve something', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('work-example-1', 'work', 'work', 'work', 'work-sense-1', 'I have a lot of work today.', '我今天有很多工作。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('work-collocation-1', 'work', 'work', 'work', 'work-sense-1', 'at work', 'at work', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('work-collocation-2', 'work', 'work', 'work', 'work-sense-1', 'work on', 'work on', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('work-collocation-3', 'work', 'work', 'work', 'work-sense-1', 'go to work', 'go to work', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('work', 'work', 'work', 'work', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('work', 'work', 'work', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'use', meaning_zh = '使用；利用', definition_en = 'to do something with a tool, method, word, or resource for a purpose', primary_part_of_speech = 'verb', phonetic_us = '/juz/', phonetic_uk = '/juːz/', updated_at = CURRENT_TIMESTAMP WHERE id = 'use';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/juz/' WHEN 'uk' THEN '/juːz/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'use' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('use-sense-1', 'use', 'use', 'use', 'verb', '使用；利用', 'to do something with a tool, method, word, or resource for a purpose', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('use-example-1', 'use', 'use', 'use', 'use-sense-1', 'You can use this app every day.', '你可以每天使用这个应用。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('use-collocation-1', 'use', 'use', 'use', 'use-sense-1', 'use for', 'use for', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('use-collocation-2', 'use', 'use', 'use', 'use-sense-1', 'make use of', 'make use of', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('use-collocation-3', 'use', 'use', 'use', 'use-sense-1', 'easy to use', 'easy to use', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('use', 'use', 'use', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('use', 'use', 'use', 'study', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('use', 'use', 'use', 'work', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'than', meaning_zh = '比；超过', definition_en = 'used when comparing two people, things, amounts, or situations', primary_part_of_speech = 'conjunction', phonetic_us = '/ðæn, ðən/', phonetic_uk = '/ðæn, ðən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'than';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ðæn, ðən/' WHEN 'uk' THEN '/ðæn, ðən/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'than' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('than-sense-1', 'than', 'than', 'than', 'conjunction', '比；超过', 'used when comparing two people, things, amounts, or situations', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('than-example-1', 'than', 'than', 'than', 'than-sense-1', 'This book is easier than that one.', '这本书比那本更容易。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('than-collocation-1', 'than', 'than', 'than', 'than-sense-1', 'more than', 'more than', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('than-collocation-2', 'than', 'than', 'than', 'than-sense-1', 'better than', 'better than', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('than-collocation-3', 'than', 'than', 'than', 'than-sense-1', 'less than', 'less than', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('than', 'than', 'than', 'study', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('than', 'than', 'than', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'now', meaning_zh = '现在；此刻', definition_en = 'at the present time or immediately', primary_part_of_speech = 'adverb', phonetic_us = '/naʊ/', phonetic_uk = '/naʊ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'now';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/naʊ/' WHEN 'uk' THEN '/naʊ/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'now' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('now-sense-1', 'now', 'now', 'now', 'adverb', '现在；此刻', 'at the present time or immediately', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('now-example-1', 'now', 'now', 'now', 'now-sense-1', 'I am ready now.', '我现在准备好了。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('now-collocation-1', 'now', 'now', 'now', 'now-sense-1', 'right now', 'right now', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('now-collocation-2', 'now', 'now', 'now', 'now-sense-1', 'now and then', 'now and then', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('now-collocation-3', 'now', 'now', 'now', 'now-sense-1', 'from now on', 'from now on', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('now', 'now', 'now', 'time', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('now', 'now', 'now', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'then', meaning_zh = '然后；那时；那么', definition_en = 'at that time, after that, or as a result', primary_part_of_speech = 'adverb', phonetic_us = '/ðɛn/', phonetic_uk = '/ðen/', updated_at = CURRENT_TIMESTAMP WHERE id = 'then';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ðɛn/' WHEN 'uk' THEN '/ðen/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'then' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('then-sense-1', 'then', 'then', 'then', 'adverb', '然后；那时；那么', 'at that time, after that, or as a result', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('then-example-1', 'then', 'then', 'then', 'then-sense-1', 'Finish your homework, then watch TV.', '先完成作业，然后看电视。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('then-collocation-1', 'then', 'then', 'then', 'then-sense-1', 'and then', 'and then', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('then-collocation-2', 'then', 'then', 'then', 'then-sense-1', 'back then', 'back then', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('then-collocation-3', 'then', 'then', 'then', 'then-sense-1', 'then again', 'then again', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('then', 'then', 'then', 'time', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('then', 'then', 'then', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'also', meaning_zh = '也；同样', definition_en = 'in addition or too', primary_part_of_speech = 'adverb', phonetic_us = '/ˈɔlsoʊ/', phonetic_uk = '/ˈɔːlsəʊ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'also';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈɔlsoʊ/' WHEN 'uk' THEN '/ˈɔːlsəʊ/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'also' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('also-sense-1', 'also', 'also', 'also', 'adverb', '也；同样', 'in addition or too', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('also-example-1', 'also', 'also', 'also', 'also-sense-1', 'She speaks Spanish and also English.', '她会说西班牙语，也会说英语。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('also-collocation-1', 'also', 'also', 'also', 'also-sense-1', 'also known as', 'also known as', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('also-collocation-2', 'also', 'also', 'also', 'also-sense-1', 'also need', 'also need', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('also-collocation-3', 'also', 'also', 'also', 'also-sense-1', 'also have', 'also have', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('also', 'also', 'also', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'into', meaning_zh = '到……里面；变成', definition_en = 'to the inside of a place or toward a new state', primary_part_of_speech = 'preposition', phonetic_us = '/ˈɪntu, ˈɪntə/', phonetic_uk = '/ˈɪntuː, ˈɪntə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'into';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈɪntu, ˈɪntə/' WHEN 'uk' THEN '/ˈɪntuː, ˈɪntə/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'into' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('into-sense-1', 'into', 'into', 'into', 'preposition', '到……里面；变成', 'to the inside of a place or toward a new state', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('into-example-1', 'into', 'into', 'into', 'into-sense-1', 'Put the milk into the fridge.', '把牛奶放进冰箱。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('into-collocation-1', 'into', 'into', 'into', 'into-sense-1', 'go into', 'go into', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('into-collocation-2', 'into', 'into', 'into', 'into-sense-1', 'turn into', 'turn into', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('into-collocation-3', 'into', 'into', 'into', 'into-sense-1', 'get into', 'get into', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('into', 'into', 'into', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'only', meaning_zh = '只；仅仅；唯一地', definition_en = 'no more than, no one except, or simply', primary_part_of_speech = 'adverb', phonetic_us = '/ˈoʊnli/', phonetic_uk = '/ˈəʊnli/', updated_at = CURRENT_TIMESTAMP WHERE id = 'only';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈoʊnli/' WHEN 'uk' THEN '/ˈəʊnli/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'only' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('only-sense-1', 'only', 'only', 'only', 'adverb', '只；仅仅；唯一地', 'no more than, no one except, or simply', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('only-example-1', 'only', 'only', 'only', 'only-sense-1', 'I only need five minutes.', '我只需要五分钟。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('only-collocation-1', 'only', 'only', 'only', 'only-sense-1', 'only one', 'only one', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('only-collocation-2', 'only', 'only', 'only', 'only-sense-1', 'only if', 'only if', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('only-collocation-3', 'only', 'only', 'only', 'only-sense-1', 'not only', 'not only', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('only', 'only', 'only', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('only', 'only', 'only', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'look', meaning_zh = '看；看起来', definition_en = 'to turn your eyes toward something or to seem a particular way', primary_part_of_speech = 'verb', phonetic_us = '/lʊk/', phonetic_uk = '/lʊk/', updated_at = CURRENT_TIMESTAMP WHERE id = 'look';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/lʊk/' WHEN 'uk' THEN '/lʊk/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'look' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('look-sense-1', 'look', 'look', 'look', 'verb', '看；看起来', 'to turn your eyes toward something or to seem a particular way', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('look-example-1', 'look', 'look', 'look', 'look-sense-1', 'Look at the picture.', '看这张图片。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('look-collocation-1', 'look', 'look', 'look', 'look-sense-1', 'look at', 'look at', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('look-collocation-2', 'look', 'look', 'look', 'look-sense-1', 'look for', 'look for', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('look-collocation-3', 'look', 'look', 'look', 'look-sense-1', 'look like', 'look like', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('look', 'look', 'look', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('look', 'look', 'look', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'want', meaning_zh = '想要；需要', definition_en = 'to wish for something or to feel a need for something', primary_part_of_speech = 'verb', phonetic_us = '/wɑnt/', phonetic_uk = '/wɒnt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'want';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/wɑnt/' WHEN 'uk' THEN '/wɒnt/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'want' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('want-sense-1', 'want', 'want', 'want', 'verb', '想要；需要', 'to wish for something or to feel a need for something', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('want-example-1', 'want', 'want', 'want', 'want-sense-1', 'I want a cup of tea.', '我想要一杯茶。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('want-collocation-1', 'want', 'want', 'want', 'want-sense-1', 'want to', 'want to', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('want-collocation-2', 'want', 'want', 'want', 'want-sense-1', 'want something', 'want something', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('want-collocation-3', 'want', 'want', 'want', 'want-sense-1', 'want more', 'want more', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('want', 'want', 'want', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('want', 'want', 'want', 'emotion', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('want', 'want', 'want', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'give', meaning_zh = '给；提供；交给', definition_en = 'to let someone have something or provide something', primary_part_of_speech = 'verb', phonetic_us = '/ɡɪv/', phonetic_uk = '/ɡɪv/', updated_at = CURRENT_TIMESTAMP WHERE id = 'give';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɡɪv/' WHEN 'uk' THEN '/ɡɪv/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'give' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('give-sense-1', 'give', 'give', 'give', 'verb', '给；提供；交给', 'to let someone have something or provide something', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('give-example-1', 'give', 'give', 'give', 'give-sense-1', 'Please give me your phone number.', '请把你的电话号码给我。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('give-collocation-1', 'give', 'give', 'give', 'give-sense-1', 'give up', 'give up', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('give-collocation-2', 'give', 'give', 'give', 'give-sense-1', 'give someone something', 'give someone something', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('give-collocation-3', 'give', 'give', 'give', 'give-sense-1', 'give a talk', 'give a talk', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('give', 'give', 'give', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('give', 'give', 'give', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('give', 'give', 'give', 'work', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'first', meaning_zh = '第一的；首先', definition_en = 'coming before all others in time, order, or importance', primary_part_of_speech = 'adjective', phonetic_us = '/fɝst/', phonetic_uk = '/fɜːst/', updated_at = CURRENT_TIMESTAMP WHERE id = 'first';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/fɝst/' WHEN 'uk' THEN '/fɜːst/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'first' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('first-sense-1', 'first', 'first', 'first', 'adjective', '第一的；首先', 'coming before all others in time, order, or importance', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('first-example-1', 'first', 'first', 'first', 'first-sense-1', 'This is my first day at work.', '这是我第一天上班。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('first-collocation-1', 'first', 'first', 'first', 'first-sense-1', 'first time', 'first time', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('first-collocation-2', 'first', 'first', 'first', 'first-sense-1', 'first of all', 'first of all', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('first-collocation-3', 'first', 'first', 'first', 'first-sense-1', 'at first', 'at first', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('first', 'first', 'first', 'time', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('first', 'first', 'first', 'work', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('first', 'first', 'first', 'study', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'new', meaning_zh = '新的；刚出现的', definition_en = 'not existing before, recently made, or recently found', primary_part_of_speech = 'adjective', phonetic_us = '/nu, nju/', phonetic_uk = '/njuː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'new';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/nu, nju/' WHEN 'uk' THEN '/njuː/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'new' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('new-sense-1', 'new', 'new', 'new', 'adjective', '新的；刚出现的', 'not existing before, recently made, or recently found', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('new-example-1', 'new', 'new', 'new', 'new-sense-1', 'I bought a new notebook.', '我买了一本新笔记本。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('new-collocation-1', 'new', 'new', 'new', 'new-sense-1', 'new idea', 'new idea', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('new-collocation-2', 'new', 'new', 'new', 'new-sense-1', 'brand new', 'brand new', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('new-collocation-3', 'new', 'new', 'new', 'new-sense-1', 'new to', 'new to', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('new', 'new', 'new', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('new', 'new', 'new', 'study', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('new', 'new', 'new', 'work', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'way', meaning_zh = '方法；道路；方式', definition_en = 'a method, manner, route, or direction', primary_part_of_speech = 'noun', phonetic_us = '/weɪ/', phonetic_uk = '/weɪ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'way';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/weɪ/' WHEN 'uk' THEN '/weɪ/' ELSE phonetic END, phonetic_source = 'manual-curation', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'way' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('way-sense-1', 'way', 'way', 'way', 'noun', '方法；道路；方式', 'a method, manner, route, or direction', 'Top 100 core learner sense.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('way-example-1', 'way', 'way', 'way', 'way-sense-1', 'There is an easier way to do this.', '有一种更简单的方法来做这件事。', 'manual', 'top-100-public-content-v1', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('way-collocation-1', 'way', 'way', 'way', 'way-sense-1', 'by the way', 'by the way', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('way-collocation-2', 'way', 'way', 'way', 'way-sense-1', 'in this way', 'in this way', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('way-collocation-3', 'way', 'way', 'way', 'way-sense-1', 'find a way', 'find a way', '', '', '', 'phrase', 3, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('way', 'way', 'way', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('way', 'way', 'way', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
