-- Top 500 public vocabulary content v1, part 5.
-- Self-authored learner definitions and examples for words 281-300.
-- Phonetics are bootstrap IPA values and remain tracked for manual review.

UPDATE core_vocabulary SET word = 'least', meaning_zh = '最少；最低', definition_en = 'the smallest amount or degree', primary_part_of_speech = 'adverb', phonetic_us = '/list/', phonetic_uk = '/list/', updated_at = CURRENT_TIMESTAMP WHERE id = 'least';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/list/' WHEN 'uk' THEN '/list/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'least' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('least-sense-1', 'least', 'least', 'least', 'adverb', '最少；最低', 'the smallest amount or degree', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('least-example-1', 'least', 'least', 'least', 'least-sense-1', 'This is the least expensive option.', '这是最便宜的选择。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('least-collocation-1', 'least', 'least', 'least', 'least-sense-1', 'at least', 'at least', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('least-collocation-2', 'least', 'least', 'least', 'least-sense-1', 'least expensive', 'least expensive', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('least', 'least', 'least', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'age', meaning_zh = '年龄', definition_en = 'the number of years someone or something has lived or existed', primary_part_of_speech = 'noun', phonetic_us = '/eɪʤ/', phonetic_uk = '/eɪʤ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'age';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/eɪʤ/' WHEN 'uk' THEN '/eɪʤ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'age' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('age-sense-1', 'age', 'age', 'age', 'noun', '年龄', 'the number of years someone or something has lived or existed', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('age-example-1', 'age', 'age', 'age', 'age-sense-1', 'What is your age?', '你多大了？', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('age-collocation-1', 'age', 'age', 'age', 'age-sense-1', 'young age', 'young age', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('age-collocation-2', 'age', 'age', 'age', 'age-sense-1', 'at the age of', 'at the age of', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('age', 'age', 'age', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'low', meaning_zh = '低的；近底部的', definition_en = 'not high in position, amount, or level', primary_part_of_speech = 'adjective', phonetic_us = '/loʊ/', phonetic_uk = '/loʊ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'low';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/loʊ/' WHEN 'uk' THEN '/loʊ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'low' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('low-sense-1', 'low', 'low', 'low', 'adjective', '低的；近底部的', 'not high in position, amount, or level', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('low-example-1', 'low', 'low', 'low', 'low-sense-1', 'The table is too low.', '这张桌子太低了。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('low-collocation-1', 'low', 'low', 'low', 'low-sense-1', 'low price', 'low price', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('low-collocation-2', 'low', 'low', 'low', 'low-sense-1', 'low level', 'low level', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('low', 'low', 'low', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'speak', meaning_zh = '讲话；发言', definition_en = 'to use words to say something', primary_part_of_speech = 'verb', phonetic_us = '/spik/', phonetic_uk = '/spik/', updated_at = CURRENT_TIMESTAMP WHERE id = 'speak';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/spik/' WHEN 'uk' THEN '/spik/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'speak' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('speak-sense-1', 'speak', 'speak', 'speak', 'verb', '讲话；发言', 'to use words to say something', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('speak-example-1', 'speak', 'speak', 'speak', 'speak-sense-1', 'Please speak slowly.', '请说慢一点。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('speak-collocation-1', 'speak', 'speak', 'speak', 'speak-sense-1', 'speak English', 'speak english', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('speak-collocation-2', 'speak', 'speak', 'speak', 'speak-sense-1', 'speak to', 'speak to', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('speak', 'speak', 'speak', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'within', meaning_zh = '在……之内', definition_en = 'inside a period, area, or limit', primary_part_of_speech = 'preposition', phonetic_us = '/wɪˈθɪn/', phonetic_uk = '/wɪˈθɪn/', updated_at = CURRENT_TIMESTAMP WHERE id = 'within';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/wɪˈθɪn/' WHEN 'uk' THEN '/wɪˈθɪn/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'within' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('within-sense-1', 'within', 'within', 'within', 'preposition', '在……之内', 'inside a period, area, or limit', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('within-example-1', 'within', 'within', 'within', 'within-sense-1', 'You should reply within two days.', '你应该在两天内回复。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('within-collocation-1', 'within', 'within', 'within', 'within-sense-1', 'within a week', 'within a week', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('within-collocation-2', 'within', 'within', 'within', 'within-sense-1', 'within reach', 'within reach', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('within', 'within', 'within', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'process', meaning_zh = '过程；流程；处理', definition_en = 'a series of actions that produce a result', primary_part_of_speech = 'noun', phonetic_us = '/ˈprɔˌsɛs/', phonetic_uk = '/ˈprɔˌsɛs/', updated_at = CURRENT_TIMESTAMP WHERE id = 'process';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈprɔˌsɛs/' WHEN 'uk' THEN '/ˈprɔˌsɛs/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'process' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('process-sense-1', 'process', 'process', 'process', 'noun', '过程；流程；处理', 'a series of actions that produce a result', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('process-example-1', 'process', 'process', 'process', 'process-sense-1', 'Learning is a slow process.', '学习是一个缓慢的过程。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('process-collocation-1', 'process', 'process', 'process', 'process-sense-1', 'learning process', 'learning process', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('process-collocation-2', 'process', 'process', 'process', 'process-sense-1', 'work process', 'work process', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('process', 'process', 'process', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'public', meaning_zh = '公共的；公开的', definition_en = 'open to people in general, or connected with ordinary people', primary_part_of_speech = 'adjective', phonetic_us = '/ˈpəblɪk/', phonetic_uk = '/ˈpəblɪk/', updated_at = CURRENT_TIMESTAMP WHERE id = 'public';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈpəblɪk/' WHEN 'uk' THEN '/ˈpəblɪk/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'public' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('public-sense-1', 'public', 'public', 'public', 'adjective', '公共的；公开的', 'open to people in general, or connected with ordinary people', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('public-example-1', 'public', 'public', 'public', 'public-sense-1', 'This is a public park.', '这是一个公共公园。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('public-collocation-1', 'public', 'public', 'public', 'public-sense-1', 'public place', 'public place', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('public-collocation-2', 'public', 'public', 'public', 'public-sense-1', 'public service', 'public service', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('public', 'public', 'public', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'often', meaning_zh = '经常', definition_en = 'many times or regularly', primary_part_of_speech = 'adverb', phonetic_us = '/ˈɔfən/', phonetic_uk = '/ˈɔfən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'often';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈɔfən/' WHEN 'uk' THEN '/ˈɔfən/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'often' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('often-sense-1', 'often', 'often', 'often', 'adverb', '经常', 'many times or regularly', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('often-example-1', 'often', 'often', 'often', 'often-sense-1', 'I often walk after dinner.', '我经常晚饭后散步。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('often-collocation-1', 'often', 'often', 'often', 'often-sense-1', 'often used', 'often used', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('often-collocation-2', 'often', 'often', 'often', 'often-sense-1', 'often happens', 'often happens', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('often', 'often', 'often', 'time', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'train', meaning_zh = '火车', definition_en = 'a long vehicle that runs on tracks', primary_part_of_speech = 'noun', phonetic_us = '/treɪn/', phonetic_uk = '/treɪn/', updated_at = CURRENT_TIMESTAMP WHERE id = 'train';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/treɪn/' WHEN 'uk' THEN '/treɪn/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'train' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('train-sense-1', 'train', 'train', 'train', 'noun', '火车', 'a long vehicle that runs on tracks', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('train-example-1', 'train', 'train', 'train', 'train-sense-1', 'The train arrives at nine.', '火车九点到达。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('train-collocation-1', 'train', 'train', 'train', 'train-sense-1', 'train station', 'train station', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('train-collocation-2', 'train', 'train', 'train', 'train-sense-1', 'by train', 'by train', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('train', 'train', 'train', 'daily', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'possible', meaning_zh = '可能的', definition_en = 'able to happen or be done', primary_part_of_speech = 'adjective', phonetic_us = '/ˈpɑsəbəl/', phonetic_uk = '/ˈpɑsəbəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'possible';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈpɑsəbəl/' WHEN 'uk' THEN '/ˈpɑsəbəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'possible' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('possible-sense-1', 'possible', 'possible', 'possible', 'adjective', '可能的', 'able to happen or be done', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('possible-example-1', 'possible', 'possible', 'possible', 'possible-sense-1', 'It is possible to finish today.', '今天完成是可能的。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('possible-collocation-1', 'possible', 'possible', 'possible', 'possible-sense-1', 'if possible', 'if possible', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('possible-collocation-2', 'possible', 'possible', 'possible', 'possible-sense-1', 'as soon as possible', 'as soon as possible', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('possible', 'possible', 'possible', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'actually', meaning_zh = '实际上', definition_en = 'used to say what is really true', primary_part_of_speech = 'adverb', phonetic_us = '/ˈæˌkʧuəli/', phonetic_uk = '/ˈæˌkʧuəli/', updated_at = CURRENT_TIMESTAMP WHERE id = 'actually';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈæˌkʧuəli/' WHEN 'uk' THEN '/ˈæˌkʧuəli/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'actually' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('actually-sense-1', 'actually', 'actually', 'actually', 'adverb', '实际上', 'used to say what is really true', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('actually-example-1', 'actually', 'actually', 'actually', 'actually-sense-1', 'Actually, I agree with you.', '实际上，我同意你的看法。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('actually-collocation-1', 'actually', 'actually', 'actually', 'actually-sense-1', 'actually true', 'actually true', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('actually', 'actually', 'actually', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'rather', meaning_zh = '或多或少地；相当地；稍微', definition_en = 'fairly, or more preferably', primary_part_of_speech = 'adverb', phonetic_us = '/ˈrəðər/', phonetic_uk = '/ˈrəðər/', updated_at = CURRENT_TIMESTAMP WHERE id = 'rather';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈrəðər/' WHEN 'uk' THEN '/ˈrəðər/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'rather' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('rather-sense-1', 'rather', 'rather', 'rather', 'adverb', '或多或少地；相当地；稍微', 'fairly, or more preferably', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('rather-example-1', 'rather', 'rather', 'rather', 'rather-sense-1', 'The room is rather small.', '这个房间相当小。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('rather-collocation-1', 'rather', 'rather', 'rather', 'rather-sense-1', 'rather than', 'rather than', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('rather', 'rather', 'rather', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'view', meaning_zh = '视野', definition_en = 'what you can see, or an opinion about something', primary_part_of_speech = 'noun', phonetic_us = '/vju/', phonetic_uk = '/vju/', updated_at = CURRENT_TIMESTAMP WHERE id = 'view';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/vju/' WHEN 'uk' THEN '/vju/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'view' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('view-sense-1', 'view', 'view', 'view', 'noun', '视野', 'what you can see, or an opinion about something', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('view-example-1', 'view', 'view', 'view', 'view-sense-1', 'The room has a nice view.', '这个房间视野很好。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('view-collocation-1', 'view', 'view', 'view', 'view-sense-1', 'point of view', 'point of view', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('view-collocation-2', 'view', 'view', 'view', 'view-sense-1', 'sea view', 'sea view', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('view', 'view', 'view', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'together', meaning_zh = '在一起', definition_en = 'with each other or in one group', primary_part_of_speech = 'adverb', phonetic_us = '/təˈgɛðər/', phonetic_uk = '/təˈgɛðər/', updated_at = CURRENT_TIMESTAMP WHERE id = 'together';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/təˈgɛðər/' WHEN 'uk' THEN '/təˈgɛðər/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'together' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('together-sense-1', 'together', 'together', 'together', 'adverb', '在一起', 'with each other or in one group', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('together-example-1', 'together', 'together', 'together', 'together-sense-1', 'We studied together after class.', '下课后我们一起学习。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('together-collocation-1', 'together', 'together', 'together', 'together-sense-1', 'work together', 'work together', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('together-collocation-2', 'together', 'together', 'together', 'together-sense-1', 'come together', 'come together', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('together', 'together', 'together', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'consider', meaning_zh = '考虑；认为', definition_en = 'to think carefully about something', primary_part_of_speech = 'verb', phonetic_us = '/kənˈsɪdər/', phonetic_uk = '/kənˈsɪdər/', updated_at = CURRENT_TIMESTAMP WHERE id = 'consider';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/kənˈsɪdər/' WHEN 'uk' THEN '/kənˈsɪdər/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'consider' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('consider-sense-1', 'consider', 'consider', 'consider', 'verb', '考虑；认为', 'to think carefully about something', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('consider-example-1', 'consider', 'consider', 'consider', 'consider-sense-1', 'Please consider my suggestion.', '请考虑我的建议。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('consider-collocation-1', 'consider', 'consider', 'consider', 'consider-sense-1', 'consider carefully', 'consider carefully', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('consider-collocation-2', 'consider', 'consider', 'consider', 'consider-sense-1', 'consider doing', 'consider doing', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('consider', 'consider', 'consider', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'price', meaning_zh = '价格', definition_en = 'the amount of money asked for something', primary_part_of_speech = 'noun', phonetic_us = '/praɪs/', phonetic_uk = '/praɪs/', updated_at = CURRENT_TIMESTAMP WHERE id = 'price';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/praɪs/' WHEN 'uk' THEN '/praɪs/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'price' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('price-sense-1', 'price', 'price', 'price', 'noun', '价格', 'the amount of money asked for something', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('price-example-1', 'price', 'price', 'price', 'price-sense-1', 'The price is too high.', '价格太高了。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('price-collocation-1', 'price', 'price', 'price', 'price-sense-1', 'low price', 'low price', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('price-collocation-2', 'price', 'price', 'price', 'price-sense-1', 'price of', 'price of', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('price', 'price', 'price', 'work', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'parent', meaning_zh = '父母；家长', definition_en = 'a mother or father', primary_part_of_speech = 'noun', phonetic_us = '/ˈpɛrənt/', phonetic_uk = '/ˈpɛrənt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'parent';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈpɛrənt/' WHEN 'uk' THEN '/ˈpɛrənt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'parent' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('parent-sense-1', 'parent', 'parent', 'parent', 'noun', '父母；家长', 'a mother or father', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('parent-example-1', 'parent', 'parent', 'parent', 'parent-sense-1', 'Every parent wants the best for their child.', '每位父母都希望孩子好。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('parent-collocation-1', 'parent', 'parent', 'parent', 'parent-sense-1', 'single parent', 'single parent', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('parent-collocation-2', 'parent', 'parent', 'parent', 'parent-sense-1', 'parent meeting', 'parent meeting', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('parent', 'parent', 'parent', 'family', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'hard', meaning_zh = '难的；硬的', definition_en = 'difficult, solid, or needing a lot of effort', primary_part_of_speech = 'adjective', phonetic_us = '/hɑrd/', phonetic_uk = '/hɑrd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'hard';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/hɑrd/' WHEN 'uk' THEN '/hɑrd/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'hard' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('hard-sense-1', 'hard', 'hard', 'hard', 'adjective', '难的；硬的', 'difficult, solid, or needing a lot of effort', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('hard-example-1', 'hard', 'hard', 'hard', 'hard-sense-1', 'This test is hard.', '这个测试很难。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('hard-collocation-1', 'hard', 'hard', 'hard', 'hard-sense-1', 'hard work', 'hard work', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('hard-collocation-2', 'hard', 'hard', 'hard', 'hard-sense-1', 'hard question', 'hard question', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('hard', 'hard', 'hard', 'emotion', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'party', meaning_zh = '派对', definition_en = 'a social event where people meet and enjoy themselves', primary_part_of_speech = 'noun', phonetic_us = '/ˈpɑrti/', phonetic_uk = '/ˈpɑrti/', updated_at = CURRENT_TIMESTAMP WHERE id = 'party';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈpɑrti/' WHEN 'uk' THEN '/ˈpɑrti/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'party' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('party-sense-1', 'party', 'party', 'party', 'noun', '派对', 'a social event where people meet and enjoy themselves', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('party-example-1', 'party', 'party', 'party', 'party-sense-1', 'We had a party on Saturday.', '我们周六举办了一个聚会。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('party-collocation-1', 'party', 'party', 'party', 'party-sense-1', 'birthday party', 'birthday party', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('party-collocation-2', 'party', 'party', 'party', 'party-sense-1', 'political party', 'political party', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('party', 'party', 'party', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'local', meaning_zh = '当地的；本地的', definition_en = 'connected with a particular area or place', primary_part_of_speech = 'adjective', phonetic_us = '/ˈloʊkəl/', phonetic_uk = '/ˈloʊkəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'local';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈloʊkəl/' WHEN 'uk' THEN '/ˈloʊkəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'local' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('local-sense-1', 'local', 'local', 'local', 'adjective', '当地的；本地的', 'connected with a particular area or place', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('local-example-1', 'local', 'local', 'local', 'local-sense-1', 'I like the local food.', '我喜欢当地食物。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('local-collocation-1', 'local', 'local', 'local', 'local-sense-1', 'local community', 'local community', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('local-collocation-2', 'local', 'local', 'local', 'local-sense-1', 'local people', 'local people', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('local', 'local', 'local', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
