-- Top 500 public vocabulary content v1, part 8.
-- Self-authored learner definitions and examples for words 341-360.
-- Phonetics are bootstrap IPA values and remain tracked for manual review.

UPDATE core_vocabulary SET word = 'mind', meaning_zh = '理智；头脑', definition_en = 'the part of a person that thinks, feels, and remembers', primary_part_of_speech = 'noun', phonetic_us = '/maɪnd/', phonetic_uk = '/maɪnd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'mind';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/maɪnd/' WHEN 'uk' THEN '/maɪnd/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'mind' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('mind-sense-1', 'mind', 'mind', 'mind', 'noun', '理智；头脑', 'the part of a person that thinks, feels, and remembers', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('mind-example-1', 'mind', 'mind', 'mind', 'mind-sense-1', 'Keep your mind open.', '保持开放的心态。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('mind-collocation-1', 'mind', 'mind', 'mind', 'mind-sense-1', 'change your mind', 'change your mind', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('mind-collocation-2', 'mind', 'mind', 'mind', 'mind-sense-1', 'keep in mind', 'keep in mind', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('mind', 'mind', 'mind', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'value', meaning_zh = '价值', definition_en = 'the importance, usefulness, or worth of something', primary_part_of_speech = 'noun', phonetic_us = '/ˈvælju/', phonetic_uk = '/ˈvælju/', updated_at = CURRENT_TIMESTAMP WHERE id = 'value';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈvælju/' WHEN 'uk' THEN '/ˈvælju/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'value' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('value-sense-1', 'value', 'value', 'value', 'noun', '价值', 'the importance, usefulness, or worth of something', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('value-example-1', 'value', 'value', 'value', 'value-sense-1', 'Time has great value.', '时间很有价值。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('value-collocation-1', 'value', 'value', 'value', 'value-sense-1', 'great value', 'great value', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('value-collocation-2', 'value', 'value', 'value', 'value-sense-1', 'value of', 'value of', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('value', 'value', 'value', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'office', meaning_zh = '办公室', definition_en = 'a place where people work at desks', primary_part_of_speech = 'noun', phonetic_us = '/ˈɔfəs/', phonetic_uk = '/ˈɔfəs/', updated_at = CURRENT_TIMESTAMP WHERE id = 'office';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈɔfəs/' WHEN 'uk' THEN '/ˈɔfəs/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'office' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('office-sense-1', 'office', 'office', 'office', 'noun', '办公室', 'a place where people work at desks', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('office-example-1', 'office', 'office', 'office', 'office-sense-1', 'Our office is on the third floor.', '我们的办公室在三楼。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('office-collocation-1', 'office', 'office', 'office', 'office-sense-1', 'office worker', 'office worker', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('office-collocation-2', 'office', 'office', 'office', 'office-sense-1', 'head office', 'head office', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('office', 'office', 'office', 'work', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'record', meaning_zh = '记录', definition_en = 'written, spoken, or stored information about something', primary_part_of_speech = 'noun', phonetic_us = '/ˈrekərd/', phonetic_uk = '/ˈrekɔːd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'record';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈrekərd/' WHEN 'uk' THEN '/ˈrekɔːd/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'record' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('record-sense-1', 'record', 'record', 'record', 'noun', '记录', 'written, spoken, or stored information about something', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('record-example-1', 'record', 'record', 'record', 'record-sense-1', 'Keep a record of your progress.', '记录你的进步。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('record-collocation-1', 'record', 'record', 'record', 'record-sense-1', 'keep a record', 'keep a record', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('record-collocation-2', 'record', 'record', 'record', 'record-sense-1', 'record of', 'record of', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('record', 'record', 'record', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'stay', meaning_zh = '暂住', definition_en = 'to remain in a place or condition', primary_part_of_speech = 'verb', phonetic_us = '/steɪ/', phonetic_uk = '/steɪ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'stay';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/steɪ/' WHEN 'uk' THEN '/steɪ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'stay' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('stay-sense-1', 'stay', 'stay', 'stay', 'verb', '暂住', 'to remain in a place or condition', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('stay-example-1', 'stay', 'stay', 'stay', 'stay-sense-1', 'We will stay here tonight.', '我们今晚会住在这里。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('stay-collocation-1', 'stay', 'stay', 'stay', 'stay-sense-1', 'stay home', 'stay home', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('stay-collocation-2', 'stay', 'stay', 'stay', 'stay-sense-1', 'stay with', 'stay with', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('stay', 'stay', 'stay', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'force', meaning_zh = '强迫；力量', definition_en = 'to make someone do something, or physical strength', primary_part_of_speech = 'verb', phonetic_us = '/fɔrs/', phonetic_uk = '/fɔrs/', updated_at = CURRENT_TIMESTAMP WHERE id = 'force';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/fɔrs/' WHEN 'uk' THEN '/fɔrs/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'force' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('force-sense-1', 'force', 'force', 'force', 'verb', '强迫；力量', 'to make someone do something, or physical strength', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('force-example-1', 'force', 'force', 'force', 'force-sense-1', 'Do not force yourself to work too late.', '不要强迫自己工作太晚。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('force-collocation-1', 'force', 'force', 'force', 'force-sense-1', 'force someone to', 'force someone to', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('force-collocation-2', 'force', 'force', 'force', 'force-sense-1', 'strong force', 'strong force', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('force', 'force', 'force', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'stop', meaning_zh = '停止', definition_en = 'to end an action or movement', primary_part_of_speech = 'verb', phonetic_us = '/stɑp/', phonetic_uk = '/stɑp/', updated_at = CURRENT_TIMESTAMP WHERE id = 'stop';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/stɑp/' WHEN 'uk' THEN '/stɑp/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'stop' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('stop-sense-1', 'stop', 'stop', 'stop', 'verb', '停止', 'to end an action or movement', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('stop-example-1', 'stop', 'stop', 'stop', 'stop-sense-1', 'Please stop talking for a minute.', '请停止说话一分钟。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('stop-collocation-1', 'stop', 'stop', 'stop', 'stop-sense-1', 'stop doing', 'stop doing', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('stop-collocation-2', 'stop', 'stop', 'stop', 'stop-sense-1', 'bus stop', 'bus stop', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('stop', 'stop', 'stop', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'several', meaning_zh = '几个；若干', definition_en = 'more than two but not many', primary_part_of_speech = 'determiner', phonetic_us = '/ˈsɛvərəl/', phonetic_uk = '/ˈsɛvərəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'several';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈsɛvərəl/' WHEN 'uk' THEN '/ˈsɛvərəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'several' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('several-sense-1', 'several', 'several', 'several', 'determiner', '几个；若干', 'more than two but not many', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('several-example-1', 'several', 'several', 'several', 'several-sense-1', 'I have several questions.', '我有几个问题。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('several-collocation-1', 'several', 'several', 'several', 'several-sense-1', 'several times', 'several times', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('several-collocation-2', 'several', 'several', 'several', 'several-sense-1', 'several people', 'several people', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('several', 'several', 'several', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'light', meaning_zh = '轻的；光', definition_en = 'not heavy, or the brightness that lets you see', primary_part_of_speech = 'adjective', phonetic_us = '/laɪt/', phonetic_uk = '/laɪt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'light';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/laɪt/' WHEN 'uk' THEN '/laɪt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'light' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('light-sense-1', 'light', 'light', 'light', 'adjective', '轻的；光', 'not heavy, or the brightness that lets you see', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('light-example-1', 'light', 'light', 'light', 'light-sense-1', 'This bag is light.', '这个包很轻。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('light-collocation-1', 'light', 'light', 'light', 'light-sense-1', 'light rain', 'light rain', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('light-collocation-2', 'light', 'light', 'light', 'light-sense-1', 'light bag', 'light bag', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('light', 'light', 'light', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'develop', meaning_zh = '发展；培养；开发', definition_en = 'to grow, improve, or create over time', primary_part_of_speech = 'verb', phonetic_us = '/dɪˈvɛləp/', phonetic_uk = '/dɪˈvɛləp/', updated_at = CURRENT_TIMESTAMP WHERE id = 'develop';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/dɪˈvɛləp/' WHEN 'uk' THEN '/dɪˈvɛləp/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'develop' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('develop-sense-1', 'develop', 'develop', 'develop', 'verb', '发展；培养；开发', 'to grow, improve, or create over time', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('develop-example-1', 'develop', 'develop', 'develop', 'develop-sense-1', 'Good habits develop slowly.', '好习惯是慢慢养成的。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('develop-collocation-1', 'develop', 'develop', 'develop', 'develop-sense-1', 'develop skills', 'develop skills', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('develop-collocation-2', 'develop', 'develop', 'develop', 'develop-sense-1', 'develop a plan', 'develop a plan', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('develop', 'develop', 'develop', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'remember', meaning_zh = '回想起；记得', definition_en = 'to keep something in your mind or bring it back to your mind', primary_part_of_speech = 'verb', phonetic_us = '/rɪˈmɛmbər/', phonetic_uk = '/rɪˈmɛmbər/', updated_at = CURRENT_TIMESTAMP WHERE id = 'remember';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/rɪˈmɛmbər/' WHEN 'uk' THEN '/rɪˈmɛmbər/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'remember' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('remember-sense-1', 'remember', 'remember', 'remember', 'verb', '回想起；记得', 'to keep something in your mind or bring it back to your mind', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('remember-example-1', 'remember', 'remember', 'remember', 'remember-sense-1', 'Remember to call me tonight.', '记得今晚给我打电话。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('remember-collocation-1', 'remember', 'remember', 'remember', 'remember-sense-1', 'remember to', 'remember to', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('remember-collocation-2', 'remember', 'remember', 'remember', 'remember-sense-1', 'remember clearly', 'remember clearly', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('remember', 'remember', 'remember', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'bit', meaning_zh = '一点', definition_en = 'a small amount or piece', primary_part_of_speech = 'noun', phonetic_us = '/bɪt/', phonetic_uk = '/bɪt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'bit';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/bɪt/' WHEN 'uk' THEN '/bɪt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'bit' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('bit-sense-1', 'bit', 'bit', 'bit', 'noun', '一点', 'a small amount or piece', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('bit-example-1', 'bit', 'bit', 'bit', 'bit-sense-1', 'I need a bit more time.', '我需要多一点时间。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('bit-collocation-1', 'bit', 'bit', 'bit', 'bit-sense-1', 'a bit', 'a bit', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('bit-collocation-2', 'bit', 'bit', 'bit', 'bit-sense-1', 'little bit', 'little bit', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('bit', 'bit', 'bit', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'share', meaning_zh = '分享；共用', definition_en = 'to use, have, or give part of something with others', primary_part_of_speech = 'verb', phonetic_us = '/ʃɛr/', phonetic_uk = '/ʃɛr/', updated_at = CURRENT_TIMESTAMP WHERE id = 'share';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ʃɛr/' WHEN 'uk' THEN '/ʃɛr/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'share' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('share-sense-1', 'share', 'share', 'share', 'verb', '分享；共用', 'to use, have, or give part of something with others', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('share-example-1', 'share', 'share', 'share', 'share-sense-1', 'We share a small office.', '我们共用一个小办公室。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('share-collocation-1', 'share', 'share', 'share', 'share-sense-1', 'share with', 'share with', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('share-collocation-2', 'share', 'share', 'share', 'share-sense-1', 'share an office', 'share an office', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('share', 'share', 'share', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'real', meaning_zh = '真实的;实在的', definition_en = 'true, actual, and not imagined', primary_part_of_speech = 'adjective', phonetic_us = '/ril/', phonetic_uk = '/ril/', updated_at = CURRENT_TIMESTAMP WHERE id = 'real';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ril/' WHEN 'uk' THEN '/ril/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'real' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('real-sense-1', 'real', 'real', 'real', 'adjective', '真实的;实在的', 'true, actual, and not imagined', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('real-example-1', 'real', 'real', 'real', 'real-sense-1', 'This is a real problem.', '这是一个真实的问题。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('real-collocation-1', 'real', 'real', 'real', 'real-sense-1', 'real life', 'real life', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('real-collocation-2', 'real', 'real', 'real', 'real-sense-1', 'real problem', 'real problem', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('real', 'real', 'real', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'answer', meaning_zh = '答案；回答', definition_en = 'a reply to a question or solution to a problem', primary_part_of_speech = 'noun', phonetic_us = '/ˈænsər/', phonetic_uk = '/ˈɑːnsə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'answer';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈænsər/' WHEN 'uk' THEN '/ˈɑːnsə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'answer' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('answer-sense-1', 'answer', 'answer', 'answer', 'noun', '答案；回答', 'a reply to a question or solution to a problem', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('answer-example-1', 'answer', 'answer', 'answer', 'answer-sense-1', 'I know the answer.', '我知道答案。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('answer-collocation-1', 'answer', 'answer', 'answer', 'answer-sense-1', 'answer a question', 'answer a question', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('answer-collocation-2', 'answer', 'answer', 'answer', 'answer-sense-1', 'right answer', 'right answer', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('answer', 'answer', 'answer', 'study', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('answer', 'answer', 'answer', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'sit', meaning_zh = '坐', definition_en = 'to rest with your body supported by a chair or surface', primary_part_of_speech = 'verb', phonetic_us = '/sɪt/', phonetic_uk = '/sɪt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'sit';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/sɪt/' WHEN 'uk' THEN '/sɪt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'sit' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('sit-sense-1', 'sit', 'sit', 'sit', 'verb', '坐', 'to rest with your body supported by a chair or surface', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('sit-example-1', 'sit', 'sit', 'sit', 'sit-sense-1', 'Please sit near the window.', '请坐在窗边。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('sit-collocation-1', 'sit', 'sit', 'sit', 'sit-sense-1', 'sit down', 'sit down', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('sit-collocation-2', 'sit', 'sit', 'sit', 'sit-sense-1', 'sit next to', 'sit next to', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('sit', 'sit', 'sit', 'problem-solving', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'figure', meaning_zh = '数字；人物；图形', definition_en = 'a number, shape, or person seen in a particular way', primary_part_of_speech = 'noun', phonetic_us = '/ˈfɪɡjər/', phonetic_uk = '/ˈfɪɡə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'figure';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈfɪɡjər/' WHEN 'uk' THEN '/ˈfɪɡə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'figure' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('figure-sense-1', 'figure', 'figure', 'figure', 'noun', '数字；人物；图形', 'a number, shape, or person seen in a particular way', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('figure-example-1', 'figure', 'figure', 'figure', 'figure-sense-1', 'The sales figure is higher this month.', '这个月的销售数字更高。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('figure-collocation-1', 'figure', 'figure', 'figure', 'figure-sense-1', 'sales figure', 'sales figure', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('figure-collocation-2', 'figure', 'figure', 'figure', 'figure-sense-1', 'figure out', 'figure out', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('figure', 'figure', 'figure', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'letter', meaning_zh = '信件', definition_en = 'a written message, or a written symbol in the alphabet', primary_part_of_speech = 'noun', phonetic_us = '/ˈlɛtər/', phonetic_uk = '/ˈlɛtər/', updated_at = CURRENT_TIMESTAMP WHERE id = 'letter';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈlɛtər/' WHEN 'uk' THEN '/ˈlɛtər/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'letter' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('letter-sense-1', 'letter', 'letter', 'letter', 'noun', '信件', 'a written message, or a written symbol in the alphabet', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('letter-example-1', 'letter', 'letter', 'letter', 'letter-sense-1', 'I wrote a letter to my friend.', '我给朋友写了一封信。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('letter-collocation-1', 'letter', 'letter', 'letter', 'letter-sense-1', 'write a letter', 'write a letter', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('letter-collocation-2', 'letter', 'letter', 'letter', 'letter-sense-1', 'letter from', 'letter from', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('letter', 'letter', 'letter', 'study', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('letter', 'letter', 'letter', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'decide', meaning_zh = '决定', definition_en = 'to choose after thinking about something', primary_part_of_speech = 'verb', phonetic_us = '/ˌdɪˈsaɪd/', phonetic_uk = '/ˌdɪˈsaɪd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'decide';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˌdɪˈsaɪd/' WHEN 'uk' THEN '/ˌdɪˈsaɪd/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'decide' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('decide-sense-1', 'decide', 'decide', 'decide', 'verb', '决定', 'to choose after thinking about something', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('decide-example-1', 'decide', 'decide', 'decide', 'decide-sense-1', 'We need to decide today.', '我们需要今天决定。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('decide-collocation-1', 'decide', 'decide', 'decide', 'decide-sense-1', 'decide to', 'decide to', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('decide-collocation-2', 'decide', 'decide', 'decide', 'decide-sense-1', 'decide on', 'decide on', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('decide', 'decide', 'decide', 'thinking', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'language', meaning_zh = '语言', definition_en = 'a system of words used for communication', primary_part_of_speech = 'noun', phonetic_us = '/ˈlæŋgwɪʤ/', phonetic_uk = '/ˈlæŋgwɪʤ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'language';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈlæŋgwɪʤ/' WHEN 'uk' THEN '/ˈlæŋgwɪʤ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'language' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('language-sense-1', 'language', 'language', 'language', 'noun', '语言', 'a system of words used for communication', 'Self-authored learner sense; pending review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('language-example-1', 'language', 'language', 'language', 'language-sense-1', 'English is a useful language.', '英语是一门有用的语言。', 'manual', 'top-500-public-content-v1-self-authored', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('language-collocation-1', 'language', 'language', 'language', 'language-sense-1', 'English language', 'english language', '', '', '', 'phrase', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_collocations (id, vocabulary_id, word, normalized_word, sense_id, phrase, normalized_phrase, meaning_zh, example_en, example_zh, collocation_type, sort_order, publish_status, updated_at) VALUES ('language-collocation-2', 'language', 'language', 'language', 'language-sense-1', 'language learning', 'language learning', '', '', '', 'phrase', 2, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, phrase = excluded.phrase, normalized_phrase = excluded.normalized_phrase, meaning_zh = excluded.meaning_zh, example_en = excluded.example_en, example_zh = excluded.example_zh, collocation_type = excluded.collocation_type, sort_order = excluded.sort_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('language', 'language', 'language', 'study', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('language', 'language', 'language', 'communication', 80, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
