-- Top 3000 public vocabulary content v1, part 18.
-- Learner bootstrap content for words 1341-1360.
-- Definitions are WordNet-assisted where needed; examples are WordNet examples or generated learner sentences.
-- Phonetics are bootstrap IPA values and remain tracked for manual review.

UPDATE core_vocabulary SET word = 'award', meaning_zh = '奖', definition_en = 'give, especially as an honor or reward', primary_part_of_speech = 'verb', phonetic_us = '/əwˈɔrd/', phonetic_uk = '/əwˈɔːd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'award';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/əwˈɔrd/' WHEN 'uk' THEN '/əwˈɔːd/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'award' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('award-sense-1', 'award', 'award', 'award', 'verb', '奖', 'give, especially as an honor or reward', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('award-example-1', 'award', 'award', 'award', 'award-sense-1', 'They tried to award carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('award', 'award', 'award', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'coach', meaning_zh = '教练', definition_en = 'a person who gives private instruction (as in singing, acting, and similar things)', primary_part_of_speech = 'noun', phonetic_us = '/koʊtʃ/', phonetic_uk = '/koʊtʃ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'coach';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/koʊtʃ/' WHEN 'uk' THEN '/koʊtʃ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'coach' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('coach-sense-1', 'coach', 'coach', 'coach', 'noun', '教练', 'a person who gives private instruction (as in singing, acting, and similar things)', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('coach-example-1', 'coach', 'coach', 'coach', 'coach-sense-1', 'The coach was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('coach', 'coach', 'coach', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'experiment', meaning_zh = '实验', definition_en = 'a venture at something new or different', primary_part_of_speech = 'noun', phonetic_us = '/ɪkspˈɛrəmənt/', phonetic_uk = '/ɪkspˈeəəmənt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'experiment';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɪkspˈɛrəmənt/' WHEN 'uk' THEN '/ɪkspˈeəəmənt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'experiment' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('experiment-sense-1', 'experiment', 'experiment', 'experiment', 'noun', '实验', 'a venture at something new or different', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('experiment-example-1', 'experiment', 'experiment', 'experiment', 'experiment-sense-1', 'As an experiment he decided to grow a beard', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('experiment', 'experiment', 'experiment', 'work', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'consideration', meaning_zh = '考虑', definition_en = 'information that should be kept in mind when making a decision', primary_part_of_speech = 'noun', phonetic_us = '/kənsˌɪdɚˈeɪʃən/', phonetic_uk = '/kənsˌɪdəˈeɪʃən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'consideration';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/kənsˌɪdɚˈeɪʃən/' WHEN 'uk' THEN '/kənsˌɪdəˈeɪʃən/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'consideration' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('consideration-sense-1', 'consideration', 'consideration', 'consideration', 'noun', '考虑', 'information that should be kept in mind when making a decision', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('consideration-example-1', 'consideration', 'consideration', 'consideration', 'consideration-sense-1', 'Another consideration is the time it would take', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('consideration', 'consideration', 'consideration', 'study', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'strange', meaning_zh = '奇怪的', definition_en = 'being definitely out of the ordinary and unexpected; slightly odd or even a bit weird', primary_part_of_speech = 'adjective', phonetic_us = '/streɪndʒ/', phonetic_uk = '/streɪndʒ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'strange';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/streɪndʒ/' WHEN 'uk' THEN '/streɪndʒ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'strange' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('strange-sense-1', 'strange', 'strange', 'strange', 'adjective', '奇怪的', 'being definitely out of the ordinary and unexpected; slightly odd or even a bit weird', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('strange-example-1', 'strange', 'strange', 'strange', 'strange-sense-1', 'A strange exaltation that was indefinable', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('strange', 'strange', 'strange', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'code', meaning_zh = '密码', definition_en = '(computer science) the symbolic arrangement of data or instructions in a computer program or the set of such instructions', primary_part_of_speech = 'noun', phonetic_us = '/koʊd/', phonetic_uk = '/koʊd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'code';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/koʊd/' WHEN 'uk' THEN '/koʊd/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'code' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('code-sense-1', 'code', 'code', 'code', 'noun', '密码', '(computer science) the symbolic arrangement of data or instructions in a computer program or the set of such instructions', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('code-example-1', 'code', 'code', 'code', 'code-sense-1', 'The code was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('code', 'code', 'code', 'study', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('code', 'code', 'code', 'communication', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'possibly', meaning_zh = '可能地', definition_en = 'by chance', primary_part_of_speech = 'adverb', phonetic_us = '/ˈpɑsəbliː/', phonetic_uk = '/ˈpɑsəbliː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'possibly';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈpɑsəbliː/' WHEN 'uk' THEN '/ˈpɑsəbliː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'possibly' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('possibly-sense-1', 'possibly', 'possibly', 'possibly', 'adverb', '可能地', 'by chance', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('possibly-example-1', 'possibly', 'possibly', 'possibly', 'possibly-sense-1', 'We may possibly run into them at the concert', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('possibly', 'possibly', 'possibly', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'threat', meaning_zh = '威胁', definition_en = 'something that is a source of danger', primary_part_of_speech = 'noun', phonetic_us = '/θrɛt/', phonetic_uk = '/θrɛt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'threat';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/θrɛt/' WHEN 'uk' THEN '/θrɛt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'threat' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('threat-sense-1', 'threat', 'threat', 'threat', 'noun', '威胁', 'something that is a source of danger', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('threat-example-1', 'threat', 'threat', 'threat', 'threat-sense-1', 'Earthquakes are a constant threat in Japan', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('threat', 'threat', 'threat', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'accident', meaning_zh = '事故', definition_en = 'an unfortunate mishap; especially one causing damage or injury', primary_part_of_speech = 'noun', phonetic_us = '/ˈæksədənt/', phonetic_uk = '/ˈæksədənt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'accident';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈæksədənt/' WHEN 'uk' THEN '/ˈæksədənt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'accident' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('accident-sense-1', 'accident', 'accident', 'accident', 'noun', '事故', 'an unfortunate mishap; especially one causing damage or injury', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('accident-example-1', 'accident', 'accident', 'accident', 'accident-sense-1', 'The accident was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('accident', 'accident', 'accident', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'impossible', meaning_zh = '不可能的', definition_en = 'not capable of occurring or being accomplished or dealt with', primary_part_of_speech = 'adjective', phonetic_us = '/ˌɪmpˈɑsəbəl/', phonetic_uk = '/ˌɪmpˈɑsəbəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'impossible';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˌɪmpˈɑsəbəl/' WHEN 'uk' THEN '/ˌɪmpˈɑsəbəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'impossible' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('impossible-sense-1', 'impossible', 'impossible', 'impossible', 'adjective', '不可能的', 'not capable of occurring or being accomplished or dealt with', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('impossible-example-1', 'impossible', 'impossible', 'impossible', 'impossible-sense-1', 'This is an impossible example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('impossible', 'impossible', 'impossible', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'revenue', meaning_zh = '收入', definition_en = 'the entire amount of income before any deductions are made', primary_part_of_speech = 'noun', phonetic_us = '/ˈrɛvənˌuː/', phonetic_uk = '/ˈrɛvənˌuː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'revenue';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈrɛvənˌuː/' WHEN 'uk' THEN '/ˈrɛvənˌuː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'revenue' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('revenue-sense-1', 'revenue', 'revenue', 'revenue', 'noun', '收入', 'the entire amount of income before any deductions are made', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('revenue-example-1', 'revenue', 'revenue', 'revenue', 'revenue-sense-1', 'The revenue was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('revenue', 'revenue', 'revenue', 'work', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'enable', meaning_zh = '使能够', definition_en = 'render capable or able for some task', primary_part_of_speech = 'verb', phonetic_us = '/ɛnˈeɪbəl/', phonetic_uk = '/ɛnˈeɪbəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'enable';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɛnˈeɪbəl/' WHEN 'uk' THEN '/ɛnˈeɪbəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'enable' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('enable-sense-1', 'enable', 'enable', 'enable', 'verb', '使能够', 'render capable or able for some task', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('enable-example-1', 'enable', 'enable', 'enable', 'enable-sense-1', 'This skill will enable you to find a job on Wall Street', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('enable', 'enable', 'enable', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'afraid', meaning_zh = '害怕的', definition_en = 'filled with fear or apprehension', primary_part_of_speech = 'adjective', phonetic_us = '/əfrˈeɪd/', phonetic_uk = '/əfrˈeɪd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'afraid';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/əfrˈeɪd/' WHEN 'uk' THEN '/əfrˈeɪd/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'afraid' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('afraid-sense-1', 'afraid', 'afraid', 'afraid', 'adjective', '害怕的', 'filled with fear or apprehension', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('afraid-example-1', 'afraid', 'afraid', 'afraid', 'afraid-sense-1', 'Afraid even to turn his head', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('afraid', 'afraid', 'afraid', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'active', meaning_zh = '积极的；活跃的', definition_en = 'characterized by energetic activity', primary_part_of_speech = 'adjective', phonetic_us = '/ˈæktɪv/', phonetic_uk = '/ˈæktɪv/', updated_at = CURRENT_TIMESTAMP WHERE id = 'active';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈæktɪv/' WHEN 'uk' THEN '/ˈæktɪv/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'active' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('active-sense-1', 'active', 'active', 'active', 'adjective', '积极的；活跃的', 'characterized by energetic activity', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('active-example-1', 'active', 'active', 'active', 'active-sense-1', 'Active as a gazelle', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('active', 'active', 'active', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'conclude', meaning_zh = '结束；作结论', definition_en = 'come to a close', primary_part_of_speech = 'verb', phonetic_us = '/kənklˈuːd/', phonetic_uk = '/kənklˈuːd/', updated_at = CURRENT_TIMESTAMP WHERE id = 'conclude';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/kənklˈuːd/' WHEN 'uk' THEN '/kənklˈuːd/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'conclude' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('conclude-sense-1', 'conclude', 'conclude', 'conclude', 'verb', '结束；作结论', 'come to a close', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('conclude-example-1', 'conclude', 'conclude', 'conclude', 'conclude-sense-1', 'They tried to conclude carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('conclude', 'conclude', 'conclude', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'religious', meaning_zh = '宗教信仰的', definition_en = 'having or showing belief in and reverence for a deity', primary_part_of_speech = 'adjective', phonetic_us = '/rɪlˈɪdʒəs/', phonetic_uk = '/rɪlˈɪdʒəs/', updated_at = CURRENT_TIMESTAMP WHERE id = 'religious';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/rɪlˈɪdʒəs/' WHEN 'uk' THEN '/rɪlˈɪdʒəs/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'religious' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('religious-sense-1', 'religious', 'religious', 'religious', 'adjective', '宗教信仰的', 'having or showing belief in and reverence for a deity', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('religious-example-1', 'religious', 'religious', 'religious', 'religious-sense-1', 'This is a religious example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('religious', 'religious', 'religious', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'cancer', meaning_zh = '癌症', definition_en = 'any malignant growth or tumor caused by abnormal and uncontrolled cell division; it may spread to other parts of the body through the lymphatic system or the blood stream', primary_part_of_speech = 'noun', phonetic_us = '/ˈkænsɚ/', phonetic_uk = '/ˈkænsə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'cancer';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈkænsɚ/' WHEN 'uk' THEN '/ˈkænsə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'cancer' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('cancer-sense-1', 'cancer', 'cancer', 'cancer', 'noun', '癌症', 'any malignant growth or tumor caused by abnormal and uncontrolled cell division; it may spread to other parts of the body through the lymphatic system or the blood stream', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('cancer-example-1', 'cancer', 'cancer', 'cancer', 'cancer-sense-1', 'The cancer was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('cancer', 'cancer', 'cancer', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'convince', meaning_zh = '说服;使确信', definition_en = 'make (someone) agree, understand, or realize the truth or validity of something', primary_part_of_speech = 'verb', phonetic_us = '/kənvˈɪns/', phonetic_uk = '/kənvˈɪns/', updated_at = CURRENT_TIMESTAMP WHERE id = 'convince';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/kənvˈɪns/' WHEN 'uk' THEN '/kənvˈɪns/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'convince' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('convince-sense-1', 'convince', 'convince', 'convince', 'verb', '说服;使确信', 'make (someone) agree, understand, or realize the truth or validity of something', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('convince-example-1', 'convince', 'convince', 'convince', 'convince-sense-1', 'He had finally convinced several customers of the advantages of his product', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('convince', 'convince', 'convince', 'communication', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'vary', meaning_zh = '使变化', definition_en = 'become different in some particular way, without permanently losing one''s or its former characteristics or essence', primary_part_of_speech = 'verb', phonetic_us = '/ˈvɛriː/', phonetic_uk = '/ˈveəiː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'vary';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈvɛriː/' WHEN 'uk' THEN '/ˈveəiː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'vary' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('vary-sense-1', 'vary', 'vary', 'vary', 'verb', '使变化', 'become different in some particular way, without permanently losing one''s or its former characteristics or essence', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('vary-example-1', 'vary', 'vary', 'vary', 'vary-sense-1', 'They tried to vary carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('vary', 'vary', 'vary', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'environmental', meaning_zh = '自然环境的', definition_en = 'of or relating to the external conditions or surroundings', primary_part_of_speech = 'adjective', phonetic_us = '/ɪnvˌaɪrənmˈɛntəl/', phonetic_uk = '/ɪnvˌaɪəənmˈɛntəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'environmental';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɪnvˌaɪrənmˈɛntəl/' WHEN 'uk' THEN '/ɪnvˌaɪəənmˈɛntəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'environmental' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('environmental-sense-1', 'environmental', 'environmental', 'environmental', 'adjective', '自然环境的', 'of or relating to the external conditions or surroundings', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('environmental-example-1', 'environmental', 'environmental', 'environmental', 'environmental-sense-1', 'This is an environmental example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('environmental', 'environmental', 'environmental', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
