-- Top 3000 public vocabulary content v1, part 39.
-- Learner bootstrap content for words 1761-1780.
-- Definitions are WordNet-assisted where needed; examples are WordNet examples or generated learner sentences.
-- Phonetics are bootstrap IPA values and remain tracked for manual review.

UPDATE core_vocabulary SET word = 'medicine', meaning_zh = '药物；医学', definition_en = '(medicine) something that treats or prevents or alleviates the symptoms of disease', primary_part_of_speech = 'noun', phonetic_us = '/ˈmɛdəsən/', phonetic_uk = '/ˈmɛdəsən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'medicine';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈmɛdəsən/' WHEN 'uk' THEN '/ˈmɛdəsən/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'medicine' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('medicine-sense-1', 'medicine', 'medicine', 'medicine', 'noun', '药物；医学', '(medicine) something that treats or prevents or alleviates the symptoms of disease', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('medicine-example-1', 'medicine', 'medicine', 'medicine', 'medicine-sense-1', 'The medicine was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('medicine', 'medicine', 'medicine', 'daily', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'professor', meaning_zh = '教授', definition_en = 'someone who is a member of the faculty at a college or university', primary_part_of_speech = 'noun', phonetic_us = '/prəfˈɛsɚ/', phonetic_uk = '/prəfˈɛsə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'professor';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/prəfˈɛsɚ/' WHEN 'uk' THEN '/prəfˈɛsə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'professor' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('professor-sense-1', 'professor', 'professor', 'professor', 'noun', '教授', 'someone who is a member of the faculty at a college or university', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('professor-example-1', 'professor', 'professor', 'professor', 'professor-sense-1', 'The professor was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('professor', 'professor', 'professor', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'rare', meaning_zh = '罕见的', definition_en = 'recurring only at long intervals', primary_part_of_speech = 'adjective', phonetic_us = '/rɛr/', phonetic_uk = '/reə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'rare';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/rɛr/' WHEN 'uk' THEN '/reə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'rare' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('rare-sense-1', 'rare', 'rare', 'rare', 'adjective', '罕见的', 'recurring only at long intervals', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('rare-example-1', 'rare', 'rare', 'rare', 'rare-sense-1', 'Total eclipses are rare events', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('rare', 'rare', 'rare', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'intention', meaning_zh = '意图，目的，打算', definition_en = 'an anticipated outcome that is intended or that guides your planned actions', primary_part_of_speech = 'noun', phonetic_us = '/ˌɪntˈɛntʃən/', phonetic_uk = '/ˌɪntˈɛntʃən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'intention';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˌɪntˈɛntʃən/' WHEN 'uk' THEN '/ˌɪntˈɛntʃən/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'intention' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('intention-sense-1', 'intention', 'intention', 'intention', 'noun', '意图，目的，打算', 'an anticipated outcome that is intended or that guides your planned actions', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('intention-example-1', 'intention', 'intention', 'intention', 'intention-sense-1', 'His intent was to provide a new translation', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('intention', 'intention', 'intention', 'study', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'dozen', meaning_zh = '一打，十二个', definition_en = 'the cardinal number that is the sum of eleven and one', primary_part_of_speech = 'noun', phonetic_us = '/ˈdʌzən/', phonetic_uk = '/ˈdʌzən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'dozen';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈdʌzən/' WHEN 'uk' THEN '/ˈdʌzən/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'dozen' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('dozen-sense-1', 'dozen', 'dozen', 'dozen', 'noun', '一打，十二个', 'the cardinal number that is the sum of eleven and one', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('dozen-example-1', 'dozen', 'dozen', 'dozen', 'dozen-sense-1', 'The dozen was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('dozen', 'dozen', 'dozen', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'settlement', meaning_zh = '解决，和解', definition_en = 'something settled or resolved; the outcome of decision making', primary_part_of_speech = 'noun', phonetic_us = '/ˈsɛtəlmənt/', phonetic_uk = '/ˈsɛtəlmənt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'settlement';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈsɛtəlmənt/' WHEN 'uk' THEN '/ˈsɛtəlmənt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'settlement' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('settlement-sense-1', 'settlement', 'settlement', 'settlement', 'noun', '解决，和解', 'something settled or resolved; the outcome of decision making', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('settlement-example-1', 'settlement', 'settlement', 'settlement', 'settlement-sense-1', 'They finally reached a settlement with the union', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('settlement', 'settlement', 'settlement', 'study', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'gap', meaning_zh = '间隔，间隙', definition_en = 'a narrow opening', primary_part_of_speech = 'noun', phonetic_us = '/ɡæp/', phonetic_uk = '/ɡæp/', updated_at = CURRENT_TIMESTAMP WHERE id = 'gap';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɡæp/' WHEN 'uk' THEN '/ɡæp/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'gap' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('gap-sense-1', 'gap', 'gap', 'gap', 'noun', '间隔，间隙', 'a narrow opening', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('gap-example-1', 'gap', 'gap', 'gap', 'gap-sense-1', 'The gap was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('gap', 'gap', 'gap', 'daily', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'widely', meaning_zh = '广泛地', definition_en = 'to a great degree', primary_part_of_speech = 'adverb', phonetic_us = '/ˈwaɪdliː/', phonetic_uk = '/ˈwaɪdliː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'widely';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈwaɪdliː/' WHEN 'uk' THEN '/ˈwaɪdliː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'widely' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('widely-sense-1', 'widely', 'widely', 'widely', 'adverb', '广泛地', 'to a great degree', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('widely-example-1', 'widely', 'widely', 'widely', 'widely-sense-1', 'Her work is widely known', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('widely', 'widely', 'widely', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'minimum', meaning_zh = '最低值，最小量', definition_en = 'the smallest possible quantity', primary_part_of_speech = 'noun', phonetic_us = '/ˈmɪnəməm/', phonetic_uk = '/ˈmɪnəməm/', updated_at = CURRENT_TIMESTAMP WHERE id = 'minimum';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈmɪnəməm/' WHEN 'uk' THEN '/ˈmɪnəməm/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'minimum' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('minimum-sense-1', 'minimum', 'minimum', 'minimum', 'noun', '最低值，最小量', 'the smallest possible quantity', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('minimum-example-1', 'minimum', 'minimum', 'minimum', 'minimum-sense-1', 'The minimum was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('minimum', 'minimum', 'minimum', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'northern', meaning_zh = '在北方的；向北方的', definition_en = 'in or characteristic of a region of the United States north of (approximately) the Mason-Dixon line', primary_part_of_speech = 'adjective', phonetic_us = '/ˈnɔrðɚn/', phonetic_uk = '/ˈnɔːðən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'northern';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈnɔrðɚn/' WHEN 'uk' THEN '/ˈnɔːðən/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'northern' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('northern-sense-1', 'northern', 'northern', 'northern', 'adjective', '在北方的；向北方的', 'in or characteristic of a region of the United States north of (approximately) the Mason-Dixon line', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('northern-example-1', 'northern', 'northern', 'northern', 'northern-sense-1', 'This is a northern example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('northern', 'northern', 'northern', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'estate', meaning_zh = '地产，私有土地', definition_en = 'extensive landed property (especially in the country) retained by the owner for his own use', primary_part_of_speech = 'noun', phonetic_us = '/ɪstˈeɪt/', phonetic_uk = '/ɪstˈeɪt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'estate';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɪstˈeɪt/' WHEN 'uk' THEN '/ɪstˈeɪt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'estate' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('estate-sense-1', 'estate', 'estate', 'estate', 'noun', '地产，私有土地', 'extensive landed property (especially in the country) retained by the owner for his own use', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('estate-example-1', 'estate', 'estate', 'estate', 'estate-sense-1', 'The family owned a large estate on Long Island', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('estate', 'estate', 'estate', 'work', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'equally', meaning_zh = '相等地，同样', definition_en = 'to the same degree (often followed by ''as'')', primary_part_of_speech = 'adverb', phonetic_us = '/ˈiːkwəliː/', phonetic_uk = '/ˈiːkwəliː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'equally';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈiːkwəliː/' WHEN 'uk' THEN '/ˈiːkwəliː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'equally' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('equally-sense-1', 'equally', 'equally', 'equally', 'adverb', '相等地，同样', 'to the same degree (often followed by ''as'')', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('equally-example-1', 'equally', 'equally', 'equally', 'equally-sense-1', 'They were equally beautiful', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('equally', 'equally', 'equally', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'expose', meaning_zh = '暴露，揭露', definition_en = 'make known to the public information that was previously known only to a few people or that was meant to be kept a secret', primary_part_of_speech = 'verb', phonetic_us = '/ɪkspˈoʊz/', phonetic_uk = '/ɪkspˈoʊz/', updated_at = CURRENT_TIMESTAMP WHERE id = 'expose';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɪkspˈoʊz/' WHEN 'uk' THEN '/ɪkspˈoʊz/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'expose' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('expose-sense-1', 'expose', 'expose', 'expose', 'verb', '暴露，揭露', 'make known to the public information that was previously known only to a few people or that was meant to be kept a secret', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('expose-example-1', 'expose', 'expose', 'expose', 'expose-sense-1', 'They tried to expose carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('expose', 'expose', 'expose', 'communication', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'alive', meaning_zh = '活着的；在世的', definition_en = 'possessing life', primary_part_of_speech = 'adjective', phonetic_us = '/əlˈaɪv/', phonetic_uk = '/əlˈaɪv/', updated_at = CURRENT_TIMESTAMP WHERE id = 'alive';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/əlˈaɪv/' WHEN 'uk' THEN '/əlˈaɪv/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'alive' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('alive-sense-1', 'alive', 'alive', 'alive', 'adjective', '活着的；在世的', 'possessing life', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('alive-example-1', 'alive', 'alive', 'alive', 'alive-sense-1', 'The happiest person alive', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('alive', 'alive', 'alive', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'shut', meaning_zh = '关闭', definition_en = 'move so that an opening or passage is obstructed; make shut', primary_part_of_speech = 'verb', phonetic_us = '/ʃʌt/', phonetic_uk = '/ʃʌt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'shut';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ʃʌt/' WHEN 'uk' THEN '/ʃʌt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'shut' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('shut-sense-1', 'shut', 'shut', 'shut', 'verb', '关闭', 'move so that an opening or passage is obstructed; make shut', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('shut-example-1', 'shut', 'shut', 'shut', 'shut-sense-1', 'They tried to shut carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('shut', 'shut', 'shut', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'victory', meaning_zh = '胜利', definition_en = 'a successful ending of a struggle or contest', primary_part_of_speech = 'noun', phonetic_us = '/ˈvɪktɚiː/', phonetic_uk = '/ˈvɪktəiː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'victory';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈvɪktɚiː/' WHEN 'uk' THEN '/ˈvɪktəiː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'victory' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('victory-sense-1', 'victory', 'victory', 'victory', 'noun', '胜利', 'a successful ending of a struggle or contest', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('victory-example-1', 'victory', 'victory', 'victory', 'victory-sense-1', 'The general always gets credit for his army''s victory', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('victory', 'victory', 'victory', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'resolve', meaning_zh = '解决', definition_en = 'understand the meaning of', primary_part_of_speech = 'verb', phonetic_us = '/riːzˈɑlv/', phonetic_uk = '/riːzˈɑlv/', updated_at = CURRENT_TIMESTAMP WHERE id = 'resolve';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/riːzˈɑlv/' WHEN 'uk' THEN '/riːzˈɑlv/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'resolve' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('resolve-sense-1', 'resolve', 'resolve', 'resolve', 'verb', '解决', 'understand the meaning of', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('resolve-example-1', 'resolve', 'resolve', 'resolve', 'resolve-sense-1', 'They tried to resolve carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('resolve', 'resolve', 'resolve', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'critic', meaning_zh = '评论家', definition_en = 'a person who is professionally engaged in the analysis and interpretation of works of art', primary_part_of_speech = 'noun', phonetic_us = '/ˈkrɪtɪk/', phonetic_uk = '/ˈkrɪtɪk/', updated_at = CURRENT_TIMESTAMP WHERE id = 'critic';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈkrɪtɪk/' WHEN 'uk' THEN '/ˈkrɪtɪk/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'critic' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('critic-sense-1', 'critic', 'critic', 'critic', 'noun', '评论家', 'a person who is professionally engaged in the analysis and interpretation of works of art', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('critic-example-1', 'critic', 'critic', 'critic', 'critic-sense-1', 'The critic was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('critic', 'critic', 'critic', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'variable', meaning_zh = '可变的', definition_en = 'liable to or capable of change', primary_part_of_speech = 'adjective', phonetic_us = '/ˈvɛriːəbəl/', phonetic_uk = '/ˈveəiːəbəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'variable';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈvɛriːəbəl/' WHEN 'uk' THEN '/ˈveəiːəbəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'variable' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('variable-sense-1', 'variable', 'variable', 'variable', 'adjective', '可变的', 'liable to or capable of change', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('variable-example-1', 'variable', 'variable', 'variable', 'variable-sense-1', 'Rainfall in the tropics is notoriously variable', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('variable', 'variable', 'variable', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'enormous', meaning_zh = '巨大的', definition_en = 'extraordinarily large in size or extent or amount or power or degree', primary_part_of_speech = 'adjective', phonetic_us = '/ɪnˈɔrməs/', phonetic_uk = '/ɪnˈɔːməs/', updated_at = CURRENT_TIMESTAMP WHERE id = 'enormous';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɪnˈɔrməs/' WHEN 'uk' THEN '/ɪnˈɔːməs/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'enormous' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('enormous-sense-1', 'enormous', 'enormous', 'enormous', 'adjective', '巨大的', 'extraordinarily large in size or extent or amount or power or degree', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('enormous-example-1', 'enormous', 'enormous', 'enormous', 'enormous-sense-1', 'This is an enormous example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('enormous', 'enormous', 'enormous', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
