-- Top 3000 public vocabulary content v1, part 67.
-- Learner bootstrap content for words 2321-2340.
-- Definitions are WordNet-assisted where needed; examples are WordNet examples or generated learner sentences.
-- Phonetics are bootstrap IPA values and remain tracked for manual review.

UPDATE core_vocabulary SET word = 'recovery', meaning_zh = '恢复', definition_en = 'gradual healing (through rest) after sickness or injury', primary_part_of_speech = 'noun', phonetic_us = '/rɪkˈʌvriː/', phonetic_uk = '/rɪkˈʌvriː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'recovery';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/rɪkˈʌvriː/' WHEN 'uk' THEN '/rɪkˈʌvriː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'recovery' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('recovery-sense-1', 'recovery', 'recovery', 'recovery', 'noun', '恢复', 'gradual healing (through rest) after sickness or injury', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('recovery-example-1', 'recovery', 'recovery', 'recovery', 'recovery-sense-1', 'The recovery was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('recovery', 'recovery', 'recovery', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'seal', meaning_zh = '密封', definition_en = 'make tight; secure against leakage', primary_part_of_speech = 'verb', phonetic_us = '/siːl/', phonetic_uk = '/siːl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'seal';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/siːl/' WHEN 'uk' THEN '/siːl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'seal' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('seal-sense-1', 'seal', 'seal', 'seal', 'verb', '密封', 'make tight; secure against leakage', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('seal-example-1', 'seal', 'seal', 'seal', 'seal-sense-1', 'They tried to seal carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('seal', 'seal', 'seal', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'tube', meaning_zh = '管子', definition_en = 'a hollow cylindrical shape', primary_part_of_speech = 'noun', phonetic_us = '/tuːb/', phonetic_uk = '/tuːb/', updated_at = CURRENT_TIMESTAMP WHERE id = 'tube';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/tuːb/' WHEN 'uk' THEN '/tuːb/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'tube' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('tube-sense-1', 'tube', 'tube', 'tube', 'noun', '管子', 'a hollow cylindrical shape', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('tube-example-1', 'tube', 'tube', 'tube', 'tube-sense-1', 'The tube was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('tube', 'tube', 'tube', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'tower', meaning_zh = '塔', definition_en = 'a structure taller than its diameter; can stand alone or be attached to a larger building', primary_part_of_speech = 'noun', phonetic_us = '/ˈtaʊɚ/', phonetic_uk = '/ˈtaʊə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'tower';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈtaʊɚ/' WHEN 'uk' THEN '/ˈtaʊə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'tower' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('tower-sense-1', 'tower', 'tower', 'tower', 'noun', '塔', 'a structure taller than its diameter; can stand alone or be attached to a larger building', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('tower-example-1', 'tower', 'tower', 'tower', 'tower-sense-1', 'The tower was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('tower', 'tower', 'tower', 'daily', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'characterize', meaning_zh = '描绘...的特征', definition_en = 'be characteristic of', primary_part_of_speech = 'verb', phonetic_us = '/ˈkɛrəktɚˌaɪz/', phonetic_uk = '/ˈkeəəktəˌaɪz/', updated_at = CURRENT_TIMESTAMP WHERE id = 'characterize';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈkɛrəktɚˌaɪz/' WHEN 'uk' THEN '/ˈkeəəktəˌaɪz/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'characterize' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('characterize-sense-1', 'characterize', 'characterize', 'characterize', 'verb', '描绘...的特征', 'be characteristic of', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('characterize-example-1', 'characterize', 'characterize', 'characterize', 'characterize-sense-1', 'What characterizes a Venetian painting?', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('characterize', 'characterize', 'characterize', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'specify', meaning_zh = '具体说明', definition_en = 'determine the essential quality of', primary_part_of_speech = 'verb', phonetic_us = '/ˈspɛsəfˌaɪ/', phonetic_uk = '/ˈspɛsəfˌaɪ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'specify';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈspɛsəfˌaɪ/' WHEN 'uk' THEN '/ˈspɛsəfˌaɪ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'specify' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('specify-sense-1', 'specify', 'specify', 'specify', 'verb', '具体说明', 'determine the essential quality of', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('specify-example-1', 'specify', 'specify', 'specify', 'specify-sense-1', 'They tried to specify carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('specify', 'specify', 'specify', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'exact', meaning_zh = '准确的，精确的，精密的', definition_en = '(of ideas, images, representations, expressions) characterized by perfect conformity to fact or truth ; strictly correct', primary_part_of_speech = 'adjective', phonetic_us = '/ɪɡzˈækt/', phonetic_uk = '/ɪɡzˈækt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'exact';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɪɡzˈækt/' WHEN 'uk' THEN '/ɪɡzˈækt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'exact' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('exact-sense-1', 'exact', 'exact', 'exact', 'adjective', '准确的，精确的，精密的', '(of ideas, images, representations, expressions) characterized by perfect conformity to fact or truth ; strictly correct', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('exact-example-1', 'exact', 'exact', 'exact', 'exact-sense-1', 'This is an exact example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('exact', 'exact', 'exact', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'spin', meaning_zh = '旋转', definition_en = 'revolve quickly and repeatedly around one''s own axis', primary_part_of_speech = 'verb', phonetic_us = '/spɪn/', phonetic_uk = '/spɪn/', updated_at = CURRENT_TIMESTAMP WHERE id = 'spin';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/spɪn/' WHEN 'uk' THEN '/spɪn/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'spin' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('spin-sense-1', 'spin', 'spin', 'spin', 'verb', '旋转', 'revolve quickly and repeatedly around one''s own axis', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('spin-example-1', 'spin', 'spin', 'spin', 'spin-sense-1', 'They tried to spin carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('spin', 'spin', 'spin', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'operator', meaning_zh = '操作员', definition_en = 'an agent that operates some apparatus or machine', primary_part_of_speech = 'noun', phonetic_us = '/ˈɑpɚˌeɪtɚ/', phonetic_uk = '/ˈɑpəˌeɪtə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'operator';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈɑpɚˌeɪtɚ/' WHEN 'uk' THEN '/ˈɑpəˌeɪtə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'operator' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('operator-sense-1', 'operator', 'operator', 'operator', 'noun', '操作员', 'an agent that operates some apparatus or machine', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('operator-example-1', 'operator', 'operator', 'operator', 'operator-sense-1', 'The operator of the switchboard', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('operator', 'operator', 'operator', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'infant', meaning_zh = '婴儿', definition_en = 'a very young child (birth to 1 year) who has not yet begun to walk or talk', primary_part_of_speech = 'noun', phonetic_us = '/ˈɪnfənt/', phonetic_uk = '/ˈɪnfənt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'infant';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈɪnfənt/' WHEN 'uk' THEN '/ˈɪnfənt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'infant' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('infant-sense-1', 'infant', 'infant', 'infant', 'noun', '婴儿', 'a very young child (birth to 1 year) who has not yet begun to walk or talk', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('infant-example-1', 'infant', 'infant', 'infant', 'infant-sense-1', 'The infant was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('infant', 'infant', 'infant', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'dig', meaning_zh = '挖', definition_en = 'turn up, loosen, or remove earth', primary_part_of_speech = 'verb', phonetic_us = '/dɪɡ/', phonetic_uk = '/dɪɡ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'dig';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/dɪɡ/' WHEN 'uk' THEN '/dɪɡ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'dig' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('dig-sense-1', 'dig', 'dig', 'dig', 'verb', '挖', 'turn up, loosen, or remove earth', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('dig-example-1', 'dig', 'dig', 'dig', 'dig-sense-1', 'They tried to dig carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('dig', 'dig', 'dig', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'drag', meaning_zh = '拖曳', definition_en = 'pull, as against a resistance', primary_part_of_speech = 'verb', phonetic_us = '/dræɡ/', phonetic_uk = '/dræɡ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'drag';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/dræɡ/' WHEN 'uk' THEN '/dræɡ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'drag' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('drag-sense-1', 'drag', 'drag', 'drag', 'verb', '拖曳', 'pull, as against a resistance', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('drag-example-1', 'drag', 'drag', 'drag', 'drag-sense-1', 'He dragged the big suitcase behind him', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('drag', 'drag', 'drag', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'mount', meaning_zh = '组织开展；准备', definition_en = 'attach to a support', primary_part_of_speech = 'verb', phonetic_us = '/maʊnt/', phonetic_uk = '/maʊnt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'mount';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/maʊnt/' WHEN 'uk' THEN '/maʊnt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'mount' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('mount-sense-1', 'mount', 'mount', 'mount', 'verb', '组织开展；准备', 'attach to a support', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('mount-example-1', 'mount', 'mount', 'mount', 'mount-sense-1', 'They mounted the aerator on a floating', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('mount', 'mount', 'mount', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'wrap', meaning_zh = '包；裹', definition_en = 'arrange or fold as a cover or protection', primary_part_of_speech = 'verb', phonetic_us = '/ræp/', phonetic_uk = '/ræp/', updated_at = CURRENT_TIMESTAMP WHERE id = 'wrap';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ræp/' WHEN 'uk' THEN '/ræp/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'wrap' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('wrap-sense-1', 'wrap', 'wrap', 'wrap', 'verb', '包；裹', 'arrange or fold as a cover or protection', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('wrap-example-1', 'wrap', 'wrap', 'wrap', 'wrap-sense-1', 'Wrap the baby before taking her out', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('wrap', 'wrap', 'wrap', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'anticipate', meaning_zh = '期盼，期望', definition_en = 'regard something as probable or likely', primary_part_of_speech = 'verb', phonetic_us = '/æntˈɪsəpˌeɪt/', phonetic_uk = '/æntˈɪsəpˌeɪt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'anticipate';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/æntˈɪsəpˌeɪt/' WHEN 'uk' THEN '/æntˈɪsəpˌeɪt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'anticipate' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('anticipate-sense-1', 'anticipate', 'anticipate', 'anticipate', 'verb', '期盼，期望', 'regard something as probable or likely', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('anticipate-example-1', 'anticipate', 'anticipate', 'anticipate', 'anticipate-sense-1', 'They tried to anticipate carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('anticipate', 'anticipate', 'anticipate', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'dependent', meaning_zh = '依靠的', definition_en = 'relying on or requiring a person or thing for support, supply, or what is needed', primary_part_of_speech = 'adjective', phonetic_us = '/dɪpˈɛndənt/', phonetic_uk = '/dɪpˈɛndənt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'dependent';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/dɪpˈɛndənt/' WHEN 'uk' THEN '/dɪpˈɛndənt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'dependent' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('dependent-sense-1', 'dependent', 'dependent', 'dependent', 'adjective', '依靠的', 'relying on or requiring a person or thing for support, supply, or what is needed', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('dependent-example-1', 'dependent', 'dependent', 'dependent', 'dependent-sense-1', 'This is a dependent example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('dependent', 'dependent', 'dependent', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'specialize', meaning_zh = '专门从事；专攻', definition_en = 'become more focus on an area of activity or field of study', primary_part_of_speech = 'verb', phonetic_us = '/ˈspɛʃəlˌaɪz/', phonetic_uk = '/ˈspɛʃəlˌaɪz/', updated_at = CURRENT_TIMESTAMP WHERE id = 'specialize';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈspɛʃəlˌaɪz/' WHEN 'uk' THEN '/ˈspɛʃəlˌaɪz/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'specialize' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('specialize-sense-1', 'specialize', 'specialize', 'specialize', 'verb', '专门从事；专攻', 'become more focus on an area of activity or field of study', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('specialize-example-1', 'specialize', 'specialize', 'specialize', 'specialize-sense-1', 'She specializes in Near Eastern history', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('specialize', 'specialize', 'specialize', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'angle', meaning_zh = '角', definition_en = 'the space between two lines or planes that intersect; the inclination of one line to another; measured in degrees or radians', primary_part_of_speech = 'noun', phonetic_us = '/ˈæŋɡəl/', phonetic_uk = '/ˈæŋɡəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'angle';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈæŋɡəl/' WHEN 'uk' THEN '/ˈæŋɡəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'angle' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('angle-sense-1', 'angle', 'angle', 'angle', 'noun', '角', 'the space between two lines or planes that intersect; the inclination of one line to another; measured in degrees or radians', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('angle-example-1', 'angle', 'angle', 'angle', 'angle-sense-1', 'The angle was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('angle', 'angle', 'angle', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'chicken', meaning_zh = '鸡', definition_en = 'a domestic fowl bred for flesh or eggs; believed to have been developed from the red jungle fowl', primary_part_of_speech = 'noun', phonetic_us = '/ˈtʃɪkən/', phonetic_uk = '/ˈtʃɪkən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'chicken';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈtʃɪkən/' WHEN 'uk' THEN '/ˈtʃɪkən/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'chicken' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('chicken-sense-1', 'chicken', 'chicken', 'chicken', 'noun', '鸡', 'a domestic fowl bred for flesh or eggs; believed to have been developed from the red jungle fowl', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('chicken-example-1', 'chicken', 'chicken', 'chicken', 'chicken-sense-1', 'The chicken was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('chicken', 'chicken', 'chicken', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'anxiety', meaning_zh = '焦虑；担心', definition_en = '(psychiatry) a relatively permanent state of worry and nervousness occurring in a variety of mental disorders, usually accompanied by compulsive behavior or attacks of panic', primary_part_of_speech = 'noun', phonetic_us = '/æŋzˈaɪətiː/', phonetic_uk = '/æŋzˈaɪətiː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'anxiety';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/æŋzˈaɪətiː/' WHEN 'uk' THEN '/æŋzˈaɪətiː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'anxiety' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('anxiety-sense-1', 'anxiety', 'anxiety', 'anxiety', 'noun', '焦虑；担心', '(psychiatry) a relatively permanent state of worry and nervousness occurring in a variety of mental disorders, usually accompanied by compulsive behavior or attacks of panic', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('anxiety-example-1', 'anxiety', 'anxiety', 'anxiety', 'anxiety-sense-1', 'The anxiety was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('anxiety', 'anxiety', 'anxiety', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
