-- Top 3000 public vocabulary content v1, part 77.
-- Learner bootstrap content for words 2521-2540.
-- Definitions are WordNet-assisted where needed; examples are WordNet examples or generated learner sentences.
-- Phonetics are bootstrap IPA values and remain tracked for manual review.

UPDATE core_vocabulary SET word = 'automatically', meaning_zh = '自动地', definition_en = 'in a reflex manner', primary_part_of_speech = 'adverb', phonetic_us = '/ˌɔtəmˈætɪkliː/', phonetic_uk = '/ˌɔtəmˈætɪkliː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'automatically';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˌɔtəmˈætɪkliː/' WHEN 'uk' THEN '/ˌɔtəmˈætɪkliː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'automatically' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('automatically-sense-1', 'automatically', 'automatically', 'automatically', 'adverb', '自动地', 'in a reflex manner', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('automatically-example-1', 'automatically', 'automatically', 'automatically', 'automatically-sense-1', 'She answered automatically.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('automatically', 'automatically', 'automatically', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'scholar', meaning_zh = '学者', definition_en = 'a learned person (especially in the humanities); someone who by long study has gained mastery in one or more disciplines', primary_part_of_speech = 'noun', phonetic_us = '/ˈskɑlɚ/', phonetic_uk = '/ˈskɑlə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'scholar';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈskɑlɚ/' WHEN 'uk' THEN '/ˈskɑlə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'scholar' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('scholar-sense-1', 'scholar', 'scholar', 'scholar', 'noun', '学者', 'a learned person (especially in the humanities); someone who by long study has gained mastery in one or more disciplines', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('scholar-example-1', 'scholar', 'scholar', 'scholar', 'scholar-sense-1', 'The scholar was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('scholar', 'scholar', 'scholar', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'psychological', meaning_zh = '心理的', definition_en = 'of or relating to or determined by psychology', primary_part_of_speech = 'adjective', phonetic_us = '/ˌsaɪkəlˈɑdʒɪkəl/', phonetic_uk = '/ˌsaɪkəlˈɑdʒɪkəl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'psychological';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˌsaɪkəlˈɑdʒɪkəl/' WHEN 'uk' THEN '/ˌsaɪkəlˈɑdʒɪkəl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'psychological' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('psychological-sense-1', 'psychological', 'psychological', 'psychological', 'adjective', '心理的', 'of or relating to or determined by psychology', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('psychological-example-1', 'psychological', 'psychological', 'psychological', 'psychological-sense-1', 'This is a psychological example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('psychological', 'psychological', 'psychological', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'dramatically', meaning_zh = '显著地；剧烈地', definition_en = 'in a very impressive manner', primary_part_of_speech = 'adverb', phonetic_us = '/drəmˈætɪkliː/', phonetic_uk = '/drəmˈætɪkliː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'dramatically';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/drəmˈætɪkliː/' WHEN 'uk' THEN '/drəmˈætɪkliː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'dramatically' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('dramatically-sense-1', 'dramatically', 'dramatically', 'dramatically', 'adverb', '显著地；剧烈地', 'in a very impressive manner', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('dramatically-example-1', 'dramatically', 'dramatically', 'dramatically', 'dramatically-sense-1', 'Your performance will improve dramatically', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('dramatically', 'dramatically', 'dramatically', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'stake', meaning_zh = '桩', definition_en = 'put at risk', primary_part_of_speech = 'verb', phonetic_us = '/steɪk/', phonetic_uk = '/steɪk/', updated_at = CURRENT_TIMESTAMP WHERE id = 'stake';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/steɪk/' WHEN 'uk' THEN '/steɪk/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'stake' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('stake-sense-1', 'stake', 'stake', 'stake', 'verb', '桩', 'put at risk', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('stake-example-1', 'stake', 'stake', 'stake', 'stake-sense-1', 'I will stake my good reputation for this', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('stake', 'stake', 'stake', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'creature', meaning_zh = '生物', definition_en = 'a living organism characterized by voluntary movement', primary_part_of_speech = 'noun', phonetic_us = '/ˈkriːtʃɚ/', phonetic_uk = '/ˈkriːtʃə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'creature';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈkriːtʃɚ/' WHEN 'uk' THEN '/ˈkriːtʃə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'creature' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('creature-sense-1', 'creature', 'creature', 'creature', 'noun', '生物', 'a living organism characterized by voluntary movement', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('creature-example-1', 'creature', 'creature', 'creature', 'creature-sense-1', 'The creature was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('creature', 'creature', 'creature', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'partnership', meaning_zh = '合作', definition_en = 'a contract between two or more persons who agree to pool talent and money and share profits or losses', primary_part_of_speech = 'noun', phonetic_us = '/ˈpɑrtnɚʃˌɪp/', phonetic_uk = '/ˈpɑːtnəʃˌɪp/', updated_at = CURRENT_TIMESTAMP WHERE id = 'partnership';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈpɑrtnɚʃˌɪp/' WHEN 'uk' THEN '/ˈpɑːtnəʃˌɪp/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'partnership' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('partnership-sense-1', 'partnership', 'partnership', 'partnership', 'noun', '合作', 'a contract between two or more persons who agree to pool talent and money and share profits or losses', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('partnership-example-1', 'partnership', 'partnership', 'partnership', 'partnership-sense-1', 'The partnership was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('partnership', 'partnership', 'partnership', 'study', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('partnership', 'partnership', 'partnership', 'communication', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'participation', meaning_zh = '参与', definition_en = 'the condition of sharing in common with others (as fellows or partners and similar things)', primary_part_of_speech = 'noun', phonetic_us = '/pɑrtˌɪsəpˈeɪʃən/', phonetic_uk = '/pɑːtˌɪsəpˈeɪʃən/', updated_at = CURRENT_TIMESTAMP WHERE id = 'participation';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/pɑrtˌɪsəpˈeɪʃən/' WHEN 'uk' THEN '/pɑːtˌɪsəpˈeɪʃən/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'participation' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('participation-sense-1', 'participation', 'participation', 'participation', 'noun', '参与', 'the condition of sharing in common with others (as fellows or partners and similar things)', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('participation-example-1', 'participation', 'participation', 'participation', 'participation-sense-1', 'The participation was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('participation', 'participation', 'participation', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'clause', meaning_zh = '条款', definition_en = 'a separate section of a legal document (as a statute or contract or will)', primary_part_of_speech = 'noun', phonetic_us = '/klɔz/', phonetic_uk = '/klɔz/', updated_at = CURRENT_TIMESTAMP WHERE id = 'clause';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/klɔz/' WHEN 'uk' THEN '/klɔz/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'clause' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('clause-sense-1', 'clause', 'clause', 'clause', 'noun', '条款', 'a separate section of a legal document (as a statute or contract or will)', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('clause-example-1', 'clause', 'clause', 'clause', 'clause-sense-1', 'The clause was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('clause', 'clause', 'clause', 'study', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('clause', 'clause', 'clause', 'communication', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'penalty', meaning_zh = '处罚', definition_en = 'the act of punishing', primary_part_of_speech = 'noun', phonetic_us = '/ˈpɛnəltiː/', phonetic_uk = '/ˈpɛnəltiː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'penalty';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈpɛnəltiː/' WHEN 'uk' THEN '/ˈpɛnəltiː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'penalty' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('penalty-sense-1', 'penalty', 'penalty', 'penalty', 'noun', '处罚', 'the act of punishing', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('penalty-example-1', 'penalty', 'penalty', 'penalty', 'penalty-sense-1', 'The penalty was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('penalty', 'penalty', 'penalty', 'work', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'chamber', meaning_zh = '室', definition_en = 'a room used primarily for sleeping', primary_part_of_speech = 'noun', phonetic_us = '/ˈtʃeɪmbɚ/', phonetic_uk = '/ˈtʃeɪmbə/', updated_at = CURRENT_TIMESTAMP WHERE id = 'chamber';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈtʃeɪmbɚ/' WHEN 'uk' THEN '/ˈtʃeɪmbə/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'chamber' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('chamber-sense-1', 'chamber', 'chamber', 'chamber', 'noun', '室', 'a room used primarily for sleeping', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('chamber-example-1', 'chamber', 'chamber', 'chamber', 'chamber-sense-1', 'The chamber was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('chamber', 'chamber', 'chamber', 'daily', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'fancy', meaning_zh = '复杂的；昂贵的', definition_en = 'not plain; decorative or ornamented', primary_part_of_speech = 'adjective', phonetic_us = '/ˈfænsiː/', phonetic_uk = '/ˈfænsiː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'fancy';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈfænsiː/' WHEN 'uk' THEN '/ˈfænsiː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'fancy' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('fancy-sense-1', 'fancy', 'fancy', 'fancy', 'adjective', '复杂的；昂贵的', 'not plain; decorative or ornamented', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('fancy-example-1', 'fancy', 'fancy', 'fancy', 'fancy-sense-1', 'This is a fancy example.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('fancy', 'fancy', 'fancy', 'emotion', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'poetry', meaning_zh = '诗', definition_en = 'literature in metrical form', primary_part_of_speech = 'noun', phonetic_us = '/ˈpoʊətriː/', phonetic_uk = '/ˈpoʊətriː/', updated_at = CURRENT_TIMESTAMP WHERE id = 'poetry';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈpoʊətriː/' WHEN 'uk' THEN '/ˈpoʊətriː/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'poetry' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('poetry-sense-1', 'poetry', 'poetry', 'poetry', 'noun', '诗', 'literature in metrical form', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('poetry-example-1', 'poetry', 'poetry', 'poetry', 'poetry-sense-1', 'The poetry was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('poetry', 'poetry', 'poetry', 'study', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('poetry', 'poetry', 'poetry', 'communication', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'chat', meaning_zh = '聊天', definition_en = 'talk socially without exchanging too much information', primary_part_of_speech = 'verb', phonetic_us = '/tʃæt/', phonetic_uk = '/tʃæt/', updated_at = CURRENT_TIMESTAMP WHERE id = 'chat';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/tʃæt/' WHEN 'uk' THEN '/tʃæt/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'chat' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('chat-sense-1', 'chat', 'chat', 'chat', 'verb', '聊天', 'talk socially without exchanging too much information', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('chat-example-1', 'chat', 'chat', 'chat', 'chat-sense-1', 'They tried to chat carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('chat', 'chat', 'chat', 'communication', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'clothing', meaning_zh = '衣服', definition_en = 'a covering designed to be worn on a person''s body', primary_part_of_speech = 'noun', phonetic_us = '/ˈkloʊðɪŋ/', phonetic_uk = '/ˈkloʊðɪŋ/', updated_at = CURRENT_TIMESTAMP WHERE id = 'clothing';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ˈkloʊðɪŋ/' WHEN 'uk' THEN '/ˈkloʊðɪŋ/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'clothing' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('clothing-sense-1', 'clothing', 'clothing', 'clothing', 'noun', '衣服', 'a covering designed to be worn on a person''s body', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('clothing-example-1', 'clothing', 'clothing', 'clothing', 'clothing-sense-1', 'The clothing was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('clothing', 'clothing', 'clothing', 'daily', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'evolve', meaning_zh = '逐渐演变；进化', definition_en = 'work out', primary_part_of_speech = 'verb', phonetic_us = '/ɪvˈɑlv/', phonetic_uk = '/ɪvˈɑlv/', updated_at = CURRENT_TIMESTAMP WHERE id = 'evolve';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ɪvˈɑlv/' WHEN 'uk' THEN '/ɪvˈɑlv/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'evolve' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('evolve-sense-1', 'evolve', 'evolve', 'evolve', 'verb', '逐渐演变；进化', 'work out', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('evolve-example-1', 'evolve', 'evolve', 'evolve', 'evolve-sense-1', 'They tried to evolve carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('evolve', 'evolve', 'evolve', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'sake', meaning_zh = '目的；利益', definition_en = 'a reason for wanting something done', primary_part_of_speech = 'noun', phonetic_us = '/seɪk/', phonetic_uk = '/seɪk/', updated_at = CURRENT_TIMESTAMP WHERE id = 'sake';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/seɪk/' WHEN 'uk' THEN '/seɪk/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'sake' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('sake-sense-1', 'sake', 'sake', 'sake', 'noun', '目的；利益', 'a reason for wanting something done', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('sake-example-1', 'sake', 'sake', 'sake', 'sake-sense-1', 'Died for the sake of his country', '', 'imported', 'wordnet-3.0', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('sake', 'sake', 'sake', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'shelf', meaning_zh = '架子；搁板', definition_en = 'a support that consists of a horizontal surface for holding objects', primary_part_of_speech = 'noun', phonetic_us = '/ʃɛlf/', phonetic_uk = '/ʃɛlf/', updated_at = CURRENT_TIMESTAMP WHERE id = 'shelf';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/ʃɛlf/' WHEN 'uk' THEN '/ʃɛlf/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'shelf' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('shelf-sense-1', 'shelf', 'shelf', 'shelf', 'noun', '架子；搁板', 'a support that consists of a horizontal surface for holding objects', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('shelf-example-1', 'shelf', 'shelf', 'shelf', 'shelf-sense-1', 'The shelf was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('shelf', 'shelf', 'shelf', 'daily', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'boost', meaning_zh = '促进', definition_en = 'contribute to the progress or growth of', primary_part_of_speech = 'verb', phonetic_us = '/buːst/', phonetic_uk = '/buːst/', updated_at = CURRENT_TIMESTAMP WHERE id = 'boost';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/buːst/' WHEN 'uk' THEN '/buːst/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'boost' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('boost-sense-1', 'boost', 'boost', 'boost', 'verb', '促进', 'contribute to the progress or growth of', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('boost-example-1', 'boost', 'boost', 'boost', 'boost-sense-1', 'They tried to boost carefully.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('boost', 'boost', 'boost', 'problem-solving', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;

UPDATE core_vocabulary SET word = 'tail', meaning_zh = '尾巴', definition_en = 'the posterior part of the body of a vertebrate especially when elongated and extending beyond the trunk or main part of the body', primary_part_of_speech = 'noun', phonetic_us = '/teɪl/', phonetic_uk = '/teɪl/', updated_at = CURRENT_TIMESTAMP WHERE id = 'tail';
UPDATE vocabulary_pronunciations SET phonetic = CASE accent WHEN 'us' THEN '/teɪl/' WHEN 'uk' THEN '/teɪl/' ELSE phonetic END, phonetic_source = 'manual-curation-pending-review', updated_at = CURRENT_TIMESTAMP WHERE vocabulary_id = 'tail' AND accent IN ('us', 'uk');
INSERT INTO vocabulary_senses (id, vocabulary_id, word, normalized_word, part_of_speech, meaning_zh, definition_en, usage_note, sense_order, level, publish_status, updated_at) VALUES ('tail-sense-1', 'tail', 'tail', 'tail', 'noun', '尾巴', 'the posterior part of the body of a vertebrate especially when elongated and extending beyond the trunk or main part of the body', 'Learner bootstrap sense; WordNet-assisted and pending human review.', 1, NULL, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, part_of_speech = excluded.part_of_speech, meaning_zh = excluded.meaning_zh, definition_en = excluded.definition_en, usage_note = excluded.usage_note, sense_order = excluded.sense_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_examples (id, vocabulary_id, word, normalized_word, sense_id, sentence_en, sentence_zh, source_type, source_ref, difficulty, example_order, publish_status, updated_at) VALUES ('tail-example-1', 'tail', 'tail', 'tail', 'tail-sense-1', 'The tail was important in the discussion.', '', 'generated', 'top-3000-public-content-v1-wordnet-assisted', 'easy', 1, 'active', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, sense_id = excluded.sense_id, sentence_en = excluded.sentence_en, sentence_zh = excluded.sentence_zh, source_type = excluded.source_type, source_ref = excluded.source_ref, difficulty = excluded.difficulty, example_order = excluded.example_order, publish_status = excluded.publish_status, updated_at = CURRENT_TIMESTAMP;
INSERT INTO vocabulary_scenario_links (vocabulary_id, word, normalized_word, scenario_id, relevance, created_at) VALUES ('tail', 'tail', 'tail', 'thinking', 70, CURRENT_TIMESTAMP) ON CONFLICT(vocabulary_id, scenario_id) DO UPDATE SET word = excluded.word, normalized_word = excluded.normalized_word, relevance = excluded.relevance;
