-- Generated verb paths batch batch-003.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  steps_json,
  growth_json
) VALUES
  (
    'consume-primary',
    'consume',
    'consume',
    'consume memory',
    '消耗内存',
    'The service consumes memory.',
    '该服务会消耗内存。',
    'The service consumes memory under heavy load.',
    '该服务在高负载下会消耗内存。',
    'runtime',
    '[{"step_no":1,"label":"主干","sentence_en":"The service consumes memory.","sentence_zh":"该服务会消耗内存。","focus_text":"consumes","note_zh":"先看服务消耗内存的主干。","segments":[{"text":"The service consumes memory","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"条件","sentence_en":"The service consumes memory under heavy load.","sentence_zh":"该服务在高负载下会消耗内存。","focus_text":"under heavy load","note_zh":"这一步说明出现内存消耗的条件。","segments":[{"text":"The service consumes memory ","kind":"core"},{"text":"under heavy load","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"service","text":"The service","kind":"core","group":"core"},{"id":"consumes","text":"consumes","kind":"action","group":"action"},{"id":"memory","text":"memory","kind":"core","group":"core"},{"id":"under-heavy-load","text":"under heavy load","kind":"modifier","group":"modifier"}],"links":[{"id":"consumes->service","from":"consumes","to":"service","kind":"core","label":"主干"},{"id":"consumes->memory","from":"consumes","to":"memory","kind":"core","label":"主干"},{"id":"under-heavy-load->consumes","from":"under-heavy-load","to":"consumes","kind":"modifier","label":"条件"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The service consumes memory.","sentence_zh":"该服务会消耗内存。","show_nodes":["service","consumes","memory"],"show_links":["consumes->service","consumes->memory"],"focus_node":"consumes","note_zh":"先看服务消耗内存的主干。"},{"step_no":2,"label":"条件","sentence_en":"The service consumes memory under heavy load.","sentence_zh":"该服务在高负载下会消耗内存。","show_nodes":["under-heavy-load"],"show_links":["under-heavy-load->consumes"],"focus_node":"under-heavy-load","note_zh":"这一步说明出现内存消耗的条件。"}]}'
  ),
  (
    'contact-primary',
    'contact',
    'contact',
    'contact support',
    '联系支持团队',
    'The engineer contacted support.',
    '工程师联系了支持团队。',
    'The engineer contacted support through the emergency channel.',
    '工程师通过紧急渠道联系了支持团队。',
    'support',
    '[{"step_no":1,"label":"主干","sentence_en":"The engineer contacted support.","sentence_zh":"工程师联系了支持团队。","focus_text":"contacted","note_zh":"先看工程师联系支持团队的主干。","segments":[{"text":"The engineer contacted support","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"方式","sentence_en":"The engineer contacted support through the emergency channel.","sentence_zh":"工程师通过紧急渠道联系了支持团队。","focus_text":"through the emergency channel","note_zh":"这一步说明联系所用的方式。","segments":[{"text":"The engineer contacted support ","kind":"core"},{"text":"through the emergency channel","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"engineer","text":"The engineer","kind":"core","group":"core"},{"id":"contacted","text":"contacted","kind":"action","group":"action"},{"id":"support","text":"support","kind":"core","group":"core"},{"id":"through-the-emergency-channel","text":"through the emergency channel","kind":"modifier","group":"modifier"}],"links":[{"id":"contacted->engineer","from":"contacted","to":"engineer","kind":"core","label":"主干"},{"id":"contacted->support","from":"contacted","to":"support","kind":"core","label":"主干"},{"id":"through-the-emergency-channel->contacted","from":"through-the-emergency-channel","to":"contacted","kind":"modifier","label":"方式"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The engineer contacted support.","sentence_zh":"工程师联系了支持团队。","show_nodes":["engineer","contacted","support"],"show_links":["contacted->engineer","contacted->support"],"focus_node":"contacted","note_zh":"先看工程师联系支持团队的主干。"},{"step_no":2,"label":"方式","sentence_en":"The engineer contacted support through the emergency channel.","sentence_zh":"工程师通过紧急渠道联系了支持团队。","show_nodes":["through-the-emergency-channel"],"show_links":["through-the-emergency-channel->contacted"],"focus_node":"through-the-emergency-channel","note_zh":"这一步说明联系所用的方式。"}]}'
  ),
  (
    'contain-primary',
    'contain',
    'contain',
    'contain credentials',
    '包含凭据',
    'The file contains credentials.',
    '该文件包含凭据。',
    'The file contains unencrypted credentials.',
    '该文件包含未加密的凭据。',
    'security',
    '[{"step_no":1,"label":"主干","sentence_en":"The file contains credentials.","sentence_zh":"该文件包含凭据。","focus_text":"contains","note_zh":"先看文件包含凭据的主干。","segments":[{"text":"The file contains credentials","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The file contains unencrypted credentials.","sentence_zh":"该文件包含未加密的凭据。","focus_text":"unencrypted","note_zh":"这一步补充凭据的安全状态。","segments":[{"text":"The file contains ","kind":"core"},{"text":"unencrypted","kind":"modifier"},{"text":" credentials","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"file","text":"The file","kind":"core","group":"core"},{"id":"contains","text":"contains","kind":"action","group":"action"},{"id":"credentials","text":"credentials","kind":"core","group":"core"},{"id":"unencrypted","text":"unencrypted","kind":"modifier","group":"modifier"}],"links":[{"id":"contains->file","from":"contains","to":"file","kind":"core","label":"主干"},{"id":"contains->credentials","from":"contains","to":"credentials","kind":"core","label":"主干"},{"id":"unencrypted->credentials","from":"unencrypted","to":"credentials","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The file contains credentials.","sentence_zh":"该文件包含凭据。","show_nodes":["file","contains","credentials"],"show_links":["contains->file","contains->credentials"],"focus_node":"contains","note_zh":"先看文件包含凭据的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The file contains unencrypted credentials.","sentence_zh":"该文件包含未加密的凭据。","show_nodes":["unencrypted"],"show_links":["unencrypted->credentials"],"focus_node":"unencrypted","note_zh":"这一步补充凭据的安全状态。"}]}'
  ),
  (
    'contend-primary',
    'contend',
    'contend',
    'contend for a lock',
    '竞争同一把锁',
    'The threads contend for the lock.',
    '这些线程会竞争这把锁。',
    'The threads contend for the lock during cache updates.',
    '这些线程在更新缓存时会竞争这把锁。',
    'runtime',
    '[{"step_no":1,"label":"主干","sentence_en":"The threads contend for the lock.","sentence_zh":"这些线程会竞争这把锁。","focus_text":"contend","note_zh":"先看线程竞争锁的主干。","segments":[{"text":"The threads contend for the lock","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"场景","sentence_en":"The threads contend for the lock during cache updates.","sentence_zh":"这些线程在更新缓存时会竞争这把锁。","focus_text":"during cache updates","note_zh":"这一步说明锁竞争发生的场景。","segments":[{"text":"The threads contend for the lock ","kind":"core"},{"text":"during cache updates","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"threads","text":"The threads","kind":"core","group":"core"},{"id":"contend","text":"contend","kind":"action","group":"action"},{"id":"for-lock","text":"for the lock","kind":"core","group":"core"},{"id":"during-cache-updates","text":"during cache updates","kind":"modifier","group":"modifier"}],"links":[{"id":"contend->threads","from":"contend","to":"threads","kind":"core","label":"主干"},{"id":"contend->for-lock","from":"contend","to":"for-lock","kind":"core","label":"主干"},{"id":"during-cache-updates->contend","from":"during-cache-updates","to":"contend","kind":"modifier","label":"场景"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The threads contend for the lock.","sentence_zh":"这些线程会竞争这把锁。","show_nodes":["threads","contend","for-lock"],"show_links":["contend->threads","contend->for-lock"],"focus_node":"contend","note_zh":"先看线程竞争锁的主干。"},{"step_no":2,"label":"场景","sentence_en":"The threads contend for the lock during cache updates.","sentence_zh":"这些线程在更新缓存时会竞争这把锁。","show_nodes":["during-cache-updates"],"show_links":["during-cache-updates->contend"],"focus_node":"during-cache-updates","note_zh":"这一步说明锁竞争发生的场景。"}]}'
  ),
  (
    'continue-primary',
    'continue',
    'continue',
    'continue processing jobs',
    '继续处理任务',
    'The worker continued processing jobs.',
    '工作进程继续处理任务。',
    'The worker continued processing jobs after the network recovered.',
    '网络恢复后，工作进程继续处理任务。',
    'queue',
    '[{"step_no":1,"label":"主干","sentence_en":"The worker continued processing jobs.","sentence_zh":"工作进程继续处理任务。","focus_text":"continued","note_zh":"先看工作进程继续处理任务的主干。","segments":[{"text":"The worker continued processing jobs","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"时间","sentence_en":"The worker continued processing jobs after the network recovered.","sentence_zh":"网络恢复后，工作进程继续处理任务。","focus_text":"after the network recovered","note_zh":"这一步说明继续处理任务的时间。","segments":[{"text":"The worker continued processing jobs ","kind":"core"},{"text":"after the network recovered","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"worker","text":"The worker","kind":"core","group":"core"},{"id":"continued","text":"continued","kind":"action","group":"action"},{"id":"processing-jobs","text":"processing jobs","kind":"core","group":"core"},{"id":"after-the-network-recovered","text":"after the network recovered","kind":"modifier","group":"modifier"}],"links":[{"id":"continued->worker","from":"continued","to":"worker","kind":"core","label":"主干"},{"id":"continued->processing-jobs","from":"continued","to":"processing-jobs","kind":"core","label":"主干"},{"id":"after-the-network-recovered->continued","from":"after-the-network-recovered","to":"continued","kind":"modifier","label":"时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The worker continued processing jobs.","sentence_zh":"工作进程继续处理任务。","show_nodes":["worker","continued","processing-jobs"],"show_links":["continued->worker","continued->processing-jobs"],"focus_node":"continued","note_zh":"先看工作进程继续处理任务的主干。"},{"step_no":2,"label":"时间","sentence_en":"The worker continued processing jobs after the network recovered.","sentence_zh":"网络恢复后，工作进程继续处理任务。","show_nodes":["after-the-network-recovered"],"show_links":["after-the-network-recovered->continued"],"focus_node":"after-the-network-recovered","note_zh":"这一步说明继续处理任务的时间。"}]}'
  ),
  (
    'contract-primary',
    'contract',
    'contract',
    'contract a specialist',
    '签约聘请专业人员',
    'The company contracted a specialist.',
    '公司签约聘请了一名专业人员。',
    'The company contracted a specialist for a security audit.',
    '公司签约聘请了一名专业人员进行安全审计。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The company contracted a specialist.","sentence_zh":"公司签约聘请了一名专业人员。","focus_text":"contracted","note_zh":"先看公司签约聘请专业人员的主干。","segments":[{"text":"The company contracted a specialist","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"目的","sentence_en":"The company contracted a specialist for a security audit.","sentence_zh":"公司签约聘请了一名专业人员进行安全审计。","focus_text":"for a security audit","note_zh":"这一步说明签约聘请的目的。","segments":[{"text":"The company contracted a specialist ","kind":"core"},{"text":"for a security audit","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"company","text":"The company","kind":"core","group":"core"},{"id":"contracted","text":"contracted","kind":"action","group":"action"},{"id":"specialist","text":"a specialist","kind":"core","group":"core"},{"id":"for-a-security-audit","text":"for a security audit","kind":"modifier","group":"modifier"}],"links":[{"id":"contracted->company","from":"contracted","to":"company","kind":"core","label":"主干"},{"id":"contracted->specialist","from":"contracted","to":"specialist","kind":"core","label":"主干"},{"id":"for-a-security-audit->contracted","from":"for-a-security-audit","to":"contracted","kind":"modifier","label":"目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The company contracted a specialist.","sentence_zh":"公司签约聘请了一名专业人员。","show_nodes":["company","contracted","specialist"],"show_links":["contracted->company","contracted->specialist"],"focus_node":"contracted","note_zh":"先看公司签约聘请专业人员的主干。"},{"step_no":2,"label":"目的","sentence_en":"The company contracted a specialist for a security audit.","sentence_zh":"公司签约聘请了一名专业人员进行安全审计。","show_nodes":["for-a-security-audit"],"show_links":["for-a-security-audit->contracted"],"focus_node":"for-a-security-audit","note_zh":"这一步说明签约聘请的目的。"}]}'
  ),
  (
    'contrast-primary',
    'contrast',
    'contrast',
    'contrast two approaches',
    '对比两种方案',
    'The report contrasts the approaches.',
    '报告对比了这些方案。',
    'The report contrasts the two caching approaches.',
    '报告对比了这两种缓存方案。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"The report contrasts the approaches.","sentence_zh":"报告对比了这些方案。","focus_text":"contrasts","note_zh":"先看报告对比方案的主干。","segments":[{"text":"The report contrasts the approaches","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The report contrasts the two caching approaches.","sentence_zh":"报告对比了这两种缓存方案。","focus_text":"two caching","note_zh":"这一步补充方案的数量和类型。","segments":[{"text":"The report contrasts the ","kind":"core"},{"text":"two caching","kind":"modifier"},{"text":" approaches","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"report","text":"The report","kind":"core","group":"core"},{"id":"contrasts","text":"contrasts","kind":"action","group":"action"},{"id":"approaches","text":"the approaches","kind":"core","group":"core"},{"id":"two-caching","text":"two caching","kind":"modifier","group":"modifier"}],"links":[{"id":"contrasts->report","from":"contrasts","to":"report","kind":"core","label":"主干"},{"id":"contrasts->approaches","from":"contrasts","to":"approaches","kind":"core","label":"主干"},{"id":"two-caching->approaches","from":"two-caching","to":"approaches","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The report contrasts the approaches.","sentence_zh":"报告对比了这些方案。","show_nodes":["report","contrasts","approaches"],"show_links":["contrasts->report","contrasts->approaches"],"focus_node":"contrasts","note_zh":"先看报告对比方案的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The report contrasts the two caching approaches.","sentence_zh":"报告对比了这两种缓存方案。","show_nodes":["two-caching"],"show_links":["two-caching->approaches"],"focus_node":"two-caching","note_zh":"这一步补充方案的数量和类型。"}]}'
  ),
  (
    'contribute-primary',
    'contribute',
    'contribute',
    'contribute to latency',
    '导致延迟增加',
    'The retries contribute to latency.',
    '这些重试会导致延迟增加。',
    'The retries contribute significantly to latency.',
    '这些重试会显著增加延迟。',
    'runtime',
    '[{"step_no":1,"label":"主干","sentence_en":"The retries contribute to latency.","sentence_zh":"这些重试会导致延迟增加。","focus_text":"contribute","note_zh":"先看重试导致延迟增加的主干。","segments":[{"text":"The retries contribute to latency","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The retries contribute significantly to latency.","sentence_zh":"这些重试会显著增加延迟。","focus_text":"significantly","note_zh":"这一步说明影响的程度。","segments":[{"text":"The retries contribute ","kind":"core"},{"text":"significantly","kind":"modifier"},{"text":" to latency","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"retries","text":"The retries","kind":"core","group":"core"},{"id":"contribute","text":"contribute","kind":"action","group":"action"},{"id":"to-latency","text":"to latency","kind":"core","group":"core"},{"id":"significantly","text":"significantly","kind":"modifier","group":"modifier"}],"links":[{"id":"contribute->retries","from":"contribute","to":"retries","kind":"core","label":"主干"},{"id":"contribute->to-latency","from":"contribute","to":"to-latency","kind":"core","label":"主干"},{"id":"significantly->contribute","from":"significantly","to":"contribute","kind":"modifier","label":"程度"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The retries contribute to latency.","sentence_zh":"这些重试会导致延迟增加。","show_nodes":["retries","contribute","to-latency"],"show_links":["contribute->retries","contribute->to-latency"],"focus_node":"contribute","note_zh":"先看重试导致延迟增加的主干。"},{"step_no":2,"label":"程度","sentence_en":"The retries contribute significantly to latency.","sentence_zh":"这些重试会显著增加延迟。","show_nodes":["significantly"],"show_links":["significantly->contribute"],"focus_node":"significantly","note_zh":"这一步说明影响的程度。"}]}'
  ),
  (
    'control-primary',
    'control',
    'control',
    'control access',
    '控制访问权限',
    'The policy controls access.',
    '该策略控制访问权限。',
    'The policy controls access to production data.',
    '该策略控制对生产数据的访问权限。',
    'security',
    '[{"step_no":1,"label":"主干","sentence_en":"The policy controls access.","sentence_zh":"该策略控制访问权限。","focus_text":"controls","note_zh":"先看策略控制访问权限的主干。","segments":[{"text":"The policy controls access","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"范围","sentence_en":"The policy controls access to production data.","sentence_zh":"该策略控制对生产数据的访问权限。","focus_text":"to production data","note_zh":"这一步说明访问权限涉及的范围。","segments":[{"text":"The policy controls access ","kind":"core"},{"text":"to production data","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"policy","text":"The policy","kind":"core","group":"core"},{"id":"controls","text":"controls","kind":"action","group":"action"},{"id":"access","text":"access","kind":"core","group":"core"},{"id":"to-production-data","text":"to production data","kind":"modifier","group":"modifier"}],"links":[{"id":"controls->policy","from":"controls","to":"policy","kind":"core","label":"主干"},{"id":"controls->access","from":"controls","to":"access","kind":"core","label":"主干"},{"id":"to-production-data->access","from":"to-production-data","to":"access","kind":"modifier","label":"范围"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The policy controls access.","sentence_zh":"该策略控制访问权限。","show_nodes":["policy","controls","access"],"show_links":["controls->policy","controls->access"],"focus_node":"controls","note_zh":"先看策略控制访问权限的主干。"},{"step_no":2,"label":"范围","sentence_en":"The policy controls access to production data.","sentence_zh":"该策略控制对生产数据的访问权限。","show_nodes":["to-production-data"],"show_links":["to-production-data->access"],"focus_node":"to-production-data","note_zh":"这一步说明访问权限涉及的范围。"}]}'
  ),
  (
    'convert-primary',
    'convert',
    'convert',
    'convert a timestamp',
    '转换时间戳格式',
    'The function converts the timestamp.',
    '该函数转换时间戳。',
    'The function converts the timestamp into ISO 8601 format.',
    '该函数将时间戳转换为 ISO 8601 格式。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"The function converts the timestamp.","sentence_zh":"该函数转换时间戳。","focus_text":"converts","note_zh":"先看函数转换时间戳的主干。","segments":[{"text":"The function converts the timestamp","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"结果","sentence_en":"The function converts the timestamp into ISO 8601 format.","sentence_zh":"该函数将时间戳转换为 ISO 8601 格式。","focus_text":"into ISO 8601 format","note_zh":"这一步说明转换后的结果。","segments":[{"text":"The function converts the timestamp ","kind":"core"},{"text":"into ISO 8601 format","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"function","text":"The function","kind":"core","group":"core"},{"id":"converts","text":"converts","kind":"action","group":"action"},{"id":"timestamp","text":"the timestamp","kind":"core","group":"core"},{"id":"into-iso-8601-format","text":"into ISO 8601 format","kind":"modifier","group":"modifier"}],"links":[{"id":"converts->function","from":"converts","to":"function","kind":"core","label":"主干"},{"id":"converts->timestamp","from":"converts","to":"timestamp","kind":"core","label":"主干"},{"id":"into-iso-8601-format->converts","from":"into-iso-8601-format","to":"converts","kind":"modifier","label":"结果"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The function converts the timestamp.","sentence_zh":"该函数转换时间戳。","show_nodes":["function","converts","timestamp"],"show_links":["converts->function","converts->timestamp"],"focus_node":"converts","note_zh":"先看函数转换时间戳的主干。"},{"step_no":2,"label":"结果","sentence_en":"The function converts the timestamp into ISO 8601 format.","sentence_zh":"该函数将时间戳转换为 ISO 8601 格式。","show_nodes":["into-iso-8601-format"],"show_links":["into-iso-8601-format->converts"],"focus_node":"into-iso-8601-format","note_zh":"这一步说明转换后的结果。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  steps_json = excluded.steps_json,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  steps_json,
  growth_json
) VALUES
  (
    'convey-primary',
    'convey',
    'convey',
    'convey urgency',
    '传达紧迫性',
    'The message conveys the urgency.',
    '这条消息传达了紧迫性。',
    'The message conveys the urgency of the outage.',
    '这条消息传达了此次服务中断的紧迫性。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The message conveys the urgency.","sentence_zh":"这条消息传达了紧迫性。","focus_text":"conveys","note_zh":"先看消息传达紧迫性的主干。","segments":[{"text":"The message conveys the urgency","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The message conveys the urgency of the outage.","sentence_zh":"这条消息传达了此次服务中断的紧迫性。","focus_text":"of the outage","note_zh":"这一步说明是哪件事具有紧迫性。","segments":[{"text":"The message conveys the urgency ","kind":"core"},{"text":"of the outage","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"message","text":"The message","kind":"core","group":"core"},{"id":"conveys","text":"conveys","kind":"action","group":"action"},{"id":"urgency","text":"the urgency","kind":"core","group":"core"},{"id":"of-the-outage","text":"of the outage","kind":"modifier","group":"modifier"}],"links":[{"id":"conveys->message","from":"conveys","to":"message","kind":"core","label":"主干"},{"id":"conveys->urgency","from":"conveys","to":"urgency","kind":"core","label":"主干"},{"id":"of-the-outage->urgency","from":"of-the-outage","to":"urgency","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The message conveys the urgency.","sentence_zh":"这条消息传达了紧迫性。","show_nodes":["message","conveys","urgency"],"show_links":["conveys->message","conveys->urgency"],"focus_node":"conveys","note_zh":"先看消息传达紧迫性的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The message conveys the urgency of the outage.","sentence_zh":"这条消息传达了此次服务中断的紧迫性。","show_nodes":["of-the-outage"],"show_links":["of-the-outage->urgency"],"focus_node":"of-the-outage","note_zh":"这一步说明是哪件事具有紧迫性。"}]}'
  ),
  (
    'convince-primary',
    'convince',
    'convince',
    'convince the team',
    '说服团队采用设计',
    'The prototype convinced the team to adopt the design.',
    '该原型说服团队采用了这一设计。',
    'The prototype convinced the team to adopt the design during the review.',
    '在评审期间，该原型说服团队采用了这一设计。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The prototype convinced the team to adopt the design.","sentence_zh":"该原型说服团队采用了这一设计。","focus_text":"convinced","note_zh":"先看原型说服团队采用设计的主干。","segments":[{"text":"The prototype convinced the team to adopt the design","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"场景","sentence_en":"The prototype convinced the team to adopt the design during the review.","sentence_zh":"在评审期间，该原型说服团队采用了这一设计。","focus_text":"during the review","note_zh":"这一步说明说服发生的场景。","segments":[{"text":"The prototype convinced the team to adopt the design ","kind":"core"},{"text":"during the review","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"prototype","text":"The prototype","kind":"core","group":"core"},{"id":"convinced","text":"convinced","kind":"action","group":"action"},{"id":"team","text":"the team","kind":"core","group":"core"},{"id":"to-adopt-the-design","text":"to adopt the design","kind":"core","group":"core"},{"id":"during-the-review","text":"during the review","kind":"modifier","group":"modifier"}],"links":[{"id":"convinced->prototype","from":"convinced","to":"prototype","kind":"core","label":"主干"},{"id":"convinced->team","from":"convinced","to":"team","kind":"core","label":"主干"},{"id":"convinced->to-adopt-the-design","from":"convinced","to":"to-adopt-the-design","kind":"core","label":"主干"},{"id":"during-the-review->convinced","from":"during-the-review","to":"convinced","kind":"modifier","label":"场景"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The prototype convinced the team to adopt the design.","sentence_zh":"该原型说服团队采用了这一设计。","show_nodes":["prototype","convinced","team","to-adopt-the-design"],"show_links":["convinced->prototype","convinced->team","convinced->to-adopt-the-design"],"focus_node":"convinced","note_zh":"先看原型说服团队采用设计的主干。"},{"step_no":2,"label":"场景","sentence_en":"The prototype convinced the team to adopt the design during the review.","sentence_zh":"在评审期间，该原型说服团队采用了这一设计。","show_nodes":["during-the-review"],"show_links":["during-the-review->convinced"],"focus_node":"during-the-review","note_zh":"这一步说明说服发生的场景。"}]}'
  ),
  (
    'cook-primary',
    'cook',
    'cook',
    'cook dinner',
    '烹饪晚餐',
    'Maya cooked dinner.',
    '玛雅做了晚餐。',
    'Maya cooked dinner for her roommates.',
    '玛雅为室友们做了晚餐。',
    'daily-life',
    '[{"step_no":1,"label":"主干","sentence_en":"Maya cooked dinner.","sentence_zh":"玛雅做了晚餐。","focus_text":"cooked","note_zh":"先看玛雅做晚餐的主干。","segments":[{"text":"Maya cooked dinner","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"目的","sentence_en":"Maya cooked dinner for her roommates.","sentence_zh":"玛雅为室友们做了晚餐。","focus_text":"for her roommates","note_zh":"这一步说明晚餐是为谁做的。","segments":[{"text":"Maya cooked dinner ","kind":"core"},{"text":"for her roommates","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"maya","text":"Maya","kind":"core","group":"core"},{"id":"cooked","text":"cooked","kind":"action","group":"action"},{"id":"dinner","text":"dinner","kind":"core","group":"core"},{"id":"for-her-roommates","text":"for her roommates","kind":"modifier","group":"modifier"}],"links":[{"id":"cooked->maya","from":"cooked","to":"maya","kind":"core","label":"主干"},{"id":"cooked->dinner","from":"cooked","to":"dinner","kind":"core","label":"主干"},{"id":"for-her-roommates->cooked","from":"for-her-roommates","to":"cooked","kind":"modifier","label":"目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Maya cooked dinner.","sentence_zh":"玛雅做了晚餐。","show_nodes":["maya","cooked","dinner"],"show_links":["cooked->maya","cooked->dinner"],"focus_node":"cooked","note_zh":"先看玛雅做晚餐的主干。"},{"step_no":2,"label":"目的","sentence_en":"Maya cooked dinner for her roommates.","sentence_zh":"玛雅为室友们做了晚餐。","show_nodes":["for-her-roommates"],"show_links":["for-her-roommates->cooked"],"focus_node":"for-her-roommates","note_zh":"这一步说明晚餐是为谁做的。"}]}'
  ),
  (
    'cook-up-primary',
    'cook-up',
    'cook up',
    'cook up a workaround',
    '想出变通方案',
    'The team cooked up a workaround.',
    '团队想出了一个变通方案。',
    'The team cooked up a temporary workaround.',
    '团队想出了一个临时变通方案。',
    'debug',
    '[{"step_no":1,"label":"主干","sentence_en":"The team cooked up a workaround.","sentence_zh":"团队想出了一个变通方案。","focus_text":"cooked up","note_zh":"先看团队想出变通方案的主干。","segments":[{"text":"The team cooked up a workaround","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The team cooked up a temporary workaround.","sentence_zh":"团队想出了一个临时变通方案。","focus_text":"temporary","note_zh":"这一步补充方案的临时性质。","segments":[{"text":"The team cooked up a ","kind":"core"},{"text":"temporary","kind":"modifier"},{"text":" workaround","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"team","text":"The team","kind":"core","group":"core"},{"id":"cooked-up","text":"cooked up","kind":"action","group":"action"},{"id":"workaround","text":"a workaround","kind":"core","group":"core"},{"id":"temporary","text":"temporary","kind":"modifier","group":"modifier"}],"links":[{"id":"cooked-up->team","from":"cooked-up","to":"team","kind":"core","label":"主干"},{"id":"cooked-up->workaround","from":"cooked-up","to":"workaround","kind":"core","label":"主干"},{"id":"temporary->workaround","from":"temporary","to":"workaround","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team cooked up a workaround.","sentence_zh":"团队想出了一个变通方案。","show_nodes":["team","cooked-up","workaround"],"show_links":["cooked-up->team","cooked-up->workaround"],"focus_node":"cooked-up","note_zh":"先看团队想出变通方案的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The team cooked up a temporary workaround.","sentence_zh":"团队想出了一个临时变通方案。","show_nodes":["temporary"],"show_links":["temporary->workaround"],"focus_node":"temporary","note_zh":"这一步补充方案的临时性质。"}]}'
  ),
  (
    'cooperate-primary',
    'cooperate',
    'cooperate',
    'cooperate with auditors',
    '与审计人员合作',
    'The team cooperated with the auditors.',
    '团队与审计人员进行了合作。',
    'The team cooperated fully with the auditors.',
    '团队与审计人员进行了充分合作。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The team cooperated with the auditors.","sentence_zh":"团队与审计人员进行了合作。","focus_text":"cooperated","note_zh":"先看团队与审计人员合作的主干。","segments":[{"text":"The team cooperated with the auditors","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The team cooperated fully with the auditors.","sentence_zh":"团队与审计人员进行了充分合作。","focus_text":"fully","note_zh":"这一步说明合作的程度。","segments":[{"text":"The team cooperated ","kind":"core"},{"text":"fully","kind":"modifier"},{"text":" with the auditors","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"team","text":"The team","kind":"core","group":"core"},{"id":"cooperated","text":"cooperated","kind":"action","group":"action"},{"id":"with-auditors","text":"with the auditors","kind":"core","group":"core"},{"id":"fully","text":"fully","kind":"modifier","group":"modifier"}],"links":[{"id":"cooperated->team","from":"cooperated","to":"team","kind":"core","label":"主干"},{"id":"cooperated->with-auditors","from":"cooperated","to":"with-auditors","kind":"core","label":"主干"},{"id":"fully->cooperated","from":"fully","to":"cooperated","kind":"modifier","label":"程度"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team cooperated with the auditors.","sentence_zh":"团队与审计人员进行了合作。","show_nodes":["team","cooperated","with-auditors"],"show_links":["cooperated->team","cooperated->with-auditors"],"focus_node":"cooperated","note_zh":"先看团队与审计人员合作的主干。"},{"step_no":2,"label":"程度","sentence_en":"The team cooperated fully with the auditors.","sentence_zh":"团队与审计人员进行了充分合作。","show_nodes":["fully"],"show_links":["fully->cooperated"],"focus_node":"fully","note_zh":"这一步说明合作的程度。"}]}'
  ),
  (
    'coordinate-primary',
    'coordinate',
    'coordinate',
    'coordinate a release',
    '协调发布工作',
    'The manager coordinated the release.',
    '经理协调了发布工作。',
    'The manager coordinated the release across three teams.',
    '经理协调了三个团队之间的发布工作。',
    'release',
    '[{"step_no":1,"label":"主干","sentence_en":"The manager coordinated the release.","sentence_zh":"经理协调了发布工作。","focus_text":"coordinated","note_zh":"先看经理协调发布工作的主干。","segments":[{"text":"The manager coordinated the release","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"范围","sentence_en":"The manager coordinated the release across three teams.","sentence_zh":"经理协调了三个团队之间的发布工作。","focus_text":"across three teams","note_zh":"这一步说明协调涉及的团队范围。","segments":[{"text":"The manager coordinated the release ","kind":"core"},{"text":"across three teams","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"manager","text":"The manager","kind":"core","group":"core"},{"id":"coordinated","text":"coordinated","kind":"action","group":"action"},{"id":"release","text":"the release","kind":"core","group":"core"},{"id":"across-three-teams","text":"across three teams","kind":"modifier","group":"modifier"}],"links":[{"id":"coordinated->manager","from":"coordinated","to":"manager","kind":"core","label":"主干"},{"id":"coordinated->release","from":"coordinated","to":"release","kind":"core","label":"主干"},{"id":"across-three-teams->coordinated","from":"across-three-teams","to":"coordinated","kind":"modifier","label":"范围"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The manager coordinated the release.","sentence_zh":"经理协调了发布工作。","show_nodes":["manager","coordinated","release"],"show_links":["coordinated->manager","coordinated->release"],"focus_node":"coordinated","note_zh":"先看经理协调发布工作的主干。"},{"step_no":2,"label":"范围","sentence_en":"The manager coordinated the release across three teams.","sentence_zh":"经理协调了三个团队之间的发布工作。","show_nodes":["across-three-teams"],"show_links":["across-three-teams->coordinated"],"focus_node":"across-three-teams","note_zh":"这一步说明协调涉及的团队范围。"}]}'
  ),
  (
    'cope-primary',
    'cope',
    'cope',
    'cope with traffic',
    '应对突发流量',
    'The system copes with traffic.',
    '该系统能够应对流量。',
    'The system copes with sudden traffic.',
    '该系统能够应对突发流量。',
    'runtime',
    '[{"step_no":1,"label":"主干","sentence_en":"The system copes with traffic.","sentence_zh":"该系统能够应对流量。","focus_text":"copes","note_zh":"先看系统应对流量的主干。","segments":[{"text":"The system copes with traffic","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The system copes with sudden traffic.","sentence_zh":"该系统能够应对突发流量。","focus_text":"sudden","note_zh":"这一步补充流量的突发性质。","segments":[{"text":"The system copes with ","kind":"core"},{"text":"sudden","kind":"modifier"},{"text":" traffic","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"system","text":"The system","kind":"core","group":"core"},{"id":"copes","text":"copes","kind":"action","group":"action"},{"id":"with-traffic","text":"with traffic","kind":"core","group":"core"},{"id":"sudden","text":"sudden","kind":"modifier","group":"modifier"}],"links":[{"id":"copes->system","from":"copes","to":"system","kind":"core","label":"主干"},{"id":"copes->with-traffic","from":"copes","to":"with-traffic","kind":"core","label":"主干"},{"id":"sudden->with-traffic","from":"sudden","to":"with-traffic","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The system copes with traffic.","sentence_zh":"该系统能够应对流量。","show_nodes":["system","copes","with-traffic"],"show_links":["copes->system","copes->with-traffic"],"focus_node":"copes","note_zh":"先看系统应对流量的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The system copes with sudden traffic.","sentence_zh":"该系统能够应对突发流量。","show_nodes":["sudden"],"show_links":["sudden->with-traffic"],"focus_node":"sudden","note_zh":"这一步补充流量的突发性质。"}]}'
  ),
  (
    'copy-primary',
    'copy',
    'copy',
    'copy a file',
    '复制文件',
    'The script copies the file.',
    '该脚本复制文件。',
    'The script copies the file to each server.',
    '该脚本把文件复制到每台服务器。',
    'deploy',
    '[{"step_no":1,"label":"主干","sentence_en":"The script copies the file.","sentence_zh":"该脚本复制文件。","focus_text":"copies","note_zh":"先看脚本复制文件的主干。","segments":[{"text":"The script copies the file","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"范围","sentence_en":"The script copies the file to each server.","sentence_zh":"该脚本把文件复制到每台服务器。","focus_text":"to each server","note_zh":"这一步说明文件复制到哪些服务器。","segments":[{"text":"The script copies the file ","kind":"core"},{"text":"to each server","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"script","text":"The script","kind":"core","group":"core"},{"id":"copies","text":"copies","kind":"action","group":"action"},{"id":"file","text":"the file","kind":"core","group":"core"},{"id":"to-each-server","text":"to each server","kind":"modifier","group":"modifier"}],"links":[{"id":"copies->script","from":"copies","to":"script","kind":"core","label":"主干"},{"id":"copies->file","from":"copies","to":"file","kind":"core","label":"主干"},{"id":"to-each-server->copies","from":"to-each-server","to":"copies","kind":"modifier","label":"范围"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The script copies the file.","sentence_zh":"该脚本复制文件。","show_nodes":["script","copies","file"],"show_links":["copies->script","copies->file"],"focus_node":"copies","note_zh":"先看脚本复制文件的主干。"},{"step_no":2,"label":"范围","sentence_en":"The script copies the file to each server.","sentence_zh":"该脚本把文件复制到每台服务器。","show_nodes":["to-each-server"],"show_links":["to-each-server->copies"],"focus_node":"to-each-server","note_zh":"这一步说明文件复制到哪些服务器。"}]}'
  ),
  (
    'correct-primary',
    'correct',
    'correct',
    'correct an error',
    '纠正错误',
    'The patch corrects the error.',
    '该补丁纠正了这个错误。',
    'The patch corrects the rounding error.',
    '该补丁纠正了舍入错误。',
    'debug',
    '[{"step_no":1,"label":"主干","sentence_en":"The patch corrects the error.","sentence_zh":"该补丁纠正了这个错误。","focus_text":"corrects","note_zh":"先看补丁纠正错误的主干。","segments":[{"text":"The patch corrects the error","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The patch corrects the rounding error.","sentence_zh":"该补丁纠正了舍入错误。","focus_text":"rounding","note_zh":"这一步补充错误的类型。","segments":[{"text":"The patch corrects the ","kind":"core"},{"text":"rounding","kind":"modifier"},{"text":" error","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"patch","text":"The patch","kind":"core","group":"core"},{"id":"corrects","text":"corrects","kind":"action","group":"action"},{"id":"error","text":"the error","kind":"core","group":"core"},{"id":"rounding","text":"rounding","kind":"modifier","group":"modifier"}],"links":[{"id":"corrects->patch","from":"corrects","to":"patch","kind":"core","label":"主干"},{"id":"corrects->error","from":"corrects","to":"error","kind":"core","label":"主干"},{"id":"rounding->error","from":"rounding","to":"error","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The patch corrects the error.","sentence_zh":"该补丁纠正了这个错误。","show_nodes":["patch","corrects","error"],"show_links":["corrects->patch","corrects->error"],"focus_node":"corrects","note_zh":"先看补丁纠正错误的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The patch corrects the rounding error.","sentence_zh":"该补丁纠正了舍入错误。","show_nodes":["rounding"],"show_links":["rounding->error"],"focus_node":"rounding","note_zh":"这一步补充错误的类型。"}]}'
  ),
  (
    'correspond-primary',
    'correspond',
    'correspond',
    'correspond to a field',
    '与字段相对应',
    'The property corresponds to the field.',
    '该属性与这个字段相对应。',
    'The property corresponds to the user ID field.',
    '该属性与用户 ID 字段相对应。',
    'api',
    '[{"step_no":1,"label":"主干","sentence_en":"The property corresponds to the field.","sentence_zh":"该属性与这个字段相对应。","focus_text":"corresponds","note_zh":"先看属性与字段对应的主干。","segments":[{"text":"The property corresponds to the field","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The property corresponds to the user ID field.","sentence_zh":"该属性与用户 ID 字段相对应。","focus_text":"user ID","note_zh":"这一步补充字段表示的内容。","segments":[{"text":"The property corresponds to the ","kind":"core"},{"text":"user ID","kind":"modifier"},{"text":" field","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"property","text":"The property","kind":"core","group":"core"},{"id":"corresponds","text":"corresponds","kind":"action","group":"action"},{"id":"to-field","text":"to the field","kind":"core","group":"core"},{"id":"user-id","text":"user ID","kind":"modifier","group":"modifier"}],"links":[{"id":"corresponds->property","from":"corresponds","to":"property","kind":"core","label":"主干"},{"id":"corresponds->to-field","from":"corresponds","to":"to-field","kind":"core","label":"主干"},{"id":"user-id->to-field","from":"user-id","to":"to-field","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The property corresponds to the field.","sentence_zh":"该属性与这个字段相对应。","show_nodes":["property","corresponds","to-field"],"show_links":["corresponds->property","corresponds->to-field"],"focus_node":"corresponds","note_zh":"先看属性与字段对应的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The property corresponds to the user ID field.","sentence_zh":"该属性与用户 ID 字段相对应。","show_nodes":["user-id"],"show_links":["user-id->to-field"],"focus_node":"user-id","note_zh":"这一步补充字段表示的内容。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  steps_json = excluded.steps_json,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  steps_json,
  growth_json
) VALUES
  (
    'corrupt-primary',
    'corrupt',
    'corrupt',
    'corrupt a cache',
    '损坏缓存数据',
    'The partial write corrupted the cache.',
    '这次不完整写入损坏了缓存。',
    'The partial write corrupted the shared cache.',
    '这次不完整写入损坏了共享缓存。',
    'debug',
    '[{"step_no":1,"label":"主干","sentence_en":"The partial write corrupted the cache.","sentence_zh":"这次不完整写入损坏了缓存。","focus_text":"corrupted","note_zh":"先看不完整写入损坏缓存的主干。","segments":[{"text":"The partial write corrupted the cache","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The partial write corrupted the shared cache.","sentence_zh":"这次不完整写入损坏了共享缓存。","focus_text":"shared","note_zh":"这一步补充缓存的共享性质。","segments":[{"text":"The partial write corrupted the ","kind":"core"},{"text":"shared","kind":"modifier"},{"text":" cache","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"partial-write","text":"The partial write","kind":"core","group":"core"},{"id":"corrupted","text":"corrupted","kind":"action","group":"action"},{"id":"cache","text":"the cache","kind":"core","group":"core"},{"id":"shared","text":"shared","kind":"modifier","group":"modifier"}],"links":[{"id":"corrupted->partial-write","from":"corrupted","to":"partial-write","kind":"core","label":"主干"},{"id":"corrupted->cache","from":"corrupted","to":"cache","kind":"core","label":"主干"},{"id":"shared->cache","from":"shared","to":"cache","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The partial write corrupted the cache.","sentence_zh":"这次不完整写入损坏了缓存。","show_nodes":["partial-write","corrupted","cache"],"show_links":["corrupted->partial-write","corrupted->cache"],"focus_node":"corrupted","note_zh":"先看不完整写入损坏缓存的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The partial write corrupted the shared cache.","sentence_zh":"这次不完整写入损坏了共享缓存。","show_nodes":["shared"],"show_links":["shared->cache"],"focus_node":"shared","note_zh":"这一步补充缓存的共享性质。"}]}'
  ),
  (
    'cost-primary',
    'cost',
    'cost',
    'cost the team time',
    '使团队付出时间代价',
    'The delay cost the team three days.',
    '这次延误让团队损失了三天。',
    'The delay cost the team three days of testing time.',
    '这次延误让团队损失了三天的测试时间。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The delay cost the team three days.","sentence_zh":"这次延误让团队损失了三天。","focus_text":"cost","note_zh":"先看延误让团队损失三天的主干。","segments":[{"text":"The delay cost the team three days","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The delay cost the team three days of testing time.","sentence_zh":"这次延误让团队损失了三天的测试时间。","focus_text":"of testing time","note_zh":"这一步补充损失的是哪类时间。","segments":[{"text":"The delay cost the team three days ","kind":"core"},{"text":"of testing time","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"delay","text":"The delay","kind":"core","group":"core"},{"id":"cost","text":"cost","kind":"action","group":"action"},{"id":"team","text":"the team","kind":"core","group":"core"},{"id":"days","text":"three days","kind":"core","group":"core"},{"id":"of-testing-time","text":"of testing time","kind":"modifier","group":"modifier"}],"links":[{"id":"cost->delay","from":"cost","to":"delay","kind":"core","label":"主干"},{"id":"cost->team","from":"cost","to":"team","kind":"core","label":"主干"},{"id":"cost->days","from":"cost","to":"days","kind":"core","label":"主干"},{"id":"of-testing-time->days","from":"of-testing-time","to":"days","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The delay cost the team three days.","sentence_zh":"这次延误让团队损失了三天。","show_nodes":["delay","cost","team","days"],"show_links":["cost->delay","cost->team","cost->days"],"focus_node":"cost","note_zh":"先看延误让团队损失三天的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The delay cost the team three days of testing time.","sentence_zh":"这次延误让团队损失了三天的测试时间。","show_nodes":["of-testing-time"],"show_links":["of-testing-time->days"],"focus_node":"of-testing-time","note_zh":"这一步补充损失的是哪类时间。"}]}'
  ),
  (
    'could-primary',
    'could',
    'could',
    'could reduce latency',
    '可能降低延迟',
    'The cache could reduce latency.',
    '该缓存可能降低延迟。',
    'The cache could significantly reduce latency.',
    '该缓存可能显著降低延迟。',
    'runtime',
    '[{"step_no":1,"label":"主干","sentence_en":"The cache could reduce latency.","sentence_zh":"该缓存可能降低延迟。","focus_text":"could reduce","note_zh":"先看缓存可能降低延迟的主干。","segments":[{"text":"The cache could reduce latency","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The cache could significantly reduce latency.","sentence_zh":"该缓存可能显著降低延迟。","focus_text":"significantly","note_zh":"这一步说明可能达到的改善程度。","segments":[{"text":"The cache could ","kind":"core"},{"text":"significantly","kind":"modifier"},{"text":" reduce latency","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"cache","text":"The cache","kind":"core","group":"core"},{"id":"could-reduce","text":"could reduce","kind":"action","group":"action"},{"id":"latency","text":"latency","kind":"core","group":"core"},{"id":"significantly","text":"significantly","kind":"modifier","group":"modifier"}],"links":[{"id":"could-reduce->cache","from":"could-reduce","to":"cache","kind":"core","label":"主干"},{"id":"could-reduce->latency","from":"could-reduce","to":"latency","kind":"core","label":"主干"},{"id":"significantly->could-reduce","from":"significantly","to":"could-reduce","kind":"modifier","label":"程度"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The cache could reduce latency.","sentence_zh":"该缓存可能降低延迟。","show_nodes":["cache","could-reduce","latency"],"show_links":["could-reduce->cache","could-reduce->latency"],"focus_node":"could-reduce","note_zh":"先看缓存可能降低延迟的主干。"},{"step_no":2,"label":"程度","sentence_en":"The cache could significantly reduce latency.","sentence_zh":"该缓存可能显著降低延迟。","show_nodes":["significantly"],"show_links":["significantly->could-reduce"],"focus_node":"significantly","note_zh":"这一步说明可能达到的改善程度。"}]}'
  ),
  (
    'count-primary',
    'count',
    'count',
    'count active sessions',
    '统计活跃会话数量',
    'The query counts sessions.',
    '该查询统计会话数量。',
    'The query counts active sessions.',
    '该查询统计活跃会话数量。',
    'system',
    '[{"step_no":1,"label":"主干","sentence_en":"The query counts sessions.","sentence_zh":"该查询统计会话数量。","focus_text":"counts","note_zh":"先看查询统计会话数量的主干。","segments":[{"text":"The query counts sessions","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The query counts active sessions.","sentence_zh":"该查询统计活跃会话数量。","focus_text":"active","note_zh":"这一步补充被统计会话的状态。","segments":[{"text":"The query counts ","kind":"core"},{"text":"active","kind":"modifier"},{"text":" sessions","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"query","text":"The query","kind":"core","group":"core"},{"id":"counts","text":"counts","kind":"action","group":"action"},{"id":"sessions","text":"sessions","kind":"core","group":"core"},{"id":"active","text":"active","kind":"modifier","group":"modifier"}],"links":[{"id":"counts->query","from":"counts","to":"query","kind":"core","label":"主干"},{"id":"counts->sessions","from":"counts","to":"sessions","kind":"core","label":"主干"},{"id":"active->sessions","from":"active","to":"sessions","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The query counts sessions.","sentence_zh":"该查询统计会话数量。","show_nodes":["query","counts","sessions"],"show_links":["counts->query","counts->sessions"],"focus_node":"counts","note_zh":"先看查询统计会话数量的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The query counts active sessions.","sentence_zh":"该查询统计活跃会话数量。","show_nodes":["active"],"show_links":["active->sessions"],"focus_node":"active","note_zh":"这一步补充被统计会话的状态。"}]}'
  ),
  (
    'count-on-primary',
    'count-on',
    'count on',
    'count on backups',
    '依靠备份恢复数据',
    'We count on the backups.',
    '我们依靠这些备份。',
    'We count on the backups to restore customer data.',
    '我们依靠这些备份来恢复客户数据。',
    'system',
    '[{"step_no":1,"label":"主干","sentence_en":"We count on the backups.","sentence_zh":"我们依靠这些备份。","focus_text":"count on","note_zh":"先看我们依靠备份的主干。","segments":[{"text":"We count on the backups","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"目的","sentence_en":"We count on the backups to restore customer data.","sentence_zh":"我们依靠这些备份来恢复客户数据。","focus_text":"to restore customer data","note_zh":"这一步说明依靠备份的目的。","segments":[{"text":"We count on the backups ","kind":"core"},{"text":"to restore customer data","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"we","text":"We","kind":"core","group":"core"},{"id":"count-on","text":"count on","kind":"action","group":"action"},{"id":"backups","text":"the backups","kind":"core","group":"core"},{"id":"to-restore-customer-data","text":"to restore customer data","kind":"modifier","group":"modifier"}],"links":[{"id":"count-on->we","from":"count-on","to":"we","kind":"core","label":"主干"},{"id":"count-on->backups","from":"count-on","to":"backups","kind":"core","label":"主干"},{"id":"to-restore-customer-data->count-on","from":"to-restore-customer-data","to":"count-on","kind":"modifier","label":"目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We count on the backups.","sentence_zh":"我们依靠这些备份。","show_nodes":["we","count-on","backups"],"show_links":["count-on->we","count-on->backups"],"focus_node":"count-on","note_zh":"先看我们依靠备份的主干。"},{"step_no":2,"label":"目的","sentence_en":"We count on the backups to restore customer data.","sentence_zh":"我们依靠这些备份来恢复客户数据。","show_nodes":["to-restore-customer-data"],"show_links":["to-restore-customer-data->count-on"],"focus_node":"to-restore-customer-data","note_zh":"这一步说明依靠备份的目的。"}]}'
  ),
  (
    'cover-primary',
    'cover',
    'cover',
    'cover edge cases',
    '覆盖边界情况',
    'The tests cover cases.',
    '这些测试覆盖了一些情况。',
    'The tests cover edge cases.',
    '这些测试覆盖了边界情况。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"The tests cover cases.","sentence_zh":"这些测试覆盖了一些情况。","focus_text":"cover","note_zh":"先看测试覆盖情况的主干。","segments":[{"text":"The tests cover cases","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The tests cover edge cases.","sentence_zh":"这些测试覆盖了边界情况。","focus_text":"edge","note_zh":"这一步补充所覆盖情况的类型。","segments":[{"text":"The tests cover ","kind":"core"},{"text":"edge","kind":"modifier"},{"text":" cases","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"tests","text":"The tests","kind":"core","group":"core"},{"id":"cover","text":"cover","kind":"action","group":"action"},{"id":"cases","text":"cases","kind":"core","group":"core"},{"id":"edge","text":"edge","kind":"modifier","group":"modifier"}],"links":[{"id":"cover->tests","from":"cover","to":"tests","kind":"core","label":"主干"},{"id":"cover->cases","from":"cover","to":"cases","kind":"core","label":"主干"},{"id":"edge->cases","from":"edge","to":"cases","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The tests cover cases.","sentence_zh":"这些测试覆盖了一些情况。","show_nodes":["tests","cover","cases"],"show_links":["cover->tests","cover->cases"],"focus_node":"cover","note_zh":"先看测试覆盖情况的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The tests cover edge cases.","sentence_zh":"这些测试覆盖了边界情况。","show_nodes":["edge"],"show_links":["edge->cases"],"focus_node":"edge","note_zh":"这一步补充所覆盖情况的类型。"}]}'
  ),
  (
    'cover-for-primary',
    'cover-for',
    'cover for',
    'cover for a teammate',
    '临时代替同事工作',
    'I covered for my teammate.',
    '我临时代替了我的同事。',
    'I covered for my teammate during her vacation.',
    '我在同事休假期间临时代替了她。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"I covered for my teammate.","sentence_zh":"我临时代替了我的同事。","focus_text":"covered for","note_zh":"先看我临时代替同事的主干。","segments":[{"text":"I covered for my teammate","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"时间","sentence_en":"I covered for my teammate during her vacation.","sentence_zh":"我在同事休假期间临时代替了她。","focus_text":"during her vacation","note_zh":"这一步说明代班发生的时间。","segments":[{"text":"I covered for my teammate ","kind":"core"},{"text":"during her vacation","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"i","text":"I","kind":"core","group":"core"},{"id":"covered-for","text":"covered for","kind":"action","group":"action"},{"id":"teammate","text":"my teammate","kind":"core","group":"core"},{"id":"during-her-vacation","text":"during her vacation","kind":"modifier","group":"modifier"}],"links":[{"id":"covered-for->i","from":"covered-for","to":"i","kind":"core","label":"主干"},{"id":"covered-for->teammate","from":"covered-for","to":"teammate","kind":"core","label":"主干"},{"id":"during-her-vacation->covered-for","from":"during-her-vacation","to":"covered-for","kind":"modifier","label":"时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I covered for my teammate.","sentence_zh":"我临时代替了我的同事。","show_nodes":["i","covered-for","teammate"],"show_links":["covered-for->i","covered-for->teammate"],"focus_node":"covered-for","note_zh":"先看我临时代替同事的主干。"},{"step_no":2,"label":"时间","sentence_en":"I covered for my teammate during her vacation.","sentence_zh":"我在同事休假期间临时代替了她。","show_nodes":["during-her-vacation"],"show_links":["during-her-vacation->covered-for"],"focus_node":"during-her-vacation","note_zh":"这一步说明代班发生的时间。"}]}'
  ),
  (
    'crack-down-primary',
    'crack-down',
    'crack down',
    'crack down on abuse',
    '严厉打击滥用行为',
    'The platform cracked down on abuse.',
    '该平台严厉打击了滥用行为。',
    'The platform cracked down on automated abuse.',
    '该平台严厉打击了自动化滥用行为。',
    'security',
    '[{"step_no":1,"label":"主干","sentence_en":"The platform cracked down on abuse.","sentence_zh":"该平台严厉打击了滥用行为。","focus_text":"cracked down","note_zh":"先看平台严厉打击滥用行为的主干。","segments":[{"text":"The platform cracked down on abuse","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The platform cracked down on automated abuse.","sentence_zh":"该平台严厉打击了自动化滥用行为。","focus_text":"automated","note_zh":"这一步补充被打击行为的类型。","segments":[{"text":"The platform cracked down on ","kind":"core"},{"text":"automated","kind":"modifier"},{"text":" abuse","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"platform","text":"The platform","kind":"core","group":"core"},{"id":"cracked-down","text":"cracked down","kind":"action","group":"action"},{"id":"on-abuse","text":"on abuse","kind":"core","group":"core"},{"id":"automated","text":"automated","kind":"modifier","group":"modifier"}],"links":[{"id":"cracked-down->platform","from":"cracked-down","to":"platform","kind":"core","label":"主干"},{"id":"cracked-down->on-abuse","from":"cracked-down","to":"on-abuse","kind":"core","label":"主干"},{"id":"automated->on-abuse","from":"automated","to":"on-abuse","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The platform cracked down on abuse.","sentence_zh":"该平台严厉打击了滥用行为。","show_nodes":["platform","cracked-down","on-abuse"],"show_links":["cracked-down->platform","cracked-down->on-abuse"],"focus_node":"cracked-down","note_zh":"先看平台严厉打击滥用行为的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The platform cracked down on automated abuse.","sentence_zh":"该平台严厉打击了自动化滥用行为。","show_nodes":["automated"],"show_links":["automated->on-abuse"],"focus_node":"automated","note_zh":"这一步补充被打击行为的类型。"}]}'
  ),
  (
    'craft-primary',
    'craft',
    'craft',
    'craft an error message',
    '精心编写错误信息',
    'The writer crafted an error message.',
    '文案人员精心编写了一条错误信息。',
    'The writer crafted a clear error message.',
    '文案人员精心编写了一条清晰的错误信息。',
    'frontend',
    '[{"step_no":1,"label":"主干","sentence_en":"The writer crafted an error message.","sentence_zh":"文案人员精心编写了一条错误信息。","focus_text":"crafted","note_zh":"先看文案人员精心编写错误信息的主干。","segments":[{"text":"The writer crafted an error message","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The writer crafted a clear error message.","sentence_zh":"文案人员精心编写了一条清晰的错误信息。","focus_text":"clear","note_zh":"这一步补充错误信息的特点。","segments":[{"text":"The writer crafted a ","kind":"core"},{"text":"clear","kind":"modifier"},{"text":" error message","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"writer","text":"The writer","kind":"core","group":"core"},{"id":"crafted","text":"crafted","kind":"action","group":"action"},{"id":"message","text":"an error message","kind":"core","group":"core"},{"id":"clear","text":"clear","kind":"modifier","group":"modifier"}],"links":[{"id":"crafted->writer","from":"crafted","to":"writer","kind":"core","label":"主干"},{"id":"crafted->message","from":"crafted","to":"message","kind":"core","label":"主干"},{"id":"clear->message","from":"clear","to":"message","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The writer crafted an error message.","sentence_zh":"文案人员精心编写了一条错误信息。","show_nodes":["writer","crafted","message"],"show_links":["crafted->writer","crafted->message"],"focus_node":"crafted","note_zh":"先看文案人员精心编写错误信息的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The writer crafted a clear error message.","sentence_zh":"文案人员精心编写了一条清晰的错误信息。","show_nodes":["clear"],"show_links":["clear->message"],"focus_node":"clear","note_zh":"这一步补充错误信息的特点。"}]}'
  ),
  (
    'crash-primary',
    'crash',
    'crash',
    'crash under load',
    '在负载下崩溃',
    'The server crashed.',
    '服务器崩溃了。',
    'The server crashed under load.',
    '服务器在负载下崩溃了。',
    'runtime',
    '[{"step_no":1,"label":"主干","sentence_en":"The server crashed.","sentence_zh":"服务器崩溃了。","focus_text":"crashed","note_zh":"先看服务器崩溃的主干。","segments":[{"text":"The server crashed","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"条件","sentence_en":"The server crashed under load.","sentence_zh":"服务器在负载下崩溃了。","focus_text":"under load","note_zh":"这一步说明服务器崩溃时的条件。","segments":[{"text":"The server crashed ","kind":"core"},{"text":"under load","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"server","text":"The server","kind":"core","group":"core"},{"id":"crashed","text":"crashed","kind":"action","group":"action"},{"id":"under-load","text":"under load","kind":"modifier","group":"modifier"}],"links":[{"id":"crashed->server","from":"crashed","to":"server","kind":"core","label":"主干"},{"id":"under-load->crashed","from":"under-load","to":"crashed","kind":"modifier","label":"条件"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The server crashed.","sentence_zh":"服务器崩溃了。","show_nodes":["server","crashed"],"show_links":["crashed->server"],"focus_node":"crashed","note_zh":"先看服务器崩溃的主干。"},{"step_no":2,"label":"条件","sentence_en":"The server crashed under load.","sentence_zh":"服务器在负载下崩溃了。","show_nodes":["under-load"],"show_links":["under-load->crashed"],"focus_node":"under-load","note_zh":"这一步说明服务器崩溃时的条件。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  steps_json = excluded.steps_json,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  steps_json,
  growth_json
) VALUES
  (
    'crawl-primary',
    'crawl',
    'crawl',
    'crawl product pages',
    '爬取产品页面',
    'The bot crawls pages.',
    '该机器人爬取页面。',
    'The bot crawls product pages.',
    '该机器人爬取产品页面。',
    'system',
    '[{"step_no":1,"label":"主干","sentence_en":"The bot crawls pages.","sentence_zh":"该机器人爬取页面。","focus_text":"crawls","note_zh":"先看机器人爬取页面的主干。","segments":[{"text":"The bot crawls pages","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The bot crawls product pages.","sentence_zh":"该机器人爬取产品页面。","focus_text":"product","note_zh":"这一步补充被爬取页面的类型。","segments":[{"text":"The bot crawls ","kind":"core"},{"text":"product","kind":"modifier"},{"text":" pages","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"bot","text":"The bot","kind":"core","group":"core"},{"id":"crawls","text":"crawls","kind":"action","group":"action"},{"id":"pages","text":"pages","kind":"core","group":"core"},{"id":"product","text":"product","kind":"modifier","group":"modifier"}],"links":[{"id":"crawls->bot","from":"crawls","to":"bot","kind":"core","label":"主干"},{"id":"crawls->pages","from":"crawls","to":"pages","kind":"core","label":"主干"},{"id":"product->pages","from":"product","to":"pages","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The bot crawls pages.","sentence_zh":"该机器人爬取页面。","show_nodes":["bot","crawls","pages"],"show_links":["crawls->bot","crawls->pages"],"focus_node":"crawls","note_zh":"先看机器人爬取页面的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The bot crawls product pages.","sentence_zh":"该机器人爬取产品页面。","show_nodes":["product"],"show_links":["product->pages"],"focus_node":"product","note_zh":"这一步补充被爬取页面的类型。"}]}'
  ),
  (
    'criticize-primary',
    'criticize',
    'criticize',
    'criticize a proposal',
    '批评方案',
    'The reviewers criticized the proposal.',
    '评审人员批评了这个方案。',
    'The reviewers criticized the proposal for ignoring security risks.',
    '评审人员批评该方案忽视了安全风险。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The reviewers criticized the proposal.","sentence_zh":"评审人员批评了这个方案。","focus_text":"criticized","note_zh":"先看评审人员批评方案的主干。","segments":[{"text":"The reviewers criticized the proposal","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"原因","sentence_en":"The reviewers criticized the proposal for ignoring security risks.","sentence_zh":"评审人员批评该方案忽视了安全风险。","focus_text":"for ignoring security risks","note_zh":"这一步说明方案受到批评的原因。","segments":[{"text":"The reviewers criticized the proposal ","kind":"core"},{"text":"for ignoring security risks","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"reviewers","text":"The reviewers","kind":"core","group":"core"},{"id":"criticized","text":"criticized","kind":"action","group":"action"},{"id":"proposal","text":"the proposal","kind":"core","group":"core"},{"id":"for-ignoring-security-risks","text":"for ignoring security risks","kind":"modifier","group":"modifier"}],"links":[{"id":"criticized->reviewers","from":"criticized","to":"reviewers","kind":"core","label":"主干"},{"id":"criticized->proposal","from":"criticized","to":"proposal","kind":"core","label":"主干"},{"id":"for-ignoring-security-risks->criticized","from":"for-ignoring-security-risks","to":"criticized","kind":"modifier","label":"原因"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The reviewers criticized the proposal.","sentence_zh":"评审人员批评了这个方案。","show_nodes":["reviewers","criticized","proposal"],"show_links":["criticized->reviewers","criticized->proposal"],"focus_node":"criticized","note_zh":"先看评审人员批评方案的主干。"},{"step_no":2,"label":"原因","sentence_en":"The reviewers criticized the proposal for ignoring security risks.","sentence_zh":"评审人员批评该方案忽视了安全风险。","show_nodes":["for-ignoring-security-risks"],"show_links":["for-ignoring-security-risks->criticized"],"focus_node":"for-ignoring-security-risks","note_zh":"这一步说明方案受到批评的原因。"}]}'
  ),
  (
    'cross-primary',
    'cross',
    'cross',
    'cross a boundary',
    '越过边界',
    'The request crossed the boundary.',
    '该请求越过了边界。',
    'The request crossed the trust boundary.',
    '该请求越过了信任边界。',
    'security',
    '[{"step_no":1,"label":"主干","sentence_en":"The request crossed the boundary.","sentence_zh":"该请求越过了边界。","focus_text":"crossed","note_zh":"先看请求越过边界的主干。","segments":[{"text":"The request crossed the boundary","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The request crossed the trust boundary.","sentence_zh":"该请求越过了信任边界。","focus_text":"trust","note_zh":"这一步补充边界的类型。","segments":[{"text":"The request crossed the ","kind":"core"},{"text":"trust","kind":"modifier"},{"text":" boundary","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"request","text":"The request","kind":"core","group":"core"},{"id":"crossed","text":"crossed","kind":"action","group":"action"},{"id":"boundary","text":"the boundary","kind":"core","group":"core"},{"id":"trust","text":"trust","kind":"modifier","group":"modifier"}],"links":[{"id":"crossed->request","from":"crossed","to":"request","kind":"core","label":"主干"},{"id":"crossed->boundary","from":"crossed","to":"boundary","kind":"core","label":"主干"},{"id":"trust->boundary","from":"trust","to":"boundary","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The request crossed the boundary.","sentence_zh":"该请求越过了边界。","show_nodes":["request","crossed","boundary"],"show_links":["crossed->request","crossed->boundary"],"focus_node":"crossed","note_zh":"先看请求越过边界的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The request crossed the trust boundary.","sentence_zh":"该请求越过了信任边界。","show_nodes":["trust"],"show_links":["trust->boundary"],"focus_node":"trust","note_zh":"这一步补充边界的类型。"}]}'
  ),
  (
    'cross-sell-primary',
    'cross-sell',
    'cross-sell',
    'cross-sell a service',
    '向客户交叉销售服务',
    'The team cross-sold the service.',
    '团队交叉销售了这项服务。',
    'The team cross-sold the service to existing customers.',
    '团队向现有客户交叉销售了这项服务。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The team cross-sold the service.","sentence_zh":"团队交叉销售了这项服务。","focus_text":"cross-sold","note_zh":"先看团队交叉销售服务的主干。","segments":[{"text":"The team cross-sold the service","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"范围","sentence_en":"The team cross-sold the service to existing customers.","sentence_zh":"团队向现有客户交叉销售了这项服务。","focus_text":"to existing customers","note_zh":"这一步说明交叉销售面向的客户范围。","segments":[{"text":"The team cross-sold the service ","kind":"core"},{"text":"to existing customers","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"team","text":"The team","kind":"core","group":"core"},{"id":"cross-sold","text":"cross-sold","kind":"action","group":"action"},{"id":"service","text":"the service","kind":"core","group":"core"},{"id":"to-existing-customers","text":"to existing customers","kind":"modifier","group":"modifier"}],"links":[{"id":"cross-sold->team","from":"cross-sold","to":"team","kind":"core","label":"主干"},{"id":"cross-sold->service","from":"cross-sold","to":"service","kind":"core","label":"主干"},{"id":"to-existing-customers->cross-sold","from":"to-existing-customers","to":"cross-sold","kind":"modifier","label":"范围"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team cross-sold the service.","sentence_zh":"团队交叉销售了这项服务。","show_nodes":["team","cross-sold","service"],"show_links":["cross-sold->team","cross-sold->service"],"focus_node":"cross-sold","note_zh":"先看团队交叉销售服务的主干。"},{"step_no":2,"label":"范围","sentence_en":"The team cross-sold the service to existing customers.","sentence_zh":"团队向现有客户交叉销售了这项服务。","show_nodes":["to-existing-customers"],"show_links":["to-existing-customers->cross-sold"],"focus_node":"to-existing-customers","note_zh":"这一步说明交叉销售面向的客户范围。"}]}'
  ),
  (
    'cry-primary',
    'cry',
    'cry',
    'cry with relief',
    '如释重负地哭',
    'Lena cried.',
    '莉娜哭了。',
    'Lena cried with relief.',
    '莉娜如释重负地哭了。',
    'daily-life',
    '[{"step_no":1,"label":"主干","sentence_en":"Lena cried.","sentence_zh":"莉娜哭了。","focus_text":"cried","note_zh":"先看莉娜哭了的主干。","segments":[{"text":"Lena cried","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"原因","sentence_en":"Lena cried with relief.","sentence_zh":"莉娜如释重负地哭了。","focus_text":"with relief","note_zh":"这一步说明她哭泣时的情绪原因。","segments":[{"text":"Lena cried ","kind":"core"},{"text":"with relief","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"lena","text":"Lena","kind":"core","group":"core"},{"id":"cried","text":"cried","kind":"action","group":"action"},{"id":"with-relief","text":"with relief","kind":"modifier","group":"modifier"}],"links":[{"id":"cried->lena","from":"cried","to":"lena","kind":"core","label":"主干"},{"id":"with-relief->cried","from":"with-relief","to":"cried","kind":"modifier","label":"原因"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Lena cried.","sentence_zh":"莉娜哭了。","show_nodes":["lena","cried"],"show_links":["cried->lena"],"focus_node":"cried","note_zh":"先看莉娜哭了的主干。"},{"step_no":2,"label":"原因","sentence_en":"Lena cried with relief.","sentence_zh":"莉娜如释重负地哭了。","show_nodes":["with-relief"],"show_links":["with-relief->cried"],"focus_node":"with-relief","note_zh":"这一步说明她哭泣时的情绪原因。"}]}'
  ),
  (
    'cure-primary',
    'cure',
    'cure',
    'cure a timeout problem',
    '解决超时问题',
    'The index cured the problem.',
    '该索引解决了这个问题。',
    'The index cured the timeout problem.',
    '该索引解决了超时问题。',
    'debug',
    '[{"step_no":1,"label":"主干","sentence_en":"The index cured the problem.","sentence_zh":"该索引解决了这个问题。","focus_text":"cured","note_zh":"先看索引解决问题的主干。","segments":[{"text":"The index cured the problem","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The index cured the timeout problem.","sentence_zh":"该索引解决了超时问题。","focus_text":"timeout","note_zh":"这一步补充所解决问题的类型。","segments":[{"text":"The index cured the ","kind":"core"},{"text":"timeout","kind":"modifier"},{"text":" problem","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"index","text":"The index","kind":"core","group":"core"},{"id":"cured","text":"cured","kind":"action","group":"action"},{"id":"problem","text":"the problem","kind":"core","group":"core"},{"id":"timeout","text":"timeout","kind":"modifier","group":"modifier"}],"links":[{"id":"cured->index","from":"cured","to":"index","kind":"core","label":"主干"},{"id":"cured->problem","from":"cured","to":"problem","kind":"core","label":"主干"},{"id":"timeout->problem","from":"timeout","to":"problem","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The index cured the problem.","sentence_zh":"该索引解决了这个问题。","show_nodes":["index","cured","problem"],"show_links":["cured->index","cured->problem"],"focus_node":"cured","note_zh":"先看索引解决问题的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The index cured the timeout problem.","sentence_zh":"该索引解决了超时问题。","show_nodes":["timeout"],"show_links":["timeout->problem"],"focus_node":"timeout","note_zh":"这一步补充所解决问题的类型。"}]}'
  ),
  (
    'customize-primary',
    'customize',
    'customize',
    'customize a dashboard',
    '定制仪表板',
    'Admins customize the dashboard.',
    '管理员定制仪表板。',
    'Admins customize the dashboard for each team.',
    '管理员为每个团队定制仪表板。',
    'frontend',
    '[{"step_no":1,"label":"主干","sentence_en":"Admins customize the dashboard.","sentence_zh":"管理员定制仪表板。","focus_text":"customize","note_zh":"先看管理员定制仪表板的主干。","segments":[{"text":"Admins customize the dashboard","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"范围","sentence_en":"Admins customize the dashboard for each team.","sentence_zh":"管理员为每个团队定制仪表板。","focus_text":"for each team","note_zh":"这一步说明定制所面向的团队范围。","segments":[{"text":"Admins customize the dashboard ","kind":"core"},{"text":"for each team","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"admins","text":"Admins","kind":"core","group":"core"},{"id":"customize","text":"customize","kind":"action","group":"action"},{"id":"dashboard","text":"the dashboard","kind":"core","group":"core"},{"id":"for-each-team","text":"for each team","kind":"modifier","group":"modifier"}],"links":[{"id":"customize->admins","from":"customize","to":"admins","kind":"core","label":"主干"},{"id":"customize->dashboard","from":"customize","to":"dashboard","kind":"core","label":"主干"},{"id":"for-each-team->customize","from":"for-each-team","to":"customize","kind":"modifier","label":"范围"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Admins customize the dashboard.","sentence_zh":"管理员定制仪表板。","show_nodes":["admins","customize","dashboard"],"show_links":["customize->admins","customize->dashboard"],"focus_node":"customize","note_zh":"先看管理员定制仪表板的主干。"},{"step_no":2,"label":"范围","sentence_en":"Admins customize the dashboard for each team.","sentence_zh":"管理员为每个团队定制仪表板。","show_nodes":["for-each-team"],"show_links":["for-each-team->customize"],"focus_node":"for-each-team","note_zh":"这一步说明定制所面向的团队范围。"}]}'
  ),
  (
    'cut-primary',
    'cut',
    'cut',
    'cut cloud costs',
    '削减云成本',
    'The change cut costs.',
    '这项改动削减了成本。',
    'The change cut cloud costs.',
    '这项改动削减了云成本。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The change cut costs.","sentence_zh":"这项改动削减了成本。","focus_text":"cut","note_zh":"先看改动削减成本的主干。","segments":[{"text":"The change cut costs","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The change cut cloud costs.","sentence_zh":"这项改动削减了云成本。","focus_text":"cloud","note_zh":"这一步补充被削减成本的类型。","segments":[{"text":"The change cut ","kind":"core"},{"text":"cloud","kind":"modifier"},{"text":" costs","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"change","text":"The change","kind":"core","group":"core"},{"id":"cut","text":"cut","kind":"action","group":"action"},{"id":"costs","text":"costs","kind":"core","group":"core"},{"id":"cloud","text":"cloud","kind":"modifier","group":"modifier"}],"links":[{"id":"cut->change","from":"cut","to":"change","kind":"core","label":"主干"},{"id":"cut->costs","from":"cut","to":"costs","kind":"core","label":"主干"},{"id":"cloud->costs","from":"cloud","to":"costs","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The change cut costs.","sentence_zh":"这项改动削减了成本。","show_nodes":["change","cut","costs"],"show_links":["cut->change","cut->costs"],"focus_node":"cut","note_zh":"先看改动削减成本的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The change cut cloud costs.","sentence_zh":"这项改动削减了云成本。","show_nodes":["cloud"],"show_links":["cloud->costs"],"focus_node":"cloud","note_zh":"这一步补充被削减成本的类型。"}]}'
  ),
  (
    'cut-back-primary',
    'cut-back',
    'cut back',
    'cut back on spending',
    '缩减支出',
    'The company cut back on spending.',
    '公司缩减了支出。',
    'The company cut back on cloud spending.',
    '公司缩减了云服务支出。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The company cut back on spending.","sentence_zh":"公司缩减了支出。","focus_text":"cut back","note_zh":"先看公司缩减支出的主干。","segments":[{"text":"The company cut back on spending","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The company cut back on cloud spending.","sentence_zh":"公司缩减了云服务支出。","focus_text":"cloud","note_zh":"这一步补充被缩减支出的类型。","segments":[{"text":"The company cut back on ","kind":"core"},{"text":"cloud","kind":"modifier"},{"text":" spending","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"company","text":"The company","kind":"core","group":"core"},{"id":"cut-back","text":"cut back","kind":"action","group":"action"},{"id":"on-spending","text":"on spending","kind":"core","group":"core"},{"id":"cloud","text":"cloud","kind":"modifier","group":"modifier"}],"links":[{"id":"cut-back->company","from":"cut-back","to":"company","kind":"core","label":"主干"},{"id":"cut-back->on-spending","from":"cut-back","to":"on-spending","kind":"core","label":"主干"},{"id":"cloud->on-spending","from":"cloud","to":"on-spending","kind":"modifier","label":"对象细节"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The company cut back on spending.","sentence_zh":"公司缩减了支出。","show_nodes":["company","cut-back","on-spending"],"show_links":["cut-back->company","cut-back->on-spending"],"focus_node":"cut-back","note_zh":"先看公司缩减支出的主干。"},{"step_no":2,"label":"对象细节","sentence_en":"The company cut back on cloud spending.","sentence_zh":"公司缩减了云服务支出。","show_nodes":["cloud"],"show_links":["cloud->on-spending"],"focus_node":"cloud","note_zh":"这一步补充被缩减支出的类型。"}]}'
  ),
  (
    'cut-in-primary',
    'cut-in',
    'cut in',
    'cut in during a call',
    '在通话中插嘴',
    'Alex cut in.',
    '亚历克斯插嘴了。',
    'Alex cut in during the call.',
    '亚历克斯在通话中插嘴了。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"Alex cut in.","sentence_zh":"亚历克斯插嘴了。","focus_text":"cut in","note_zh":"先看亚历克斯插嘴的主干。","segments":[{"text":"Alex cut in","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"场景","sentence_en":"Alex cut in during the call.","sentence_zh":"亚历克斯在通话中插嘴了。","focus_text":"during the call","note_zh":"这一步说明插嘴发生的场景。","segments":[{"text":"Alex cut in ","kind":"core"},{"text":"during the call","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"alex","text":"Alex","kind":"core","group":"core"},{"id":"cut-in","text":"cut in","kind":"action","group":"action"},{"id":"during-the-call","text":"during the call","kind":"modifier","group":"modifier"}],"links":[{"id":"cut-in->alex","from":"cut-in","to":"alex","kind":"core","label":"主干"},{"id":"during-the-call->cut-in","from":"during-the-call","to":"cut-in","kind":"modifier","label":"场景"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Alex cut in.","sentence_zh":"亚历克斯插嘴了。","show_nodes":["alex","cut-in"],"show_links":["cut-in->alex"],"focus_node":"cut-in","note_zh":"先看亚历克斯插嘴的主干。"},{"step_no":2,"label":"场景","sentence_en":"Alex cut in during the call.","sentence_zh":"亚历克斯在通话中插嘴了。","show_nodes":["during-the-call"],"show_links":["during-the-call->cut-in"],"focus_node":"during-the-call","note_zh":"这一步说明插嘴发生的场景。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  steps_json = excluded.steps_json,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
