-- Generated verb paths batch batch-003.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  steps_json,
  growth_json
) VALUES
  (
    'pose-primary',
    'pose',
    'pose',
    'pose a security risk',
    '造成安全风险',
    'Outdated dependencies pose a security risk.',
    '过时的依赖会造成安全风险。',
    'Outdated dependencies with known vulnerabilities pose a security risk in production.',
    '带有已知漏洞的过时依赖会在生产环境中造成安全风险。',
    'security-review',
    '[{"step_no":1,"label":"主干","sentence_en":"Outdated dependencies pose a security risk.","sentence_zh":"过时的依赖会造成安全风险。","focus_text":"pose","note_zh":"先看核心：过时的依赖会造成安全风险。","segments":[{"text":"Outdated dependencies pose a security risk","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"Outdated dependencies pose a security risk in production.","sentence_zh":"过时的依赖会在生产环境中造成安全风险。","focus_text":"in production","note_zh":"这一步说明安全风险出现在生产环境中。","segments":[{"text":"Outdated dependencies pose a security risk ","kind":"core"},{"text":"in production","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点对象细节","sentence_en":"Outdated dependencies with known vulnerabilities pose a security risk in production.","sentence_zh":"带有已知漏洞的过时依赖会在生产环境中造成安全风险。","focus_text":"with known vulnerabilities","note_zh":"这一步说明这些依赖本身带有已知漏洞。","segments":[{"text":"Outdated dependencies ","kind":"core"},{"text":"with known vulnerabilities","kind":"modifier"},{"text":" pose a security risk in production","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"outdated-dependencies","text":"Outdated dependencies","kind":"core","group":"core"},{"id":"pose","text":"pose","kind":"action","group":"action"},{"id":"a-security-risk","text":"a security risk","kind":"core","group":"core"},{"id":"in-production","text":"in production","kind":"modifier","group":"modifier"},{"id":"with-known-vulnerabilities","text":"with known vulnerabilities","kind":"modifier","group":"modifier"}],"links":[{"id":"pose->outdated-dependencies","from":"pose","to":"outdated-dependencies","kind":"core","label":"什么造成风险"},{"id":"pose->a-security-risk","from":"pose","to":"a-security-risk","kind":"core","label":"造成什么"},{"id":"in-production->a-security-risk","from":"in-production","to":"a-security-risk","kind":"modifier","label":"说明风险的场景"},{"id":"with-known-vulnerabilities->outdated-dependencies","from":"with-known-vulnerabilities","to":"outdated-dependencies","kind":"modifier","label":"说明依赖的特征"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Outdated dependencies pose a security risk.","sentence_zh":"过时的依赖会造成安全风险。","show_nodes":["outdated-dependencies","pose","a-security-risk"],"show_links":["pose->outdated-dependencies","pose->a-security-risk"],"focus_node":"pose","note_zh":"先看核心：过时的依赖会造成安全风险。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"Outdated dependencies pose a security risk in production.","sentence_zh":"过时的依赖会在生产环境中造成安全风险。","show_nodes":["in-production"],"show_links":["in-production->a-security-risk"],"focus_node":"in-production","note_zh":"这一步说明安全风险出现在生产环境中。"},{"step_no":3,"label":"加一点对象细节","sentence_en":"Outdated dependencies with known vulnerabilities pose a security risk in production.","sentence_zh":"带有已知漏洞的过时依赖会在生产环境中造成安全风险。","show_nodes":["with-known-vulnerabilities"],"show_links":["with-known-vulnerabilities->outdated-dependencies"],"focus_node":"with-known-vulnerabilities","note_zh":"这一步说明这些依赖本身带有已知漏洞。"}]}'
  ),
  (
    'position-primary',
    'position',
    'position',
    'position a product',
    '定位产品',
    'The marketing team positioned the app.',
    '市场团队给这款应用做了定位。',
    'The marketing team positioned the app as a premium tool for professional designers.',
    '市场团队把这款应用定位为面向专业设计师的高端工具。',
    'marketing',
    '[{"step_no":1,"label":"主干","sentence_en":"The marketing team positioned the app.","sentence_zh":"市场团队给这款应用做了定位。","focus_text":"positioned","note_zh":"先看核心：市场团队对应用进行了定位。","segments":[{"text":"The marketing team positioned the app","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点方式","sentence_en":"The marketing team positioned the app as a premium tool.","sentence_zh":"市场团队把这款应用定位为高端工具。","focus_text":"as a premium tool","note_zh":"这一步说明定位成什么类型的产品。","segments":[{"text":"The marketing team positioned the app ","kind":"core"},{"text":"as a premium tool","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点对象细节","sentence_en":"The marketing team positioned the app as a premium tool for professional designers.","sentence_zh":"市场团队把这款应用定位为面向专业设计师的高端工具。","focus_text":"for professional designers","note_zh":"这一步说明目标用户群体是专业设计师。","segments":[{"text":"The marketing team positioned the app as a premium tool ","kind":"core"},{"text":"for professional designers","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-marketing-team","text":"The marketing team","kind":"core","group":"core"},{"id":"positioned","text":"positioned","kind":"action","group":"action"},{"id":"the-app","text":"the app","kind":"core","group":"core"},{"id":"as-a-premium-tool","text":"as a premium tool","kind":"modifier","group":"modifier"},{"id":"for-professional-designers","text":"for professional designers","kind":"modifier","group":"modifier"}],"links":[{"id":"positioned->the-marketing-team","from":"positioned","to":"the-marketing-team","kind":"core","label":"谁定位产品"},{"id":"positioned->the-app","from":"positioned","to":"the-app","kind":"core","label":"定位什么"},{"id":"as-a-premium-tool->positioned","from":"as-a-premium-tool","to":"positioned","kind":"modifier","label":"说明定位成什么"},{"id":"for-professional-designers->the-app","from":"for-professional-designers","to":"the-app","kind":"modifier","label":"说明目标用户群"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The marketing team positioned the app.","sentence_zh":"市场团队给这款应用做了定位。","show_nodes":["the-marketing-team","positioned","the-app"],"show_links":["positioned->the-marketing-team","positioned->the-app"],"focus_node":"positioned","note_zh":"先看核心：市场团队对应用进行了定位。"},{"step_no":2,"label":"加一点方式","sentence_en":"The marketing team positioned the app as a premium tool.","sentence_zh":"市场团队把这款应用定位为高端工具。","show_nodes":["as-a-premium-tool"],"show_links":["as-a-premium-tool->positioned"],"focus_node":"as-a-premium-tool","note_zh":"这一步说明定位成什么类型的产品。"},{"step_no":3,"label":"加一点对象细节","sentence_en":"The marketing team positioned the app as a premium tool for professional designers.","sentence_zh":"市场团队把这款应用定位为面向专业设计师的高端工具。","show_nodes":["for-professional-designers"],"show_links":["for-professional-designers->the-app"],"focus_node":"for-professional-designers","note_zh":"这一步说明目标用户群体是专业设计师。"}]}'
  ),
  (
    'post-primary',
    'post',
    'post',
    'post an update',
    '发布更新',
    'The dev lead posted an update.',
    '开发组长发布了一条更新。',
    'The dev lead posted an update in the Slack channel after the standup.',
    '站会后，开发组长在 Slack 频道里发布了一条更新。',
    'team-chat',
    '[{"step_no":1,"label":"主干","sentence_en":"The dev lead posted an update.","sentence_zh":"开发组长发布了一条更新。","focus_text":"posted","note_zh":"先看核心：开发组长发布了一条更新。","segments":[{"text":"The dev lead posted an update","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点方式","sentence_en":"The dev lead posted an update in the Slack channel.","sentence_zh":"开发组长在 Slack 频道里发布了一条更新。","focus_text":"in the Slack channel","note_zh":"这一步说明更新发布在什么地方。","segments":[{"text":"The dev lead posted an update ","kind":"core"},{"text":"in the Slack channel","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点时间","sentence_en":"The dev lead posted an update in the Slack channel after the standup.","sentence_zh":"站会后，开发组长在 Slack 频道里发布了一条更新。","focus_text":"after the standup","note_zh":"这一步说明发布更新的具体时间。","segments":[{"text":"The dev lead posted an update in the Slack channel ","kind":"core"},{"text":"after the standup","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-dev-lead","text":"The dev lead","kind":"core","group":"core"},{"id":"posted","text":"posted","kind":"action","group":"action"},{"id":"an-update","text":"an update","kind":"core","group":"core"},{"id":"in-the-slack-channel","text":"in the Slack channel","kind":"modifier","group":"modifier"},{"id":"after-the-standup","text":"after the standup","kind":"modifier","group":"modifier"}],"links":[{"id":"posted->the-dev-lead","from":"posted","to":"the-dev-lead","kind":"core","label":"谁发布更新"},{"id":"posted->an-update","from":"posted","to":"an-update","kind":"core","label":"发布什么"},{"id":"in-the-slack-channel->posted","from":"in-the-slack-channel","to":"posted","kind":"modifier","label":"说明发布渠道"},{"id":"after-the-standup->posted","from":"after-the-standup","to":"posted","kind":"modifier","label":"说明发布时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The dev lead posted an update.","sentence_zh":"开发组长发布了一条更新。","show_nodes":["the-dev-lead","posted","an-update"],"show_links":["posted->the-dev-lead","posted->an-update"],"focus_node":"posted","note_zh":"先看核心：开发组长发布了一条更新。"},{"step_no":2,"label":"加一点方式","sentence_en":"The dev lead posted an update in the Slack channel.","sentence_zh":"开发组长在 Slack 频道里发布了一条更新。","show_nodes":["in-the-slack-channel"],"show_links":["in-the-slack-channel->posted"],"focus_node":"in-the-slack-channel","note_zh":"这一步说明更新发布在什么地方。"},{"step_no":3,"label":"加一点时间","sentence_en":"The dev lead posted an update in the Slack channel after the standup.","sentence_zh":"站会后，开发组长在 Slack 频道里发布了一条更新。","show_nodes":["after-the-standup"],"show_links":["after-the-standup->posted"],"focus_node":"after-the-standup","note_zh":"这一步说明发布更新的具体时间。"}]}'
  ),
  (
    'postpone-primary',
    'postpone',
    'postpone',
    'postpone a deployment',
    '推迟部署',
    'We postponed the deployment.',
    '我们推迟了部署。',
    'We postponed the deployment until Monday due to an unresolved bug.',
    '由于一个未解决的 bug，我们把部署推迟到了周一。',
    'deploy',
    '[{"step_no":1,"label":"主干","sentence_en":"We postponed the deployment.","sentence_zh":"我们推迟了部署。","focus_text":"postponed","note_zh":"先看核心：团队推迟了部署。","segments":[{"text":"We postponed the deployment","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点时间","sentence_en":"We postponed the deployment until Monday.","sentence_zh":"我们把部署推迟到了周一。","focus_text":"until Monday","note_zh":"这一步说明部署推迟到了周一。","segments":[{"text":"We postponed the deployment ","kind":"core"},{"text":"until Monday","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点原因","sentence_en":"We postponed the deployment until Monday due to an unresolved bug.","sentence_zh":"由于一个未解决的 bug，我们把部署推迟到了周一。","focus_text":"due to an unresolved bug","note_zh":"这一步说明推迟部署是因为有一个未解决的 bug。","segments":[{"text":"We postponed the deployment until Monday ","kind":"core"},{"text":"due to an unresolved bug","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"we","text":"We","kind":"core","group":"core"},{"id":"postponed","text":"postponed","kind":"action","group":"action"},{"id":"the-deployment","text":"the deployment","kind":"core","group":"core"},{"id":"until-monday","text":"until Monday","kind":"modifier","group":"modifier"},{"id":"due-to-an-unresolved-bug","text":"due to an unresolved bug","kind":"modifier","group":"modifier"}],"links":[{"id":"postponed->we","from":"postponed","to":"we","kind":"core","label":"谁推迟部署"},{"id":"postponed->the-deployment","from":"postponed","to":"the-deployment","kind":"core","label":"推迟什么"},{"id":"until-monday->postponed","from":"until-monday","to":"postponed","kind":"modifier","label":"说明推迟到什么时候"},{"id":"due-to-an-unresolved-bug->postponed","from":"due-to-an-unresolved-bug","to":"postponed","kind":"modifier","label":"说明推迟的原因"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We postponed the deployment.","sentence_zh":"我们推迟了部署。","show_nodes":["we","postponed","the-deployment"],"show_links":["postponed->we","postponed->the-deployment"],"focus_node":"postponed","note_zh":"先看核心：团队推迟了部署。"},{"step_no":2,"label":"加一点时间","sentence_en":"We postponed the deployment until Monday.","sentence_zh":"我们把部署推迟到了周一。","show_nodes":["until-monday"],"show_links":["until-monday->postponed"],"focus_node":"until-monday","note_zh":"这一步说明部署推迟到了周一。"},{"step_no":3,"label":"加一点原因","sentence_en":"We postponed the deployment until Monday due to an unresolved bug.","sentence_zh":"由于一个未解决的 bug，我们把部署推迟到了周一。","show_nodes":["due-to-an-unresolved-bug"],"show_links":["due-to-an-unresolved-bug->postponed"],"focus_node":"due-to-an-unresolved-bug","note_zh":"这一步说明推迟部署是因为有一个未解决的 bug。"}]}'
  ),
  (
    'pour-primary',
    'pour',
    'pour',
    'pour resources into',
    '大量投入资源',
    'The startup poured resources into the AI feature.',
    '这家创业公司把资源大量投入了 AI 功能。',
    'After the funding round, the startup poured resources into the AI feature.',
    '融资轮过后，这家创业公司把资源大量投入了 AI 功能。',
    'startup',
    '[{"step_no":1,"label":"主干","sentence_en":"The startup poured resources into the AI feature.","sentence_zh":"这家创业公司把资源大量投入了 AI 功能。","focus_text":"poured","note_zh":"先看核心：创业公司把资源大量投入了 AI 功能。这里 pour 和 into 搭配使用。","segments":[{"text":"The startup poured resources into the AI feature","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点时间","sentence_en":"After the funding round, the startup poured resources into the AI feature.","sentence_zh":"融资轮过后，这家创业公司把资源大量投入了 AI 功能。","focus_text":"after the funding round","note_zh":"这一步说明投入资源是在融资之后。","segments":[{"text":"After the funding round","kind":"modifier"},{"text":", the startup poured resources into the AI feature","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-startup","text":"The startup","kind":"core","group":"core"},{"id":"poured","text":"poured","kind":"action","group":"action"},{"id":"resources","text":"resources","kind":"core","group":"core"},{"id":"into-the-ai-feature","text":"into the AI feature","kind":"modifier","group":"modifier"},{"id":"after-the-funding-round","text":"after the funding round","kind":"modifier","group":"modifier"}],"links":[{"id":"poured->the-startup","from":"poured","to":"the-startup","kind":"core","label":"谁投入资源"},{"id":"poured->resources","from":"poured","to":"resources","kind":"core","label":"投入什么"},{"id":"into-the-ai-feature->poured","from":"into-the-ai-feature","to":"poured","kind":"modifier","label":"说明资源投向哪里"},{"id":"after-the-funding-round->poured","from":"after-the-funding-round","to":"poured","kind":"modifier","label":"说明投入资源的时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The startup poured resources into the AI feature.","sentence_zh":"这家创业公司把资源大量投入了 AI 功能。","show_nodes":["the-startup","poured","resources","into-the-ai-feature"],"show_links":["poured->the-startup","poured->resources","into-the-ai-feature->poured"],"focus_node":"poured","note_zh":"先看核心：创业公司把资源大量投入了 AI 功能。这里 pour 和 into 搭配使用。"},{"step_no":2,"label":"加一点时间","sentence_en":"After the funding round, the startup poured resources into the AI feature.","sentence_zh":"融资轮过后，这家创业公司把资源大量投入了 AI 功能。","show_nodes":["after-the-funding-round"],"show_links":["after-the-funding-round->poured"],"focus_node":"after-the-funding-round","note_zh":"这一步说明投入资源是在融资之后。"}]}'
  ),
  (
    'power-primary',
    'power',
    'power',
    'power a dashboard',
    '驱动仪表板',
    'A real-time data pipeline powers the dashboard.',
    '一条实时数据管道驱动这个仪表板。',
    'A real-time data pipeline powers the dashboard displaying metrics across all regions.',
    '一条实时数据管道驱动这个展示所有区域指标的仪表板。',
    'data-engineering',
    '[{"step_no":1,"label":"主干","sentence_en":"A real-time data pipeline powers the dashboard.","sentence_zh":"一条实时数据管道驱动这个仪表板。","focus_text":"powers","note_zh":"先看核心：实时数据管道驱动仪表板。","segments":[{"text":"A real-time data pipeline powers the dashboard","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"A real-time data pipeline powers the dashboard displaying metrics.","sentence_zh":"一条实时数据管道驱动这个展示指标的仪表板。","focus_text":"displaying metrics","note_zh":"这一步说明仪表板用来展示指标。","segments":[{"text":"A real-time data pipeline powers the dashboard ","kind":"core"},{"text":"displaying metrics","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点范围","sentence_en":"A real-time data pipeline powers the dashboard displaying metrics across all regions.","sentence_zh":"一条实时数据管道驱动这个展示所有区域指标的仪表板。","focus_text":"across all regions","note_zh":"这一步说明指标覆盖了所有区域。","segments":[{"text":"A real-time data pipeline powers the dashboard displaying metrics ","kind":"core"},{"text":"across all regions","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"a-real-time-data-pipeline","text":"A real-time data pipeline","kind":"core","group":"core"},{"id":"powers","text":"powers","kind":"action","group":"action"},{"id":"the-dashboard","text":"the dashboard","kind":"core","group":"core"},{"id":"displaying-metrics","text":"displaying metrics","kind":"modifier","group":"modifier"},{"id":"across-all-regions","text":"across all regions","kind":"modifier","group":"modifier"}],"links":[{"id":"powers->a-real-time-data-pipeline","from":"powers","to":"a-real-time-data-pipeline","kind":"core","label":"什么驱动仪表板"},{"id":"powers->the-dashboard","from":"powers","to":"the-dashboard","kind":"core","label":"驱动什么"},{"id":"displaying-metrics->the-dashboard","from":"displaying-metrics","to":"the-dashboard","kind":"modifier","label":"说明仪表板的功能"},{"id":"across-all-regions->displaying-metrics","from":"across-all-regions","to":"displaying-metrics","kind":"modifier","label":"说明指标覆盖的范围"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A real-time data pipeline powers the dashboard.","sentence_zh":"一条实时数据管道驱动这个仪表板。","show_nodes":["a-real-time-data-pipeline","powers","the-dashboard"],"show_links":["powers->a-real-time-data-pipeline","powers->the-dashboard"],"focus_node":"powers","note_zh":"先看核心：实时数据管道驱动仪表板。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"A real-time data pipeline powers the dashboard displaying metrics.","sentence_zh":"一条实时数据管道驱动这个展示指标的仪表板。","show_nodes":["displaying-metrics"],"show_links":["displaying-metrics->the-dashboard"],"focus_node":"displaying-metrics","note_zh":"这一步说明仪表板用来展示指标。"},{"step_no":3,"label":"加一点范围","sentence_en":"A real-time data pipeline powers the dashboard displaying metrics across all regions.","sentence_zh":"一条实时数据管道驱动这个展示所有区域指标的仪表板。","show_nodes":["across-all-regions"],"show_links":["across-all-regions->displaying-metrics"],"focus_node":"across-all-regions","note_zh":"这一步说明指标覆盖了所有区域。"}]}'
  ),
  (
    'power-down-primary',
    'power-down',
    'power down',
    'power down a server',
    '关闭服务器',
    'The on-call engineer powered down the server.',
    '值班工程师关闭了这台服务器。',
    'The on-call engineer powered down the server for maintenance during the maintenance window.',
    '值班工程师在维护窗口期间为进行维护关闭了这台服务器。',
    'infra',
    '[{"step_no":1,"label":"主干","sentence_en":"The on-call engineer powered down the server.","sentence_zh":"值班工程师关闭了这台服务器。","focus_text":"powered down","note_zh":"先看核心：值班工程师关闭了服务器。power down 是动词短语，表示断电关机。","segments":[{"text":"The on-call engineer powered down the server","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点目的","sentence_en":"The on-call engineer powered down the server for maintenance.","sentence_zh":"值班工程师为进行维护关闭了这台服务器。","focus_text":"for maintenance","note_zh":"这一步说明关闭服务器是为了维护。","segments":[{"text":"The on-call engineer powered down the server ","kind":"core"},{"text":"for maintenance","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点时间","sentence_en":"The on-call engineer powered down the server for maintenance during the maintenance window.","sentence_zh":"值班工程师在维护窗口期间为进行维护关闭了这台服务器。","focus_text":"during the maintenance window","note_zh":"这一步说明关闭操作发生在计划好的维护窗口内。","segments":[{"text":"The on-call engineer powered down the server for maintenance ","kind":"core"},{"text":"during the maintenance window","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-on-call-engineer","text":"The on-call engineer","kind":"core","group":"core"},{"id":"powered-down","text":"powered down","kind":"action","group":"action"},{"id":"the-server","text":"the server","kind":"core","group":"core"},{"id":"for-maintenance","text":"for maintenance","kind":"modifier","group":"modifier"},{"id":"during-the-maintenance-window","text":"during the maintenance window","kind":"modifier","group":"modifier"}],"links":[{"id":"powered-down->the-on-call-engineer","from":"powered-down","to":"the-on-call-engineer","kind":"core","label":"谁关闭服务器"},{"id":"powered-down->the-server","from":"powered-down","to":"the-server","kind":"core","label":"关闭什么"},{"id":"for-maintenance->powered-down","from":"for-maintenance","to":"powered-down","kind":"modifier","label":"说明关闭的目的"},{"id":"during-the-maintenance-window->powered-down","from":"during-the-maintenance-window","to":"powered-down","kind":"modifier","label":"说明关闭服务器的时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The on-call engineer powered down the server.","sentence_zh":"值班工程师关闭了这台服务器。","show_nodes":["the-on-call-engineer","powered-down","the-server"],"show_links":["powered-down->the-on-call-engineer","powered-down->the-server"],"focus_node":"powered-down","note_zh":"先看核心：值班工程师关闭了服务器。power down 是动词短语，表示断电关机。"},{"step_no":2,"label":"加一点目的","sentence_en":"The on-call engineer powered down the server for maintenance.","sentence_zh":"值班工程师为进行维护关闭了这台服务器。","show_nodes":["for-maintenance"],"show_links":["for-maintenance->powered-down"],"focus_node":"for-maintenance","note_zh":"这一步说明关闭服务器是为了维护。"},{"step_no":3,"label":"加一点时间","sentence_en":"The on-call engineer powered down the server for maintenance during the maintenance window.","sentence_zh":"值班工程师在维护窗口期间为进行维护关闭了这台服务器。","show_nodes":["during-the-maintenance-window"],"show_links":["during-the-maintenance-window->powered-down"],"focus_node":"during-the-maintenance-window","note_zh":"这一步说明关闭操作发生在计划好的维护窗口内。"}]}'
  ),
  (
    'practice-primary',
    'practice',
    'practice',
    'practice a presentation',
    '练习演讲',
    'She practiced her presentation.',
    '她练习了自己的演讲。',
    'She practiced her presentation in front of the team before the client demo.',
    '在客户演示之前，她在团队面前练习了自己的演讲。',
    'meeting-prep',
    '[{"step_no":1,"label":"主干","sentence_en":"She practiced her presentation.","sentence_zh":"她练习了自己的演讲。","focus_text":"practiced","note_zh":"先看核心：她练习了演讲。","segments":[{"text":"She practiced her presentation","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点方式","sentence_en":"She practiced her presentation in front of the team.","sentence_zh":"她在团队面前练习了自己的演讲。","focus_text":"in front of the team","note_zh":"这一步说明她在团队面前进行了模拟演练。","segments":[{"text":"She practiced her presentation ","kind":"core"},{"text":"in front of the team","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点时间","sentence_en":"She practiced her presentation in front of the team before the client demo.","sentence_zh":"在客户演示之前，她在团队面前练习了自己的演讲。","focus_text":"before the client demo","note_zh":"这一步说明练习发生在客户演示之前。","segments":[{"text":"She practiced her presentation in front of the team ","kind":"core"},{"text":"before the client demo","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"she","text":"She","kind":"core","group":"core"},{"id":"practiced","text":"practiced","kind":"action","group":"action"},{"id":"her-presentation","text":"her presentation","kind":"core","group":"core"},{"id":"in-front-of-the-team","text":"in front of the team","kind":"modifier","group":"modifier"},{"id":"before-the-client-demo","text":"before the client demo","kind":"modifier","group":"modifier"}],"links":[{"id":"practiced->she","from":"practiced","to":"she","kind":"core","label":"谁练习"},{"id":"practiced->her-presentation","from":"practiced","to":"her-presentation","kind":"core","label":"练习什么"},{"id":"in-front-of-the-team->practiced","from":"in-front-of-the-team","to":"practiced","kind":"modifier","label":"说明练习的方式"},{"id":"before-the-client-demo->practiced","from":"before-the-client-demo","to":"practiced","kind":"modifier","label":"说明练习的时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"She practiced her presentation.","sentence_zh":"她练习了自己的演讲。","show_nodes":["she","practiced","her-presentation"],"show_links":["practiced->she","practiced->her-presentation"],"focus_node":"practiced","note_zh":"先看核心：她练习了演讲。"},{"step_no":2,"label":"加一点方式","sentence_en":"She practiced her presentation in front of the team.","sentence_zh":"她在团队面前练习了自己的演讲。","show_nodes":["in-front-of-the-team"],"show_links":["in-front-of-the-team->practiced"],"focus_node":"in-front-of-the-team","note_zh":"这一步说明她在团队面前进行了模拟演练。"},{"step_no":3,"label":"加一点时间","sentence_en":"She practiced her presentation in front of the team before the client demo.","sentence_zh":"在客户演示之前，她在团队面前练习了自己的演讲。","show_nodes":["before-the-client-demo"],"show_links":["before-the-client-demo->practiced"],"focus_node":"before-the-client-demo","note_zh":"这一步说明练习发生在客户演示之前。"}]}'
  ),
  (
    'practise-primary',
    'practise',
    'practise',
    'practise TDD',
    '实践测试驱动开发',
    'The engineering team practises test-driven development.',
    '工程团队实践测试驱动开发。',
    'The engineering team practises test-driven development on every feature branch to reduce regressions.',
    '工程团队在每个功能分支上实践测试驱动开发，以减少回归问题。',
    'coding',
    '[{"step_no":1,"label":"主干","sentence_en":"The engineering team practises test-driven development.","sentence_zh":"工程团队实践测试驱动开发。","focus_text":"practises","note_zh":"先看核心：工程团队实践 TDD 开发方法。","segments":[{"text":"The engineering team practises test-driven development","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点范围","sentence_en":"The engineering team practises test-driven development on every feature branch.","sentence_zh":"工程团队在每个功能分支上实践测试驱动开发。","focus_text":"on every feature branch","note_zh":"这一步说明 TDD 覆盖到所有功能分支。","segments":[{"text":"The engineering team practises test-driven development ","kind":"core"},{"text":"on every feature branch","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点目的","sentence_en":"The engineering team practises test-driven development on every feature branch to reduce regressions.","sentence_zh":"工程团队在每个功能分支上实践测试驱动开发，以减少回归问题。","focus_text":"to reduce regressions","note_zh":"这一步说明实践 TDD 是为了减少回归缺陷。","segments":[{"text":"The engineering team practises test-driven development on every feature branch ","kind":"core"},{"text":"to reduce regressions","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-engineering-team","text":"The engineering team","kind":"core","group":"core"},{"id":"practises","text":"practises","kind":"action","group":"action"},{"id":"test-driven-development","text":"test-driven development","kind":"core","group":"core"},{"id":"on-every-feature-branch","text":"on every feature branch","kind":"modifier","group":"modifier"},{"id":"to-reduce-regressions","text":"to reduce regressions","kind":"modifier","group":"modifier"}],"links":[{"id":"practises->the-engineering-team","from":"practises","to":"the-engineering-team","kind":"core","label":"谁在实践 TDD"},{"id":"practises->test-driven-development","from":"practises","to":"test-driven-development","kind":"core","label":"实践什么"},{"id":"on-every-feature-branch->practises","from":"on-every-feature-branch","to":"practises","kind":"modifier","label":"说明实践的范围"},{"id":"to-reduce-regressions->practises","from":"to-reduce-regressions","to":"practises","kind":"modifier","label":"说明实践的目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The engineering team practises test-driven development.","sentence_zh":"工程团队实践测试驱动开发。","show_nodes":["the-engineering-team","practises","test-driven-development"],"show_links":["practises->the-engineering-team","practises->test-driven-development"],"focus_node":"practises","note_zh":"先看核心：工程团队实践 TDD 开发方法。"},{"step_no":2,"label":"加一点范围","sentence_en":"The engineering team practises test-driven development on every feature branch.","sentence_zh":"工程团队在每个功能分支上实践测试驱动开发。","show_nodes":["on-every-feature-branch"],"show_links":["on-every-feature-branch->practises"],"focus_node":"on-every-feature-branch","note_zh":"这一步说明 TDD 覆盖到所有功能分支。"},{"step_no":3,"label":"加一点目的","sentence_en":"The engineering team practises test-driven development on every feature branch to reduce regressions.","sentence_zh":"工程团队在每个功能分支上实践测试驱动开发，以减少回归问题。","show_nodes":["to-reduce-regressions"],"show_links":["to-reduce-regressions->practises"],"focus_node":"to-reduce-regressions","note_zh":"这一步说明实践 TDD 是为了减少回归缺陷。"}]}'
  ),
  (
    'praise-primary',
    'praise',
    'praise',
    'praise a colleague',
    '表扬同事',
    'The manager praised the junior developer.',
    '经理表扬了这位初级开发者。',
    'The manager praised the junior developer for the clean refactor during the sprint retrospective.',
    '经理在 Sprint 回顾会上因为这次干净的重构表扬了这位初级开发者。',
    'standup',
    '[{"step_no":1,"label":"主干","sentence_en":"The manager praised the junior developer.","sentence_zh":"经理表扬了这位初级开发者。","focus_text":"praised","note_zh":"先看核心：经理表扬了初级开发者。","segments":[{"text":"The manager praised the junior developer","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点原因","sentence_en":"The manager praised the junior developer for the clean refactor.","sentence_zh":"经理因为这次干净的重构表扬了这位初级开发者。","focus_text":"for the clean refactor","note_zh":"这一步说明表扬的具体原因是代码重构做得很干净。","segments":[{"text":"The manager praised the junior developer ","kind":"core"},{"text":"for the clean refactor","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点场景","sentence_en":"The manager praised the junior developer for the clean refactor during the sprint retrospective.","sentence_zh":"经理在 Sprint 回顾会上因为这次干净的重构表扬了这位初级开发者。","focus_text":"during the sprint retrospective","note_zh":"这一步说明表扬发生在 Sprint 回顾会上。","segments":[{"text":"The manager praised the junior developer for the clean refactor ","kind":"core"},{"text":"during the sprint retrospective","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-manager","text":"The manager","kind":"core","group":"core"},{"id":"praised","text":"praised","kind":"action","group":"action"},{"id":"the-junior-developer","text":"the junior developer","kind":"core","group":"core"},{"id":"for-the-clean-refactor","text":"for the clean refactor","kind":"modifier","group":"modifier"},{"id":"during-the-sprint-retrospective","text":"during the sprint retrospective","kind":"modifier","group":"modifier"}],"links":[{"id":"praised->the-manager","from":"praised","to":"the-manager","kind":"core","label":"谁表扬"},{"id":"praised->the-junior-developer","from":"praised","to":"the-junior-developer","kind":"core","label":"表扬谁"},{"id":"for-the-clean-refactor->praised","from":"for-the-clean-refactor","to":"praised","kind":"modifier","label":"说明表扬的原因"},{"id":"during-the-sprint-retrospective->praised","from":"during-the-sprint-retrospective","to":"praised","kind":"modifier","label":"说明表扬的场景"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The manager praised the junior developer.","sentence_zh":"经理表扬了这位初级开发者。","show_nodes":["the-manager","praised","the-junior-developer"],"show_links":["praised->the-manager","praised->the-junior-developer"],"focus_node":"praised","note_zh":"先看核心：经理表扬了初级开发者。"},{"step_no":2,"label":"加一点原因","sentence_en":"The manager praised the junior developer for the clean refactor.","sentence_zh":"经理因为这次干净的重构表扬了这位初级开发者。","show_nodes":["for-the-clean-refactor"],"show_links":["for-the-clean-refactor->praised"],"focus_node":"for-the-clean-refactor","note_zh":"这一步说明表扬的具体原因是代码重构做得很干净。"},{"step_no":3,"label":"加一点场景","sentence_en":"The manager praised the junior developer for the clean refactor during the sprint retrospective.","sentence_zh":"经理在 Sprint 回顾会上因为这次干净的重构表扬了这位初级开发者。","show_nodes":["during-the-sprint-retrospective"],"show_links":["during-the-sprint-retrospective->praised"],"focus_node":"during-the-sprint-retrospective","note_zh":"这一步说明表扬发生在 Sprint 回顾会上。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  steps_json = excluded.steps_json,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
