-- Generated verb paths batch batch-010.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  steps_json,
  growth_json
) VALUES
  (
    'reach-primary',
    'reach',
    'reach',
    'reach production',
    '到达（生产环境）',
    'The deployment reached production.',
    '部署到达了生产环境。',
    'The deployment reached production successfully this morning.',
    '部署今天早上成功到达了生产环境。',
    'deploy',
    '[{"step_no":1,"label":"主干","sentence_en":"The deployment reached production.","sentence_zh":"部署到达了生产环境。","focus_text":"reached","note_zh":"这一步展示动作和主干——什么到达了哪里。","segments":[{"text":"The deployment reached production","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"结果","sentence_en":"The deployment reached production successfully.","sentence_zh":"部署成功到达了生产环境。","focus_text":"successfully","note_zh":"这一步说明到达的结果如何。","segments":[{"text":"The deployment reached production ","kind":"core"},{"text":"successfully","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"时间","sentence_en":"The deployment reached production successfully this morning.","sentence_zh":"部署今天早上成功到达了生产环境。","focus_text":"this morning","note_zh":"这一步说明到达发生在什么时候。","segments":[{"text":"The deployment reached production successfully ","kind":"core"},{"text":"this morning","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-deployment","text":"the deployment","kind":"core","group":"core"},{"id":"reached","text":"reached","kind":"action","group":"action"},{"id":"production","text":"production","kind":"core","group":"core"},{"id":"successfully","text":"successfully","kind":"modifier","group":"modifier"},{"id":"this-morning","text":"this morning","kind":"modifier","group":"modifier"}],"links":[{"id":"reached->the-deployment","from":"reached","to":"the-deployment","kind":"core","label":"执行者"},{"id":"reached->production","from":"reached","to":"production","kind":"core","label":"到达目标"},{"id":"successfully->reached","from":"successfully","to":"reached","kind":"modifier","label":"说明结果状态"},{"id":"this-morning->reached","from":"this-morning","to":"reached","kind":"modifier","label":"说明发生时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The deployment reached production.","sentence_zh":"部署到达了生产环境。","show_nodes":["the-deployment","reached","production"],"show_links":["reached->the-deployment","reached->production"],"focus_node":"reached","note_zh":"这一步展示动作和主干——什么到达了哪里。"},{"step_no":2,"label":"结果","sentence_en":"The deployment reached production successfully.","sentence_zh":"部署成功到达了生产环境。","show_nodes":["successfully"],"show_links":["successfully->reached"],"focus_node":"successfully","note_zh":"这一步说明到达的结果如何。"},{"step_no":3,"label":"时间","sentence_en":"The deployment reached production successfully this morning.","sentence_zh":"部署今天早上成功到达了生产环境。","show_nodes":["this-morning"],"show_links":["this-morning->reached"],"focus_node":"this-morning","note_zh":"这一步说明到达发生在什么时候。"}]}'
  ),
  (
    'reach-out-primary',
    'reach-out',
    'reach out',
    'reach out to a client',
    '联系（某人）',
    'She reached out to the client.',
    '她联系了客户。',
    'She reached out to the client on Monday to schedule a meeting.',
    '她周一联系客户来安排一次会议。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"She reached out to the client.","sentence_zh":"她联系了客户。","focus_text":"reached out","note_zh":"这一步展示动作和主干——谁联系了谁。","segments":[{"text":"She reached out to the client","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"时间","sentence_en":"She reached out to the client on Monday.","sentence_zh":"她周一联系了客户。","focus_text":"on Monday","note_zh":"这一步说明联系发生在什么时候。","segments":[{"text":"She reached out to the client ","kind":"core"},{"text":"on Monday","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"目的","sentence_en":"She reached out to the client on Monday to schedule a meeting.","sentence_zh":"她周一联系客户来安排一次会议。","focus_text":"to schedule a meeting","note_zh":"这一步说明联系是为了什么。","segments":[{"text":"She reached out to the client on Monday ","kind":"core"},{"text":"to schedule a meeting","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"she","text":"She","kind":"core","group":"core"},{"id":"reached-out","text":"reached out","kind":"action","group":"action"},{"id":"to-the-client","text":"to the client","kind":"core","group":"core"},{"id":"on-monday","text":"on Monday","kind":"modifier","group":"modifier"},{"id":"to-schedule-a-meeting","text":"to schedule a meeting","kind":"modifier","group":"modifier"}],"links":[{"id":"reached-out->she","from":"reached-out","to":"she","kind":"core","label":"执行者"},{"id":"reached-out->to-the-client","from":"reached-out","to":"to-the-client","kind":"core","label":"联系对象"},{"id":"on-monday->reached-out","from":"on-monday","to":"reached-out","kind":"modifier","label":"说明发生时间"},{"id":"to-schedule-a-meeting->reached-out","from":"to-schedule-a-meeting","to":"reached-out","kind":"modifier","label":"说明联系目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"She reached out to the client.","sentence_zh":"她联系了客户。","show_nodes":["she","reached-out","to-the-client"],"show_links":["reached-out->she","reached-out->to-the-client"],"focus_node":"reached-out","note_zh":"这一步展示动作和主干——谁联系了谁。"},{"step_no":2,"label":"时间","sentence_en":"She reached out to the client on Monday.","sentence_zh":"她周一联系了客户。","show_nodes":["on-monday"],"show_links":["on-monday->reached-out"],"focus_node":"on-monday","note_zh":"这一步说明联系发生在什么时候。"},{"step_no":3,"label":"目的","sentence_en":"She reached out to the client on Monday to schedule a meeting.","sentence_zh":"她周一联系客户来安排一次会议。","show_nodes":["to-schedule-a-meeting"],"show_links":["to-schedule-a-meeting->reached-out"],"focus_node":"to-schedule-a-meeting","note_zh":"这一步说明联系是为了什么。"}]}'
  ),
  (
    'react-primary',
    'react',
    'react',
    'react to state changes',
    '响应（变化）',
    'The component reacts to state changes.',
    '组件对状态变化作出反应。',
    'The component reacts to state changes instantly during rendering.',
    '组件在渲染过程中即时对状态变化作出反应。',
    'frontend',
    '[{"step_no":1,"label":"主干","sentence_en":"The component reacts to state changes.","sentence_zh":"组件对状态变化作出反应。","focus_text":"reacts","note_zh":"这一步展示动作和主干——什么对什么作出反应。","segments":[{"text":"The component reacts to state changes","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The component reacts to state changes instantly.","sentence_zh":"组件即时对状态变化作出反应。","focus_text":"instantly","note_zh":"这一步说明反应有多快。","segments":[{"text":"The component reacts to state changes ","kind":"core"},{"text":"instantly","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"场景","sentence_en":"The component reacts to state changes instantly during rendering.","sentence_zh":"组件在渲染过程中即时对状态变化作出反应。","focus_text":"during rendering","note_zh":"这一步说明反应发生在什么阶段。","segments":[{"text":"The component reacts to state changes instantly ","kind":"core"},{"text":"during rendering","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-component","text":"The component","kind":"core","group":"core"},{"id":"reacts","text":"reacts","kind":"action","group":"action"},{"id":"to-state-changes","text":"to state changes","kind":"core","group":"core"},{"id":"instantly","text":"instantly","kind":"modifier","group":"modifier"},{"id":"during-rendering","text":"during rendering","kind":"modifier","group":"modifier"}],"links":[{"id":"reacts->the-component","from":"reacts","to":"the-component","kind":"core","label":"执行者"},{"id":"reacts->to-state-changes","from":"reacts","to":"to-state-changes","kind":"core","label":"回应对象"},{"id":"instantly->reacts","from":"instantly","to":"reacts","kind":"modifier","label":"说明反应速度"},{"id":"during-rendering->reacts","from":"during-rendering","to":"reacts","kind":"modifier","label":"说明发生场景"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The component reacts to state changes.","sentence_zh":"组件对状态变化作出反应。","show_nodes":["the-component","reacts","to-state-changes"],"show_links":["reacts->the-component","reacts->to-state-changes"],"focus_node":"reacts","note_zh":"这一步展示动作和主干——什么对什么作出反应。"},{"step_no":2,"label":"程度","sentence_en":"The component reacts to state changes instantly.","sentence_zh":"组件即时对状态变化作出反应。","show_nodes":["instantly"],"show_links":["instantly->reacts"],"focus_node":"instantly","note_zh":"这一步说明反应有多快。"},{"step_no":3,"label":"场景","sentence_en":"The component reacts to state changes instantly during rendering.","sentence_zh":"组件在渲染过程中即时对状态变化作出反应。","show_nodes":["during-rendering"],"show_links":["during-rendering->reacts"],"focus_node":"during-rendering","note_zh":"这一步说明反应发生在什么阶段。"}]}'
  ),
  (
    'read-primary',
    'read',
    'read',
    'read a config file',
    '读取（文件）',
    'The parser reads the config file.',
    '解析器读取配置文件。',
    'The parser reads the config file synchronously at startup.',
    '解析器在启动时同步读取配置文件。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"The parser reads the config file.","sentence_zh":"解析器读取配置文件。","focus_text":"reads","note_zh":"这一步展示动作和主干——什么读取什么。","segments":[{"text":"The parser reads the config file","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"方式","sentence_en":"The parser reads the config file synchronously.","sentence_zh":"解析器同步读取配置文件。","focus_text":"synchronously","note_zh":"这一步说明以什么方式读取。","segments":[{"text":"The parser reads the config file ","kind":"core"},{"text":"synchronously","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"场景","sentence_en":"The parser reads the config file synchronously at startup.","sentence_zh":"解析器在启动时同步读取配置文件。","focus_text":"at startup","note_zh":"这一步说明读取发生在什么时机。","segments":[{"text":"The parser reads the config file synchronously ","kind":"core"},{"text":"at startup","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-parser","text":"The parser","kind":"core","group":"core"},{"id":"reads","text":"reads","kind":"action","group":"action"},{"id":"the-config-file","text":"the config file","kind":"core","group":"core"},{"id":"synchronously","text":"synchronously","kind":"modifier","group":"modifier"},{"id":"at-startup","text":"at startup","kind":"modifier","group":"modifier"}],"links":[{"id":"reads->the-parser","from":"reads","to":"the-parser","kind":"core","label":"执行者"},{"id":"reads->the-config-file","from":"reads","to":"the-config-file","kind":"core","label":"读取对象"},{"id":"synchronously->reads","from":"synchronously","to":"reads","kind":"modifier","label":"说明读取方式"},{"id":"at-startup->reads","from":"at-startup","to":"reads","kind":"modifier","label":"说明发生时机"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The parser reads the config file.","sentence_zh":"解析器读取配置文件。","show_nodes":["the-parser","reads","the-config-file"],"show_links":["reads->the-parser","reads->the-config-file"],"focus_node":"reads","note_zh":"这一步展示动作和主干——什么读取什么。"},{"step_no":2,"label":"方式","sentence_en":"The parser reads the config file synchronously.","sentence_zh":"解析器同步读取配置文件。","show_nodes":["synchronously"],"show_links":["synchronously->reads"],"focus_node":"synchronously","note_zh":"这一步说明以什么方式读取。"},{"step_no":3,"label":"场景","sentence_en":"The parser reads the config file synchronously at startup.","sentence_zh":"解析器在启动时同步读取配置文件。","show_nodes":["at-startup"],"show_links":["at-startup->reads"],"focus_node":"at-startup","note_zh":"这一步说明读取发生在什么时机。"}]}'
  ),
  (
    'realize-primary',
    'realize',
    'realize',
    'realize the mistake',
    '意识到（错误）',
    'The engineer realized the mistake.',
    '工程师意识到了这个错误。',
    'The engineer realized the mistake almost immediately after the deploy.',
    '工程师在部署后几乎立刻就意识到了这个错误。',
    'debug',
    '[{"step_no":1,"label":"主干","sentence_en":"The engineer realized the mistake.","sentence_zh":"工程师意识到了这个错误。","focus_text":"realized","note_zh":"这一步展示动作和主干——谁意识到了什么。","segments":[{"text":"The engineer realized the mistake","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The engineer realized the mistake almost immediately.","sentence_zh":"工程师几乎立刻就意识到了这个错误。","focus_text":"almost immediately","note_zh":"这一步说明意识到错误有多快。","segments":[{"text":"The engineer realized the mistake ","kind":"core"},{"text":"almost immediately","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"时间","sentence_en":"The engineer realized the mistake almost immediately after the deploy.","sentence_zh":"工程师在部署后几乎立刻就意识到了这个错误。","focus_text":"after the deploy","note_zh":"这一步说明意识到错误发生在什么时候。","segments":[{"text":"The engineer realized the mistake almost immediately ","kind":"core"},{"text":"after the deploy","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-engineer","text":"The engineer","kind":"core","group":"core"},{"id":"realized","text":"realized","kind":"action","group":"action"},{"id":"the-mistake","text":"the mistake","kind":"core","group":"core"},{"id":"almost-immediately","text":"almost immediately","kind":"modifier","group":"modifier"},{"id":"after-the-deploy","text":"after the deploy","kind":"modifier","group":"modifier"}],"links":[{"id":"realized->the-engineer","from":"realized","to":"the-engineer","kind":"core","label":"执行者"},{"id":"realized->the-mistake","from":"realized","to":"the-mistake","kind":"core","label":"认知对象"},{"id":"almost-immediately->realized","from":"almost-immediately","to":"realized","kind":"modifier","label":"说明意识到速度"},{"id":"after-the-deploy->realized","from":"after-the-deploy","to":"realized","kind":"modifier","label":"说明发生时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The engineer realized the mistake.","sentence_zh":"工程师意识到了这个错误。","show_nodes":["the-engineer","realized","the-mistake"],"show_links":["realized->the-engineer","realized->the-mistake"],"focus_node":"realized","note_zh":"这一步展示动作和主干——谁意识到了什么。"},{"step_no":2,"label":"程度","sentence_en":"The engineer realized the mistake almost immediately.","sentence_zh":"工程师几乎立刻就意识到了这个错误。","show_nodes":["almost-immediately"],"show_links":["almost-immediately->realized"],"focus_node":"almost-immediately","note_zh":"这一步说明意识到错误有多快。"},{"step_no":3,"label":"时间","sentence_en":"The engineer realized the mistake almost immediately after the deploy.","sentence_zh":"工程师在部署后几乎立刻就意识到了这个错误。","show_nodes":["after-the-deploy"],"show_links":["after-the-deploy->realized"],"focus_node":"after-the-deploy","note_zh":"这一步说明意识到错误发生在什么时候。"}]}'
  ),
  (
    'rebalance-primary',
    'rebalance',
    'rebalance',
    'rebalance the workload',
    '重新平衡（工作负载）',
    'The scheduler rebalances the workload.',
    '调度器重新平衡工作负载。',
    'The scheduler rebalances the workload across nodes when a node fails.',
    '当某个节点故障时，调度器跨节点重新平衡工作负载。',
    'system',
    '[{"step_no":1,"label":"主干","sentence_en":"The scheduler rebalances the workload.","sentence_zh":"调度器重新平衡工作负载。","focus_text":"rebalances","note_zh":"这一步展示动作和主干——什么重新平衡什么。","segments":[{"text":"The scheduler rebalances the workload","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"范围","sentence_en":"The scheduler rebalances the workload across nodes.","sentence_zh":"调度器跨节点重新平衡工作负载。","focus_text":"across nodes","note_zh":"这一步说明重新平衡的范围。","segments":[{"text":"The scheduler rebalances the workload ","kind":"core"},{"text":"across nodes","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"条件","sentence_en":"The scheduler rebalances the workload across nodes when a node fails.","sentence_zh":"当某个节点故障时，调度器跨节点重新平衡工作负载。","focus_text":"when a node fails","note_zh":"这一步说明什么条件下会触发重新平衡。","segments":[{"text":"The scheduler rebalances the workload across nodes ","kind":"core"},{"text":"when a node fails","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-scheduler","text":"The scheduler","kind":"core","group":"core"},{"id":"rebalances","text":"rebalances","kind":"action","group":"action"},{"id":"the-workload","text":"the workload","kind":"core","group":"core"},{"id":"across-nodes","text":"across nodes","kind":"modifier","group":"modifier"},{"id":"when-a-node-fails","text":"when a node fails","kind":"modifier","group":"modifier"}],"links":[{"id":"rebalances->the-scheduler","from":"rebalances","to":"the-scheduler","kind":"core","label":"执行者"},{"id":"rebalances->the-workload","from":"rebalances","to":"the-workload","kind":"core","label":"作用对象"},{"id":"across-nodes->rebalances","from":"across-nodes","to":"rebalances","kind":"modifier","label":"说明作用范围"},{"id":"when-a-node-fails->rebalances","from":"when-a-node-fails","to":"rebalances","kind":"modifier","label":"说明触发条件"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The scheduler rebalances the workload.","sentence_zh":"调度器重新平衡工作负载。","show_nodes":["the-scheduler","rebalances","the-workload"],"show_links":["rebalances->the-scheduler","rebalances->the-workload"],"focus_node":"rebalances","note_zh":"这一步展示动作和主干——什么重新平衡什么。"},{"step_no":2,"label":"范围","sentence_en":"The scheduler rebalances the workload across nodes.","sentence_zh":"调度器跨节点重新平衡工作负载。","show_nodes":["across-nodes"],"show_links":["across-nodes->rebalances"],"focus_node":"across-nodes","note_zh":"这一步说明重新平衡的范围。"},{"step_no":3,"label":"条件","sentence_en":"The scheduler rebalances the workload across nodes when a node fails.","sentence_zh":"当某个节点故障时，调度器跨节点重新平衡工作负载。","show_nodes":["when-a-node-fails"],"show_links":["when-a-node-fails->rebalances"],"focus_node":"when-a-node-fails","note_zh":"这一步说明什么条件下会触发重新平衡。"}]}'
  ),
  (
    'rebase-primary',
    'rebase',
    'rebase',
    'rebase a feature branch',
    '变基（分支）',
    'He rebased the feature branch.',
    '他变基了功能分支。',
    'He rebased the feature branch onto main to resolve conflicts.',
    '他把功能分支变基到了 main 上来解决冲突。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"He rebased the feature branch.","sentence_zh":"他变基了功能分支。","focus_text":"rebased","note_zh":"这一步展示动作和主干——谁对什么执行了操作。","segments":[{"text":"He rebased the feature branch","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"He rebased the feature branch onto main.","sentence_zh":"他把功能分支变基到了 main 上。","focus_text":"onto main","note_zh":"这一步说明变基的目标基准分支。","segments":[{"text":"He rebased the feature branch ","kind":"core"},{"text":"onto main","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"目的","sentence_en":"He rebased the feature branch onto main to resolve conflicts.","sentence_zh":"他把功能分支变基到了 main 上来解决冲突。","focus_text":"to resolve conflicts","note_zh":"这一步说明变基的目的是什么。","segments":[{"text":"He rebased the feature branch onto main ","kind":"core"},{"text":"to resolve conflicts","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"he","text":"He","kind":"core","group":"core"},{"id":"rebased","text":"rebased","kind":"action","group":"action"},{"id":"the-feature-branch","text":"the feature branch","kind":"core","group":"core"},{"id":"onto-main","text":"onto main","kind":"modifier","group":"modifier"},{"id":"to-resolve-conflicts","text":"to resolve conflicts","kind":"modifier","group":"modifier"}],"links":[{"id":"rebased->he","from":"rebased","to":"he","kind":"core","label":"执行者"},{"id":"rebased->the-feature-branch","from":"rebased","to":"the-feature-branch","kind":"core","label":"操作对象"},{"id":"onto-main->rebased","from":"onto-main","to":"rebased","kind":"modifier","label":"说明目标基准"},{"id":"to-resolve-conflicts->rebased","from":"to-resolve-conflicts","to":"rebased","kind":"modifier","label":"说明操作目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"He rebased the feature branch.","sentence_zh":"他变基了功能分支。","show_nodes":["he","rebased","the-feature-branch"],"show_links":["rebased->he","rebased->the-feature-branch"],"focus_node":"rebased","note_zh":"这一步展示动作和主干——谁对什么执行了操作。"},{"step_no":2,"label":"对象细节","sentence_en":"He rebased the feature branch onto main.","sentence_zh":"他把功能分支变基到了 main 上。","show_nodes":["onto-main"],"show_links":["onto-main->rebased"],"focus_node":"onto-main","note_zh":"这一步说明变基的目标基准分支。"},{"step_no":3,"label":"目的","sentence_en":"He rebased the feature branch onto main to resolve conflicts.","sentence_zh":"他把功能分支变基到了 main 上来解决冲突。","show_nodes":["to-resolve-conflicts"],"show_links":["to-resolve-conflicts->rebased"],"focus_node":"to-resolve-conflicts","note_zh":"这一步说明变基的目的是什么。"}]}'
  ),
  (
    'recall-primary',
    'recall',
    'recall',
    'recall the meeting details',
    '回想起（细节）',
    'She recalled the meeting details.',
    '她回想起了会议细节。',
    'She recalled the meeting details clearly after checking her notes.',
    '查看笔记后，她清楚地回想起了会议细节。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"She recalled the meeting details.","sentence_zh":"她回想起了会议细节。","focus_text":"recalled","note_zh":"这一步展示动作和主干——谁回想起了什么。","segments":[{"text":"She recalled the meeting details","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"She recalled the meeting details clearly.","sentence_zh":"她清楚地回想起了会议细节。","focus_text":"clearly","note_zh":"这一步说明回忆有多清楚。","segments":[{"text":"She recalled the meeting details ","kind":"core"},{"text":"clearly","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"条件","sentence_en":"She recalled the meeting details clearly after checking her notes.","sentence_zh":"查看笔记后，她清楚地回想起了会议细节。","focus_text":"after checking her notes","note_zh":"这一步说明在什么条件下想起来的。","segments":[{"text":"She recalled the meeting details clearly ","kind":"core"},{"text":"after checking her notes","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"she-2","text":"She","kind":"core","group":"core"},{"id":"recalled","text":"recalled","kind":"action","group":"action"},{"id":"the-meeting-details","text":"the meeting details","kind":"core","group":"core"},{"id":"clearly","text":"clearly","kind":"modifier","group":"modifier"},{"id":"after-checking-her-notes","text":"after checking her notes","kind":"modifier","group":"modifier"}],"links":[{"id":"recalled->she-2","from":"recalled","to":"she-2","kind":"core","label":"执行者"},{"id":"recalled->the-meeting-details","from":"recalled","to":"the-meeting-details","kind":"core","label":"回忆对象"},{"id":"clearly->recalled","from":"clearly","to":"recalled","kind":"modifier","label":"说明回忆清晰度"},{"id":"after-checking-her-notes->recalled","from":"after-checking-her-notes","to":"recalled","kind":"modifier","label":"说明回忆触发条件"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"She recalled the meeting details.","sentence_zh":"她回想起了会议细节。","show_nodes":["she-2","recalled","the-meeting-details"],"show_links":["recalled->she-2","recalled->the-meeting-details"],"focus_node":"recalled","note_zh":"这一步展示动作和主干——谁回想起了什么。"},{"step_no":2,"label":"程度","sentence_en":"She recalled the meeting details clearly.","sentence_zh":"她清楚地回想起了会议细节。","show_nodes":["clearly"],"show_links":["clearly->recalled"],"focus_node":"clearly","note_zh":"这一步说明回忆有多清楚。"},{"step_no":3,"label":"条件","sentence_en":"She recalled the meeting details clearly after checking her notes.","sentence_zh":"查看笔记后，她清楚地回想起了会议细节。","show_nodes":["after-checking-her-notes"],"show_links":["after-checking-her-notes->recalled"],"focus_node":"after-checking-her-notes","note_zh":"这一步说明在什么条件下想起来的。"}]}'
  ),
  (
    'recap-primary',
    'recap',
    'recap',
    'recap the quarterly results',
    '回顾（结果）',
    'The manager recapped the quarterly results.',
    '经理回顾了季度业绩。',
    'The manager recapped the quarterly results briefly at the team meeting.',
    '经理在团队会议上简要回顾了季度业绩。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The manager recapped the quarterly results.","sentence_zh":"经理回顾了季度业绩。","focus_text":"recapped","note_zh":"这一步展示动作和主干——谁回顾了什么。","segments":[{"text":"The manager recapped the quarterly results","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"方式","sentence_en":"The manager recapped the quarterly results briefly.","sentence_zh":"经理简要回顾了季度业绩。","focus_text":"briefly","note_zh":"这一步说明回顾的详细程度。","segments":[{"text":"The manager recapped the quarterly results ","kind":"core"},{"text":"briefly","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"场景","sentence_en":"The manager recapped the quarterly results briefly at the team meeting.","sentence_zh":"经理在团队会议上简要回顾了季度业绩。","focus_text":"at the team meeting","note_zh":"这一步说明回顾发生在什么场合。","segments":[{"text":"The manager recapped the quarterly results briefly ","kind":"core"},{"text":"at the team meeting","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-manager","text":"The manager","kind":"core","group":"core"},{"id":"recapped","text":"recapped","kind":"action","group":"action"},{"id":"the-quarterly-results","text":"the quarterly results","kind":"core","group":"core"},{"id":"briefly","text":"briefly","kind":"modifier","group":"modifier"},{"id":"at-the-team-meeting","text":"at the team meeting","kind":"modifier","group":"modifier"}],"links":[{"id":"recapped->the-manager","from":"recapped","to":"the-manager","kind":"core","label":"执行者"},{"id":"recapped->the-quarterly-results","from":"recapped","to":"the-quarterly-results","kind":"core","label":"回顾对象"},{"id":"briefly->recapped","from":"briefly","to":"recapped","kind":"modifier","label":"说明回顾方式"},{"id":"at-the-team-meeting->recapped","from":"at-the-team-meeting","to":"recapped","kind":"modifier","label":"说明发生场景"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The manager recapped the quarterly results.","sentence_zh":"经理回顾了季度业绩。","show_nodes":["the-manager","recapped","the-quarterly-results"],"show_links":["recapped->the-manager","recapped->the-quarterly-results"],"focus_node":"recapped","note_zh":"这一步展示动作和主干——谁回顾了什么。"},{"step_no":2,"label":"方式","sentence_en":"The manager recapped the quarterly results briefly.","sentence_zh":"经理简要回顾了季度业绩。","show_nodes":["briefly"],"show_links":["briefly->recapped"],"focus_node":"briefly","note_zh":"这一步说明回顾的详细程度。"},{"step_no":3,"label":"场景","sentence_en":"The manager recapped the quarterly results briefly at the team meeting.","sentence_zh":"经理在团队会议上简要回顾了季度业绩。","show_nodes":["at-the-team-meeting"],"show_links":["at-the-team-meeting->recapped"],"focus_node":"at-the-team-meeting","note_zh":"这一步说明回顾发生在什么场合。"}]}'
  ),
  (
    'receive-primary',
    'receive',
    'receive',
    'receive a request',
    '接收（请求）',
    'The server received the request.',
    '服务器接收到了请求。',
    'The server received the request from the mobile app at midnight.',
    '服务器在午夜从移动应用接收到了请求。',
    'api',
    '[{"step_no":1,"label":"主干","sentence_en":"The server received the request.","sentence_zh":"服务器接收到了请求。","focus_text":"received","note_zh":"这一步展示动作和主干——什么接收了什么。","segments":[{"text":"The server received the request","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"对象细节","sentence_en":"The server received the request from the mobile app.","sentence_zh":"服务器从移动应用接收到了请求。","focus_text":"from the mobile app","note_zh":"这一步说明请求是从哪里发来的。","segments":[{"text":"The server received the request ","kind":"core"},{"text":"from the mobile app","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"时间","sentence_en":"The server received the request from the mobile app at midnight.","sentence_zh":"服务器在午夜从移动应用接收到了请求。","focus_text":"at midnight","note_zh":"这一步说明接收请求发生在什么时候。","segments":[{"text":"The server received the request from the mobile app ","kind":"core"},{"text":"at midnight","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-server","text":"The server","kind":"core","group":"core"},{"id":"received","text":"received","kind":"action","group":"action"},{"id":"the-request","text":"the request","kind":"core","group":"core"},{"id":"from-the-mobile-app","text":"from the mobile app","kind":"modifier","group":"modifier"},{"id":"at-midnight","text":"at midnight","kind":"modifier","group":"modifier"}],"links":[{"id":"received->the-server","from":"received","to":"the-server","kind":"core","label":"执行者"},{"id":"received->the-request","from":"received","to":"the-request","kind":"core","label":"接收对象"},{"id":"from-the-mobile-app->received","from":"from-the-mobile-app","to":"received","kind":"modifier","label":"说明请求来源"},{"id":"at-midnight->received","from":"at-midnight","to":"received","kind":"modifier","label":"说明发生时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The server received the request.","sentence_zh":"服务器接收到了请求。","show_nodes":["the-server","received","the-request"],"show_links":["received->the-server","received->the-request"],"focus_node":"received","note_zh":"这一步展示动作和主干——什么接收了什么。"},{"step_no":2,"label":"对象细节","sentence_en":"The server received the request from the mobile app.","sentence_zh":"服务器从移动应用接收到了请求。","show_nodes":["from-the-mobile-app"],"show_links":["from-the-mobile-app->received"],"focus_node":"from-the-mobile-app","note_zh":"这一步说明请求是从哪里发来的。"},{"step_no":3,"label":"时间","sentence_en":"The server received the request from the mobile app at midnight.","sentence_zh":"服务器在午夜从移动应用接收到了请求。","show_nodes":["at-midnight"],"show_links":["at-midnight->received"],"focus_node":"at-midnight","note_zh":"这一步说明接收请求发生在什么时候。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  steps_json = excluded.steps_json,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
