-- Generated verb paths batch batch-011.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  steps_json,
  growth_json
) VALUES
  (
    'reckon-primary',
    'reckon',
    'reckon',
    'reckon the cost',
    '估计',
    'The team reckons the cost.',
    '团队估算了成本。',
    'The team reckons the total cost before each sprint.',
    '团队在每个迭代前估算总成本。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The team reckons the cost.","sentence_zh":"团队估算了成本。","focus_text":"reckons","note_zh":"先看核心：团队估算了成本。","segments":[{"text":"The team reckons the cost","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"The team reckons the total cost.","sentence_zh":"团队估算了总成本。","focus_text":"total","note_zh":"这一步说明估算的是全部成本。","segments":[{"text":"The team reckons the ","kind":"core"},{"text":"total","kind":"modifier"},{"text":" cost","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点时间","sentence_en":"The team reckons the total cost before each sprint.","sentence_zh":"团队在每个迭代前估算总成本。","focus_text":"before each sprint","note_zh":"这一步说明估算发生在什么时候。","segments":[{"text":"The team reckons the total cost ","kind":"core"},{"text":"before each sprint","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-team","text":"the team","kind":"core","group":"core"},{"id":"reckons","text":"reckons","kind":"action","group":"action"},{"id":"the-cost","text":"the cost","kind":"core","group":"core"},{"id":"total","text":"total","kind":"modifier","group":"modifier"},{"id":"before-each-sprint","text":"before each sprint","kind":"modifier","group":"modifier"}],"links":[{"id":"reckons->the-team","from":"reckons","to":"the-team","kind":"core","label":"谁在估算"},{"id":"reckons->the-cost","from":"reckons","to":"the-cost","kind":"core","label":"估算什么"},{"id":"total->the-cost","from":"total","to":"the-cost","kind":"modifier","label":"说明成本的范围"},{"id":"before-each-sprint->reckons","from":"before-each-sprint","to":"reckons","kind":"modifier","label":"说明什么时候估算"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team reckons the cost.","sentence_zh":"团队估算了成本。","show_nodes":["the-team","reckons","the-cost"],"show_links":["reckons->the-team","reckons->the-cost"],"focus_node":"reckons","note_zh":"先看核心：团队估算了成本。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"The team reckons the total cost.","sentence_zh":"团队估算了总成本。","show_nodes":["total"],"show_links":["total->the-cost"],"focus_node":"total","note_zh":"这一步说明估算的是全部成本。"},{"step_no":3,"label":"加一点时间","sentence_en":"The team reckons the total cost before each sprint.","sentence_zh":"团队在每个迭代前估算总成本。","show_nodes":["before-each-sprint"],"show_links":["before-each-sprint->reckons"],"focus_node":"before-each-sprint","note_zh":"这一步说明估算发生在什么时候。"}]}'
  ),
  (
    'recognize-primary',
    'recognize',
    'recognize',
    'recognize code patterns',
    '识别',
    'The tool recognizes patterns.',
    '该工具识别模式。',
    'The tool automatically recognizes common patterns in the codebase.',
    '该工具自动识别代码库中的常见模式。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"The tool recognizes patterns.","sentence_zh":"该工具识别模式。","focus_text":"recognizes","note_zh":"先看核心：工具识别模式。","segments":[{"text":"The tool recognizes patterns","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"The tool recognizes common patterns.","sentence_zh":"该工具识别常见模式。","focus_text":"common","note_zh":"这一步说明识别的是常见模式。","segments":[{"text":"The tool recognizes ","kind":"core"},{"text":"common","kind":"modifier"},{"text":" patterns","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点范围","sentence_en":"The tool recognizes common patterns in the codebase.","sentence_zh":"该工具识别代码库中的常见模式。","focus_text":"in the codebase","note_zh":"这一步说明模式来自代码库。","segments":[{"text":"The tool recognizes common patterns ","kind":"core"},{"text":"in the codebase","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":4,"label":"加一点方式","sentence_en":"The tool automatically recognizes common patterns in the codebase.","sentence_zh":"该工具自动识别代码库中的常见模式。","focus_text":"automatically","note_zh":"这一步说明识别是自动完成的。","segments":[{"text":"The tool ","kind":"core"},{"text":"automatically","kind":"modifier"},{"text":" recognizes common patterns in the codebase","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-tool","text":"the tool","kind":"core","group":"core"},{"id":"recognizes","text":"recognizes","kind":"action","group":"action"},{"id":"patterns","text":"patterns","kind":"core","group":"core"},{"id":"common","text":"common","kind":"modifier","group":"modifier"},{"id":"in-the-codebase","text":"in the codebase","kind":"modifier","group":"modifier"},{"id":"automatically","text":"automatically","kind":"modifier","group":"modifier"}],"links":[{"id":"recognizes->the-tool","from":"recognizes","to":"the-tool","kind":"core","label":"什么在识别"},{"id":"recognizes->patterns","from":"recognizes","to":"patterns","kind":"core","label":"识别什么"},{"id":"common->patterns","from":"common","to":"patterns","kind":"modifier","label":"说明模式的类型"},{"id":"in-the-codebase->patterns","from":"in-the-codebase","to":"patterns","kind":"modifier","label":"说明模式所在的范围"},{"id":"automatically->recognizes","from":"automatically","to":"recognizes","kind":"modifier","label":"说明识别的方式"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The tool recognizes patterns.","sentence_zh":"该工具识别模式。","show_nodes":["the-tool","recognizes","patterns"],"show_links":["recognizes->the-tool","recognizes->patterns"],"focus_node":"recognizes","note_zh":"先看核心：工具识别模式。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"The tool recognizes common patterns.","sentence_zh":"该工具识别常见模式。","show_nodes":["common"],"show_links":["common->patterns"],"focus_node":"common","note_zh":"这一步说明识别的是常见模式。"},{"step_no":3,"label":"加一点范围","sentence_en":"The tool recognizes common patterns in the codebase.","sentence_zh":"该工具识别代码库中的常见模式。","show_nodes":["in-the-codebase"],"show_links":["in-the-codebase->patterns"],"focus_node":"in-the-codebase","note_zh":"这一步说明模式来自代码库。"},{"step_no":4,"label":"加一点方式","sentence_en":"The tool automatically recognizes common patterns in the codebase.","sentence_zh":"该工具自动识别代码库中的常见模式。","show_nodes":["automatically"],"show_links":["automatically->recognizes"],"focus_node":"automatically","note_zh":"这一步说明识别是自动完成的。"}]}'
  ),
  (
    'recommend-primary',
    'recommend',
    'recommend',
    'recommend a fix',
    '推荐',
    'The linter recommends a fix.',
    '代码检查工具推荐了一项修复。',
    'The linter recommends a quick fix for each warning.',
    '代码检查工具为每个警告推荐一项快速修复。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"The linter recommends a fix.","sentence_zh":"代码检查工具推荐了一项修复。","focus_text":"recommends","note_zh":"先看核心：代码检查工具推荐了修复。","segments":[{"text":"The linter recommends a fix","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"The linter recommends a quick fix.","sentence_zh":"代码检查工具推荐了一项快速修复。","focus_text":"quick","note_zh":"这一步说明修复可以快速完成。","segments":[{"text":"The linter recommends a ","kind":"core"},{"text":"quick","kind":"modifier"},{"text":" fix","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点目的","sentence_en":"The linter recommends a quick fix for each warning.","sentence_zh":"代码检查工具为每个警告推荐一项快速修复。","focus_text":"for each warning","note_zh":"这一步说明推荐针对每一个警告。","segments":[{"text":"The linter recommends a quick fix ","kind":"core"},{"text":"for each warning","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-linter","text":"the linter","kind":"core","group":"core"},{"id":"recommends","text":"recommends","kind":"action","group":"action"},{"id":"a-fix","text":"a fix","kind":"core","group":"core"},{"id":"quick","text":"quick","kind":"modifier","group":"modifier"},{"id":"for-each-warning","text":"for each warning","kind":"modifier","group":"modifier"}],"links":[{"id":"recommends->the-linter","from":"recommends","to":"the-linter","kind":"core","label":"什么在推荐"},{"id":"recommends->a-fix","from":"recommends","to":"a-fix","kind":"core","label":"推荐什么"},{"id":"quick->a-fix","from":"quick","to":"a-fix","kind":"modifier","label":"说明修复的类型"},{"id":"for-each-warning->recommends","from":"for-each-warning","to":"recommends","kind":"modifier","label":"说明推荐针对什么"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The linter recommends a fix.","sentence_zh":"代码检查工具推荐了一项修复。","show_nodes":["the-linter","recommends","a-fix"],"show_links":["recommends->the-linter","recommends->a-fix"],"focus_node":"recommends","note_zh":"先看核心：代码检查工具推荐了修复。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"The linter recommends a quick fix.","sentence_zh":"代码检查工具推荐了一项快速修复。","show_nodes":["quick"],"show_links":["quick->a-fix"],"focus_node":"quick","note_zh":"这一步说明修复可以快速完成。"},{"step_no":3,"label":"加一点目的","sentence_en":"The linter recommends a quick fix for each warning.","sentence_zh":"代码检查工具为每个警告推荐一项快速修复。","show_nodes":["for-each-warning"],"show_links":["for-each-warning->recommends"],"focus_node":"for-each-warning","note_zh":"这一步说明推荐针对每一个警告。"}]}'
  ),
  (
    'reconcile-primary',
    'reconcile',
    'reconcile',
    'reconcile payment records',
    '对账',
    'The script reconciles the records.',
    '脚本对账记录。',
    'The script reconciles the payment records with the bank statement every night.',
    '脚本每晚将支付记录与银行对账单进行对账。',
    'data',
    '[{"step_no":1,"label":"主干","sentence_en":"The script reconciles the records.","sentence_zh":"脚本对账记录。","focus_text":"reconciles","note_zh":"先看核心：脚本对账记录。","segments":[{"text":"The script reconciles the records","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"The script reconciles the payment records.","sentence_zh":"脚本对账支付记录。","focus_text":"payment","note_zh":"这一步说明对账的是支付记录。","segments":[{"text":"The script reconciles the ","kind":"core"},{"text":"payment","kind":"modifier"},{"text":" records","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点方式","sentence_en":"The script reconciles the payment records with the bank statement.","sentence_zh":"脚本将支付记录与银行对账单进行对账。","focus_text":"with the bank statement","note_zh":"这一步说明与银行对账单进行比对。","segments":[{"text":"The script reconciles the payment records ","kind":"core"},{"text":"with the bank statement","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":4,"label":"加一点时间","sentence_en":"The script reconciles the payment records with the bank statement every night.","sentence_zh":"脚本每晚将支付记录与银行对账单进行对账。","focus_text":"every night","note_zh":"这一步说明对账每天晚上自动运行。","segments":[{"text":"The script reconciles the payment records with the bank statement ","kind":"core"},{"text":"every night","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-script","text":"the script","kind":"core","group":"core"},{"id":"reconciles","text":"reconciles","kind":"action","group":"action"},{"id":"the-records","text":"the records","kind":"core","group":"core"},{"id":"payment","text":"payment","kind":"modifier","group":"modifier"},{"id":"with-the-bank-statement","text":"with the bank statement","kind":"modifier","group":"modifier"},{"id":"every-night","text":"every night","kind":"modifier","group":"modifier"}],"links":[{"id":"reconciles->the-script","from":"reconciles","to":"the-script","kind":"core","label":"什么在对账"},{"id":"reconciles->the-records","from":"reconciles","to":"the-records","kind":"core","label":"对账什么"},{"id":"payment->the-records","from":"payment","to":"the-records","kind":"modifier","label":"说明记录的类型"},{"id":"with-the-bank-statement->reconciles","from":"with-the-bank-statement","to":"reconciles","kind":"modifier","label":"说明与什么对账"},{"id":"every-night->reconciles","from":"every-night","to":"reconciles","kind":"modifier","label":"说明对账的频率"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The script reconciles the records.","sentence_zh":"脚本对账记录。","show_nodes":["the-script","reconciles","the-records"],"show_links":["reconciles->the-script","reconciles->the-records"],"focus_node":"reconciles","note_zh":"先看核心：脚本对账记录。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"The script reconciles the payment records.","sentence_zh":"脚本对账支付记录。","show_nodes":["payment"],"show_links":["payment->the-records"],"focus_node":"payment","note_zh":"这一步说明对账的是支付记录。"},{"step_no":3,"label":"加一点方式","sentence_en":"The script reconciles the payment records with the bank statement.","sentence_zh":"脚本将支付记录与银行对账单进行对账。","show_nodes":["with-the-bank-statement"],"show_links":["with-the-bank-statement->reconciles"],"focus_node":"with-the-bank-statement","note_zh":"这一步说明与银行对账单进行比对。"},{"step_no":4,"label":"加一点时间","sentence_en":"The script reconciles the payment records with the bank statement every night.","sentence_zh":"脚本每晚将支付记录与银行对账单进行对账。","show_nodes":["every-night"],"show_links":["every-night->reconciles"],"focus_node":"every-night","note_zh":"这一步说明对账每天晚上自动运行。"}]}'
  ),
  (
    'record-primary',
    'record',
    'record',
    'record runtime errors',
    '记录',
    'The gateway records errors.',
    '网关记录错误。',
    'The gateway records runtime errors with a stack trace.',
    '网关记录运行时错误及其堆栈跟踪。',
    'api',
    '[{"step_no":1,"label":"主干","sentence_en":"The gateway records errors.","sentence_zh":"网关记录错误。","focus_text":"records","note_zh":"先看核心：网关记录错误。","segments":[{"text":"The gateway records errors","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"The gateway records runtime errors.","sentence_zh":"网关记录运行时错误。","focus_text":"runtime","note_zh":"这一步说明记录的是运行时错误。","segments":[{"text":"The gateway records ","kind":"core"},{"text":"runtime","kind":"modifier"},{"text":" errors","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点方式","sentence_en":"The gateway records runtime errors with a stack trace.","sentence_zh":"网关记录运行时错误及其堆栈跟踪。","focus_text":"with a stack trace","note_zh":"这一步说明每条错误记录都附带堆栈跟踪。","segments":[{"text":"The gateway records runtime errors ","kind":"core"},{"text":"with a stack trace","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-gateway","text":"the gateway","kind":"core","group":"core"},{"id":"records","text":"records","kind":"action","group":"action"},{"id":"errors","text":"errors","kind":"core","group":"core"},{"id":"runtime","text":"runtime","kind":"modifier","group":"modifier"},{"id":"with-a-stack-trace","text":"with a stack trace","kind":"modifier","group":"modifier"}],"links":[{"id":"records->the-gateway","from":"records","to":"the-gateway","kind":"core","label":"什么在记录"},{"id":"records->errors","from":"records","to":"errors","kind":"core","label":"记录什么"},{"id":"runtime->errors","from":"runtime","to":"errors","kind":"modifier","label":"说明错误的类型"},{"id":"with-a-stack-trace->records","from":"with-a-stack-trace","to":"records","kind":"modifier","label":"说明记录包含哪些信息"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The gateway records errors.","sentence_zh":"网关记录错误。","show_nodes":["the-gateway","records","errors"],"show_links":["records->the-gateway","records->errors"],"focus_node":"records","note_zh":"先看核心：网关记录错误。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"The gateway records runtime errors.","sentence_zh":"网关记录运行时错误。","show_nodes":["runtime"],"show_links":["runtime->errors"],"focus_node":"runtime","note_zh":"这一步说明记录的是运行时错误。"},{"step_no":3,"label":"加一点方式","sentence_en":"The gateway records runtime errors with a stack trace.","sentence_zh":"网关记录运行时错误及其堆栈跟踪。","show_nodes":["with-a-stack-trace"],"show_links":["with-a-stack-trace->records"],"focus_node":"with-a-stack-trace","note_zh":"这一步说明每条错误记录都附带堆栈跟踪。"}]}'
  ),
  (
    'recover-primary',
    'recover',
    'recover',
    'recover after a crash',
    '恢复',
    'The node recovered.',
    '节点恢复了。',
    'The node recovered automatically after the crash.',
    '节点在崩溃后自动恢复了。',
    'system',
    '[{"step_no":1,"label":"主干","sentence_en":"The node recovered.","sentence_zh":"节点恢复了。","focus_text":"recovered","note_zh":"先看核心：节点恢复了。","segments":[{"text":"The node recovered","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点方式","sentence_en":"The node recovered automatically.","sentence_zh":"节点自动恢复了。","focus_text":"automatically","note_zh":"这一步说明恢复是自动完成的。","segments":[{"text":"The node recovered ","kind":"core"},{"text":"automatically","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点时间","sentence_en":"The node recovered automatically after the crash.","sentence_zh":"节点在崩溃后自动恢复了。","focus_text":"after the crash","note_zh":"这一步说明恢复发生在崩溃之后。","segments":[{"text":"The node recovered automatically ","kind":"core"},{"text":"after the crash","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-node","text":"the node","kind":"core","group":"core"},{"id":"recovered","text":"recovered","kind":"action","group":"action"},{"id":"automatically","text":"automatically","kind":"modifier","group":"modifier"},{"id":"after-the-crash","text":"after the crash","kind":"modifier","group":"modifier"}],"links":[{"id":"recovered->the-node","from":"recovered","to":"the-node","kind":"core","label":"什么恢复了"},{"id":"automatically->recovered","from":"automatically","to":"recovered","kind":"modifier","label":"说明恢复的方式"},{"id":"after-the-crash->recovered","from":"after-the-crash","to":"recovered","kind":"modifier","label":"说明恢复的时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The node recovered.","sentence_zh":"节点恢复了。","show_nodes":["the-node","recovered"],"show_links":["recovered->the-node"],"focus_node":"recovered","note_zh":"先看核心：节点恢复了。"},{"step_no":2,"label":"加一点方式","sentence_en":"The node recovered automatically.","sentence_zh":"节点自动恢复了。","show_nodes":["automatically"],"show_links":["automatically->recovered"],"focus_node":"automatically","note_zh":"这一步说明恢复是自动完成的。"},{"step_no":3,"label":"加一点时间","sentence_en":"The node recovered automatically after the crash.","sentence_zh":"节点在崩溃后自动恢复了。","show_nodes":["after-the-crash"],"show_links":["after-the-crash->recovered"],"focus_node":"after-the-crash","note_zh":"这一步说明恢复发生在崩溃之后。"}]}'
  ),
  (
    'recruit-primary',
    'recruit',
    'recruit',
    'recruit platform engineers',
    '招聘',
    'The startup recruits engineers.',
    '这家初创公司招聘工程师。',
    'The startup recruits senior engineers for the platform team.',
    '这家初创公司为平台团队招聘资深工程师。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The startup recruits engineers.","sentence_zh":"这家初创公司招聘工程师。","focus_text":"recruits","note_zh":"先看核心：初创公司招聘工程师。","segments":[{"text":"The startup recruits engineers","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"The startup recruits senior engineers.","sentence_zh":"这家初创公司招聘资深工程师。","focus_text":"senior","note_zh":"这一步说明招聘的是资深级别。","segments":[{"text":"The startup recruits ","kind":"core"},{"text":"senior","kind":"modifier"},{"text":" engineers","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点目的","sentence_en":"The startup recruits senior engineers for the platform team.","sentence_zh":"这家初创公司为平台团队招聘资深工程师。","focus_text":"for the platform team","note_zh":"这一步说明招聘是为了充实平台团队。","segments":[{"text":"The startup recruits senior engineers ","kind":"core"},{"text":"for the platform team","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-startup","text":"the startup","kind":"core","group":"core"},{"id":"recruits","text":"recruits","kind":"action","group":"action"},{"id":"engineers","text":"engineers","kind":"core","group":"core"},{"id":"senior","text":"senior","kind":"modifier","group":"modifier"},{"id":"for-the-platform-team","text":"for the platform team","kind":"modifier","group":"modifier"}],"links":[{"id":"recruits->the-startup","from":"recruits","to":"the-startup","kind":"core","label":"谁在招聘"},{"id":"recruits->engineers","from":"recruits","to":"engineers","kind":"core","label":"招聘什么职位"},{"id":"senior->engineers","from":"senior","to":"engineers","kind":"modifier","label":"说明工程师的级别"},{"id":"for-the-platform-team->recruits","from":"for-the-platform-team","to":"recruits","kind":"modifier","label":"说明招聘的目的团队"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The startup recruits engineers.","sentence_zh":"这家初创公司招聘工程师。","show_nodes":["the-startup","recruits","engineers"],"show_links":["recruits->the-startup","recruits->engineers"],"focus_node":"recruits","note_zh":"先看核心：初创公司招聘工程师。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"The startup recruits senior engineers.","sentence_zh":"这家初创公司招聘资深工程师。","show_nodes":["senior"],"show_links":["senior->engineers"],"focus_node":"senior","note_zh":"这一步说明招聘的是资深级别。"},{"step_no":3,"label":"加一点目的","sentence_en":"The startup recruits senior engineers for the platform team.","sentence_zh":"这家初创公司为平台团队招聘资深工程师。","show_nodes":["for-the-platform-team"],"show_links":["for-the-platform-team->recruits"],"focus_node":"for-the-platform-team","note_zh":"这一步说明招聘是为了充实平台团队。"}]}'
  ),
  (
    'redirect-primary',
    'redirect',
    'redirect',
    'redirect incoming traffic',
    '重定向',
    'The proxy redirects traffic.',
    '代理重定向流量。',
    'The proxy redirects incoming traffic to the new domain.',
    '代理将传入流量重定向到新域名。',
    'web',
    '[{"step_no":1,"label":"主干","sentence_en":"The proxy redirects traffic.","sentence_zh":"代理重定向流量。","focus_text":"redirects","note_zh":"先看核心：代理重定向流量。","segments":[{"text":"The proxy redirects traffic","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"The proxy redirects incoming traffic.","sentence_zh":"代理重定向传入流量。","focus_text":"incoming","note_zh":"这一步说明重定向的是来自外部的流量。","segments":[{"text":"The proxy redirects ","kind":"core"},{"text":"incoming","kind":"modifier"},{"text":" traffic","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点方向","sentence_en":"The proxy redirects incoming traffic to the new domain.","sentence_zh":"代理将传入流量重定向到新域名。","focus_text":"to the new domain","note_zh":"这一步说明流量被重定向到新域名。","segments":[{"text":"The proxy redirects incoming traffic ","kind":"core"},{"text":"to the new domain","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-proxy","text":"the proxy","kind":"core","group":"core"},{"id":"redirects","text":"redirects","kind":"action","group":"action"},{"id":"traffic","text":"traffic","kind":"core","group":"core"},{"id":"incoming","text":"incoming","kind":"modifier","group":"modifier"},{"id":"to-the-new-domain","text":"to the new domain","kind":"modifier","group":"modifier"}],"links":[{"id":"redirects->the-proxy","from":"redirects","to":"the-proxy","kind":"core","label":"什么在重定向"},{"id":"redirects->traffic","from":"redirects","to":"traffic","kind":"core","label":"重定向什么"},{"id":"incoming->traffic","from":"incoming","to":"traffic","kind":"modifier","label":"说明流量的方向"},{"id":"to-the-new-domain->redirects","from":"to-the-new-domain","to":"redirects","kind":"modifier","label":"说明重定向的目标"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The proxy redirects traffic.","sentence_zh":"代理重定向流量。","show_nodes":["the-proxy","redirects","traffic"],"show_links":["redirects->the-proxy","redirects->traffic"],"focus_node":"redirects","note_zh":"先看核心：代理重定向流量。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"The proxy redirects incoming traffic.","sentence_zh":"代理重定向传入流量。","show_nodes":["incoming"],"show_links":["incoming->traffic"],"focus_node":"incoming","note_zh":"这一步说明重定向的是来自外部的流量。"},{"step_no":3,"label":"加一点方向","sentence_en":"The proxy redirects incoming traffic to the new domain.","sentence_zh":"代理将传入流量重定向到新域名。","show_nodes":["to-the-new-domain"],"show_links":["to-the-new-domain->redirects"],"focus_node":"to-the-new-domain","note_zh":"这一步说明流量被重定向到新域名。"}]}'
  ),
  (
    'reduce-primary',
    'reduce',
    'reduce',
    'reduce API latency',
    '减少',
    'Caching reduces latency.',
    '缓存减少延迟。',
    'Caching significantly reduces API latency.',
    '缓存显著减少 API 延迟。',
    'performance',
    '[{"step_no":1,"label":"主干","sentence_en":"Caching reduces latency.","sentence_zh":"缓存减少延迟。","focus_text":"reduces","note_zh":"先看核心：缓存减少延迟。","segments":[{"text":"Caching reduces latency","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点范围","sentence_en":"Caching reduces API latency.","sentence_zh":"缓存减少 API 延迟。","focus_text":"API","note_zh":"这一步说明减少的是 API 层面的延迟。","segments":[{"text":"Caching reduces ","kind":"core"},{"text":"API","kind":"modifier"},{"text":" latency","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点程度","sentence_en":"Caching significantly reduces API latency.","sentence_zh":"缓存显著减少 API 延迟。","focus_text":"significantly","note_zh":"这一步说明延迟减少的幅度很大。","segments":[{"text":"Caching ","kind":"core"},{"text":"significantly","kind":"modifier"},{"text":" reduces API latency","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"caching","text":"caching","kind":"core","group":"core"},{"id":"reduces","text":"reduces","kind":"action","group":"action"},{"id":"latency","text":"latency","kind":"core","group":"core"},{"id":"api","text":"API","kind":"modifier","group":"modifier"},{"id":"significantly","text":"significantly","kind":"modifier","group":"modifier"}],"links":[{"id":"reduces->caching","from":"reduces","to":"caching","kind":"core","label":"什么在减少延迟"},{"id":"reduces->latency","from":"reduces","to":"latency","kind":"core","label":"减少什么"},{"id":"api->latency","from":"api","to":"latency","kind":"modifier","label":"说明延迟的范围"},{"id":"significantly->reduces","from":"significantly","to":"reduces","kind":"modifier","label":"说明减少的程度"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Caching reduces latency.","sentence_zh":"缓存减少延迟。","show_nodes":["caching","reduces","latency"],"show_links":["reduces->caching","reduces->latency"],"focus_node":"reduces","note_zh":"先看核心：缓存减少延迟。"},{"step_no":2,"label":"加一点范围","sentence_en":"Caching reduces API latency.","sentence_zh":"缓存减少 API 延迟。","show_nodes":["api"],"show_links":["api->latency"],"focus_node":"api","note_zh":"这一步说明减少的是 API 层面的延迟。"},{"step_no":3,"label":"加一点程度","sentence_en":"Caching significantly reduces API latency.","sentence_zh":"缓存显著减少 API 延迟。","show_nodes":["significantly"],"show_links":["significantly->reduces"],"focus_node":"significantly","note_zh":"这一步说明延迟减少的幅度很大。"}]}'
  ),
  (
    'refactor-primary',
    'refactor',
    'refactor',
    'refactor the auth module',
    '重构',
    'The team refactored the module.',
    '团队重构了模块。',
    'The team refactored the auth module over the weekend to simplify the login flow.',
    '团队在周末重构了认证模块，以简化登录流程。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"The team refactored the module.","sentence_zh":"团队重构了模块。","focus_text":"refactored","note_zh":"先看核心：团队重构了模块。","segments":[{"text":"The team refactored the module","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"加一点对象细节","sentence_en":"The team refactored the auth module.","sentence_zh":"团队重构了认证模块。","focus_text":"auth","note_zh":"这一步说明重构的是认证模块。","segments":[{"text":"The team refactored the ","kind":"core"},{"text":"auth","kind":"modifier"},{"text":" module","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"加一点时间","sentence_en":"The team refactored the auth module over the weekend.","sentence_zh":"团队在周末重构了认证模块。","focus_text":"over the weekend","note_zh":"这一步说明重构在周末进行。","segments":[{"text":"The team refactored the auth module ","kind":"core"},{"text":"over the weekend","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":4,"label":"加一点目的","sentence_en":"The team refactored the auth module over the weekend to simplify the login flow.","sentence_zh":"团队在周末重构了认证模块，以简化登录流程。","focus_text":"to simplify the login flow","note_zh":"这一步说明重构是为了简化登录流程。","segments":[{"text":"The team refactored the auth module over the weekend ","kind":"core"},{"text":"to simplify the login flow","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-team","text":"the team","kind":"core","group":"core"},{"id":"refactored","text":"refactored","kind":"action","group":"action"},{"id":"the-module","text":"the module","kind":"core","group":"core"},{"id":"auth","text":"auth","kind":"modifier","group":"modifier"},{"id":"over-the-weekend","text":"over the weekend","kind":"modifier","group":"modifier"},{"id":"to-simplify-the-login-flow","text":"to simplify the login flow","kind":"modifier","group":"modifier"}],"links":[{"id":"refactored->the-team","from":"refactored","to":"the-team","kind":"core","label":"谁在重构"},{"id":"refactored->the-module","from":"refactored","to":"the-module","kind":"core","label":"重构什么"},{"id":"auth->the-module","from":"auth","to":"the-module","kind":"modifier","label":"说明模块的类型"},{"id":"over-the-weekend->refactored","from":"over-the-weekend","to":"refactored","kind":"modifier","label":"说明重构的时间"},{"id":"to-simplify-the-login-flow->refactored","from":"to-simplify-the-login-flow","to":"refactored","kind":"modifier","label":"说明重构的目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team refactored the module.","sentence_zh":"团队重构了模块。","show_nodes":["the-team","refactored","the-module"],"show_links":["refactored->the-team","refactored->the-module"],"focus_node":"refactored","note_zh":"先看核心：团队重构了模块。"},{"step_no":2,"label":"加一点对象细节","sentence_en":"The team refactored the auth module.","sentence_zh":"团队重构了认证模块。","show_nodes":["auth"],"show_links":["auth->the-module"],"focus_node":"auth","note_zh":"这一步说明重构的是认证模块。"},{"step_no":3,"label":"加一点时间","sentence_en":"The team refactored the auth module over the weekend.","sentence_zh":"团队在周末重构了认证模块。","show_nodes":["over-the-weekend"],"show_links":["over-the-weekend->refactored"],"focus_node":"over-the-weekend","note_zh":"这一步说明重构在周末进行。"},{"step_no":4,"label":"加一点目的","sentence_en":"The team refactored the auth module over the weekend to simplify the login flow.","sentence_zh":"团队在周末重构了认证模块，以简化登录流程。","show_nodes":["to-simplify-the-login-flow"],"show_links":["to-simplify-the-login-flow->refactored"],"focus_node":"to-simplify-the-login-flow","note_zh":"这一步说明重构是为了简化登录流程。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  steps_json = excluded.steps_json,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
