-- Generated verb paths batch batch-013.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  steps_json,
  growth_json
) VALUES
  (
    'regulate-primary',
    'regulate',
    'regulate',
    'regulate data collection',
    '监管',
    'The law regulates data collection.',
    '法律监管数据收集。',
    'The law strictly regulates data collection across all platforms.',
    '法律在所有平台上严格监管数据收集。',
    'compliance',
    '[{"step_no":1,"label":"主干","sentence_en":"The law regulates data collection.","sentence_zh":"法律监管数据收集。","focus_text":"regulates","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"The law regulates data collection","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The law strictly regulates data collection.","sentence_zh":"法律严格监管数据收集。","focus_text":"strictly","note_zh":"这一步说明监管的严格程度。","segments":[{"text":"The law ","kind":"core"},{"text":"strictly","kind":"modifier"},{"text":" regulates data collection","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"范围","sentence_en":"The law strictly regulates data collection across all platforms.","sentence_zh":"法律在所有平台上严格监管数据收集。","focus_text":"across all platforms","note_zh":"这一步说明监管适用的平台范围。","segments":[{"text":"The law strictly regulates data collection ","kind":"core"},{"text":"across all platforms","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-law","text":"the law","kind":"core","group":"core"},{"id":"regulates","text":"regulates","kind":"action","group":"action"},{"id":"data-collection","text":"data collection","kind":"core","group":"core"},{"id":"strictly","text":"strictly","kind":"modifier","group":"modifier"},{"id":"across-all-platforms","text":"across all platforms","kind":"modifier","group":"modifier"}],"links":[{"id":"regulates->the-law","from":"regulates","to":"the-law","kind":"core","label":"监管主体"},{"id":"regulates->data-collection","from":"regulates","to":"data-collection","kind":"core","label":"监管对象"},{"id":"strictly->regulates","from":"strictly","to":"regulates","kind":"modifier","label":"监管程度"},{"id":"across-all-platforms->regulates","from":"across-all-platforms","to":"regulates","kind":"modifier","label":"适用范围"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The law regulates data collection.","sentence_zh":"法律监管数据收集。","show_nodes":["the-law","regulates","data-collection"],"show_links":["regulates->the-law","regulates->data-collection"],"focus_node":"regulates","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"程度","sentence_en":"The law strictly regulates data collection.","sentence_zh":"法律严格监管数据收集。","show_nodes":["strictly"],"show_links":["strictly->regulates"],"focus_node":"strictly","note_zh":"这一步说明监管的严格程度。"},{"step_no":3,"label":"范围","sentence_en":"The law strictly regulates data collection across all platforms.","sentence_zh":"法律在所有平台上严格监管数据收集。","show_nodes":["across-all-platforms"],"show_links":["across-all-platforms->regulates"],"focus_node":"across-all-platforms","note_zh":"这一步说明监管适用的平台范围。"}]}'
  ),
  (
    'reimburse-primary',
    'reimburse',
    'reimburse',
    'reimburse travel expenses',
    '报销',
    'The company reimburses travel expenses.',
    '公司报销差旅费。',
    'The company reimburses travel expenses in full within 30 days.',
    '公司在30天内全额报销差旅费。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The company reimburses travel expenses.","sentence_zh":"公司报销差旅费。","focus_text":"reimburses","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"The company reimburses travel expenses","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The company reimburses travel expenses in full.","sentence_zh":"公司全额报销差旅费。","focus_text":"in full","note_zh":"这一步说明报销的比例。","segments":[{"text":"The company reimburses travel expenses ","kind":"core"},{"text":"in full","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"时间","sentence_en":"The company reimburses travel expenses in full within 30 days.","sentence_zh":"公司在30天内全额报销差旅费。","focus_text":"within 30 days","note_zh":"这一步说明报销到账的时间。","segments":[{"text":"The company reimburses travel expenses in full ","kind":"core"},{"text":"within 30 days","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-company","text":"the company","kind":"core","group":"core"},{"id":"reimburses","text":"reimburses","kind":"action","group":"action"},{"id":"travel-expenses","text":"travel expenses","kind":"core","group":"core"},{"id":"in-full","text":"in full","kind":"modifier","group":"modifier"},{"id":"within-30-days","text":"within 30 days","kind":"modifier","group":"modifier"}],"links":[{"id":"reimburses->the-company","from":"reimburses","to":"the-company","kind":"core","label":"报销方"},{"id":"reimburses->travel-expenses","from":"reimburses","to":"travel-expenses","kind":"core","label":"报销内容"},{"id":"in-full->reimburses","from":"in-full","to":"reimburses","kind":"modifier","label":"报销程度"},{"id":"within-30-days->reimburses","from":"within-30-days","to":"reimburses","kind":"modifier","label":"报销时限"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The company reimburses travel expenses.","sentence_zh":"公司报销差旅费。","show_nodes":["the-company","reimburses","travel-expenses"],"show_links":["reimburses->the-company","reimburses->travel-expenses"],"focus_node":"reimburses","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"程度","sentence_en":"The company reimburses travel expenses in full.","sentence_zh":"公司全额报销差旅费。","show_nodes":["in-full"],"show_links":["in-full->reimburses"],"focus_node":"in-full","note_zh":"这一步说明报销的比例。"},{"step_no":3,"label":"时间","sentence_en":"The company reimburses travel expenses in full within 30 days.","sentence_zh":"公司在30天内全额报销差旅费。","show_nodes":["within-30-days"],"show_links":["within-30-days->reimburses"],"focus_node":"within-30-days","note_zh":"这一步说明报销到账的时间。"}]}'
  ),
  (
    'rein-in-primary',
    'rein-in',
    'rein in',
    'rein in spending',
    '控制；收紧',
    'The manager reined in spending.',
    '经理收紧开支。',
    'The manager sharply reined in spending after the budget review.',
    '预算审查后，经理大幅收紧开支。',
    'management',
    '[{"step_no":1,"label":"主干","sentence_en":"The manager reined in spending.","sentence_zh":"经理收紧开支。","focus_text":"reined in","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"The manager reined in spending","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The manager sharply reined in spending.","sentence_zh":"经理大幅收紧开支。","focus_text":"sharply","note_zh":"这一步说明收紧的力度。","segments":[{"text":"The manager ","kind":"core"},{"text":"sharply","kind":"modifier"},{"text":" reined in spending","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"条件","sentence_en":"The manager sharply reined in spending after the budget review.","sentence_zh":"预算审查后，经理大幅收紧开支。","focus_text":"after the budget review","note_zh":"这一步说明收紧开支的触发条件。","segments":[{"text":"The manager sharply reined in spending ","kind":"core"},{"text":"after the budget review","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-manager","text":"the manager","kind":"core","group":"core"},{"id":"reined-in","text":"reined in","kind":"action","group":"action"},{"id":"spending","text":"spending","kind":"core","group":"core"},{"id":"sharply","text":"sharply","kind":"modifier","group":"modifier"},{"id":"after-the-budget-review","text":"after the budget review","kind":"modifier","group":"modifier"}],"links":[{"id":"reined-in->the-manager","from":"reined-in","to":"the-manager","kind":"core","label":"执行者"},{"id":"reined-in->spending","from":"reined-in","to":"spending","kind":"core","label":"控制对象"},{"id":"sharply->reined-in","from":"sharply","to":"reined-in","kind":"modifier","label":"收紧程度"},{"id":"after-the-budget-review->reined-in","from":"after-the-budget-review","to":"reined-in","kind":"modifier","label":"触发时机"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The manager reined in spending.","sentence_zh":"经理收紧开支。","show_nodes":["the-manager","reined-in","spending"],"show_links":["reined-in->the-manager","reined-in->spending"],"focus_node":"reined-in","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"程度","sentence_en":"The manager sharply reined in spending.","sentence_zh":"经理大幅收紧开支。","show_nodes":["sharply"],"show_links":["sharply->reined-in"],"focus_node":"sharply","note_zh":"这一步说明收紧的力度。"},{"step_no":3,"label":"条件","sentence_en":"The manager sharply reined in spending after the budget review.","sentence_zh":"预算审查后，经理大幅收紧开支。","show_nodes":["after-the-budget-review"],"show_links":["after-the-budget-review->reined-in"],"focus_node":"after-the-budget-review","note_zh":"这一步说明收紧开支的触发条件。"}]}'
  ),
  (
    'reinforce-primary',
    'reinforce',
    'reinforce',
    'reinforce security measures',
    '加强；强化',
    'The team reinforces security measures.',
    '团队加强安全措施。',
    'The team reinforces security measures after each incident with additional checks.',
    '团队在每次事件后通过额外检查加强安全措施。',
    'security',
    '[{"step_no":1,"label":"主干","sentence_en":"The team reinforces security measures.","sentence_zh":"团队加强安全措施。","focus_text":"reinforces","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"The team reinforces security measures","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"条件","sentence_en":"The team reinforces security measures after each incident.","sentence_zh":"团队在每次事件后加强安全措施。","focus_text":"after each incident","note_zh":"这一步说明加强措施的触发时机。","segments":[{"text":"The team reinforces security measures ","kind":"core"},{"text":"after each incident","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"方式","sentence_en":"The team reinforces security measures after each incident with additional checks.","sentence_zh":"团队在每次事件后通过额外检查加强安全措施。","focus_text":"with additional checks","note_zh":"这一步说明加强措施的具体方式。","segments":[{"text":"The team reinforces security measures after each incident ","kind":"core"},{"text":"with additional checks","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-team","text":"the team","kind":"core","group":"core"},{"id":"reinforces","text":"reinforces","kind":"action","group":"action"},{"id":"security-measures","text":"security measures","kind":"core","group":"core"},{"id":"after-each-incident","text":"after each incident","kind":"modifier","group":"modifier"},{"id":"with-additional-checks","text":"with additional checks","kind":"modifier","group":"modifier"}],"links":[{"id":"reinforces->the-team","from":"reinforces","to":"the-team","kind":"core","label":"执行者"},{"id":"reinforces->security-measures","from":"reinforces","to":"security-measures","kind":"core","label":"强化对象"},{"id":"after-each-incident->reinforces","from":"after-each-incident","to":"reinforces","kind":"modifier","label":"强化时机"},{"id":"with-additional-checks->reinforces","from":"with-additional-checks","to":"reinforces","kind":"modifier","label":"强化方式"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team reinforces security measures.","sentence_zh":"团队加强安全措施。","show_nodes":["the-team","reinforces","security-measures"],"show_links":["reinforces->the-team","reinforces->security-measures"],"focus_node":"reinforces","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"条件","sentence_en":"The team reinforces security measures after each incident.","sentence_zh":"团队在每次事件后加强安全措施。","show_nodes":["after-each-incident"],"show_links":["after-each-incident->reinforces"],"focus_node":"after-each-incident","note_zh":"这一步说明加强措施的触发时机。"},{"step_no":3,"label":"方式","sentence_en":"The team reinforces security measures after each incident with additional checks.","sentence_zh":"团队在每次事件后通过额外检查加强安全措施。","show_nodes":["with-additional-checks"],"show_links":["with-additional-checks->reinforces"],"focus_node":"with-additional-checks","note_zh":"这一步说明加强措施的具体方式。"}]}'
  ),
  (
    'reiterate-primary',
    'reiterate',
    'reiterate',
    'reiterate the deadline',
    '重申',
    'The lead reiterates the deadline.',
    '负责人重申截止日期。',
    'The lead clearly reiterates the deadline at every standup.',
    '负责人在每次站会上清楚地重申截止日期。',
    'workplace',
    '[{"step_no":1,"label":"主干","sentence_en":"The lead reiterates the deadline.","sentence_zh":"负责人重申截止日期。","focus_text":"reiterates","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"The lead reiterates the deadline","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"场景","sentence_en":"The lead reiterates the deadline at every standup.","sentence_zh":"负责人在每次站会上重申截止日期。","focus_text":"at every standup","note_zh":"这一步说明重申发生的场景。","segments":[{"text":"The lead reiterates the deadline ","kind":"core"},{"text":"at every standup","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"方式","sentence_en":"The lead clearly reiterates the deadline at every standup.","sentence_zh":"负责人在每次站会上清楚地重申截止日期。","focus_text":"clearly","note_zh":"这一步说明重申的方式。","segments":[{"text":"The lead ","kind":"core"},{"text":"clearly","kind":"modifier"},{"text":" reiterates the deadline at every standup","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-lead","text":"the lead","kind":"core","group":"core"},{"id":"reiterates","text":"reiterates","kind":"action","group":"action"},{"id":"the-deadline","text":"the deadline","kind":"core","group":"core"},{"id":"at-every-standup","text":"at every standup","kind":"modifier","group":"modifier"},{"id":"clearly","text":"clearly","kind":"modifier","group":"modifier"}],"links":[{"id":"reiterates->the-lead","from":"reiterates","to":"the-lead","kind":"core","label":"重申者"},{"id":"reiterates->the-deadline","from":"reiterates","to":"the-deadline","kind":"core","label":"重申内容"},{"id":"at-every-standup->reiterates","from":"at-every-standup","to":"reiterates","kind":"modifier","label":"重申场景"},{"id":"clearly->reiterates","from":"clearly","to":"reiterates","kind":"modifier","label":"重申方式"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The lead reiterates the deadline.","sentence_zh":"负责人重申截止日期。","show_nodes":["the-lead","reiterates","the-deadline"],"show_links":["reiterates->the-lead","reiterates->the-deadline"],"focus_node":"reiterates","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"场景","sentence_en":"The lead reiterates the deadline at every standup.","sentence_zh":"负责人在每次站会上重申截止日期。","show_nodes":["at-every-standup"],"show_links":["at-every-standup->reiterates"],"focus_node":"at-every-standup","note_zh":"这一步说明重申发生的场景。"},{"step_no":3,"label":"方式","sentence_en":"The lead clearly reiterates the deadline at every standup.","sentence_zh":"负责人在每次站会上清楚地重申截止日期。","show_nodes":["clearly"],"show_links":["clearly->reiterates"],"focus_node":"clearly","note_zh":"这一步说明重申的方式。"}]}'
  ),
  (
    'reject-primary',
    'reject',
    'reject',
    'reject a pull request',
    '拒绝',
    'The reviewer rejects the pull request.',
    '审核者拒绝了拉取请求。',
    'The reviewer immediately rejects the pull request for security reasons.',
    '审核者出于安全原因立即拒绝了拉取请求。',
    'code',
    '[{"step_no":1,"label":"主干","sentence_en":"The reviewer rejects the pull request.","sentence_zh":"审核者拒绝了拉取请求。","focus_text":"rejects","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"The reviewer rejects the pull request","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"原因","sentence_en":"The reviewer rejects the pull request for security reasons.","sentence_zh":"审核者出于安全原因拒绝了拉取请求。","focus_text":"for security reasons","note_zh":"这一步说明拒绝的原因。","segments":[{"text":"The reviewer rejects the pull request ","kind":"core"},{"text":"for security reasons","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"方式","sentence_en":"The reviewer immediately rejects the pull request for security reasons.","sentence_zh":"审核者出于安全原因立即拒绝了拉取请求。","focus_text":"immediately","note_zh":"这一步说明拒绝的速度。","segments":[{"text":"The reviewer ","kind":"core"},{"text":"immediately","kind":"modifier"},{"text":" rejects the pull request for security reasons","kind":"core"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-reviewer","text":"the reviewer","kind":"core","group":"core"},{"id":"rejects","text":"rejects","kind":"action","group":"action"},{"id":"the-pull-request","text":"the pull request","kind":"core","group":"core"},{"id":"for-security-reasons","text":"for security reasons","kind":"modifier","group":"modifier"},{"id":"immediately","text":"immediately","kind":"modifier","group":"modifier"}],"links":[{"id":"rejects->the-reviewer","from":"rejects","to":"the-reviewer","kind":"core","label":"拒绝者"},{"id":"rejects->the-pull-request","from":"rejects","to":"the-pull-request","kind":"core","label":"拒绝对象"},{"id":"for-security-reasons->rejects","from":"for-security-reasons","to":"rejects","kind":"modifier","label":"拒绝原因"},{"id":"immediately->rejects","from":"immediately","to":"rejects","kind":"modifier","label":"拒绝速度"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The reviewer rejects the pull request.","sentence_zh":"审核者拒绝了拉取请求。","show_nodes":["the-reviewer","rejects","the-pull-request"],"show_links":["rejects->the-reviewer","rejects->the-pull-request"],"focus_node":"rejects","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"原因","sentence_en":"The reviewer rejects the pull request for security reasons.","sentence_zh":"审核者出于安全原因拒绝了拉取请求。","show_nodes":["for-security-reasons"],"show_links":["for-security-reasons->rejects"],"focus_node":"for-security-reasons","note_zh":"这一步说明拒绝的原因。"},{"step_no":3,"label":"方式","sentence_en":"The reviewer immediately rejects the pull request for security reasons.","sentence_zh":"审核者出于安全原因立即拒绝了拉取请求。","show_nodes":["immediately"],"show_links":["immediately->rejects"],"focus_node":"immediately","note_zh":"这一步说明拒绝的速度。"}]}'
  ),
  (
    'relate-primary',
    'relate',
    'relate',
    'relate each error to a request ID',
    '关联；联系',
    'The log relates each error to a request ID.',
    '日志将每个错误关联到一个请求ID。',
    'The log automatically relates each error to a request ID for faster debugging.',
    '日志自动将每个错误关联到一个请求ID，以便更快调试。',
    'debug',
    '[{"step_no":1,"label":"主干","sentence_en":"The log relates each error to a request ID.","sentence_zh":"日志将每个错误关联到一个请求ID。","focus_text":"relates","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"The log relates each error to a request ID","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"方式","sentence_en":"The log automatically relates each error to a request ID.","sentence_zh":"日志自动将每个错误关联到一个请求ID。","focus_text":"automatically","note_zh":"这一步说明关联的方式。","segments":[{"text":"The log ","kind":"core"},{"text":"automatically","kind":"modifier"},{"text":" relates each error to a request ID","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"目的","sentence_en":"The log automatically relates each error to a request ID for faster debugging.","sentence_zh":"日志自动将每个错误关联到一个请求ID，以便更快调试。","focus_text":"for faster debugging","note_zh":"这一步说明这样关联的目的。","segments":[{"text":"The log automatically relates each error to a request ID ","kind":"core"},{"text":"for faster debugging","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-log","text":"the log","kind":"core","group":"core"},{"id":"relates","text":"relates","kind":"action","group":"action"},{"id":"each-error","text":"each error","kind":"core","group":"core"},{"id":"to-a-request-id","text":"to a request ID","kind":"core","group":"core"},{"id":"automatically","text":"automatically","kind":"modifier","group":"modifier"},{"id":"for-faster-debugging","text":"for faster debugging","kind":"modifier","group":"modifier"}],"links":[{"id":"relates->the-log","from":"relates","to":"the-log","kind":"core","label":"关联来源"},{"id":"relates->each-error","from":"relates","to":"each-error","kind":"core","label":"被关联项"},{"id":"relates->to-a-request-id","from":"relates","to":"to-a-request-id","kind":"core","label":"关联目标"},{"id":"automatically->relates","from":"automatically","to":"relates","kind":"modifier","label":"关联方式"},{"id":"for-faster-debugging->relates","from":"for-faster-debugging","to":"relates","kind":"modifier","label":"关联目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The log relates each error to a request ID.","sentence_zh":"日志将每个错误关联到一个请求ID。","show_nodes":["the-log","relates","each-error","to-a-request-id"],"show_links":["relates->the-log","relates->each-error","relates->to-a-request-id"],"focus_node":"relates","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"方式","sentence_en":"The log automatically relates each error to a request ID.","sentence_zh":"日志自动将每个错误关联到一个请求ID。","show_nodes":["automatically"],"show_links":["automatically->relates"],"focus_node":"automatically","note_zh":"这一步说明关联的方式。"},{"step_no":3,"label":"目的","sentence_en":"The log automatically relates each error to a request ID for faster debugging.","sentence_zh":"日志自动将每个错误关联到一个请求ID，以便更快调试。","show_nodes":["for-faster-debugging"],"show_links":["for-faster-debugging->relates"],"focus_node":"for-faster-debugging","note_zh":"这一步说明这样关联的目的。"}]}'
  ),
  (
    'relate-to-primary',
    'relate-to',
    'relate to',
    'relate to the timeout',
    '与……相关',
    'This error relates to the database timeout.',
    '这个错误与数据库超时有关。',
    'This error directly relates to the database timeout under heavy load.',
    '这个错误在高负载下与数据库超时直接相关。',
    'debug',
    '[{"step_no":1,"label":"主干","sentence_en":"This error relates to the database timeout.","sentence_zh":"这个错误与数据库超时有关。","focus_text":"relates to","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"This error relates to the database timeout","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"This error directly relates to the database timeout.","sentence_zh":"这个错误与数据库超时直接相关。","focus_text":"directly","note_zh":"这一步说明关联的直接程度。","segments":[{"text":"This error ","kind":"core"},{"text":"directly","kind":"modifier"},{"text":" relates to the database timeout","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"条件","sentence_en":"This error directly relates to the database timeout under heavy load.","sentence_zh":"这个错误在高负载下与数据库超时直接相关。","focus_text":"under heavy load","note_zh":"这一步说明关联发生的条件。","segments":[{"text":"This error directly relates to the database timeout ","kind":"core"},{"text":"under heavy load","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"this-error","text":"this error","kind":"core","group":"core"},{"id":"relates-to","text":"relates to","kind":"action","group":"action"},{"id":"the-database-timeout","text":"the database timeout","kind":"core","group":"core"},{"id":"directly","text":"directly","kind":"modifier","group":"modifier"},{"id":"under-heavy-load","text":"under heavy load","kind":"modifier","group":"modifier"}],"links":[{"id":"relates-to->this-error","from":"relates-to","to":"this-error","kind":"core","label":"关联方"},{"id":"relates-to->the-database-timeout","from":"relates-to","to":"the-database-timeout","kind":"core","label":"关联对象"},{"id":"directly->relates-to","from":"directly","to":"relates-to","kind":"modifier","label":"关联程度"},{"id":"under-heavy-load->relates-to","from":"under-heavy-load","to":"relates-to","kind":"modifier","label":"发生条件"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"This error relates to the database timeout.","sentence_zh":"这个错误与数据库超时有关。","show_nodes":["this-error","relates-to","the-database-timeout"],"show_links":["relates-to->this-error","relates-to->the-database-timeout"],"focus_node":"relates-to","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"程度","sentence_en":"This error directly relates to the database timeout.","sentence_zh":"这个错误与数据库超时直接相关。","show_nodes":["directly"],"show_links":["directly->relates-to"],"focus_node":"directly","note_zh":"这一步说明关联的直接程度。"},{"step_no":3,"label":"条件","sentence_en":"This error directly relates to the database timeout under heavy load.","sentence_zh":"这个错误在高负载下与数据库超时直接相关。","show_nodes":["under-heavy-load"],"show_links":["under-heavy-load->relates-to"],"focus_node":"under-heavy-load","note_zh":"这一步说明关联发生的条件。"}]}'
  ),
  (
    'relax-primary',
    'relax',
    'relax',
    'relax after work',
    '放松',
    'She relaxes.',
    '她放松。',
    'She relaxes at home after work.',
    '她下班后在家放松。',
    'daily',
    '[{"step_no":1,"label":"主干","sentence_en":"She relaxes.","sentence_zh":"她放松。","focus_text":"relaxes","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"She relaxes","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"场景","sentence_en":"She relaxes at home.","sentence_zh":"她在家放松。","focus_text":"at home","note_zh":"这一步说明放松的地点。","segments":[{"text":"She relaxes ","kind":"core"},{"text":"at home","kind":"modifier"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"时间","sentence_en":"She relaxes at home after work.","sentence_zh":"她下班后在家放松。","focus_text":"after work","note_zh":"这一步说明放松的时间。","segments":[{"text":"She relaxes at home ","kind":"core"},{"text":"after work","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"she","text":"she","kind":"core","group":"core"},{"id":"relaxes","text":"relaxes","kind":"action","group":"action"},{"id":"at-home","text":"at home","kind":"modifier","group":"modifier"},{"id":"after-work","text":"after work","kind":"modifier","group":"modifier"}],"links":[{"id":"relaxes->she","from":"relaxes","to":"she","kind":"core","label":"放松者"},{"id":"at-home->relaxes","from":"at-home","to":"relaxes","kind":"modifier","label":"放松地点"},{"id":"after-work->relaxes","from":"after-work","to":"relaxes","kind":"modifier","label":"放松时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"She relaxes.","sentence_zh":"她放松。","show_nodes":["she","relaxes"],"show_links":["relaxes->she"],"focus_node":"relaxes","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"场景","sentence_en":"She relaxes at home.","sentence_zh":"她在家放松。","show_nodes":["at-home"],"show_links":["at-home->relaxes"],"focus_node":"at-home","note_zh":"这一步说明放松的地点。"},{"step_no":3,"label":"时间","sentence_en":"She relaxes at home after work.","sentence_zh":"她下班后在家放松。","show_nodes":["after-work"],"show_links":["after-work->relaxes"],"focus_node":"after-work","note_zh":"这一步说明放松的时间。"}]}'
  ),
  (
    'relieve-primary',
    'relieve',
    'relieve',
    'relieve server pressure',
    '缓解；减轻',
    'The cache relieves server pressure.',
    '缓存缓解了服务器压力。',
    'The cache significantly relieves server pressure during peak hours.',
    '缓存在高峰时段显著缓解了服务器压力。',
    'system',
    '[{"step_no":1,"label":"主干","sentence_en":"The cache relieves server pressure.","sentence_zh":"缓存缓解了服务器压力。","focus_text":"relieves","note_zh":"这一步展示句子的核心动作和主干。","segments":[{"text":"The cache relieves server pressure","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":2,"label":"程度","sentence_en":"The cache significantly relieves server pressure.","sentence_zh":"缓存显著缓解了服务器压力。","focus_text":"significantly","note_zh":"这一步说明缓解的程度。","segments":[{"text":"The cache ","kind":"core"},{"text":"significantly","kind":"modifier"},{"text":" relieves server pressure","kind":"core"},{"text":".","kind":"punctuation"}]},{"step_no":3,"label":"时间","sentence_en":"The cache significantly relieves server pressure during peak hours.","sentence_zh":"缓存在高峰时段显著缓解了服务器压力。","focus_text":"during peak hours","note_zh":"这一步说明缓解发生的时段。","segments":[{"text":"The cache significantly relieves server pressure ","kind":"core"},{"text":"during peak hours","kind":"modifier"},{"text":".","kind":"punctuation"}]}]',
    '{"nodes":[{"id":"the-cache","text":"the cache","kind":"core","group":"core"},{"id":"relieves","text":"relieves","kind":"action","group":"action"},{"id":"server-pressure","text":"server pressure","kind":"core","group":"core"},{"id":"significantly","text":"significantly","kind":"modifier","group":"modifier"},{"id":"during-peak-hours","text":"during peak hours","kind":"modifier","group":"modifier"}],"links":[{"id":"relieves->the-cache","from":"relieves","to":"the-cache","kind":"core","label":"缓解者"},{"id":"relieves->server-pressure","from":"relieves","to":"server-pressure","kind":"core","label":"缓解对象"},{"id":"significantly->relieves","from":"significantly","to":"relieves","kind":"modifier","label":"缓解程度"},{"id":"during-peak-hours->relieves","from":"during-peak-hours","to":"relieves","kind":"modifier","label":"缓解时机"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The cache relieves server pressure.","sentence_zh":"缓存缓解了服务器压力。","show_nodes":["the-cache","relieves","server-pressure"],"show_links":["relieves->the-cache","relieves->server-pressure"],"focus_node":"relieves","note_zh":"这一步展示句子的核心动作和主干。"},{"step_no":2,"label":"程度","sentence_en":"The cache significantly relieves server pressure.","sentence_zh":"缓存显著缓解了服务器压力。","show_nodes":["significantly"],"show_links":["significantly->relieves"],"focus_node":"significantly","note_zh":"这一步说明缓解的程度。"},{"step_no":3,"label":"时间","sentence_en":"The cache significantly relieves server pressure during peak hours.","sentence_zh":"缓存在高峰时段显著缓解了服务器压力。","show_nodes":["during-peak-hours"],"show_links":["during-peak-hours->relieves"],"focus_node":"during-peak-hours","note_zh":"这一步说明缓解发生的时段。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  steps_json = excluded.steps_json,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
