-- Generated verb paths batch batch-004.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'become-primary',
    'become',
    'become',
    'become stable',
    '变得稳定',
    'The prototype became stable.',
    '这个原型变得稳定了。',
    'The prototype became stable after it passed the overnight stress test.',
    '这个原型通过通宵压力测试后变得稳定了。',
    'prototype-stability',
    '{"schema_version":2,"root_action_id":"became","nodes":[{"id":"became","text":"became","kind":"action","label_zh":"原型转入稳定状态"},{"id":"prototype","text":"The prototype","kind":"core","label_zh":"发生状态变化的原型"},{"id":"stable","text":"stable","kind":"core","label_zh":"原型最终达到的稳定状态"},{"id":"passed","text":"passed","kind":"action","label_zh":"原型通过压力测试"},{"id":"it","text":"it","kind":"core","label_zh":"参加测试的原型"},{"id":"stress-test","text":"the overnight stress test","kind":"core","label_zh":"原型通过的通宵压力测试"}],"links":[{"id":"became->prototype","from":"became","to":"prototype","kind":"core","relation_type":"actor","label_zh":"说明哪个原型发生了变化"},{"id":"became->stable","from":"became","to":"stable","kind":"core","relation_type":"result","label_zh":"说明原型变成了什么状态"},{"id":"passed->it","from":"passed","to":"it","kind":"core","relation_type":"actor","label_zh":"说明是该原型通过测试"},{"id":"passed->stress-test","from":"passed","to":"stress-test","kind":"core","relation_type":"target","label_zh":"说明原型通过了哪项测试"},{"id":"passed->became","from":"passed","to":"became","kind":"modifier","relation_type":"time","label_zh":"通过测试后才出现稳定状态"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The prototype became stable.","sentence_zh":"这个原型变得稳定了。","add_node_ids":["became","prototype","stable"],"add_link_ids":["became->prototype","became->stable"],"focus_node_id":"became","note_zh":"先呈现原型从原有状态转为稳定状态。"},{"step_no":2,"label":"时间","sentence_en":"The prototype became stable after it passed the overnight stress test.","sentence_zh":"这个原型通过通宵压力测试后变得稳定了。","add_node_ids":["passed","it","stress-test"],"add_link_ids":["passed->it","passed->stress-test","passed->became"],"focus_node_id":"passed","note_zh":"测试事件确定了状态变化出现的时间。"}]}'
  ),
  (
    'beg-primary',
    'beg',
    'beg',
    'beg for a review',
    '恳求某人进行检查',
    'The intern begged Lena to review the rollback plan.',
    '实习生恳求莉娜检查回滚方案。',
    'The intern begged Lena to review the rollback plan immediately.',
    '实习生恳求莉娜立即检查回滚方案。',
    'rollback-review',
    '{"schema_version":2,"root_action_id":"begged","nodes":[{"id":"begged","text":"begged","kind":"action","label_zh":"实习生急切提出请求"},{"id":"intern","text":"The intern","kind":"core","label_zh":"发出恳求的实习生"},{"id":"lena","text":"Lena","kind":"core","label_zh":"收到请求的莉娜"},{"id":"review","text":"review","kind":"action","label_zh":"莉娜检查回滚方案"},{"id":"rollback-plan","text":"the rollback plan","kind":"core","label_zh":"需要检查的回滚方案"},{"id":"immediately","text":"immediately","kind":"modifier","label_zh":"要求检查立刻进行"}],"links":[{"id":"begged->intern","from":"begged","to":"intern","kind":"core","relation_type":"actor","label_zh":"说明是谁发出了恳求"},{"id":"begged->lena","from":"begged","to":"lena","kind":"core","relation_type":"recipient","label_zh":"说明恳求是向谁提出的"},{"id":"begged->review","from":"begged","to":"review","kind":"core","relation_type":"content","label_zh":"说明恳求对方完成什么行动"},{"id":"review->lena","from":"review","to":"lena","kind":"core","relation_type":"shared_actor","label_zh":"莉娜也是执行检查的人"},{"id":"review->rollback-plan","from":"review","to":"rollback-plan","kind":"core","relation_type":"target","label_zh":"说明需要检查哪份方案"},{"id":"immediately->review","from":"immediately","to":"review","kind":"modifier","relation_type":"time","label_zh":"说明检查不能延后"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The intern begged Lena to review the rollback plan.","sentence_zh":"实习生恳求莉娜检查回滚方案。","add_node_ids":["begged","intern","lena","review","rollback-plan"],"add_link_ids":["begged->intern","begged->lena","begged->review","review->lena","review->rollback-plan"],"focus_node_id":"begged","note_zh":"请求对象和希望完成的行动都在主干中出现。"},{"step_no":2,"label":"时间要求","sentence_en":"The intern begged Lena to review the rollback plan immediately.","sentence_zh":"实习生恳求莉娜立即检查回滚方案。","add_node_ids":["immediately"],"add_link_ids":["immediately->review"],"focus_node_id":"immediately","note_zh":"时间词直接限定检查行动。"}]}'
  ),
  (
    'begin-primary',
    'begin',
    'begin',
    'begin at midnight',
    '开始发生',
    'The migration began.',
    '数据迁移开始了。',
    'The migration began at midnight.',
    '数据迁移在午夜开始了。',
    'midnight-migration',
    '{"schema_version":2,"root_action_id":"began","nodes":[{"id":"began","text":"began","kind":"action","label_zh":"迁移任务正式启动"},{"id":"migration","text":"The migration","kind":"core","label_zh":"开始运行的数据迁移"},{"id":"at-midnight","text":"at midnight","kind":"modifier","label_zh":"迁移启动的午夜时刻"}],"links":[{"id":"began->migration","from":"began","to":"migration","kind":"core","relation_type":"actor","label_zh":"说明开始的是哪项任务"},{"id":"at-midnight->began","from":"at-midnight","to":"began","kind":"modifier","relation_type":"time","label_zh":"确定迁移的启动时刻"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The migration began.","sentence_zh":"数据迁移开始了。","add_node_ids":["began","migration"],"add_link_ids":["began->migration"],"focus_node_id":"began","note_zh":"最短表达只说明迁移已经启动。"},{"step_no":2,"label":"时间","sentence_en":"The migration began at midnight.","sentence_zh":"数据迁移在午夜开始了。","add_node_ids":["at-midnight"],"add_link_ids":["at-midnight->began"],"focus_node_id":"at-midnight","note_zh":"准确时刻明确了任务何时启动。"}]}'
  ),
  (
    'behave-primary',
    'behave',
    'behave',
    'behave predictably',
    '表现得稳定且可预测',
    'The API behaves predictably.',
    '这个API的表现稳定，可以预期。',
    'The API behaves predictably under heavy load.',
    '这个API在高负载下仍表现稳定，可以预期。',
    'api-load-test',
    '{"schema_version":2,"root_action_id":"behaves","nodes":[{"id":"behaves","text":"behaves","kind":"action","label_zh":"API呈现运行表现"},{"id":"api","text":"The API","kind":"core","label_zh":"接受观察的API"},{"id":"predictably","text":"predictably","kind":"modifier","label_zh":"API的反应符合预期"},{"id":"under-load","text":"under heavy load","kind":"modifier","label_zh":"观察API表现的高负载条件"}],"links":[{"id":"behaves->api","from":"behaves","to":"api","kind":"core","relation_type":"actor","label_zh":"说明呈现这种表现的是API"},{"id":"predictably->behaves","from":"predictably","to":"behaves","kind":"modifier","relation_type":"manner","label_zh":"说明API的反应可以预期"},{"id":"under-load->behaves","from":"under-load","to":"behaves","kind":"modifier","relation_type":"condition","label_zh":"限定观察运行表现时的负载条件"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The API behaves predictably.","sentence_zh":"这个API的表现稳定，可以预期。","add_node_ids":["behaves","api","predictably"],"add_link_ids":["behaves->api","predictably->behaves"],"focus_node_id":"predictably","note_zh":"主干直接评价API的运行表现。"},{"step_no":2,"label":"条件","sentence_en":"The API behaves predictably under heavy load.","sentence_zh":"这个API在高负载下仍表现稳定，可以预期。","add_node_ids":["under-load"],"add_link_ids":["under-load->behaves"],"focus_node_id":"under-load","note_zh":"高负载使这项表现更具有测试价值。"}]}'
  ),
  (
    'believe-primary',
    'believe',
    'believe',
    'believe a patch works',
    '相信某个技术判断属实',
    'Maya believes the patch closes the race condition.',
    '玛雅相信这个补丁能消除竞态问题。',
    'Maya believes the patch closes the race condition after she reran the suite.',
    '重新运行测试套件后，玛雅相信这个补丁能消除竞态问题。',
    'race-condition-fix',
    '{"schema_version":2,"root_action_id":"believes","nodes":[{"id":"believes","text":"believes","kind":"action","label_zh":"玛雅形成修复有效的判断"},{"id":"maya","text":"Maya","kind":"core","label_zh":"持有该判断的玛雅"},{"id":"closes","text":"closes","kind":"action","label_zh":"补丁消除竞态问题"},{"id":"patch","text":"the patch","kind":"core","label_zh":"被判断有效的补丁"},{"id":"race-condition","text":"the race condition","kind":"core","label_zh":"补丁需要消除的竞态问题"},{"id":"reran","text":"reran","kind":"action","label_zh":"玛雅重新运行测试套件"},{"id":"she","text":"she","kind":"core","label_zh":"重新测试的玛雅"},{"id":"suite","text":"the suite","kind":"core","label_zh":"被重新运行的测试套件"}],"links":[{"id":"believes->maya","from":"believes","to":"maya","kind":"core","relation_type":"actor","label_zh":"说明是谁持有这个判断"},{"id":"believes->closes","from":"believes","to":"closes","kind":"core","relation_type":"content","label_zh":"说明玛雅相信的具体结果"},{"id":"closes->patch","from":"closes","to":"patch","kind":"core","relation_type":"actor","label_zh":"说明由补丁解决问题"},{"id":"closes->race-condition","from":"closes","to":"race-condition","kind":"core","relation_type":"target","label_zh":"说明补丁消除的是哪项问题"},{"id":"reran->she","from":"reran","to":"she","kind":"core","relation_type":"actor","label_zh":"说明重新运行测试的是玛雅"},{"id":"reran->suite","from":"reran","to":"suite","kind":"core","relation_type":"target","label_zh":"说明她重新运行了哪套测试"},{"id":"reran->believes","from":"reran","to":"believes","kind":"modifier","relation_type":"time","label_zh":"重新测试后形成当前判断"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Maya believes the patch closes the race condition.","sentence_zh":"玛雅相信这个补丁能消除竞态问题。","add_node_ids":["believes","maya","closes","patch","race-condition"],"add_link_ids":["believes->maya","believes->closes","closes->patch","closes->race-condition"],"focus_node_id":"believes","note_zh":"相信的内容是一个完整的修复事件。"},{"step_no":2,"label":"判断依据","sentence_en":"Maya believes the patch closes the race condition after she reran the suite.","sentence_zh":"重新运行测试套件后，玛雅相信这个补丁能消除竞态问题。","add_node_ids":["reran","she","suite"],"add_link_ids":["reran->she","reran->suite","reran->believes"],"focus_node_id":"reran","note_zh":"重新测试交代了这个判断形成之前的行动。"}]}'
  ),
  (
    'belong-primary',
    'belong',
    'belong',
    'belong in a layer',
    '应该归入某个位置',
    'This helper belongs in the validation layer.',
    '这个辅助函数应该放在验证层。',
    'This helper belongs in the validation layer because it normalizes request data.',
    '这个辅助函数应该放在验证层，因为它负责统一请求数据的格式。',
    'validation-layer',
    '{"schema_version":2,"root_action_id":"belongs","nodes":[{"id":"belongs","text":"belongs","kind":"action","label_zh":"辅助函数具有合适的代码位置"},{"id":"helper","text":"This helper","kind":"core","label_zh":"需要确定位置的辅助函数"},{"id":"validation-layer","text":"in the validation layer","kind":"core","label_zh":"辅助函数适合归入的验证层"},{"id":"normalizes","text":"normalizes","kind":"action","label_zh":"辅助函数统一数据格式"},{"id":"it","text":"it","kind":"core","label_zh":"执行格式统一的辅助函数"},{"id":"request-data","text":"request data","kind":"core","label_zh":"被统一格式的请求数据"}],"links":[{"id":"belongs->helper","from":"belongs","to":"helper","kind":"core","relation_type":"actor","label_zh":"说明需要归位的是哪个函数"},{"id":"belongs->validation-layer","from":"belongs","to":"validation-layer","kind":"core","relation_type":"place","label_zh":"说明函数适合放在哪一层"},{"id":"normalizes->it","from":"normalizes","to":"it","kind":"core","relation_type":"actor","label_zh":"说明由该辅助函数统一格式"},{"id":"normalizes->request-data","from":"normalizes","to":"request-data","kind":"core","relation_type":"target","label_zh":"说明函数处理的是请求数据"},{"id":"normalizes->belongs","from":"normalizes","to":"belongs","kind":"modifier","relation_type":"reason","label_zh":"处理请求数据解释了它为何属于验证层"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"This helper belongs in the validation layer.","sentence_zh":"这个辅助函数应该放在验证层。","add_node_ids":["belongs","helper","validation-layer"],"add_link_ids":["belongs->helper","belongs->validation-layer"],"focus_node_id":"validation-layer","note_zh":"这里的 belong 表示代码在结构上适合某个位置。"},{"step_no":2,"label":"原因","sentence_en":"This helper belongs in the validation layer because it normalizes request data.","sentence_zh":"这个辅助函数应该放在验证层，因为它负责统一请求数据的格式。","add_node_ids":["normalizes","it","request-data"],"add_link_ids":["normalizes->it","normalizes->request-data","normalizes->belongs"],"focus_node_id":"normalizes","note_zh":"函数承担的数据处理工作支持前面的归类判断。"}]}'
  ),
  (
    'belong-to-primary',
    'belong-to',
    'belong to',
    'belong to a team',
    '归某个团队所有',
    'The signing key belongs to the release team.',
    '这把签名密钥属于发布团队。',
    'The signing key for the mobile app belongs to the release team.',
    '移动应用使用的签名密钥属于发布团队。',
    'signing-key-ownership',
    '{"schema_version":2,"root_action_id":"belongs-to","nodes":[{"id":"belongs-to","text":"belongs to","kind":"action","label_zh":"签名密钥具有明确归属"},{"id":"signing-key","text":"The signing key","kind":"core","label_zh":"需要确认归属的签名密钥"},{"id":"release-team","text":"the release team","kind":"core","label_zh":"拥有签名密钥的发布团队"},{"id":"for-mobile-app","text":"for the mobile app","kind":"modifier","label_zh":"密钥所服务的移动应用"}],"links":[{"id":"belongs-to->signing-key","from":"belongs-to","to":"signing-key","kind":"core","relation_type":"actor","label_zh":"说明被确认归属的是签名密钥"},{"id":"belongs-to->release-team","from":"belongs-to","to":"release-team","kind":"core","relation_type":"ownership","label_zh":"说明密钥归哪个团队所有"},{"id":"for-mobile-app->signing-key","from":"for-mobile-app","to":"signing-key","kind":"modifier","relation_type":"purpose","label_zh":"说明这把密钥用于哪个产品"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The signing key belongs to the release team.","sentence_zh":"这把签名密钥属于发布团队。","add_node_ids":["belongs-to","signing-key","release-team"],"add_link_ids":["belongs-to->signing-key","belongs-to->release-team"],"focus_node_id":"belongs-to","note_zh":"固定搭配 belong to 直接说明所有权。"},{"step_no":2,"label":"对象细节","sentence_en":"The signing key for the mobile app belongs to the release team.","sentence_zh":"移动应用使用的签名密钥属于发布团队。","add_node_ids":["for-mobile-app"],"add_link_ids":["for-mobile-app->signing-key"],"focus_node_id":"for-mobile-app","note_zh":"产品信息附着在密钥上，用来区分具体密钥。"}]}'
  ),
  (
    'benchmark-primary',
    'benchmark',
    'benchmark',
    'benchmark a parser',
    '对解析器进行基准测试',
    'Nora benchmarked the parser.',
    '诺拉对解析器进行了基准测试。',
    'Nora benchmarked the parser against the old implementation.',
    '诺拉以旧实现为比较基线，对解析器进行了基准测试。',
    'parser-performance',
    '{"schema_version":2,"root_action_id":"benchmarked","nodes":[{"id":"benchmarked","text":"benchmarked","kind":"action","label_zh":"诺拉测量解析器性能"},{"id":"nora","text":"Nora","kind":"core","label_zh":"执行基准测试的诺拉"},{"id":"parser","text":"the parser","kind":"core","label_zh":"接受性能测试的解析器"},{"id":"against-old","text":"against the old implementation","kind":"modifier","label_zh":"作为比较基线的旧实现"}],"links":[{"id":"benchmarked->nora","from":"benchmarked","to":"nora","kind":"core","relation_type":"actor","label_zh":"说明是谁执行性能测试"},{"id":"benchmarked->parser","from":"benchmarked","to":"parser","kind":"core","relation_type":"target","label_zh":"说明被测试的是解析器"},{"id":"against-old->benchmarked","from":"against-old","to":"benchmarked","kind":"modifier","relation_type":"scope","label_zh":"说明性能数据与哪个实现比较"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Nora benchmarked the parser.","sentence_zh":"诺拉对解析器进行了基准测试。","add_node_ids":["benchmarked","nora","parser"],"add_link_ids":["benchmarked->nora","benchmarked->parser"],"focus_node_id":"benchmarked","note_zh":"主干确定测试执行者和被测组件。"},{"step_no":2,"label":"比较范围","sentence_en":"Nora benchmarked the parser against the old implementation.","sentence_zh":"诺拉以旧实现为比较基线，对解析器进行了基准测试。","add_node_ids":["against-old"],"add_link_ids":["against-old->benchmarked"],"focus_node_id":"against-old","note_zh":"旧实现使性能结果具有可比较性。"}]}'
  ),
  (
    'bend-primary',
    'bend',
    'bend',
    'bend a bracket',
    '使支架弯曲',
    'The technician bent the bracket.',
    '技术员把支架掰弯了。',
    'The technician bent the bracket to align the sensor.',
    '技术员为了对齐传感器而把支架掰弯了。',
    'sensor-alignment',
    '{"schema_version":2,"root_action_id":"bent","nodes":[{"id":"bent","text":"bent","kind":"action","label_zh":"技术员改变支架形状"},{"id":"technician","text":"The technician","kind":"core","label_zh":"弯曲支架的技术员"},{"id":"bracket","text":"the bracket","kind":"core","label_zh":"被弯曲的金属支架"},{"id":"align","text":"align","kind":"action","label_zh":"技术员使传感器对齐"},{"id":"sensor","text":"the sensor","kind":"core","label_zh":"需要对齐的传感器"}],"links":[{"id":"bent->technician","from":"bent","to":"technician","kind":"core","relation_type":"actor","label_zh":"说明是谁弯曲了支架"},{"id":"bent->bracket","from":"bent","to":"bracket","kind":"core","relation_type":"target","label_zh":"说明发生弯曲的是哪个部件"},{"id":"align->technician","from":"align","to":"technician","kind":"core","relation_type":"shared_actor","label_zh":"技术员也负责对齐传感器"},{"id":"align->sensor","from":"align","to":"sensor","kind":"core","relation_type":"target","label_zh":"说明需要对齐的是传感器"},{"id":"align->bent","from":"align","to":"bent","kind":"modifier","relation_type":"purpose","label_zh":"对齐传感器是弯曲支架的目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The technician bent the bracket.","sentence_zh":"技术员把支架掰弯了。","add_node_ids":["bent","technician","bracket"],"add_link_ids":["bent->technician","bent->bracket"],"focus_node_id":"bent","note_zh":"主干描述技术员改变支架形状。"},{"step_no":2,"label":"目的","sentence_en":"The technician bent the bracket to align the sensor.","sentence_zh":"技术员为了对齐传感器而把支架掰弯了。","add_node_ids":["align","sensor"],"add_link_ids":["align->technician","align->sensor","align->bent"],"focus_node_id":"align","note_zh":"对齐行动说明这次形状调整要达到什么效果。"}]}'
  ),
  (
    'benefit-primary',
    'benefit',
    'benefit',
    'benefit from caching',
    '从缓存查询中受益',
    'The dashboard benefits from cached queries.',
    '这个仪表盘得益于缓存查询。',
    'The dashboard benefits from cached queries because they reduce database load.',
    '这个仪表盘得益于缓存查询，因为它们能降低数据库负载。',
    'dashboard-caching',
    '{"schema_version":2,"root_action_id":"benefits","nodes":[{"id":"benefits","text":"benefits","kind":"action","label_zh":"仪表盘获得性能收益"},{"id":"dashboard","text":"The dashboard","kind":"core","label_zh":"获得性能改善的仪表盘"},{"id":"cached-queries","text":"cached queries","kind":"core","label_zh":"带来性能收益的缓存查询"},{"id":"reduce","text":"reduce","kind":"action","label_zh":"缓存查询降低数据库负载"},{"id":"they","text":"they","kind":"core","label_zh":"发挥减负作用的缓存查询"},{"id":"database-load","text":"database load","kind":"core","label_zh":"被降低的数据库负载"}],"links":[{"id":"benefits->dashboard","from":"benefits","to":"dashboard","kind":"core","relation_type":"actor","label_zh":"说明哪个界面获得了收益"},{"id":"benefits->cached-queries","from":"benefits","to":"cached-queries","kind":"core","relation_type":"target","label_zh":"说明收益来自缓存查询"},{"id":"reduce->they","from":"reduce","to":"they","kind":"core","relation_type":"actor","label_zh":"说明缓存查询发挥了减负作用"},{"id":"reduce->database-load","from":"reduce","to":"database-load","kind":"core","relation_type":"target","label_zh":"说明被降低的是数据库负载"},{"id":"reduce->benefits","from":"reduce","to":"benefits","kind":"modifier","relation_type":"reason","label_zh":"降低数据库负载解释了仪表盘为何受益"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The dashboard benefits from cached queries.","sentence_zh":"这个仪表盘得益于缓存查询。","add_node_ids":["benefits","dashboard","cached-queries"],"add_link_ids":["benefits->dashboard","benefits->cached-queries"],"focus_node_id":"benefits","note_zh":"benefit from 指明性能收益的来源。"},{"step_no":2,"label":"原因","sentence_en":"The dashboard benefits from cached queries because they reduce database load.","sentence_zh":"这个仪表盘得益于缓存查询，因为它们能降低数据库负载。","add_node_ids":["reduce","they","database-load"],"add_link_ids":["reduce->they","reduce->database-load","reduce->benefits"],"focus_node_id":"reduce","note_zh":"减轻数据库压力揭示了收益产生的机制。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'bet-primary',
    'bet',
    'bet',
    'bet a fix will work',
    '确信某件事会发生',
    'I bet the hotfix resolves the timeout.',
    '我敢肯定这个热修复能解决超时问题。',
    'I bet the hotfix resolves the timeout before morning traffic arrives.',
    '我敢肯定这个热修复能在早间流量到来前解决超时问题。',
    'hotfix-confidence',
    '{"schema_version":2,"root_action_id":"bet","nodes":[{"id":"bet","text":"bet","kind":"action","label_zh":"说话者表达高度确信"},{"id":"i","text":"I","kind":"core","label_zh":"对修复结果很有把握的人"},{"id":"resolves","text":"resolves","kind":"action","label_zh":"热修复消除超时问题"},{"id":"hotfix","text":"the hotfix","kind":"core","label_zh":"预计会生效的热修复"},{"id":"timeout","text":"the timeout","kind":"core","label_zh":"热修复需要解决的超时问题"},{"id":"arrives","text":"arrives","kind":"action","label_zh":"早间流量开始到来"},{"id":"morning-traffic","text":"morning traffic","kind":"core","label_zh":"为修复设置期限的早间流量"}],"links":[{"id":"bet->i","from":"bet","to":"i","kind":"core","relation_type":"actor","label_zh":"说明是谁表达确信"},{"id":"bet->resolves","from":"bet","to":"resolves","kind":"core","relation_type":"content","label_zh":"说明说话者确信的具体结果"},{"id":"resolves->hotfix","from":"resolves","to":"hotfix","kind":"core","relation_type":"actor","label_zh":"说明由热修复解决问题"},{"id":"resolves->timeout","from":"resolves","to":"timeout","kind":"core","relation_type":"target","label_zh":"说明需要解决的是超时问题"},{"id":"arrives->morning-traffic","from":"arrives","to":"morning-traffic","kind":"core","relation_type":"actor","label_zh":"说明即将到来的是早间流量"},{"id":"arrives->resolves","from":"arrives","to":"resolves","kind":"modifier","relation_type":"time","label_zh":"热修复预计在流量到来前生效"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I bet the hotfix resolves the timeout.","sentence_zh":"我敢肯定这个热修复能解决超时问题。","add_node_ids":["bet","i","resolves","hotfix","timeout"],"add_link_ids":["bet->i","bet->resolves","resolves->hotfix","resolves->timeout"],"focus_node_id":"bet","note_zh":"这里的 bet 不涉及下注，而是表达强烈确信。"},{"step_no":2,"label":"时间期限","sentence_en":"I bet the hotfix resolves the timeout before morning traffic arrives.","sentence_zh":"我敢肯定这个热修复能在早间流量到来前解决超时问题。","add_node_ids":["arrives","morning-traffic"],"add_link_ids":["arrives->morning-traffic","arrives->resolves"],"focus_node_id":"arrives","note_zh":"流量到来为修复生效设置了明确期限。"}]}'
  ),
  (
    'bid-primary',
    'bid',
    'bid',
    'bid on a contract',
    '参与合同投标',
    'Three vendors bid on the support contract.',
    '三家供应商竞标了这份支持合同。',
    'Three vendors bid on the support contract last week.',
    '上周，三家供应商竞标了这份支持合同。',
    'support-contract',
    '{"schema_version":2,"root_action_id":"bid","nodes":[{"id":"bid","text":"bid","kind":"action","label_zh":"供应商提交竞争性报价"},{"id":"vendors","text":"Three vendors","kind":"core","label_zh":"参与投标的三家供应商"},{"id":"contract","text":"the support contract","kind":"core","label_zh":"供应商争取的支持合同"},{"id":"last-week","text":"last week","kind":"modifier","label_zh":"投标发生的上周"}],"links":[{"id":"bid->vendors","from":"bid","to":"vendors","kind":"core","relation_type":"actor","label_zh":"说明哪些供应商参与了投标"},{"id":"bid->contract","from":"bid","to":"contract","kind":"core","relation_type":"target","label_zh":"说明供应商竞标的是哪份合同"},{"id":"last-week->bid","from":"last-week","to":"bid","kind":"modifier","relation_type":"time","label_zh":"确定提交投标的时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Three vendors bid on the support contract.","sentence_zh":"三家供应商竞标了这份支持合同。","add_node_ids":["bid","vendors","contract"],"add_link_ids":["bid->vendors","bid->contract"],"focus_node_id":"bid","note_zh":"bid on 表示针对具体项目提交竞争性报价。"},{"step_no":2,"label":"时间","sentence_en":"Three vendors bid on the support contract last week.","sentence_zh":"上周，三家供应商竞标了这份支持合同。","add_node_ids":["last-week"],"add_link_ids":["last-week->bid"],"focus_node_id":"last-week","note_zh":"时间信息把投标放入明确的业务周期。"}]}'
  ),
  (
    'bill-primary',
    'bill',
    'bill',
    'bill customers monthly',
    '定期向客户计费',
    'The platform bills customers.',
    '这个平台向客户计费。',
    'The platform bills customers monthly.',
    '这个平台每月向客户计费。',
    'service-billing',
    '{"schema_version":2,"root_action_id":"bills","nodes":[{"id":"bills","text":"bills","kind":"action","label_zh":"平台向客户收取费用"},{"id":"platform","text":"The platform","kind":"core","label_zh":"执行自动计费的平台"},{"id":"customers","text":"customers","kind":"core","label_zh":"收到费用账单的客户"},{"id":"monthly","text":"monthly","kind":"modifier","label_zh":"每月执行一次计费"}],"links":[{"id":"bills->platform","from":"bills","to":"platform","kind":"core","relation_type":"actor","label_zh":"说明由哪个系统执行计费"},{"id":"bills->customers","from":"bills","to":"customers","kind":"core","relation_type":"target","label_zh":"说明费用向哪些客户收取"},{"id":"monthly->bills","from":"monthly","to":"bills","kind":"modifier","relation_type":"frequency","label_zh":"说明平台多久结算一次费用"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The platform bills customers.","sentence_zh":"这个平台向客户计费。","add_node_ids":["bills","platform","customers"],"add_link_ids":["bills->platform","bills->customers"],"focus_node_id":"bills","note_zh":"主干说明计费平台和费用承担方。"},{"step_no":2,"label":"频率","sentence_en":"The platform bills customers monthly.","sentence_zh":"这个平台每月向客户计费。","add_node_ids":["monthly"],"add_link_ids":["monthly->bills"],"focus_node_id":"monthly","note_zh":"结算频率明确了账单生成周期。"}]}'
  ),
  (
    'bind-primary',
    'bind',
    'bind',
    'bind a handler to a route',
    '将处理函数绑定到路由',
    'The framework binds the handler to the route.',
    '框架将处理函数绑定到这条路由。',
    'The framework binds the handler to the route at startup.',
    '框架在应用启动时将处理函数绑定到这条路由。',
    'route-registration',
    '{"schema_version":2,"root_action_id":"binds","nodes":[{"id":"binds","text":"binds","kind":"action","label_zh":"框架建立处理函数与路由的关联"},{"id":"framework","text":"The framework","kind":"core","label_zh":"执行自动绑定的框架"},{"id":"handler","text":"the handler","kind":"core","label_zh":"被注册的处理函数"},{"id":"route","text":"the route","kind":"core","label_zh":"接收处理函数的路由"},{"id":"at-startup","text":"at startup","kind":"modifier","label_zh":"应用启动时执行绑定"}],"links":[{"id":"binds->framework","from":"binds","to":"framework","kind":"core","relation_type":"actor","label_zh":"说明由框架建立绑定关系"},{"id":"binds->handler","from":"binds","to":"handler","kind":"core","relation_type":"target","label_zh":"说明哪个处理函数被绑定"},{"id":"binds->route","from":"binds","to":"route","kind":"core","relation_type":"recipient","label_zh":"说明处理函数被绑定到哪条路由"},{"id":"at-startup->binds","from":"at-startup","to":"binds","kind":"modifier","relation_type":"time","label_zh":"说明绑定发生在应用启动阶段"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The framework binds the handler to the route.","sentence_zh":"框架将处理函数绑定到这条路由。","add_node_ids":["binds","framework","handler","route"],"add_link_ids":["binds->framework","binds->handler","binds->route"],"focus_node_id":"binds","note_zh":"主干完整呈现被绑定的组件和绑定位置。"},{"step_no":2,"label":"时间","sentence_en":"The framework binds the handler to the route at startup.","sentence_zh":"框架在应用启动时将处理函数绑定到这条路由。","add_node_ids":["at-startup"],"add_link_ids":["at-startup->binds"],"focus_node_id":"at-startup","note_zh":"启动阶段说明绑定并非在每次请求时进行。"}]}'
  ),
  (
    'bite-primary',
    'bite',
    'bite',
    'bite us later',
    '因早先的选择而反噬',
    'The shortcut bit us.',
    '这个权宜做法反噬了我们。',
    'The shortcut bit us when a hidden dependency broke.',
    '一个隐藏依赖失效时，这个权宜做法反噬了我们。',
    'release-shortcut',
    '{"schema_version":2,"root_action_id":"bit","nodes":[{"id":"bit","text":"bit","kind":"action","label_zh":"早先的捷径造成负面后果"},{"id":"shortcut","text":"The shortcut","kind":"core","label_zh":"最终引发问题的权宜做法"},{"id":"us","text":"us","kind":"core","label_zh":"承受反噬后果的团队"},{"id":"broke","text":"broke","kind":"action","label_zh":"隐藏依赖突然失效"},{"id":"dependency","text":"a hidden dependency","kind":"core","label_zh":"触发问题的隐藏依赖"}],"links":[{"id":"bit->shortcut","from":"bit","to":"shortcut","kind":"core","relation_type":"actor","label_zh":"说明是哪项捷径带来了后果"},{"id":"bit->us","from":"bit","to":"us","kind":"core","relation_type":"target","label_zh":"说明团队承受了反噬"},{"id":"broke->dependency","from":"broke","to":"dependency","kind":"core","relation_type":"actor","label_zh":"说明失效的是隐藏依赖"},{"id":"broke->bit","from":"broke","to":"bit","kind":"modifier","relation_type":"reason","label_zh":"依赖失效使早先的捷径产生反噬"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The shortcut bit us.","sentence_zh":"这个权宜做法反噬了我们。","add_node_ids":["bit","shortcut","us"],"add_link_ids":["bit->shortcut","bit->us"],"focus_node_id":"bit","note_zh":"bite 在这里表示早先决定造成后患。"},{"step_no":2,"label":"触发原因","sentence_en":"The shortcut bit us when a hidden dependency broke.","sentence_zh":"一个隐藏依赖失效时，这个权宜做法反噬了我们。","add_node_ids":["broke","dependency"],"add_link_ids":["broke->dependency","broke->bit"],"focus_node_id":"broke","note_zh":"隐藏依赖失效触发了此前被掩盖的问题。"}]}'
  ),
  (
    'blame-primary',
    'blame',
    'blame',
    'blame an outage on something',
    '把故障归咎于某个原因',
    'The team blamed the outage on a stale certificate.',
    '团队把这次故障归咎于一张过期证书。',
    'The team blamed the outage on a stale certificate during the review.',
    '团队在复盘期间把这次故障归咎于一张过期证书。',
    'outage-review',
    '{"schema_version":2,"root_action_id":"blamed","nodes":[{"id":"blamed","text":"blamed","kind":"action","label_zh":"团队判断故障责任来源"},{"id":"team","text":"The team","kind":"core","label_zh":"作出初步归因的团队"},{"id":"outage","text":"the outage","kind":"core","label_zh":"需要解释原因的服务故障"},{"id":"certificate","text":"a stale certificate","kind":"core","label_zh":"被认为导致故障的过期证书"},{"id":"during-review","text":"during the review","kind":"modifier","label_zh":"团队作出归因的复盘阶段"}],"links":[{"id":"blamed->team","from":"blamed","to":"team","kind":"core","relation_type":"actor","label_zh":"说明是谁作出了归因"},{"id":"blamed->outage","from":"blamed","to":"outage","kind":"core","relation_type":"target","label_zh":"说明团队在解释哪次故障"},{"id":"blamed->certificate","from":"blamed","to":"certificate","kind":"core","relation_type":"reason","label_zh":"说明故障被归咎于什么"},{"id":"during-review->blamed","from":"during-review","to":"blamed","kind":"modifier","relation_type":"time","label_zh":"说明归因发生在复盘期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team blamed the outage on a stale certificate.","sentence_zh":"团队把这次故障归咎于一张过期证书。","add_node_ids":["blamed","team","outage","certificate"],"add_link_ids":["blamed->team","blamed->outage","blamed->certificate"],"focus_node_id":"blamed","note_zh":"blame ... on ... 表示把问题归因于某个来源。"},{"step_no":2,"label":"场景","sentence_en":"The team blamed the outage on a stale certificate during the review.","sentence_zh":"团队在复盘期间把这次故障归咎于一张过期证书。","add_node_ids":["during-review"],"add_link_ids":["during-review->blamed"],"focus_node_id":"during-review","note_zh":"复盘阶段交代了判断出现的工作场景。"}]}'
  ),
  (
    'blend-primary',
    'blend',
    'blend',
    'blend metrics with feedback',
    '把不同类型的信息融合起来',
    'The designer blended live metrics with user feedback.',
    '设计师把实时指标与用户反馈融合在一起。',
    'The designer blended live metrics with user feedback to explain the adoption drop.',
    '设计师把实时指标与用户反馈融合起来，以解释采用率下降。',
    'launch-report',
    '{"schema_version":2,"root_action_id":"blended","nodes":[{"id":"blended","text":"blended","kind":"action","label_zh":"设计师融合两类信息"},{"id":"designer","text":"The designer","kind":"core","label_zh":"整合报告内容的设计师"},{"id":"metrics","text":"live metrics","kind":"core","label_zh":"被纳入分析的实时指标"},{"id":"feedback","text":"user feedback","kind":"core","label_zh":"与指标结合的用户反馈"},{"id":"explain","text":"explain","kind":"action","label_zh":"设计师解释采用率下降"},{"id":"adoption-drop","text":"the adoption drop","kind":"core","label_zh":"需要解释的采用率下降"}],"links":[{"id":"blended->designer","from":"blended","to":"designer","kind":"core","relation_type":"actor","label_zh":"说明是谁整合了信息"},{"id":"blended->metrics","from":"blended","to":"metrics","kind":"core","relation_type":"target","label_zh":"说明被纳入融合的是实时指标"},{"id":"blended->feedback","from":"blended","to":"feedback","kind":"core","relation_type":"category","label_zh":"说明指标与哪类信息结合"},{"id":"explain->designer","from":"explain","to":"designer","kind":"core","relation_type":"shared_actor","label_zh":"设计师也负责形成解释"},{"id":"explain->adoption-drop","from":"explain","to":"adoption-drop","kind":"core","relation_type":"target","label_zh":"说明需要解释的是采用率下降"},{"id":"explain->blended","from":"explain","to":"blended","kind":"modifier","relation_type":"purpose","label_zh":"解释采用率变化是融合信息的目的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The designer blended live metrics with user feedback.","sentence_zh":"设计师把实时指标与用户反馈融合在一起。","add_node_ids":["blended","designer","metrics","feedback"],"add_link_ids":["blended->designer","blended->metrics","blended->feedback"],"focus_node_id":"blended","note_zh":"主干强调两类不同信息被结合使用。"},{"step_no":2,"label":"目的","sentence_en":"The designer blended live metrics with user feedback to explain the adoption drop.","sentence_zh":"设计师把实时指标与用户反馈融合起来，以解释采用率下降。","add_node_ids":["explain","adoption-drop"],"add_link_ids":["explain->designer","explain->adoption-drop","explain->blended"],"focus_node_id":"explain","note_zh":"解释采用率下降为信息融合提供了明确目标。"}]}'
  ),
  (
    'bless-primary',
    'bless',
    'bless',
    'bless an exception',
    '批准例外安排',
    'The security lead blessed the exception.',
    '安全负责人批准了这项例外安排。',
    'The security lead blessed the exception after legal completed its review.',
    '法务完成审查后，安全负责人批准了这项例外安排。',
    'security-exception',
    '{"schema_version":2,"root_action_id":"blessed","nodes":[{"id":"blessed","text":"blessed","kind":"action","label_zh":"安全负责人批准例外安排"},{"id":"security-lead","text":"The security lead","kind":"core","label_zh":"有权批准例外的安全负责人"},{"id":"exception","text":"the exception","kind":"core","label_zh":"获得批准的临时例外"},{"id":"completed","text":"completed","kind":"action","label_zh":"法务完成审查流程"},{"id":"legal","text":"legal","kind":"core","label_zh":"完成审查的法务团队"},{"id":"review","text":"its review","kind":"core","label_zh":"法务针对该例外开展的审查"}],"links":[{"id":"blessed->security-lead","from":"blessed","to":"security-lead","kind":"core","relation_type":"actor","label_zh":"说明是谁认可了例外安排"},{"id":"blessed->exception","from":"blessed","to":"exception","kind":"core","relation_type":"target","label_zh":"说明获得批准的是哪项例外"},{"id":"completed->legal","from":"completed","to":"legal","kind":"core","relation_type":"actor","label_zh":"说明由法务完成审查"},{"id":"completed->review","from":"completed","to":"review","kind":"core","relation_type":"target","label_zh":"说明法务完成了哪项流程"},{"id":"completed->blessed","from":"completed","to":"blessed","kind":"modifier","relation_type":"time","label_zh":"法务审查完成后才给予批准"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The security lead blessed the exception.","sentence_zh":"安全负责人批准了这项例外安排。","add_node_ids":["blessed","security-lead","exception"],"add_link_ids":["blessed->security-lead","blessed->exception"],"focus_node_id":"blessed","note_zh":"工作场景中的 bless 可表示认可并放行。"},{"step_no":2,"label":"前置审查","sentence_en":"The security lead blessed the exception after legal completed its review.","sentence_zh":"法务完成审查后，安全负责人批准了这项例外安排。","add_node_ids":["completed","legal","review"],"add_link_ids":["completed->legal","completed->review","completed->blessed"],"focus_node_id":"completed","note_zh":"法务完成审查是批准之前发生的独立行动。"}]}'
  ),
  (
    'blink-primary',
    'blink',
    'blink',
    'blink at intervals',
    '灯光有规律地闪烁',
    'The status light blinked.',
    '状态灯闪烁着。',
    'The status light blinked every two seconds.',
    '状态灯每两秒闪烁一次。',
    'firmware-status-light',
    '{"schema_version":2,"root_action_id":"blinked","nodes":[{"id":"blinked","text":"blinked","kind":"action","label_zh":"状态灯反复闪烁"},{"id":"status-light","text":"The status light","kind":"core","label_zh":"发出闪烁信号的状态灯"},{"id":"every-two-seconds","text":"every two seconds","kind":"modifier","label_zh":"状态灯的固定闪烁间隔"}],"links":[{"id":"blinked->status-light","from":"blinked","to":"status-light","kind":"core","relation_type":"actor","label_zh":"说明闪烁的是状态灯"},{"id":"every-two-seconds->blinked","from":"every-two-seconds","to":"blinked","kind":"modifier","relation_type":"frequency","label_zh":"说明状态灯多久闪一次"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The status light blinked.","sentence_zh":"状态灯闪烁着。","add_node_ids":["blinked","status-light"],"add_link_ids":["blinked->status-light"],"focus_node_id":"blinked","note_zh":"主干只呈现状态灯的闪烁动作。"},{"step_no":2,"label":"频率","sentence_en":"The status light blinked every two seconds.","sentence_zh":"状态灯每两秒闪烁一次。","add_node_ids":["every-two-seconds"],"add_link_ids":["every-two-seconds->blinked"],"focus_node_id":"every-two-seconds","note_zh":"固定间隔把闪烁描述为规律信号。"}]}'
  ),
  (
    'block-primary',
    'block',
    'block',
    'block a deployment',
    '阻止部署继续进行',
    'A missing index blocked the deployment.',
    '一个缺失的索引阻止了部署。',
    'A missing index blocked the deployment until Ravi rebuilt the table.',
    '一个缺失的索引使部署一直无法继续，直到拉维重新构建了数据表。',
    'missing-index',
    '{"schema_version":2,"root_action_id":"blocked","nodes":[{"id":"blocked","text":"blocked","kind":"action","label_zh":"缺失索引使部署无法继续"},{"id":"missing-index","text":"A missing index","kind":"core","label_zh":"造成阻塞的缺失索引"},{"id":"deployment","text":"the deployment","kind":"core","label_zh":"被迫暂停的部署"},{"id":"rebuilt","text":"rebuilt","kind":"action","label_zh":"拉维重新构建数据表"},{"id":"ravi","text":"Ravi","kind":"core","label_zh":"执行重建的工程师"},{"id":"table","text":"the table","kind":"core","label_zh":"被重新构建的数据表"}],"links":[{"id":"blocked->missing-index","from":"blocked","to":"missing-index","kind":"core","relation_type":"actor","label_zh":"说明缺失索引造成了阻塞"},{"id":"blocked->deployment","from":"blocked","to":"deployment","kind":"core","relation_type":"target","label_zh":"说明被阻止的是部署流程"},{"id":"rebuilt->ravi","from":"rebuilt","to":"ravi","kind":"core","relation_type":"actor","label_zh":"说明由拉维执行重建"},{"id":"rebuilt->table","from":"rebuilt","to":"table","kind":"core","relation_type":"target","label_zh":"说明拉维重新构建了哪张表"},{"id":"rebuilt->blocked","from":"rebuilt","to":"blocked","kind":"modifier","relation_type":"time","label_zh":"表重建完成时部署阻塞才结束"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A missing index blocked the deployment.","sentence_zh":"一个缺失的索引阻止了部署。","add_node_ids":["blocked","missing-index","deployment"],"add_link_ids":["blocked->missing-index","blocked->deployment"],"focus_node_id":"blocked","note_zh":"主干直接指出阻塞来源和受影响流程。"},{"step_no":2,"label":"结束条件","sentence_en":"A missing index blocked the deployment until Ravi rebuilt the table.","sentence_zh":"一个缺失的索引使部署一直无法继续，直到拉维重新构建了数据表。","add_node_ids":["rebuilt","ravi","table"],"add_link_ids":["rebuilt->ravi","rebuilt->table","rebuilt->blocked"],"focus_node_id":"rebuilt","note_zh":"重建数据表是结束部署阻塞的关键行动。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
