-- Generated verb paths batch batch-007.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'call-in-primary',
    'call-in',
    'call in',
    'call in a specialist',
    '叫来专业人员',
    'Maya called in a database specialist.',
    'Maya叫来了一名数据库专家。',
    'Maya called in a database specialist after the replication alert.',
    '复制告警出现后，Maya叫来了一名数据库专家。',
    'database-incident',
    '{"schema_version":2,"root_action_id":"called-in","nodes":[{"id":"called-in","text":"called in","kind":"action","label_zh":"叫来技术支援"},{"id":"maya","text":"Maya","kind":"core","label_zh":"请求支援的人"},{"id":"database-specialist","text":"a database specialist","kind":"core","label_zh":"被叫来的专家"},{"id":"after-replication-alert","text":"after the replication alert","kind":"modifier","label_zh":"请求支援的时间背景"}],"links":[{"id":"called-in->maya","from":"called-in","to":"maya","kind":"core","relation_type":"actor","label_zh":"Maya发起了支援请求"},{"id":"called-in->database-specialist","from":"called-in","to":"database-specialist","kind":"core","relation_type":"target","label_zh":"叫来的是数据库专家"},{"id":"after-replication-alert->called-in","from":"after-replication-alert","to":"called-in","kind":"modifier","relation_type":"time","label_zh":"复制告警出现后才请求专家支援"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Maya called in a database specialist.","sentence_zh":"Maya叫来了一名数据库专家。","add_node_ids":["called-in","maya","database-specialist"],"add_link_ids":["called-in->maya","called-in->database-specialist"],"focus_node_id":"called-in","note_zh":"先交代谁请求了哪类专业支援。"},{"step_no":2,"label":"时间","sentence_en":"Maya called in a database specialist after the replication alert.","sentence_zh":"复制告警出现后，Maya叫来了一名数据库专家。","add_node_ids":["after-replication-alert"],"add_link_ids":["after-replication-alert->called-in"],"focus_node_id":"after-replication-alert","note_zh":"补充请求专家支援的时间背景。"}]}'
  ),
  (
    'call-off-primary',
    'call-off',
    'call off',
    'call off a migration',
    '取消原定安排',
    'The team called off the migration.',
    '团队取消了迁移。',
    'The team called off the migration because of failed health checks.',
    '由于健康检查未通过，团队取消了迁移。',
    'migration-decision',
    '{"schema_version":2,"root_action_id":"called-off","nodes":[{"id":"called-off","text":"called off","kind":"action","label_zh":"取消迁移"},{"id":"team","text":"The team","kind":"core","label_zh":"作出取消决定的团队"},{"id":"migration","text":"the migration","kind":"core","label_zh":"被取消的迁移"},{"id":"because-health-checks-failed","text":"because of failed health checks","kind":"modifier","label_zh":"取消迁移的技术原因"}],"links":[{"id":"called-off->team","from":"called-off","to":"team","kind":"core","relation_type":"actor","label_zh":"团队决定取消迁移"},{"id":"called-off->migration","from":"called-off","to":"migration","kind":"core","relation_type":"target","label_zh":"取消的是迁移计划"},{"id":"because-health-checks-failed->called-off","from":"because-health-checks-failed","to":"called-off","kind":"modifier","relation_type":"reason","label_zh":"健康检查未通过导致迁移取消"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team called off the migration.","sentence_zh":"团队取消了迁移。","add_node_ids":["called-off","team","migration"],"add_link_ids":["called-off->team","called-off->migration"],"focus_node_id":"called-off","note_zh":"主干直接呈现取消决定及其对象。"},{"step_no":2,"label":"原因","sentence_en":"The team called off the migration because of failed health checks.","sentence_zh":"由于健康检查未通过，团队取消了迁移。","add_node_ids":["because-health-checks-failed"],"add_link_ids":["because-health-checks-failed->called-off"],"focus_node_id":"because-health-checks-failed","note_zh":"说明团队取消迁移的技术原因。"}]}'
  ),
  (
    'call-on-primary',
    'call-on',
    'call on',
    'call on a service',
    '调用某项服务',
    'The workflow calls on a validation service.',
    '该工作流调用一项验证服务。',
    'The workflow calls on a validation service for high-risk payments.',
    '该工作流为高风险支付调用一项验证服务。',
    'payment-validation',
    '{"schema_version":2,"root_action_id":"calls-on","nodes":[{"id":"calls-on","text":"calls on","kind":"action","label_zh":"调用验证能力"},{"id":"workflow","text":"The workflow","kind":"core","label_zh":"发起调用的工作流"},{"id":"validation-service","text":"a validation service","kind":"core","label_zh":"被调用的验证服务"},{"id":"for-high-risk-payments","text":"for high-risk payments","kind":"modifier","label_zh":"需要验证的支付范围"}],"links":[{"id":"calls-on->workflow","from":"calls-on","to":"workflow","kind":"core","relation_type":"actor","label_zh":"工作流发起服务调用"},{"id":"calls-on->validation-service","from":"calls-on","to":"validation-service","kind":"core","relation_type":"target","label_zh":"工作流调用验证服务"},{"id":"for-high-risk-payments->calls-on","from":"for-high-risk-payments","to":"calls-on","kind":"modifier","relation_type":"scope","label_zh":"这项调用用于检查高风险支付"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The workflow calls on a validation service.","sentence_zh":"该工作流调用一项验证服务。","add_node_ids":["calls-on","workflow","validation-service"],"add_link_ids":["calls-on->workflow","calls-on->validation-service"],"focus_node_id":"calls-on","note_zh":"先建立工作流与验证服务之间的调用关系。"},{"step_no":2,"label":"范围","sentence_en":"The workflow calls on a validation service for high-risk payments.","sentence_zh":"该工作流为高风险支付调用一项验证服务。","add_node_ids":["for-high-risk-payments"],"add_link_ids":["for-high-risk-payments->calls-on"],"focus_node_id":"for-high-risk-payments","note_zh":"明确这项调用服务于哪类支付。"}]}'
  ),
  (
    'call-up-primary',
    'call-up',
    'call up',
    'call up an archived ticket',
    '调出存档信息',
    'Nina called up the archived ticket.',
    'Nina调出了那张存档工单。',
    'Nina called up the archived ticket on her second monitor.',
    'Nina在她的第二台显示器上调出了那张存档工单。',
    'support-investigation',
    '{"schema_version":2,"root_action_id":"called-up","nodes":[{"id":"called-up","text":"called up","kind":"action","label_zh":"调出历史记录"},{"id":"nina","text":"Nina","kind":"core","label_zh":"查找工单的人"},{"id":"archived-ticket","text":"the archived ticket","kind":"core","label_zh":"被调出的存档工单"},{"id":"on-second-monitor","text":"on her second monitor","kind":"modifier","label_zh":"显示工单的屏幕"}],"links":[{"id":"called-up->nina","from":"called-up","to":"nina","kind":"core","relation_type":"actor","label_zh":"Nina执行了调取操作"},{"id":"called-up->archived-ticket","from":"called-up","to":"archived-ticket","kind":"core","relation_type":"target","label_zh":"调出的是存档工单"},{"id":"on-second-monitor->called-up","from":"on-second-monitor","to":"called-up","kind":"modifier","relation_type":"place","label_zh":"工单被调出并显示在第二台显示器上"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Nina called up the archived ticket.","sentence_zh":"Nina调出了那张存档工单。","add_node_ids":["called-up","nina","archived-ticket"],"add_link_ids":["called-up->nina","called-up->archived-ticket"],"focus_node_id":"archived-ticket","note_zh":"说明Nina调出了哪项历史记录。"},{"step_no":2,"label":"场景","sentence_en":"Nina called up the archived ticket on her second monitor.","sentence_zh":"Nina在她的第二台显示器上调出了那张存档工单。","add_node_ids":["on-second-monitor"],"add_link_ids":["on-second-monitor->called-up"],"focus_node_id":"on-second-monitor","note_zh":"增加工单出现的具体屏幕位置。"}]}'
  ),
  (
    'calm-primary',
    'calm',
    'calm',
    'calm a worried client',
    '使焦虑的人平静下来',
    'The incident lead calmed the client.',
    '事故负责人安抚了客户。',
    'The incident lead calmed the client with a clear recovery plan.',
    '事故负责人用一份清晰的恢复计划安抚了客户。',
    'incident-communication',
    '{"schema_version":2,"root_action_id":"calmed","nodes":[{"id":"calmed","text":"calmed","kind":"action","label_zh":"安抚客户"},{"id":"incident-lead","text":"The incident lead","kind":"core","label_zh":"负责安抚的人"},{"id":"client","text":"the client","kind":"core","label_zh":"情绪得到安抚的客户"},{"id":"with-clear-recovery-plan","text":"with a clear recovery plan","kind":"modifier","label_zh":"让客户安心的具体方式"}],"links":[{"id":"calmed->incident-lead","from":"calmed","to":"incident-lead","kind":"core","relation_type":"actor","label_zh":"事故负责人进行安抚"},{"id":"calmed->client","from":"calmed","to":"client","kind":"core","relation_type":"target","label_zh":"客户的情绪得到安抚"},{"id":"with-clear-recovery-plan->calmed","from":"with-clear-recovery-plan","to":"calmed","kind":"modifier","relation_type":"manner","label_zh":"负责人通过清晰的恢复计划安抚客户"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The incident lead calmed the client.","sentence_zh":"事故负责人安抚了客户。","add_node_ids":["calmed","incident-lead","client"],"add_link_ids":["calmed->incident-lead","calmed->client"],"focus_node_id":"calmed","note_zh":"突出负责人使客户恢复平静这一变化。"},{"step_no":2,"label":"方式","sentence_en":"The incident lead calmed the client with a clear recovery plan.","sentence_zh":"事故负责人用一份清晰的恢复计划安抚了客户。","add_node_ids":["with-clear-recovery-plan"],"add_link_ids":["with-clear-recovery-plan->calmed"],"focus_node_id":"with-clear-recovery-plan","note_zh":"交代安抚客户所依靠的信息。"}]}'
  ),
  (
    'calm-down-primary',
    'calm-down',
    'calm down',
    'calm down after rerouting',
    '逐渐平息',
    'The alert storm calmed down.',
    '告警潮平息了。',
    'The alert storm calmed down within ten minutes after the traffic rerouting.',
    '流量重新路由后，告警潮在十分钟内平息了。',
    'alert-recovery',
    '{"schema_version":2,"root_action_id":"calmed-down","nodes":[{"id":"calmed-down","text":"calmed down","kind":"action","label_zh":"告警逐渐平息"},{"id":"alert-storm","text":"The alert storm","kind":"core","label_zh":"恢复平稳的告警潮"},{"id":"within-ten-minutes","text":"within ten minutes","kind":"modifier","label_zh":"告警平息所用时间"},{"id":"after-traffic-rerouting","text":"after the traffic rerouting","kind":"modifier","label_zh":"告警回落前的流量调整"}],"links":[{"id":"calmed-down->alert-storm","from":"calmed-down","to":"alert-storm","kind":"core","relation_type":"actor","label_zh":"告警潮自身逐渐减弱"},{"id":"within-ten-minutes->calmed-down","from":"within-ten-minutes","to":"calmed-down","kind":"modifier","relation_type":"time","label_zh":"平息过程在十分钟内完成"},{"id":"after-traffic-rerouting->calmed-down","from":"after-traffic-rerouting","to":"calmed-down","kind":"modifier","relation_type":"time","label_zh":"流量重新路由后告警开始回落"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The alert storm calmed down.","sentence_zh":"告警潮平息了。","add_node_ids":["calmed-down","alert-storm"],"add_link_ids":["calmed-down->alert-storm"],"focus_node_id":"calmed-down","note_zh":"主干描述告警从密集转为平稳。"},{"step_no":2,"label":"时间","sentence_en":"The alert storm calmed down within ten minutes.","sentence_zh":"告警潮在十分钟内平息了。","add_node_ids":["within-ten-minutes"],"add_link_ids":["within-ten-minutes->calmed-down"],"focus_node_id":"within-ten-minutes","note_zh":"补充恢复平稳所需的时长。"},{"step_no":3,"label":"时间","sentence_en":"The alert storm calmed down within ten minutes after the traffic rerouting.","sentence_zh":"流量重新路由后，告警潮在十分钟内平息了。","add_node_ids":["after-traffic-rerouting"],"add_link_ids":["after-traffic-rerouting->calmed-down"],"focus_node_id":"after-traffic-rerouting","note_zh":"指出告警回落前完成的关键调整。"}]}'
  ),
  (
    'can-primary',
    'can',
    'can',
    'can restore a backup',
    '有能力完成某事',
    'The admin can restore the backup.',
    '管理员能够恢复该备份。',
    'The admin can restore the backup from cold storage.',
    '管理员能够从冷存储中恢复该备份。',
    'backup-recovery',
    '{"schema_version":2,"root_action_id":"can","nodes":[{"id":"can","text":"can","kind":"action","label_zh":"具备恢复能力"},{"id":"admin","text":"The admin","kind":"core","label_zh":"拥有操作能力的管理员"},{"id":"restore","text":"restore","kind":"action","label_zh":"执行备份恢复"},{"id":"backup","text":"the backup","kind":"core","label_zh":"需要恢复的备份"},{"id":"from-cold-storage","text":"from cold storage","kind":"modifier","label_zh":"备份恢复的数据来源"}],"links":[{"id":"can->admin","from":"can","to":"admin","kind":"core","relation_type":"actor","label_zh":"管理员具备这项恢复能力"},{"id":"can->restore","from":"can","to":"restore","kind":"core","relation_type":"content","label_zh":"能力的具体内容是恢复备份"},{"id":"restore->admin","from":"restore","to":"admin","kind":"core","relation_type":"shared_actor","label_zh":"恢复操作同样由管理员执行"},{"id":"restore->backup","from":"restore","to":"backup","kind":"core","relation_type":"target","label_zh":"恢复操作作用于该备份"},{"id":"from-cold-storage->restore","from":"from-cold-storage","to":"restore","kind":"modifier","relation_type":"place","label_zh":"恢复所需的数据来自冷存储"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The admin can restore the backup.","sentence_zh":"管理员能够恢复该备份。","add_node_ids":["can","admin","restore","backup"],"add_link_ids":["can->admin","can->restore","restore->admin","restore->backup"],"focus_node_id":"can","note_zh":"can承载能力判断，具体内容是恢复备份。"},{"step_no":2,"label":"场景","sentence_en":"The admin can restore the backup from cold storage.","sentence_zh":"管理员能够从冷存储中恢复该备份。","add_node_ids":["from-cold-storage"],"add_link_ids":["from-cold-storage->restore"],"focus_node_id":"from-cold-storage","note_zh":"说明恢复数据取自哪里。"}]}'
  ),
  (
    'cancel-primary',
    'cancel',
    'cancel',
    'cancel a product demo',
    '取消已经安排的活动',
    'Priya canceled the demo.',
    'Priya取消了演示。',
    'Priya canceled the demo for the sales team after the staging crash.',
    '预发布环境崩溃后，Priya取消了原定面向销售团队的演示。',
    'demo-scheduling',
    '{"schema_version":2,"root_action_id":"canceled","nodes":[{"id":"canceled","text":"canceled","kind":"action","label_zh":"取消演示"},{"id":"priya","text":"Priya","kind":"core","label_zh":"决定取消的人"},{"id":"demo","text":"the demo","kind":"core","label_zh":"被取消的产品演示"},{"id":"for-sales-team","text":"for the sales team","kind":"modifier","label_zh":"演示原本面向的团队"},{"id":"after-staging-crash","text":"after the staging crash","kind":"modifier","label_zh":"决定取消前发生的故障"}],"links":[{"id":"canceled->priya","from":"canceled","to":"priya","kind":"core","relation_type":"actor","label_zh":"Priya作出取消决定"},{"id":"canceled->demo","from":"canceled","to":"demo","kind":"core","relation_type":"target","label_zh":"产品演示被取消"},{"id":"for-sales-team->demo","from":"for-sales-team","to":"demo","kind":"modifier","relation_type":"purpose","label_zh":"这场演示原本供销售团队参加"},{"id":"after-staging-crash->canceled","from":"after-staging-crash","to":"canceled","kind":"modifier","relation_type":"time","label_zh":"预发布环境崩溃后才取消演示"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Priya canceled the demo.","sentence_zh":"Priya取消了演示。","add_node_ids":["canceled","priya","demo"],"add_link_ids":["canceled->priya","canceled->demo"],"focus_node_id":"canceled","note_zh":"直接表达取消活动这一决定。"},{"step_no":2,"label":"对象细节","sentence_en":"Priya canceled the demo for the sales team.","sentence_zh":"Priya取消了原定面向销售团队的演示。","add_node_ids":["for-sales-team"],"add_link_ids":["for-sales-team->demo"],"focus_node_id":"for-sales-team","note_zh":"说明被取消的演示原本服务于谁。"},{"step_no":3,"label":"时间","sentence_en":"Priya canceled the demo for the sales team after the staging crash.","sentence_zh":"预发布环境崩溃后，Priya取消了原定面向销售团队的演示。","add_node_ids":["after-staging-crash"],"add_link_ids":["after-staging-crash->canceled"],"focus_node_id":"after-staging-crash","note_zh":"加入取消决定之前出现的技术故障。"}]}'
  ),
  (
    'capitalize-primary',
    'capitalize',
    'capitalize',
    'capitalize on demand',
    '利用有利形势',
    'The startup capitalized on the sudden demand.',
    '这家创业公司利用了突然增长的需求。',
    'The startup capitalized on the sudden demand with a self-service plan before its larger rivals.',
    '这家创业公司抢在规模更大的竞争者之前，通过一套自助方案利用了突然增长的需求。',
    'startup-growth',
    '{"schema_version":2,"root_action_id":"capitalized-on","nodes":[{"id":"capitalized-on","text":"capitalized on","kind":"action","label_zh":"抓住需求机会"},{"id":"startup","text":"The startup","kind":"core","label_zh":"利用机会的创业公司"},{"id":"sudden-demand","text":"the sudden demand","kind":"core","label_zh":"被利用的市场需求"},{"id":"with-self-service-plan","text":"with a self-service plan","kind":"modifier","label_zh":"承接需求的产品方案"},{"id":"before-rivals","text":"before its larger rivals","kind":"modifier","label_zh":"公司抢占机会的时间优势"}],"links":[{"id":"capitalized-on->startup","from":"capitalized-on","to":"startup","kind":"core","relation_type":"actor","label_zh":"创业公司抓住了机会"},{"id":"capitalized-on->sudden-demand","from":"capitalized-on","to":"sudden-demand","kind":"core","relation_type":"target","label_zh":"公司利用了突然增长的需求"},{"id":"with-self-service-plan->capitalized-on","from":"with-self-service-plan","to":"capitalized-on","kind":"modifier","relation_type":"manner","label_zh":"公司通过自助方案承接需求"},{"id":"before-rivals->capitalized-on","from":"before-rivals","to":"capitalized-on","kind":"modifier","relation_type":"sequence","label_zh":"公司比规模更大的竞争者更早抓住机会"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The startup capitalized on the sudden demand.","sentence_zh":"这家创业公司利用了突然增长的需求。","add_node_ids":["capitalized-on","startup","sudden-demand"],"add_link_ids":["capitalized-on->startup","capitalized-on->sudden-demand"],"focus_node_id":"capitalized-on","note_zh":"capitalize与on连用，表示利用有利形势。"},{"step_no":2,"label":"方式","sentence_en":"The startup capitalized on the sudden demand with a self-service plan.","sentence_zh":"这家创业公司通过一套自助方案利用了突然增长的需求。","add_node_ids":["with-self-service-plan"],"add_link_ids":["with-self-service-plan->capitalized-on"],"focus_node_id":"with-self-service-plan","note_zh":"补充公司承接新增需求的具体方案。"},{"step_no":3,"label":"顺序","sentence_en":"The startup capitalized on the sudden demand with a self-service plan before its larger rivals.","sentence_zh":"这家创业公司抢在规模更大的竞争者之前，通过一套自助方案利用了突然增长的需求。","add_node_ids":["before-rivals"],"add_link_ids":["before-rivals->capitalized-on"],"focus_node_id":"before-rivals","note_zh":"突出公司迅速利用机会的时间优势。"}]}'
  ),
  (
    'capture-primary',
    'capture',
    'capture',
    'capture a memory spike',
    '记录并捕捉异常现象',
    'The profiler captured the memory spike.',
    '性能分析器捕捉到了内存峰值。',
    'The profiler captured the memory spike during the load test with full stack data.',
    '性能分析器在负载测试期间捕捉到了内存峰值，并记录了完整的调用栈数据。',
    'performance-profiling',
    '{"schema_version":2,"root_action_id":"captured","nodes":[{"id":"captured","text":"captured","kind":"action","label_zh":"记录异常峰值"},{"id":"profiler","text":"The profiler","kind":"core","label_zh":"执行记录的分析工具"},{"id":"memory-spike","text":"the memory spike","kind":"core","label_zh":"被捕捉的内存峰值"},{"id":"during-load-test","text":"during the load test","kind":"modifier","label_zh":"峰值被记录的测试阶段"},{"id":"with-full-stack-data","text":"with full stack data","kind":"modifier","label_zh":"记录中包含的调用栈信息"}],"links":[{"id":"captured->profiler","from":"captured","to":"profiler","kind":"core","relation_type":"actor","label_zh":"性能分析器完成了捕捉"},{"id":"captured->memory-spike","from":"captured","to":"memory-spike","kind":"core","relation_type":"target","label_zh":"捕捉对象是内存峰值"},{"id":"during-load-test->captured","from":"during-load-test","to":"captured","kind":"modifier","relation_type":"time","label_zh":"捕捉发生在负载测试期间"},{"id":"with-full-stack-data->captured","from":"with-full-stack-data","to":"captured","kind":"modifier","relation_type":"content","label_zh":"捕捉结果保留了完整调用栈数据"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The profiler captured the memory spike.","sentence_zh":"性能分析器捕捉到了内存峰值。","add_node_ids":["captured","profiler","memory-spike"],"add_link_ids":["captured->profiler","captured->memory-spike"],"focus_node_id":"memory-spike","note_zh":"主干指出工具成功记录了哪项异常。"},{"step_no":2,"label":"时间","sentence_en":"The profiler captured the memory spike during the load test.","sentence_zh":"性能分析器在负载测试期间捕捉到了内存峰值。","add_node_ids":["during-load-test"],"add_link_ids":["during-load-test->captured"],"focus_node_id":"during-load-test","note_zh":"定位异常被捕捉时所处的测试阶段。"},{"step_no":3,"label":"内容","sentence_en":"The profiler captured the memory spike during the load test with full stack data.","sentence_zh":"性能分析器在负载测试期间捕捉到了内存峰值，并记录了完整的调用栈数据。","add_node_ids":["with-full-stack-data"],"add_link_ids":["with-full-stack-data->captured"],"focus_node_id":"with-full-stack-data","note_zh":"说明捕捉结果还保留了哪些诊断信息。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'care-primary',
    'care',
    'care',
    'care whether a fix works',
    '在意某件事是否成立',
    'The reviewer cared.',
    '评审者很在意。',
    'The reviewer cared whether the fix protected older clients during the rollout.',
    '评审者在意这项修复是否能在发布过程中保护旧版客户端。',
    'compatibility-review',
    '{"schema_version":2,"root_action_id":"cared","nodes":[{"id":"cared","text":"cared","kind":"action","label_zh":"认真在意结果"},{"id":"reviewer","text":"The reviewer","kind":"core","label_zh":"关注结果的评审者"},{"id":"protected","text":"protected","kind":"action","label_zh":"保障旧版客户端"},{"id":"fix","text":"the fix","kind":"core","label_zh":"接受兼容性检验的修复"},{"id":"older-clients","text":"older clients","kind":"core","label_zh":"需要受到保护的旧版客户端"},{"id":"during-rollout","text":"during the rollout","kind":"modifier","label_zh":"兼容性保护需要持续的阶段"}],"links":[{"id":"cared->reviewer","from":"cared","to":"reviewer","kind":"core","relation_type":"actor","label_zh":"评审者很在意兼容性结果"},{"id":"cared->protected","from":"cared","to":"protected","kind":"core","relation_type":"content","label_zh":"在意的内容是修复能否保护旧客户端"},{"id":"protected->fix","from":"protected","to":"fix","kind":"core","relation_type":"actor","label_zh":"修复承担兼容性保护作用"},{"id":"protected->older-clients","from":"protected","to":"older-clients","kind":"core","relation_type":"target","label_zh":"保护对象是旧版客户端"},{"id":"during-rollout->protected","from":"during-rollout","to":"protected","kind":"modifier","relation_type":"time","label_zh":"保护需要在发布过程中保持有效"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The reviewer cared.","sentence_zh":"评审者很在意。","add_node_ids":["cared","reviewer"],"add_link_ids":["cared->reviewer"],"focus_node_id":"cared","note_zh":"先呈现评审者认真关注的态度。"},{"step_no":2,"label":"内容","sentence_en":"The reviewer cared whether the fix protected older clients.","sentence_zh":"评审者在意这项修复是否保护了旧版客户端。","add_node_ids":["protected","fix","older-clients"],"add_link_ids":["cared->protected","protected->fix","protected->older-clients"],"focus_node_id":"protected","note_zh":"whether引出评审者真正关心的兼容性结果。"},{"step_no":3,"label":"时间","sentence_en":"The reviewer cared whether the fix protected older clients during the rollout.","sentence_zh":"评审者在意这项修复是否能在发布过程中保护旧版客户端。","add_node_ids":["during-rollout"],"add_link_ids":["during-rollout->protected"],"focus_node_id":"during-rollout","note_zh":"限定兼容性保护必须覆盖发布过程。"}]}'
  ),
  (
    'care-about-primary',
    'care-about',
    'care about',
    'care about predictable billing',
    '重视某个方面',
    'Users care about predictable billing.',
    '用户关心计费是否稳定可预期。',
    'Users care about predictable billing more than flashy dashboards during budget reviews.',
    '在预算评审期间，相比炫目的仪表盘，用户更关心稳定可预期的计费。',
    'customer-priorities',
    '{"schema_version":2,"root_action_id":"care-about","nodes":[{"id":"care-about","text":"care about","kind":"action","label_zh":"重视计费体验"},{"id":"users","text":"Users","kind":"core","label_zh":"表达产品偏好的用户"},{"id":"predictable-billing","text":"predictable billing","kind":"core","label_zh":"用户重视的稳定计费"},{"id":"more-than-flashy-dashboards","text":"more than flashy dashboards","kind":"modifier","label_zh":"计费与炫目界面的偏好比较"},{"id":"during-budget-reviews","text":"during budget reviews","kind":"modifier","label_zh":"这种偏好尤其明显的场景"}],"links":[{"id":"care-about->users","from":"care-about","to":"users","kind":"core","relation_type":"actor","label_zh":"用户持有这种产品偏好"},{"id":"care-about->predictable-billing","from":"care-about","to":"predictable-billing","kind":"core","relation_type":"target","label_zh":"用户重视可预期的计费"},{"id":"more-than-flashy-dashboards->care-about","from":"more-than-flashy-dashboards","to":"care-about","kind":"modifier","relation_type":"degree","label_zh":"用户对计费的重视超过对炫目界面的重视"},{"id":"during-budget-reviews->care-about","from":"during-budget-reviews","to":"care-about","kind":"modifier","relation_type":"time","label_zh":"预算评审期间这种偏好尤其重要"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Users care about predictable billing.","sentence_zh":"用户关心计费是否稳定可预期。","add_node_ids":["care-about","users","predictable-billing"],"add_link_ids":["care-about->users","care-about->predictable-billing"],"focus_node_id":"predictable-billing","note_zh":"care about直接连接用户重视的产品特征。"},{"step_no":2,"label":"程度","sentence_en":"Users care about predictable billing more than flashy dashboards.","sentence_zh":"相比炫目的仪表盘，用户更关心稳定可预期的计费。","add_node_ids":["more-than-flashy-dashboards"],"add_link_ids":["more-than-flashy-dashboards->care-about"],"focus_node_id":"more-than-flashy-dashboards","note_zh":"通过比较明确两种产品价值的优先级。"},{"step_no":3,"label":"场景","sentence_en":"Users care about predictable billing more than flashy dashboards during budget reviews.","sentence_zh":"在预算评审期间，相比炫目的仪表盘，用户更关心稳定可预期的计费。","add_node_ids":["during-budget-reviews"],"add_link_ids":["during-budget-reviews->care-about"],"focus_node_id":"during-budget-reviews","note_zh":"补充这种产品偏好尤其明显的实际场景。"}]}'
  ),
  (
    'carry-primary',
    'carry',
    'carry',
    'carry a tenant ID',
    '携带并传递信息',
    'The gateway carries the tenant ID.',
    '网关携带租户标识。',
    'The gateway carries the tenant ID across internal requests without the account name.',
    '网关让租户标识贯穿内部请求，但不附带账户名称。',
    'request-routing',
    '{"schema_version":2,"root_action_id":"carries","nodes":[{"id":"carries","text":"carries","kind":"action","label_zh":"随请求传递标识"},{"id":"gateway","text":"The gateway","kind":"core","label_zh":"负责传递信息的网关"},{"id":"tenant-id","text":"the tenant ID","kind":"core","label_zh":"被携带的租户标识"},{"id":"across-internal-requests","text":"across internal requests","kind":"modifier","label_zh":"标识随行的请求范围"},{"id":"without-account-name","text":"without the account name","kind":"modifier","label_zh":"传递时排除的账户信息"}],"links":[{"id":"carries->gateway","from":"carries","to":"gateway","kind":"core","relation_type":"actor","label_zh":"网关负责携带标识"},{"id":"carries->tenant-id","from":"carries","to":"tenant-id","kind":"core","relation_type":"target","label_zh":"网关传递的是租户标识"},{"id":"across-internal-requests->carries","from":"across-internal-requests","to":"carries","kind":"modifier","relation_type":"scope","label_zh":"租户标识贯穿内部请求"},{"id":"without-account-name->carries","from":"without-account-name","to":"carries","kind":"modifier","relation_type":"content","label_zh":"传递租户标识时不附带账户名称"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The gateway carries the tenant ID.","sentence_zh":"网关携带租户标识。","add_node_ids":["carries","gateway","tenant-id"],"add_link_ids":["carries->gateway","carries->tenant-id"],"focus_node_id":"carries","note_zh":"这里的carry表示信息随技术流程一同传递。"},{"step_no":2,"label":"范围","sentence_en":"The gateway carries the tenant ID across internal requests.","sentence_zh":"网关让租户标识贯穿内部请求。","add_node_ids":["across-internal-requests"],"add_link_ids":["across-internal-requests->carries"],"focus_node_id":"across-internal-requests","note_zh":"扩展标识被传递的请求范围。"},{"step_no":3,"label":"内容","sentence_en":"The gateway carries the tenant ID across internal requests without the account name.","sentence_zh":"网关让租户标识贯穿内部请求，但不附带账户名称。","add_node_ids":["without-account-name"],"add_link_ids":["without-account-name->carries"],"focus_node_id":"without-account-name","note_zh":"说明传递过程中有意排除了哪项信息。"}]}'
  ),
  (
    'carry-on-primary',
    'carry-on',
    'carry on',
    'carry on despite a warning',
    '在干扰下继续进行',
    'The deployment carried on.',
    '部署继续进行。',
    'The deployment carried on despite a noisy warning through the final region.',
    '尽管有一条干扰性很强的告警，部署仍继续推进并覆盖了最后一个区域。',
    'regional-deployment',
    '{"schema_version":2,"root_action_id":"carried-on","nodes":[{"id":"carried-on","text":"carried on","kind":"action","label_zh":"部署继续推进"},{"id":"deployment","text":"The deployment","kind":"core","label_zh":"没有中止的部署过程"},{"id":"despite-noisy-warning","text":"despite a noisy warning","kind":"modifier","label_zh":"未能阻止部署的干扰"},{"id":"through-final-region","text":"through the final region","kind":"modifier","label_zh":"部署持续覆盖的最后范围"}],"links":[{"id":"carried-on->deployment","from":"carried-on","to":"deployment","kind":"core","relation_type":"actor","label_zh":"部署过程持续向前"},{"id":"despite-noisy-warning->carried-on","from":"despite-noisy-warning","to":"carried-on","kind":"modifier","relation_type":"condition","label_zh":"即使告警嘈杂，部署仍未停止"},{"id":"through-final-region->carried-on","from":"through-final-region","to":"carried-on","kind":"modifier","relation_type":"scope","label_zh":"部署一直继续到最后一个区域"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The deployment carried on.","sentence_zh":"部署继续进行。","add_node_ids":["carried-on","deployment"],"add_link_ids":["carried-on->deployment"],"focus_node_id":"carried-on","note_zh":"主干强调部署过程没有停止。"},{"step_no":2,"label":"条件","sentence_en":"The deployment carried on despite a noisy warning.","sentence_zh":"尽管有一条干扰性很强的告警，部署仍继续进行。","add_node_ids":["despite-noisy-warning"],"add_link_ids":["despite-noisy-warning->carried-on"],"focus_node_id":"despite-noisy-warning","note_zh":"加入未能打断部署的干扰因素。"},{"step_no":3,"label":"范围","sentence_en":"The deployment carried on despite a noisy warning through the final region.","sentence_zh":"尽管有一条干扰性很强的告警，部署仍继续推进并覆盖了最后一个区域。","add_node_ids":["through-final-region"],"add_link_ids":["through-final-region->carried-on"],"focus_node_id":"through-final-region","note_zh":"指出部署持续推进到哪个区域。"}]}'
  ),
  (
    'carry-out-primary',
    'carry-out',
    'carry out',
    'carry out an audit',
    '执行计划好的工作',
    'The security team carried out the audit.',
    '安全团队执行了审计。',
    'The security team carried out the audit under the new policy with metadata only.',
    '安全团队按照新政策执行了审计，并且只使用元数据。',
    'security-audit',
    '{"schema_version":2,"root_action_id":"carried-out","nodes":[{"id":"carried-out","text":"carried out","kind":"action","label_zh":"执行安全审计"},{"id":"security-team","text":"The security team","kind":"core","label_zh":"负责执行审计的团队"},{"id":"audit","text":"the audit","kind":"core","label_zh":"被执行的审计工作"},{"id":"under-new-policy","text":"under the new policy","kind":"modifier","label_zh":"审计遵循的政策环境"},{"id":"with-metadata-only","text":"with metadata only","kind":"modifier","label_zh":"审计所使用的数据范围"}],"links":[{"id":"carried-out->security-team","from":"carried-out","to":"security-team","kind":"core","relation_type":"actor","label_zh":"安全团队执行了审计"},{"id":"carried-out->audit","from":"carried-out","to":"audit","kind":"core","relation_type":"target","label_zh":"团队落实的是安全审计"},{"id":"under-new-policy->carried-out","from":"under-new-policy","to":"carried-out","kind":"modifier","relation_type":"condition","label_zh":"审计按照新政策开展"},{"id":"with-metadata-only->carried-out","from":"with-metadata-only","to":"carried-out","kind":"modifier","relation_type":"manner","label_zh":"审计过程只使用元数据"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The security team carried out the audit.","sentence_zh":"安全团队执行了审计。","add_node_ids":["carried-out","security-team","audit"],"add_link_ids":["carried-out->security-team","carried-out->audit"],"focus_node_id":"carried-out","note_zh":"carry out表示把计划中的审计实际执行出来。"},{"step_no":2,"label":"条件","sentence_en":"The security team carried out the audit under the new policy.","sentence_zh":"安全团队按照新政策执行了审计。","add_node_ids":["under-new-policy"],"add_link_ids":["under-new-policy->carried-out"],"focus_node_id":"under-new-policy","note_zh":"补上审计所遵循的制度背景。"},{"step_no":3,"label":"方式","sentence_en":"The security team carried out the audit under the new policy with metadata only.","sentence_zh":"安全团队按照新政策执行了审计，并且只使用元数据。","add_node_ids":["with-metadata-only"],"add_link_ids":["with-metadata-only->carried-out"],"focus_node_id":"with-metadata-only","note_zh":"明确审计过程采用的数据边界。"}]}'
  ),
  (
    'carry-over-primary',
    'carry-over',
    'carry over',
    'credits carry over',
    '保留并延续到下一周期',
    'Unused credits carry over.',
    '未使用的额度会结转。',
    'Unused credits carry over to the next billing cycle for active accounts.',
    '对于有效账户，未使用的额度会结转到下一个计费周期。',
    'subscription-billing',
    '{"schema_version":2,"root_action_id":"carry-over","nodes":[{"id":"carry-over","text":"carry over","kind":"action","label_zh":"余额延续到下期"},{"id":"unused-credits","text":"Unused credits","kind":"core","label_zh":"可以继续保留的额度"},{"id":"next-billing-cycle","text":"the next billing cycle","kind":"core","label_zh":"额度转入的新周期"},{"id":"for-active-accounts","text":"for active accounts","kind":"modifier","label_zh":"允许额度结转的账户范围"}],"links":[{"id":"carry-over->unused-credits","from":"carry-over","to":"unused-credits","kind":"core","relation_type":"actor","label_zh":"未使用额度继续保留"},{"id":"carry-over->next-billing-cycle","from":"carry-over","to":"next-billing-cycle","kind":"core","relation_type":"target","label_zh":"额度延续到下一计费周期"},{"id":"for-active-accounts->carry-over","from":"for-active-accounts","to":"carry-over","kind":"modifier","relation_type":"condition","label_zh":"只有有效账户中的额度可以结转"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Unused credits carry over.","sentence_zh":"未使用的额度会结转。","add_node_ids":["carry-over","unused-credits"],"add_link_ids":["carry-over->unused-credits"],"focus_node_id":"carry-over","note_zh":"先表达剩余额度不会立即消失。"},{"step_no":2,"label":"去向","sentence_en":"Unused credits carry over to the next billing cycle.","sentence_zh":"未使用的额度会结转到下一个计费周期。","add_node_ids":["next-billing-cycle"],"add_link_ids":["carry-over->next-billing-cycle"],"focus_node_id":"next-billing-cycle","note_zh":"指出保留额度进入哪个周期。"},{"step_no":3,"label":"条件","sentence_en":"Unused credits carry over to the next billing cycle for active accounts.","sentence_zh":"对于有效账户，未使用的额度会结转到下一个计费周期。","add_node_ids":["for-active-accounts"],"add_link_ids":["for-active-accounts->carry-over"],"focus_node_id":"for-active-accounts","note_zh":"限定哪些账户可以保留剩余额度。"}]}'
  ),
  (
    'carve-primary',
    'carve',
    'carve',
    'carve a serial number',
    '在坚硬表面刻出标记',
    'The laser carved a serial number.',
    '激光设备刻出了一个序列号。',
    'The laser carved a serial number into the aluminum case before final assembly.',
    '最终组装前，激光设备在铝制外壳上刻出了一个序列号。',
    'hardware-marking',
    '{"schema_version":2,"root_action_id":"carved","nodes":[{"id":"carved","text":"carved","kind":"action","label_zh":"刻出序列号"},{"id":"laser","text":"The laser","kind":"core","label_zh":"执行雕刻的设备"},{"id":"serial-number","text":"a serial number","kind":"core","label_zh":"被刻出的识别标记"},{"id":"aluminum-case","text":"the aluminum case","kind":"core","label_zh":"承载序列号的外壳"},{"id":"before-final-assembly","text":"before final assembly","kind":"modifier","label_zh":"雕刻在生产流程中的时间"}],"links":[{"id":"carved->laser","from":"carved","to":"laser","kind":"core","relation_type":"actor","label_zh":"激光设备完成雕刻"},{"id":"carved->serial-number","from":"carved","to":"serial-number","kind":"core","relation_type":"target","label_zh":"刻出的内容是序列号"},{"id":"carved->aluminum-case","from":"carved","to":"aluminum-case","kind":"core","relation_type":"place","label_zh":"序列号被刻入铝制外壳"},{"id":"before-final-assembly->carved","from":"before-final-assembly","to":"carved","kind":"modifier","relation_type":"time","label_zh":"雕刻安排在最终组装之前"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The laser carved a serial number.","sentence_zh":"激光设备刻出了一个序列号。","add_node_ids":["carved","laser","serial-number"],"add_link_ids":["carved->laser","carved->serial-number"],"focus_node_id":"carved","note_zh":"主干呈现设备刻出识别标记的动作。"},{"step_no":2,"label":"场景","sentence_en":"The laser carved a serial number into the aluminum case.","sentence_zh":"激光设备在铝制外壳上刻出了一个序列号。","add_node_ids":["aluminum-case"],"add_link_ids":["carved->aluminum-case"],"focus_node_id":"aluminum-case","note_zh":"补充序列号实际刻入的硬件表面。"},{"step_no":3,"label":"时间","sentence_en":"The laser carved a serial number into the aluminum case before final assembly.","sentence_zh":"最终组装前，激光设备在铝制外壳上刻出了一个序列号。","add_node_ids":["before-final-assembly"],"add_link_ids":["before-final-assembly->carved"],"focus_node_id":"before-final-assembly","note_zh":"把雕刻操作定位到生产流程中的具体阶段。"}]}'
  ),
  (
    'cash-in-primary',
    'cash-in',
    'cash in',
    'cash in stock options',
    '将有价值的权益兑现',
    'The founders cashed in their stock options.',
    '创始人兑现了他们的股票期权。',
    'The founders cashed in their stock options at the agreed price after the acquisition.',
    '收购完成后，创始人按约定价格兑现了他们的股票期权。',
    'acquisition-payout',
    '{"schema_version":2,"root_action_id":"cashed-in","nodes":[{"id":"cashed-in","text":"cashed in","kind":"action","label_zh":"兑现股票期权"},{"id":"founders","text":"The founders","kind":"core","label_zh":"获得兑现收益的创始人"},{"id":"stock-options","text":"their stock options","kind":"core","label_zh":"被兑现的股票期权"},{"id":"at-agreed-price","text":"at the agreed price","kind":"modifier","label_zh":"期权兑现采用的价格"},{"id":"after-acquisition","text":"after the acquisition","kind":"modifier","label_zh":"期权兑现所处的交易阶段"}],"links":[{"id":"cashed-in->founders","from":"cashed-in","to":"founders","kind":"core","relation_type":"actor","label_zh":"创始人执行了兑现操作"},{"id":"cashed-in->stock-options","from":"cashed-in","to":"stock-options","kind":"core","relation_type":"target","label_zh":"兑现对象是他们的股票期权"},{"id":"at-agreed-price->cashed-in","from":"at-agreed-price","to":"cashed-in","kind":"modifier","relation_type":"degree","label_zh":"期权按照约定价格兑现"},{"id":"after-acquisition->cashed-in","from":"after-acquisition","to":"cashed-in","kind":"modifier","relation_type":"time","label_zh":"期权在收购完成后兑现"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The founders cashed in their stock options.","sentence_zh":"创始人兑现了他们的股票期权。","add_node_ids":["cashed-in","founders","stock-options"],"add_link_ids":["cashed-in->founders","cashed-in->stock-options"],"focus_node_id":"cashed-in","note_zh":"cash in在这里表示把期权转换为实际收益。"},{"step_no":2,"label":"程度","sentence_en":"The founders cashed in their stock options at the agreed price.","sentence_zh":"创始人按约定价格兑现了他们的股票期权。","add_node_ids":["at-agreed-price"],"add_link_ids":["at-agreed-price->cashed-in"],"focus_node_id":"at-agreed-price","note_zh":"补充权益兑现时采用的价格。"},{"step_no":3,"label":"时间","sentence_en":"The founders cashed in their stock options at the agreed price after the acquisition.","sentence_zh":"收购完成后，创始人按约定价格兑现了他们的股票期权。","add_node_ids":["after-acquisition"],"add_link_ids":["after-acquisition->cashed-in"],"focus_node_id":"after-acquisition","note_zh":"说明兑现期权所处的交易阶段。"}]}'
  ),
  (
    'catch-primary',
    'catch',
    'catch',
    'catch a missing check',
    '及时发现问题',
    'The linter caught a missing null check.',
    '代码检查工具发现了一处缺失的空值检查。',
    'The linter caught a missing null check in the upload handler before production.',
    '代码检查工具在进入生产环境前，于上传处理代码中发现了一处缺失的空值检查。',
    'static-analysis',
    '{"schema_version":2,"root_action_id":"caught","nodes":[{"id":"caught","text":"caught","kind":"action","label_zh":"发现代码遗漏"},{"id":"linter","text":"The linter","kind":"core","label_zh":"检测出问题的工具"},{"id":"missing-null-check","text":"a missing null check","kind":"core","label_zh":"被发现的空值检查遗漏"},{"id":"in-upload-handler","text":"in the upload handler","kind":"modifier","label_zh":"遗漏所在的代码位置"},{"id":"before-production","text":"before production","kind":"modifier","label_zh":"问题被发现的上线阶段"}],"links":[{"id":"caught->linter","from":"caught","to":"linter","kind":"core","relation_type":"actor","label_zh":"代码检查工具发现了遗漏"},{"id":"caught->missing-null-check","from":"caught","to":"missing-null-check","kind":"core","relation_type":"target","label_zh":"发现的是缺失的空值检查"},{"id":"in-upload-handler->missing-null-check","from":"in-upload-handler","to":"missing-null-check","kind":"modifier","relation_type":"place","label_zh":"空值检查遗漏位于上传处理代码中"},{"id":"before-production->caught","from":"before-production","to":"caught","kind":"modifier","relation_type":"time","label_zh":"问题在进入生产环境前被发现"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The linter caught a missing null check.","sentence_zh":"代码检查工具发现了一处缺失的空值检查。","add_node_ids":["caught","linter","missing-null-check"],"add_link_ids":["caught->linter","caught->missing-null-check"],"focus_node_id":"caught","note_zh":"catch表示工具及时检测到了代码问题。"},{"step_no":2,"label":"对象细节","sentence_en":"The linter caught a missing null check in the upload handler.","sentence_zh":"代码检查工具在上传处理代码中发现了一处缺失的空值检查。","add_node_ids":["in-upload-handler"],"add_link_ids":["in-upload-handler->missing-null-check"],"focus_node_id":"in-upload-handler","note_zh":"把遗漏准确定位到上传处理代码。"},{"step_no":3,"label":"时间","sentence_en":"The linter caught a missing null check in the upload handler before production.","sentence_zh":"代码检查工具在进入生产环境前，于上传处理代码中发现了一处缺失的空值检查。","add_node_ids":["before-production"],"add_link_ids":["before-production->caught"],"focus_node_id":"before-production","note_zh":"强调问题是在上线之前被及时发现的。"}]}'
  ),
  (
    'catch-on-primary',
    'catch-on',
    'catch on',
    'catch on through comparison',
    '逐渐理解',
    'Omar caught on.',
    'Omar明白过来了。',
    'Omar caught on after the comparison with the query plans side by side.',
    '把两份查询计划并排比较后，Omar明白过来了。',
    'query-debugging',
    '{"schema_version":2,"root_action_id":"caught-on","nodes":[{"id":"caught-on","text":"caught on","kind":"action","label_zh":"理解了问题关键"},{"id":"omar","text":"Omar","kind":"core","label_zh":"逐渐理解的人"},{"id":"after-comparison","text":"after the comparison","kind":"modifier","label_zh":"促成理解的分析阶段"},{"id":"with-query-plans-side-by-side","text":"with the query plans side by side","kind":"modifier","label_zh":"帮助看出差异的排列方式"}],"links":[{"id":"caught-on->omar","from":"caught-on","to":"omar","kind":"core","relation_type":"actor","label_zh":"Omar最终理解了问题"},{"id":"after-comparison->caught-on","from":"after-comparison","to":"caught-on","kind":"modifier","relation_type":"time","label_zh":"完成比较后Omar明白了关键"},{"id":"with-query-plans-side-by-side->after-comparison","from":"with-query-plans-side-by-side","to":"after-comparison","kind":"modifier","relation_type":"manner","label_zh":"比较时将两份查询计划并排放置"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Omar caught on.","sentence_zh":"Omar明白过来了。","add_node_ids":["caught-on","omar"],"add_link_ids":["caught-on->omar"],"focus_node_id":"caught-on","note_zh":"主干表达从不理解到理解的变化。"},{"step_no":2,"label":"时间","sentence_en":"Omar caught on after the comparison.","sentence_zh":"完成比较后，Omar明白过来了。","add_node_ids":["after-comparison"],"add_link_ids":["after-comparison->caught-on"],"focus_node_id":"after-comparison","note_zh":"指出理解发生在分析比较之后。"},{"step_no":3,"label":"方式","sentence_en":"Omar caught on after the comparison with the query plans side by side.","sentence_zh":"把两份查询计划并排比较后，Omar明白过来了。","add_node_ids":["with-query-plans-side-by-side"],"add_link_ids":["with-query-plans-side-by-side->after-comparison"],"focus_node_id":"with-query-plans-side-by-side","note_zh":"说明比较查询计划时采用的具体排列方式。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
