-- Generated verb paths batch batch-002.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'cope-primary',
    'cope',
    'cope',
    'cope with a traffic spike',
    '应对突发的流量高峰',
    'The support team coped with the traffic spike.',
    '支持团队应对了这次流量高峰。',
    'The support team coped with the traffic spike during the product launch by routing overflow requests to a backup cluster.',
    '支持团队在产品发布期间把溢出的请求转发到备用集群，从而应对了这次流量高峰。',
    'traffic-spike',
    '{"schema_version":2,"root_action_id":"cope-with-spike","nodes":[{"id":"cope-with-spike","text":"coped","kind":"action","label_zh":"应对流量高峰"},{"id":"support-team","text":"The support team","kind":"core","label_zh":"负责应对的支持团队"},{"id":"traffic-spike","text":"the traffic spike","kind":"core","label_zh":"需要处理的流量高峰"},{"id":"during-launch","text":"during the product launch","kind":"modifier","label_zh":"流量应对发生的时间"},{"id":"route-requests","text":"routing","kind":"action","label_zh":"转发溢出的请求"},{"id":"overflow-requests","text":"overflow requests","kind":"core","label_zh":"被转发的溢出请求"},{"id":"backup-cluster","text":"a backup cluster","kind":"core","label_zh":"接收请求的备用集群"}],"links":[{"id":"cope-with-spike->support-team","from":"cope-with-spike","to":"support-team","kind":"core","relation_type":"actor","label_zh":"支持团队负责应对"},{"id":"cope-with-spike->traffic-spike","from":"cope-with-spike","to":"traffic-spike","kind":"core","relation_type":"target","label_zh":"应对的是流量高峰"},{"id":"during-launch->cope-with-spike","from":"during-launch","to":"cope-with-spike","kind":"modifier","relation_type":"time","label_zh":"应对发生在产品发布期间"},{"id":"route-requests->support-team","from":"route-requests","to":"support-team","kind":"core","relation_type":"shared_actor","label_zh":"同一支持团队执行请求转发"},{"id":"route-requests->overflow-requests","from":"route-requests","to":"overflow-requests","kind":"core","relation_type":"target","label_zh":"被转发的是溢出请求"},{"id":"route-requests->backup-cluster","from":"route-requests","to":"backup-cluster","kind":"core","relation_type":"recipient","label_zh":"备用集群接收转发的请求"},{"id":"route-requests->cope-with-spike","from":"route-requests","to":"cope-with-spike","kind":"modifier","relation_type":"manner","label_zh":"转发请求是团队的应对方式"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The support team coped with the traffic spike.","sentence_zh":"支持团队应对了这次流量高峰。","add_node_ids":["cope-with-spike","support-team","traffic-spike"],"add_link_ids":["cope-with-spike->support-team","cope-with-spike->traffic-spike"],"focus_node_id":"cope-with-spike","note_zh":"先说明哪个团队应对了什么问题。"},{"step_no":2,"label":"时间","sentence_en":"The support team coped with the traffic spike during the product launch.","sentence_zh":"支持团队在产品发布期间应对了这次流量高峰。","add_node_ids":["during-launch"],"add_link_ids":["during-launch->cope-with-spike"],"focus_node_id":"during-launch","note_zh":"补充流量高峰需要处理的时间。"},{"step_no":3,"label":"方式","sentence_en":"The support team coped with the traffic spike during the product launch by routing overflow requests to a backup cluster.","sentence_zh":"支持团队在产品发布期间把溢出的请求转发到备用集群，从而应对了这次流量高峰。","add_node_ids":["route-requests","overflow-requests","backup-cluster"],"add_link_ids":["route-requests->support-team","route-requests->overflow-requests","route-requests->backup-cluster","route-requests->cope-with-spike"],"focus_node_id":"route-requests","note_zh":"最后交代团队具体采用的应对方式。"}]}'
  ),
  (
    'copy-primary',
    'copy',
    'copy',
    'copy logs to a drive',
    '把日志复制到另一个存储位置',
    'Maya copied the production logs.',
    'Maya复制了生产日志。',
    'Maya copied the production logs to an encrypted drive before the instance was terminated.',
    'Maya在实例被终止前，把生产日志复制到了一块加密硬盘中。',
    'log-backup',
    '{"schema_version":2,"root_action_id":"copy-logs","nodes":[{"id":"copy-logs","text":"copied","kind":"action","label_zh":"复制生产日志"},{"id":"maya","text":"Maya","kind":"core","label_zh":"执行复制的工程师"},{"id":"production-logs","text":"the production logs","kind":"core","label_zh":"被复制的生产日志"},{"id":"encrypted-drive","text":"an encrypted drive","kind":"core","label_zh":"保存日志的加密硬盘"},{"id":"terminate-instance","text":"was terminated","kind":"action","label_zh":"实例被终止"},{"id":"instance","text":"the instance","kind":"core","label_zh":"随后被终止的实例"}],"links":[{"id":"copy-logs->maya","from":"copy-logs","to":"maya","kind":"core","relation_type":"actor","label_zh":"Maya执行日志复制"},{"id":"copy-logs->production-logs","from":"copy-logs","to":"production-logs","kind":"core","relation_type":"target","label_zh":"复制的内容是生产日志"},{"id":"copy-logs->encrypted-drive","from":"copy-logs","to":"encrypted-drive","kind":"core","relation_type":"recipient","label_zh":"日志被复制到加密硬盘"},{"id":"terminate-instance->instance","from":"terminate-instance","to":"instance","kind":"core","relation_type":"target","label_zh":"被终止的是该实例"},{"id":"terminate-instance->copy-logs","from":"terminate-instance","to":"copy-logs","kind":"modifier","relation_type":"time","label_zh":"日志复制发生在实例终止之前"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Maya copied the production logs.","sentence_zh":"Maya复制了生产日志。","add_node_ids":["copy-logs","maya","production-logs"],"add_link_ids":["copy-logs->maya","copy-logs->production-logs"],"focus_node_id":"copy-logs","note_zh":"先呈现复制日志这一核心事实。"},{"step_no":2,"label":"对象细节","sentence_en":"Maya copied the production logs to an encrypted drive.","sentence_zh":"Maya把生产日志复制到了一块加密硬盘中。","add_node_ids":["encrypted-drive"],"add_link_ids":["copy-logs->encrypted-drive"],"focus_node_id":"encrypted-drive","note_zh":"加入日志复制后的存放位置。"},{"step_no":3,"label":"时间","sentence_en":"Maya copied the production logs to an encrypted drive before the instance was terminated.","sentence_zh":"Maya在实例被终止前，把生产日志复制到了一块加密硬盘中。","add_node_ids":["terminate-instance","instance"],"add_link_ids":["terminate-instance->instance","terminate-instance->copy-logs"],"focus_node_id":"terminate-instance","note_zh":"用实例终止这一事件限定复制时间。"}]}'
  ),
  (
    'correct-primary',
    'correct',
    'correct',
    'correct an API example',
    '改正API示例中的错误',
    'The reviewer corrected the API example.',
    '审阅者改正了API示例。',
    'The reviewer corrected the API example in the migration guide after a reader reported an incorrect parameter name.',
    '一名读者报告了一个错误的参数名后，审阅者改正了迁移指南中的API示例。',
    'documentation-fix',
    '{"schema_version":2,"root_action_id":"correct-example","nodes":[{"id":"correct-example","text":"corrected","kind":"action","label_zh":"改正API示例"},{"id":"reviewer","text":"The reviewer","kind":"core","label_zh":"改正示例的审阅者"},{"id":"api-example","text":"the API example","kind":"core","label_zh":"需要改正的API示例"},{"id":"in-migration-guide","text":"in the migration guide","kind":"modifier","label_zh":"示例所在的迁移指南"},{"id":"report-parameter","text":"reported","kind":"action","label_zh":"报告参数名称错误"},{"id":"reader","text":"a reader","kind":"core","label_zh":"发现并报告问题的读者"},{"id":"incorrect-parameter-name","text":"an incorrect parameter name","kind":"core","label_zh":"读者报告的错误参数名"}],"links":[{"id":"correct-example->reviewer","from":"correct-example","to":"reviewer","kind":"core","relation_type":"actor","label_zh":"审阅者执行改正"},{"id":"correct-example->api-example","from":"correct-example","to":"api-example","kind":"core","relation_type":"target","label_zh":"被改正的是API示例"},{"id":"in-migration-guide->api-example","from":"in-migration-guide","to":"api-example","kind":"modifier","relation_type":"place","label_zh":"该示例位于迁移指南中"},{"id":"report-parameter->reader","from":"report-parameter","to":"reader","kind":"core","relation_type":"actor","label_zh":"读者提交了问题报告"},{"id":"report-parameter->incorrect-parameter-name","from":"report-parameter","to":"incorrect-parameter-name","kind":"core","relation_type":"content","label_zh":"报告内容是一个错误的参数名"},{"id":"report-parameter->correct-example","from":"report-parameter","to":"correct-example","kind":"modifier","relation_type":"time","label_zh":"示例在读者报告问题后得到改正"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The reviewer corrected the API example.","sentence_zh":"审阅者改正了API示例。","add_node_ids":["correct-example","reviewer","api-example"],"add_link_ids":["correct-example->reviewer","correct-example->api-example"],"focus_node_id":"correct-example","note_zh":"主干说明审阅者改正了哪项内容。"},{"step_no":2,"label":"场景","sentence_en":"The reviewer corrected the API example in the migration guide.","sentence_zh":"审阅者改正了迁移指南中的API示例。","add_node_ids":["in-migration-guide"],"add_link_ids":["in-migration-guide->api-example"],"focus_node_id":"in-migration-guide","note_zh":"指出这个API示例出现在哪份文档中。"},{"step_no":3,"label":"时间","sentence_en":"The reviewer corrected the API example in the migration guide after a reader reported an incorrect parameter name.","sentence_zh":"一名读者报告了一个错误的参数名后，审阅者改正了迁移指南中的API示例。","add_node_ids":["report-parameter","reader","incorrect-parameter-name"],"add_link_ids":["report-parameter->reader","report-parameter->incorrect-parameter-name","report-parameter->correct-example"],"focus_node_id":"report-parameter","note_zh":"补充促使改正发生的先前报告。"}]}'
  ),
  (
    'correspond-primary',
    'correspond',
    'correspond',
    'correspond to an action',
    '与某项处理措施相对应',
    'Each status code corresponds to one recovery action.',
    '每个状态码都对应一项恢复措施。',
    'Each status code corresponds to one recovery action in the runbook.',
    '每个状态码都对应运行手册中的一项恢复措施。',
    'status-runbook',
    '{"schema_version":2,"root_action_id":"correspond-to-action","nodes":[{"id":"correspond-to-action","text":"corresponds","kind":"action","label_zh":"状态码与措施相对应"},{"id":"status-code","text":"Each status code","kind":"core","label_zh":"逐一对应的状态码"},{"id":"recovery-action","text":"one recovery action","kind":"core","label_zh":"与状态码匹配的恢复措施"},{"id":"in-runbook","text":"in the runbook","kind":"modifier","label_zh":"恢复措施记录的位置"}],"links":[{"id":"correspond-to-action->status-code","from":"correspond-to-action","to":"status-code","kind":"core","relation_type":"actor","label_zh":"每个状态码建立一项对应关系"},{"id":"correspond-to-action->recovery-action","from":"correspond-to-action","to":"recovery-action","kind":"core","relation_type":"target","label_zh":"对应的是一项恢复措施"},{"id":"in-runbook->recovery-action","from":"in-runbook","to":"recovery-action","kind":"modifier","relation_type":"place","label_zh":"恢复措施记录在运行手册中"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Each status code corresponds to one recovery action.","sentence_zh":"每个状态码都对应一项恢复措施。","add_node_ids":["correspond-to-action","status-code","recovery-action"],"add_link_ids":["correspond-to-action->status-code","correspond-to-action->recovery-action"],"focus_node_id":"correspond-to-action","note_zh":"直接建立状态码与恢复措施之间的对应关系。"},{"step_no":2,"label":"场景","sentence_en":"Each status code corresponds to one recovery action in the runbook.","sentence_zh":"每个状态码都对应运行手册中的一项恢复措施。","add_node_ids":["in-runbook"],"add_link_ids":["in-runbook->recovery-action"],"focus_node_id":"in-runbook","note_zh":"说明这些恢复措施可以在哪里找到。"}]}'
  ),
  (
    'corrupt-primary',
    'corrupt',
    'corrupt',
    'corrupt a configuration',
    '造成配置数据损坏',
    'A firmware update corrupted the router''s configuration.',
    '一次固件更新损坏了路由器的配置。',
    'A firmware update corrupted the router''s configuration during a power outage.',
    '一次固件更新在停电期间损坏了路由器的配置。',
    'router-outage',
    '{"schema_version":2,"root_action_id":"corrupt-configuration","nodes":[{"id":"corrupt-configuration","text":"corrupted","kind":"action","label_zh":"造成路由器配置损坏"},{"id":"firmware-update","text":"A firmware update","kind":"core","label_zh":"导致损坏的固件更新"},{"id":"router-configuration","text":"the router''s configuration","kind":"core","label_zh":"被损坏的路由器配置"},{"id":"during-outage","text":"during a power outage","kind":"modifier","label_zh":"配置损坏发生的场景"}],"links":[{"id":"corrupt-configuration->firmware-update","from":"corrupt-configuration","to":"firmware-update","kind":"core","relation_type":"actor","label_zh":"固件更新造成了损坏"},{"id":"corrupt-configuration->router-configuration","from":"corrupt-configuration","to":"router-configuration","kind":"core","relation_type":"target","label_zh":"受损的是路由器配置"},{"id":"during-outage->corrupt-configuration","from":"during-outage","to":"corrupt-configuration","kind":"modifier","relation_type":"time","label_zh":"损坏发生在停电期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A firmware update corrupted the router''s configuration.","sentence_zh":"一次固件更新损坏了路由器的配置。","add_node_ids":["corrupt-configuration","firmware-update","router-configuration"],"add_link_ids":["corrupt-configuration->firmware-update","corrupt-configuration->router-configuration"],"focus_node_id":"corrupt-configuration","note_zh":"先明确造成损坏的更新和受损的配置。"},{"step_no":2,"label":"场景","sentence_en":"A firmware update corrupted the router''s configuration during a power outage.","sentence_zh":"一次固件更新在停电期间损坏了路由器的配置。","add_node_ids":["during-outage"],"add_link_ids":["during-outage->corrupt-configuration"],"focus_node_id":"during-outage","note_zh":"补充配置损坏发生时的停电场景。"}]}'
  ),
  (
    'cost-primary',
    'cost',
    'cost',
    'cost the team two days',
    '使团队损失两天时间',
    'The database migration cost the team two days.',
    '这次数据库迁移让团队损失了两天时间。',
    'The database migration cost the team two days of release work because the rollback script failed.',
    '由于回滚脚本失效，这次数据库迁移让团队损失了两天的发布工作时间。',
    'migration-delay',
    '{"schema_version":2,"root_action_id":"cost-team-time","nodes":[{"id":"cost-team-time","text":"cost","kind":"action","label_zh":"使团队付出时间代价"},{"id":"database-migration","text":"The database migration","kind":"core","label_zh":"造成时间损失的数据库迁移"},{"id":"team","text":"the team","kind":"core","label_zh":"承担时间损失的团队"},{"id":"two-days","text":"two days","kind":"core","label_zh":"损失的两天时间"},{"id":"of-release-work","text":"of release work","kind":"modifier","label_zh":"被耽误工作的具体范围"},{"id":"rollback-fail","text":"failed","kind":"action","label_zh":"回滚脚本失效"},{"id":"rollback-script","text":"the rollback script","kind":"core","label_zh":"未能正常工作的回滚脚本"}],"links":[{"id":"cost-team-time->database-migration","from":"cost-team-time","to":"database-migration","kind":"core","relation_type":"actor","label_zh":"数据库迁移造成了这项代价"},{"id":"cost-team-time->team","from":"cost-team-time","to":"team","kind":"core","relation_type":"recipient","label_zh":"团队承受了时间损失"},{"id":"cost-team-time->two-days","from":"cost-team-time","to":"two-days","kind":"core","relation_type":"target","label_zh":"时间代价为两天"},{"id":"of-release-work->two-days","from":"of-release-work","to":"two-days","kind":"modifier","relation_type":"scope","label_zh":"两天损失涉及发布工作"},{"id":"rollback-fail->rollback-script","from":"rollback-fail","to":"rollback-script","kind":"core","relation_type":"actor","label_zh":"失效的是回滚脚本"},{"id":"rollback-fail->cost-team-time","from":"rollback-fail","to":"cost-team-time","kind":"modifier","relation_type":"reason","label_zh":"脚本失效导致团队损失时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The database migration cost the team two days.","sentence_zh":"这次数据库迁移让团队损失了两天时间。","add_node_ids":["cost-team-time","database-migration","team","two-days"],"add_link_ids":["cost-team-time->database-migration","cost-team-time->team","cost-team-time->two-days"],"focus_node_id":"cost-team-time","note_zh":"主干给出造成代价的事项、承担者和时间数额。"},{"step_no":2,"label":"范围","sentence_en":"The database migration cost the team two days of release work.","sentence_zh":"这次数据库迁移让团队损失了两天的发布工作时间。","add_node_ids":["of-release-work"],"add_link_ids":["of-release-work->two-days"],"focus_node_id":"of-release-work","note_zh":"限定损失的两天原本用于哪类工作。"},{"step_no":3,"label":"原因","sentence_en":"The database migration cost the team two days of release work because the rollback script failed.","sentence_zh":"由于回滚脚本失效，这次数据库迁移让团队损失了两天的发布工作时间。","add_node_ids":["rollback-fail","rollback-script"],"add_link_ids":["rollback-fail->rollback-script","rollback-fail->cost-team-time"],"focus_node_id":"rollback-fail","note_zh":"交代这次迁移产生时间代价的技术原因。"}]}'
  ),
  (
    'could-primary',
    'could',
    'could',
    'could postpone the rollout',
    '可以考虑推迟发布',
    'We could postpone the rollout.',
    '我们可以推迟这次发布。',
    'We could postpone the rollout until the vendor fixes the authentication bug.',
    '我们可以把这次发布推迟到供应商修复认证缺陷之后。',
    'rollout-decision',
    '{"schema_version":2,"root_action_id":"could-postpone","nodes":[{"id":"could-postpone","text":"could postpone","kind":"action","label_zh":"可以推迟发布"},{"id":"we","text":"We","kind":"core","label_zh":"可以作出推迟决定的团队"},{"id":"rollout","text":"the rollout","kind":"core","label_zh":"可能被推迟的发布"},{"id":"fix-bug","text":"fixes","kind":"action","label_zh":"修复认证缺陷"},{"id":"vendor","text":"the vendor","kind":"core","label_zh":"负责修复缺陷的供应商"},{"id":"authentication-bug","text":"the authentication bug","kind":"core","label_zh":"需要修复的认证缺陷"}],"links":[{"id":"could-postpone->we","from":"could-postpone","to":"we","kind":"core","relation_type":"actor","label_zh":"团队可以选择推迟"},{"id":"could-postpone->rollout","from":"could-postpone","to":"rollout","kind":"core","relation_type":"target","label_zh":"可能推迟的是本次发布"},{"id":"fix-bug->vendor","from":"fix-bug","to":"vendor","kind":"core","relation_type":"actor","label_zh":"供应商负责修复"},{"id":"fix-bug->authentication-bug","from":"fix-bug","to":"authentication-bug","kind":"core","relation_type":"target","label_zh":"修复对象是认证缺陷"},{"id":"fix-bug->could-postpone","from":"fix-bug","to":"could-postpone","kind":"modifier","relation_type":"time","label_zh":"发布最多推迟到缺陷修复完成时"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We could postpone the rollout.","sentence_zh":"我们可以推迟这次发布。","add_node_ids":["could-postpone","we","rollout"],"add_link_ids":["could-postpone->we","could-postpone->rollout"],"focus_node_id":"could-postpone","note_zh":"could表示这是可以考虑的选择，并非已经确定的安排。"},{"step_no":2,"label":"时间","sentence_en":"We could postpone the rollout until the vendor fixes the authentication bug.","sentence_zh":"我们可以把这次发布推迟到供应商修复认证缺陷之后。","add_node_ids":["fix-bug","vendor","authentication-bug"],"add_link_ids":["fix-bug->vendor","fix-bug->authentication-bug","fix-bug->could-postpone"],"focus_node_id":"fix-bug","note_zh":"用缺陷修复事件确定可能推迟到的时间点。"}]}'
  ),
  (
    'count-primary',
    'count',
    'count',
    'count valid records',
    '统计有效记录的数量',
    'The import job counted the valid records.',
    '导入任务统计了有效记录。',
    'The import job counted the valid records in each batch before it rejected the malformed rows.',
    '导入任务先统计每个批次中的有效记录，再拒绝格式错误的数据行。',
    'data-import',
    '{"schema_version":2,"root_action_id":"count-records","nodes":[{"id":"count-records","text":"counted","kind":"action","label_zh":"统计有效记录"},{"id":"import-job","text":"The import job","kind":"core","label_zh":"执行统计的导入任务"},{"id":"valid-records","text":"the valid records","kind":"core","label_zh":"被统计的有效记录"},{"id":"in-each-batch","text":"in each batch","kind":"modifier","label_zh":"逐批统计的范围"},{"id":"reject-rows","text":"rejected","kind":"action","label_zh":"拒绝格式错误的行"},{"id":"malformed-rows","text":"the malformed rows","kind":"core","label_zh":"随后被拒绝的错误数据行"}],"links":[{"id":"count-records->import-job","from":"count-records","to":"import-job","kind":"core","relation_type":"actor","label_zh":"导入任务执行记录统计"},{"id":"count-records->valid-records","from":"count-records","to":"valid-records","kind":"core","relation_type":"target","label_zh":"统计对象是有效记录"},{"id":"in-each-batch->count-records","from":"in-each-batch","to":"count-records","kind":"modifier","relation_type":"scope","label_zh":"统计在每个批次内分别进行"},{"id":"reject-rows->import-job","from":"reject-rows","to":"import-job","kind":"core","relation_type":"shared_actor","label_zh":"同一导入任务执行拒绝处理"},{"id":"reject-rows->malformed-rows","from":"reject-rows","to":"malformed-rows","kind":"core","relation_type":"target","label_zh":"被拒绝的是格式错误的数据行"},{"id":"reject-rows->count-records","from":"reject-rows","to":"count-records","kind":"modifier","relation_type":"sequence","label_zh":"统计有效记录先于拒绝错误数据"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The import job counted the valid records.","sentence_zh":"导入任务统计了有效记录。","add_node_ids":["count-records","import-job","valid-records"],"add_link_ids":["count-records->import-job","count-records->valid-records"],"focus_node_id":"count-records","note_zh":"先说明导入任务统计了哪类记录。"},{"step_no":2,"label":"范围","sentence_en":"The import job counted the valid records in each batch.","sentence_zh":"导入任务统计了每个批次中的有效记录。","add_node_ids":["in-each-batch"],"add_link_ids":["in-each-batch->count-records"],"focus_node_id":"in-each-batch","note_zh":"补充统计按批次分别进行。"},{"step_no":3,"label":"顺序","sentence_en":"The import job counted the valid records in each batch before it rejected the malformed rows.","sentence_zh":"导入任务先统计每个批次中的有效记录，再拒绝格式错误的数据行。","add_node_ids":["reject-rows","malformed-rows"],"add_link_ids":["reject-rows->import-job","reject-rows->malformed-rows","reject-rows->count-records"],"focus_node_id":"reject-rows","note_zh":"加入后续处理，明确统计与拒绝的先后顺序。"}]}'
  ),
  (
    'count-on-primary',
    'count-on',
    'count on',
    'count on Priya',
    '相信并依靠Priya完成任务',
    'You can count on Priya.',
    '你可以依靠Priya。',
    'You can count on Priya to monitor the deployment while you handle customer updates.',
    '在你处理客户更新时，可以依靠Priya监控部署过程。',
    'deployment-support',
    '{"schema_version":2,"root_action_id":"count-on-priya","nodes":[{"id":"count-on-priya","text":"can count on","kind":"action","label_zh":"可以依靠Priya"},{"id":"you","text":"You","kind":"core","label_zh":"需要获得协助的人"},{"id":"priya","text":"Priya","kind":"core","label_zh":"值得依靠的同事"},{"id":"monitor-deployment","text":"monitor","kind":"action","label_zh":"监控部署过程"},{"id":"deployment","text":"the deployment","kind":"core","label_zh":"Priya负责监控的部署"},{"id":"handle-updates","text":"handle","kind":"action","label_zh":"处理客户更新"},{"id":"customer-updates","text":"customer updates","kind":"core","label_zh":"由另一人处理的客户更新"}],"links":[{"id":"count-on-priya->you","from":"count-on-priya","to":"you","kind":"core","relation_type":"actor","label_zh":"你可以依靠同事协助"},{"id":"count-on-priya->priya","from":"count-on-priya","to":"priya","kind":"core","relation_type":"target","label_zh":"依靠的人是Priya"},{"id":"count-on-priya->monitor-deployment","from":"count-on-priya","to":"monitor-deployment","kind":"core","relation_type":"nested_action","label_zh":"所依靠的具体事项是监控部署"},{"id":"monitor-deployment->priya","from":"monitor-deployment","to":"priya","kind":"core","relation_type":"shared_actor","label_zh":"Priya承担部署监控"},{"id":"monitor-deployment->deployment","from":"monitor-deployment","to":"deployment","kind":"core","relation_type":"target","label_zh":"监控对象是部署过程"},{"id":"handle-updates->you","from":"handle-updates","to":"you","kind":"core","relation_type":"shared_actor","label_zh":"你同时负责客户更新"},{"id":"handle-updates->customer-updates","from":"handle-updates","to":"customer-updates","kind":"core","relation_type":"target","label_zh":"处理对象是客户更新"},{"id":"handle-updates->monitor-deployment","from":"handle-updates","to":"monitor-deployment","kind":"modifier","relation_type":"time","label_zh":"两项工作在同一时段并行进行"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"You can count on Priya.","sentence_zh":"你可以依靠Priya。","add_node_ids":["count-on-priya","you","priya"],"add_link_ids":["count-on-priya->you","count-on-priya->priya"],"focus_node_id":"count-on-priya","note_zh":"先表达Priya是可以信赖和依靠的人。"},{"step_no":2,"label":"对象细节","sentence_en":"You can count on Priya to monitor the deployment.","sentence_zh":"你可以依靠Priya监控部署过程。","add_node_ids":["monitor-deployment","deployment"],"add_link_ids":["count-on-priya->monitor-deployment","monitor-deployment->priya","monitor-deployment->deployment"],"focus_node_id":"monitor-deployment","note_zh":"说明希望Priya具体承担什么工作。"},{"step_no":3,"label":"时间","sentence_en":"You can count on Priya to monitor the deployment while you handle customer updates.","sentence_zh":"在你处理客户更新时，可以依靠Priya监控部署过程。","add_node_ids":["handle-updates","customer-updates"],"add_link_ids":["handle-updates->you","handle-updates->customer-updates","handle-updates->monitor-deployment"],"focus_node_id":"handle-updates","note_zh":"补充两人同时承担的不同工作。"}]}'
  ),
  (
    'cover-primary',
    'cover',
    'cover',
    'cover payment failures',
    '覆盖支付失败的测试场景',
    'The new integration tests cover payment failures.',
    '新的集成测试覆盖了支付失败情况。',
    'The new integration tests cover payment failures in the mobile checkout flow across three retry scenarios.',
    '新的集成测试覆盖了移动结账流程中三种重试场景下的支付失败情况。',
    'checkout-testing',
    '{"schema_version":2,"root_action_id":"cover-failures","nodes":[{"id":"cover-failures","text":"cover","kind":"action","label_zh":"测试覆盖支付失败"},{"id":"integration-tests","text":"The new integration tests","kind":"core","label_zh":"提供覆盖的新集成测试"},{"id":"payment-failures","text":"payment failures","kind":"core","label_zh":"测试覆盖的支付失败情况"},{"id":"in-mobile-flow","text":"in the mobile checkout flow","kind":"modifier","label_zh":"支付失败出现的流程位置"},{"id":"across-scenarios","text":"across three retry scenarios","kind":"modifier","label_zh":"覆盖到的三种重试场景"}],"links":[{"id":"cover-failures->integration-tests","from":"cover-failures","to":"integration-tests","kind":"core","relation_type":"actor","label_zh":"新集成测试提供场景覆盖"},{"id":"cover-failures->payment-failures","from":"cover-failures","to":"payment-failures","kind":"core","relation_type":"target","label_zh":"覆盖对象是支付失败情况"},{"id":"in-mobile-flow->payment-failures","from":"in-mobile-flow","to":"payment-failures","kind":"modifier","relation_type":"place","label_zh":"这些失败出现在移动结账流程中"},{"id":"across-scenarios->cover-failures","from":"across-scenarios","to":"cover-failures","kind":"modifier","relation_type":"scope","label_zh":"覆盖范围包含三种重试场景"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The new integration tests cover payment failures.","sentence_zh":"新的集成测试覆盖了支付失败情况。","add_node_ids":["cover-failures","integration-tests","payment-failures"],"add_link_ids":["cover-failures->integration-tests","cover-failures->payment-failures"],"focus_node_id":"cover-failures","note_zh":"先说明新增测试覆盖的主要问题。"},{"step_no":2,"label":"场景","sentence_en":"The new integration tests cover payment failures in the mobile checkout flow.","sentence_zh":"新的集成测试覆盖了移动结账流程中的支付失败情况。","add_node_ids":["in-mobile-flow"],"add_link_ids":["in-mobile-flow->payment-failures"],"focus_node_id":"in-mobile-flow","note_zh":"定位支付失败出现的具体流程。"},{"step_no":3,"label":"范围","sentence_en":"The new integration tests cover payment failures in the mobile checkout flow across three retry scenarios.","sentence_zh":"新的集成测试覆盖了移动结账流程中三种重试场景下的支付失败情况。","add_node_ids":["across-scenarios"],"add_link_ids":["across-scenarios->cover-failures"],"focus_node_id":"across-scenarios","note_zh":"进一步给出测试覆盖的场景数量和范围。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'cover-for-primary',
    'cover-for',
    'cover for',
    'cover for a colleague',
    '临时代替同事承担工作',
    'Leo covered for Nina.',
    'Leo临时代替了Nina。',
    'Leo covered for Nina while Nina investigated a production alert.',
    'Nina调查一条生产环境警报时，Leo临时代替了她。',
    'on-call-shift',
    '{"schema_version":2,"root_action_id":"cover-for-nina","nodes":[{"id":"cover-for-nina","text":"covered for","kind":"action","label_zh":"临时代替Nina值班"},{"id":"leo","text":"Leo","kind":"core","label_zh":"代替同事工作的Leo"},{"id":"nina","text":"Nina","kind":"core","label_zh":"工作被临时代替的同事"},{"id":"investigate-alert","text":"investigated","kind":"action","label_zh":"调查生产环境警报"},{"id":"production-alert","text":"a production alert","kind":"core","label_zh":"Nina调查的生产警报"}],"links":[{"id":"cover-for-nina->leo","from":"cover-for-nina","to":"leo","kind":"core","relation_type":"actor","label_zh":"Leo承担临时代班"},{"id":"cover-for-nina->nina","from":"cover-for-nina","to":"nina","kind":"core","relation_type":"target","label_zh":"Leo代替的是Nina"},{"id":"investigate-alert->nina","from":"investigate-alert","to":"nina","kind":"core","relation_type":"actor","label_zh":"Nina负责调查警报"},{"id":"investigate-alert->production-alert","from":"investigate-alert","to":"production-alert","kind":"core","relation_type":"target","label_zh":"调查对象是生产环境警报"},{"id":"investigate-alert->cover-for-nina","from":"investigate-alert","to":"cover-for-nina","kind":"modifier","relation_type":"time","label_zh":"Leo在Nina调查警报期间代班"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Leo covered for Nina.","sentence_zh":"Leo临时代替了Nina。","add_node_ids":["cover-for-nina","leo","nina"],"add_link_ids":["cover-for-nina->leo","cover-for-nina->nina"],"focus_node_id":"cover-for-nina","note_zh":"主干表达Leo临时代替Nina承担工作。"},{"step_no":2,"label":"时间","sentence_en":"Leo covered for Nina while Nina investigated a production alert.","sentence_zh":"Nina调查一条生产环境警报时，Leo临时代替了她。","add_node_ids":["investigate-alert","production-alert"],"add_link_ids":["investigate-alert->nina","investigate-alert->production-alert","investigate-alert->cover-for-nina"],"focus_node_id":"investigate-alert","note_zh":"说明Nina因处理什么事情而需要Leo代班。"}]}'
  ),
  (
    'crack-down-primary',
    'crack-down',
    'crack down',
    'crack down on fake reviews',
    '严厉整治虚假评论',
    'The platform cracked down on fake reviews.',
    '该平台严厉整治了虚假评论。',
    'The platform cracked down on fake reviews by requiring verified purchase records.',
    '该平台通过要求提供已验证的购买记录来严厉整治虚假评论。',
    'review-enforcement',
    '{"schema_version":2,"root_action_id":"crack-down-reviews","nodes":[{"id":"crack-down-reviews","text":"cracked down","kind":"action","label_zh":"严厉整治虚假评论"},{"id":"platform","text":"The platform","kind":"core","label_zh":"实施整治的平台"},{"id":"fake-reviews","text":"fake reviews","kind":"core","label_zh":"受到整治的虚假评论"},{"id":"require-records","text":"requiring","kind":"action","label_zh":"要求提供购买记录"},{"id":"verified-records","text":"verified purchase records","kind":"core","label_zh":"必须提供的已验证购买记录"}],"links":[{"id":"crack-down-reviews->platform","from":"crack-down-reviews","to":"platform","kind":"core","relation_type":"actor","label_zh":"平台实施严格整治"},{"id":"crack-down-reviews->fake-reviews","from":"crack-down-reviews","to":"fake-reviews","kind":"core","relation_type":"target","label_zh":"整治对象是虚假评论"},{"id":"require-records->platform","from":"require-records","to":"platform","kind":"core","relation_type":"shared_actor","label_zh":"平台同时提出记录要求"},{"id":"require-records->verified-records","from":"require-records","to":"verified-records","kind":"core","relation_type":"target","label_zh":"平台要求提供已验证的购买记录"},{"id":"require-records->crack-down-reviews","from":"require-records","to":"crack-down-reviews","kind":"modifier","relation_type":"manner","label_zh":"核验购买记录是整治虚假评论的办法"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The platform cracked down on fake reviews.","sentence_zh":"该平台严厉整治了虚假评论。","add_node_ids":["crack-down-reviews","platform","fake-reviews"],"add_link_ids":["crack-down-reviews->platform","crack-down-reviews->fake-reviews"],"focus_node_id":"crack-down-reviews","note_zh":"先呈现平台严格处理虚假评论的核心信息。"},{"step_no":2,"label":"方式","sentence_en":"The platform cracked down on fake reviews by requiring verified purchase records.","sentence_zh":"该平台通过要求提供已验证的购买记录来严厉整治虚假评论。","add_node_ids":["require-records","verified-records"],"add_link_ids":["require-records->platform","require-records->verified-records","require-records->crack-down-reviews"],"focus_node_id":"require-records","note_zh":"补充平台落实整治措施的具体方式。"}]}'
  ),
  (
    'craft-primary',
    'craft',
    'craft',
    'craft an incident summary',
    '精心撰写事故总结',
    'Elena crafted a concise incident summary.',
    'Elena精心撰写了一份简明的事故总结。',
    'Elena crafted a concise incident summary for executives after the recovery was complete.',
    '恢复工作完成后，Elena为管理层精心撰写了一份简明的事故总结。',
    'incident-report',
    '{"schema_version":2,"root_action_id":"craft-summary","nodes":[{"id":"craft-summary","text":"crafted","kind":"action","label_zh":"精心撰写事故总结"},{"id":"elena","text":"Elena","kind":"core","label_zh":"撰写总结的Elena"},{"id":"incident-summary","text":"a concise incident summary","kind":"core","label_zh":"精心整理的简明事故总结"},{"id":"executives","text":"executives","kind":"core","label_zh":"事故总结的阅读对象"},{"id":"recovery-complete","text":"was complete","kind":"action","label_zh":"恢复工作已经完成"},{"id":"recovery","text":"the recovery","kind":"core","label_zh":"事故后的恢复工作"}],"links":[{"id":"craft-summary->elena","from":"craft-summary","to":"elena","kind":"core","relation_type":"actor","label_zh":"Elena负责精心撰写"},{"id":"craft-summary->incident-summary","from":"craft-summary","to":"incident-summary","kind":"core","relation_type":"target","label_zh":"撰写成果是简明事故总结"},{"id":"craft-summary->executives","from":"craft-summary","to":"executives","kind":"core","relation_type":"recipient","label_zh":"总结提供给管理层阅读"},{"id":"recovery-complete->recovery","from":"recovery-complete","to":"recovery","kind":"core","relation_type":"actor","label_zh":"已经完成的是恢复工作"},{"id":"recovery-complete->craft-summary","from":"recovery-complete","to":"craft-summary","kind":"modifier","relation_type":"time","label_zh":"总结在恢复工作完成后撰写"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Elena crafted a concise incident summary.","sentence_zh":"Elena精心撰写了一份简明的事故总结。","add_node_ids":["craft-summary","elena","incident-summary"],"add_link_ids":["craft-summary->elena","craft-summary->incident-summary"],"focus_node_id":"craft-summary","note_zh":"crafted强调总结经过认真组织和打磨。"},{"step_no":2,"label":"对象细节","sentence_en":"Elena crafted a concise incident summary for executives.","sentence_zh":"Elena为管理层精心撰写了一份简明的事故总结。","add_node_ids":["executives"],"add_link_ids":["craft-summary->executives"],"focus_node_id":"executives","note_zh":"补充这份总结面向的阅读人群。"},{"step_no":3,"label":"时间","sentence_en":"Elena crafted a concise incident summary for executives after the recovery was complete.","sentence_zh":"恢复工作完成后，Elena为管理层精心撰写了一份简明的事故总结。","add_node_ids":["recovery-complete","recovery"],"add_link_ids":["recovery-complete->recovery","recovery-complete->craft-summary"],"focus_node_id":"recovery-complete","note_zh":"说明事故总结是在恢复结束后形成的。"}]}'
  ),
  (
    'crash-primary',
    'crash',
    'crash',
    'crash under a bad filter',
    '因程序故障而崩溃',
    'The analytics dashboard crashed.',
    '分析仪表盘崩溃了。',
    'The analytics dashboard crashed when a malformed filter exhausted the browser''s memory.',
    '一个格式错误的筛选条件耗尽浏览器内存时，分析仪表盘崩溃了。',
    'dashboard-crash',
    '{"schema_version":2,"root_action_id":"dashboard-crash","nodes":[{"id":"dashboard-crash","text":"crashed","kind":"action","label_zh":"分析仪表盘崩溃"},{"id":"analytics-dashboard","text":"The analytics dashboard","kind":"core","label_zh":"发生崩溃的分析仪表盘"},{"id":"exhaust-memory","text":"exhausted","kind":"action","label_zh":"耗尽浏览器内存"},{"id":"malformed-filter","text":"a malformed filter","kind":"core","label_zh":"导致内存耗尽的错误筛选条件"},{"id":"browser-memory","text":"the browser''s memory","kind":"core","label_zh":"被耗尽的浏览器内存"}],"links":[{"id":"dashboard-crash->analytics-dashboard","from":"dashboard-crash","to":"analytics-dashboard","kind":"core","relation_type":"actor","label_zh":"分析仪表盘发生崩溃"},{"id":"exhaust-memory->malformed-filter","from":"exhaust-memory","to":"malformed-filter","kind":"core","relation_type":"actor","label_zh":"错误筛选条件耗尽了内存"},{"id":"exhaust-memory->browser-memory","from":"exhaust-memory","to":"browser-memory","kind":"core","relation_type":"target","label_zh":"被耗尽的是浏览器内存"},{"id":"exhaust-memory->dashboard-crash","from":"exhaust-memory","to":"dashboard-crash","kind":"modifier","relation_type":"time","label_zh":"内存耗尽时仪表盘随即崩溃"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The analytics dashboard crashed.","sentence_zh":"分析仪表盘崩溃了。","add_node_ids":["dashboard-crash","analytics-dashboard"],"add_link_ids":["dashboard-crash->analytics-dashboard"],"focus_node_id":"dashboard-crash","note_zh":"先给出仪表盘停止正常工作的结果。"},{"step_no":2,"label":"原因","sentence_en":"The analytics dashboard crashed when a malformed filter exhausted the browser''s memory.","sentence_zh":"一个格式错误的筛选条件耗尽浏览器内存时，分析仪表盘崩溃了。","add_node_ids":["exhaust-memory","malformed-filter","browser-memory"],"add_link_ids":["exhaust-memory->malformed-filter","exhaust-memory->browser-memory","exhaust-memory->dashboard-crash"],"focus_node_id":"exhaust-memory","note_zh":"加入导致崩溃的内存耗尽事件。"}]}'
  ),
  (
    'crawl-primary',
    'crawl',
    'crawl',
    'crawl a documentation site',
    '自动爬取文档网站',
    'The indexing bot crawled the documentation site.',
    '索引程序爬取了文档网站。',
    'The indexing bot crawled the documentation site overnight without exceeding the rate limit.',
    '索引程序整夜爬取文档网站，同时没有超过请求速率限制。',
    'site-indexing',
    '{"schema_version":2,"root_action_id":"crawl-site","nodes":[{"id":"crawl-site","text":"crawled","kind":"action","label_zh":"爬取文档网站"},{"id":"indexing-bot","text":"The indexing bot","kind":"core","label_zh":"执行网站爬取的索引程序"},{"id":"documentation-site","text":"the documentation site","kind":"core","label_zh":"被爬取的文档网站"},{"id":"overnight","text":"overnight","kind":"modifier","label_zh":"爬取持续的时间"},{"id":"exceed-limit","text":"exceeding","kind":"action","label_zh":"超过请求速率限制"},{"id":"rate-limit","text":"the rate limit","kind":"core","label_zh":"爬取程序遵守的速率上限"}],"links":[{"id":"crawl-site->indexing-bot","from":"crawl-site","to":"indexing-bot","kind":"core","relation_type":"actor","label_zh":"索引程序执行网站爬取"},{"id":"crawl-site->documentation-site","from":"crawl-site","to":"documentation-site","kind":"core","relation_type":"target","label_zh":"爬取对象是文档网站"},{"id":"overnight->crawl-site","from":"overnight","to":"crawl-site","kind":"modifier","relation_type":"time","label_zh":"爬取在夜间持续进行"},{"id":"exceed-limit->indexing-bot","from":"exceed-limit","to":"indexing-bot","kind":"core","relation_type":"shared_actor","label_zh":"索引程序是可能触及限制的一方"},{"id":"exceed-limit->rate-limit","from":"exceed-limit","to":"rate-limit","kind":"core","relation_type":"target","label_zh":"不能超过的是请求速率上限"},{"id":"exceed-limit->crawl-site","from":"exceed-limit","to":"crawl-site","kind":"modifier","relation_type":"condition","label_zh":"整个爬取过程始终没有超过速率限制"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The indexing bot crawled the documentation site.","sentence_zh":"索引程序爬取了文档网站。","add_node_ids":["crawl-site","indexing-bot","documentation-site"],"add_link_ids":["crawl-site->indexing-bot","crawl-site->documentation-site"],"focus_node_id":"crawl-site","note_zh":"主干交代哪个程序爬取了哪个网站。"},{"step_no":2,"label":"时间","sentence_en":"The indexing bot crawled the documentation site overnight.","sentence_zh":"索引程序整夜爬取了文档网站。","add_node_ids":["overnight"],"add_link_ids":["overnight->crawl-site"],"focus_node_id":"overnight","note_zh":"补充爬取任务持续运行的时段。"},{"step_no":3,"label":"条件","sentence_en":"The indexing bot crawled the documentation site overnight without exceeding the rate limit.","sentence_zh":"索引程序整夜爬取文档网站，同时没有超过请求速率限制。","add_node_ids":["exceed-limit","rate-limit"],"add_link_ids":["exceed-limit->indexing-bot","exceed-limit->rate-limit","exceed-limit->crawl-site"],"focus_node_id":"exceed-limit","note_zh":"说明爬取过程中始终遵守速率限制。"}]}'
  ),
  (
    'criticize-primary',
    'criticize',
    'criticize',
    'criticize a proposal',
    '指出并批评方案的问题',
    'The security lead criticized the proposal.',
    '安全负责人批评了这份方案。',
    'The security lead criticized the proposal because the proposed design would expose API keys to client-side code.',
    '安全负责人批评了这份方案，因为其中的设计会让客户端代码接触到API密钥。',
    'security-review',
    '{"schema_version":2,"root_action_id":"criticize-proposal","nodes":[{"id":"criticize-proposal","text":"criticized","kind":"action","label_zh":"批评存在风险的方案"},{"id":"security-lead","text":"The security lead","kind":"core","label_zh":"提出批评的安全负责人"},{"id":"proposal","text":"the proposal","kind":"core","label_zh":"受到批评的方案"},{"id":"expose-keys","text":"would expose","kind":"action","label_zh":"会使API密钥暴露"},{"id":"proposed-design","text":"the proposed design","kind":"core","label_zh":"存在暴露风险的设计"},{"id":"api-keys","text":"API keys","kind":"core","label_zh":"可能被暴露的API密钥"},{"id":"client-side-code","text":"client-side code","kind":"core","label_zh":"会接触密钥的客户端代码"}],"links":[{"id":"criticize-proposal->security-lead","from":"criticize-proposal","to":"security-lead","kind":"core","relation_type":"actor","label_zh":"安全负责人提出批评"},{"id":"criticize-proposal->proposal","from":"criticize-proposal","to":"proposal","kind":"core","relation_type":"target","label_zh":"被批评的是这份方案"},{"id":"expose-keys->proposed-design","from":"expose-keys","to":"proposed-design","kind":"core","relation_type":"actor","label_zh":"方案中的设计会造成暴露"},{"id":"expose-keys->api-keys","from":"expose-keys","to":"api-keys","kind":"core","relation_type":"target","label_zh":"可能暴露的是API密钥"},{"id":"expose-keys->client-side-code","from":"expose-keys","to":"client-side-code","kind":"core","relation_type":"recipient","label_zh":"客户端代码将能够接触密钥"},{"id":"expose-keys->criticize-proposal","from":"expose-keys","to":"criticize-proposal","kind":"modifier","relation_type":"reason","label_zh":"密钥暴露风险是批评该方案的原因"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The security lead criticized the proposal.","sentence_zh":"安全负责人批评了这份方案。","add_node_ids":["criticize-proposal","security-lead","proposal"],"add_link_ids":["criticize-proposal->security-lead","criticize-proposal->proposal"],"focus_node_id":"criticize-proposal","note_zh":"先明确谁对哪份方案提出了批评。"},{"step_no":2,"label":"原因","sentence_en":"The security lead criticized the proposal because the proposed design would expose API keys to client-side code.","sentence_zh":"安全负责人批评了这份方案，因为其中的设计会让客户端代码接触到API密钥。","add_node_ids":["expose-keys","proposed-design","api-keys","client-side-code"],"add_link_ids":["expose-keys->proposed-design","expose-keys->api-keys","expose-keys->client-side-code","expose-keys->criticize-proposal"],"focus_node_id":"expose-keys","note_zh":"具体说明方案为何受到安全负责人的批评。"}]}'
  ),
  (
    'cross-primary',
    'cross',
    'cross',
    'cross the bridge',
    '从桥的一端穿过到另一端',
    'The delivery van crossed the bridge.',
    '送货车驶过了桥梁。',
    'The delivery van crossed the bridge before the storm reached the harbor.',
    '送货车在风暴抵达港口前驶过了桥梁。',
    'storm-delivery',
    '{"schema_version":2,"root_action_id":"cross-bridge","nodes":[{"id":"cross-bridge","text":"crossed","kind":"action","label_zh":"驶过桥梁"},{"id":"delivery-van","text":"The delivery van","kind":"core","label_zh":"驶过桥梁的送货车"},{"id":"bridge","text":"the bridge","kind":"core","label_zh":"送货车穿过的桥梁"},{"id":"reach-harbor","text":"reached","kind":"action","label_zh":"风暴抵达港口"},{"id":"storm","text":"the storm","kind":"core","label_zh":"正在接近港口的风暴"},{"id":"harbor","text":"the harbor","kind":"core","label_zh":"风暴即将抵达的港口"}],"links":[{"id":"cross-bridge->delivery-van","from":"cross-bridge","to":"delivery-van","kind":"core","relation_type":"actor","label_zh":"送货车执行过桥行程"},{"id":"cross-bridge->bridge","from":"cross-bridge","to":"bridge","kind":"core","relation_type":"target","label_zh":"车辆穿过的是这座桥"},{"id":"reach-harbor->storm","from":"reach-harbor","to":"storm","kind":"core","relation_type":"actor","label_zh":"风暴向港口抵达"},{"id":"reach-harbor->harbor","from":"reach-harbor","to":"harbor","kind":"core","relation_type":"target","label_zh":"风暴抵达的地点是港口"},{"id":"reach-harbor->cross-bridge","from":"reach-harbor","to":"cross-bridge","kind":"modifier","relation_type":"time","label_zh":"送货车在风暴抵达港口前过桥"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The delivery van crossed the bridge.","sentence_zh":"送货车驶过了桥梁。","add_node_ids":["cross-bridge","delivery-van","bridge"],"add_link_ids":["cross-bridge->delivery-van","cross-bridge->bridge"],"focus_node_id":"cross-bridge","note_zh":"主干呈现车辆穿过桥梁的移动。"},{"step_no":2,"label":"时间","sentence_en":"The delivery van crossed the bridge before the storm reached the harbor.","sentence_zh":"送货车在风暴抵达港口前驶过了桥梁。","add_node_ids":["reach-harbor","storm","harbor"],"add_link_ids":["reach-harbor->storm","reach-harbor->harbor","reach-harbor->cross-bridge"],"focus_node_id":"reach-harbor","note_zh":"用风暴抵达港口的事件限定过桥时间。"}]}'
  ),
  (
    'cross-sell-primary',
    'cross-sell',
    'cross-sell',
    'cross-sell cloud backup',
    '向购买相关产品的顾客追加销售云备份',
    'The checkout flow cross-sells cloud backup.',
    '结账流程追加销售云备份服务。',
    'The checkout flow cross-sells cloud backup to laptop buyers on the confirmation page.',
    '结账流程在确认页面上向笔记本买家追加销售云备份服务。',
    'checkout-offer',
    '{"schema_version":2,"root_action_id":"cross-sell-backup","nodes":[{"id":"cross-sell-backup","text":"cross-sells","kind":"action","label_zh":"追加销售云备份"},{"id":"checkout-flow","text":"The checkout flow","kind":"core","label_zh":"展示追加产品的结账流程"},{"id":"cloud-backup","text":"cloud backup","kind":"core","label_zh":"被追加推荐的云备份服务"},{"id":"laptop-buyers","text":"laptop buyers","kind":"core","label_zh":"收到追加推荐的笔记本买家"},{"id":"on-confirmation-page","text":"on the confirmation page","kind":"modifier","label_zh":"云备份推荐出现的页面"}],"links":[{"id":"cross-sell-backup->checkout-flow","from":"cross-sell-backup","to":"checkout-flow","kind":"core","relation_type":"actor","label_zh":"结账流程执行追加推荐"},{"id":"cross-sell-backup->cloud-backup","from":"cross-sell-backup","to":"cloud-backup","kind":"core","relation_type":"target","label_zh":"追加销售的产品是云备份"},{"id":"cross-sell-backup->laptop-buyers","from":"cross-sell-backup","to":"laptop-buyers","kind":"core","relation_type":"recipient","label_zh":"追加推荐面向笔记本买家"},{"id":"on-confirmation-page->cross-sell-backup","from":"on-confirmation-page","to":"cross-sell-backup","kind":"modifier","relation_type":"place","label_zh":"推荐展示在确认页面上"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The checkout flow cross-sells cloud backup.","sentence_zh":"结账流程追加销售云备份服务。","add_node_ids":["cross-sell-backup","checkout-flow","cloud-backup"],"add_link_ids":["cross-sell-backup->checkout-flow","cross-sell-backup->cloud-backup"],"focus_node_id":"cross-sell-backup","note_zh":"先说明结账流程追加推荐的产品。"},{"step_no":2,"label":"对象细节","sentence_en":"The checkout flow cross-sells cloud backup to laptop buyers.","sentence_zh":"结账流程向笔记本买家追加销售云备份服务。","add_node_ids":["laptop-buyers"],"add_link_ids":["cross-sell-backup->laptop-buyers"],"focus_node_id":"laptop-buyers","note_zh":"加入收到这项追加推荐的顾客群体。"},{"step_no":3,"label":"场景","sentence_en":"The checkout flow cross-sells cloud backup to laptop buyers on the confirmation page.","sentence_zh":"结账流程在确认页面上向笔记本买家追加销售云备份服务。","add_node_ids":["on-confirmation-page"],"add_link_ids":["on-confirmation-page->cross-sell-backup"],"focus_node_id":"on-confirmation-page","note_zh":"指出追加销售内容在结账流程中的展示位置。"}]}'
  ),
  (
    'cry-primary',
    'cry',
    'cry',
    'cry when a toy goes missing',
    '因难过而哭泣',
    'The toddler cried.',
    '幼儿哭了起来。',
    'The toddler cried in the airport lounge when her favorite toy went missing.',
    '幼儿最喜欢的玩具不见时，她在机场休息室里哭了起来。',
    'airport-lounge',
    '{"schema_version":2,"root_action_id":"toddler-cry","nodes":[{"id":"toddler-cry","text":"cried","kind":"action","label_zh":"幼儿哭了起来"},{"id":"toddler","text":"The toddler","kind":"core","label_zh":"正在哭泣的幼儿"},{"id":"in-airport-lounge","text":"in the airport lounge","kind":"modifier","label_zh":"幼儿哭泣的地点"},{"id":"toy-go-missing","text":"went missing","kind":"action","label_zh":"最喜欢的玩具不见了"},{"id":"favorite-toy","text":"her favorite toy","kind":"core","label_zh":"幼儿最喜欢却不见了的玩具"}],"links":[{"id":"toddler-cry->toddler","from":"toddler-cry","to":"toddler","kind":"core","relation_type":"actor","label_zh":"哭泣的是这名幼儿"},{"id":"in-airport-lounge->toddler-cry","from":"in-airport-lounge","to":"toddler-cry","kind":"modifier","relation_type":"place","label_zh":"哭泣发生在机场休息室"},{"id":"toy-go-missing->favorite-toy","from":"toy-go-missing","to":"favorite-toy","kind":"core","relation_type":"actor","label_zh":"不见的是她最喜欢的玩具"},{"id":"toy-go-missing->toddler-cry","from":"toy-go-missing","to":"toddler-cry","kind":"modifier","relation_type":"reason","label_zh":"玩具不见引发了幼儿哭泣"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The toddler cried.","sentence_zh":"幼儿哭了起来。","add_node_ids":["toddler-cry","toddler"],"add_link_ids":["toddler-cry->toddler"],"focus_node_id":"toddler-cry","note_zh":"先呈现幼儿哭泣这一核心情形。"},{"step_no":2,"label":"场景","sentence_en":"The toddler cried in the airport lounge.","sentence_zh":"幼儿在机场休息室里哭了起来。","add_node_ids":["in-airport-lounge"],"add_link_ids":["in-airport-lounge->toddler-cry"],"focus_node_id":"in-airport-lounge","note_zh":"补充哭泣发生的具体地点。"},{"step_no":3,"label":"原因","sentence_en":"The toddler cried in the airport lounge when her favorite toy went missing.","sentence_zh":"幼儿最喜欢的玩具不见时，她在机场休息室里哭了起来。","add_node_ids":["toy-go-missing","favorite-toy"],"add_link_ids":["toy-go-missing->favorite-toy","toy-go-missing->toddler-cry"],"focus_node_id":"toy-go-missing","note_zh":"最后说明幼儿为何突然哭泣。"}]}'
  ),
  (
    'cure-primary',
    'cure',
    'cure',
    'cure a login delay',
    '彻底解决登录延迟问题',
    'The patch cured the login delay.',
    '这个补丁解决了登录延迟问题。',
    'The patch cured the login delay by removing a redundant database lookup.',
    '这个补丁通过移除一次多余的数据库查询，解决了登录延迟问题。',
    'login-performance',
    '{"schema_version":2,"root_action_id":"cure-delay","nodes":[{"id":"cure-delay","text":"cured","kind":"action","label_zh":"解决登录延迟"},{"id":"patch","text":"The patch","kind":"core","label_zh":"解决问题的代码补丁"},{"id":"login-delay","text":"the login delay","kind":"core","label_zh":"被解决的登录延迟问题"},{"id":"remove-lookup","text":"removing","kind":"action","label_zh":"移除多余的数据库查询"},{"id":"redundant-lookup","text":"a redundant database lookup","kind":"core","label_zh":"被移除的多余数据库查询"}],"links":[{"id":"cure-delay->patch","from":"cure-delay","to":"patch","kind":"core","relation_type":"actor","label_zh":"代码补丁解决了延迟"},{"id":"cure-delay->login-delay","from":"cure-delay","to":"login-delay","kind":"core","relation_type":"target","label_zh":"被解决的是登录延迟"},{"id":"remove-lookup->patch","from":"remove-lookup","to":"patch","kind":"core","relation_type":"shared_actor","label_zh":"该补丁负责移除查询"},{"id":"remove-lookup->redundant-lookup","from":"remove-lookup","to":"redundant-lookup","kind":"core","relation_type":"target","label_zh":"移除对象是多余的数据库查询"},{"id":"remove-lookup->cure-delay","from":"remove-lookup","to":"cure-delay","kind":"modifier","relation_type":"manner","label_zh":"移除多余查询是解决延迟的方式"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The patch cured the login delay.","sentence_zh":"这个补丁解决了登录延迟问题。","add_node_ids":["cure-delay","patch","login-delay"],"add_link_ids":["cure-delay->patch","cure-delay->login-delay"],"focus_node_id":"cure-delay","note_zh":"cured在这里表示补丁彻底消除了性能问题。"},{"step_no":2,"label":"方式","sentence_en":"The patch cured the login delay by removing a redundant database lookup.","sentence_zh":"这个补丁通过移除一次多余的数据库查询，解决了登录延迟问题。","add_node_ids":["remove-lookup","redundant-lookup"],"add_link_ids":["remove-lookup->patch","remove-lookup->redundant-lookup","remove-lookup->cure-delay"],"focus_node_id":"remove-lookup","note_zh":"补充补丁解决延迟所采用的具体技术改动。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
