-- Generated verb paths batch batch-008.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'negotiate-primary',
    'negotiate',
    'negotiate',
    'negotiate a support contract',
    '协商支持合同的具体条件',
    'Lena negotiated the support contract.',
    'Lena协商了支持合同。',
    'Lena negotiated the support contract with the vendor before the trial ended.',
    'Lena在试用期结束前与供应商协商了支持合同。',
    'support-renewal',
    '{"schema_version":2,"root_action_id":"negotiate-contract","nodes":[{"id":"negotiate-contract","text":"negotiated","kind":"action","label_zh":"协商支持合同"},{"id":"lena","text":"Lena","kind":"core","label_zh":"负责合同协商的工程经理"},{"id":"support-contract","text":"the support contract","kind":"core","label_zh":"双方讨论的支持合同"},{"id":"with-vendor","text":"with the vendor","kind":"modifier","label_zh":"参与协商的供应商一方"},{"id":"before-trial-ended","text":"before the trial ended","kind":"action","label_zh":"试用期结束"},{"id":"trial","text":"the trial","kind":"core","label_zh":"即将结束的产品试用期"}],"links":[{"id":"negotiate-contract->lena","from":"negotiate-contract","to":"lena","kind":"core","relation_type":"actor","label_zh":"Lena负责推进这次合同协商"},{"id":"negotiate-contract->support-contract","from":"negotiate-contract","to":"support-contract","kind":"core","relation_type":"target","label_zh":"协商围绕支持合同展开"},{"id":"with-vendor->negotiate-contract","from":"with-vendor","to":"negotiate-contract","kind":"modifier","relation_type":"recipient","label_zh":"Lena与供应商进行协商"},{"id":"before-trial-ended->negotiate-contract","from":"before-trial-ended","to":"negotiate-contract","kind":"modifier","relation_type":"time","label_zh":"合同协商赶在试用期结束之前完成"},{"id":"before-trial-ended->trial","from":"before-trial-ended","to":"trial","kind":"core","relation_type":"actor","label_zh":"结束的是当前产品试用期"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Lena negotiated the support contract.","sentence_zh":"Lena协商了支持合同。","add_node_ids":["negotiate-contract","lena","support-contract"],"add_link_ids":["negotiate-contract->lena","negotiate-contract->support-contract"],"focus_node_id":"negotiate-contract","note_zh":"先交代由谁处理哪份合同。"},{"step_no":2,"label":"协商对象","sentence_en":"Lena negotiated the support contract with the vendor.","sentence_zh":"Lena与供应商协商了支持合同。","add_node_ids":["with-vendor"],"add_link_ids":["with-vendor->negotiate-contract"],"focus_node_id":"with-vendor","note_zh":"补充坐在谈判另一边的合作方。"},{"step_no":3,"label":"时间","sentence_en":"Lena negotiated the support contract with the vendor before the trial ended.","sentence_zh":"Lena在试用期结束前与供应商协商了支持合同。","add_node_ids":["before-trial-ended","trial"],"add_link_ids":["before-trial-ended->negotiate-contract","before-trial-ended->trial"],"focus_node_id":"before-trial-ended","note_zh":"用试用期结束这一事件标明协商期限。"}]}'
  ),
  (
    'nest-primary',
    'nest',
    'nest',
    'nest a query inside a loop',
    '把一段查询嵌套在循环结构中',
    'Devon nested the cleanup query.',
    'Devon嵌套了清理查询。',
    'Devon nested the cleanup query inside the batch loop to limit lock time.',
    'Devon把清理查询嵌套在批处理循环中，以缩短锁定时间。',
    'batch-cleanup',
    '{"schema_version":2,"root_action_id":"nest-query","nodes":[{"id":"nest-query","text":"nested","kind":"action","label_zh":"嵌套清理查询"},{"id":"devon","text":"Devon","kind":"core","label_zh":"调整批处理代码的人"},{"id":"cleanup-query","text":"the cleanup query","kind":"core","label_zh":"被放入循环的清理查询"},{"id":"inside-batch-loop","text":"inside the batch loop","kind":"modifier","label_zh":"容纳查询的批处理循环"},{"id":"to-limit-lock-time","text":"to limit lock time","kind":"action","label_zh":"缩短数据库锁定时间"},{"id":"lock-time","text":"lock time","kind":"core","label_zh":"需要控制的数据库锁定时长"}],"links":[{"id":"nest-query->devon","from":"nest-query","to":"devon","kind":"core","relation_type":"actor","label_zh":"Devon完成了查询结构调整"},{"id":"nest-query->cleanup-query","from":"nest-query","to":"cleanup-query","kind":"core","relation_type":"target","label_zh":"清理查询是被嵌套的代码单元"},{"id":"inside-batch-loop->nest-query","from":"inside-batch-loop","to":"nest-query","kind":"modifier","relation_type":"place","label_zh":"查询被放在批处理循环内部"},{"id":"to-limit-lock-time->nest-query","from":"to-limit-lock-time","to":"nest-query","kind":"modifier","relation_type":"purpose","label_zh":"采用嵌套结构是为了控制锁定时长"},{"id":"to-limit-lock-time->lock-time","from":"to-limit-lock-time","to":"lock-time","kind":"core","relation_type":"target","label_zh":"需要缩短的是数据库锁定时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Devon nested the cleanup query.","sentence_zh":"Devon嵌套了清理查询。","add_node_ids":["nest-query","devon","cleanup-query"],"add_link_ids":["nest-query->devon","nest-query->cleanup-query"],"focus_node_id":"nest-query","note_zh":"先呈现发生结构变化的查询。"},{"step_no":2,"label":"场景","sentence_en":"Devon nested the cleanup query inside the batch loop.","sentence_zh":"Devon把清理查询嵌套在批处理循环中。","add_node_ids":["inside-batch-loop"],"add_link_ids":["inside-batch-loop->nest-query"],"focus_node_id":"inside-batch-loop","note_zh":"指出查询进入了哪一层代码结构。"},{"step_no":3,"label":"目的","sentence_en":"Devon nested the cleanup query inside the batch loop to limit lock time.","sentence_zh":"Devon把清理查询嵌套在批处理循环中，以缩短锁定时间。","add_node_ids":["to-limit-lock-time","lock-time"],"add_link_ids":["to-limit-lock-time->nest-query","to-limit-lock-time->lock-time"],"focus_node_id":"to-limit-lock-time","note_zh":"说明这种组织方式要改善的数据库问题。"}]}'
  ),
  (
    'nod-primary',
    'nod',
    'nod',
    'nod at a proposal',
    '点头表示认可某项提议',
    'The architect nodded.',
    '架构师点了点头。',
    'The architect nodded at the proposal after the team explained the trade-offs.',
    '团队说明各项取舍后，架构师对这项提议点头表示认可。',
    'architecture-meeting',
    '{"schema_version":2,"root_action_id":"nod-approval","nodes":[{"id":"nod-approval","text":"nodded","kind":"action","label_zh":"点头表示认可"},{"id":"architect","text":"The architect","kind":"core","label_zh":"作出点头回应的架构师"},{"id":"at-proposal","text":"at the proposal","kind":"modifier","label_zh":"获得认可的拆分方案"},{"id":"after-team-explained","text":"after the team explained the trade-offs","kind":"action","label_zh":"团队说明取舍"},{"id":"team","text":"the team","kind":"core","label_zh":"负责解释方案的团队"},{"id":"trade-offs","text":"the trade-offs","kind":"core","label_zh":"方案涉及的利弊取舍"}],"links":[{"id":"nod-approval->architect","from":"nod-approval","to":"architect","kind":"core","relation_type":"actor","label_zh":"架构师作出了点头动作"},{"id":"at-proposal->nod-approval","from":"at-proposal","to":"nod-approval","kind":"modifier","relation_type":"target","label_zh":"点头回应针对这项提议"},{"id":"after-team-explained->nod-approval","from":"after-team-explained","to":"nod-approval","kind":"modifier","relation_type":"time","label_zh":"架构师在听完取舍说明后点头"},{"id":"after-team-explained->team","from":"after-team-explained","to":"team","kind":"core","relation_type":"actor","label_zh":"团队负责说明方案取舍"},{"id":"after-team-explained->trade-offs","from":"after-team-explained","to":"trade-offs","kind":"core","relation_type":"content","label_zh":"团队解释的是方案的利弊"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The architect nodded.","sentence_zh":"架构师点了点头。","add_node_ids":["nod-approval","architect"],"add_link_ids":["nod-approval->architect"],"focus_node_id":"nod-approval","note_zh":"先显示架构师给出的简短回应。"},{"step_no":2,"label":"对象细节","sentence_en":"The architect nodded at the proposal.","sentence_zh":"架构师对这项提议点头表示认可。","add_node_ids":["at-proposal"],"add_link_ids":["at-proposal->nod-approval"],"focus_node_id":"at-proposal","note_zh":"点明这次认可针对哪项方案。"},{"step_no":3,"label":"时间","sentence_en":"The architect nodded at the proposal after the team explained the trade-offs.","sentence_zh":"团队说明各项取舍后，架构师对这项提议点头表示认可。","add_node_ids":["after-team-explained","team","trade-offs"],"add_link_ids":["after-team-explained->nod-approval","after-team-explained->team","after-team-explained->trade-offs"],"focus_node_id":"after-team-explained","note_zh":"加入促成认可的先行讨论。"}]}'
  ),
  (
    'normalize-primary',
    'normalize',
    'normalize',
    'normalize incoming paths',
    '把输入路径转换为统一格式',
    'The gateway normalizes incoming paths.',
    '网关会规范化传入的路径。',
    'The gateway normalizes incoming paths before matching routes.',
    '网关会先规范化传入的路径，再匹配路由。',
    'request-routing',
    '{"schema_version":2,"root_action_id":"normalize-paths","nodes":[{"id":"normalize-paths","text":"normalizes","kind":"action","label_zh":"统一请求路径格式"},{"id":"gateway","text":"The gateway","kind":"core","label_zh":"执行路径规范化的网关"},{"id":"incoming-paths","text":"incoming paths","kind":"core","label_zh":"进入系统且格式不一的路径"},{"id":"before-matching-routes","text":"before matching routes","kind":"action","label_zh":"匹配路由规则"},{"id":"routes","text":"routes","kind":"core","label_zh":"等待匹配的路由规则"}],"links":[{"id":"normalize-paths->gateway","from":"normalize-paths","to":"gateway","kind":"core","relation_type":"actor","label_zh":"网关负责统一路径写法"},{"id":"normalize-paths->incoming-paths","from":"normalize-paths","to":"incoming-paths","kind":"core","relation_type":"target","label_zh":"传入路径是规范化对象"},{"id":"before-matching-routes->normalize-paths","from":"before-matching-routes","to":"normalize-paths","kind":"modifier","relation_type":"sequence","label_zh":"路径规范化先于路由匹配"},{"id":"before-matching-routes->routes","from":"before-matching-routes","to":"routes","kind":"core","relation_type":"target","label_zh":"后续匹配针对路由规则"},{"id":"before-matching-routes->gateway","from":"before-matching-routes","to":"gateway","kind":"core","relation_type":"shared_actor","label_zh":"执行路由匹配的仍是这个网关"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The gateway normalizes incoming paths.","sentence_zh":"网关会规范化传入的路径。","add_node_ids":["normalize-paths","gateway","incoming-paths"],"add_link_ids":["normalize-paths->gateway","normalize-paths->incoming-paths"],"focus_node_id":"normalize-paths","note_zh":"建立网关统一输入格式的核心过程。"},{"step_no":2,"label":"时间","sentence_en":"The gateway normalizes incoming paths before matching routes.","sentence_zh":"网关会先规范化传入的路径，再匹配路由。","add_node_ids":["before-matching-routes","routes"],"add_link_ids":["before-matching-routes->normalize-paths","before-matching-routes->routes","before-matching-routes->gateway"],"focus_node_id":"before-matching-routes","note_zh":"说明格式统一在路由处理流程中的位置。"}]}'
  ),
  (
    'note-primary',
    'note',
    'note',
    'note a compatibility risk',
    '指出一个需要关注的兼容性风险',
    'Mina noted that the plugin might break.',
    'Mina指出，这个插件可能会出故障。',
    'Mina noted during the upgrade review that the plugin might break on older browsers.',
    'Mina在升级评审期间指出，这个插件在旧版浏览器上可能会出故障。',
    'upgrade-review',
    '{"schema_version":2,"root_action_id":"note-risk","nodes":[{"id":"note-risk","text":"noted","kind":"action","label_zh":"指出兼容性风险"},{"id":"mina","text":"Mina","kind":"core","label_zh":"提出风险的开发者"},{"id":"plugin-might-break","text":"the plugin might break","kind":"action","label_zh":"插件可能无法正常运行"},{"id":"plugin","text":"the plugin","kind":"core","label_zh":"存在兼容风险的插件"},{"id":"on-older-browsers","text":"on older browsers","kind":"modifier","label_zh":"可能出现问题的旧版浏览器范围"},{"id":"during-upgrade-review","text":"during the upgrade review","kind":"modifier","label_zh":"风险被提出的升级评审阶段"}],"links":[{"id":"note-risk->mina","from":"note-risk","to":"mina","kind":"core","relation_type":"actor","label_zh":"Mina提出了这项兼容性提醒"},{"id":"note-risk->plugin-might-break","from":"note-risk","to":"plugin-might-break","kind":"core","relation_type":"content","label_zh":"她指出插件可能出现故障"},{"id":"plugin-might-break->plugin","from":"plugin-might-break","to":"plugin","kind":"core","relation_type":"actor","label_zh":"可能失效的是这个插件"},{"id":"on-older-browsers->plugin-might-break","from":"on-older-browsers","to":"plugin-might-break","kind":"modifier","relation_type":"condition","label_zh":"故障风险限于旧版浏览器环境"},{"id":"during-upgrade-review->note-risk","from":"during-upgrade-review","to":"note-risk","kind":"modifier","relation_type":"time","label_zh":"Mina在升级评审期间提出风险"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Mina noted that the plugin might break.","sentence_zh":"Mina指出，这个插件可能会出故障。","add_node_ids":["note-risk","mina","plugin-might-break","plugin"],"add_link_ids":["note-risk->mina","note-risk->plugin-might-break","plugin-might-break->plugin"],"focus_node_id":"note-risk","note_zh":"直接展开Mina记录的潜在问题。"},{"step_no":2,"label":"条件","sentence_en":"Mina noted that the plugin might break on older browsers.","sentence_zh":"Mina指出，这个插件在旧版浏览器上可能会出故障。","add_node_ids":["on-older-browsers"],"add_link_ids":["on-older-browsers->plugin-might-break"],"focus_node_id":"on-older-browsers","note_zh":"限定风险可能出现的运行环境。"},{"step_no":3,"label":"时间","sentence_en":"Mina noted during the upgrade review that the plugin might break on older browsers.","sentence_zh":"Mina在升级评审期间指出，这个插件在旧版浏览器上可能会出故障。","add_node_ids":["during-upgrade-review"],"add_link_ids":["during-upgrade-review->note-risk"],"focus_node_id":"during-upgrade-review","note_zh":"补充这项提醒进入项目讨论的环节。"}]}'
  ),
  (
    'notice-primary',
    'notice',
    'notice',
    'notice a queue growing',
    '注意到队列正在异常增长',
    'Sam noticed the upload queue growing.',
    'Sam注意到上传队列正在增长。',
    'Sam noticed the upload queue growing after the release while checking the metrics.',
    'Sam在检查运行指标时，注意到上传队列在发布后不断增长。',
    'queue-monitoring',
    '{"schema_version":2,"root_action_id":"notice-queue-growth","nodes":[{"id":"notice-queue-growth","text":"noticed","kind":"action","label_zh":"察觉队列增长"},{"id":"sam","text":"Sam","kind":"core","label_zh":"发现队列异常的人"},{"id":"queue-growing","text":"the upload queue growing","kind":"action","label_zh":"上传队列持续增长"},{"id":"upload-queue","text":"the upload queue","kind":"core","label_zh":"正在积压的上传队列"},{"id":"while-checking-metrics","text":"while checking the metrics","kind":"action","label_zh":"查看运行指标"},{"id":"metrics","text":"the metrics","kind":"core","label_zh":"Sam正在检查的运行指标"},{"id":"after-release","text":"after the release","kind":"modifier","label_zh":"队列增长出现的发布后阶段"}],"links":[{"id":"notice-queue-growth->sam","from":"notice-queue-growth","to":"sam","kind":"core","relation_type":"actor","label_zh":"Sam察觉了运行异常"},{"id":"notice-queue-growth->queue-growing","from":"notice-queue-growth","to":"queue-growing","kind":"core","relation_type":"content","label_zh":"Sam看到上传队列正在增长"},{"id":"queue-growing->upload-queue","from":"queue-growing","to":"upload-queue","kind":"core","relation_type":"actor","label_zh":"持续增长的是上传队列"},{"id":"while-checking-metrics->notice-queue-growth","from":"while-checking-metrics","to":"notice-queue-growth","kind":"modifier","relation_type":"time","label_zh":"异常是在检查指标时发现的"},{"id":"while-checking-metrics->metrics","from":"while-checking-metrics","to":"metrics","kind":"core","relation_type":"target","label_zh":"检查动作针对系统运行指标"},{"id":"while-checking-metrics->sam","from":"while-checking-metrics","to":"sam","kind":"core","relation_type":"shared_actor","label_zh":"检查指标的也是Sam"},{"id":"after-release->queue-growing","from":"after-release","to":"queue-growing","kind":"modifier","relation_type":"time","label_zh":"队列增长发生在版本发布之后"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Sam noticed the upload queue growing.","sentence_zh":"Sam注意到上传队列正在增长。","add_node_ids":["notice-queue-growth","sam","queue-growing","upload-queue"],"add_link_ids":["notice-queue-growth->sam","notice-queue-growth->queue-growing","queue-growing->upload-queue"],"focus_node_id":"notice-queue-growth","note_zh":"同时建立发现动作和被发现的变化。"},{"step_no":2,"label":"时间","sentence_en":"Sam noticed the upload queue growing while checking the metrics.","sentence_zh":"Sam在检查运行指标时，注意到上传队列正在增长。","add_node_ids":["while-checking-metrics","metrics"],"add_link_ids":["while-checking-metrics->notice-queue-growth","while-checking-metrics->metrics","while-checking-metrics->sam"],"focus_node_id":"while-checking-metrics","note_zh":"说明Sam通过什么排查过程发现了积压。"},{"step_no":3,"label":"对象细节","sentence_en":"Sam noticed the upload queue growing after the release while checking the metrics.","sentence_zh":"Sam在检查运行指标时，注意到上传队列在发布后不断增长。","add_node_ids":["after-release"],"add_link_ids":["after-release->queue-growing"],"focus_node_id":"after-release","note_zh":"把队列变化与刚完成的版本发布联系起来。"}]}'
  ),
  (
    'notify-primary',
    'notify',
    'notify',
    'notify owners of failures',
    '把任务失败情况通知给负责人',
    'The scheduler notifies job owners.',
    '调度器会通知任务负责人。',
    'The scheduler notifies job owners of repeated failures after the third attempt fails.',
    '第三次尝试失败后，调度器会把任务连续失败的情况通知给负责人。',
    'pipeline-alerting',
    '{"schema_version":2,"root_action_id":"notify-owners","nodes":[{"id":"notify-owners","text":"notifies","kind":"action","label_zh":"发送失败通知"},{"id":"scheduler","text":"The scheduler","kind":"core","label_zh":"自动发出通知的调度器"},{"id":"job-owners","text":"job owners","kind":"core","label_zh":"接收失败提醒的任务负责人"},{"id":"of-repeated-failures","text":"of repeated failures","kind":"modifier","label_zh":"通知涉及的连续失败情况"},{"id":"after-third-attempt-fails","text":"after the third attempt fails","kind":"action","label_zh":"第三次尝试失败"},{"id":"third-attempt","text":"the third attempt","kind":"core","label_zh":"触发通知的第三次运行尝试"}],"links":[{"id":"notify-owners->scheduler","from":"notify-owners","to":"scheduler","kind":"core","relation_type":"actor","label_zh":"调度器负责自动发送提醒"},{"id":"notify-owners->job-owners","from":"notify-owners","to":"job-owners","kind":"core","relation_type":"recipient","label_zh":"任务负责人会收到通知"},{"id":"of-repeated-failures->notify-owners","from":"of-repeated-failures","to":"notify-owners","kind":"modifier","relation_type":"content","label_zh":"通知内容是任务连续失败"},{"id":"after-third-attempt-fails->notify-owners","from":"after-third-attempt-fails","to":"notify-owners","kind":"modifier","relation_type":"condition","label_zh":"第三次尝试仍失败后才发送通知"},{"id":"after-third-attempt-fails->third-attempt","from":"after-third-attempt-fails","to":"third-attempt","kind":"core","relation_type":"actor","label_zh":"发生失败的是第三次尝试"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The scheduler notifies job owners.","sentence_zh":"调度器会通知任务负责人。","add_node_ids":["notify-owners","scheduler","job-owners"],"add_link_ids":["notify-owners->scheduler","notify-owners->job-owners"],"focus_node_id":"notify-owners","note_zh":"先确定自动通知的发送方和接收方。"},{"step_no":2,"label":"内容","sentence_en":"The scheduler notifies job owners of repeated failures.","sentence_zh":"调度器会把任务连续失败的情况通知给负责人。","add_node_ids":["of-repeated-failures"],"add_link_ids":["of-repeated-failures->notify-owners"],"focus_node_id":"of-repeated-failures","note_zh":"说明负责人收到的是哪类运行问题。"},{"step_no":3,"label":"条件","sentence_en":"The scheduler notifies job owners of repeated failures after the third attempt fails.","sentence_zh":"第三次尝试失败后，调度器会把任务连续失败的情况通知给负责人。","add_node_ids":["after-third-attempt-fails","third-attempt"],"add_link_ids":["after-third-attempt-fails->notify-owners","after-third-attempt-fails->third-attempt"],"focus_node_id":"after-third-attempt-fails","note_zh":"给出系统决定升级提醒的明确触发点。"}]}'
  ),
  (
    'nudge-primary',
    'nudge',
    'nudge',
    'nudge a reviewer to respond',
    '温和提醒评审者采取行动',
    'Elena nudged Omar.',
    'Elena轻声提醒了Omar。',
    'Elena nudged Omar in the review thread to approve the change.',
    'Elena在评审讨论中提醒Omar批准这项改动。',
    'review-followup',
    '{"schema_version":2,"root_action_id":"nudge-omar","nodes":[{"id":"nudge-omar","text":"nudged","kind":"action","label_zh":"温和提醒Omar"},{"id":"elena","text":"Elena","kind":"core","label_zh":"发出提醒的开发者"},{"id":"omar","text":"Omar","kind":"core","label_zh":"收到提醒的评审者"},{"id":"to-approve-change","text":"to approve the change","kind":"action","label_zh":"批准这项代码改动"},{"id":"change","text":"the change","kind":"core","label_zh":"等待批准的代码改动"},{"id":"in-review-thread","text":"in the review thread","kind":"modifier","label_zh":"提醒出现的代码评审讨论"}],"links":[{"id":"nudge-omar->elena","from":"nudge-omar","to":"elena","kind":"core","relation_type":"actor","label_zh":"Elena发出了这次轻提醒"},{"id":"nudge-omar->omar","from":"nudge-omar","to":"omar","kind":"core","relation_type":"recipient","label_zh":"Omar是提醒的接收者"},{"id":"nudge-omar->to-approve-change","from":"nudge-omar","to":"to-approve-change","kind":"core","relation_type":"content","label_zh":"提醒Omar批准代码改动"},{"id":"to-approve-change->omar","from":"to-approve-change","to":"omar","kind":"core","relation_type":"shared_actor","label_zh":"需要执行批准动作的是Omar"},{"id":"to-approve-change->change","from":"to-approve-change","to":"change","kind":"core","relation_type":"target","label_zh":"等待批准的是这项代码改动"},{"id":"in-review-thread->nudge-omar","from":"in-review-thread","to":"nudge-omar","kind":"modifier","relation_type":"place","label_zh":"Elena在评审讨论中发出提醒"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Elena nudged Omar.","sentence_zh":"Elena轻声提醒了Omar。","add_node_ids":["nudge-omar","elena","omar"],"add_link_ids":["nudge-omar->elena","nudge-omar->omar"],"focus_node_id":"nudge-omar","note_zh":"先呈现同事之间一次温和的催促。"},{"step_no":2,"label":"内容","sentence_en":"Elena nudged Omar to approve the change.","sentence_zh":"Elena提醒Omar批准这项改动。","add_node_ids":["to-approve-change","change"],"add_link_ids":["nudge-omar->to-approve-change","to-approve-change->omar","to-approve-change->change"],"focus_node_id":"to-approve-change","note_zh":"展开提醒希望推动的具体操作。"},{"step_no":3,"label":"场景","sentence_en":"Elena nudged Omar in the review thread to approve the change.","sentence_zh":"Elena在评审讨论中提醒Omar批准这项改动。","add_node_ids":["in-review-thread"],"add_link_ids":["in-review-thread->nudge-omar"],"focus_node_id":"in-review-thread","note_zh":"补充提醒所使用的工作沟通场景。"}]}'
  ),
  (
    'obey-primary',
    'obey',
    'obey',
    'obey a concurrency limit',
    '遵守系统设置的并发限制',
    'The worker pool obeys the concurrency limit.',
    '工作进程池遵守并发上限。',
    'The worker pool obeys the concurrency limit for free accounts even during bulk imports.',
    '即使在批量导入期间，工作进程池也遵守免费账户的并发上限。',
    'worker-scaling',
    '{"schema_version":2,"root_action_id":"obey-limit","nodes":[{"id":"obey-limit","text":"obeys","kind":"action","label_zh":"遵守并发上限"},{"id":"worker-pool","text":"The worker pool","kind":"core","label_zh":"受到并发规则约束的进程池"},{"id":"concurrency-limit","text":"the concurrency limit","kind":"core","label_zh":"进程池必须遵守的并发上限"},{"id":"for-free-accounts","text":"for free accounts","kind":"modifier","label_zh":"并发上限适用的免费账户"},{"id":"even-during-imports","text":"even during bulk imports","kind":"modifier","label_zh":"仍不能突破上限的批量导入阶段"}],"links":[{"id":"obey-limit->worker-pool","from":"obey-limit","to":"worker-pool","kind":"core","relation_type":"actor","label_zh":"工作进程池按并发规则运行"},{"id":"obey-limit->concurrency-limit","from":"obey-limit","to":"concurrency-limit","kind":"core","relation_type":"target","label_zh":"进程池遵守的是并发任务上限"},{"id":"for-free-accounts->concurrency-limit","from":"for-free-accounts","to":"concurrency-limit","kind":"modifier","relation_type":"scope","label_zh":"这项限制针对免费账户"},{"id":"even-during-imports->obey-limit","from":"even-during-imports","to":"obey-limit","kind":"modifier","relation_type":"condition","label_zh":"批量导入期间也不会越过上限"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The worker pool obeys the concurrency limit.","sentence_zh":"工作进程池遵守并发上限。","add_node_ids":["obey-limit","worker-pool","concurrency-limit"],"add_link_ids":["obey-limit->worker-pool","obey-limit->concurrency-limit"],"focus_node_id":"obey-limit","note_zh":"直接建立运行组件与限制规则的关系。"},{"step_no":2,"label":"范围","sentence_en":"The worker pool obeys the concurrency limit for free accounts.","sentence_zh":"工作进程池遵守免费账户的并发上限。","add_node_ids":["for-free-accounts"],"add_link_ids":["for-free-accounts->concurrency-limit"],"focus_node_id":"for-free-accounts","note_zh":"限定这项容量规则服务的账户类型。"},{"step_no":3,"label":"条件","sentence_en":"The worker pool obeys the concurrency limit for free accounts even during bulk imports.","sentence_zh":"即使在批量导入期间，工作进程池也遵守免费账户的并发上限。","add_node_ids":["even-during-imports"],"add_link_ids":["even-during-imports->obey-limit"],"focus_node_id":"even-during-imports","note_zh":"强调高负载任务不会解除规则约束。"}]}'
  ),
  (
    'object-primary',
    'object',
    'object',
    'object to skipping tests',
    '明确反对跳过测试',
    'The release manager objected.',
    '发布经理表示反对。',
    'The release manager objected to skipping the integration tests because the patch changed the schema.',
    '发布经理反对跳过集成测试，因为这个补丁修改了数据结构。',
    'release-planning',
    '{"schema_version":2,"root_action_id":"object-skipping","nodes":[{"id":"object-skipping","text":"objected","kind":"action","label_zh":"反对跳过测试"},{"id":"release-manager","text":"The release manager","kind":"core","label_zh":"提出反对意见的发布经理"},{"id":"to-skipping-tests","text":"to skipping the integration tests","kind":"action","label_zh":"跳过集成测试"},{"id":"integration-tests","text":"the integration tests","kind":"core","label_zh":"不应被跳过的集成测试"},{"id":"because-patch-changed-schema","text":"because the patch changed the schema","kind":"action","label_zh":"补丁修改了数据结构"},{"id":"patch","text":"the patch","kind":"core","label_zh":"涉及数据结构修改的补丁"},{"id":"schema","text":"the schema","kind":"core","label_zh":"被补丁改变的数据结构"}],"links":[{"id":"object-skipping->release-manager","from":"object-skipping","to":"release-manager","kind":"core","relation_type":"actor","label_zh":"发布经理明确表达了反对"},{"id":"object-skipping->to-skipping-tests","from":"object-skipping","to":"to-skipping-tests","kind":"core","relation_type":"target","label_zh":"受到反对的是跳过测试的做法"},{"id":"to-skipping-tests->integration-tests","from":"to-skipping-tests","to":"integration-tests","kind":"core","relation_type":"target","label_zh":"有人提议跳过集成测试"},{"id":"because-patch-changed-schema->object-skipping","from":"because-patch-changed-schema","to":"object-skipping","kind":"modifier","relation_type":"reason","label_zh":"补丁改动数据结构是反对的原因"},{"id":"because-patch-changed-schema->patch","from":"because-patch-changed-schema","to":"patch","kind":"core","relation_type":"actor","label_zh":"这项补丁造成了结构变化"},{"id":"because-patch-changed-schema->schema","from":"because-patch-changed-schema","to":"schema","kind":"core","relation_type":"target","label_zh":"补丁改变的是数据库结构"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The release manager objected.","sentence_zh":"发布经理表示反对。","add_node_ids":["object-skipping","release-manager"],"add_link_ids":["object-skipping->release-manager"],"focus_node_id":"object-skipping","note_zh":"先给出发布经理明确的立场。"},{"step_no":2,"label":"对象细节","sentence_en":"The release manager objected to skipping the integration tests.","sentence_zh":"发布经理反对跳过集成测试。","add_node_ids":["to-skipping-tests","integration-tests"],"add_link_ids":["object-skipping->to-skipping-tests","to-skipping-tests->integration-tests"],"focus_node_id":"to-skipping-tests","note_zh":"具体说明反对意见针对哪种发布安排。"},{"step_no":3,"label":"原因","sentence_en":"The release manager objected to skipping the integration tests because the patch changed the schema.","sentence_zh":"发布经理反对跳过集成测试，因为这个补丁修改了数据结构。","add_node_ids":["because-patch-changed-schema","patch","schema"],"add_link_ids":["because-patch-changed-schema->object-skipping","because-patch-changed-schema->patch","because-patch-changed-schema->schema"],"focus_node_id":"because-patch-changed-schema","note_zh":"补上坚持执行测试的技术依据。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'observe-primary',
    'observe',
    'observe',
    'observe requests retrying',
    '观察到请求正在自动重试',
    'The engineers observed requests retrying.',
    '工程师们观察到请求正在重试。',
    'The engineers observed requests retrying automatically during the failover test.',
    '工程师们在故障切换测试期间观察到请求正在自动重试。',
    'failure-test',
    '{"schema_version":2,"root_action_id":"observe-retries","nodes":[{"id":"observe-retries","text":"observed","kind":"action","label_zh":"观察系统重试行为"},{"id":"engineers","text":"The engineers","kind":"core","label_zh":"进行故障测试观察的工程师"},{"id":"requests-retrying","text":"requests retrying","kind":"action","label_zh":"请求重新发起"},{"id":"requests","text":"requests","kind":"core","label_zh":"发生重试的网络请求"},{"id":"automatically","text":"automatically","kind":"modifier","label_zh":"由系统自行触发重试"},{"id":"during-failover-test","text":"during the failover test","kind":"modifier","label_zh":"重试行为出现的故障切换测试"}],"links":[{"id":"observe-retries->engineers","from":"observe-retries","to":"engineers","kind":"core","relation_type":"actor","label_zh":"工程师观察并确认了系统行为"},{"id":"observe-retries->requests-retrying","from":"observe-retries","to":"requests-retrying","kind":"core","relation_type":"content","label_zh":"被观察到的现象是请求重试"},{"id":"requests-retrying->requests","from":"requests-retrying","to":"requests","kind":"core","relation_type":"actor","label_zh":"重新发起的是网络请求"},{"id":"automatically->requests-retrying","from":"automatically","to":"requests-retrying","kind":"modifier","relation_type":"manner","label_zh":"重试不需要人工触发"},{"id":"during-failover-test->observe-retries","from":"during-failover-test","to":"observe-retries","kind":"modifier","relation_type":"time","label_zh":"工程师在故障切换测试期间进行观察"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The engineers observed requests retrying.","sentence_zh":"工程师们观察到请求正在重试。","add_node_ids":["observe-retries","engineers","requests-retrying","requests"],"add_link_ids":["observe-retries->engineers","observe-retries->requests-retrying","requests-retrying->requests"],"focus_node_id":"observe-retries","note_zh":"将观察过程和实际发生的重试同时呈现。"},{"step_no":2,"label":"方式","sentence_en":"The engineers observed requests retrying automatically.","sentence_zh":"工程师们观察到请求正在自动重试。","add_node_ids":["automatically"],"add_link_ids":["automatically->requests-retrying"],"focus_node_id":"automatically","note_zh":"说明请求由系统自动重新发起。"},{"step_no":3,"label":"场景","sentence_en":"The engineers observed requests retrying automatically during the failover test.","sentence_zh":"工程师们在故障切换测试期间观察到请求正在自动重试。","add_node_ids":["during-failover-test"],"add_link_ids":["during-failover-test->observe-retries"],"focus_node_id":"during-failover-test","note_zh":"定位验证这一行为的测试环境。"}]}'
  ),
  (
    'obtain-primary',
    'obtain',
    'obtain',
    'obtain a signing key',
    '通过审批获取签名密钥',
    'Ira obtained a temporary signing key.',
    'Ira获得了一把临时签名密钥。',
    'Ira obtained a temporary signing key from the security team after the request was approved.',
    '申请获批后，Ira从安全团队获得了一把临时签名密钥。',
    'release-signing',
    '{"schema_version":2,"root_action_id":"obtain-key","nodes":[{"id":"obtain-key","text":"obtained","kind":"action","label_zh":"获取临时签名密钥"},{"id":"ira","text":"Ira","kind":"core","label_zh":"取得密钥的发布工程师"},{"id":"temporary-key","text":"a temporary signing key","kind":"core","label_zh":"用于本次发布的临时签名密钥"},{"id":"from-security-team","text":"from the security team","kind":"modifier","label_zh":"签发密钥的安全团队"},{"id":"after-request-was-approved","text":"after the request was approved","kind":"action","label_zh":"密钥申请获得批准"},{"id":"request","text":"the request","kind":"core","label_zh":"针对临时密钥的申请"}],"links":[{"id":"obtain-key->ira","from":"obtain-key","to":"ira","kind":"core","relation_type":"actor","label_zh":"Ira最终取得了签名密钥"},{"id":"obtain-key->temporary-key","from":"obtain-key","to":"temporary-key","kind":"core","relation_type":"target","label_zh":"获得的是一把临时签名密钥"},{"id":"from-security-team->obtain-key","from":"from-security-team","to":"obtain-key","kind":"modifier","relation_type":"recipient","label_zh":"密钥由安全团队提供"},{"id":"after-request-was-approved->obtain-key","from":"after-request-was-approved","to":"obtain-key","kind":"modifier","relation_type":"condition","label_zh":"申请批准后Ira才能取得密钥"},{"id":"after-request-was-approved->request","from":"after-request-was-approved","to":"request","kind":"core","relation_type":"target","label_zh":"获得批准的是密钥申请"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Ira obtained a temporary signing key.","sentence_zh":"Ira获得了一把临时签名密钥。","add_node_ids":["obtain-key","ira","temporary-key"],"add_link_ids":["obtain-key->ira","obtain-key->temporary-key"],"focus_node_id":"obtain-key","note_zh":"先交代Ira正式取得的安全凭据。"},{"step_no":2,"label":"来源","sentence_en":"Ira obtained a temporary signing key from the security team.","sentence_zh":"Ira从安全团队获得了一把临时签名密钥。","add_node_ids":["from-security-team"],"add_link_ids":["from-security-team->obtain-key"],"focus_node_id":"from-security-team","note_zh":"指出敏感凭据由哪个团队签发。"},{"step_no":3,"label":"条件","sentence_en":"Ira obtained a temporary signing key from the security team after the request was approved.","sentence_zh":"申请获批后，Ira从安全团队获得了一把临时签名密钥。","add_node_ids":["after-request-was-approved","request"],"add_link_ids":["after-request-was-approved->obtain-key","after-request-was-approved->request"],"focus_node_id":"after-request-was-approved","note_zh":"补全获取密钥前必须满足的审批要求。"}]}'
  ),
  (
    'occupy-primary',
    'occupy',
    'occupy',
    'occupy disk space',
    '占用大量磁盘空间',
    'The build cache occupies most of the runner''s disk space.',
    '构建缓存占用了运行器的大部分磁盘空间。',
    'The build cache occupies most of the runner''s disk space after a week of builds unless cleanup runs nightly.',
    '连续构建一周后，除非每晚执行清理，否则构建缓存会占用运行器的大部分磁盘空间。',
    'build-cache',
    '{"schema_version":2,"root_action_id":"occupy-space","nodes":[{"id":"occupy-space","text":"occupies","kind":"action","label_zh":"占用磁盘空间"},{"id":"build-cache","text":"The build cache","kind":"core","label_zh":"消耗存储容量的构建缓存"},{"id":"disk-space","text":"most of the runner''s disk space","kind":"core","label_zh":"运行器上被占用的大部分磁盘空间"},{"id":"after-weekly-builds","text":"after a week of builds","kind":"modifier","label_zh":"缓存持续累积一周后的阶段"},{"id":"unless-cleanup-runs","text":"unless cleanup runs nightly","kind":"action","label_zh":"每晚执行清理任务"},{"id":"cleanup","text":"cleanup","kind":"core","label_zh":"能够释放缓存空间的清理任务"},{"id":"nightly","text":"nightly","kind":"modifier","label_zh":"清理任务每晚执行的频率"}],"links":[{"id":"occupy-space->build-cache","from":"occupy-space","to":"build-cache","kind":"core","relation_type":"actor","label_zh":"构建缓存造成大量磁盘占用"},{"id":"occupy-space->disk-space","from":"occupy-space","to":"disk-space","kind":"core","relation_type":"target","label_zh":"缓存占据的是运行器磁盘空间"},{"id":"after-weekly-builds->occupy-space","from":"after-weekly-builds","to":"occupy-space","kind":"modifier","relation_type":"time","label_zh":"连续构建一周后占用变得明显"},{"id":"unless-cleanup-runs->occupy-space","from":"unless-cleanup-runs","to":"occupy-space","kind":"modifier","relation_type":"condition","label_zh":"定期清理可以避免磁盘被大量占用"},{"id":"unless-cleanup-runs->cleanup","from":"unless-cleanup-runs","to":"cleanup","kind":"core","relation_type":"actor","label_zh":"需要运行的是缓存清理任务"},{"id":"nightly->unless-cleanup-runs","from":"nightly","to":"unless-cleanup-runs","kind":"modifier","relation_type":"frequency","label_zh":"清理任务应当每晚运行"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The build cache occupies most of the runner''s disk space.","sentence_zh":"构建缓存占用了运行器的大部分磁盘空间。","add_node_ids":["occupy-space","build-cache","disk-space"],"add_link_ids":["occupy-space->build-cache","occupy-space->disk-space"],"focus_node_id":"occupy-space","note_zh":"直接呈现缓存造成的存储压力。"},{"step_no":2,"label":"时间","sentence_en":"The build cache occupies most of the runner''s disk space after a week of builds.","sentence_zh":"连续构建一周后，构建缓存占用了运行器的大部分磁盘空间。","add_node_ids":["after-weekly-builds"],"add_link_ids":["after-weekly-builds->occupy-space"],"focus_node_id":"after-weekly-builds","note_zh":"说明缓存经过多长时间的累积后形成问题。"},{"step_no":3,"label":"条件","sentence_en":"The build cache occupies most of the runner''s disk space after a week of builds unless cleanup runs nightly.","sentence_zh":"连续构建一周后，除非每晚执行清理，否则构建缓存会占用运行器的大部分磁盘空间。","add_node_ids":["unless-cleanup-runs","cleanup","nightly"],"add_link_ids":["unless-cleanup-runs->occupy-space","unless-cleanup-runs->cleanup","nightly->unless-cleanup-runs"],"focus_node_id":"unless-cleanup-runs","note_zh":"加入能够阻止缓存持续膨胀的运维措施。"}]}'
  ),
  (
    'occur-primary',
    'occur',
    'occur',
    'occur during failover',
    '在故障切换期间发生',
    'Brief timeouts occurred.',
    '发生了短暂超时。',
    'Brief timeouts occurred only in the EU region while the replica was being promoted.',
    '数据库副本提升期间，短暂超时只发生在欧洲区域。',
    'database-failover',
    '{"schema_version":2,"root_action_id":"occur-timeouts","nodes":[{"id":"occur-timeouts","text":"occurred","kind":"action","label_zh":"发生短暂超时"},{"id":"brief-timeouts","text":"Brief timeouts","kind":"core","label_zh":"实际出现的短暂请求超时"},{"id":"while-replica-was-promoted","text":"while the replica was being promoted","kind":"action","label_zh":"副本正在提升为主节点"},{"id":"replica","text":"the replica","kind":"core","label_zh":"正在提升角色的数据库副本"},{"id":"only-in-eu-region","text":"only in the EU region","kind":"modifier","label_zh":"超时影响的欧洲区域范围"}],"links":[{"id":"occur-timeouts->brief-timeouts","from":"occur-timeouts","to":"brief-timeouts","kind":"core","relation_type":"actor","label_zh":"发生的是短暂请求超时"},{"id":"while-replica-was-promoted->occur-timeouts","from":"while-replica-was-promoted","to":"occur-timeouts","kind":"modifier","relation_type":"time","label_zh":"超时出现在副本提升过程中"},{"id":"while-replica-was-promoted->replica","from":"while-replica-was-promoted","to":"replica","kind":"core","relation_type":"target","label_zh":"被提升的是数据库副本"},{"id":"only-in-eu-region->occur-timeouts","from":"only-in-eu-region","to":"occur-timeouts","kind":"modifier","relation_type":"scope","label_zh":"这些超时只发生在欧洲区域"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Brief timeouts occurred.","sentence_zh":"发生了短暂超时。","add_node_ids":["occur-timeouts","brief-timeouts"],"add_link_ids":["occur-timeouts->brief-timeouts"],"focus_node_id":"occur-timeouts","note_zh":"先记录系统中出现的短暂异常。"},{"step_no":2,"label":"时间","sentence_en":"Brief timeouts occurred while the replica was being promoted.","sentence_zh":"数据库副本提升期间发生了短暂超时。","add_node_ids":["while-replica-was-promoted","replica"],"add_link_ids":["while-replica-was-promoted->occur-timeouts","while-replica-was-promoted->replica"],"focus_node_id":"while-replica-was-promoted","note_zh":"用并行发生的切换事件定位异常时段。"},{"step_no":3,"label":"范围","sentence_en":"Brief timeouts occurred only in the EU region while the replica was being promoted.","sentence_zh":"数据库副本提升期间，短暂超时只发生在欧洲区域。","add_node_ids":["only-in-eu-region"],"add_link_ids":["only-in-eu-region->occur-timeouts"],"focus_node_id":"only-in-eu-region","note_zh":"进一步缩小这次异常的影响范围。"}]}'
  ),
  (
    'offend-primary',
    'offend',
    'offend',
    'offend a teammate',
    '因表达不当而冒犯同事',
    'The joke offended a teammate.',
    '这个玩笑冒犯了一位同事。',
    'The joke during the retrospective offended a teammate by blaming her for the outage.',
    '复盘会议上的这个玩笑把服务中断归咎于她，因而冒犯了这位同事。',
    'incident-retrospective',
    '{"schema_version":2,"root_action_id":"offend-teammate","nodes":[{"id":"offend-teammate","text":"offended","kind":"action","label_zh":"冒犯了同事"},{"id":"joke","text":"The joke","kind":"core","label_zh":"造成冒犯的不当玩笑"},{"id":"teammate","text":"a teammate","kind":"core","label_zh":"因玩笑感到被冒犯的同事"},{"id":"by-blaming-mistake","text":"by blaming her for the outage","kind":"action","label_zh":"把服务中断归咎于她"},{"id":"her","text":"her","kind":"core","label_zh":"被错误指责的那位同事"},{"id":"outage","text":"the outage","kind":"core","label_zh":"被拿来归责的服务中断"},{"id":"during-retrospective","text":"during the retrospective","kind":"modifier","label_zh":"不当玩笑出现的复盘会议"}],"links":[{"id":"offend-teammate->joke","from":"offend-teammate","to":"joke","kind":"core","relation_type":"actor","label_zh":"这句玩笑造成了冒犯"},{"id":"offend-teammate->teammate","from":"offend-teammate","to":"teammate","kind":"core","relation_type":"target","label_zh":"受到冒犯的是团队中的一位同事"},{"id":"by-blaming-mistake->offend-teammate","from":"by-blaming-mistake","to":"offend-teammate","kind":"modifier","relation_type":"manner","label_zh":"玩笑通过错误归责伤害了同事"},{"id":"by-blaming-mistake->her","from":"by-blaming-mistake","to":"her","kind":"core","relation_type":"target","label_zh":"被归咎的是受到冒犯的同事"},{"id":"by-blaming-mistake->outage","from":"by-blaming-mistake","to":"outage","kind":"core","relation_type":"content","label_zh":"指责涉及这次服务中断"},{"id":"during-retrospective->joke","from":"during-retrospective","to":"joke","kind":"modifier","relation_type":"time","label_zh":"玩笑是在事故复盘期间说出的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The joke offended a teammate.","sentence_zh":"这个玩笑冒犯了一位同事。","add_node_ids":["offend-teammate","joke","teammate"],"add_link_ids":["offend-teammate->joke","offend-teammate->teammate"],"focus_node_id":"offend-teammate","note_zh":"先明确哪段话伤害了团队成员。"},{"step_no":2,"label":"方式","sentence_en":"The joke offended a teammate by blaming her for the outage.","sentence_zh":"这个玩笑把服务中断归咎于她，因而冒犯了这位同事。","add_node_ids":["by-blaming-mistake","her","outage"],"add_link_ids":["by-blaming-mistake->offend-teammate","by-blaming-mistake->her","by-blaming-mistake->outage"],"focus_node_id":"by-blaming-mistake","note_zh":"说明玩笑中真正造成伤害的表达。"},{"step_no":3,"label":"场景","sentence_en":"The joke during the retrospective offended a teammate by blaming her for the outage.","sentence_zh":"复盘会议上的这个玩笑把服务中断归咎于她，因而冒犯了这位同事。","add_node_ids":["during-retrospective"],"add_link_ids":["during-retrospective->joke"],"focus_node_id":"during-retrospective","note_zh":"补充不当表达出现的公开工作场合。"}]}'
  ),
  (
    'offer-primary',
    'offer',
    'offer',
    'offer automatic rollback',
    '提供自动回滚功能',
    'The deployment service offers automatic rollback.',
    '部署服务提供自动回滚功能。',
    'The deployment service offers automatic rollback for failed health checks to restore the previous version.',
    '部署服务为健康检查失败的情况提供自动回滚功能，以恢复上一个版本。',
    'deployment-platform',
    '{"schema_version":2,"root_action_id":"offer-rollback","nodes":[{"id":"offer-rollback","text":"offers","kind":"action","label_zh":"提供自动回滚功能"},{"id":"deployment-service","text":"The deployment service","kind":"core","label_zh":"提供回滚能力的部署服务"},{"id":"automatic-rollback","text":"automatic rollback","kind":"core","label_zh":"平台提供的自动恢复功能"},{"id":"for-failed-health-checks","text":"for failed health checks","kind":"modifier","label_zh":"触发回滚的健康检查失败情况"},{"id":"to-restore-previous-version","text":"to restore the previous version","kind":"action","label_zh":"恢复上一个稳定版本"},{"id":"previous-version","text":"the previous version","kind":"core","label_zh":"回滚后重新运行的旧版本"}],"links":[{"id":"offer-rollback->deployment-service","from":"offer-rollback","to":"deployment-service","kind":"core","relation_type":"actor","label_zh":"部署服务提供恢复能力"},{"id":"offer-rollback->automatic-rollback","from":"offer-rollback","to":"automatic-rollback","kind":"core","relation_type":"target","label_zh":"提供的是自动回滚功能"},{"id":"for-failed-health-checks->automatic-rollback","from":"for-failed-health-checks","to":"automatic-rollback","kind":"modifier","relation_type":"condition","label_zh":"健康检查失败时可以使用该功能"},{"id":"to-restore-previous-version->automatic-rollback","from":"to-restore-previous-version","to":"automatic-rollback","kind":"modifier","relation_type":"purpose","label_zh":"自动回滚用于恢复先前版本"},{"id":"to-restore-previous-version->previous-version","from":"to-restore-previous-version","to":"previous-version","kind":"core","relation_type":"target","label_zh":"恢复动作针对上一个版本"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The deployment service offers automatic rollback.","sentence_zh":"部署服务提供自动回滚功能。","add_node_ids":["offer-rollback","deployment-service","automatic-rollback"],"add_link_ids":["offer-rollback->deployment-service","offer-rollback->automatic-rollback"],"focus_node_id":"offer-rollback","note_zh":"先介绍部署平台具备的恢复能力。"},{"step_no":2,"label":"条件","sentence_en":"The deployment service offers automatic rollback for failed health checks.","sentence_zh":"部署服务为健康检查失败的情况提供自动回滚功能。","add_node_ids":["for-failed-health-checks"],"add_link_ids":["for-failed-health-checks->automatic-rollback"],"focus_node_id":"for-failed-health-checks","note_zh":"说明什么故障信号可以启用回滚。"},{"step_no":3,"label":"目的","sentence_en":"The deployment service offers automatic rollback for failed health checks to restore the previous version.","sentence_zh":"部署服务为健康检查失败的情况提供自动回滚功能，以恢复上一个版本。","add_node_ids":["to-restore-previous-version","previous-version"],"add_link_ids":["to-restore-previous-version->automatic-rollback","to-restore-previous-version->previous-version"],"focus_node_id":"to-restore-previous-version","note_zh":"展开回滚功能最终恢复的系统状态。"}]}'
  ),
  (
    'offload-primary',
    'offload',
    'offload',
    'offload report generation',
    '把报表生成任务分流到后台资源',
    'The web server offloads report generation.',
    'Web服务器会分流报表生成任务。',
    'The web server offloads report generation to background workers when an export is large to avoid request timeouts.',
    '导出文件较大时，Web服务器会把报表生成任务分流给后台进程，以避免请求超时。',
    'reporting-api',
    '{"schema_version":2,"root_action_id":"offload-reports","nodes":[{"id":"offload-reports","text":"offloads","kind":"action","label_zh":"分流报表生成任务"},{"id":"web-server","text":"The web server","kind":"core","label_zh":"转移计算任务的前端服务"},{"id":"report-generation","text":"report generation","kind":"core","label_zh":"被移出请求流程的报表任务"},{"id":"to-background-workers","text":"to background workers","kind":"modifier","label_zh":"接手报表任务的后台进程"},{"id":"when-export-is-large","text":"when an export is large","kind":"action","label_zh":"导出文件规模较大"},{"id":"export","text":"an export","kind":"core","label_zh":"需要生成的大型数据导出"},{"id":"to-avoid-timeouts","text":"to avoid request timeouts","kind":"action","label_zh":"避免请求超时"},{"id":"request-timeouts","text":"request timeouts","kind":"core","label_zh":"需要防止的接口超时"}],"links":[{"id":"offload-reports->web-server","from":"offload-reports","to":"web-server","kind":"core","relation_type":"actor","label_zh":"Web服务器负责转移重计算任务"},{"id":"offload-reports->report-generation","from":"offload-reports","to":"report-generation","kind":"core","relation_type":"target","label_zh":"报表生成是被分流的工作"},{"id":"to-background-workers->offload-reports","from":"to-background-workers","to":"offload-reports","kind":"modifier","relation_type":"recipient","label_zh":"后台进程接收报表生成任务"},{"id":"when-export-is-large->offload-reports","from":"when-export-is-large","to":"offload-reports","kind":"modifier","relation_type":"condition","label_zh":"导出规模较大时才进行任务分流"},{"id":"when-export-is-large->export","from":"when-export-is-large","to":"export","kind":"core","relation_type":"actor","label_zh":"规模较大的是这次数据导出"},{"id":"to-avoid-timeouts->offload-reports","from":"to-avoid-timeouts","to":"offload-reports","kind":"modifier","relation_type":"purpose","label_zh":"分流任务是为了防止接口超时"},{"id":"to-avoid-timeouts->request-timeouts","from":"to-avoid-timeouts","to":"request-timeouts","kind":"core","relation_type":"target","label_zh":"需要避免的是请求处理超时"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The web server offloads report generation.","sentence_zh":"Web服务器会分流报表生成任务。","add_node_ids":["offload-reports","web-server","report-generation"],"add_link_ids":["offload-reports->web-server","offload-reports->report-generation"],"focus_node_id":"offload-reports","note_zh":"先交代前端服务转移的计算工作。"},{"step_no":2,"label":"去向","sentence_en":"The web server offloads report generation to background workers.","sentence_zh":"Web服务器会把报表生成任务分流给后台进程。","add_node_ids":["to-background-workers"],"add_link_ids":["to-background-workers->offload-reports"],"focus_node_id":"to-background-workers","note_zh":"指出实际承接报表计算的后台资源。"},{"step_no":3,"label":"条件","sentence_en":"The web server offloads report generation to background workers when an export is large.","sentence_zh":"导出文件较大时，Web服务器会把报表生成任务分流给后台进程。","add_node_ids":["when-export-is-large","export"],"add_link_ids":["when-export-is-large->offload-reports","when-export-is-large->export"],"focus_node_id":"when-export-is-large","note_zh":"加入系统决定分流任务的规模条件。"},{"step_no":4,"label":"目的","sentence_en":"The web server offloads report generation to background workers when an export is large to avoid request timeouts.","sentence_zh":"导出文件较大时，Web服务器会把报表生成任务分流给后台进程，以避免请求超时。","add_node_ids":["to-avoid-timeouts","request-timeouts"],"add_link_ids":["to-avoid-timeouts->offload-reports","to-avoid-timeouts->request-timeouts"],"focus_node_id":"to-avoid-timeouts","note_zh":"说明任务分流要保护的用户请求体验。"}]}'
  ),
  (
    'offset-primary',
    'offset',
    'offset',
    'offset storage growth',
    '抵消存储用量的增长',
    'Compression savings offset the storage growth.',
    '压缩带来的空间节省抵消了存储用量增长。',
    'Last quarter, compression savings almost completely offset the storage growth from the new audit logs.',
    '上个季度，压缩带来的空间节省几乎完全抵消了新增审计日志造成的存储用量增长。',
    'storage-budget',
    '{"schema_version":2,"root_action_id":"offset-growth","nodes":[{"id":"offset-growth","text":"offset","kind":"action","label_zh":"抵消存储增长"},{"id":"compression-savings","text":"Compression savings","kind":"core","label_zh":"通过压缩释放的存储容量"},{"id":"storage-growth","text":"the storage growth","kind":"core","label_zh":"需要被抵消的存储用量增长"},{"id":"from-new-logs","text":"from the new audit logs","kind":"modifier","label_zh":"存储增长来自新增审计日志"},{"id":"almost-completely","text":"almost completely","kind":"modifier","label_zh":"增长基本被抵消的程度"},{"id":"last-quarter","text":"last quarter","kind":"modifier","label_zh":"这次容量变化所在的季度"}],"links":[{"id":"offset-growth->compression-savings","from":"offset-growth","to":"compression-savings","kind":"core","relation_type":"actor","label_zh":"压缩节省量发挥了抵消作用"},{"id":"offset-growth->storage-growth","from":"offset-growth","to":"storage-growth","kind":"core","relation_type":"target","label_zh":"被抵消的是存储容量增长"},{"id":"from-new-logs->storage-growth","from":"from-new-logs","to":"storage-growth","kind":"modifier","relation_type":"reason","label_zh":"新增审计日志造成了存储增长"},{"id":"almost-completely->offset-growth","from":"almost-completely","to":"offset-growth","kind":"modifier","relation_type":"degree","label_zh":"压缩覆盖了绝大部分新增用量"},{"id":"last-quarter->offset-growth","from":"last-quarter","to":"offset-growth","kind":"modifier","relation_type":"time","label_zh":"抵消效果发生在上个季度"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Compression savings offset the storage growth.","sentence_zh":"压缩带来的空间节省抵消了存储用量增长。","add_node_ids":["offset-growth","compression-savings","storage-growth"],"add_link_ids":["offset-growth->compression-savings","offset-growth->storage-growth"],"focus_node_id":"offset-growth","note_zh":"建立节省容量与新增用量之间的抵消关系。"},{"step_no":2,"label":"原因","sentence_en":"Compression savings offset the storage growth from the new audit logs.","sentence_zh":"压缩带来的空间节省抵消了新增审计日志造成的存储用量增长。","add_node_ids":["from-new-logs"],"add_link_ids":["from-new-logs->storage-growth"],"focus_node_id":"from-new-logs","note_zh":"解释额外存储用量来自哪类数据。"},{"step_no":3,"label":"程度","sentence_en":"Compression savings almost completely offset the storage growth from the new audit logs.","sentence_zh":"压缩带来的空间节省几乎完全抵消了新增审计日志造成的存储用量增长。","add_node_ids":["almost-completely"],"add_link_ids":["almost-completely->offset-growth"],"focus_node_id":"almost-completely","note_zh":"量化压缩措施覆盖新增用量的程度。"},{"step_no":4,"label":"时间","sentence_en":"Last quarter, compression savings almost completely offset the storage growth from the new audit logs.","sentence_zh":"上个季度，压缩带来的空间节省几乎完全抵消了新增审计日志造成的存储用量增长。","add_node_ids":["last-quarter"],"add_link_ids":["last-quarter->offset-growth"],"focus_node_id":"last-quarter","note_zh":"把容量变化限定在具体统计周期。"}]}'
  ),
  (
    'omit-primary',
    'omit',
    'omit',
    'omit empty values',
    '从请求中省略空值字段',
    'The serializer omits empty values.',
    '序列化程序会省略空值。',
    'The serializer omits empty values from the request body unless the API requires them.',
    '除非接口要求包含空值，否则序列化程序会从请求内容中省略它们。',
    'api-serialization',
    '{"schema_version":2,"root_action_id":"omit-values","nodes":[{"id":"omit-values","text":"omits","kind":"action","label_zh":"省略空值字段"},{"id":"serializer","text":"The serializer","kind":"core","label_zh":"负责生成请求内容的序列化程序"},{"id":"empty-values","text":"empty values","kind":"core","label_zh":"不会写入请求的空值"},{"id":"from-request-body","text":"from the request body","kind":"modifier","label_zh":"空值被排除的请求内容"},{"id":"unless-api-requires-them","text":"unless the API requires them","kind":"action","label_zh":"接口明确要求这些空值"},{"id":"api","text":"the API","kind":"core","label_zh":"可能要求保留空值的接口"},{"id":"them","text":"them","kind":"core","label_zh":"接口可能要求包含的空值"}],"links":[{"id":"omit-values->serializer","from":"omit-values","to":"serializer","kind":"core","relation_type":"actor","label_zh":"序列化程序执行字段过滤"},{"id":"omit-values->empty-values","from":"omit-values","to":"empty-values","kind":"core","relation_type":"target","label_zh":"被省略的是值为空的字段"},{"id":"from-request-body->omit-values","from":"from-request-body","to":"omit-values","kind":"modifier","relation_type":"place","label_zh":"这些空值不会进入请求内容"},{"id":"unless-api-requires-them->omit-values","from":"unless-api-requires-them","to":"omit-values","kind":"modifier","relation_type":"condition","label_zh":"接口明确要求时才会保留空值"},{"id":"unless-api-requires-them->api","from":"unless-api-requires-them","to":"api","kind":"core","relation_type":"actor","label_zh":"由目标接口决定是否必须包含空值"},{"id":"unless-api-requires-them->them","from":"unless-api-requires-them","to":"them","kind":"core","relation_type":"target","label_zh":"接口要求的内容指这些空值"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The serializer omits empty values.","sentence_zh":"序列化程序会省略空值。","add_node_ids":["omit-values","serializer","empty-values"],"add_link_ids":["omit-values->serializer","omit-values->empty-values"],"focus_node_id":"omit-values","note_zh":"先说明请求生成过程会过滤什么内容。"},{"step_no":2,"label":"场景","sentence_en":"The serializer omits empty values from the request body.","sentence_zh":"序列化程序会从请求内容中省略空值。","add_node_ids":["from-request-body"],"add_link_ids":["from-request-body->omit-values"],"focus_node_id":"from-request-body","note_zh":"指出空值不会出现在哪部分输出中。"},{"step_no":3,"label":"条件","sentence_en":"The serializer omits empty values from the request body unless the API requires them.","sentence_zh":"除非接口要求包含空值，否则序列化程序会从请求内容中省略它们。","add_node_ids":["unless-api-requires-them","api","them"],"add_link_ids":["unless-api-requires-them->omit-values","unless-api-requires-them->api","unless-api-requires-them->them"],"focus_node_id":"unless-api-requires-them","note_zh":"补充可以改变默认过滤行为的接口要求。"}]}'
  ),
  (
    'open-primary',
    'open',
    'open',
    'open repository access',
    '向更多开发者开放仓库访问权限',
    'The maintainers opened the repository.',
    '维护者开放了这个代码仓库。',
    'The maintainers opened the repository to external contributors after the security audit finished so they could submit fixes.',
    '安全审计完成后，维护者向外部贡献者开放了这个代码仓库，以便他们提交修复。',
    'community-release',
    '{"schema_version":2,"root_action_id":"open-access","nodes":[{"id":"open-access","text":"opened","kind":"action","label_zh":"开放仓库访问权限"},{"id":"maintainers","text":"The maintainers","kind":"core","label_zh":"决定开放权限的维护者"},{"id":"repository","text":"the repository","kind":"core","label_zh":"向外部贡献者开放的代码仓库"},{"id":"to-external-contributors","text":"to external contributors","kind":"modifier","label_zh":"获得访问权限的外部贡献者"},{"id":"after-audit-finished","text":"after the security audit finished","kind":"action","label_zh":"安全审计完成"},{"id":"security-audit","text":"the security audit","kind":"core","label_zh":"开放仓库前完成的安全审计"},{"id":"so-they-could-submit-fixes","text":"so they could submit fixes","kind":"action","label_zh":"外部贡献者可以提交修复"},{"id":"they","text":"they","kind":"core","label_zh":"被允许提交修复的外部贡献者"},{"id":"fixes","text":"fixes","kind":"core","label_zh":"外部贡献者提交的问题修复"}],"links":[{"id":"open-access->maintainers","from":"open-access","to":"maintainers","kind":"core","relation_type":"actor","label_zh":"维护者作出了开放仓库的决定"},{"id":"open-access->repository","from":"open-access","to":"repository","kind":"core","relation_type":"target","label_zh":"获得开放访问的是代码仓库"},{"id":"to-external-contributors->open-access","from":"to-external-contributors","to":"open-access","kind":"modifier","relation_type":"recipient","label_zh":"仓库权限向外部贡献者开放"},{"id":"after-audit-finished->open-access","from":"after-audit-finished","to":"open-access","kind":"modifier","relation_type":"time","label_zh":"仓库在安全审计完成后才开放"},{"id":"after-audit-finished->security-audit","from":"after-audit-finished","to":"security-audit","kind":"core","relation_type":"actor","label_zh":"完成的是仓库安全审计"},{"id":"so-they-could-submit-fixes->open-access","from":"so-they-could-submit-fixes","to":"open-access","kind":"modifier","relation_type":"purpose","label_zh":"开放权限是为了接收外部修复"},{"id":"so-they-could-submit-fixes->they","from":"so-they-could-submit-fixes","to":"they","kind":"core","relation_type":"actor","label_zh":"提交修复的是外部贡献者"},{"id":"so-they-could-submit-fixes->fixes","from":"so-they-could-submit-fixes","to":"fixes","kind":"core","relation_type":"target","label_zh":"贡献者提交的是代码修复"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The maintainers opened the repository.","sentence_zh":"维护者开放了这个代码仓库。","add_node_ids":["open-access","maintainers","repository"],"add_link_ids":["open-access->maintainers","open-access->repository"],"focus_node_id":"open-access","note_zh":"先建立维护者改变仓库访问状态的动作。"},{"step_no":2,"label":"开放对象","sentence_en":"The maintainers opened the repository to external contributors.","sentence_zh":"维护者向外部贡献者开放了这个代码仓库。","add_node_ids":["to-external-contributors"],"add_link_ids":["to-external-contributors->open-access"],"focus_node_id":"to-external-contributors","note_zh":"明确新获得访问机会的是哪类开发者。"},{"step_no":3,"label":"时间","sentence_en":"The maintainers opened the repository to external contributors after the security audit finished.","sentence_zh":"安全审计完成后，维护者向外部贡献者开放了这个代码仓库。","add_node_ids":["after-audit-finished","security-audit"],"add_link_ids":["after-audit-finished->open-access","after-audit-finished->security-audit"],"focus_node_id":"after-audit-finished","note_zh":"加入开放访问前必须完成的安全事件。"},{"step_no":4,"label":"目的","sentence_en":"The maintainers opened the repository to external contributors after the security audit finished so they could submit fixes.","sentence_zh":"安全审计完成后，维护者向外部贡献者开放了这个代码仓库，以便他们提交修复。","add_node_ids":["so-they-could-submit-fixes","they","fixes"],"add_link_ids":["so-they-could-submit-fixes->open-access","so-they-could-submit-fixes->they","so-they-could-submit-fixes->fixes"],"focus_node_id":"so-they-could-submit-fixes","note_zh":"最后说明开放仓库希望促成的贡献行为。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
