-- Generated verb paths batch batch-010.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'package-primary',
    'package',
    'package',
    'package a desktop app',
    '把应用打包成可分发文件',
    'The release job packages the desktop app.',
    '发布任务会打包桌面应用。',
    'The release job packages the desktop app as a signed archive on the Linux runner.',
    '发布任务会在 Linux 运行器上把桌面应用打包成已签名的压缩包。',
    'release-build',
    '{"schema_version":2,"root_action_id":"package-app","nodes":[{"id":"package-app","text":"packages","kind":"action","label_zh":"执行应用打包"},{"id":"release-job","text":"The release job","kind":"core","label_zh":"运行打包流程的发布任务"},{"id":"desktop-app","text":"the desktop app","kind":"core","label_zh":"被打包的桌面应用"},{"id":"signed-archive","text":"as a signed archive","kind":"modifier","label_zh":"成品采用已签名压缩包形式"},{"id":"linux-runner","text":"on the Linux runner","kind":"modifier","label_zh":"打包所在的运行环境"}],"links":[{"id":"package-app->release-job","from":"package-app","to":"release-job","kind":"core","relation_type":"actor","label_zh":"发布任务负责执行打包"},{"id":"package-app->desktop-app","from":"package-app","to":"desktop-app","kind":"core","relation_type":"target","label_zh":"打包处理的是桌面应用"},{"id":"signed-archive->package-app","from":"signed-archive","to":"package-app","kind":"modifier","relation_type":"result","label_zh":"说明打包后得到的文件形式"},{"id":"linux-runner->package-app","from":"linux-runner","to":"package-app","kind":"modifier","relation_type":"place","label_zh":"指出打包在哪个运行器上完成"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The release job packages the desktop app.","sentence_zh":"发布任务会打包桌面应用。","add_node_ids":["package-app","release-job","desktop-app"],"add_link_ids":["package-app->release-job","package-app->desktop-app"],"focus_node_id":"package-app","note_zh":"先明确发布任务打包哪个应用。"},{"step_no":2,"label":"成品形式","sentence_en":"The release job packages the desktop app as a signed archive.","sentence_zh":"发布任务会把桌面应用打包成已签名的压缩包。","add_node_ids":["signed-archive"],"add_link_ids":["signed-archive->package-app"],"focus_node_id":"signed-archive","note_zh":"补充打包后生成的具体形式。"},{"step_no":3,"label":"运行环境","sentence_en":"The release job packages the desktop app as a signed archive on the Linux runner.","sentence_zh":"发布任务会在 Linux 运行器上把桌面应用打包成已签名的压缩包。","add_node_ids":["linux-runner"],"add_link_ids":["linux-runner->package-app"],"focus_node_id":"linux-runner","note_zh":"最后交代打包实际发生的位置。"}]}'
  ),
  (
    'pad-primary',
    'pad',
    'pad',
    'pad records with zeroes',
    '用填充值补足数据长度',
    'The serializer pads each record.',
    '序列化程序会填充每条记录。',
    'The serializer pads each record to 256 bytes with zeroes.',
    '序列化程序会用零把每条记录填充到 256 字节。',
    'binary-serialization',
    '{"schema_version":2,"root_action_id":"pad-record","nodes":[{"id":"pad-record","text":"pads","kind":"action","label_zh":"补足记录长度"},{"id":"serializer","text":"The serializer","kind":"core","label_zh":"执行填充的序列化程序"},{"id":"each-record","text":"each record","kind":"core","label_zh":"逐条接受填充的记录"},{"id":"byte-limit","text":"to 256 bytes","kind":"modifier","label_zh":"每条记录需要达到的长度"},{"id":"zero-padding","text":"with zeroes","kind":"modifier","label_zh":"用于补齐空位的数值"}],"links":[{"id":"pad-record->serializer","from":"pad-record","to":"serializer","kind":"core","relation_type":"actor","label_zh":"序列化程序负责填充记录"},{"id":"pad-record->each-record","from":"pad-record","to":"each-record","kind":"core","relation_type":"target","label_zh":"填充作用于每一条记录"},{"id":"byte-limit->pad-record","from":"byte-limit","to":"pad-record","kind":"modifier","relation_type":"result","label_zh":"限定填充完成后的记录长度"},{"id":"zero-padding->pad-record","from":"zero-padding","to":"pad-record","kind":"modifier","relation_type":"manner","label_zh":"说明空余字节用零来补齐"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The serializer pads each record.","sentence_zh":"序列化程序会填充每条记录。","add_node_ids":["pad-record","serializer","each-record"],"add_link_ids":["pad-record->serializer","pad-record->each-record"],"focus_node_id":"pad-record","note_zh":"主干先呈现记录填充这一处理。"},{"step_no":2,"label":"目标长度","sentence_en":"The serializer pads each record to 256 bytes.","sentence_zh":"序列化程序会把每条记录填充到 256 字节。","add_node_ids":["byte-limit"],"add_link_ids":["byte-limit->pad-record"],"focus_node_id":"byte-limit","note_zh":"加入填充完成时必须达到的尺寸。"},{"step_no":3,"label":"填充值","sentence_en":"The serializer pads each record to 256 bytes with zeroes.","sentence_zh":"序列化程序会用零把每条记录填充到 256 字节。","add_node_ids":["zero-padding"],"add_link_ids":["zero-padding->pad-record"],"focus_node_id":"zero-padding","note_zh":"指出新增字节具体使用什么内容。"}]}'
  ),
  (
    'paint-primary',
    'paint',
    'paint',
    'paint a wall green',
    '给墙面涂上颜色',
    'Maya painted the nursery wall.',
    'Maya 给育儿室的墙刷了漆。',
    'Maya painted the nursery wall a soft green before the baby arrived.',
    'Maya 在宝宝到来之前把育儿室的墙刷成了柔和的绿色。',
    'nursery-renovation',
    '{"schema_version":2,"root_action_id":"paint-wall","nodes":[{"id":"paint-wall","text":"painted","kind":"action","label_zh":"给育儿室墙面上漆"},{"id":"maya","text":"Maya","kind":"core","label_zh":"负责刷墙的人"},{"id":"nursery-wall","text":"the nursery wall","kind":"core","label_zh":"接受涂漆的墙面"},{"id":"soft-green","text":"a soft green","kind":"modifier","label_zh":"墙面最终呈现的柔和绿色"},{"id":"baby-arrive","text":"arrived","kind":"action","label_zh":"宝宝来到家中"},{"id":"baby","text":"the baby","kind":"core","label_zh":"之后到来的宝宝"}],"links":[{"id":"paint-wall->maya","from":"paint-wall","to":"maya","kind":"core","relation_type":"actor","label_zh":"Maya 完成了墙面涂漆"},{"id":"paint-wall->nursery-wall","from":"paint-wall","to":"nursery-wall","kind":"core","relation_type":"target","label_zh":"油漆涂在育儿室墙面上"},{"id":"soft-green->paint-wall","from":"soft-green","to":"paint-wall","kind":"modifier","relation_type":"result","label_zh":"说明刷完后墙面的颜色"},{"id":"baby-arrive->baby","from":"baby-arrive","to":"baby","kind":"core","relation_type":"actor","label_zh":"到来的是宝宝"},{"id":"baby-arrive->paint-wall","from":"baby-arrive","to":"paint-wall","kind":"modifier","relation_type":"time","label_zh":"宝宝到来为刷墙设定了时间界限"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Maya painted the nursery wall.","sentence_zh":"Maya 给育儿室的墙刷了漆。","add_node_ids":["paint-wall","maya","nursery-wall"],"add_link_ids":["paint-wall->maya","paint-wall->nursery-wall"],"focus_node_id":"paint-wall","note_zh":"先建立人物、涂漆动作和墙面。"},{"step_no":2,"label":"墙面颜色","sentence_en":"Maya painted the nursery wall a soft green.","sentence_zh":"Maya 把育儿室的墙刷成了柔和的绿色。","add_node_ids":["soft-green"],"add_link_ids":["soft-green->paint-wall"],"focus_node_id":"soft-green","note_zh":"颜色说明墙面刷完后的样子。"},{"step_no":3,"label":"完成时机","sentence_en":"Maya painted the nursery wall a soft green before the baby arrived.","sentence_zh":"Maya 在宝宝到来之前把育儿室的墙刷成了柔和的绿色。","add_node_ids":["baby-arrive","baby"],"add_link_ids":["baby-arrive->baby","baby-arrive->paint-wall"],"focus_node_id":"baby-arrive","note_zh":"用宝宝到来这一事件界定刷墙时间。"}]}'
  ),
  (
    'pan-out-primary',
    'pan-out',
    'pan out',
    'pan out well',
    '取得令人满意的结果',
    'The caching experiment panned out.',
    '缓存实验取得了成效。',
    'The caching experiment panned out remarkably well under peak traffic.',
    '缓存实验在流量高峰下仍取得了非常理想的成效。',
    'cache-experiment',
    '{"schema_version":2,"root_action_id":"experiment-pan-out","nodes":[{"id":"experiment-pan-out","text":"panned out","kind":"action","label_zh":"实验取得了实际成效"},{"id":"caching-experiment","text":"The caching experiment","kind":"core","label_zh":"接受结果检验的缓存实验"},{"id":"remarkably-well","text":"remarkably well","kind":"modifier","label_zh":"实验结果非常理想"},{"id":"peak-traffic","text":"under peak traffic","kind":"modifier","label_zh":"检验实验的高流量条件"}],"links":[{"id":"experiment-pan-out->caching-experiment","from":"experiment-pan-out","to":"caching-experiment","kind":"core","relation_type":"actor","label_zh":"缓存实验最终获得了成效"},{"id":"remarkably-well->experiment-pan-out","from":"remarkably-well","to":"experiment-pan-out","kind":"modifier","relation_type":"degree","label_zh":"强调实验成功的程度"},{"id":"peak-traffic->experiment-pan-out","from":"peak-traffic","to":"experiment-pan-out","kind":"modifier","relation_type":"condition","label_zh":"说明实验在高峰流量下仍然有效"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The caching experiment panned out.","sentence_zh":"缓存实验取得了成效。","add_node_ids":["experiment-pan-out","caching-experiment"],"add_link_ids":["experiment-pan-out->caching-experiment"],"focus_node_id":"experiment-pan-out","note_zh":"这里的 pan out 表示方案最终有效。"},{"step_no":2,"label":"成功程度","sentence_en":"The caching experiment panned out remarkably well.","sentence_zh":"缓存实验取得了非常理想的成效。","add_node_ids":["remarkably-well"],"add_link_ids":["remarkably-well->experiment-pan-out"],"focus_node_id":"remarkably-well","note_zh":"加入程度，突出结果不只是勉强可用。"},{"step_no":3,"label":"检验条件","sentence_en":"The caching experiment panned out remarkably well under peak traffic.","sentence_zh":"缓存实验在流量高峰下仍取得了非常理想的成效。","add_node_ids":["peak-traffic"],"add_link_ids":["peak-traffic->experiment-pan-out"],"focus_node_id":"peak-traffic","note_zh":"高流量条件让成功结果更有说服力。"}]}'
  ),
  (
    'panic-primary',
    'panic',
    'panic',
    'panic during an outage',
    '因突发问题而惊慌',
    'The on-call engineer panicked.',
    '值班工程师慌了。',
    'The on-call engineer panicked for a moment when every health check turned red.',
    '当所有健康检查都变成红色时，值班工程师慌了一下。',
    'service-outage',
    '{"schema_version":2,"root_action_id":"engineer-panic","nodes":[{"id":"engineer-panic","text":"panicked","kind":"action","label_zh":"值班工程师一时惊慌"},{"id":"on-call-engineer","text":"The on-call engineer","kind":"core","label_zh":"面对告警的值班工程师"},{"id":"brief-moment","text":"for a moment","kind":"modifier","label_zh":"惊慌只持续了片刻"},{"id":"checks-turn-red","text":"turned red","kind":"action","label_zh":"健康检查全部变为红色"},{"id":"health-checks","text":"every health check","kind":"core","label_zh":"同时显示异常的全部检查"}],"links":[{"id":"engineer-panic->on-call-engineer","from":"engineer-panic","to":"on-call-engineer","kind":"core","relation_type":"actor","label_zh":"值班工程师产生了惊慌反应"},{"id":"brief-moment->engineer-panic","from":"brief-moment","to":"engineer-panic","kind":"modifier","relation_type":"time","label_zh":"限定惊慌持续的短暂时间"},{"id":"checks-turn-red->health-checks","from":"checks-turn-red","to":"health-checks","kind":"core","relation_type":"actor","label_zh":"所有健康检查都变成红色"},{"id":"checks-turn-red->engineer-panic","from":"checks-turn-red","to":"engineer-panic","kind":"modifier","relation_type":"reason","label_zh":"检查同时变红引发了工程师的惊慌"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The on-call engineer panicked.","sentence_zh":"值班工程师慌了。","add_node_ids":["engineer-panic","on-call-engineer"],"add_link_ids":["engineer-panic->on-call-engineer"],"focus_node_id":"engineer-panic","note_zh":"先呈现值班人员的情绪反应。"},{"step_no":2,"label":"持续时间","sentence_en":"The on-call engineer panicked for a moment.","sentence_zh":"值班工程师慌了一下。","add_node_ids":["brief-moment"],"add_link_ids":["brief-moment->engineer-panic"],"focus_node_id":"brief-moment","note_zh":"短时间信息避免把反应理解成持续失控。"},{"step_no":3,"label":"触发原因","sentence_en":"The on-call engineer panicked for a moment when every health check turned red.","sentence_zh":"当所有健康检查都变成红色时，值班工程师慌了一下。","add_node_ids":["checks-turn-red","health-checks"],"add_link_ids":["checks-turn-red->health-checks","checks-turn-red->engineer-panic"],"focus_node_id":"checks-turn-red","note_zh":"最后补出导致惊慌的异常事件。"}]}'
  ),
  (
    'park-primary',
    'park',
    'park',
    'park a migration',
    '暂时搁置一项工作',
    'The team parked the migration.',
    '团队暂时搁置了迁移工作。',
    'The team parked the migration in the backlog until the audit ends.',
    '团队把迁移工作暂时搁置在待办列表中，直到审计结束。',
    'migration-planning',
    '{"schema_version":2,"root_action_id":"park-migration","nodes":[{"id":"park-migration","text":"parked","kind":"action","label_zh":"暂时停止推进迁移"},{"id":"team","text":"The team","kind":"core","label_zh":"决定搁置工作的团队"},{"id":"migration","text":"the migration","kind":"core","label_zh":"暂不继续推进的迁移任务"},{"id":"backlog","text":"in the backlog","kind":"modifier","label_zh":"迁移暂时存放的工作列表"},{"id":"audit-end","text":"ends","kind":"action","label_zh":"审计工作结束"},{"id":"audit","text":"the audit","kind":"core","label_zh":"决定等待期限的审计"}],"links":[{"id":"park-migration->team","from":"park-migration","to":"team","kind":"core","relation_type":"actor","label_zh":"团队作出了搁置决定"},{"id":"park-migration->migration","from":"park-migration","to":"migration","kind":"core","relation_type":"target","label_zh":"被搁置的是迁移任务"},{"id":"backlog->park-migration","from":"backlog","to":"park-migration","kind":"modifier","relation_type":"place","label_zh":"迁移被暂放在待办列表中"},{"id":"audit-end->audit","from":"audit-end","to":"audit","kind":"core","relation_type":"actor","label_zh":"需要先结束的是审计"},{"id":"audit-end->park-migration","from":"audit-end","to":"park-migration","kind":"modifier","relation_type":"time","label_zh":"审计结束标志着搁置期限的终点"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team parked the migration.","sentence_zh":"团队暂时搁置了迁移工作。","add_node_ids":["park-migration","team","migration"],"add_link_ids":["park-migration->team","park-migration->migration"],"focus_node_id":"park-migration","note_zh":"park 在这里表示暂不推进工作。"},{"step_no":2,"label":"搁置位置","sentence_en":"The team parked the migration in the backlog.","sentence_zh":"团队把迁移工作暂时搁置在待办列表中。","add_node_ids":["backlog"],"add_link_ids":["backlog->park-migration"],"focus_node_id":"backlog","note_zh":"待办列表表明任务没有被取消。"},{"step_no":3,"label":"恢复节点","sentence_en":"The team parked the migration in the backlog until the audit ends.","sentence_zh":"团队把迁移工作暂时搁置在待办列表中，直到审计结束。","add_node_ids":["audit-end","audit"],"add_link_ids":["audit-end->audit","audit-end->park-migration"],"focus_node_id":"audit-end","note_zh":"审计结束为暂停安排提供明确界限。"}]}'
  ),
  (
    'parse-config-file',
    'parse',
    'parse',
    'parse a config file',
    '解析配置文件中的结构化内容',
    'The loader parses the config file.',
    '加载程序会解析配置文件。',
    'The loader parses the config file into a typed object at startup.',
    '加载程序会在启动时把配置文件解析成类型化对象。',
    'application-startup',
    '{"schema_version":2,"root_action_id":"parse-config","nodes":[{"id":"parse-config","text":"parses","kind":"action","label_zh":"读取并解析配置结构"},{"id":"loader","text":"The loader","kind":"core","label_zh":"负责解析配置的加载程序"},{"id":"config-file","text":"the config file","kind":"core","label_zh":"提供配置数据的文件"},{"id":"typed-object","text":"into a typed object","kind":"modifier","label_zh":"解析后形成的类型化对象"},{"id":"startup","text":"at startup","kind":"modifier","label_zh":"配置解析发生的启动阶段"}],"links":[{"id":"parse-config->loader","from":"parse-config","to":"loader","kind":"core","relation_type":"actor","label_zh":"加载程序执行配置解析"},{"id":"parse-config->config-file","from":"parse-config","to":"config-file","kind":"core","relation_type":"target","label_zh":"解析处理的是配置文件"},{"id":"typed-object->parse-config","from":"typed-object","to":"parse-config","kind":"modifier","relation_type":"result","label_zh":"说明配置内容被转换成什么结构"},{"id":"startup->parse-config","from":"startup","to":"parse-config","kind":"modifier","relation_type":"time","label_zh":"指出解析在应用启动时进行"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The loader parses the config file.","sentence_zh":"加载程序会解析配置文件。","add_node_ids":["parse-config","loader","config-file"],"add_link_ids":["parse-config->loader","parse-config->config-file"],"focus_node_id":"parse-config","note_zh":"核心信息是加载程序读取配置结构。"},{"step_no":2,"label":"解析结果","sentence_en":"The loader parses the config file into a typed object.","sentence_zh":"加载程序会把配置文件解析成类型化对象。","add_node_ids":["typed-object"],"add_link_ids":["typed-object->parse-config"],"focus_node_id":"typed-object","note_zh":"补充解析完成后产生的数据形式。"},{"step_no":3,"label":"执行阶段","sentence_en":"The loader parses the config file into a typed object at startup.","sentence_zh":"加载程序会在启动时把配置文件解析成类型化对象。","add_node_ids":["startup"],"add_link_ids":["startup->parse-config"],"focus_node_id":"startup","note_zh":"启动阶段说明这项处理何时发生。"}]}'
  ),
  (
    'participate-primary',
    'participate',
    'participate',
    'participate in a review',
    '参加一项集体活动',
    'Three interns participated in the incident review.',
    '三名实习生参加了事故复盘。',
    'Three interns participated in the incident review remotely on Friday morning.',
    '三名实习生在周五上午远程参加了事故复盘。',
    'incident-review',
    '{"schema_version":2,"root_action_id":"participate-review","nodes":[{"id":"participate-review","text":"participated","kind":"action","label_zh":"参加事故复盘会议"},{"id":"three-interns","text":"Three interns","kind":"core","label_zh":"加入复盘的三名实习生"},{"id":"incident-review","text":"the incident review","kind":"core","label_zh":"实习生参与的复盘活动"},{"id":"remotely","text":"remotely","kind":"modifier","label_zh":"通过远程方式加入"},{"id":"friday-morning","text":"on Friday morning","kind":"modifier","label_zh":"复盘安排在周五上午"}],"links":[{"id":"participate-review->three-interns","from":"participate-review","to":"three-interns","kind":"core","relation_type":"actor","label_zh":"三名实习生参加了活动"},{"id":"participate-review->incident-review","from":"participate-review","to":"incident-review","kind":"core","relation_type":"category","label_zh":"他们参加的是事故复盘"},{"id":"remotely->participate-review","from":"remotely","to":"participate-review","kind":"modifier","relation_type":"manner","label_zh":"说明实习生采用远程方式参与"},{"id":"friday-morning->participate-review","from":"friday-morning","to":"participate-review","kind":"modifier","relation_type":"time","label_zh":"给出参加复盘的具体时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Three interns participated in the incident review.","sentence_zh":"三名实习生参加了事故复盘。","add_node_ids":["participate-review","three-interns","incident-review"],"add_link_ids":["participate-review->three-interns","participate-review->incident-review"],"focus_node_id":"participate-review","note_zh":"participate 通常与 in 连用来引出所参加的活动。"},{"step_no":2,"label":"参与方式","sentence_en":"Three interns participated in the incident review remotely.","sentence_zh":"三名实习生远程参加了事故复盘。","add_node_ids":["remotely"],"add_link_ids":["remotely->participate-review"],"focus_node_id":"remotely","note_zh":"远程方式说明他们不必到达现场。"},{"step_no":3,"label":"会议时间","sentence_en":"Three interns participated in the incident review remotely on Friday morning.","sentence_zh":"三名实习生在周五上午远程参加了事故复盘。","add_node_ids":["friday-morning"],"add_link_ids":["friday-morning->participate-review"],"focus_node_id":"friday-morning","note_zh":"时间信息完成这次参与的场景。"}]}'
  ),
  (
    'partition-primary',
    'partition',
    'partition',
    'partition incoming events',
    '把数据划分到不同分区',
    'The database service partitions incoming events.',
    '数据库服务会对传入的事件进行分区。',
    'The database service partitions incoming events by customer ID across twelve shards.',
    '数据库服务会按照客户 ID，把传入的事件分布到十二个分片中。',
    'event-streaming',
    '{"schema_version":2,"root_action_id":"partition-events","nodes":[{"id":"partition-events","text":"partitions","kind":"action","label_zh":"把事件划入不同分区"},{"id":"database-service","text":"The database service","kind":"core","label_zh":"负责事件分区的数据库服务"},{"id":"incoming-events","text":"incoming events","kind":"core","label_zh":"持续进入系统的事件数据"},{"id":"customer-key","text":"by customer ID","kind":"modifier","label_zh":"决定分区归属的客户标识"},{"id":"twelve-shards","text":"across twelve shards","kind":"modifier","label_zh":"事件分布覆盖的十二个分片"}],"links":[{"id":"partition-events->database-service","from":"partition-events","to":"database-service","kind":"core","relation_type":"actor","label_zh":"数据库服务执行事件分区"},{"id":"partition-events->incoming-events","from":"partition-events","to":"incoming-events","kind":"core","relation_type":"target","label_zh":"被划分的是新进入的事件"},{"id":"customer-key->partition-events","from":"customer-key","to":"partition-events","kind":"modifier","relation_type":"category","label_zh":"客户标识决定每个事件所属分区"},{"id":"twelve-shards->partition-events","from":"twelve-shards","to":"partition-events","kind":"modifier","relation_type":"scope","label_zh":"说明分区结果分布在多少个分片上"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The database service partitions incoming events.","sentence_zh":"数据库服务会对传入的事件进行分区。","add_node_ids":["partition-events","database-service","incoming-events"],"add_link_ids":["partition-events->database-service","partition-events->incoming-events"],"focus_node_id":"partition-events","note_zh":"先说明系统正在划分哪类数据。"},{"step_no":2,"label":"分区依据","sentence_en":"The database service partitions incoming events by customer ID.","sentence_zh":"数据库服务会按照客户 ID 对传入的事件进行分区。","add_node_ids":["customer-key"],"add_link_ids":["customer-key->partition-events"],"focus_node_id":"customer-key","note_zh":"客户 ID 提供稳定的分组规则。"},{"step_no":3,"label":"分布范围","sentence_en":"The database service partitions incoming events by customer ID across twelve shards.","sentence_zh":"数据库服务会按照客户 ID，把传入的事件分布到十二个分片中。","add_node_ids":["twelve-shards"],"add_link_ids":["twelve-shards->partition-events"],"focus_node_id":"twelve-shards","note_zh":"分片数量展示数据最终分布的范围。"}]}'
  ),
  (
    'partner-primary',
    'partner',
    'partner',
    'partner with a lab',
    '与另一个组织合作',
    'Our security team partnered with an external lab.',
    '我们的安全团队与一家外部实验室展开了合作。',
    'Our security team partnered with an external lab on the penetration test last quarter.',
    '上个季度，我们的安全团队与一家外部实验室合作开展了渗透测试。',
    'security-assessment',
    '{"schema_version":2,"root_action_id":"partner-lab","nodes":[{"id":"partner-lab","text":"partnered","kind":"action","label_zh":"与外部机构建立合作"},{"id":"security-team","text":"Our security team","kind":"core","label_zh":"发起合作的内部安全团队"},{"id":"external-lab","text":"an external lab","kind":"core","label_zh":"共同工作的外部实验室"},{"id":"penetration-test","text":"the penetration test","kind":"core","label_zh":"双方共同开展的渗透测试"},{"id":"last-quarter","text":"last quarter","kind":"modifier","label_zh":"合作发生在上个季度"}],"links":[{"id":"partner-lab->security-team","from":"partner-lab","to":"security-team","kind":"core","relation_type":"actor","label_zh":"安全团队参与了这次合作"},{"id":"partner-lab->external-lab","from":"partner-lab","to":"external-lab","kind":"core","relation_type":"recipient","label_zh":"安全团队选择外部实验室作为合作方"},{"id":"partner-lab->penetration-test","from":"partner-lab","to":"penetration-test","kind":"core","relation_type":"content","label_zh":"合作围绕渗透测试展开"},{"id":"last-quarter->partner-lab","from":"last-quarter","to":"partner-lab","kind":"modifier","relation_type":"time","label_zh":"指出双方开展合作的季度"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Our security team partnered with an external lab.","sentence_zh":"我们的安全团队与一家外部实验室展开了合作。","add_node_ids":["partner-lab","security-team","external-lab"],"add_link_ids":["partner-lab->security-team","partner-lab->external-lab"],"focus_node_id":"partner-lab","note_zh":"partner with 自然引出共同工作的另一方。"},{"step_no":2,"label":"合作事项","sentence_en":"Our security team partnered with an external lab on the penetration test.","sentence_zh":"我们的安全团队与一家外部实验室合作开展了渗透测试。","add_node_ids":["penetration-test"],"add_link_ids":["partner-lab->penetration-test"],"focus_node_id":"penetration-test","note_zh":"渗透测试说明双方具体合作什么。"},{"step_no":3,"label":"合作时间","sentence_en":"Our security team partnered with an external lab on the penetration test last quarter.","sentence_zh":"上个季度，我们的安全团队与一家外部实验室合作开展了渗透测试。","add_node_ids":["last-quarter"],"add_link_ids":["last-quarter->partner-lab"],"focus_node_id":"last-quarter","note_zh":"季度信息把合作放入明确的工作周期。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'pass-primary',
    'pass',
    'pass',
    'pass a token to a service',
    '把数据传递给另一个服务',
    'The router passes the token.',
    '路由器会传递令牌。',
    'The router passes the token to the billing service through an encrypted header.',
    '路由器会通过加密请求头把令牌传给计费服务。',
    'service-routing',
    '{"schema_version":2,"root_action_id":"pass-token","nodes":[{"id":"pass-token","text":"passes","kind":"action","label_zh":"把令牌继续传给下游"},{"id":"router","text":"The router","kind":"core","label_zh":"负责转交令牌的路由器"},{"id":"token","text":"the token","kind":"core","label_zh":"在服务间传递的令牌"},{"id":"billing-service","text":"the billing service","kind":"core","label_zh":"接收令牌的计费服务"},{"id":"encrypted-header","text":"through an encrypted header","kind":"modifier","label_zh":"承载令牌的加密请求头"}],"links":[{"id":"pass-token->router","from":"pass-token","to":"router","kind":"core","relation_type":"actor","label_zh":"路由器执行令牌转交"},{"id":"pass-token->token","from":"pass-token","to":"token","kind":"core","relation_type":"target","label_zh":"被传递的是访问令牌"},{"id":"pass-token->billing-service","from":"pass-token","to":"billing-service","kind":"core","relation_type":"recipient","label_zh":"计费服务接收该令牌"},{"id":"encrypted-header->pass-token","from":"encrypted-header","to":"pass-token","kind":"modifier","relation_type":"manner","label_zh":"说明令牌通过加密请求头传送"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The router passes the token.","sentence_zh":"路由器会传递令牌。","add_node_ids":["pass-token","router","token"],"add_link_ids":["pass-token->router","pass-token->token"],"focus_node_id":"pass-token","note_zh":"主干先保留令牌转交这一核心处理。"},{"step_no":2,"label":"接收服务","sentence_en":"The router passes the token to the billing service.","sentence_zh":"路由器会把令牌传给计费服务。","add_node_ids":["billing-service"],"add_link_ids":["pass-token->billing-service"],"focus_node_id":"billing-service","note_zh":"加入下游服务后，传递方向变得明确。"},{"step_no":3,"label":"传递通道","sentence_en":"The router passes the token to the billing service through an encrypted header.","sentence_zh":"路由器会通过加密请求头把令牌传给计费服务。","add_node_ids":["encrypted-header"],"add_link_ids":["encrypted-header->pass-token"],"focus_node_id":"encrypted-header","note_zh":"加密请求头交代令牌采用的传送方式。"}]}'
  ),
  (
    'pass-on-primary',
    'pass-on',
    'pass on',
    'pass on deployment notes',
    '把信息转交给其他人',
    'Nina passed on the deployment notes.',
    'Nina 转交了部署记录。',
    'Nina passed on the deployment notes to the night shift before leaving the office.',
    'Nina 在离开办公室前把部署记录转交给了夜班团队。',
    'shift-handover',
    '{"schema_version":2,"root_action_id":"pass-on-notes","nodes":[{"id":"pass-on-notes","text":"passed on","kind":"action","label_zh":"转交部署记录"},{"id":"nina","text":"Nina","kind":"core","label_zh":"完成交接的工程师"},{"id":"deployment-notes","text":"the deployment notes","kind":"core","label_zh":"需要交给下一班的部署记录"},{"id":"night-shift","text":"the night shift","kind":"core","label_zh":"接收记录的夜班团队"},{"id":"leave-office","text":"leaving","kind":"action","label_zh":"离开办公室"},{"id":"office","text":"the office","kind":"core","label_zh":"Nina 离开的工作地点"}],"links":[{"id":"pass-on-notes->nina","from":"pass-on-notes","to":"nina","kind":"core","relation_type":"actor","label_zh":"Nina 负责转交部署记录"},{"id":"pass-on-notes->deployment-notes","from":"pass-on-notes","to":"deployment-notes","kind":"core","relation_type":"target","label_zh":"被转交的是部署记录"},{"id":"pass-on-notes->night-shift","from":"pass-on-notes","to":"night-shift","kind":"core","relation_type":"recipient","label_zh":"夜班团队接收这些记录"},{"id":"leave-office->nina","from":"leave-office","to":"nina","kind":"core","relation_type":"shared_actor","label_zh":"离开办公室的人同样是 Nina"},{"id":"leave-office->office","from":"leave-office","to":"office","kind":"core","relation_type":"target","label_zh":"Nina 离开的是办公室"},{"id":"leave-office->pass-on-notes","from":"leave-office","to":"pass-on-notes","kind":"modifier","relation_type":"time","label_zh":"记录转交发生在 Nina 离开之前"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Nina passed on the deployment notes.","sentence_zh":"Nina 转交了部署记录。","add_node_ids":["pass-on-notes","nina","deployment-notes"],"add_link_ids":["pass-on-notes->nina","pass-on-notes->deployment-notes"],"focus_node_id":"pass-on-notes","note_zh":"pass on 在这里强调把信息继续交给别人。"},{"step_no":2,"label":"接收班次","sentence_en":"Nina passed on the deployment notes to the night shift.","sentence_zh":"Nina 把部署记录转交给了夜班团队。","add_node_ids":["night-shift"],"add_link_ids":["pass-on-notes->night-shift"],"focus_node_id":"night-shift","note_zh":"夜班团队补全了交接方向。"},{"step_no":3,"label":"离开之前","sentence_en":"Nina passed on the deployment notes to the night shift before leaving the office.","sentence_zh":"Nina 在离开办公室前把部署记录转交给了夜班团队。","add_node_ids":["leave-office","office"],"add_link_ids":["leave-office->nina","leave-office->office","leave-office->pass-on-notes"],"focus_node_id":"leave-office","note_zh":"离开办公室这一动作确定交接已经及时完成。"}]}'
  ),
  (
    'paste-primary',
    'paste',
    'paste',
    'paste a stack trace',
    '把已复制的文本粘贴到另一处',
    'I pasted the stack trace.',
    '我粘贴了错误堆栈。',
    'I pasted the stack trace into the bug report without customer data.',
    '我把不含客户数据的错误堆栈粘贴到了错误报告中。',
    'bug-reporting',
    '{"schema_version":2,"root_action_id":"paste-trace","nodes":[{"id":"paste-trace","text":"pasted","kind":"action","label_zh":"粘贴错误堆栈文本"},{"id":"speaker","text":"I","kind":"core","label_zh":"提交错误信息的人"},{"id":"stack-trace","text":"the stack trace","kind":"core","label_zh":"被粘贴的错误堆栈"},{"id":"bug-report","text":"the bug report","kind":"core","label_zh":"接收堆栈内容的错误报告"},{"id":"no-customer-data","text":"without customer data","kind":"modifier","label_zh":"粘贴内容不包含客户数据"}],"links":[{"id":"paste-trace->speaker","from":"paste-trace","to":"speaker","kind":"core","relation_type":"actor","label_zh":"说话者执行了粘贴"},{"id":"paste-trace->stack-trace","from":"paste-trace","to":"stack-trace","kind":"core","relation_type":"target","label_zh":"粘贴的是错误堆栈"},{"id":"paste-trace->bug-report","from":"paste-trace","to":"bug-report","kind":"core","relation_type":"recipient","label_zh":"错误报告接收了堆栈文本"},{"id":"no-customer-data->paste-trace","from":"no-customer-data","to":"paste-trace","kind":"modifier","relation_type":"scope","label_zh":"限定粘贴内容排除了客户数据"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I pasted the stack trace.","sentence_zh":"我粘贴了错误堆栈。","add_node_ids":["paste-trace","speaker","stack-trace"],"add_link_ids":["paste-trace->speaker","paste-trace->stack-trace"],"focus_node_id":"paste-trace","note_zh":"先建立粘贴动作和被复制的技术文本。"},{"step_no":2,"label":"粘贴位置","sentence_en":"I pasted the stack trace into the bug report.","sentence_zh":"我把错误堆栈粘贴到了错误报告中。","add_node_ids":["bug-report"],"add_link_ids":["paste-trace->bug-report"],"focus_node_id":"bug-report","note_zh":"错误报告说明文本最终进入哪里。"},{"step_no":3,"label":"内容范围","sentence_en":"I pasted the stack trace into the bug report without customer data.","sentence_zh":"我把不含客户数据的错误堆栈粘贴到了错误报告中。","add_node_ids":["no-customer-data"],"add_link_ids":["no-customer-data->paste-trace"],"focus_node_id":"no-customer-data","note_zh":"排除客户数据体现了信息处理边界。"}]}'
  ),
  (
    'pat-primary',
    'pat',
    'pat',
    'pat a child gently',
    '用手轻拍以表示安抚',
    'The nurse patted the child.',
    '护士轻拍了孩子。',
    'The nurse patted the child gently to offer reassurance.',
    '护士轻柔地拍了拍孩子，以表达安慰。',
    'clinic-comfort',
    '{"schema_version":2,"root_action_id":"pat-child","nodes":[{"id":"pat-child","text":"patted","kind":"action","label_zh":"轻拍孩子给予安抚"},{"id":"nurse","text":"The nurse","kind":"core","label_zh":"伸手安抚孩子的护士"},{"id":"child","text":"the child","kind":"core","label_zh":"接受轻拍的孩子"},{"id":"gently","text":"gently","kind":"modifier","label_zh":"动作轻柔而克制"},{"id":"offer-reassurance","text":"offer","kind":"action","label_zh":"向孩子表达安慰"},{"id":"reassurance","text":"reassurance","kind":"core","label_zh":"护士希望传达的安心感"}],"links":[{"id":"pat-child->nurse","from":"pat-child","to":"nurse","kind":"core","relation_type":"actor","label_zh":"护士做出了轻拍动作"},{"id":"pat-child->child","from":"pat-child","to":"child","kind":"core","relation_type":"target","label_zh":"轻拍落在孩子身上"},{"id":"gently->pat-child","from":"gently","to":"pat-child","kind":"modifier","relation_type":"manner","label_zh":"说明护士轻柔地拍了孩子"},{"id":"offer-reassurance->nurse","from":"offer-reassurance","to":"nurse","kind":"core","relation_type":"shared_actor","label_zh":"提供安慰的同样是护士"},{"id":"offer-reassurance->reassurance","from":"offer-reassurance","to":"reassurance","kind":"core","relation_type":"content","label_zh":"护士通过动作传达安慰"},{"id":"offer-reassurance->pat-child","from":"offer-reassurance","to":"pat-child","kind":"modifier","relation_type":"purpose","label_zh":"轻拍是为了让孩子感到安心"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The nurse patted the child.","sentence_zh":"护士轻拍了孩子。","add_node_ids":["pat-child","nurse","child"],"add_link_ids":["pat-child->nurse","pat-child->child"],"focus_node_id":"pat-child","note_zh":"pat 表示短促、轻柔的拍触。"},{"step_no":2,"label":"动作方式","sentence_en":"The nurse patted the child gently.","sentence_zh":"护士轻柔地拍了拍孩子。","add_node_ids":["gently"],"add_link_ids":["gently->pat-child"],"focus_node_id":"gently","note_zh":"gently 明确动作没有用力。"},{"step_no":3,"label":"安抚目的","sentence_en":"The nurse patted the child gently to offer reassurance.","sentence_zh":"护士轻柔地拍了拍孩子，以表达安慰。","add_node_ids":["offer-reassurance","reassurance"],"add_link_ids":["offer-reassurance->nurse","offer-reassurance->reassurance","offer-reassurance->pat-child"],"focus_node_id":"offer-reassurance","note_zh":"提供安慰解释了护士为何轻拍孩子。"}]}'
  ),
  (
    'patch-primary',
    'patch',
    'patch',
    'patch an authentication bug',
    '通过修改代码修复漏洞或缺陷',
    'Ravi patched the authentication bug.',
    'Ravi 修补了认证缺陷。',
    'Ravi patched the authentication bug in the mobile client within an hour.',
    'Ravi 在一小时内修补了移动客户端中的认证缺陷。',
    'mobile-hotfix',
    '{"schema_version":2,"root_action_id":"patch-bug","nodes":[{"id":"patch-bug","text":"patched","kind":"action","label_zh":"用代码修改修复认证缺陷"},{"id":"ravi","text":"Ravi","kind":"core","label_zh":"完成紧急修复的开发者"},{"id":"authentication-bug","text":"the authentication bug","kind":"core","label_zh":"需要修补的认证缺陷"},{"id":"mobile-client","text":"in the mobile client","kind":"modifier","label_zh":"缺陷所在的移动客户端"},{"id":"one-hour","text":"within an hour","kind":"modifier","label_zh":"完成修复所用的最长时间"}],"links":[{"id":"patch-bug->ravi","from":"patch-bug","to":"ravi","kind":"core","relation_type":"actor","label_zh":"Ravi 编写并应用了补丁"},{"id":"patch-bug->authentication-bug","from":"patch-bug","to":"authentication-bug","kind":"core","relation_type":"target","label_zh":"补丁处理的是认证缺陷"},{"id":"mobile-client->authentication-bug","from":"mobile-client","to":"authentication-bug","kind":"modifier","relation_type":"place","label_zh":"指出认证缺陷存在于移动客户端"},{"id":"one-hour->patch-bug","from":"one-hour","to":"patch-bug","kind":"modifier","relation_type":"time","label_zh":"限定 Ravi 完成修复的时间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Ravi patched the authentication bug.","sentence_zh":"Ravi 修补了认证缺陷。","add_node_ids":["patch-bug","ravi","authentication-bug"],"add_link_ids":["patch-bug->ravi","patch-bug->authentication-bug"],"focus_node_id":"patch-bug","note_zh":"技术场景中的 patch 常表示用补丁修复问题。"},{"step_no":2,"label":"缺陷位置","sentence_en":"Ravi patched the authentication bug in the mobile client.","sentence_zh":"Ravi 修补了移动客户端中的认证缺陷。","add_node_ids":["mobile-client"],"add_link_ids":["mobile-client->authentication-bug"],"focus_node_id":"mobile-client","note_zh":"移动客户端直接说明是哪一处认证缺陷。"},{"step_no":3,"label":"修复速度","sentence_en":"Ravi patched the authentication bug in the mobile client within an hour.","sentence_zh":"Ravi 在一小时内修补了移动客户端中的认证缺陷。","add_node_ids":["one-hour"],"add_link_ids":["one-hour->patch-bug"],"focus_node_id":"one-hour","note_zh":"时间限制突出这次修复的紧急程度。"}]}'
  ),
  (
    'pause-primary',
    'pause',
    'pause',
    'pause a rollout',
    '暂时停止正在进行的发布',
    'The operator paused the rollout.',
    '操作人员暂停了版本发布。',
    'The operator paused the rollout for ten minutes after the error rate doubled.',
    '错误率翻倍后，操作人员暂停了版本发布十分钟。',
    'rollout-monitoring',
    '{"schema_version":2,"root_action_id":"pause-rollout","nodes":[{"id":"pause-rollout","text":"paused","kind":"action","label_zh":"暂时停止发布进程"},{"id":"operator","text":"The operator","kind":"core","label_zh":"控制发布进度的操作人员"},{"id":"rollout","text":"the rollout","kind":"core","label_zh":"正在逐步进行的版本发布"},{"id":"ten-minutes","text":"for ten minutes","kind":"modifier","label_zh":"发布暂停持续的时间"},{"id":"error-rate-double","text":"doubled","kind":"action","label_zh":"错误率升到原来的两倍"},{"id":"error-rate","text":"the error rate","kind":"core","label_zh":"触发暂停的错误指标"}],"links":[{"id":"pause-rollout->operator","from":"pause-rollout","to":"operator","kind":"core","relation_type":"actor","label_zh":"操作人员决定暂停发布"},{"id":"pause-rollout->rollout","from":"pause-rollout","to":"rollout","kind":"core","relation_type":"target","label_zh":"被暂停的是版本发布"},{"id":"ten-minutes->pause-rollout","from":"ten-minutes","to":"pause-rollout","kind":"modifier","relation_type":"time","label_zh":"说明发布停止了十分钟"},{"id":"error-rate-double->error-rate","from":"error-rate-double","to":"error-rate","kind":"core","relation_type":"actor","label_zh":"发生翻倍变化的是错误率"},{"id":"error-rate-double->pause-rollout","from":"error-rate-double","to":"pause-rollout","kind":"modifier","relation_type":"reason","label_zh":"错误率翻倍促使操作人员暂停发布"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The operator paused the rollout.","sentence_zh":"操作人员暂停了版本发布。","add_node_ids":["pause-rollout","operator","rollout"],"add_link_ids":["pause-rollout->operator","pause-rollout->rollout"],"focus_node_id":"pause-rollout","note_zh":"pause 表示暂时停止，而不是永久取消。"},{"step_no":2,"label":"暂停时长","sentence_en":"The operator paused the rollout for ten minutes.","sentence_zh":"操作人员暂停了版本发布十分钟。","add_node_ids":["ten-minutes"],"add_link_ids":["ten-minutes->pause-rollout"],"focus_node_id":"ten-minutes","note_zh":"十分钟给暂停设置了明确长度。"},{"step_no":3,"label":"异常原因","sentence_en":"The operator paused the rollout for ten minutes after the error rate doubled.","sentence_zh":"错误率翻倍后，操作人员暂停了版本发布十分钟。","add_node_ids":["error-rate-double","error-rate"],"add_link_ids":["error-rate-double->error-rate","error-rate-double->pause-rollout"],"focus_node_id":"error-rate-double","note_zh":"指标翻倍解释了暂停决定的直接原因。"}]}'
  ),
  (
    'pay-primary',
    'pay',
    'pay',
    'pay a vendor',
    '向供应商支付款项',
    'The finance team paid the vendor.',
    '财务团队向供应商付了款。',
    'The finance team paid the vendor $4,800 by bank transfer.',
    '财务团队通过银行转账向供应商支付了 4,800 美元。',
    'vendor-payment',
    '{"schema_version":2,"root_action_id":"pay-vendor","nodes":[{"id":"pay-vendor","text":"paid","kind":"action","label_zh":"向供应商完成付款"},{"id":"finance-team","text":"The finance team","kind":"core","label_zh":"负责安排付款的财务团队"},{"id":"vendor","text":"the vendor","kind":"core","label_zh":"收到款项的供应商"},{"id":"payment-amount","text":"$4,800","kind":"core","label_zh":"实际支付的金额"},{"id":"bank-transfer","text":"by bank transfer","kind":"modifier","label_zh":"付款采用银行转账方式"}],"links":[{"id":"pay-vendor->finance-team","from":"pay-vendor","to":"finance-team","kind":"core","relation_type":"actor","label_zh":"财务团队执行付款"},{"id":"pay-vendor->vendor","from":"pay-vendor","to":"vendor","kind":"core","relation_type":"recipient","label_zh":"供应商是款项接收方"},{"id":"pay-vendor->payment-amount","from":"pay-vendor","to":"payment-amount","kind":"core","relation_type":"content","label_zh":"付款金额为四千八百美元"},{"id":"bank-transfer->pay-vendor","from":"bank-transfer","to":"pay-vendor","kind":"modifier","relation_type":"manner","label_zh":"说明款项通过银行转账支付"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The finance team paid the vendor.","sentence_zh":"财务团队向供应商付了款。","add_node_ids":["pay-vendor","finance-team","vendor"],"add_link_ids":["pay-vendor->finance-team","pay-vendor->vendor"],"focus_node_id":"pay-vendor","note_zh":"先明确付款方和收款方。"},{"step_no":2,"label":"支付金额","sentence_en":"The finance team paid the vendor $4,800.","sentence_zh":"财务团队向供应商支付了 4,800 美元。","add_node_ids":["payment-amount"],"add_link_ids":["pay-vendor->payment-amount"],"focus_node_id":"payment-amount","note_zh":"金额补全这笔付款的具体内容。"},{"step_no":3,"label":"付款方式","sentence_en":"The finance team paid the vendor $4,800 by bank transfer.","sentence_zh":"财务团队通过银行转账向供应商支付了 4,800 美元。","add_node_ids":["bank-transfer"],"add_link_ids":["bank-transfer->pay-vendor"],"focus_node_id":"bank-transfer","note_zh":"银行转账说明资金如何送达供应商。"}]}'
  ),
  (
    'pay-off-primary',
    'pay-off',
    'pay off',
    'engineering work pays off',
    '投入最终带来良好回报',
    'The indexing work paid off.',
    '索引优化工作取得了回报。',
    'The indexing work paid off with faster search results during the product launch.',
    '产品发布期间，索引优化工作获得了回报，搜索结果变得更快。',
    'search-launch',
    '{"schema_version":2,"root_action_id":"work-pay-off","nodes":[{"id":"work-pay-off","text":"paid off","kind":"action","label_zh":"前期投入产生了实际回报"},{"id":"indexing-work","text":"The indexing work","kind":"core","label_zh":"带来收益的索引优化工作"},{"id":"faster-results","text":"with faster search results","kind":"modifier","label_zh":"回报体现为搜索结果更快"},{"id":"product-launch","text":"during the product launch","kind":"modifier","label_zh":"成效显现的产品发布阶段"}],"links":[{"id":"work-pay-off->indexing-work","from":"work-pay-off","to":"indexing-work","kind":"core","relation_type":"actor","label_zh":"索引优化最终证明值得投入"},{"id":"faster-results->work-pay-off","from":"faster-results","to":"work-pay-off","kind":"modifier","relation_type":"result","label_zh":"更快的搜索结果体现了工作回报"},{"id":"product-launch->work-pay-off","from":"product-launch","to":"work-pay-off","kind":"modifier","relation_type":"time","label_zh":"产品发布期间最明显地看到了成效"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The indexing work paid off.","sentence_zh":"索引优化工作取得了回报。","add_node_ids":["work-pay-off","indexing-work"],"add_link_ids":["work-pay-off->indexing-work"],"focus_node_id":"work-pay-off","note_zh":"pay off 在这里表示投入最终产生价值。"},{"step_no":2,"label":"具体回报","sentence_en":"The indexing work paid off with faster search results.","sentence_zh":"索引优化工作获得了回报，搜索结果变得更快。","add_node_ids":["faster-results"],"add_link_ids":["faster-results->work-pay-off"],"focus_node_id":"faster-results","note_zh":"搜索速度把抽象回报变成可观察结果。"},{"step_no":3,"label":"显效阶段","sentence_en":"The indexing work paid off with faster search results during the product launch.","sentence_zh":"产品发布期间，索引优化工作获得了回报，搜索结果变得更快。","add_node_ids":["product-launch"],"add_link_ids":["product-launch->work-pay-off"],"focus_node_id":"product-launch","note_zh":"发布阶段说明这项收益何时发挥关键作用。"}]}'
  ),
  (
    'peek-primary',
    'peek',
    'peek',
    'peek at a dashboard',
    '快速看一眼或预览',
    'Lena peeked at the staging dashboard.',
    'Lena 快速看了一眼预发布仪表盘。',
    'Lena peeked at the staging dashboard from her phone between meetings.',
    'Lena 在会议间隙用手机快速看了一眼预发布仪表盘。',
    'mobile-monitoring',
    '{"schema_version":2,"root_action_id":"peek-dashboard","nodes":[{"id":"peek-dashboard","text":"peeked","kind":"action","label_zh":"快速查看监控页面"},{"id":"lena","text":"Lena","kind":"core","label_zh":"抽空查看状态的工程师"},{"id":"staging-dashboard","text":"the staging dashboard","kind":"core","label_zh":"被快速查看的预发布仪表盘"},{"id":"phone","text":"from her phone","kind":"modifier","label_zh":"用于查看仪表盘的手机设备"},{"id":"between-meetings","text":"between meetings","kind":"modifier","label_zh":"两场会议之间的短暂空档"}],"links":[{"id":"peek-dashboard->lena","from":"peek-dashboard","to":"lena","kind":"core","relation_type":"actor","label_zh":"Lena 快速看了仪表盘"},{"id":"peek-dashboard->staging-dashboard","from":"peek-dashboard","to":"staging-dashboard","kind":"core","relation_type":"target","label_zh":"她查看的是预发布仪表盘"},{"id":"phone->peek-dashboard","from":"phone","to":"peek-dashboard","kind":"modifier","relation_type":"manner","label_zh":"说明 Lena 使用手机完成查看"},{"id":"between-meetings->peek-dashboard","from":"between-meetings","to":"peek-dashboard","kind":"modifier","relation_type":"time","label_zh":"查看发生在会议间隙"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Lena peeked at the staging dashboard.","sentence_zh":"Lena 快速看了一眼预发布仪表盘。","add_node_ids":["peek-dashboard","lena","staging-dashboard"],"add_link_ids":["peek-dashboard->lena","peek-dashboard->staging-dashboard"],"focus_node_id":"peek-dashboard","note_zh":"peek at 表示短暂而快速地看一眼。"},{"step_no":2,"label":"查看设备","sentence_en":"Lena peeked at the staging dashboard from her phone.","sentence_zh":"Lena 用手机快速看了一眼预发布仪表盘。","add_node_ids":["phone"],"add_link_ids":["phone->peek-dashboard"],"focus_node_id":"phone","note_zh":"手机说明她采用了便捷的查看方式。"},{"step_no":3,"label":"空档时间","sentence_en":"Lena peeked at the staging dashboard from her phone between meetings.","sentence_zh":"Lena 在会议间隙用手机快速看了一眼预发布仪表盘。","add_node_ids":["between-meetings"],"add_link_ids":["between-meetings->peek-dashboard"],"focus_node_id":"between-meetings","note_zh":"会议间隙符合 peek 所表达的短暂查看。"}]}'
  ),
  (
    'peel-primary',
    'peel',
    'peel',
    'peel protective film',
    '把覆盖表面的薄层剥下来',
    'Jon peeled the protective film.',
    'Jon 剥下了保护膜。',
    'Jon peeled the protective film from the new monitor in one smooth motion.',
    'Jon 用一个流畅的动作从新显示器上剥下了保护膜。',
    'monitor-setup',
    '{"schema_version":2,"root_action_id":"peel-film","nodes":[{"id":"peel-film","text":"peeled","kind":"action","label_zh":"从设备表面剥下保护膜"},{"id":"jon","text":"Jon","kind":"core","label_zh":"拆除保护膜的人"},{"id":"protective-film","text":"the protective film","kind":"core","label_zh":"被剥离的透明保护层"},{"id":"new-monitor","text":"the new monitor","kind":"core","label_zh":"原本贴有保护膜的新显示器"},{"id":"smooth-motion","text":"in one smooth motion","kind":"modifier","label_zh":"一次流畅动作完成剥离"}],"links":[{"id":"peel-film->jon","from":"peel-film","to":"jon","kind":"core","relation_type":"actor","label_zh":"Jon 动手剥下保护膜"},{"id":"peel-film->protective-film","from":"peel-film","to":"protective-film","kind":"core","relation_type":"target","label_zh":"被移除的是保护膜"},{"id":"peel-film->new-monitor","from":"peel-film","to":"new-monitor","kind":"core","relation_type":"scope","label_zh":"保护膜从新显示器表面剥离"},{"id":"smooth-motion->peel-film","from":"smooth-motion","to":"peel-film","kind":"modifier","relation_type":"manner","label_zh":"说明整个剥离过程一次完成且很流畅"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Jon peeled the protective film.","sentence_zh":"Jon 剥下了保护膜。","add_node_ids":["peel-film","jon","protective-film"],"add_link_ids":["peel-film->jon","peel-film->protective-film"],"focus_node_id":"peel-film","note_zh":"peel 描写把贴附的薄层从表面分离。"},{"step_no":2,"label":"附着设备","sentence_en":"Jon peeled the protective film from the new monitor.","sentence_zh":"Jon 从新显示器上剥下了保护膜。","add_node_ids":["new-monitor"],"add_link_ids":["peel-film->new-monitor"],"focus_node_id":"new-monitor","note_zh":"新显示器说明保护膜原本贴在哪里。"},{"step_no":3,"label":"剥离方式","sentence_en":"Jon peeled the protective film from the new monitor in one smooth motion.","sentence_zh":"Jon 用一个流畅的动作从新显示器上剥下了保护膜。","add_node_ids":["smooth-motion"],"add_link_ids":["smooth-motion->peel-film"],"focus_node_id":"smooth-motion","note_zh":"一次流畅动作呈现剥离过程的完整与利落。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
