-- Generated verb paths batch batch-002.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'publish-primary',
    'publish',
    'publish',
    'publish a migration guide',
    '发布迁移指南',
    'Elena published the migration guide.',
    'Elena 发布了迁移指南。',
    'Elena published the migration guide for mobile clients on Friday.',
    'Elena 周五发布了面向移动客户端的迁移指南。',
    'sdk-release',
    '{"schema_version":2,"root_action_id":"published","nodes":[{"id":"published","text":"published","kind":"action","label_zh":"正式发布迁移指南"},{"id":"elena","text":"Elena","kind":"core","label_zh":"负责发布指南的工程师"},{"id":"migration-guide","text":"the migration guide","kind":"core","label_zh":"面向用户发布的迁移指南"},{"id":"mobile-clients","text":"for mobile clients","kind":"modifier","label_zh":"指南所服务的客户端类型"},{"id":"on-friday","text":"on Friday","kind":"modifier","label_zh":"指南正式发布的日期"}],"links":[{"id":"published->elena","from":"published","to":"elena","kind":"core","relation_type":"actor","label_zh":"Elena完成了发布工作"},{"id":"published->migration-guide","from":"published","to":"migration-guide","kind":"core","relation_type":"target","label_zh":"发布的内容是迁移指南"},{"id":"mobile-clients->migration-guide","from":"mobile-clients","to":"migration-guide","kind":"modifier","relation_type":"purpose","label_zh":"这份指南供移动客户端开发者使用"},{"id":"on-friday->published","from":"on-friday","to":"published","kind":"modifier","relation_type":"time","label_zh":"发布安排在周五"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Elena published the migration guide.","sentence_zh":"Elena 发布了迁移指南。","add_node_ids":["published","elena","migration-guide"],"add_link_ids":["published->elena","published->migration-guide"],"focus_node_id":"published","note_zh":"先呈现发布动作及其具体内容。"},{"step_no":2,"label":"对象细节","sentence_en":"Elena published the migration guide for mobile clients.","sentence_zh":"Elena 发布了面向移动客户端的迁移指南。","add_node_ids":["mobile-clients"],"add_link_ids":["mobile-clients->migration-guide"],"focus_node_id":"mobile-clients","note_zh":"限定这份指南所面向的开发场景。"},{"step_no":3,"label":"时间","sentence_en":"Elena published the migration guide for mobile clients on Friday.","sentence_zh":"Elena 周五发布了面向移动客户端的迁移指南。","add_node_ids":["on-friday"],"add_link_ids":["on-friday->published"],"focus_node_id":"on-friday","note_zh":"最后补充正式发布的日期。"}]}'
  ),
  (
    'pull-primary',
    'pull',
    'pull',
    'pull an image',
    '拉取容器镜像',
    'The build runner pulled the runtime image.',
    '构建节点拉取了运行时镜像。',
    'The build runner pulled the runtime image from the regional mirror before compilation.',
    '构建节点在编译前从区域镜像站拉取了运行时镜像。',
    'container-build',
    '{"schema_version":2,"root_action_id":"pulled","nodes":[{"id":"pulled","text":"pulled","kind":"action","label_zh":"下载构建所需镜像"},{"id":"build-runner","text":"The build runner","kind":"core","label_zh":"发起镜像拉取的构建节点"},{"id":"runtime-image","text":"the runtime image","kind":"core","label_zh":"构建节点下载的运行时镜像"},{"id":"regional-mirror","text":"from the regional mirror","kind":"modifier","label_zh":"镜像实际下载的来源"},{"id":"before-compilation","text":"before compilation","kind":"modifier","label_zh":"镜像拉取相对于编译的时间"}],"links":[{"id":"pulled->build-runner","from":"pulled","to":"build-runner","kind":"core","relation_type":"actor","label_zh":"构建节点执行镜像拉取"},{"id":"pulled->runtime-image","from":"pulled","to":"runtime-image","kind":"core","relation_type":"target","label_zh":"拉取内容是运行时镜像"},{"id":"regional-mirror->pulled","from":"regional-mirror","to":"pulled","kind":"modifier","relation_type":"place","label_zh":"镜像来自区域镜像站"},{"id":"before-compilation->pulled","from":"before-compilation","to":"pulled","kind":"modifier","relation_type":"time","label_zh":"镜像在编译开始前完成拉取"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The build runner pulled the runtime image.","sentence_zh":"构建节点拉取了运行时镜像。","add_node_ids":["pulled","build-runner","runtime-image"],"add_link_ids":["pulled->build-runner","pulled->runtime-image"],"focus_node_id":"runtime-image","note_zh":"建立构建节点与所需镜像之间的拉取关系。"},{"step_no":2,"label":"场景","sentence_en":"The build runner pulled the runtime image from the regional mirror.","sentence_zh":"构建节点从区域镜像站拉取了运行时镜像。","add_node_ids":["regional-mirror"],"add_link_ids":["regional-mirror->pulled"],"focus_node_id":"regional-mirror","note_zh":"指出镜像下载所使用的来源。"},{"step_no":3,"label":"时间","sentence_en":"The build runner pulled the runtime image from the regional mirror before compilation.","sentence_zh":"构建节点在编译前从区域镜像站拉取了运行时镜像。","add_node_ids":["before-compilation"],"add_link_ids":["before-compilation->pulled"],"focus_node_id":"before-compilation","note_zh":"明确拉取动作在构建流程中的位置。"}]}'
  ),
  (
    'pull-off-primary',
    'pull-off',
    'pull off',
    'pull off an emergency migration',
    '成功完成困难的紧急迁移',
    'The database team pulled off the emergency migration.',
    '数据库团队成功完成了紧急迁移。',
    'The database team pulled off the emergency migration despite losing its lead engineer the night before.',
    '尽管前一晚失去了主要工程师，数据库团队仍成功完成了紧急迁移。',
    'emergency-migration',
    '{"schema_version":2,"root_action_id":"pulled-off","nodes":[{"id":"pulled-off","text":"pulled off","kind":"action","label_zh":"成功完成高难度迁移"},{"id":"database-team","text":"The database team","kind":"core","label_zh":"承担紧急迁移的团队"},{"id":"emergency-migration","text":"the emergency migration","kind":"core","label_zh":"最终成功完成的困难任务"},{"id":"losing","text":"losing","kind":"action","label_zh":"临时失去主要工程师"},{"id":"lead-engineer","text":"its lead engineer","kind":"core","label_zh":"团队在关键时期失去的工程师"},{"id":"night-before","text":"the night before","kind":"modifier","label_zh":"主要工程师离开的紧迫时间"}],"links":[{"id":"pulled-off->database-team","from":"pulled-off","to":"database-team","kind":"core","relation_type":"actor","label_zh":"数据库团队完成了困难迁移"},{"id":"pulled-off->emergency-migration","from":"pulled-off","to":"emergency-migration","kind":"core","relation_type":"target","label_zh":"成功完成的是紧急迁移"},{"id":"losing->database-team","from":"losing","to":"database-team","kind":"core","relation_type":"shared_actor","label_zh":"失去工程师的也是该数据库团队"},{"id":"losing->lead-engineer","from":"losing","to":"lead-engineer","kind":"core","relation_type":"target","label_zh":"团队失去的是主要工程师"},{"id":"losing->pulled-off","from":"losing","to":"pulled-off","kind":"modifier","relation_type":"condition","label_zh":"团队在人员突然缺席的困难条件下完成迁移"},{"id":"night-before->losing","from":"night-before","to":"losing","kind":"modifier","relation_type":"time","label_zh":"主要工程师在迁移前一晚离开"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The database team pulled off the emergency migration.","sentence_zh":"数据库团队成功完成了紧急迁移。","add_node_ids":["pulled-off","database-team","emergency-migration"],"add_link_ids":["pulled-off->database-team","pulled-off->emergency-migration"],"focus_node_id":"pulled-off","note_zh":"主干突出困难任务最终取得成功。"},{"step_no":2,"label":"条件","sentence_en":"The database team pulled off the emergency migration despite losing its lead engineer.","sentence_zh":"尽管失去了主要工程师，数据库团队仍成功完成了紧急迁移。","add_node_ids":["losing","lead-engineer"],"add_link_ids":["losing->database-team","losing->lead-engineer","losing->pulled-off"],"focus_node_id":"losing","note_zh":"加入显著提高迁移难度的人员变化。"},{"step_no":3,"label":"时间","sentence_en":"The database team pulled off the emergency migration despite losing its lead engineer the night before.","sentence_zh":"尽管前一晚失去了主要工程师，数据库团队仍成功完成了紧急迁移。","add_node_ids":["night-before"],"add_link_ids":["night-before->losing"],"focus_node_id":"night-before","note_zh":"说明人员变化发生得非常突然。"}]}'
  ),
  (
    'pull-out-primary',
    'pull-out',
    'pull out',
    'pull out of a rollout',
    '退出上线计划',
    'The integration partner pulled out of the rollout.',
    '集成合作方退出了上线计划。',
    'The integration partner pulled out of the rollout after its security review found a compatibility issue.',
    '安全审查发现兼容性问题后，集成合作方退出了上线计划。',
    'partner-withdrawal',
    '{"schema_version":2,"root_action_id":"pulled-out","nodes":[{"id":"pulled-out","text":"pulled out","kind":"action","label_zh":"退出联合上线计划"},{"id":"integration-partner","text":"The integration partner","kind":"core","label_zh":"决定退出的合作方"},{"id":"rollout","text":"the rollout","kind":"core","label_zh":"合作方不再参与的上线计划"},{"id":"found","text":"found","kind":"action","label_zh":"在审查中发现兼容问题"},{"id":"security-review","text":"its security review","kind":"core","label_zh":"合作方执行的问题审查"},{"id":"compatibility-issue","text":"a compatibility issue","kind":"core","label_zh":"审查发现的兼容性问题"}],"links":[{"id":"pulled-out->integration-partner","from":"pulled-out","to":"integration-partner","kind":"core","relation_type":"actor","label_zh":"集成合作方作出了退出决定"},{"id":"pulled-out->rollout","from":"pulled-out","to":"rollout","kind":"core","relation_type":"target","label_zh":"退出的是联合上线计划"},{"id":"found->security-review","from":"found","to":"security-review","kind":"core","relation_type":"actor","label_zh":"安全审查揭示了技术问题"},{"id":"found->compatibility-issue","from":"found","to":"compatibility-issue","kind":"core","relation_type":"target","label_zh":"审查发现的是兼容性问题"},{"id":"found->pulled-out","from":"found","to":"pulled-out","kind":"modifier","relation_type":"reason","label_zh":"兼容问题促使合作方退出上线"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The integration partner pulled out of the rollout.","sentence_zh":"集成合作方退出了上线计划。","add_node_ids":["pulled-out","integration-partner","rollout"],"add_link_ids":["pulled-out->integration-partner","pulled-out->rollout"],"focus_node_id":"pulled-out","note_zh":"先交代退出方和不再参与的计划。"},{"step_no":2,"label":"原因","sentence_en":"The integration partner pulled out of the rollout after its security review found a compatibility issue.","sentence_zh":"安全审查发现兼容性问题后，集成合作方退出了上线计划。","add_node_ids":["found","security-review","compatibility-issue"],"add_link_ids":["found->security-review","found->compatibility-issue","found->pulled-out"],"focus_node_id":"found","note_zh":"用审查发现解释退出决定。"}]}'
  ),
  (
    'pump-primary',
    'pump',
    'pump',
    'pump events into an index',
    '持续大量输送事件数据',
    'The ingestion worker pumps audit events into the search index.',
    '摄取程序将审计事件持续输送到搜索索引中。',
    'The ingestion worker pumps audit events into the search index overnight in compressed batches.',
    '摄取程序在夜间以压缩批次的方式将审计事件持续输送到搜索索引中。',
    'search-ingestion',
    '{"schema_version":2,"root_action_id":"pumps","nodes":[{"id":"pumps","text":"pumps","kind":"action","label_zh":"持续输送事件数据"},{"id":"ingestion-worker","text":"The ingestion worker","kind":"core","label_zh":"负责高速传输的后台程序"},{"id":"audit-events","text":"audit events","kind":"core","label_zh":"被持续发送的审计事件"},{"id":"search-index","text":"the search index","kind":"core","label_zh":"接收审计事件的搜索索引"},{"id":"overnight","text":"overnight","kind":"modifier","label_zh":"批量输送持续的时段"},{"id":"batches","text":"in compressed batches","kind":"modifier","label_zh":"事件数据采用的批量传输方式"}],"links":[{"id":"pumps->ingestion-worker","from":"pumps","to":"ingestion-worker","kind":"core","relation_type":"actor","label_zh":"摄取程序持续发送数据"},{"id":"pumps->audit-events","from":"pumps","to":"audit-events","kind":"core","relation_type":"target","label_zh":"被输送的是审计事件"},{"id":"pumps->search-index","from":"pumps","to":"search-index","kind":"core","relation_type":"recipient","label_zh":"审计事件进入搜索索引"},{"id":"overnight->pumps","from":"overnight","to":"pumps","kind":"modifier","relation_type":"time","label_zh":"大量数据在夜间持续传输"},{"id":"batches->pumps","from":"batches","to":"pumps","kind":"modifier","relation_type":"manner","label_zh":"事件被压缩并分批送入索引"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The ingestion worker pumps audit events into the search index.","sentence_zh":"摄取程序将审计事件持续输送到搜索索引中。","add_node_ids":["pumps","ingestion-worker","audit-events","search-index"],"add_link_ids":["pumps->ingestion-worker","pumps->audit-events","pumps->search-index"],"focus_node_id":"pumps","note_zh":"主干完整呈现发送程序、数据和接收位置。"},{"step_no":2,"label":"时间","sentence_en":"The ingestion worker pumps audit events into the search index overnight.","sentence_zh":"摄取程序在夜间将审计事件持续输送到搜索索引中。","add_node_ids":["overnight"],"add_link_ids":["overnight->pumps"],"focus_node_id":"overnight","note_zh":"限定这条数据流集中运行的时段。"},{"step_no":3,"label":"方式","sentence_en":"The ingestion worker pumps audit events into the search index overnight in compressed batches.","sentence_zh":"摄取程序在夜间以压缩批次的方式将审计事件持续输送到搜索索引中。","add_node_ids":["batches"],"add_link_ids":["batches->pumps"],"focus_node_id":"batches","note_zh":"补充适合大批量数据的传输方式。"}]}'
  ),
  (
    'purchase-primary',
    'purchase',
    'purchase',
    'purchase testing hardware',
    '采购测试硬件',
    'The IT team purchased four network appliances.',
    'IT 团队采购了四台网络设备。',
    'The IT team purchased four network appliances to equip the new QA lab under the annual supplier contract.',
    'IT 团队按照年度供应商合同采购了四台网络设备，用于配置新的质量测试实验室。',
    'qa-lab-procurement',
    '{"schema_version":2,"root_action_id":"purchased","nodes":[{"id":"purchased","text":"purchased","kind":"action","label_zh":"采购专用测试硬件"},{"id":"it-team","text":"The IT team","kind":"core","label_zh":"负责完成采购的团队"},{"id":"network-appliances","text":"four network appliances","kind":"core","label_zh":"采购的四台网络设备"},{"id":"equip","text":"equip","kind":"action","label_zh":"为新实验室配置设备"},{"id":"qa-lab","text":"the new QA lab","kind":"core","label_zh":"将使用这批设备的新实验室"},{"id":"annual-contract","text":"under the annual supplier contract","kind":"modifier","label_zh":"此次采购采用的供应协议"}],"links":[{"id":"purchased->it-team","from":"purchased","to":"it-team","kind":"core","relation_type":"actor","label_zh":"IT团队执行了硬件采购"},{"id":"purchased->network-appliances","from":"purchased","to":"network-appliances","kind":"core","relation_type":"target","label_zh":"采购内容是四台网络设备"},{"id":"equip->it-team","from":"equip","to":"it-team","kind":"core","relation_type":"shared_actor","label_zh":"IT团队也负责配置实验室"},{"id":"equip->qa-lab","from":"equip","to":"qa-lab","kind":"core","relation_type":"target","label_zh":"设备用于完善新的测试实验室"},{"id":"equip->purchased","from":"equip","to":"purchased","kind":"modifier","relation_type":"purpose","label_zh":"采购设备是为了建设新的测试实验室"},{"id":"annual-contract->purchased","from":"annual-contract","to":"purchased","kind":"modifier","relation_type":"condition","label_zh":"采购按照年度供应商合同执行"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The IT team purchased four network appliances.","sentence_zh":"IT 团队采购了四台网络设备。","add_node_ids":["purchased","it-team","network-appliances"],"add_link_ids":["purchased->it-team","purchased->network-appliances"],"focus_node_id":"network-appliances","note_zh":"先说明采购方以及设备类型和数量。"},{"step_no":2,"label":"目的","sentence_en":"The IT team purchased four network appliances to equip the new QA lab.","sentence_zh":"IT 团队采购了四台网络设备，用于配置新的质量测试实验室。","add_node_ids":["equip","qa-lab"],"add_link_ids":["equip->it-team","equip->qa-lab","equip->purchased"],"focus_node_id":"equip","note_zh":"加入这批硬件需要完成的建设任务。"},{"step_no":3,"label":"条件","sentence_en":"The IT team purchased four network appliances to equip the new QA lab under the annual supplier contract.","sentence_zh":"IT 团队按照年度供应商合同采购了四台网络设备，用于配置新的质量测试实验室。","add_node_ids":["annual-contract"],"add_link_ids":["annual-contract->purchased"],"focus_node_id":"annual-contract","note_zh":"说明采购遵循的现有供应协议。"}]}'
  ),
  (
    'purge-primary',
    'purge',
    'purge',
    'purge stale messages',
    '清除队列中的过期消息',
    'The cleanup worker purges stale messages.',
    '清理程序会删除过期消息。',
    'The cleanup worker purges stale messages from the retry queue when the queue depth exceeds the configured limit.',
    '当队列长度超过预设上限时，清理程序会从重试队列中删除过期消息。',
    'message-queue-cleanup',
    '{"schema_version":2,"root_action_id":"purges","nodes":[{"id":"purges","text":"purges","kind":"action","label_zh":"删除不再有效的消息"},{"id":"cleanup-worker","text":"The cleanup worker","kind":"core","label_zh":"自动执行消息清理的程序"},{"id":"stale-messages","text":"stale messages","kind":"core","label_zh":"需要从系统中删除的旧消息"},{"id":"retry-queue","text":"from the retry queue","kind":"modifier","label_zh":"旧消息所在的重试队列"},{"id":"exceeds","text":"exceeds","kind":"action","label_zh":"队列长度超过限制"},{"id":"queue-depth","text":"the queue depth","kind":"core","label_zh":"决定是否清理的队列长度"},{"id":"limit","text":"the configured limit","kind":"core","label_zh":"触发清理的预设上限"}],"links":[{"id":"purges->cleanup-worker","from":"purges","to":"cleanup-worker","kind":"core","relation_type":"actor","label_zh":"清理程序负责删除旧消息"},{"id":"purges->stale-messages","from":"purges","to":"stale-messages","kind":"core","relation_type":"target","label_zh":"删除对象是失效消息"},{"id":"retry-queue->purges","from":"retry-queue","to":"purges","kind":"modifier","relation_type":"place","label_zh":"清理发生在重试队列中"},{"id":"exceeds->queue-depth","from":"exceeds","to":"queue-depth","kind":"core","relation_type":"actor","label_zh":"受到监控的是当前队列长度"},{"id":"exceeds->limit","from":"exceeds","to":"limit","kind":"core","relation_type":"target","label_zh":"队列长度越过预设上限"},{"id":"exceeds->purges","from":"exceeds","to":"purges","kind":"modifier","relation_type":"condition","label_zh":"只有队列过长时才自动清除旧消息"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The cleanup worker purges stale messages.","sentence_zh":"清理程序会删除过期消息。","add_node_ids":["purges","cleanup-worker","stale-messages"],"add_link_ids":["purges->cleanup-worker","purges->stale-messages"],"focus_node_id":"purges","note_zh":"先建立自动清理与失效消息的关系。"},{"step_no":2,"label":"场景","sentence_en":"The cleanup worker purges stale messages from the retry queue.","sentence_zh":"清理程序会从重试队列中删除过期消息。","add_node_ids":["retry-queue"],"add_link_ids":["retry-queue->purges"],"focus_node_id":"retry-queue","note_zh":"指出需要清理的是哪一个队列。"},{"step_no":3,"label":"条件","sentence_en":"The cleanup worker purges stale messages from the retry queue when the queue depth exceeds the configured limit.","sentence_zh":"当队列长度超过预设上限时，清理程序会从重试队列中删除过期消息。","add_node_ids":["exceeds","queue-depth","limit"],"add_link_ids":["exceeds->queue-depth","exceeds->limit","exceeds->purges"],"focus_node_id":"exceeds","note_zh":"补充自动清理开始运行的资源条件。"}]}'
  ),
  (
    'pursue-primary',
    'pursue',
    'pursue',
    'pursue platform engineering',
    '追求平台工程职业方向',
    'Marcus pursued a career in platform engineering.',
    'Marcus 选择追求平台工程职业。',
    'Marcus pursued a career in platform engineering after three years in support through part-time projects.',
    '从事支持工作三年后，Marcus 通过业余项目追求平台工程职业。',
    'career-development',
    '{"schema_version":2,"root_action_id":"pursued","nodes":[{"id":"pursued","text":"pursued","kind":"action","label_zh":"主动选择新的职业方向"},{"id":"marcus","text":"Marcus","kind":"core","label_zh":"规划职业转向的工程师"},{"id":"platform-career","text":"a career in platform engineering","kind":"core","label_zh":"Marcus希望长期发展的领域"},{"id":"three-years","text":"after three years in support","kind":"modifier","label_zh":"职业转向前积累的工作经历"},{"id":"part-time","text":"through part-time projects","kind":"modifier","label_zh":"探索新职业方向的实践方式"}],"links":[{"id":"pursued->marcus","from":"pursued","to":"marcus","kind":"core","relation_type":"actor","label_zh":"Marcus主动规划新的职业道路"},{"id":"pursued->platform-career","from":"pursued","to":"platform-career","kind":"core","relation_type":"target","label_zh":"他追求的是平台工程职业"},{"id":"three-years->pursued","from":"three-years","to":"pursued","kind":"modifier","relation_type":"time","label_zh":"转向发生在三年支持工作之后"},{"id":"part-time->pursued","from":"part-time","to":"pursued","kind":"modifier","relation_type":"manner","label_zh":"他通过业余项目逐步进入该领域"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Marcus pursued a career in platform engineering.","sentence_zh":"Marcus 选择追求平台工程职业。","add_node_ids":["pursued","marcus","platform-career"],"add_link_ids":["pursued->marcus","pursued->platform-career"],"focus_node_id":"platform-career","note_zh":"直接呈现他希望发展的专业方向。"},{"step_no":2,"label":"时间","sentence_en":"Marcus pursued a career in platform engineering after three years in support.","sentence_zh":"从事支持工作三年后，Marcus 选择追求平台工程职业。","add_node_ids":["three-years"],"add_link_ids":["three-years->pursued"],"focus_node_id":"three-years","note_zh":"交代职业选择之前的经历背景。"},{"step_no":3,"label":"方式","sentence_en":"Marcus pursued a career in platform engineering after three years in support through part-time projects.","sentence_zh":"从事支持工作三年后，Marcus 通过业余项目追求平台工程职业。","add_node_ids":["part-time"],"add_link_ids":["part-time->pursued"],"focus_node_id":"part-time","note_zh":"说明他如何实际探索新的职业道路。"}]}'
  ),
  (
    'push-primary',
    'push',
    'push',
    'push a commit',
    '推送代码提交',
    'Ravi pushed the commit to the release branch.',
    'Ravi 将代码提交推送到了发布分支。',
    'Ravi pushed the commit to the release branch after the reviewer approved it.',
    '评审人员批准该提交后，Ravi 将它推送到了发布分支。',
    'repository-update',
    '{"schema_version":2,"root_action_id":"pushed","nodes":[{"id":"pushed","text":"pushed","kind":"action","label_zh":"将代码提交发送到远端"},{"id":"ravi","text":"Ravi","kind":"core","label_zh":"执行代码推送的开发者"},{"id":"commit","text":"the commit","kind":"core","label_zh":"被发送到远端的代码提交"},{"id":"release-branch","text":"the release branch","kind":"core","label_zh":"接收此次提交的远端分支"},{"id":"approved","text":"approved","kind":"action","label_zh":"确认提交可以合入"},{"id":"reviewer","text":"the reviewer","kind":"core","label_zh":"批准这次提交的评审人员"}],"links":[{"id":"pushed->ravi","from":"pushed","to":"ravi","kind":"core","relation_type":"actor","label_zh":"Ravi执行了远端推送"},{"id":"pushed->commit","from":"pushed","to":"commit","kind":"core","relation_type":"target","label_zh":"推送内容是该代码提交"},{"id":"pushed->release-branch","from":"pushed","to":"release-branch","kind":"core","relation_type":"recipient","label_zh":"提交被发送到发布分支"},{"id":"approved->reviewer","from":"approved","to":"reviewer","kind":"core","relation_type":"actor","label_zh":"评审人员作出了批准决定"},{"id":"approved->commit","from":"approved","to":"commit","kind":"core","relation_type":"target","label_zh":"获得批准的是同一个代码提交"},{"id":"approved->pushed","from":"approved","to":"pushed","kind":"modifier","relation_type":"time","label_zh":"提交获批后Ravi才进行推送"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Ravi pushed the commit to the release branch.","sentence_zh":"Ravi 将代码提交推送到了发布分支。","add_node_ids":["pushed","ravi","commit","release-branch"],"add_link_ids":["pushed->ravi","pushed->commit","pushed->release-branch"],"focus_node_id":"pushed","note_zh":"主干说明推送者、提交内容和目标分支。"},{"step_no":2,"label":"时间","sentence_en":"Ravi pushed the commit to the release branch after the reviewer approved it.","sentence_zh":"评审人员批准该提交后，Ravi 将它推送到了发布分支。","add_node_ids":["approved","reviewer"],"add_link_ids":["approved->reviewer","approved->commit","approved->pushed"],"focus_node_id":"approved","note_zh":"加入推送前完成的代码批准事件。"}]}'
  ),
  (
    'push-back-primary',
    'push-back',
    'push back',
    'push back on a proposal',
    '反对一项技术提议',
    'The architect pushed back on the proposal.',
    '架构师反对这项方案。',
    'The architect pushed back on the proposal during the design review because it duplicated the existing event pipeline.',
    '架构师在设计评审期间反对这项方案，因为它重复了现有事件管道的功能。',
    'architecture-review',
    '{"schema_version":2,"root_action_id":"pushed-back","nodes":[{"id":"pushed-back","text":"pushed back","kind":"action","label_zh":"明确反对技术方案"},{"id":"architect","text":"The architect","kind":"core","label_zh":"在评审中提出异议的人"},{"id":"proposal","text":"the proposal","kind":"core","label_zh":"受到架构师反对的方案"},{"id":"design-review","text":"during the design review","kind":"modifier","label_zh":"异议公开提出的会议"},{"id":"duplicated","text":"duplicated","kind":"action","label_zh":"重复已有管道的功能"},{"id":"event-pipeline","text":"the existing event pipeline","kind":"core","label_zh":"方案会重复建设的现有系统"}],"links":[{"id":"pushed-back->architect","from":"pushed-back","to":"architect","kind":"core","relation_type":"actor","label_zh":"架构师明确表达了反对意见"},{"id":"pushed-back->proposal","from":"pushed-back","to":"proposal","kind":"core","relation_type":"target","label_zh":"异议直接针对这项方案"},{"id":"design-review->pushed-back","from":"design-review","to":"pushed-back","kind":"modifier","relation_type":"time","label_zh":"反对意见在设计评审期间提出"},{"id":"duplicated->proposal","from":"duplicated","to":"proposal","kind":"core","relation_type":"actor","label_zh":"同一项方案会造成重复建设"},{"id":"duplicated->event-pipeline","from":"duplicated","to":"event-pipeline","kind":"core","relation_type":"target","label_zh":"被重复的是已有事件管道的功能"},{"id":"duplicated->pushed-back","from":"duplicated","to":"pushed-back","kind":"modifier","relation_type":"reason","label_zh":"重复现有管道是架构师反对的技术原因"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The architect pushed back on the proposal.","sentence_zh":"架构师反对这项方案。","add_node_ids":["pushed-back","architect","proposal"],"add_link_ids":["pushed-back->architect","pushed-back->proposal"],"focus_node_id":"pushed-back","note_zh":"先呈现架构师对具体方案的明确异议。"},{"step_no":2,"label":"场景","sentence_en":"The architect pushed back on the proposal during the design review.","sentence_zh":"架构师在设计评审期间反对这项方案。","add_node_ids":["design-review"],"add_link_ids":["design-review->pushed-back"],"focus_node_id":"design-review","note_zh":"补充异议出现的评审场景。"},{"step_no":3,"label":"原因","sentence_en":"The architect pushed back on the proposal during the design review because it duplicated the existing event pipeline.","sentence_zh":"架构师在设计评审期间反对这项方案，因为它重复了现有事件管道的功能。","add_node_ids":["duplicated","event-pipeline"],"add_link_ids":["duplicated->proposal","duplicated->event-pipeline","duplicated->pushed-back"],"focus_node_id":"duplicated","note_zh":"说明该方案为什么没有得到架构师支持。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'put-primary',
    'put',
    'put',
    'put a config file in storage',
    '把配置文件放入安全存储位置',
    'June put the config file in the encrypted folder.',
    'June 把配置文件放进了加密目录。',
    'June put the config file in the encrypted folder for safekeeping.',
    'June 为了安全保管，把配置文件放进了加密目录。',
    'secure-configuration',
    '{"schema_version":2,"root_action_id":"put","nodes":[{"id":"put","text":"put","kind":"action","label_zh":"将配置文件存放起来"},{"id":"june","text":"June","kind":"core","label_zh":"负责保存配置文件的工程师"},{"id":"config-file","text":"the config file","kind":"core","label_zh":"需要受到保护的配置文件"},{"id":"encrypted-folder","text":"the encrypted folder","kind":"core","label_zh":"配置文件被放入的安全目录"},{"id":"safekeeping","text":"for safekeeping","kind":"modifier","label_zh":"安全保存文件的目的"}],"links":[{"id":"put->june","from":"put","to":"june","kind":"core","relation_type":"actor","label_zh":"June执行了文件存放"},{"id":"put->config-file","from":"put","to":"config-file","kind":"core","relation_type":"target","label_zh":"被存放的是配置文件"},{"id":"put->encrypted-folder","from":"put","to":"encrypted-folder","kind":"core","relation_type":"place","label_zh":"文件被放进加密目录"},{"id":"safekeeping->put","from":"safekeeping","to":"put","kind":"modifier","relation_type":"purpose","label_zh":"这样放置是为了安全保管文件"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"June put the config file in the encrypted folder.","sentence_zh":"June 把配置文件放进了加密目录。","add_node_ids":["put","june","config-file","encrypted-folder"],"add_link_ids":["put->june","put->config-file","put->encrypted-folder"],"focus_node_id":"encrypted-folder","note_zh":"主干完整交代文件及其放置位置。"},{"step_no":2,"label":"目的","sentence_en":"June put the config file in the encrypted folder for safekeeping.","sentence_zh":"June 为了安全保管，把配置文件放进了加密目录。","add_node_ids":["safekeeping"],"add_link_ids":["safekeeping->put"],"focus_node_id":"safekeeping","note_zh":"补充选择加密目录的安全目的。"}]}'
  ),
  (
    'put-off-primary',
    'put-off',
    'put off',
    'put off a database upgrade',
    '推迟数据库升级',
    'The operations team put off the database upgrade.',
    '运维团队推迟了数据库升级。',
    'The operations team put off the database upgrade until the next maintenance window because the vendor had not delivered the compatibility patch.',
    '由于供应商尚未交付兼容性补丁，运维团队将数据库升级推迟到下一个维护窗口。',
    'upgrade-delay',
    '{"schema_version":2,"root_action_id":"put-off","nodes":[{"id":"put-off","text":"put off","kind":"action","label_zh":"决定延后数据库升级"},{"id":"operations-team","text":"The operations team","kind":"core","label_zh":"作出延期决定的团队"},{"id":"database-upgrade","text":"the database upgrade","kind":"core","label_zh":"被延后执行的升级工作"},{"id":"next-window","text":"until the next maintenance window","kind":"modifier","label_zh":"升级推迟到的维护时段"},{"id":"had-not-delivered","text":"had not delivered","kind":"action","label_zh":"尚未提供必要补丁"},{"id":"vendor","text":"the vendor","kind":"core","label_zh":"应当提供补丁的供应商"},{"id":"compatibility-patch","text":"the compatibility patch","kind":"core","label_zh":"升级前仍然缺少的补丁"}],"links":[{"id":"put-off->operations-team","from":"put-off","to":"operations-team","kind":"core","relation_type":"actor","label_zh":"运维团队决定延后升级"},{"id":"put-off->database-upgrade","from":"put-off","to":"database-upgrade","kind":"core","relation_type":"target","label_zh":"延期事项是数据库升级"},{"id":"next-window->put-off","from":"next-window","to":"put-off","kind":"modifier","relation_type":"time","label_zh":"升级被延后到下一维护窗口"},{"id":"had-not-delivered->vendor","from":"had-not-delivered","to":"vendor","kind":"core","relation_type":"actor","label_zh":"供应商尚未完成补丁交付"},{"id":"had-not-delivered->compatibility-patch","from":"had-not-delivered","to":"compatibility-patch","kind":"core","relation_type":"target","label_zh":"未交付的是兼容性补丁"},{"id":"had-not-delivered->put-off","from":"had-not-delivered","to":"put-off","kind":"modifier","relation_type":"reason","label_zh":"缺少兼容性补丁导致升级延期"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The operations team put off the database upgrade.","sentence_zh":"运维团队推迟了数据库升级。","add_node_ids":["put-off","operations-team","database-upgrade"],"add_link_ids":["put-off->operations-team","put-off->database-upgrade"],"focus_node_id":"database-upgrade","note_zh":"先明确团队延后了哪项维护工作。"},{"step_no":2,"label":"时间","sentence_en":"The operations team put off the database upgrade until the next maintenance window.","sentence_zh":"运维团队将数据库升级推迟到下一个维护窗口。","add_node_ids":["next-window"],"add_link_ids":["next-window->put-off"],"focus_node_id":"next-window","note_zh":"给出升级重新安排的时间界线。"},{"step_no":3,"label":"原因","sentence_en":"The operations team put off the database upgrade until the next maintenance window because the vendor had not delivered the compatibility patch.","sentence_zh":"由于供应商尚未交付兼容性补丁，运维团队将数据库升级推迟到下一个维护窗口。","add_node_ids":["had-not-delivered","vendor","compatibility-patch"],"add_link_ids":["had-not-delivered->vendor","had-not-delivered->compatibility-patch","had-not-delivered->put-off"],"focus_node_id":"had-not-delivered","note_zh":"补充迫使团队延期的外部依赖。"}]}'
  ),
  (
    'put-together-primary',
    'put-together',
    'put together',
    'put together an incident brief',
    '整理并组合成事件简报',
    'The on-call engineer put together an incident brief.',
    '值班工程师整理出了一份事件简报。',
    'The on-call engineer put together an incident brief from the logs and chat notes for the morning handoff.',
    '值班工程师根据日志和聊天记录整理出事件简报，供早班交接使用。',
    'incident-handoff',
    '{"schema_version":2,"root_action_id":"put-together","nodes":[{"id":"put-together","text":"put together","kind":"action","label_zh":"汇总材料形成简报"},{"id":"on-call-engineer","text":"The on-call engineer","kind":"core","label_zh":"负责整理事件材料的人"},{"id":"incident-brief","text":"an incident brief","kind":"core","label_zh":"多项材料组合出的事件简报"},{"id":"logs-and-notes","text":"from the logs and chat notes","kind":"modifier","label_zh":"简报内容采用的原始材料"},{"id":"morning-handoff","text":"for the morning handoff","kind":"modifier","label_zh":"简报需要支持的交接场景"}],"links":[{"id":"put-together->on-call-engineer","from":"put-together","to":"on-call-engineer","kind":"core","relation_type":"actor","label_zh":"值班工程师完成材料整理"},{"id":"put-together->incident-brief","from":"put-together","to":"incident-brief","kind":"core","relation_type":"result","label_zh":"整理工作产生了一份事件简报"},{"id":"logs-and-notes->incident-brief","from":"logs-and-notes","to":"incident-brief","kind":"modifier","relation_type":"content","label_zh":"简报综合了日志和聊天记录"},{"id":"morning-handoff->put-together","from":"morning-handoff","to":"put-together","kind":"modifier","relation_type":"purpose","label_zh":"整理简报是为了早班交接"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The on-call engineer put together an incident brief.","sentence_zh":"值班工程师整理出了一份事件简报。","add_node_ids":["put-together","on-call-engineer","incident-brief"],"add_link_ids":["put-together->on-call-engineer","put-together->incident-brief"],"focus_node_id":"incident-brief","note_zh":"先呈现整理工作形成的具体成果。"},{"step_no":2,"label":"对象细节","sentence_en":"The on-call engineer put together an incident brief from the logs and chat notes.","sentence_zh":"值班工程师根据日志和聊天记录整理出了一份事件简报。","add_node_ids":["logs-and-notes"],"add_link_ids":["logs-and-notes->incident-brief"],"focus_node_id":"logs-and-notes","note_zh":"指出简报综合了哪些现场材料。"},{"step_no":3,"label":"目的","sentence_en":"The on-call engineer put together an incident brief from the logs and chat notes for the morning handoff.","sentence_zh":"值班工程师根据日志和聊天记录整理出事件简报，供早班交接使用。","add_node_ids":["morning-handoff"],"add_link_ids":["morning-handoff->put-together"],"focus_node_id":"morning-handoff","note_zh":"说明这份简报将在什么工作环节使用。"}]}'
  ),
  (
    'qualify-primary',
    'qualify',
    'qualify',
    'qualify for the final round',
    '获得进入最终环节的资格',
    'The candidate qualified for the final round.',
    '这名候选人获得了进入最终面试的资格。',
    'The candidate qualified for the final round after passing the live coding test on the first attempt.',
    '第一次尝试就通过现场编程测试后，这名候选人获得了进入最终面试的资格。',
    'engineering-interview',
    '{"schema_version":2,"root_action_id":"qualified","nodes":[{"id":"qualified","text":"qualified","kind":"action","label_zh":"达到进入最终面试的要求"},{"id":"candidate","text":"The candidate","kind":"core","label_zh":"成功取得下一轮资格的人"},{"id":"final-round","text":"the final round","kind":"core","label_zh":"候选人获准进入的面试环节"},{"id":"passing","text":"passing","kind":"action","label_zh":"通过现场编程测试"},{"id":"coding-test","text":"the live coding test","kind":"core","label_zh":"决定候选人能否晋级的测试"},{"id":"first-attempt","text":"on the first attempt","kind":"modifier","label_zh":"编程测试一次通过的表现"}],"links":[{"id":"qualified->candidate","from":"qualified","to":"candidate","kind":"core","relation_type":"actor","label_zh":"该候选人达到了晋级要求"},{"id":"qualified->final-round","from":"qualified","to":"final-round","kind":"core","relation_type":"category","label_zh":"获得的是最终面试资格"},{"id":"passing->candidate","from":"passing","to":"candidate","kind":"core","relation_type":"shared_actor","label_zh":"通过测试的也是该候选人"},{"id":"passing->coding-test","from":"passing","to":"coding-test","kind":"core","relation_type":"target","label_zh":"候选人通过了现场编程测试"},{"id":"passing->qualified","from":"passing","to":"qualified","kind":"modifier","relation_type":"condition","label_zh":"通过编程测试使候选人取得晋级资格"},{"id":"first-attempt->passing","from":"first-attempt","to":"passing","kind":"modifier","relation_type":"frequency","label_zh":"候选人第一次尝试就通过了测试"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The candidate qualified for the final round.","sentence_zh":"这名候选人获得了进入最终面试的资格。","add_node_ids":["qualified","candidate","final-round"],"add_link_ids":["qualified->candidate","qualified->final-round"],"focus_node_id":"qualified","note_zh":"先说明候选人取得了哪个环节的资格。"},{"step_no":2,"label":"条件","sentence_en":"The candidate qualified for the final round after passing the live coding test.","sentence_zh":"通过现场编程测试后，这名候选人获得了进入最终面试的资格。","add_node_ids":["passing","coding-test"],"add_link_ids":["passing->candidate","passing->coding-test","passing->qualified"],"focus_node_id":"passing","note_zh":"加入候选人达到晋级要求的关键表现。"},{"step_no":3,"label":"频率","sentence_en":"The candidate qualified for the final round after passing the live coding test on the first attempt.","sentence_zh":"第一次尝试就通过现场编程测试后，这名候选人获得了进入最终面试的资格。","add_node_ids":["first-attempt"],"add_link_ids":["first-attempt->passing"],"focus_node_id":"first-attempt","note_zh":"强调测试是在首次尝试时通过的。"}]}'
  ),
  (
    'query-primary',
    'query',
    'query',
    'query a service catalog',
    '查询服务目录',
    'The billing service queried the service catalog.',
    '计费服务查询了服务目录。',
    'The billing service queried the service catalog for each account''s current status during nightly reconciliation.',
    '计费服务在夜间核对期间查询服务目录，以获取每个账户的当前状态。',
    'account-reconciliation',
    '{"schema_version":2,"root_action_id":"queried","nodes":[{"id":"queried","text":"queried","kind":"action","label_zh":"向服务目录发起数据查询"},{"id":"billing-service","text":"The billing service","kind":"core","label_zh":"自动发起查询的计费服务"},{"id":"service-catalog","text":"the service catalog","kind":"core","label_zh":"接收查询请求的目录系统"},{"id":"account-status","text":"for each account''s current status","kind":"core","label_zh":"查询需要取得的账户状态"},{"id":"reconciliation","text":"during nightly reconciliation","kind":"modifier","label_zh":"查询运行的夜间核对流程"}],"links":[{"id":"queried->billing-service","from":"queried","to":"billing-service","kind":"core","relation_type":"actor","label_zh":"计费服务自动执行查询"},{"id":"queried->service-catalog","from":"queried","to":"service-catalog","kind":"core","relation_type":"recipient","label_zh":"查询请求发送到服务目录"},{"id":"queried->account-status","from":"queried","to":"account-status","kind":"core","relation_type":"content","label_zh":"查询内容是每个账户的当前状态"},{"id":"reconciliation->queried","from":"reconciliation","to":"queried","kind":"modifier","relation_type":"time","label_zh":"查询发生在夜间账户核对期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The billing service queried the service catalog.","sentence_zh":"计费服务查询了服务目录。","add_node_ids":["queried","billing-service","service-catalog"],"add_link_ids":["queried->billing-service","queried->service-catalog"],"focus_node_id":"queried","note_zh":"先建立计费服务与目录系统之间的查询。"},{"step_no":2,"label":"内容","sentence_en":"The billing service queried the service catalog for each account''s current status.","sentence_zh":"计费服务查询服务目录，以获取每个账户的当前状态。","add_node_ids":["account-status"],"add_link_ids":["queried->account-status"],"focus_node_id":"account-status","note_zh":"补充该查询需要返回的具体信息。"},{"step_no":3,"label":"时间","sentence_en":"The billing service queried the service catalog for each account''s current status during nightly reconciliation.","sentence_zh":"计费服务在夜间核对期间查询服务目录，以获取每个账户的当前状态。","add_node_ids":["reconciliation"],"add_link_ids":["reconciliation->queried"],"focus_node_id":"reconciliation","note_zh":"将查询放入实际运行的核对流程中。"}]}'
  ),
  (
    'question-primary',
    'question',
    'question',
    'question a capacity estimate',
    '质疑容量估算',
    'The auditor questioned the capacity estimate.',
    '审计人员质疑了这项容量估算。',
    'The auditor questioned the capacity estimate after noticing that the model omitted peak traffic.',
    '审计人员发现模型遗漏了高峰流量后，质疑了这项容量估算。',
    'capacity-review',
    '{"schema_version":2,"root_action_id":"questioned","nodes":[{"id":"questioned","text":"questioned","kind":"action","label_zh":"对容量估算提出质疑"},{"id":"auditor","text":"The auditor","kind":"core","label_zh":"检查估算依据并提出疑问的人"},{"id":"capacity-estimate","text":"the capacity estimate","kind":"core","label_zh":"可信度受到质疑的容量估算"},{"id":"noticing","text":"noticing","kind":"action","label_zh":"注意到模型遗漏关键信息"},{"id":"omitted","text":"omitted","kind":"action","label_zh":"没有计入峰值流量"},{"id":"model","text":"the model","kind":"core","label_zh":"生成容量估算的计算模型"},{"id":"peak-traffic","text":"peak traffic","kind":"core","label_zh":"模型未纳入的高峰流量"}],"links":[{"id":"questioned->auditor","from":"questioned","to":"auditor","kind":"core","relation_type":"actor","label_zh":"审计人员提出了质疑"},{"id":"questioned->capacity-estimate","from":"questioned","to":"capacity-estimate","kind":"core","relation_type":"target","label_zh":"质疑针对容量估算结果"},{"id":"noticing->auditor","from":"noticing","to":"auditor","kind":"core","relation_type":"shared_actor","label_zh":"发现遗漏的也是该审计人员"},{"id":"noticing->omitted","from":"noticing","to":"omitted","kind":"core","relation_type":"content","label_zh":"审计人员注意到模型漏算流量"},{"id":"omitted->model","from":"omitted","to":"model","kind":"core","relation_type":"actor","label_zh":"容量模型产生了信息遗漏"},{"id":"omitted->peak-traffic","from":"omitted","to":"peak-traffic","kind":"core","relation_type":"target","label_zh":"模型没有计入高峰流量"},{"id":"noticing->questioned","from":"noticing","to":"questioned","kind":"modifier","relation_type":"reason","label_zh":"发现模型遗漏后审计人员开始质疑估算"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The auditor questioned the capacity estimate.","sentence_zh":"审计人员质疑了这项容量估算。","add_node_ids":["questioned","auditor","capacity-estimate"],"add_link_ids":["questioned->auditor","questioned->capacity-estimate"],"focus_node_id":"questioned","note_zh":"直接呈现对估算结果的专业质疑。"},{"step_no":2,"label":"原因","sentence_en":"The auditor questioned the capacity estimate after noticing that the model omitted peak traffic.","sentence_zh":"审计人员发现模型遗漏了高峰流量后，质疑了这项容量估算。","add_node_ids":["noticing","omitted","model","peak-traffic"],"add_link_ids":["noticing->auditor","noticing->omitted","omitted->model","omitted->peak-traffic","noticing->questioned"],"focus_node_id":"noticing","note_zh":"完整展示引发质疑的数据建模问题。"}]}'
  ),
  (
    'queue-primary',
    'queue',
    'queue',
    'queue a restart job',
    '将重启任务加入队列',
    'The controller queued the restart job.',
    '控制器将重启任务加入了队列。',
    'The controller queued the restart job behind the backup when memory use climbed above ninety percent.',
    '当内存使用量升至百分之九十以上时，控制器把重启任务排在了备份任务之后。',
    'automated-recovery',
    '{"schema_version":2,"root_action_id":"queued","nodes":[{"id":"queued","text":"queued","kind":"action","label_zh":"把重启任务安排进执行队列"},{"id":"controller","text":"The controller","kind":"core","label_zh":"自动安排恢复任务的控制器"},{"id":"restart-job","text":"the restart job","kind":"core","label_zh":"等待执行的服务重启任务"},{"id":"backup","text":"behind the backup","kind":"modifier","label_zh":"重启任务在队列中的相对位置"},{"id":"climbed","text":"climbed","kind":"action","label_zh":"内存使用量上升到危险水平"},{"id":"memory-use","text":"memory use","kind":"core","label_zh":"触发恢复流程的内存指标"},{"id":"ninety-percent","text":"above ninety percent","kind":"core","label_zh":"导致任务入队的内存水平"}],"links":[{"id":"queued->controller","from":"queued","to":"controller","kind":"core","relation_type":"actor","label_zh":"控制器负责安排重启任务"},{"id":"queued->restart-job","from":"queued","to":"restart-job","kind":"core","relation_type":"target","label_zh":"进入队列的是重启任务"},{"id":"backup->queued","from":"backup","to":"queued","kind":"modifier","relation_type":"sequence","label_zh":"重启任务排在备份任务之后"},{"id":"climbed->memory-use","from":"climbed","to":"memory-use","kind":"core","relation_type":"actor","label_zh":"内存使用量出现明显上升"},{"id":"climbed->ninety-percent","from":"climbed","to":"ninety-percent","kind":"core","relation_type":"target","label_zh":"内存用量升至百分之九十以上"},{"id":"climbed->queued","from":"climbed","to":"queued","kind":"modifier","relation_type":"condition","label_zh":"内存用量过高时控制器才安排重启"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The controller queued the restart job.","sentence_zh":"控制器将重启任务加入了队列。","add_node_ids":["queued","controller","restart-job"],"add_link_ids":["queued->controller","queued->restart-job"],"focus_node_id":"queued","note_zh":"先交代自动入队的系统和恢复任务。"},{"step_no":2,"label":"顺序","sentence_en":"The controller queued the restart job behind the backup.","sentence_zh":"控制器把重启任务排在了备份任务之后。","add_node_ids":["backup"],"add_link_ids":["backup->queued"],"focus_node_id":"backup","note_zh":"明确重启任务不会抢在备份之前执行。"},{"step_no":3,"label":"条件","sentence_en":"The controller queued the restart job behind the backup when memory use climbed above ninety percent.","sentence_zh":"当内存使用量升至百分之九十以上时，控制器把重启任务排在了备份任务之后。","add_node_ids":["climbed","memory-use","ninety-percent"],"add_link_ids":["climbed->memory-use","climbed->ninety-percent","climbed->queued"],"focus_node_id":"climbed","note_zh":"加入自动恢复流程的监控触发条件。"}]}'
  ),
  (
    'queue-up-primary',
    'queue-up',
    'queue up',
    'queue up at a gateway',
    '排队等待处理',
    'Payment requests queued up.',
    '支付请求排起了队。',
    'Payment requests queued up at the API gateway during the regional outage by the hundreds.',
    '区域故障期间，数百条支付请求在 API 网关处排队等待。',
    'gateway-outage',
    '{"schema_version":2,"root_action_id":"queued-up","nodes":[{"id":"queued-up","text":"queued up","kind":"action","label_zh":"请求形成等待队列"},{"id":"payment-requests","text":"Payment requests","kind":"core","label_zh":"暂时无法立即处理的支付请求"},{"id":"api-gateway","text":"at the API gateway","kind":"modifier","label_zh":"支付请求积压的位置"},{"id":"regional-outage","text":"during the regional outage","kind":"modifier","label_zh":"请求排队时发生的区域故障"},{"id":"hundreds","text":"by the hundreds","kind":"modifier","label_zh":"排队请求达到的大致规模"}],"links":[{"id":"queued-up->payment-requests","from":"queued-up","to":"payment-requests","kind":"core","relation_type":"actor","label_zh":"大量支付请求形成了队列"},{"id":"api-gateway->queued-up","from":"api-gateway","to":"queued-up","kind":"modifier","relation_type":"place","label_zh":"请求积压在API网关处"},{"id":"regional-outage->queued-up","from":"regional-outage","to":"queued-up","kind":"modifier","relation_type":"time","label_zh":"区域故障期间请求持续等待"},{"id":"hundreds->payment-requests","from":"hundreds","to":"payment-requests","kind":"modifier","relation_type":"degree","label_zh":"等待处理的支付请求多达数百条"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Payment requests queued up.","sentence_zh":"支付请求排起了队。","add_node_ids":["queued-up","payment-requests"],"add_link_ids":["queued-up->payment-requests"],"focus_node_id":"queued-up","note_zh":"主干呈现请求无法立即处理的状态。"},{"step_no":2,"label":"场景","sentence_en":"Payment requests queued up at the API gateway.","sentence_zh":"支付请求在 API 网关处排队等待。","add_node_ids":["api-gateway"],"add_link_ids":["api-gateway->queued-up"],"focus_node_id":"api-gateway","note_zh":"指出请求具体积压在系统的哪个位置。"},{"step_no":3,"label":"时间","sentence_en":"Payment requests queued up at the API gateway during the regional outage.","sentence_zh":"区域故障期间，支付请求在 API 网关处排队等待。","add_node_ids":["regional-outage"],"add_link_ids":["regional-outage->queued-up"],"focus_node_id":"regional-outage","note_zh":"补充请求开始积压的故障时段。"},{"step_no":4,"label":"程度","sentence_en":"Payment requests queued up at the API gateway during the regional outage by the hundreds.","sentence_zh":"区域故障期间，数百条支付请求在 API 网关处排队等待。","add_node_ids":["hundreds"],"add_link_ids":["hundreds->payment-requests"],"focus_node_id":"hundreds","note_zh":"最后说明等待请求的实际规模。"}]}'
  ),
  (
    'quit-primary',
    'quit',
    'quit',
    'quit a migration project',
    '退出迁移项目',
    'Dana quit the migration project.',
    'Dana 退出了迁移项目。',
    'Dana quit the migration project after three failed runs corrupted the test archive in the same week.',
    '同一周内三次失败运行破坏测试存档后，Dana 退出了迁移项目。',
    'failed-migration',
    '{"schema_version":2,"root_action_id":"quit","nodes":[{"id":"quit","text":"quit","kind":"action","label_zh":"停止参与迁移项目"},{"id":"dana","text":"Dana","kind":"core","label_zh":"决定退出项目的工程师"},{"id":"migration-project","text":"the migration project","kind":"core","label_zh":"Dana不再继续参与的项目"},{"id":"corrupted","text":"corrupted","kind":"action","label_zh":"多次故障破坏测试存档"},{"id":"failed-runs","text":"three failed runs","kind":"core","label_zh":"连续出现的三次迁移失败"},{"id":"test-archive","text":"the test archive","kind":"core","label_zh":"被失败运行破坏的测试存档"},{"id":"same-week","text":"in the same week","kind":"modifier","label_zh":"三次失败集中发生的时间范围"}],"links":[{"id":"quit->dana","from":"quit","to":"dana","kind":"core","relation_type":"actor","label_zh":"Dana作出了退出项目的决定"},{"id":"quit->migration-project","from":"quit","to":"migration-project","kind":"core","relation_type":"target","label_zh":"她退出的是迁移项目"},{"id":"corrupted->failed-runs","from":"corrupted","to":"failed-runs","kind":"core","relation_type":"actor","label_zh":"三次失败运行造成数据破坏"},{"id":"corrupted->test-archive","from":"corrupted","to":"test-archive","kind":"core","relation_type":"target","label_zh":"受损的是迁移测试存档"},{"id":"corrupted->quit","from":"corrupted","to":"quit","kind":"modifier","relation_type":"reason","label_zh":"测试存档反复受损促使Dana退出"},{"id":"same-week->failed-runs","from":"same-week","to":"failed-runs","kind":"modifier","relation_type":"time","label_zh":"三次失败都集中在同一周"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Dana quit the migration project.","sentence_zh":"Dana 退出了迁移项目。","add_node_ids":["quit","dana","migration-project"],"add_link_ids":["quit->dana","quit->migration-project"],"focus_node_id":"quit","note_zh":"先直接表达停止参与项目的决定。"},{"step_no":2,"label":"原因","sentence_en":"Dana quit the migration project after three failed runs corrupted the test archive.","sentence_zh":"三次失败运行破坏测试存档后，Dana 退出了迁移项目。","add_node_ids":["corrupted","failed-runs","test-archive"],"add_link_ids":["corrupted->failed-runs","corrupted->test-archive","corrupted->quit"],"focus_node_id":"corrupted","note_zh":"加入导致她停止项目工作的严重后果。"},{"step_no":3,"label":"时间","sentence_en":"Dana quit the migration project after three failed runs corrupted the test archive in the same week.","sentence_zh":"同一周内三次失败运行破坏测试存档后，Dana 退出了迁移项目。","add_node_ids":["same-week"],"add_link_ids":["same-week->failed-runs"],"focus_node_id":"same-week","note_zh":"说明这些失败在短时间内连续发生。"}]}'
  ),
  (
    'quote-primary',
    'quote',
    'quote',
    'quote an error message',
    '引用错误信息',
    'The support engineer quoted the error message.',
    '支持工程师引用了错误信息。',
    'The support engineer quoted the error message verbatim in the customer ticket with the surrounding diagnostic context.',
    '支持工程师在客户工单中逐字引用了错误信息，并保留了周边诊断内容。',
    'support-ticket',
    '{"schema_version":2,"root_action_id":"quoted","nodes":[{"id":"quoted","text":"quoted","kind":"action","label_zh":"引用系统显示的错误信息"},{"id":"support-engineer","text":"The support engineer","kind":"core","label_zh":"记录错误内容的支持工程师"},{"id":"error-message","text":"the error message","kind":"core","label_zh":"工单中引用的系统提示"},{"id":"verbatim","text":"verbatim","kind":"modifier","label_zh":"错误信息按原文记录"},{"id":"customer-ticket","text":"in the customer ticket","kind":"modifier","label_zh":"引用内容出现的客户工单"},{"id":"diagnostic-context","text":"with the surrounding diagnostic context","kind":"modifier","label_zh":"与错误信息一起保留的诊断内容"}],"links":[{"id":"quoted->support-engineer","from":"quoted","to":"support-engineer","kind":"core","relation_type":"actor","label_zh":"支持工程师记录了引用内容"},{"id":"quoted->error-message","from":"quoted","to":"error-message","kind":"core","relation_type":"target","label_zh":"被引用的是系统错误信息"},{"id":"verbatim->quoted","from":"verbatim","to":"quoted","kind":"modifier","relation_type":"manner","label_zh":"工程师保留了错误信息的原始措辞"},{"id":"customer-ticket->quoted","from":"customer-ticket","to":"quoted","kind":"modifier","relation_type":"place","label_zh":"这段引用写在客户支持工单中"},{"id":"diagnostic-context->error-message","from":"diagnostic-context","to":"error-message","kind":"modifier","relation_type":"content","label_zh":"错误信息旁还保留了相关诊断内容"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The support engineer quoted the error message.","sentence_zh":"支持工程师引用了错误信息。","add_node_ids":["quoted","support-engineer","error-message"],"add_link_ids":["quoted->support-engineer","quoted->error-message"],"focus_node_id":"quoted","note_zh":"先说明工程师记录了哪段系统内容。"},{"step_no":2,"label":"方式","sentence_en":"The support engineer quoted the error message verbatim.","sentence_zh":"支持工程师逐字引用了错误信息。","add_node_ids":["verbatim"],"add_link_ids":["verbatim->quoted"],"focus_node_id":"verbatim","note_zh":"强调错误内容没有经过改写。"},{"step_no":3,"label":"场景","sentence_en":"The support engineer quoted the error message verbatim in the customer ticket.","sentence_zh":"支持工程师在客户工单中逐字引用了错误信息。","add_node_ids":["customer-ticket"],"add_link_ids":["customer-ticket->quoted"],"focus_node_id":"customer-ticket","note_zh":"指出这段引用被记录在什么位置。"},{"step_no":4,"label":"对象细节","sentence_en":"The support engineer quoted the error message verbatim in the customer ticket with the surrounding diagnostic context.","sentence_zh":"支持工程师在客户工单中逐字引用了错误信息，并保留了周边诊断内容。","add_node_ids":["diagnostic-context"],"add_link_ids":["diagnostic-context->error-message"],"focus_node_id":"diagnostic-context","note_zh":"补充帮助理解错误信息的相关诊断内容。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
