-- Generated verb paths batch batch-003.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'race-primary',
    'race',
    'race',
    'race to update shared state',
    '竞相操作共享状态，形成竞态',
    'Two workers raced.',
    '两个工作进程发生了竞态。',
    'Two workers raced to update the same cache entry after the lock expired.',
    '锁失效后，两个工作进程竞相更新同一个缓存项。',
    'cache-update-race',
    '{"schema_version":2,"root_action_id":"race-action","nodes":[{"id":"race-action","text":"raced","kind":"action","label_zh":"发生竞态操作"},{"id":"workers","text":"Two workers","kind":"core","label_zh":"同时运行的两个工作进程"},{"id":"update-action","text":"update","kind":"action","label_zh":"尝试写入缓存"},{"id":"cache-entry","text":"the same cache entry","kind":"core","label_zh":"两个进程争用的缓存项"},{"id":"expire-action","text":"expired","kind":"action","label_zh":"锁失效"},{"id":"lock","text":"the lock","kind":"core","label_zh":"原本限制并发写入的锁"}],"links":[{"id":"race-action->workers","from":"race-action","to":"workers","kind":"core","relation_type":"actor","label_zh":"两个工作进程参与竞态"},{"id":"race-action->update-action","from":"race-action","to":"update-action","kind":"core","relation_type":"nested_action","label_zh":"竞相执行的操作是更新"},{"id":"update-action->workers","from":"update-action","to":"workers","kind":"core","relation_type":"shared_actor","label_zh":"更新仍由这两个工作进程执行"},{"id":"update-action->cache-entry","from":"update-action","to":"cache-entry","kind":"core","relation_type":"target","label_zh":"更新指向同一个缓存项"},{"id":"expire-action->lock","from":"expire-action","to":"lock","kind":"core","relation_type":"actor","label_zh":"发生失效的是并发锁"},{"id":"expire-action->race-action","from":"expire-action","to":"race-action","kind":"modifier","relation_type":"time","label_zh":"锁失效后才出现这次竞态"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Two workers raced.","sentence_zh":"两个工作进程发生了竞态。","add_node_ids":["race-action","workers"],"add_link_ids":["race-action->workers"],"focus_node_id":"race-action","note_zh":"先呈现两个进程同时争抢执行机会。"},{"step_no":2,"label":"竞态目标","sentence_en":"Two workers raced to update the same cache entry.","sentence_zh":"两个工作进程竞相更新同一个缓存项。","add_node_ids":["update-action","cache-entry"],"add_link_ids":["race-action->update-action","update-action->workers","update-action->cache-entry"],"focus_node_id":"update-action","note_zh":"补出冲突操作及其共享对象。"},{"step_no":3,"label":"锁失效时点","sentence_en":"Two workers raced to update the same cache entry after the lock expired.","sentence_zh":"锁失效后，两个工作进程竞相更新同一个缓存项。","add_node_ids":["expire-action","lock"],"add_link_ids":["expire-action->lock","expire-action->race-action"],"focus_node_id":"expire-action","note_zh":"说明竞态是在锁失效之后出现的。"}]}'
  ),
  (
    'rain-primary',
    'rain',
    'rain',
    'alerts rain into a channel',
    '大量事物如雨般接连落下或涌入',
    'Error alerts rained into the team channel.',
    '错误告警如雨般涌入团队频道。',
    'Error alerts rained into the team channel during Monday''s rollout.',
    '周一发布期间，错误告警如雨般涌入团队频道。',
    'rollout-alert-storm',
    '{"schema_version":2,"root_action_id":"rain-action","nodes":[{"id":"rain-action","text":"rained","kind":"action","label_zh":"密集涌入"},{"id":"error-alerts","text":"Error alerts","kind":"core","label_zh":"接连出现的错误告警"},{"id":"team-channel","text":"into the team channel","kind":"modifier","label_zh":"告警涌入的团队频道"},{"id":"monday-rollout","text":"during Monday''s rollout","kind":"modifier","label_zh":"告警集中出现的发布时段"}],"links":[{"id":"rain-action->error-alerts","from":"rain-action","to":"error-alerts","kind":"core","relation_type":"actor","label_zh":"如雨般涌来的是错误告警"},{"id":"team-channel->rain-action","from":"team-channel","to":"rain-action","kind":"modifier","relation_type":"place","label_zh":"错误告警涌进团队频道"},{"id":"monday-rollout->rain-action","from":"monday-rollout","to":"rain-action","kind":"modifier","relation_type":"time","label_zh":"密集告警出现在周一发布期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Error alerts rained into the team channel.","sentence_zh":"错误告警如雨般涌入团队频道。","add_node_ids":["rain-action","error-alerts","team-channel"],"add_link_ids":["rain-action->error-alerts","team-channel->rain-action"],"focus_node_id":"rain-action","note_zh":"rain 在这里形容告警大量而密集地出现。"},{"step_no":2,"label":"发布时段","sentence_en":"Error alerts rained into the team channel during Monday''s rollout.","sentence_zh":"周一发布期间，错误告警如雨般涌入团队频道。","add_node_ids":["monday-rollout"],"add_link_ids":["monday-rollout->rain-action"],"focus_node_id":"monday-rollout","note_zh":"加入告警集中爆发的具体场景。"}]}'
  ),
  (
    'raise-primary',
    'raise',
    'raise',
    'raise a timeout limit',
    '提高数值或限制',
    'The platform team raised the timeout limit.',
    '平台团队提高了超时上限。',
    'The platform team raised the timeout limit to ten seconds on the staging cluster.',
    '平台团队把预发布集群的超时上限提高到了十秒。',
    'staging-timeout-change',
    '{"schema_version":2,"root_action_id":"raise-action","nodes":[{"id":"raise-action","text":"raised","kind":"action","label_zh":"调高限制"},{"id":"platform-team","text":"The platform team","kind":"core","label_zh":"修改超时配置的平台团队"},{"id":"timeout-limit","text":"the timeout limit","kind":"core","label_zh":"被调高的超时上限"},{"id":"ten-seconds","text":"to ten seconds","kind":"modifier","label_zh":"调整后的超时时长"},{"id":"staging-cluster","text":"on the staging cluster","kind":"modifier","label_zh":"配置生效的预发布集群"}],"links":[{"id":"raise-action->platform-team","from":"raise-action","to":"platform-team","kind":"core","relation_type":"actor","label_zh":"平台团队执行了调高操作"},{"id":"raise-action->timeout-limit","from":"raise-action","to":"timeout-limit","kind":"core","relation_type":"target","label_zh":"被提高的是超时上限"},{"id":"ten-seconds->raise-action","from":"ten-seconds","to":"raise-action","kind":"modifier","relation_type":"result","label_zh":"超时上限最终变为十秒"},{"id":"staging-cluster->raise-action","from":"staging-cluster","to":"raise-action","kind":"modifier","relation_type":"place","label_zh":"这次配置修改发生在预发布集群"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The platform team raised the timeout limit.","sentence_zh":"平台团队提高了超时上限。","add_node_ids":["raise-action","platform-team","timeout-limit"],"add_link_ids":["raise-action->platform-team","raise-action->timeout-limit"],"focus_node_id":"timeout-limit","note_zh":"先明确团队提高了哪项限制。"},{"step_no":2,"label":"调整结果","sentence_en":"The platform team raised the timeout limit to ten seconds.","sentence_zh":"平台团队把超时上限提高到了十秒。","add_node_ids":["ten-seconds"],"add_link_ids":["ten-seconds->raise-action"],"focus_node_id":"ten-seconds","note_zh":"补充修改后达到的具体数值。"},{"step_no":3,"label":"生效场景","sentence_en":"The platform team raised the timeout limit to ten seconds on the staging cluster.","sentence_zh":"平台团队把预发布集群的超时上限提高到了十秒。","add_node_ids":["staging-cluster"],"add_link_ids":["staging-cluster->raise-action"],"focus_node_id":"staging-cluster","note_zh":"限定此次调整所在的集群。"}]}'
  ),
  (
    'ramp-down-primary',
    'ramp-down',
    'ramp down',
    'ramp down background traffic',
    '有控制地逐步减少流量',
    'The controller ramped down background traffic.',
    '控制器逐步减少了后台流量。',
    'The controller ramped down background traffic to 20 percent once peak hours ended.',
    '高峰时段一结束，控制器就把后台流量逐步降到了百分之二十。',
    'traffic-ramp-down',
    '{"schema_version":2,"root_action_id":"ramp-down-action","nodes":[{"id":"ramp-down-action","text":"ramped down","kind":"action","label_zh":"逐步压低流量"},{"id":"controller","text":"The controller","kind":"core","label_zh":"自动调节流量的控制器"},{"id":"background-traffic","text":"background traffic","kind":"core","label_zh":"被逐步减少的后台流量"},{"id":"twenty-percent","text":"to 20 percent","kind":"modifier","label_zh":"流量最终保留的比例"},{"id":"end-action","text":"ended","kind":"action","label_zh":"高峰时段结束"},{"id":"peak-hours","text":"peak hours","kind":"core","label_zh":"已经结束的访问高峰"}],"links":[{"id":"ramp-down-action->controller","from":"ramp-down-action","to":"controller","kind":"core","relation_type":"actor","label_zh":"控制器执行了流量下调"},{"id":"ramp-down-action->background-traffic","from":"ramp-down-action","to":"background-traffic","kind":"core","relation_type":"target","label_zh":"下调对象是后台流量"},{"id":"twenty-percent->ramp-down-action","from":"twenty-percent","to":"ramp-down-action","kind":"modifier","relation_type":"result","label_zh":"后台流量逐步降至百分之二十"},{"id":"end-action->peak-hours","from":"end-action","to":"peak-hours","kind":"core","relation_type":"actor","label_zh":"结束的是访问高峰时段"},{"id":"end-action->ramp-down-action","from":"end-action","to":"ramp-down-action","kind":"modifier","relation_type":"time","label_zh":"高峰结束后开始逐步降低流量"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The controller ramped down background traffic.","sentence_zh":"控制器逐步减少了后台流量。","add_node_ids":["ramp-down-action","controller","background-traffic"],"add_link_ids":["ramp-down-action->controller","ramp-down-action->background-traffic"],"focus_node_id":"ramp-down-action","note_zh":"ramp down 强调减少过程是逐步进行的。"},{"step_no":2,"label":"目标比例","sentence_en":"The controller ramped down background traffic to 20 percent.","sentence_zh":"控制器把后台流量逐步降到了百分之二十。","add_node_ids":["twenty-percent"],"add_link_ids":["twenty-percent->ramp-down-action"],"focus_node_id":"twenty-percent","note_zh":"给出流量下降后保留的比例。"},{"step_no":3,"label":"高峰结束后","sentence_en":"The controller ramped down background traffic to 20 percent once peak hours ended.","sentence_zh":"高峰时段一结束，控制器就把后台流量逐步降到了百分之二十。","add_node_ids":["end-action","peak-hours"],"add_link_ids":["end-action->peak-hours","end-action->ramp-down-action"],"focus_node_id":"end-action","note_zh":"说明流量下调由高峰结束这一时点触发。"}]}'
  ),
  (
    'ramp-up-primary',
    'ramp-up',
    'ramp up',
    'ramp up API traffic',
    '逐步增加流量或负载',
    'We ramped up API traffic.',
    '我们逐步增加了接口流量。',
    'We ramped up API traffic gradually to 5,000 requests per second.',
    '我们逐步增加接口流量，最终达到每秒五千次请求。',
    'api-load-ramp',
    '{"schema_version":2,"root_action_id":"ramp-up-action","nodes":[{"id":"ramp-up-action","text":"ramped up","kind":"action","label_zh":"逐步提高请求流量"},{"id":"team","text":"We","kind":"core","label_zh":"执行流量提升的团队"},{"id":"api-traffic","text":"API traffic","kind":"core","label_zh":"逐步增加的接口流量"},{"id":"gradually","text":"gradually","kind":"modifier","label_zh":"平缓增加而非瞬间放量"},{"id":"request-rate","text":"to 5,000 requests per second","kind":"modifier","label_zh":"流量最终达到的请求速率"}],"links":[{"id":"ramp-up-action->team","from":"ramp-up-action","to":"team","kind":"core","relation_type":"actor","label_zh":"团队执行了逐步放量"},{"id":"ramp-up-action->api-traffic","from":"ramp-up-action","to":"api-traffic","kind":"core","relation_type":"target","label_zh":"被增加的是接口流量"},{"id":"gradually->ramp-up-action","from":"gradually","to":"ramp-up-action","kind":"modifier","relation_type":"manner","label_zh":"请求量以渐进方式提高"},{"id":"request-rate->ramp-up-action","from":"request-rate","to":"ramp-up-action","kind":"modifier","relation_type":"result","label_zh":"放量后达到每秒五千次请求"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We ramped up API traffic.","sentence_zh":"我们逐步增加了接口流量。","add_node_ids":["ramp-up-action","team","api-traffic"],"add_link_ids":["ramp-up-action->team","ramp-up-action->api-traffic"],"focus_node_id":"api-traffic","note_zh":"先呈现逐步提高接口流量这一操作。"},{"step_no":2,"label":"渐进方式","sentence_en":"We ramped up API traffic gradually.","sentence_zh":"我们以渐进方式增加了接口流量。","add_node_ids":["gradually"],"add_link_ids":["gradually->ramp-up-action"],"focus_node_id":"gradually","note_zh":"明确流量不是一次性提升的。"},{"step_no":3,"label":"负载终点","sentence_en":"We ramped up API traffic gradually to 5,000 requests per second.","sentence_zh":"我们逐步增加接口流量，最终达到每秒五千次请求。","add_node_ids":["request-rate"],"add_link_ids":["request-rate->ramp-up-action"],"focus_node_id":"request-rate","note_zh":"加入渐进放量最终达到的速率。"}]}'
  ),
  (
    'rank-primary',
    'rank',
    'rank',
    'rank recent fixes higher',
    '按优先顺序排列结果',
    'The search service ranks fixes.',
    '搜索服务对修复方案进行排序。',
    'The search service ranks recent fixes above older forum posts for crash-related queries.',
    '对于崩溃相关查询，搜索服务把近期修复方案排在旧论坛帖子之前。',
    'search-result-ranking',
    '{"schema_version":2,"root_action_id":"rank-action","nodes":[{"id":"rank-action","text":"ranks","kind":"action","label_zh":"安排搜索结果顺序"},{"id":"search-service","text":"The search service","kind":"core","label_zh":"负责结果排序的搜索服务"},{"id":"fixes","text":"fixes","kind":"core","label_zh":"被放入结果列表的修复方案"},{"id":"recent","text":"recent","kind":"modifier","label_zh":"时间较新的修复方案"},{"id":"older-posts","text":"above older forum posts","kind":"modifier","label_zh":"修复方案排在旧论坛帖子之前"},{"id":"crash-queries","text":"for crash-related queries","kind":"modifier","label_zh":"采用该排序规则的崩溃类查询"}],"links":[{"id":"rank-action->search-service","from":"rank-action","to":"search-service","kind":"core","relation_type":"actor","label_zh":"搜索服务决定结果次序"},{"id":"rank-action->fixes","from":"rank-action","to":"fixes","kind":"core","relation_type":"target","label_zh":"排序涉及修复方案"},{"id":"recent->fixes","from":"recent","to":"fixes","kind":"modifier","relation_type":"time","label_zh":"优先考虑的是近期修复方案"},{"id":"older-posts->rank-action","from":"older-posts","to":"rank-action","kind":"modifier","relation_type":"sequence","label_zh":"近期修复方案位于旧论坛帖子之前"},{"id":"crash-queries->rank-action","from":"crash-queries","to":"rank-action","kind":"modifier","relation_type":"scope","label_zh":"该顺序仅用于崩溃相关查询"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The search service ranks fixes.","sentence_zh":"搜索服务对修复方案进行排序。","add_node_ids":["rank-action","search-service","fixes"],"add_link_ids":["rank-action->search-service","rank-action->fixes"],"focus_node_id":"rank-action","note_zh":"建立搜索服务排列修复方案的核心信息。"},{"step_no":2,"label":"方案新旧","sentence_en":"The search service ranks recent fixes.","sentence_zh":"搜索服务对近期修复方案进行排序。","add_node_ids":["recent"],"add_link_ids":["recent->fixes"],"focus_node_id":"recent","note_zh":"限定参与优先排序的是近期方案。"},{"step_no":3,"label":"相对次序","sentence_en":"The search service ranks recent fixes above older forum posts.","sentence_zh":"搜索服务把近期修复方案排在旧论坛帖子之前。","add_node_ids":["older-posts"],"add_link_ids":["older-posts->rank-action"],"focus_node_id":"older-posts","note_zh":"补出两类搜索结果之间的先后位置。"},{"step_no":4,"label":"查询范围","sentence_en":"The search service ranks recent fixes above older forum posts for crash-related queries.","sentence_zh":"对于崩溃相关查询，搜索服务把近期修复方案排在旧论坛帖子之前。","add_node_ids":["crash-queries"],"add_link_ids":["crash-queries->rank-action"],"focus_node_id":"crash-queries","note_zh":"把这项排序策略限定在特定查询类型中。"}]}'
  ),
  (
    'rate-primary',
    'rate',
    'rate',
    'rate an onboarding flow',
    '对体验作出等级评价',
    'Beta users rated the onboarding flow.',
    '测试用户评价了引导流程。',
    'Beta users rated the new onboarding flow highly after completing their first setup.',
    '测试用户完成首次设置后，对新的引导流程评价很高。',
    'onboarding-feedback',
    '{"schema_version":2,"root_action_id":"rate-action","nodes":[{"id":"rate-action","text":"rated","kind":"action","label_zh":"给使用体验打分"},{"id":"beta-users","text":"Beta users","kind":"core","label_zh":"参与评价的测试用户"},{"id":"onboarding-flow","text":"the onboarding flow","kind":"core","label_zh":"接受评价的引导流程"},{"id":"new","text":"new","kind":"modifier","label_zh":"刚上线的引导流程"},{"id":"highly","text":"highly","kind":"modifier","label_zh":"用户给出的较高评价"},{"id":"complete-action","text":"completing","kind":"action","label_zh":"完成首次设置"},{"id":"first-setup","text":"their first setup","kind":"core","label_zh":"测试用户完成的首次设置"}],"links":[{"id":"rate-action->beta-users","from":"rate-action","to":"beta-users","kind":"core","relation_type":"actor","label_zh":"测试用户给出了评价"},{"id":"rate-action->onboarding-flow","from":"rate-action","to":"onboarding-flow","kind":"core","relation_type":"target","label_zh":"评价针对引导流程"},{"id":"new->onboarding-flow","from":"new","to":"onboarding-flow","kind":"modifier","relation_type":"time","label_zh":"被评价的是新引导流程"},{"id":"highly->rate-action","from":"highly","to":"rate-action","kind":"modifier","relation_type":"degree","label_zh":"测试用户给出的评分较高"},{"id":"complete-action->beta-users","from":"complete-action","to":"beta-users","kind":"core","relation_type":"shared_actor","label_zh":"完成设置的也是这些测试用户"},{"id":"complete-action->first-setup","from":"complete-action","to":"first-setup","kind":"core","relation_type":"target","label_zh":"用户完成的是首次设置"},{"id":"complete-action->rate-action","from":"complete-action","to":"rate-action","kind":"modifier","relation_type":"time","label_zh":"评价发生在首次设置完成之后"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Beta users rated the onboarding flow.","sentence_zh":"测试用户评价了引导流程。","add_node_ids":["rate-action","beta-users","onboarding-flow"],"add_link_ids":["rate-action->beta-users","rate-action->onboarding-flow"],"focus_node_id":"onboarding-flow","note_zh":"明确谁评价了哪段产品体验。"},{"step_no":2,"label":"流程版本","sentence_en":"Beta users rated the new onboarding flow.","sentence_zh":"测试用户评价了新的引导流程。","add_node_ids":["new"],"add_link_ids":["new->onboarding-flow"],"focus_node_id":"new","note_zh":"指出评价针对刚推出的流程。"},{"step_no":3,"label":"评价程度","sentence_en":"Beta users rated the new onboarding flow highly.","sentence_zh":"测试用户对新的引导流程评价很高。","add_node_ids":["highly"],"add_link_ids":["highly->rate-action"],"focus_node_id":"highly","note_zh":"补充用户评价所处的高低程度。"},{"step_no":4,"label":"体验完成后","sentence_en":"Beta users rated the new onboarding flow highly after completing their first setup.","sentence_zh":"测试用户完成首次设置后，对新的引导流程评价很高。","add_node_ids":["complete-action","first-setup"],"add_link_ids":["complete-action->beta-users","complete-action->first-setup","complete-action->rate-action"],"focus_node_id":"complete-action","note_zh":"说明用户是在实际走完首次设置后评分的。"}]}'
  ),
  (
    'reach-primary',
    'reach',
    'reach',
    'reach a migration milestone',
    '达到某个进度或水平',
    'The data migration reached 80 percent completion.',
    '数据迁移达到了百分之八十的完成度。',
    'The data migration reached 80 percent completion before the maintenance window closed.',
    '数据迁移在维护窗口关闭前达到了百分之八十的完成度。',
    'migration-progress',
    '{"schema_version":2,"root_action_id":"reach-action","nodes":[{"id":"reach-action","text":"reached","kind":"action","label_zh":"进度达到里程碑"},{"id":"data-migration","text":"The data migration","kind":"core","label_zh":"正在推进的数据迁移"},{"id":"completion-level","text":"80 percent completion","kind":"core","label_zh":"迁移达到的完成度"},{"id":"close-action","text":"closed","kind":"action","label_zh":"维护窗口关闭"},{"id":"maintenance-window","text":"the maintenance window","kind":"core","label_zh":"可执行迁移的维护时段"}],"links":[{"id":"reach-action->data-migration","from":"reach-action","to":"data-migration","kind":"core","relation_type":"actor","label_zh":"达到新进度的是数据迁移"},{"id":"reach-action->completion-level","from":"reach-action","to":"completion-level","kind":"core","relation_type":"target","label_zh":"迁移进度达到百分之八十"},{"id":"close-action->maintenance-window","from":"close-action","to":"maintenance-window","kind":"core","relation_type":"actor","label_zh":"关闭的是维护窗口"},{"id":"close-action->reach-action","from":"close-action","to":"reach-action","kind":"modifier","relation_type":"sequence","label_zh":"达到该进度早于维护窗口关闭"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The data migration reached 80 percent completion.","sentence_zh":"数据迁移达到了百分之八十的完成度。","add_node_ids":["reach-action","data-migration","completion-level"],"add_link_ids":["reach-action->data-migration","reach-action->completion-level"],"focus_node_id":"completion-level","note_zh":"reach 表示进度推进到明确的里程碑。"},{"step_no":2,"label":"窗口关闭前","sentence_en":"The data migration reached 80 percent completion before the maintenance window closed.","sentence_zh":"数据迁移在维护窗口关闭前达到了百分之八十的完成度。","add_node_ids":["close-action","maintenance-window"],"add_link_ids":["close-action->maintenance-window","close-action->reach-action"],"focus_node_id":"close-action","note_zh":"用维护窗口的关闭界定达成进度的先后关系。"}]}'
  ),
  (
    'reach-out-primary',
    'reach-out',
    'reach out',
    'reach out for help',
    '主动联系某人',
    'I reached out to the database team.',
    '我主动联系了数据库团队。',
    'I reached out to the database team for help after the deadlock reappeared.',
    '死锁再次出现后，我主动联系数据库团队寻求帮助。',
    'database-support-request',
    '{"schema_version":2,"root_action_id":"reach-out-action","nodes":[{"id":"reach-out-action","text":"reached out","kind":"action","label_zh":"主动发起联系"},{"id":"speaker","text":"I","kind":"core","label_zh":"寻求协助的人"},{"id":"database-team","text":"the database team","kind":"core","label_zh":"收到联系的数据库团队"},{"id":"for-help","text":"for help","kind":"modifier","label_zh":"此次联系是为了获得协助"},{"id":"reappear-action","text":"reappeared","kind":"action","label_zh":"死锁再次出现"},{"id":"deadlock","text":"the deadlock","kind":"core","label_zh":"重新发生的数据库死锁"}],"links":[{"id":"reach-out-action->speaker","from":"reach-out-action","to":"speaker","kind":"core","relation_type":"actor","label_zh":"我主动发起了联系"},{"id":"reach-out-action->database-team","from":"reach-out-action","to":"database-team","kind":"core","relation_type":"recipient","label_zh":"联系对象是数据库团队"},{"id":"for-help->reach-out-action","from":"for-help","to":"reach-out-action","kind":"modifier","relation_type":"purpose","label_zh":"主动联系是为了请求帮助"},{"id":"reappear-action->deadlock","from":"reappear-action","to":"deadlock","kind":"core","relation_type":"actor","label_zh":"再次出现的是死锁问题"},{"id":"reappear-action->reach-out-action","from":"reappear-action","to":"reach-out-action","kind":"modifier","relation_type":"time","label_zh":"死锁再次出现后才联系团队"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I reached out to the database team.","sentence_zh":"我主动联系了数据库团队。","add_node_ids":["reach-out-action","speaker","database-team"],"add_link_ids":["reach-out-action->speaker","reach-out-action->database-team"],"focus_node_id":"database-team","note_zh":"reach out to 后面接主动联系的对象。"},{"step_no":2,"label":"联系目的","sentence_en":"I reached out to the database team for help.","sentence_zh":"我主动联系数据库团队寻求帮助。","add_node_ids":["for-help"],"add_link_ids":["for-help->reach-out-action"],"focus_node_id":"for-help","note_zh":"加入这次主动沟通要解决的需求。"},{"step_no":3,"label":"问题复发后","sentence_en":"I reached out to the database team for help after the deadlock reappeared.","sentence_zh":"死锁再次出现后，我主动联系数据库团队寻求帮助。","add_node_ids":["reappear-action","deadlock"],"add_link_ids":["reappear-action->deadlock","reappear-action->reach-out-action"],"focus_node_id":"reappear-action","note_zh":"交代促成此次联系的故障时点。"}]}'
  ),
  (
    'react-primary',
    'react',
    'react',
    'react by retrying',
    '对情况作出回应',
    'The client reacted to a 429 response.',
    '客户端对一个 429 响应作出了反应。',
    'The client reacted to a 429 response by retrying after two seconds.',
    '客户端等待两秒后重试，以回应一个 429 响应。',
    'rate-limit-response',
    '{"schema_version":2,"root_action_id":"react-action","nodes":[{"id":"react-action","text":"reacted","kind":"action","label_zh":"对限流响应作出处理"},{"id":"client","text":"The client","kind":"core","label_zh":"接收到限流信息的客户端"},{"id":"rate-limit-response","text":"a 429 response","kind":"core","label_zh":"触发处理的限流响应"},{"id":"retry-action","text":"retrying","kind":"action","label_zh":"再次发送请求"},{"id":"two-seconds","text":"after two seconds","kind":"modifier","label_zh":"重试前等待的时间"}],"links":[{"id":"react-action->client","from":"react-action","to":"client","kind":"core","relation_type":"actor","label_zh":"客户端作出了回应"},{"id":"react-action->rate-limit-response","from":"react-action","to":"rate-limit-response","kind":"core","relation_type":"target","label_zh":"客户端回应的是 429 限流响应"},{"id":"retry-action->client","from":"retry-action","to":"client","kind":"core","relation_type":"shared_actor","label_zh":"执行重试的仍是该客户端"},{"id":"retry-action->react-action","from":"retry-action","to":"react-action","kind":"modifier","relation_type":"manner","label_zh":"客户端通过重试来回应限流"},{"id":"two-seconds->retry-action","from":"two-seconds","to":"retry-action","kind":"modifier","relation_type":"time","label_zh":"客户端等待两秒后再重试"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The client reacted to a 429 response.","sentence_zh":"客户端对一个 429 响应作出了反应。","add_node_ids":["react-action","client","rate-limit-response"],"add_link_ids":["react-action->client","react-action->rate-limit-response"],"focus_node_id":"react-action","note_zh":"react to 引出客户端所回应的情况。"},{"step_no":2,"label":"回应方式","sentence_en":"The client reacted to a 429 response by retrying.","sentence_zh":"客户端通过重试来回应一个 429 响应。","add_node_ids":["retry-action"],"add_link_ids":["retry-action->client","retry-action->react-action"],"focus_node_id":"retry-action","note_zh":"说明客户端采取的具体回应动作。"},{"step_no":3,"label":"重试等待","sentence_en":"The client reacted to a 429 response by retrying after two seconds.","sentence_zh":"客户端等待两秒后重试，以回应一个 429 响应。","add_node_ids":["two-seconds"],"add_link_ids":["two-seconds->retry-action"],"focus_node_id":"two-seconds","note_zh":"补充重试动作之前的等待时长。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'read-primary',
    'read',
    'read',
    'read a version number',
    '读取或阅读文本信息',
    'The release script reads the version number.',
    '发布脚本读取版本号。',
    'The release script reads the version number from package.json before creating the archive.',
    '发布脚本先从 package.json 中读取版本号，然后再创建归档文件。',
    'release-script-metadata',
    '{"schema_version":2,"root_action_id":"read-action","nodes":[{"id":"read-action","text":"reads","kind":"action","label_zh":"读取版本信息"},{"id":"release-script","text":"The release script","kind":"core","label_zh":"自动读取版本号的发布脚本"},{"id":"version-number","text":"the version number","kind":"core","label_zh":"脚本读取的版本信息"},{"id":"package-file","text":"from package.json","kind":"modifier","label_zh":"版本号所在的配置文件"},{"id":"create-action","text":"creating","kind":"action","label_zh":"生成发布归档"},{"id":"archive","text":"the archive","kind":"core","label_zh":"随后生成的归档文件"}],"links":[{"id":"read-action->release-script","from":"read-action","to":"release-script","kind":"core","relation_type":"actor","label_zh":"发布脚本执行读取"},{"id":"read-action->version-number","from":"read-action","to":"version-number","kind":"core","relation_type":"target","label_zh":"脚本读取的是版本号"},{"id":"package-file->read-action","from":"package-file","to":"read-action","kind":"modifier","relation_type":"place","label_zh":"版本号从 package.json 中取得"},{"id":"create-action->release-script","from":"create-action","to":"release-script","kind":"core","relation_type":"shared_actor","label_zh":"创建归档的也是该发布脚本"},{"id":"create-action->archive","from":"create-action","to":"archive","kind":"core","relation_type":"target","label_zh":"脚本随后创建归档文件"},{"id":"create-action->read-action","from":"create-action","to":"read-action","kind":"modifier","relation_type":"sequence","label_zh":"读取版本号发生在创建归档之前"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The release script reads the version number.","sentence_zh":"发布脚本读取版本号。","add_node_ids":["read-action","release-script","version-number"],"add_link_ids":["read-action->release-script","read-action->version-number"],"focus_node_id":"version-number","note_zh":"先说明脚本需要读取的关键信息。"},{"step_no":2,"label":"信息来源","sentence_en":"The release script reads the version number from package.json.","sentence_zh":"发布脚本从 package.json 中读取版本号。","add_node_ids":["package-file"],"add_link_ids":["package-file->read-action"],"focus_node_id":"package-file","note_zh":"指出版本号具体取自哪个文件。"},{"step_no":3,"label":"归档之前","sentence_en":"The release script reads the version number from package.json before creating the archive.","sentence_zh":"发布脚本先从 package.json 中读取版本号，然后再创建归档文件。","add_node_ids":["create-action","archive"],"add_link_ids":["create-action->release-script","create-action->archive","create-action->read-action"],"focus_node_id":"create-action","note_zh":"补出读取和创建归档之间的执行顺序。"}]}'
  ),
  (
    'realize-primary',
    'realize',
    'realize',
    'realize a job skipped files',
    '意识到此前未察觉的事实',
    'Nora realized that the backup job had skipped two folders.',
    'Nora 意识到备份任务漏掉了两个文件夹。',
    'Nora realized that the backup job had skipped two encrypted folders overnight.',
    'Nora 意识到备份任务在夜间漏掉了两个加密文件夹。',
    'backup-skip-discovery',
    '{"schema_version":2,"root_action_id":"realize-action","nodes":[{"id":"realize-action","text":"realized","kind":"action","label_zh":"察觉备份存在遗漏"},{"id":"nora","text":"Nora","kind":"core","label_zh":"发现问题的工程师"},{"id":"skip-action","text":"had skipped","kind":"action","label_zh":"备份任务遗漏文件夹"},{"id":"backup-job","text":"the backup job","kind":"core","label_zh":"发生遗漏的备份任务"},{"id":"folders","text":"two folders","kind":"core","label_zh":"未被备份的两个文件夹"},{"id":"encrypted","text":"encrypted","kind":"modifier","label_zh":"遗漏文件夹采用了加密"},{"id":"overnight","text":"overnight","kind":"modifier","label_zh":"遗漏发生在夜间运行期间"}],"links":[{"id":"realize-action->nora","from":"realize-action","to":"nora","kind":"core","relation_type":"actor","label_zh":"Nora 意识到了问题"},{"id":"realize-action->skip-action","from":"realize-action","to":"skip-action","kind":"core","relation_type":"content","label_zh":"她意识到的是备份任务发生了遗漏"},{"id":"skip-action->backup-job","from":"skip-action","to":"backup-job","kind":"core","relation_type":"actor","label_zh":"产生遗漏的是备份任务"},{"id":"skip-action->folders","from":"skip-action","to":"folders","kind":"core","relation_type":"target","label_zh":"任务漏掉了两个文件夹"},{"id":"encrypted->folders","from":"encrypted","to":"folders","kind":"modifier","relation_type":"quality","label_zh":"被漏掉的文件夹是加密的"},{"id":"overnight->skip-action","from":"overnight","to":"skip-action","kind":"modifier","relation_type":"time","label_zh":"备份遗漏发生在夜间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Nora realized that the backup job had skipped two folders.","sentence_zh":"Nora 意识到备份任务漏掉了两个文件夹。","add_node_ids":["realize-action","nora","skip-action","backup-job","folders"],"add_link_ids":["realize-action->nora","realize-action->skip-action","skip-action->backup-job","skip-action->folders"],"focus_node_id":"realize-action","note_zh":"realize 带出她后来才察觉的完整事实。"},{"step_no":2,"label":"文件夹特征","sentence_en":"Nora realized that the backup job had skipped two encrypted folders.","sentence_zh":"Nora 意识到备份任务漏掉了两个加密文件夹。","add_node_ids":["encrypted"],"add_link_ids":["encrypted->folders"],"focus_node_id":"encrypted","note_zh":"补充被遗漏文件夹的关键特征。"},{"step_no":3,"label":"夜间遗漏","sentence_en":"Nora realized that the backup job had skipped two encrypted folders overnight.","sentence_zh":"Nora 意识到备份任务在夜间漏掉了两个加密文件夹。","add_node_ids":["overnight"],"add_link_ids":["overnight->skip-action"],"focus_node_id":"overnight","note_zh":"指出遗漏发生在备份任务夜间运行时。"}]}'
  ),
  (
    'rebalance-primary',
    'rebalance',
    'rebalance',
    'rebalance pods across nodes',
    '重新分配资源以恢复均衡',
    'Kubernetes rebalanced the pods.',
    'Kubernetes 重新平衡了容器实例。',
    'Kubernetes rebalanced the pods across three nodes after one node recovered.',
    '一个节点恢复后，Kubernetes 在三个节点之间重新分配了容器实例。',
    'cluster-pod-rebalance',
    '{"schema_version":2,"root_action_id":"rebalance-action","nodes":[{"id":"rebalance-action","text":"rebalanced","kind":"action","label_zh":"重新分配工作负载"},{"id":"kubernetes","text":"Kubernetes","kind":"core","label_zh":"执行重新分配的集群系统"},{"id":"pods","text":"the pods","kind":"core","label_zh":"被重新分配的容器实例"},{"id":"three-nodes","text":"across three nodes","kind":"modifier","label_zh":"容器重新分布到三个节点"},{"id":"recover-action","text":"recovered","kind":"action","label_zh":"故障节点恢复运行"},{"id":"recovered-node","text":"one node","kind":"core","label_zh":"恢复可用的集群节点"}],"links":[{"id":"rebalance-action->kubernetes","from":"rebalance-action","to":"kubernetes","kind":"core","relation_type":"actor","label_zh":"Kubernetes 执行重新平衡"},{"id":"rebalance-action->pods","from":"rebalance-action","to":"pods","kind":"core","relation_type":"target","label_zh":"重新分配的是容器实例"},{"id":"three-nodes->rebalance-action","from":"three-nodes","to":"rebalance-action","kind":"modifier","relation_type":"place","label_zh":"容器实例被分散到三个节点"},{"id":"recover-action->recovered-node","from":"recover-action","to":"recovered-node","kind":"core","relation_type":"actor","label_zh":"恢复运行的是其中一个节点"},{"id":"recover-action->rebalance-action","from":"recover-action","to":"rebalance-action","kind":"modifier","relation_type":"time","label_zh":"节点恢复后集群才重新分配容器"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Kubernetes rebalanced the pods.","sentence_zh":"Kubernetes 重新平衡了容器实例。","add_node_ids":["rebalance-action","kubernetes","pods"],"add_link_ids":["rebalance-action->kubernetes","rebalance-action->pods"],"focus_node_id":"rebalance-action","note_zh":"rebalance 表示再次调整分配以恢复均衡。"},{"step_no":2,"label":"节点分布","sentence_en":"Kubernetes rebalanced the pods across three nodes.","sentence_zh":"Kubernetes 在三个节点之间重新分配了容器实例。","add_node_ids":["three-nodes"],"add_link_ids":["three-nodes->rebalance-action"],"focus_node_id":"three-nodes","note_zh":"交代重新平衡后的资源分布范围。"},{"step_no":3,"label":"节点恢复后","sentence_en":"Kubernetes rebalanced the pods across three nodes after one node recovered.","sentence_zh":"一个节点恢复后，Kubernetes 在三个节点之间重新分配了容器实例。","add_node_ids":["recover-action","recovered-node"],"add_link_ids":["recover-action->recovered-node","recover-action->rebalance-action"],"focus_node_id":"recover-action","note_zh":"说明节点恢复是重新平衡之前发生的事件。"}]}'
  ),
  (
    'rebase-primary',
    'rebase',
    'rebase',
    'rebase a branch onto main',
    '把分支提交变基到新的基线',
    'Priya rebased the feature branch onto main.',
    'Priya 把功能分支变基到了 main 之上。',
    'Priya rebased the feature branch onto main before opening the pull request.',
    'Priya 在创建拉取请求前，把功能分支变基到了 main 之上。',
    'git-branch-rebase',
    '{"schema_version":2,"root_action_id":"rebase-action","nodes":[{"id":"rebase-action","text":"rebased","kind":"action","label_zh":"重新设置分支基线"},{"id":"priya","text":"Priya","kind":"core","label_zh":"执行变基的开发者"},{"id":"feature-branch","text":"the feature branch","kind":"core","label_zh":"需要变基的功能分支"},{"id":"main-branch","text":"main","kind":"core","label_zh":"功能分支采用的新基线"},{"id":"open-action","text":"opening","kind":"action","label_zh":"创建拉取请求"},{"id":"pull-request","text":"the pull request","kind":"core","label_zh":"变基后准备创建的拉取请求"}],"links":[{"id":"rebase-action->priya","from":"rebase-action","to":"priya","kind":"core","relation_type":"actor","label_zh":"Priya 执行了分支变基"},{"id":"rebase-action->feature-branch","from":"rebase-action","to":"feature-branch","kind":"core","relation_type":"target","label_zh":"被变基的是功能分支"},{"id":"rebase-action->main-branch","from":"rebase-action","to":"main-branch","kind":"core","relation_type":"content","label_zh":"功能分支被重新放到 main 之上"},{"id":"open-action->priya","from":"open-action","to":"priya","kind":"core","relation_type":"shared_actor","label_zh":"创建拉取请求的也是 Priya"},{"id":"open-action->pull-request","from":"open-action","to":"pull-request","kind":"core","relation_type":"target","label_zh":"随后创建的是拉取请求"},{"id":"open-action->rebase-action","from":"open-action","to":"rebase-action","kind":"modifier","relation_type":"sequence","label_zh":"变基先于创建拉取请求"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Priya rebased the feature branch onto main.","sentence_zh":"Priya 把功能分支变基到了 main 之上。","add_node_ids":["rebase-action","priya","feature-branch","main-branch"],"add_link_ids":["rebase-action->priya","rebase-action->feature-branch","rebase-action->main-branch"],"focus_node_id":"rebase-action","note_zh":"onto main 指明变基后采用的新基线。"},{"step_no":2,"label":"提交请求前","sentence_en":"Priya rebased the feature branch onto main before opening the pull request.","sentence_zh":"Priya 在创建拉取请求前，把功能分支变基到了 main 之上。","add_node_ids":["open-action","pull-request"],"add_link_ids":["open-action->priya","open-action->pull-request","open-action->rebase-action"],"focus_node_id":"open-action","note_zh":"补充团队工作流中变基和创建请求的顺序。"}]}'
  ),
  (
    'recall-primary',
    'recall',
    'recall',
    'recall seeing a warning',
    '回想起曾经见过的信息',
    'I recall seeing the warning.',
    '我记得曾经看到过那条警告。',
    'I recall seeing the warning yesterday in the deployment log.',
    '我记得昨天在发布日志里看到过那条警告。',
    'deployment-log-memory',
    '{"schema_version":2,"root_action_id":"recall-action","nodes":[{"id":"recall-action","text":"recall","kind":"action","label_zh":"回想起过去的经历"},{"id":"speaker","text":"I","kind":"core","label_zh":"尝试回忆的人"},{"id":"see-action","text":"seeing","kind":"action","label_zh":"曾经看到警告"},{"id":"warning","text":"the warning","kind":"core","label_zh":"记忆中出现的警告"},{"id":"yesterday","text":"yesterday","kind":"modifier","label_zh":"看到警告的日期"},{"id":"deployment-log","text":"in the deployment log","kind":"modifier","label_zh":"警告当时出现的位置"}],"links":[{"id":"recall-action->speaker","from":"recall-action","to":"speaker","kind":"core","relation_type":"actor","label_zh":"我正在回想这段经历"},{"id":"recall-action->see-action","from":"recall-action","to":"see-action","kind":"core","relation_type":"content","label_zh":"回想的内容是曾经看到警告"},{"id":"see-action->speaker","from":"see-action","to":"speaker","kind":"core","relation_type":"shared_actor","label_zh":"看到警告的人同样是我"},{"id":"see-action->warning","from":"see-action","to":"warning","kind":"core","relation_type":"target","label_zh":"当时看到的是这条警告"},{"id":"yesterday->see-action","from":"yesterday","to":"see-action","kind":"modifier","relation_type":"time","label_zh":"看到警告发生在昨天"},{"id":"deployment-log->see-action","from":"deployment-log","to":"see-action","kind":"modifier","relation_type":"place","label_zh":"警告是在发布日志里看到的"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I recall seeing the warning.","sentence_zh":"我记得曾经看到过那条警告。","add_node_ids":["recall-action","speaker","see-action","warning"],"add_link_ids":["recall-action->speaker","recall-action->see-action","see-action->speaker","see-action->warning"],"focus_node_id":"recall-action","note_zh":"recall seeing 表示回想起过去确实发生的经历。"},{"step_no":2,"label":"记忆日期","sentence_en":"I recall seeing the warning yesterday.","sentence_zh":"我记得昨天看到过那条警告。","add_node_ids":["yesterday"],"add_link_ids":["yesterday->see-action"],"focus_node_id":"yesterday","note_zh":"给记忆中的查看动作加入日期。"},{"step_no":3,"label":"日志位置","sentence_en":"I recall seeing the warning yesterday in the deployment log.","sentence_zh":"我记得昨天在发布日志里看到过那条警告。","add_node_ids":["deployment-log"],"add_link_ids":["deployment-log->see-action"],"focus_node_id":"deployment-log","note_zh":"补出警告当时所在的技术记录。"}]}'
  ),
  (
    'recap-primary',
    'recap',
    'recap',
    'recap an incident timeline',
    '简要回顾并概括关键信息',
    'Leo recapped the timeline.',
    'Leo 概括回顾了时间线。',
    'Leo recapped the incident timeline for the night shift in a two-minute voice note.',
    'Leo 用一段两分钟的语音，为夜班团队概括回顾了故障事件的时间线。',
    'shift-handoff-recap',
    '{"schema_version":2,"root_action_id":"recap-action","nodes":[{"id":"recap-action","text":"recapped","kind":"action","label_zh":"简要回顾事件经过"},{"id":"leo","text":"Leo","kind":"core","label_zh":"整理事件信息的人"},{"id":"timeline","text":"the timeline","kind":"core","label_zh":"被概括的时间线"},{"id":"incident","text":"incident","kind":"modifier","label_zh":"时间线记录的是故障事件"},{"id":"night-shift","text":"the night shift","kind":"core","label_zh":"接收回顾内容的夜班团队"},{"id":"voice-note","text":"in a two-minute voice note","kind":"modifier","label_zh":"用两分钟语音传达回顾内容"}],"links":[{"id":"recap-action->leo","from":"recap-action","to":"leo","kind":"core","relation_type":"actor","label_zh":"Leo 进行了简要回顾"},{"id":"recap-action->timeline","from":"recap-action","to":"timeline","kind":"core","relation_type":"target","label_zh":"回顾内容围绕事件时间线"},{"id":"incident->timeline","from":"incident","to":"timeline","kind":"modifier","relation_type":"category","label_zh":"这条时间线属于故障事件"},{"id":"recap-action->night-shift","from":"recap-action","to":"night-shift","kind":"core","relation_type":"recipient","label_zh":"夜班团队接收了这次回顾"},{"id":"voice-note->recap-action","from":"voice-note","to":"recap-action","kind":"modifier","relation_type":"manner","label_zh":"Leo 通过两分钟语音完成概括"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Leo recapped the timeline.","sentence_zh":"Leo 概括回顾了时间线。","add_node_ids":["recap-action","leo","timeline"],"add_link_ids":["recap-action->leo","recap-action->timeline"],"focus_node_id":"recap-action","note_zh":"recap 强调抓住要点进行简短回顾。"},{"step_no":2,"label":"事件时间线","sentence_en":"Leo recapped the incident timeline.","sentence_zh":"Leo 概括回顾了故障事件的时间线。","add_node_ids":["incident"],"add_link_ids":["incident->timeline"],"focus_node_id":"incident","note_zh":"明确时间线记录的是哪类事情。"},{"step_no":3,"label":"交接对象","sentence_en":"Leo recapped the incident timeline for the night shift.","sentence_zh":"Leo 为夜班团队概括回顾了故障事件的时间线。","add_node_ids":["night-shift"],"add_link_ids":["recap-action->night-shift"],"focus_node_id":"night-shift","note_zh":"加入这段回顾内容的接收团队。"},{"step_no":4,"label":"语音形式","sentence_en":"Leo recapped the incident timeline for the night shift in a two-minute voice note.","sentence_zh":"Leo 用一段两分钟的语音，为夜班团队概括回顾了故障事件的时间线。","add_node_ids":["voice-note"],"add_link_ids":["voice-note->recap-action"],"focus_node_id":"voice-note","note_zh":"说明这次交接回顾采用的简短形式。"}]}'
  ),
  (
    'receive-primary',
    'receive',
    'receive',
    'receive a signed payload',
    '接收到传入的信息或数据',
    'The webhook received the payload.',
    'Webhook 接收到了载荷。',
    'The webhook received the billing service''s signed payload at 09:42 UTC.',
    'Webhook 在 UTC 09:42 接收到了计费服务发来的带签名载荷。',
    'webhook-payload-receipt',
    '{"schema_version":2,"root_action_id":"receive-action","nodes":[{"id":"receive-action","text":"received","kind":"action","label_zh":"接收传入数据"},{"id":"webhook","text":"The webhook","kind":"core","label_zh":"接收请求数据的网络端点"},{"id":"payload","text":"the payload","kind":"core","label_zh":"端点收到的数据内容"},{"id":"signed","text":"signed","kind":"modifier","label_zh":"载荷带有可验证签名"},{"id":"billing-owner","text":"billing service''s","kind":"modifier","label_zh":"载荷来自计费服务"},{"id":"receipt-time","text":"at 09:42 UTC","kind":"modifier","label_zh":"载荷到达的精确时间"}],"links":[{"id":"receive-action->webhook","from":"receive-action","to":"webhook","kind":"core","relation_type":"actor","label_zh":"网络端点接收了数据"},{"id":"receive-action->payload","from":"receive-action","to":"payload","kind":"core","relation_type":"target","label_zh":"收到的内容是一份载荷"},{"id":"signed->payload","from":"signed","to":"payload","kind":"modifier","relation_type":"quality","label_zh":"这份载荷包含数字签名"},{"id":"billing-owner->payload","from":"billing-owner","to":"payload","kind":"modifier","relation_type":"ownership","label_zh":"该载荷由计费服务发来"},{"id":"receipt-time->receive-action","from":"receipt-time","to":"receive-action","kind":"modifier","relation_type":"time","label_zh":"端点在 UTC 09:42 收到载荷"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The webhook received the payload.","sentence_zh":"Webhook 接收到了载荷。","add_node_ids":["receive-action","webhook","payload"],"add_link_ids":["receive-action->webhook","receive-action->payload"],"focus_node_id":"receive-action","note_zh":"建立端点收到传入数据的基本场景。"},{"step_no":2,"label":"签名载荷","sentence_en":"The webhook received the signed payload.","sentence_zh":"Webhook 接收到了带签名的载荷。","add_node_ids":["signed"],"add_link_ids":["signed->payload"],"focus_node_id":"signed","note_zh":"补充载荷可供验证的安全特征。"},{"step_no":3,"label":"数据来源","sentence_en":"The webhook received the billing service''s signed payload.","sentence_zh":"Webhook 接收到了计费服务发来的带签名载荷。","add_node_ids":["billing-owner"],"add_link_ids":["billing-owner->payload"],"focus_node_id":"billing-owner","note_zh":"指出这份签名载荷属于哪个服务。"},{"step_no":4,"label":"到达时刻","sentence_en":"The webhook received the billing service''s signed payload at 09:42 UTC.","sentence_zh":"Webhook 在 UTC 09:42 接收到了计费服务发来的带签名载荷。","add_node_ids":["receipt-time"],"add_link_ids":["receipt-time->receive-action"],"focus_node_id":"receipt-time","note_zh":"记录载荷到达端点的精确时刻。"}]}'
  ),
  (
    'reckon-primary',
    'reckon',
    'reckon',
    'reckon a fix will pass',
    '认为或估计，语气较口语化',
    'I reckon the fix will pass review.',
    '我认为这项修复会通过审查。',
    'I reckon the fix will pass review this time.',
    '我认为这项修复这次会通过审查。',
    'code-review-outlook',
    '{"schema_version":2,"root_action_id":"reckon-action","nodes":[{"id":"reckon-action","text":"reckon","kind":"action","label_zh":"作出非正式判断"},{"id":"speaker","text":"I","kind":"core","label_zh":"表达判断的人"},{"id":"pass-action","text":"will pass","kind":"action","label_zh":"预计顺利通过审查"},{"id":"fix","text":"the fix","kind":"core","label_zh":"等待审查的修复方案"},{"id":"review","text":"review","kind":"core","label_zh":"修复方案预计通过的审查"},{"id":"this-time","text":"this time","kind":"modifier","label_zh":"判断针对当前这一轮审查"}],"links":[{"id":"reckon-action->speaker","from":"reckon-action","to":"speaker","kind":"core","relation_type":"actor","label_zh":"我给出了个人判断"},{"id":"reckon-action->pass-action","from":"reckon-action","to":"pass-action","kind":"core","relation_type":"content","label_zh":"判断内容是修复方案会通过审查"},{"id":"pass-action->fix","from":"pass-action","to":"fix","kind":"core","relation_type":"actor","label_zh":"预计通过审查的是这项修复"},{"id":"pass-action->review","from":"pass-action","to":"review","kind":"core","relation_type":"target","label_zh":"修复方案要通过的是代码审查"},{"id":"this-time->pass-action","from":"this-time","to":"pass-action","kind":"modifier","relation_type":"time","label_zh":"通过审查的预期针对当前这一轮"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I reckon the fix will pass review.","sentence_zh":"我认为这项修复会通过审查。","add_node_ids":["reckon-action","speaker","pass-action","fix","review"],"add_link_ids":["reckon-action->speaker","reckon-action->pass-action","pass-action->fix","pass-action->review"],"focus_node_id":"reckon-action","note_zh":"reckon 在这里用口语语气表达个人判断。"},{"step_no":2,"label":"当前一轮","sentence_en":"I reckon the fix will pass review this time.","sentence_zh":"我认为这项修复这次会通过审查。","add_node_ids":["this-time"],"add_link_ids":["this-time->pass-action"],"focus_node_id":"this-time","note_zh":"把预测限定在当前这一次审查中。"}]}'
  ),
  (
    'recognize-primary',
    'recognize',
    'recognize',
    'recognize a QR code',
    '成功识别某个对象',
    'The scanner recognized the QR code.',
    '扫描器识别出了二维码。',
    'The scanner recognized the QR code on the visitor badge despite the dim hallway.',
    '尽管走廊光线昏暗，扫描器仍识别出了访客证件上的二维码。',
    'badge-qr-scan',
    '{"schema_version":2,"root_action_id":"recognize-action","nodes":[{"id":"recognize-action","text":"recognized","kind":"action","label_zh":"成功识别图码"},{"id":"scanner","text":"The scanner","kind":"core","label_zh":"执行图码识别的扫描器"},{"id":"qr-code","text":"the QR code","kind":"core","label_zh":"被扫描器识别的二维码"},{"id":"visitor-badge","text":"on the visitor badge","kind":"modifier","label_zh":"二维码所在的访客证件"},{"id":"dim-hallway","text":"despite the dim hallway","kind":"modifier","label_zh":"识别时现场光线昏暗"}],"links":[{"id":"recognize-action->scanner","from":"recognize-action","to":"scanner","kind":"core","relation_type":"actor","label_zh":"扫描器完成了识别"},{"id":"recognize-action->qr-code","from":"recognize-action","to":"qr-code","kind":"core","relation_type":"target","label_zh":"扫描器识别的是二维码"},{"id":"visitor-badge->qr-code","from":"visitor-badge","to":"qr-code","kind":"modifier","relation_type":"place","label_zh":"二维码印在访客证件上"},{"id":"dim-hallway->recognize-action","from":"dim-hallway","to":"recognize-action","kind":"modifier","relation_type":"condition","label_zh":"即使走廊昏暗，识别仍然成功"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The scanner recognized the QR code.","sentence_zh":"扫描器识别出了二维码。","add_node_ids":["recognize-action","scanner","qr-code"],"add_link_ids":["recognize-action->scanner","recognize-action->qr-code"],"focus_node_id":"recognize-action","note_zh":"recognize 表示系统成功判断出图码内容。"},{"step_no":2,"label":"图码位置","sentence_en":"The scanner recognized the QR code on the visitor badge.","sentence_zh":"扫描器识别出了访客证件上的二维码。","add_node_ids":["visitor-badge"],"add_link_ids":["visitor-badge->qr-code"],"focus_node_id":"visitor-badge","note_zh":"补充二维码依附的具体物件。"},{"step_no":3,"label":"昏暗条件","sentence_en":"The scanner recognized the QR code on the visitor badge despite the dim hallway.","sentence_zh":"尽管走廊光线昏暗，扫描器仍识别出了访客证件上的二维码。","add_node_ids":["dim-hallway"],"add_link_ids":["dim-hallway->recognize-action"],"focus_node_id":"dim-hallway","note_zh":"加入不利条件，突出识别依然成功。"}]}'
  ),
  (
    'recommend-primary',
    'recommend',
    'recommend',
    'recommend rotating an API key',
    '建议采取某项做法',
    'The security review recommends rotating the API key.',
    '安全审查建议更换接口密钥。',
    'The security review strongly recommends rotating the production API key immediately.',
    '安全审查强烈建议立即更换生产环境的接口密钥。',
    'security-key-rotation',
    '{"schema_version":2,"root_action_id":"recommend-action","nodes":[{"id":"recommend-action","text":"recommends","kind":"action","label_zh":"提出安全建议"},{"id":"security-review","text":"The security review","kind":"core","label_zh":"给出建议的安全审查报告"},{"id":"rotate-action","text":"rotating","kind":"action","label_zh":"更换接口密钥"},{"id":"api-key","text":"the API key","kind":"core","label_zh":"建议更换的接口密钥"},{"id":"production","text":"production","kind":"modifier","label_zh":"密钥用于生产环境"},{"id":"strongly","text":"strongly","kind":"modifier","label_zh":"审查报告明确强调该建议"},{"id":"immediately","text":"immediately","kind":"modifier","label_zh":"建议不延迟地更换密钥"}],"links":[{"id":"recommend-action->security-review","from":"recommend-action","to":"security-review","kind":"core","relation_type":"actor","label_zh":"安全审查报告给出了建议"},{"id":"recommend-action->rotate-action","from":"recommend-action","to":"rotate-action","kind":"core","relation_type":"content","label_zh":"建议内容是更换接口密钥"},{"id":"rotate-action->api-key","from":"rotate-action","to":"api-key","kind":"core","relation_type":"target","label_zh":"需要更换的是接口密钥"},{"id":"production->api-key","from":"production","to":"api-key","kind":"modifier","relation_type":"category","label_zh":"这把密钥服务于生产环境"},{"id":"strongly->recommend-action","from":"strongly","to":"recommend-action","kind":"modifier","relation_type":"degree","label_zh":"报告以强烈程度提出建议"},{"id":"immediately->rotate-action","from":"immediately","to":"rotate-action","kind":"modifier","relation_type":"time","label_zh":"密钥更换应当立即进行"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The security review recommends rotating the API key.","sentence_zh":"安全审查建议更换接口密钥。","add_node_ids":["recommend-action","security-review","rotate-action","api-key"],"add_link_ids":["recommend-action->security-review","recommend-action->rotate-action","rotate-action->api-key"],"focus_node_id":"recommend-action","note_zh":"recommend 后直接带出审查报告建议采取的做法。"},{"step_no":2,"label":"生产密钥","sentence_en":"The security review recommends rotating the production API key.","sentence_zh":"安全审查建议更换生产环境的接口密钥。","add_node_ids":["production"],"add_link_ids":["production->api-key"],"focus_node_id":"production","note_zh":"明确需要更换的是生产环境所用密钥。"},{"step_no":3,"label":"建议强度","sentence_en":"The security review strongly recommends rotating the production API key.","sentence_zh":"安全审查强烈建议更换生产环境的接口密钥。","add_node_ids":["strongly"],"add_link_ids":["strongly->recommend-action"],"focus_node_id":"strongly","note_zh":"加入审查报告对该措施的强调程度。"},{"step_no":4,"label":"执行时点","sentence_en":"The security review strongly recommends rotating the production API key immediately.","sentence_zh":"安全审查强烈建议立即更换生产环境的接口密钥。","add_node_ids":["immediately"],"add_link_ids":["immediately->rotate-action"],"focus_node_id":"immediately","note_zh":"最后说明密钥更换不应延后。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
