-- Generated verb paths batch batch-015.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'stay-primary',
    'stay',
    'stay',
    'stay online',
    '保持在线状态',
    'The engineers stayed online.',
    '工程师们保持在线。',
    'The on-call engineers stayed online after the release until the error rate returned to normal.',
    '发布后，值班工程师们一直保持在线，直到错误率恢复正常。',
    'release-monitoring',
    '{"schema_version":2,"root_action_id":"stay-online","nodes":[{"id":"stay-online","text":"stayed","kind":"action","label_zh":"发布后保持在线"},{"id":"engineers","text":"The engineers","kind":"core","label_zh":"保持在线的工程师"},{"id":"online","text":"online","kind":"core","label_zh":"工程师保持的状态"},{"id":"on-call","text":"on-call","kind":"modifier","label_zh":"说明工程师正在值班"},{"id":"after-release","text":"after the release","kind":"modifier","label_zh":"保持在线的开始时段"},{"id":"return-normal","text":"returned","kind":"action","label_zh":"错误率恢复正常"},{"id":"error-rate","text":"the error rate","kind":"core","label_zh":"恢复正常的指标"},{"id":"normal","text":"normal","kind":"core","label_zh":"错误率恢复到的水平"}],"links":[{"id":"stay-online->engineers","from":"stay-online","to":"engineers","kind":"core","relation_type":"actor","label_zh":"工程师保持在线"},{"id":"stay-online->online","from":"stay-online","to":"online","kind":"core","relation_type":"quality","label_zh":"保持的是在线状态"},{"id":"on-call->engineers","from":"on-call","to":"engineers","kind":"modifier","relation_type":"quality","label_zh":"这些工程师正在承担值班工作"},{"id":"after-release->stay-online","from":"after-release","to":"stay-online","kind":"modifier","relation_type":"time","label_zh":"在线值守发生在发布之后"},{"id":"return-normal->error-rate","from":"return-normal","to":"error-rate","kind":"core","relation_type":"actor","label_zh":"错误率发生恢复"},{"id":"return-normal->normal","from":"return-normal","to":"normal","kind":"core","relation_type":"result","label_zh":"错误率最终回到正常水平"},{"id":"return-normal->stay-online","from":"return-normal","to":"stay-online","kind":"modifier","relation_type":"time","label_zh":"错误率恢复正常时在线值守才结束"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The engineers stayed online.","sentence_zh":"工程师们保持在线。","add_node_ids":["stay-online","engineers","online"],"add_link_ids":["stay-online->engineers","stay-online->online"],"focus_node_id":"stay-online","note_zh":"先建立工程师保持在线这一核心情况。"},{"step_no":2,"label":"对象细节","sentence_en":"The on-call engineers stayed online.","sentence_zh":"值班工程师们保持在线。","add_node_ids":["on-call"],"add_link_ids":["on-call->engineers"],"focus_node_id":"on-call","note_zh":"明确保持在线的是当班人员。"},{"step_no":3,"label":"时间","sentence_en":"The on-call engineers stayed online after the release.","sentence_zh":"发布后，值班工程师们保持在线。","add_node_ids":["after-release"],"add_link_ids":["after-release->stay-online"],"focus_node_id":"after-release","note_zh":"交代在线值守从发布之后开始。"},{"step_no":4,"label":"时间","sentence_en":"The on-call engineers stayed online after the release until the error rate returned to normal.","sentence_zh":"发布后，值班工程师们一直保持在线，直到错误率恢复正常。","add_node_ids":["return-normal","error-rate","normal"],"add_link_ids":["return-normal->error-rate","return-normal->normal","return-normal->stay-online"],"focus_node_id":"return-normal","note_zh":"用指标恢复这一完整变化限定值守的结束时间。"}]}'
  ),
  (
    'steal-primary',
    'steal',
    'steal',
    'steal session cookies',
    '窃取会话 Cookie',
    'A browser extension stole session cookies.',
    '一个浏览器扩展窃取了会话 Cookie。',
    'A compromised browser extension stole session cookies from employee browsers overnight.',
    '一个被攻破的浏览器扩展在夜间从员工浏览器中窃取了会话 Cookie。',
    'malicious-extension',
    '{"schema_version":2,"root_action_id":"steal-cookies","nodes":[{"id":"steal-cookies","text":"stole","kind":"action","label_zh":"扩展窃取会话信息"},{"id":"browser-extension","text":"A browser extension","kind":"core","label_zh":"实施窃取的浏览器扩展"},{"id":"session-cookies","text":"session cookies","kind":"core","label_zh":"被窃取的会话 Cookie"},{"id":"compromised","text":"compromised","kind":"modifier","label_zh":"说明扩展已被攻破"},{"id":"from-employee-browsers","text":"from employee browsers","kind":"modifier","label_zh":"会话 Cookie 的窃取来源"},{"id":"overnight","text":"overnight","kind":"modifier","label_zh":"窃取持续的夜间时段"}],"links":[{"id":"steal-cookies->browser-extension","from":"steal-cookies","to":"browser-extension","kind":"core","relation_type":"actor","label_zh":"浏览器扩展执行了窃取"},{"id":"steal-cookies->session-cookies","from":"steal-cookies","to":"session-cookies","kind":"core","relation_type":"target","label_zh":"窃取针对会话 Cookie"},{"id":"compromised->browser-extension","from":"compromised","to":"browser-extension","kind":"modifier","relation_type":"quality","label_zh":"该扩展处于被攻破的状态"},{"id":"from-employee-browsers->steal-cookies","from":"from-employee-browsers","to":"steal-cookies","kind":"modifier","relation_type":"place","label_zh":"Cookie 是从员工浏览器中窃取的"},{"id":"overnight->steal-cookies","from":"overnight","to":"steal-cookies","kind":"modifier","relation_type":"time","label_zh":"窃取发生在夜间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A browser extension stole session cookies.","sentence_zh":"一个浏览器扩展窃取了会话 Cookie。","add_node_ids":["steal-cookies","browser-extension","session-cookies"],"add_link_ids":["steal-cookies->browser-extension","steal-cookies->session-cookies"],"focus_node_id":"steal-cookies","note_zh":"先说明扩展窃取了什么。"},{"step_no":2,"label":"对象细节","sentence_en":"A compromised browser extension stole session cookies.","sentence_zh":"一个被攻破的浏览器扩展窃取了会话 Cookie。","add_node_ids":["compromised"],"add_link_ids":["compromised->browser-extension"],"focus_node_id":"compromised","note_zh":"补充扩展存在安全问题这一关键信息。"},{"step_no":3,"label":"场景","sentence_en":"A compromised browser extension stole session cookies from employee browsers.","sentence_zh":"一个被攻破的浏览器扩展从员工浏览器中窃取了会话 Cookie。","add_node_ids":["from-employee-browsers"],"add_link_ids":["from-employee-browsers->steal-cookies"],"focus_node_id":"from-employee-browsers","note_zh":"指出被盗信息来自哪些设备。"},{"step_no":4,"label":"时间","sentence_en":"A compromised browser extension stole session cookies from employee browsers overnight.","sentence_zh":"一个被攻破的浏览器扩展在夜间从员工浏览器中窃取了会话 Cookie。","add_node_ids":["overnight"],"add_link_ids":["overnight->steal-cookies"],"focus_node_id":"overnight","note_zh":"最后标明窃取发生的时间。"}]}'
  ),
  (
    'steer-primary',
    'steer',
    'steer',
    'steer a discussion',
    '引导讨论走向',
    'The facilitator steered the discussion.',
    '主持人引导了讨论。',
    'The facilitator steered the discussion away from personal blame and toward concrete fixes during the incident review.',
    '在事故复盘期间，主持人引导讨论避开对个人的指责，转向具体的解决办法。',
    'incident-review',
    '{"schema_version":2,"root_action_id":"steer-discussion","nodes":[{"id":"steer-discussion","text":"steered","kind":"action","label_zh":"主持人引导讨论方向"},{"id":"facilitator","text":"The facilitator","kind":"core","label_zh":"负责引导讨论的人"},{"id":"discussion","text":"the discussion","kind":"core","label_zh":"被引导的讨论"},{"id":"away-from-blame","text":"away from personal blame","kind":"modifier","label_zh":"讨论需要避开的方向"},{"id":"toward-fixes","text":"toward concrete fixes","kind":"modifier","label_zh":"讨论被带向的实际方向"},{"id":"during-review","text":"during the incident review","kind":"modifier","label_zh":"引导讨论发生的会议场景"}],"links":[{"id":"steer-discussion->facilitator","from":"steer-discussion","to":"facilitator","kind":"core","relation_type":"actor","label_zh":"主持人负责调整讨论方向"},{"id":"steer-discussion->discussion","from":"steer-discussion","to":"discussion","kind":"core","relation_type":"target","label_zh":"方向调整作用于这场讨论"},{"id":"away-from-blame->steer-discussion","from":"away-from-blame","to":"steer-discussion","kind":"modifier","relation_type":"manner","label_zh":"引导时避开针对个人的指责"},{"id":"toward-fixes->steer-discussion","from":"toward-fixes","to":"steer-discussion","kind":"modifier","relation_type":"purpose","label_zh":"引导的目标是讨论具体解决办法"},{"id":"during-review->steer-discussion","from":"during-review","to":"steer-discussion","kind":"modifier","relation_type":"time","label_zh":"方向调整发生在事故复盘期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The facilitator steered the discussion.","sentence_zh":"主持人引导了讨论。","add_node_ids":["steer-discussion","facilitator","discussion"],"add_link_ids":["steer-discussion->facilitator","steer-discussion->discussion"],"focus_node_id":"steer-discussion","note_zh":"先呈现主持人主动调整讨论方向。"},{"step_no":2,"label":"方式","sentence_en":"The facilitator steered the discussion away from personal blame.","sentence_zh":"主持人引导讨论避开对个人的指责。","add_node_ids":["away-from-blame"],"add_link_ids":["away-from-blame->steer-discussion"],"focus_node_id":"away-from-blame","note_zh":"说明讨论被带离哪种无益方向。"},{"step_no":3,"label":"目的","sentence_en":"The facilitator steered the discussion away from personal blame and toward concrete fixes.","sentence_zh":"主持人引导讨论避开对个人的指责，转向具体的解决办法。","add_node_ids":["toward-fixes"],"add_link_ids":["toward-fixes->steer-discussion"],"focus_node_id":"toward-fixes","note_zh":"进一步给出主持人希望讨论到达的方向。"},{"step_no":4,"label":"场景","sentence_en":"The facilitator steered the discussion away from personal blame and toward concrete fixes during the incident review.","sentence_zh":"在事故复盘期间，主持人引导讨论避开对个人的指责，转向具体的解决办法。","add_node_ids":["during-review"],"add_link_ids":["during-review->steer-discussion"],"focus_node_id":"during-review","note_zh":"把这次方向调整放入事故复盘场景。"}]}'
  ),
  (
    'step-up-primary',
    'step-up',
    'step up',
    'step up monitoring',
    '加大监控力度',
    'The support team stepped up monitoring.',
    '支持团队加大了监控力度。',
    'The support team stepped up monitoring of the payment API after the alerting service missed two failures.',
    '告警服务漏报两次故障后，支持团队加大了对支付接口的监控力度。',
    'payment-alerting',
    '{"schema_version":2,"root_action_id":"step-up-monitoring","nodes":[{"id":"step-up-monitoring","text":"stepped up","kind":"action","label_zh":"支持团队加大监控力度"},{"id":"support-team","text":"The support team","kind":"core","label_zh":"加强监控的团队"},{"id":"monitoring","text":"monitoring","kind":"core","label_zh":"被加强的监控工作"},{"id":"of-payment-api","text":"of the payment API","kind":"modifier","label_zh":"监控覆盖的接口"},{"id":"miss-failures","text":"missed","kind":"action","label_zh":"告警服务漏报故障"},{"id":"alerting-service","text":"the alerting service","kind":"core","label_zh":"发生漏报的服务"},{"id":"two-failures","text":"two failures","kind":"core","label_zh":"未被告警捕获的两次故障"}],"links":[{"id":"step-up-monitoring->support-team","from":"step-up-monitoring","to":"support-team","kind":"core","relation_type":"actor","label_zh":"支持团队执行了加强措施"},{"id":"step-up-monitoring->monitoring","from":"step-up-monitoring","to":"monitoring","kind":"core","relation_type":"target","label_zh":"加强的是监控工作"},{"id":"of-payment-api->monitoring","from":"of-payment-api","to":"monitoring","kind":"modifier","relation_type":"scope","label_zh":"监控专门覆盖支付接口"},{"id":"miss-failures->alerting-service","from":"miss-failures","to":"alerting-service","kind":"core","relation_type":"actor","label_zh":"告警服务发生了漏报"},{"id":"miss-failures->two-failures","from":"miss-failures","to":"two-failures","kind":"core","relation_type":"target","label_zh":"漏掉的是两次故障"},{"id":"miss-failures->step-up-monitoring","from":"miss-failures","to":"step-up-monitoring","kind":"modifier","relation_type":"reason","label_zh":"两次漏报促使团队加强监控"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The support team stepped up monitoring.","sentence_zh":"支持团队加大了监控力度。","add_node_ids":["step-up-monitoring","support-team","monitoring"],"add_link_ids":["step-up-monitoring->support-team","step-up-monitoring->monitoring"],"focus_node_id":"step-up-monitoring","note_zh":"先说明团队提高了监控强度。"},{"step_no":2,"label":"范围","sentence_en":"The support team stepped up monitoring of the payment API.","sentence_zh":"支持团队加大了对支付接口的监控力度。","add_node_ids":["of-payment-api"],"add_link_ids":["of-payment-api->monitoring"],"focus_node_id":"of-payment-api","note_zh":"限定这次加强措施所覆盖的系统。"},{"step_no":3,"label":"原因","sentence_en":"The support team stepped up monitoring of the payment API after the alerting service missed two failures.","sentence_zh":"告警服务漏报两次故障后，支持团队加大了对支付接口的监控力度。","add_node_ids":["miss-failures","alerting-service","two-failures"],"add_link_ids":["miss-failures->alerting-service","miss-failures->two-failures","miss-failures->step-up-monitoring"],"focus_node_id":"miss-failures","note_zh":"用完整的漏报事件解释为何要加强监控。"}]}'
  ),
  (
    'stick-to-primary',
    'stick-to',
    'stick to',
    'stick to a checklist',
    '严格遵守清单',
    'We stuck to the rollback checklist.',
    '我们严格遵守了回滚清单。',
    'We stuck to the rollback checklist for database migrations even when the incident channel became noisy.',
    '即使事故频道变得嘈杂，我们仍严格遵守数据库迁移回滚清单。',
    'database-rollback',
    '{"schema_version":2,"root_action_id":"stick-to-checklist","nodes":[{"id":"stick-to-checklist","text":"stuck to","kind":"action","label_zh":"团队坚持按清单操作"},{"id":"we","text":"We","kind":"core","label_zh":"遵守清单的团队成员"},{"id":"rollback-checklist","text":"the rollback checklist","kind":"core","label_zh":"团队遵守的回滚清单"},{"id":"for-migrations","text":"for database migrations","kind":"modifier","label_zh":"清单适用的变更类型"},{"id":"become-noisy","text":"became","kind":"action","label_zh":"事故频道变得嘈杂"},{"id":"incident-channel","text":"the incident channel","kind":"core","label_zh":"出现干扰的沟通频道"},{"id":"noisy","text":"noisy","kind":"core","label_zh":"频道变成的混乱状态"}],"links":[{"id":"stick-to-checklist->we","from":"stick-to-checklist","to":"we","kind":"core","relation_type":"actor","label_zh":"我们坚持执行既定步骤"},{"id":"stick-to-checklist->rollback-checklist","from":"stick-to-checklist","to":"rollback-checklist","kind":"core","relation_type":"target","label_zh":"坚持遵守的是回滚清单"},{"id":"for-migrations->rollback-checklist","from":"for-migrations","to":"rollback-checklist","kind":"modifier","relation_type":"scope","label_zh":"这份清单用于数据库迁移"},{"id":"become-noisy->incident-channel","from":"become-noisy","to":"incident-channel","kind":"core","relation_type":"actor","label_zh":"事故频道出现状态变化"},{"id":"become-noisy->noisy","from":"become-noisy","to":"noisy","kind":"core","relation_type":"quality","label_zh":"频道变得嘈杂混乱"},{"id":"become-noisy->stick-to-checklist","from":"become-noisy","to":"stick-to-checklist","kind":"modifier","relation_type":"condition","label_zh":"即使频道嘈杂，团队仍然遵守清单"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We stuck to the rollback checklist.","sentence_zh":"我们严格遵守了回滚清单。","add_node_ids":["stick-to-checklist","we","rollback-checklist"],"add_link_ids":["stick-to-checklist->we","stick-to-checklist->rollback-checklist"],"focus_node_id":"stick-to-checklist","note_zh":"先表达团队没有偏离既定操作。"},{"step_no":2,"label":"范围","sentence_en":"We stuck to the rollback checklist for database migrations.","sentence_zh":"我们严格遵守了数据库迁移回滚清单。","add_node_ids":["for-migrations"],"add_link_ids":["for-migrations->rollback-checklist"],"focus_node_id":"for-migrations","note_zh":"说明这份回滚清单针对哪类工作。"},{"step_no":3,"label":"条件","sentence_en":"We stuck to the rollback checklist for database migrations even when the incident channel became noisy.","sentence_zh":"即使事故频道变得嘈杂，我们仍严格遵守数据库迁移回滚清单。","add_node_ids":["become-noisy","incident-channel","noisy"],"add_link_ids":["become-noisy->incident-channel","become-noisy->noisy","become-noisy->stick-to-checklist"],"focus_node_id":"become-noisy","note_zh":"加入干扰场景，突出团队仍未偏离流程。"}]}'
  ),
  (
    'stimulate-primary',
    'stimulate',
    'stimulate',
    'stimulate useful debate',
    '激发有价值的讨论',
    'The prototype stimulated debate.',
    '这个原型激发了讨论。',
    'The prototype stimulated useful debate among the security reviewers before the design freeze.',
    '在设计冻结之前，这个原型在安全评审人员之间激发了有价值的讨论。',
    'prototype-review',
    '{"schema_version":2,"root_action_id":"stimulate-debate","nodes":[{"id":"stimulate-debate","text":"stimulated","kind":"action","label_zh":"原型激发讨论"},{"id":"prototype","text":"The prototype","kind":"core","label_zh":"引发讨论的产品原型"},{"id":"debate","text":"debate","kind":"core","label_zh":"被激发的讨论"},{"id":"useful","text":"useful","kind":"modifier","label_zh":"说明讨论具有实际价值"},{"id":"among-reviewers","text":"among the security reviewers","kind":"modifier","label_zh":"参与讨论的评审人员"},{"id":"before-freeze","text":"before the design freeze","kind":"modifier","label_zh":"讨论发生的设计节点之前"}],"links":[{"id":"stimulate-debate->prototype","from":"stimulate-debate","to":"prototype","kind":"core","relation_type":"actor","label_zh":"产品原型促成了讨论"},{"id":"stimulate-debate->debate","from":"stimulate-debate","to":"debate","kind":"core","relation_type":"result","label_zh":"原型带来的结果是出现讨论"},{"id":"useful->debate","from":"useful","to":"debate","kind":"modifier","relation_type":"quality","label_zh":"这场讨论能帮助改进设计"},{"id":"among-reviewers->debate","from":"among-reviewers","to":"debate","kind":"modifier","relation_type":"scope","label_zh":"讨论在安全评审人员之间展开"},{"id":"before-freeze->stimulate-debate","from":"before-freeze","to":"stimulate-debate","kind":"modifier","relation_type":"time","label_zh":"讨论在设计冻结之前被激发"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The prototype stimulated debate.","sentence_zh":"这个原型激发了讨论。","add_node_ids":["stimulate-debate","prototype","debate"],"add_link_ids":["stimulate-debate->prototype","stimulate-debate->debate"],"focus_node_id":"stimulate-debate","note_zh":"先呈现原型带来讨论这一结果。"},{"step_no":2,"label":"对象细节","sentence_en":"The prototype stimulated useful debate.","sentence_zh":"这个原型激发了有价值的讨论。","add_node_ids":["useful"],"add_link_ids":["useful->debate"],"focus_node_id":"useful","note_zh":"说明讨论并非空泛争论，而有实际作用。"},{"step_no":3,"label":"范围","sentence_en":"The prototype stimulated useful debate among the security reviewers.","sentence_zh":"这个原型在安全评审人员之间激发了有价值的讨论。","add_node_ids":["among-reviewers"],"add_link_ids":["among-reviewers->debate"],"focus_node_id":"among-reviewers","note_zh":"补充讨论发生在哪一群人之间。"},{"step_no":4,"label":"时间","sentence_en":"The prototype stimulated useful debate among the security reviewers before the design freeze.","sentence_zh":"在设计冻结之前，这个原型在安全评审人员之间激发了有价值的讨论。","add_node_ids":["before-freeze"],"add_link_ids":["before-freeze->stimulate-debate"],"focus_node_id":"before-freeze","note_zh":"指出讨论及时发生在设计尚可调整的阶段。"}]}'
  ),
  (
    'stir-primary',
    'stir',
    'stir',
    'stir concern',
    '引起担忧',
    'A status update stirred concern.',
    '一则状态更新引起了担忧。',
    'A vague status update stirred concern across the remote support team before the maintenance window.',
    '维护窗口开始前，一则含糊的状态更新在远程支持团队中引起了担忧。',
    'maintenance-update',
    '{"schema_version":2,"root_action_id":"stir-concern","nodes":[{"id":"stir-concern","text":"stirred","kind":"action","label_zh":"状态更新引起担忧"},{"id":"status-update","text":"A status update","kind":"core","label_zh":"引发反应的状态更新"},{"id":"concern","text":"concern","kind":"core","label_zh":"被引起的担忧"},{"id":"vague","text":"vague","kind":"modifier","label_zh":"说明更新内容不够明确"},{"id":"across-support-team","text":"across the remote support team","kind":"modifier","label_zh":"担忧扩散到的团队范围"},{"id":"before-window","text":"before the maintenance window","kind":"modifier","label_zh":"担忧出现的维护时段之前"}],"links":[{"id":"stir-concern->status-update","from":"stir-concern","to":"status-update","kind":"core","relation_type":"actor","label_zh":"状态更新造成了情绪反应"},{"id":"stir-concern->concern","from":"stir-concern","to":"concern","kind":"core","relation_type":"result","label_zh":"更新引发的结果是担忧"},{"id":"vague->status-update","from":"vague","to":"status-update","kind":"modifier","relation_type":"quality","label_zh":"这则状态更新表达含糊"},{"id":"across-support-team->concern","from":"across-support-team","to":"concern","kind":"modifier","relation_type":"scope","label_zh":"担忧遍及整个远程支持团队"},{"id":"before-window->stir-concern","from":"before-window","to":"stir-concern","kind":"modifier","relation_type":"time","label_zh":"担忧在维护窗口开始前出现"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A status update stirred concern.","sentence_zh":"一则状态更新引起了担忧。","add_node_ids":["stir-concern","status-update","concern"],"add_link_ids":["stir-concern->status-update","stir-concern->concern"],"focus_node_id":"stir-concern","note_zh":"先说明一则更新造成了担忧。"},{"step_no":2,"label":"对象细节","sentence_en":"A vague status update stirred concern.","sentence_zh":"一则含糊的状态更新引起了担忧。","add_node_ids":["vague"],"add_link_ids":["vague->status-update"],"focus_node_id":"vague","note_zh":"补充更新表达不清这一特点。"},{"step_no":3,"label":"范围","sentence_en":"A vague status update stirred concern across the remote support team.","sentence_zh":"一则含糊的状态更新在远程支持团队中引起了担忧。","add_node_ids":["across-support-team"],"add_link_ids":["across-support-team->concern"],"focus_node_id":"across-support-team","note_zh":"展示担忧影响了整个远程团队。"},{"step_no":4,"label":"时间","sentence_en":"A vague status update stirred concern across the remote support team before the maintenance window.","sentence_zh":"维护窗口开始前，一则含糊的状态更新在远程支持团队中引起了担忧。","add_node_ids":["before-window"],"add_link_ids":["before-window->stir-concern"],"focus_node_id":"before-window","note_zh":"交代这种反应出现在维护即将开始时。"}]}'
  ),
  (
    'stock-up-primary',
    'stock-up',
    'stock up',
    'stock up on batteries',
    '提前备足电池',
    'The field office stocked up on batteries.',
    '现场办事处储备了电池。',
    'The field office stocked up on spare batteries before the storm reached the coast.',
    '风暴抵达海岸前，现场办事处储备了备用电池。',
    'storm-preparation',
    '{"schema_version":2,"root_action_id":"stock-up-batteries","nodes":[{"id":"stock-up-batteries","text":"stocked up on","kind":"action","label_zh":"办事处提前储备电池"},{"id":"field-office","text":"The field office","kind":"core","label_zh":"进行物资储备的办事处"},{"id":"batteries","text":"batteries","kind":"core","label_zh":"提前备下的物资"},{"id":"spare","text":"spare","kind":"modifier","label_zh":"说明电池用于备用"},{"id":"reach-coast","text":"reached","kind":"action","label_zh":"风暴抵达海岸"},{"id":"storm","text":"the storm","kind":"core","label_zh":"正在逼近的风暴"},{"id":"coast","text":"the coast","kind":"core","label_zh":"风暴抵达的地区"}],"links":[{"id":"stock-up-batteries->field-office","from":"stock-up-batteries","to":"field-office","kind":"core","relation_type":"actor","label_zh":"现场办事处负责提前备货"},{"id":"stock-up-batteries->batteries","from":"stock-up-batteries","to":"batteries","kind":"core","relation_type":"target","label_zh":"储备的物资是电池"},{"id":"spare->batteries","from":"spare","to":"batteries","kind":"modifier","relation_type":"purpose","label_zh":"这些电池是应急备用品"},{"id":"reach-coast->storm","from":"reach-coast","to":"storm","kind":"core","relation_type":"actor","label_zh":"风暴向海岸移动并抵达"},{"id":"reach-coast->coast","from":"reach-coast","to":"coast","kind":"core","relation_type":"target","label_zh":"风暴抵达的是海岸地区"},{"id":"reach-coast->stock-up-batteries","from":"reach-coast","to":"stock-up-batteries","kind":"modifier","relation_type":"time","label_zh":"电池储备在风暴抵达前完成"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The field office stocked up on batteries.","sentence_zh":"现场办事处储备了电池。","add_node_ids":["stock-up-batteries","field-office","batteries"],"add_link_ids":["stock-up-batteries->field-office","stock-up-batteries->batteries"],"focus_node_id":"stock-up-batteries","note_zh":"先表达办事处提前储备物资。"},{"step_no":2,"label":"对象细节","sentence_en":"The field office stocked up on spare batteries.","sentence_zh":"现场办事处储备了备用电池。","add_node_ids":["spare"],"add_link_ids":["spare->batteries"],"focus_node_id":"spare","note_zh":"明确这些电池用于应急替换。"},{"step_no":3,"label":"时间","sentence_en":"The field office stocked up on spare batteries before the storm reached the coast.","sentence_zh":"风暴抵达海岸前，现场办事处储备了备用电池。","add_node_ids":["reach-coast","storm","coast"],"add_link_ids":["reach-coast->storm","reach-coast->coast","reach-coast->stock-up-batteries"],"focus_node_id":"reach-coast","note_zh":"用风暴抵达这一事件说明备货必须提前完成。"}]}'
  ),
  (
    'store-primary',
    'store',
    'store',
    'store encrypted tokens',
    '存储加密令牌',
    'The client stores tokens.',
    '客户端存储令牌。',
    'The client stores encrypted tokens in the system keychain for seven days.',
    '客户端将加密令牌在系统钥匙串中存储七天。',
    'credential-storage',
    '{"schema_version":2,"root_action_id":"store-tokens","nodes":[{"id":"store-tokens","text":"stores","kind":"action","label_zh":"客户端保存访问令牌"},{"id":"client","text":"The client","kind":"core","label_zh":"执行令牌存储的客户端"},{"id":"tokens","text":"tokens","kind":"core","label_zh":"被保存的访问信息"},{"id":"encrypted","text":"encrypted","kind":"modifier","label_zh":"说明令牌以加密形式保存"},{"id":"in-system-keychain","text":"in the system keychain","kind":"modifier","label_zh":"令牌所在的安全存储位置"},{"id":"for-seven-days","text":"for seven days","kind":"modifier","label_zh":"令牌保留的时长"}],"links":[{"id":"store-tokens->client","from":"store-tokens","to":"client","kind":"core","relation_type":"actor","label_zh":"客户端负责保存令牌"},{"id":"store-tokens->tokens","from":"store-tokens","to":"tokens","kind":"core","relation_type":"target","label_zh":"保存的是访问令牌"},{"id":"encrypted->tokens","from":"encrypted","to":"tokens","kind":"modifier","relation_type":"quality","label_zh":"这些令牌经过加密处理"},{"id":"in-system-keychain->store-tokens","from":"in-system-keychain","to":"store-tokens","kind":"modifier","relation_type":"place","label_zh":"令牌被放入系统钥匙串"},{"id":"for-seven-days->store-tokens","from":"for-seven-days","to":"store-tokens","kind":"modifier","relation_type":"time","label_zh":"保存期限设为七天"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The client stores tokens.","sentence_zh":"客户端存储令牌。","add_node_ids":["store-tokens","client","tokens"],"add_link_ids":["store-tokens->client","store-tokens->tokens"],"focus_node_id":"store-tokens","note_zh":"先建立客户端保存令牌这一基本行为。"},{"step_no":2,"label":"对象细节","sentence_en":"The client stores encrypted tokens.","sentence_zh":"客户端存储加密令牌。","add_node_ids":["encrypted"],"add_link_ids":["encrypted->tokens"],"focus_node_id":"encrypted","note_zh":"补充令牌在保存前已经加密。"},{"step_no":3,"label":"场景","sentence_en":"The client stores encrypted tokens in the system keychain.","sentence_zh":"客户端将加密令牌存储在系统钥匙串中。","add_node_ids":["in-system-keychain"],"add_link_ids":["in-system-keychain->store-tokens"],"focus_node_id":"in-system-keychain","note_zh":"指出客户端使用的安全存储位置。"},{"step_no":4,"label":"时间","sentence_en":"The client stores encrypted tokens in the system keychain for seven days.","sentence_zh":"客户端将加密令牌在系统钥匙串中存储七天。","add_node_ids":["for-seven-days"],"add_link_ids":["for-seven-days->store-tokens"],"focus_node_id":"for-seven-days","note_zh":"最后说明令牌的保留期限。"}]}'
  ),
  (
    'stream-primary',
    'stream',
    'stream',
    'stream sensor data',
    '流式传输传感器数据',
    'The gateway streams sensor data to the dashboard.',
    '网关将传感器数据流式传输到仪表盘。',
    'The gateway streams live sensor data to the dashboard whenever a device reconnects.',
    '每当设备重新连接时，网关都会将实时传感器数据流式传输到仪表盘。',
    'device-dashboard',
    '{"schema_version":2,"root_action_id":"stream-data","nodes":[{"id":"stream-data","text":"streams","kind":"action","label_zh":"网关持续传输传感器数据"},{"id":"gateway","text":"The gateway","kind":"core","label_zh":"发送数据流的网关"},{"id":"sensor-data","text":"sensor data","kind":"core","label_zh":"被连续传输的数据"},{"id":"dashboard","text":"the dashboard","kind":"core","label_zh":"接收数据流的仪表盘"},{"id":"live","text":"live","kind":"modifier","label_zh":"说明数据是实时产生的"},{"id":"reconnect","text":"reconnects","kind":"action","label_zh":"设备重新建立连接"},{"id":"device","text":"a device","kind":"core","label_zh":"重新连接的设备"}],"links":[{"id":"stream-data->gateway","from":"stream-data","to":"gateway","kind":"core","relation_type":"actor","label_zh":"网关负责发送连续数据"},{"id":"stream-data->sensor-data","from":"stream-data","to":"sensor-data","kind":"core","relation_type":"target","label_zh":"传输内容是传感器数据"},{"id":"stream-data->dashboard","from":"stream-data","to":"dashboard","kind":"core","relation_type":"recipient","label_zh":"仪表盘接收数据流"},{"id":"live->sensor-data","from":"live","to":"sensor-data","kind":"modifier","relation_type":"quality","label_zh":"传输的是实时数据而非历史记录"},{"id":"reconnect->device","from":"reconnect","to":"device","kind":"core","relation_type":"actor","label_zh":"某台设备恢复连接"},{"id":"reconnect->stream-data","from":"reconnect","to":"stream-data","kind":"modifier","relation_type":"condition","label_zh":"每次设备重连都会触发数据传输"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The gateway streams sensor data to the dashboard.","sentence_zh":"网关将传感器数据流式传输到仪表盘。","add_node_ids":["stream-data","gateway","sensor-data","dashboard"],"add_link_ids":["stream-data->gateway","stream-data->sensor-data","stream-data->dashboard"],"focus_node_id":"stream-data","note_zh":"先交代数据从网关持续送往仪表盘。"},{"step_no":2,"label":"对象细节","sentence_en":"The gateway streams live sensor data to the dashboard.","sentence_zh":"网关将实时传感器数据流式传输到仪表盘。","add_node_ids":["live"],"add_link_ids":["live->sensor-data"],"focus_node_id":"live","note_zh":"明确仪表盘接收的是实时数据。"},{"step_no":3,"label":"条件","sentence_en":"The gateway streams live sensor data to the dashboard whenever a device reconnects.","sentence_zh":"每当设备重新连接时，网关都会将实时传感器数据流式传输到仪表盘。","add_node_ids":["reconnect","device"],"add_link_ids":["reconnect->device","reconnect->stream-data"],"focus_node_id":"reconnect","note_zh":"加入设备重连这一传输触发条件。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'streamline-primary',
    'streamline',
    'streamline',
    'streamline bug triage',
    '简化缺陷分流流程',
    'An intake form streamlined bug triage.',
    '一张信息收集表简化了缺陷分流流程。',
    'A shared intake form streamlined bug triage for the mobile team by collecting logs upfront.',
    '一张共用的信息收集表通过预先收集日志，简化了移动端团队的缺陷分流流程。',
    'bug-intake',
    '{"schema_version":2,"root_action_id":"streamline-triage","nodes":[{"id":"streamline-triage","text":"streamlined","kind":"action","label_zh":"表单提高缺陷分流效率"},{"id":"intake-form","text":"An intake form","kind":"core","label_zh":"改善流程的收集表单"},{"id":"bug-triage","text":"bug triage","kind":"core","label_zh":"被简化的缺陷分流工作"},{"id":"shared","text":"shared","kind":"modifier","label_zh":"说明团队共用同一表单"},{"id":"for-mobile-team","text":"for the mobile team","kind":"modifier","label_zh":"流程改进服务的团队"},{"id":"collect-logs","text":"collecting","kind":"action","label_zh":"表单预先收集日志"},{"id":"logs","text":"logs","kind":"core","label_zh":"表单收集的诊断资料"},{"id":"upfront","text":"upfront","kind":"modifier","label_zh":"日志在分流开始前收集"}],"links":[{"id":"streamline-triage->intake-form","from":"streamline-triage","to":"intake-form","kind":"core","relation_type":"actor","label_zh":"收集表单带来了流程改进"},{"id":"streamline-triage->bug-triage","from":"streamline-triage","to":"bug-triage","kind":"core","relation_type":"target","label_zh":"改进作用于缺陷分流流程"},{"id":"shared->intake-form","from":"shared","to":"intake-form","kind":"modifier","relation_type":"quality","label_zh":"该表单由相关人员共同使用"},{"id":"for-mobile-team->streamline-triage","from":"for-mobile-team","to":"streamline-triage","kind":"modifier","relation_type":"scope","label_zh":"效率提升针对移动端团队"},{"id":"collect-logs->intake-form","from":"collect-logs","to":"intake-form","kind":"core","relation_type":"shared_actor","label_zh":"同一张表单负责收集日志"},{"id":"collect-logs->logs","from":"collect-logs","to":"logs","kind":"core","relation_type":"target","label_zh":"预先收集的内容是日志"},{"id":"upfront->collect-logs","from":"upfront","to":"collect-logs","kind":"modifier","relation_type":"time","label_zh":"日志在正式分流前就被收集"},{"id":"collect-logs->streamline-triage","from":"collect-logs","to":"streamline-triage","kind":"modifier","relation_type":"manner","label_zh":"预先收集日志使分流流程更高效"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"An intake form streamlined bug triage.","sentence_zh":"一张信息收集表简化了缺陷分流流程。","add_node_ids":["streamline-triage","intake-form","bug-triage"],"add_link_ids":["streamline-triage->intake-form","streamline-triage->bug-triage"],"focus_node_id":"streamline-triage","note_zh":"先说明表单让缺陷分流更高效。"},{"step_no":2,"label":"对象细节","sentence_en":"A shared intake form streamlined bug triage.","sentence_zh":"一张共用的信息收集表简化了缺陷分流流程。","add_node_ids":["shared"],"add_link_ids":["shared->intake-form"],"focus_node_id":"shared","note_zh":"说明所有相关人员使用统一入口。"},{"step_no":3,"label":"范围","sentence_en":"A shared intake form streamlined bug triage for the mobile team.","sentence_zh":"一张共用的信息收集表简化了移动端团队的缺陷分流流程。","add_node_ids":["for-mobile-team"],"add_link_ids":["for-mobile-team->streamline-triage"],"focus_node_id":"for-mobile-team","note_zh":"限定这项流程改进服务于移动端团队。"},{"step_no":4,"label":"方式","sentence_en":"A shared intake form streamlined bug triage for the mobile team by collecting logs upfront.","sentence_zh":"一张共用的信息收集表通过预先收集日志，简化了移动端团队的缺陷分流流程。","add_node_ids":["collect-logs","logs","upfront"],"add_link_ids":["collect-logs->intake-form","collect-logs->logs","upfront->collect-logs","collect-logs->streamline-triage"],"focus_node_id":"collect-logs","note_zh":"用表单提前收集日志这一行为解释效率如何提升。"}]}'
  ),
  (
    'strengthen-primary',
    'strengthen',
    'strengthen',
    'strengthen team confidence',
    '增强团队信心',
    'Rollback drills strengthened the team''s confidence.',
    '回滚演练增强了团队的信心。',
    'Regular rollback drills strengthened the team''s confidence in the deployment process after two failed launches.',
    '两次发布失败后，定期进行的回滚演练增强了团队对部署流程的信心。',
    'rollback-readiness',
    '{"schema_version":2,"root_action_id":"strengthen-confidence","nodes":[{"id":"strengthen-confidence","text":"strengthened","kind":"action","label_zh":"回滚演练增强团队信心"},{"id":"rollback-drills","text":"Rollback drills","kind":"core","label_zh":"带来信心的回滚演练"},{"id":"team-confidence","text":"the team''s confidence","kind":"core","label_zh":"得到增强的团队信心"},{"id":"regular","text":"Regular","kind":"modifier","label_zh":"说明演练持续定期进行"},{"id":"in-deployment-process","text":"in the deployment process","kind":"modifier","label_zh":"团队信心所针对的流程"},{"id":"after-failed-launches","text":"after two failed launches","kind":"modifier","label_zh":"开展强化措施的背景时间"}],"links":[{"id":"strengthen-confidence->rollback-drills","from":"strengthen-confidence","to":"rollback-drills","kind":"core","relation_type":"actor","label_zh":"回滚演练促成信心提升"},{"id":"strengthen-confidence->team-confidence","from":"strengthen-confidence","to":"team-confidence","kind":"core","relation_type":"target","label_zh":"被增强的是团队信心"},{"id":"regular->rollback-drills","from":"regular","to":"rollback-drills","kind":"modifier","relation_type":"frequency","label_zh":"回滚演练按固定频率开展"},{"id":"in-deployment-process->team-confidence","from":"in-deployment-process","to":"team-confidence","kind":"modifier","relation_type":"scope","label_zh":"信心具体指向部署流程"},{"id":"after-failed-launches->strengthen-confidence","from":"after-failed-launches","to":"strengthen-confidence","kind":"modifier","relation_type":"time","label_zh":"信心提升发生在两次发布失败之后"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Rollback drills strengthened the team''s confidence.","sentence_zh":"回滚演练增强了团队的信心。","add_node_ids":["strengthen-confidence","rollback-drills","team-confidence"],"add_link_ids":["strengthen-confidence->rollback-drills","strengthen-confidence->team-confidence"],"focus_node_id":"strengthen-confidence","note_zh":"先呈现演练带来的信心提升。"},{"step_no":2,"label":"频率","sentence_en":"Regular rollback drills strengthened the team''s confidence.","sentence_zh":"定期进行的回滚演练增强了团队的信心。","add_node_ids":["regular"],"add_link_ids":["regular->rollback-drills"],"focus_node_id":"regular","note_zh":"指出信心来自持续而非一次性的演练。"},{"step_no":3,"label":"范围","sentence_en":"Regular rollback drills strengthened the team''s confidence in the deployment process.","sentence_zh":"定期进行的回滚演练增强了团队对部署流程的信心。","add_node_ids":["in-deployment-process"],"add_link_ids":["in-deployment-process->team-confidence"],"focus_node_id":"in-deployment-process","note_zh":"明确团队对哪项工作更有把握。"},{"step_no":4,"label":"时间","sentence_en":"Regular rollback drills strengthened the team''s confidence in the deployment process after two failed launches.","sentence_zh":"两次发布失败后，定期进行的回滚演练增强了团队对部署流程的信心。","add_node_ids":["after-failed-launches"],"add_link_ids":["after-failed-launches->strengthen-confidence"],"focus_node_id":"after-failed-launches","note_zh":"补充推动团队重建信心的现实背景。"}]}'
  ),
  (
    'stretch-primary',
    'stretch',
    'stretch',
    'stretch a maintenance window',
    '延长维护窗口',
    'The team stretched the maintenance window.',
    '团队延长了维护窗口。',
    'The team stretched the scheduled maintenance window by nearly two hours to finish the archive transfer.',
    '为了完成归档传输，团队将原定的维护窗口延长了将近两小时。',
    'archive-migration',
    '{"schema_version":2,"root_action_id":"stretch-window","nodes":[{"id":"stretch-window","text":"stretched","kind":"action","label_zh":"团队延长维护窗口"},{"id":"team","text":"The team","kind":"core","label_zh":"决定延长窗口的团队"},{"id":"maintenance-window","text":"the maintenance window","kind":"core","label_zh":"被延长的维护时段"},{"id":"scheduled","text":"scheduled","kind":"modifier","label_zh":"说明窗口原本已有计划"},{"id":"by-two-hours","text":"by nearly two hours","kind":"modifier","label_zh":"维护窗口增加的时长"},{"id":"finish-transfer","text":"finish","kind":"action","label_zh":"团队完成归档传输"},{"id":"archive-transfer","text":"the archive transfer","kind":"core","label_zh":"需要完成的数据传输"}],"links":[{"id":"stretch-window->team","from":"stretch-window","to":"team","kind":"core","relation_type":"actor","label_zh":"团队作出延长窗口的安排"},{"id":"stretch-window->maintenance-window","from":"stretch-window","to":"maintenance-window","kind":"core","relation_type":"target","label_zh":"延长作用于维护窗口"},{"id":"scheduled->maintenance-window","from":"scheduled","to":"maintenance-window","kind":"modifier","relation_type":"quality","label_zh":"这个维护窗口原先已经排定"},{"id":"by-two-hours->stretch-window","from":"by-two-hours","to":"stretch-window","kind":"modifier","relation_type":"degree","label_zh":"窗口被延长了将近两小时"},{"id":"finish-transfer->team","from":"finish-transfer","to":"team","kind":"core","relation_type":"shared_actor","label_zh":"同一团队需要完成传输"},{"id":"finish-transfer->archive-transfer","from":"finish-transfer","to":"archive-transfer","kind":"core","relation_type":"target","label_zh":"需要完成的是归档传输"},{"id":"finish-transfer->stretch-window","from":"finish-transfer","to":"stretch-window","kind":"modifier","relation_type":"purpose","label_zh":"延长窗口是为了完成归档传输"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team stretched the maintenance window.","sentence_zh":"团队延长了维护窗口。","add_node_ids":["stretch-window","team","maintenance-window"],"add_link_ids":["stretch-window->team","stretch-window->maintenance-window"],"focus_node_id":"stretch-window","note_zh":"先说明团队扩大了可用维护时段。"},{"step_no":2,"label":"对象细节","sentence_en":"The team stretched the scheduled maintenance window.","sentence_zh":"团队延长了原定的维护窗口。","add_node_ids":["scheduled"],"add_link_ids":["scheduled->maintenance-window"],"focus_node_id":"scheduled","note_zh":"强调被延长的是原本排定的窗口。"},{"step_no":3,"label":"程度","sentence_en":"The team stretched the scheduled maintenance window by nearly two hours.","sentence_zh":"团队将原定的维护窗口延长了将近两小时。","add_node_ids":["by-two-hours"],"add_link_ids":["by-two-hours->stretch-window"],"focus_node_id":"by-two-hours","note_zh":"量化维护窗口实际增加了多久。"},{"step_no":4,"label":"目的","sentence_en":"The team stretched the scheduled maintenance window by nearly two hours to finish the archive transfer.","sentence_zh":"为了完成归档传输，团队将原定的维护窗口延长了将近两小时。","add_node_ids":["finish-transfer","archive-transfer"],"add_link_ids":["finish-transfer->team","finish-transfer->archive-transfer","finish-transfer->stretch-window"],"focus_node_id":"finish-transfer","note_zh":"加入团队延长窗口所要完成的具体工作。"}]}'
  ),
  (
    'strike-primary',
    'strike',
    'strike',
    'strike a payment network',
    '突然袭击支付网络',
    'A cyberattack struck the payment network.',
    '一场网络攻击袭击了支付网络。',
    'A coordinated cyberattack struck the payment network without warning during the holiday rush.',
    '节日交易高峰期，一场协同网络攻击在毫无预警的情况下袭击了支付网络。',
    'network-attack',
    '{"schema_version":2,"root_action_id":"strike-network","nodes":[{"id":"strike-network","text":"struck","kind":"action","label_zh":"网络攻击袭击支付系统"},{"id":"cyberattack","text":"A cyberattack","kind":"core","label_zh":"造成冲击的网络攻击"},{"id":"payment-network","text":"the payment network","kind":"core","label_zh":"遭受袭击的支付网络"},{"id":"coordinated","text":"coordinated","kind":"modifier","label_zh":"说明攻击经过协同组织"},{"id":"without-warning","text":"without warning","kind":"modifier","label_zh":"攻击发生时没有预警"},{"id":"during-holiday-rush","text":"during the holiday rush","kind":"modifier","label_zh":"攻击发生的业务高峰期"}],"links":[{"id":"strike-network->cyberattack","from":"strike-network","to":"cyberattack","kind":"core","relation_type":"actor","label_zh":"网络攻击造成了突然冲击"},{"id":"strike-network->payment-network","from":"strike-network","to":"payment-network","kind":"core","relation_type":"target","label_zh":"攻击直接冲击支付网络"},{"id":"coordinated->cyberattack","from":"coordinated","to":"cyberattack","kind":"modifier","relation_type":"quality","label_zh":"这次攻击由多方协同实施"},{"id":"without-warning->strike-network","from":"without-warning","to":"strike-network","kind":"modifier","relation_type":"manner","label_zh":"支付网络在没有预警的情况下遇袭"},{"id":"during-holiday-rush->strike-network","from":"during-holiday-rush","to":"strike-network","kind":"modifier","relation_type":"time","label_zh":"攻击发生在节日交易高峰期"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A cyberattack struck the payment network.","sentence_zh":"一场网络攻击袭击了支付网络。","add_node_ids":["strike-network","cyberattack","payment-network"],"add_link_ids":["strike-network->cyberattack","strike-network->payment-network"],"focus_node_id":"strike-network","note_zh":"先表达支付网络遭到突然攻击。"},{"step_no":2,"label":"对象细节","sentence_en":"A coordinated cyberattack struck the payment network.","sentence_zh":"一场协同网络攻击袭击了支付网络。","add_node_ids":["coordinated"],"add_link_ids":["coordinated->cyberattack"],"focus_node_id":"coordinated","note_zh":"补充这次攻击具有组织性。"},{"step_no":3,"label":"方式","sentence_en":"A coordinated cyberattack struck the payment network without warning.","sentence_zh":"一场协同网络攻击在毫无预警的情况下袭击了支付网络。","add_node_ids":["without-warning"],"add_link_ids":["without-warning->strike-network"],"focus_node_id":"without-warning","note_zh":"突出攻击来得突然，系统没有提前收到信号。"},{"step_no":4,"label":"时间","sentence_en":"A coordinated cyberattack struck the payment network without warning during the holiday rush.","sentence_zh":"节日交易高峰期，一场协同网络攻击在毫无预警的情况下袭击了支付网络。","add_node_ids":["during-holiday-rush"],"add_link_ids":["during-holiday-rush->strike-network"],"focus_node_id":"during-holiday-rush","note_zh":"说明攻击发生在业务压力最大的时段。"}]}'
  ),
  (
    'strip-primary',
    'strip',
    'strip',
    'strip sensitive headers',
    '剥离敏感请求头',
    'The sanitizer strips headers.',
    '清理器会移除请求头。',
    'The sanitizer strips sensitive headers from outgoing requests before forwarding the cleaned requests.',
    '清理器会先从外发请求中移除敏感请求头，再转发清理后的请求。',
    'request-sanitization',
    '{"schema_version":2,"root_action_id":"strip-headers","nodes":[{"id":"strip-headers","text":"strips","kind":"action","label_zh":"清理器移除请求头"},{"id":"sanitizer","text":"The sanitizer","kind":"core","label_zh":"负责移除信息的清理器"},{"id":"headers","text":"headers","kind":"core","label_zh":"被剥离的请求头"},{"id":"sensitive","text":"sensitive","kind":"modifier","label_zh":"说明请求头含有敏感信息"},{"id":"from-outgoing-requests","text":"from outgoing requests","kind":"modifier","label_zh":"请求头被移除的来源"},{"id":"forward-requests","text":"forwarding","kind":"action","label_zh":"清理器转发处理后的请求"},{"id":"cleaned-requests","text":"the cleaned requests","kind":"core","label_zh":"完成清理后被转发的请求"}],"links":[{"id":"strip-headers->sanitizer","from":"strip-headers","to":"sanitizer","kind":"core","relation_type":"actor","label_zh":"清理器执行剥离操作"},{"id":"strip-headers->headers","from":"strip-headers","to":"headers","kind":"core","relation_type":"target","label_zh":"剥离针对请求头"},{"id":"sensitive->headers","from":"sensitive","to":"headers","kind":"modifier","relation_type":"quality","label_zh":"这些请求头包含不应外发的信息"},{"id":"from-outgoing-requests->strip-headers","from":"from-outgoing-requests","to":"strip-headers","kind":"modifier","relation_type":"place","label_zh":"请求头从即将发出的请求中移除"},{"id":"forward-requests->sanitizer","from":"forward-requests","to":"sanitizer","kind":"core","relation_type":"shared_actor","label_zh":"同一个清理器随后转发请求"},{"id":"forward-requests->cleaned-requests","from":"forward-requests","to":"cleaned-requests","kind":"core","relation_type":"target","label_zh":"转发的是已经清理的请求"},{"id":"forward-requests->strip-headers","from":"forward-requests","to":"strip-headers","kind":"modifier","relation_type":"sequence","label_zh":"敏感请求头在请求转发前被移除"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The sanitizer strips headers.","sentence_zh":"清理器会移除请求头。","add_node_ids":["strip-headers","sanitizer","headers"],"add_link_ids":["strip-headers->sanitizer","strip-headers->headers"],"focus_node_id":"strip-headers","note_zh":"先建立清理器移除请求头的核心操作。"},{"step_no":2,"label":"对象细节","sentence_en":"The sanitizer strips sensitive headers.","sentence_zh":"清理器会移除敏感请求头。","add_node_ids":["sensitive"],"add_link_ids":["sensitive->headers"],"focus_node_id":"sensitive","note_zh":"明确只有包含敏感信息的请求头需要剥离。"},{"step_no":3,"label":"场景","sentence_en":"The sanitizer strips sensitive headers from outgoing requests.","sentence_zh":"清理器会从外发请求中移除敏感请求头。","add_node_ids":["from-outgoing-requests"],"add_link_ids":["from-outgoing-requests->strip-headers"],"focus_node_id":"from-outgoing-requests","note_zh":"指出剥离操作针对即将发出的请求。"},{"step_no":4,"label":"时间","sentence_en":"The sanitizer strips sensitive headers from outgoing requests before forwarding the cleaned requests.","sentence_zh":"清理器会先从外发请求中移除敏感请求头，再转发清理后的请求。","add_node_ids":["forward-requests","cleaned-requests"],"add_link_ids":["forward-requests->sanitizer","forward-requests->cleaned-requests","forward-requests->strip-headers"],"focus_node_id":"forward-requests","note_zh":"通过后续转发行为明确两个处理步骤的先后顺序。"}]}'
  ),
  (
    'strive-primary',
    'strive',
    'strive',
    'strive to keep deploys reversible',
    '努力保持部署可回滚',
    'The platform team strives to keep deploys reversible.',
    '平台团队努力保持部署可回滚。',
    'The platform team strives to keep production deploys reversible even under tight deadlines.',
    '即使期限紧迫，平台团队仍努力保持生产环境部署可回滚。',
    'deployment-safety',
    '{"schema_version":2,"root_action_id":"strive","nodes":[{"id":"strive","text":"strives","kind":"action","label_zh":"平台团队持续努力"},{"id":"platform-team","text":"The platform team","kind":"core","label_zh":"为部署安全努力的团队"},{"id":"keep-reversible","text":"keep","kind":"action","label_zh":"团队保持部署可回滚"},{"id":"deploys","text":"deploys","kind":"core","label_zh":"需要保持可回滚的部署"},{"id":"reversible","text":"reversible","kind":"core","label_zh":"部署需要维持的状态"},{"id":"production","text":"production","kind":"modifier","label_zh":"说明这些部署进入生产环境"},{"id":"under-deadlines","text":"even under tight deadlines","kind":"modifier","label_zh":"团队仍要努力的压力条件"}],"links":[{"id":"strive->platform-team","from":"strive","to":"platform-team","kind":"core","relation_type":"actor","label_zh":"平台团队投入持续努力"},{"id":"strive->keep-reversible","from":"strive","to":"keep-reversible","kind":"core","relation_type":"nested_action","label_zh":"努力的具体内容是维持可回滚性"},{"id":"keep-reversible->platform-team","from":"keep-reversible","to":"platform-team","kind":"core","relation_type":"shared_actor","label_zh":"同一平台团队负责保持部署状态"},{"id":"keep-reversible->deploys","from":"keep-reversible","to":"deploys","kind":"core","relation_type":"target","label_zh":"需要维持状态的是部署"},{"id":"keep-reversible->reversible","from":"keep-reversible","to":"reversible","kind":"core","relation_type":"quality","label_zh":"部署被保持在可回滚状态"},{"id":"production->deploys","from":"production","to":"deploys","kind":"modifier","relation_type":"category","label_zh":"这些部署属于生产环境变更"},{"id":"under-deadlines->strive","from":"under-deadlines","to":"strive","kind":"modifier","relation_type":"condition","label_zh":"即使期限紧迫，团队仍坚持这一目标"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The platform team strives to keep deploys reversible.","sentence_zh":"平台团队努力保持部署可回滚。","add_node_ids":["strive","platform-team","keep-reversible","deploys","reversible"],"add_link_ids":["strive->platform-team","strive->keep-reversible","keep-reversible->platform-team","keep-reversible->deploys","keep-reversible->reversible"],"focus_node_id":"strive","note_zh":"先完整呈现团队努力实现的部署安全目标。"},{"step_no":2,"label":"范围","sentence_en":"The platform team strives to keep production deploys reversible.","sentence_zh":"平台团队努力保持生产环境部署可回滚。","add_node_ids":["production"],"add_link_ids":["production->deploys"],"focus_node_id":"production","note_zh":"明确可回滚要求适用于生产环境部署。"},{"step_no":3,"label":"条件","sentence_en":"The platform team strives to keep production deploys reversible even under tight deadlines.","sentence_zh":"即使期限紧迫，平台团队仍努力保持生产环境部署可回滚。","add_node_ids":["under-deadlines"],"add_link_ids":["under-deadlines->strive"],"focus_node_id":"under-deadlines","note_zh":"加入时间压力，突出团队仍持续追求这一目标。"}]}'
  ),
  (
    'struggle-primary',
    'struggle',
    'struggle',
    'struggle to reproduce a bug',
    '艰难尝试复现缺陷',
    'Contributors struggle to reproduce the race condition.',
    '贡献者们很难复现这个竞态条件。',
    'New contributors struggle to reproduce the race condition on local machines without production data.',
    '在缺少生产数据的情况下，新贡献者们很难在本地机器上复现这个竞态条件。',
    'race-condition-debugging',
    '{"schema_version":2,"root_action_id":"struggle","nodes":[{"id":"struggle","text":"struggle","kind":"action","label_zh":"贡献者难以完成复现"},{"id":"contributors","text":"Contributors","kind":"core","label_zh":"尝试复现问题的贡献者"},{"id":"reproduce-condition","text":"reproduce","kind":"action","label_zh":"贡献者复现竞态问题"},{"id":"race-condition","text":"the race condition","kind":"core","label_zh":"需要复现的竞态条件"},{"id":"new","text":"New","kind":"modifier","label_zh":"说明贡献者刚加入项目"},{"id":"on-local-machines","text":"on local machines","kind":"modifier","label_zh":"尝试复现问题的设备环境"},{"id":"without-production-data","text":"without production data","kind":"modifier","label_zh":"复现时缺少的关键资料"}],"links":[{"id":"struggle->contributors","from":"struggle","to":"contributors","kind":"core","relation_type":"actor","label_zh":"贡献者在复现工作中遇到困难"},{"id":"struggle->reproduce-condition","from":"struggle","to":"reproduce-condition","kind":"core","relation_type":"nested_action","label_zh":"困难集中在复现竞态条件"},{"id":"reproduce-condition->contributors","from":"reproduce-condition","to":"contributors","kind":"core","relation_type":"shared_actor","label_zh":"这些贡献者亲自尝试复现"},{"id":"reproduce-condition->race-condition","from":"reproduce-condition","to":"race-condition","kind":"core","relation_type":"target","label_zh":"尝试复现的是竞态条件"},{"id":"new->contributors","from":"new","to":"contributors","kind":"modifier","relation_type":"quality","label_zh":"这些贡献者对项目还不熟悉"},{"id":"on-local-machines->reproduce-condition","from":"on-local-machines","to":"reproduce-condition","kind":"modifier","relation_type":"place","label_zh":"复现尝试发生在本地机器上"},{"id":"without-production-data->reproduce-condition","from":"without-production-data","to":"reproduce-condition","kind":"modifier","relation_type":"condition","label_zh":"缺少生产数据使复现更加困难"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Contributors struggle to reproduce the race condition.","sentence_zh":"贡献者们很难复现这个竞态条件。","add_node_ids":["struggle","contributors","reproduce-condition","race-condition"],"add_link_ids":["struggle->contributors","struggle->reproduce-condition","reproduce-condition->contributors","reproduce-condition->race-condition"],"focus_node_id":"struggle","note_zh":"先说明贡献者在复现特定问题时遇到困难。"},{"step_no":2,"label":"对象细节","sentence_en":"New contributors struggle to reproduce the race condition.","sentence_zh":"新贡献者们很难复现这个竞态条件。","add_node_ids":["new"],"add_link_ids":["new->contributors"],"focus_node_id":"new","note_zh":"指出困难主要出现在刚加入项目的人身上。"},{"step_no":3,"label":"场景","sentence_en":"New contributors struggle to reproduce the race condition on local machines.","sentence_zh":"新贡献者们很难在本地机器上复现这个竞态条件。","add_node_ids":["on-local-machines"],"add_link_ids":["on-local-machines->reproduce-condition"],"focus_node_id":"on-local-machines","note_zh":"交代复现尝试所在的运行环境。"},{"step_no":4,"label":"条件","sentence_en":"New contributors struggle to reproduce the race condition on local machines without production data.","sentence_zh":"在缺少生产数据的情况下，新贡献者们很难在本地机器上复现这个竞态条件。","add_node_ids":["without-production-data"],"add_link_ids":["without-production-data->reproduce-condition"],"focus_node_id":"without-production-data","note_zh":"补充导致本地复现困难的资料限制。"}]}'
  ),
  (
    'stub-primary',
    'stub',
    'stub',
    'stub a payment gateway',
    '为支付网关创建桩实现',
    'The test harness stubs the payment gateway.',
    '测试工具为支付网关创建桩实现。',
    'The test harness stubs the payment gateway with fixed responses during local runs.',
    '本地运行测试时，测试工具用固定响应为支付网关创建桩实现。',
    'local-payment-tests',
    '{"schema_version":2,"root_action_id":"stub-gateway","nodes":[{"id":"stub-gateway","text":"stubs","kind":"action","label_zh":"测试工具为网关提供桩实现"},{"id":"test-harness","text":"The test harness","kind":"core","label_zh":"创建桩行为的测试工具"},{"id":"payment-gateway","text":"the payment gateway","kind":"core","label_zh":"被替代为桩实现的外部服务"},{"id":"with-fixed-responses","text":"with fixed responses","kind":"modifier","label_zh":"桩实现返回的固定内容"},{"id":"during-local-runs","text":"during local runs","kind":"modifier","label_zh":"使用桩实现的测试场景"}],"links":[{"id":"stub-gateway->test-harness","from":"stub-gateway","to":"test-harness","kind":"core","relation_type":"actor","label_zh":"测试工具负责模拟外部服务"},{"id":"stub-gateway->payment-gateway","from":"stub-gateway","to":"payment-gateway","kind":"core","relation_type":"target","label_zh":"被模拟的是支付网关"},{"id":"with-fixed-responses->stub-gateway","from":"with-fixed-responses","to":"stub-gateway","kind":"modifier","relation_type":"manner","label_zh":"网关通过固定响应被模拟"},{"id":"during-local-runs->stub-gateway","from":"during-local-runs","to":"stub-gateway","kind":"modifier","relation_type":"time","label_zh":"桩实现仅在本地运行测试时使用"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The test harness stubs the payment gateway.","sentence_zh":"测试工具为支付网关创建桩实现。","add_node_ids":["stub-gateway","test-harness","payment-gateway"],"add_link_ids":["stub-gateway->test-harness","stub-gateway->payment-gateway"],"focus_node_id":"stub-gateway","note_zh":"先说明测试工具用桩实现替代支付网关。"},{"step_no":2,"label":"方式","sentence_en":"The test harness stubs the payment gateway with fixed responses.","sentence_zh":"测试工具用固定响应为支付网关创建桩实现。","add_node_ids":["with-fixed-responses"],"add_link_ids":["with-fixed-responses->stub-gateway"],"focus_node_id":"with-fixed-responses","note_zh":"说明这个桩实现如何模拟网关行为。"},{"step_no":3,"label":"场景","sentence_en":"The test harness stubs the payment gateway with fixed responses during local runs.","sentence_zh":"本地运行测试时，测试工具用固定响应为支付网关创建桩实现。","add_node_ids":["during-local-runs"],"add_link_ids":["during-local-runs->stub-gateway"],"focus_node_id":"during-local-runs","note_zh":"限定桩实现用于无需连接真实网关的本地测试。"}]}'
  ),
  (
    'study-primary',
    'study',
    'study',
    'study query traces',
    '仔细研究查询跟踪记录',
    'The database team studied the traces.',
    '数据库团队研究了这些跟踪记录。',
    'The database team studied the slow-query traces before changing the index strategy.',
    '数据库团队先研究慢查询跟踪记录，再调整索引策略。',
    'database-tuning',
    '{"schema_version":2,"root_action_id":"study-traces","nodes":[{"id":"study-traces","text":"studied","kind":"action","label_zh":"数据库团队研究跟踪记录"},{"id":"database-team","text":"The database team","kind":"core","label_zh":"分析性能问题的团队"},{"id":"traces","text":"the traces","kind":"core","label_zh":"团队研究的跟踪记录"},{"id":"slow-query","text":"slow-query","kind":"modifier","label_zh":"说明记录来自慢查询"},{"id":"change-strategy","text":"changing","kind":"action","label_zh":"团队调整索引策略"},{"id":"index-strategy","text":"the index strategy","kind":"core","label_zh":"团队准备调整的索引方案"}],"links":[{"id":"study-traces->database-team","from":"study-traces","to":"database-team","kind":"core","relation_type":"actor","label_zh":"数据库团队执行分析研究"},{"id":"study-traces->traces","from":"study-traces","to":"traces","kind":"core","relation_type":"target","label_zh":"研究针对查询跟踪记录"},{"id":"slow-query->traces","from":"slow-query","to":"traces","kind":"modifier","relation_type":"category","label_zh":"这些记录专门反映慢查询"},{"id":"change-strategy->database-team","from":"change-strategy","to":"database-team","kind":"core","relation_type":"shared_actor","label_zh":"同一数据库团队随后调整方案"},{"id":"change-strategy->index-strategy","from":"change-strategy","to":"index-strategy","kind":"core","relation_type":"target","label_zh":"准备调整的是索引策略"},{"id":"change-strategy->study-traces","from":"change-strategy","to":"study-traces","kind":"modifier","relation_type":"sequence","label_zh":"团队先研究记录，再修改索引策略"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The database team studied the traces.","sentence_zh":"数据库团队研究了这些跟踪记录。","add_node_ids":["study-traces","database-team","traces"],"add_link_ids":["study-traces->database-team","study-traces->traces"],"focus_node_id":"study-traces","note_zh":"先说明团队仔细分析已有记录。"},{"step_no":2,"label":"对象细节","sentence_en":"The database team studied the slow-query traces.","sentence_zh":"数据库团队研究了慢查询跟踪记录。","add_node_ids":["slow-query"],"add_link_ids":["slow-query->traces"],"focus_node_id":"slow-query","note_zh":"明确团队关注的是查询延迟资料。"},{"step_no":3,"label":"时间","sentence_en":"The database team studied the slow-query traces before changing the index strategy.","sentence_zh":"数据库团队先研究慢查询跟踪记录，再调整索引策略。","add_node_ids":["change-strategy","index-strategy"],"add_link_ids":["change-strategy->database-team","change-strategy->index-strategy","change-strategy->study-traces"],"focus_node_id":"change-strategy","note_zh":"加入后续调整行为，体现分析先于决策。"}]}'
  ),
  (
    'stuff-primary',
    'stuff',
    'stuff',
    'stuff files into an archive',
    '把文件塞进一个归档包',
    'The script stuffed diagnostic files into a single archive.',
    '脚本把诊断文件塞进了一个归档包。',
    'The script stuffed diagnostic files from three test runs into a single archive to simplify the upload.',
    '为了简化上传，脚本把三次测试运行产生的诊断文件塞进了一个归档包。',
    'diagnostic-bundling',
    '{"schema_version":2,"root_action_id":"stuff-files","nodes":[{"id":"stuff-files","text":"stuffed","kind":"action","label_zh":"脚本把诊断文件集中塞入归档"},{"id":"script","text":"The script","kind":"core","label_zh":"执行文件打包的脚本"},{"id":"diagnostic-files","text":"diagnostic files","kind":"core","label_zh":"被塞入归档的诊断文件"},{"id":"single-archive","text":"a single archive","kind":"core","label_zh":"集中容纳文件的归档包"},{"id":"from-test-runs","text":"from three test runs","kind":"modifier","label_zh":"诊断文件产生的测试批次"},{"id":"simplify-upload","text":"simplify","kind":"action","label_zh":"脚本让上传过程更简单"},{"id":"upload","text":"the upload","kind":"core","label_zh":"需要简化的上传工作"}],"links":[{"id":"stuff-files->script","from":"stuff-files","to":"script","kind":"core","relation_type":"actor","label_zh":"脚本执行文件集中操作"},{"id":"stuff-files->diagnostic-files","from":"stuff-files","to":"diagnostic-files","kind":"core","relation_type":"target","label_zh":"被集中处理的是诊断文件"},{"id":"stuff-files->single-archive","from":"stuff-files","to":"single-archive","kind":"core","relation_type":"recipient","label_zh":"所有文件被塞进同一个归档包"},{"id":"from-test-runs->diagnostic-files","from":"from-test-runs","to":"diagnostic-files","kind":"modifier","relation_type":"ownership","label_zh":"这些文件来自三次测试运行"},{"id":"simplify-upload->script","from":"simplify-upload","to":"script","kind":"core","relation_type":"shared_actor","label_zh":"同一脚本通过打包降低上传复杂度"},{"id":"simplify-upload->upload","from":"simplify-upload","to":"upload","kind":"core","relation_type":"target","label_zh":"需要简化的是上传过程"},{"id":"simplify-upload->stuff-files","from":"simplify-upload","to":"stuff-files","kind":"modifier","relation_type":"purpose","label_zh":"把文件集中归档是为了方便上传"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The script stuffed diagnostic files into a single archive.","sentence_zh":"脚本把诊断文件塞进了一个归档包。","add_node_ids":["stuff-files","script","diagnostic-files","single-archive"],"add_link_ids":["stuff-files->script","stuff-files->diagnostic-files","stuff-files->single-archive"],"focus_node_id":"stuff-files","note_zh":"先说明脚本把多份文件集中放进一个归档包。"},{"step_no":2,"label":"对象细节","sentence_en":"The script stuffed diagnostic files from three test runs into a single archive.","sentence_zh":"脚本把三次测试运行产生的诊断文件塞进了一个归档包。","add_node_ids":["from-test-runs"],"add_link_ids":["from-test-runs->diagnostic-files"],"focus_node_id":"from-test-runs","note_zh":"补充这些诊断文件来自哪些运行批次。"},{"step_no":3,"label":"目的","sentence_en":"The script stuffed diagnostic files from three test runs into a single archive to simplify the upload.","sentence_zh":"为了简化上传，脚本把三次测试运行产生的诊断文件塞进了一个归档包。","add_node_ids":["simplify-upload","upload"],"add_link_ids":["simplify-upload->script","simplify-upload->upload","simplify-upload->stuff-files"],"focus_node_id":"simplify-upload","note_zh":"说明集中归档这些文件所要解决的实际问题。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
