-- Generated verb paths batch batch-003.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'tag-primary',
    'tag',
    'tag',
    'tag flaky tests',
    '给内容打标签',
    'Maya tagged the tests.',
    'Maya给这些测试打了标签。',
    'Maya tagged the flaky tests in the CI dashboard.',
    'Maya在持续集成面板中给这些偶发失败的测试打了标签。',
    'ci-dashboard',
    '{"schema_version":2,"root_action_id":"tag-action","nodes":[{"id":"tag-action","text":"tagged","kind":"action","label_zh":"给测试添加标记"},{"id":"tag-maya","text":"Maya","kind":"core","label_zh":"执行标记的工程师"},{"id":"tag-tests","text":"the tests","kind":"core","label_zh":"被标记的测试"},{"id":"tag-flaky","text":"flaky","kind":"modifier","label_zh":"说明测试偶发失败"},{"id":"tag-dashboard","text":"in the CI dashboard","kind":"modifier","label_zh":"添加标签所在的界面"}],"links":[{"id":"tag-action->tag-maya","from":"tag-action","to":"tag-maya","kind":"core","relation_type":"actor","label_zh":"Maya执行了标记操作"},{"id":"tag-action->tag-tests","from":"tag-action","to":"tag-tests","kind":"core","relation_type":"target","label_zh":"标签加在这些测试上"},{"id":"tag-flaky->tag-tests","from":"tag-flaky","to":"tag-tests","kind":"modifier","relation_type":"quality","label_zh":"这些测试具有偶发失败的特点"},{"id":"tag-dashboard->tag-action","from":"tag-dashboard","to":"tag-action","kind":"modifier","relation_type":"place","label_zh":"标记操作发生在持续集成面板中"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Maya tagged the tests.","sentence_zh":"Maya给这些测试打了标签。","add_node_ids":["tag-action","tag-maya","tag-tests"],"add_link_ids":["tag-action->tag-maya","tag-action->tag-tests"],"focus_node_id":"tag-action","note_zh":"先交代执行标记的人和对象。"},{"step_no":2,"label":"对象细节","sentence_en":"Maya tagged the flaky tests.","sentence_zh":"Maya给这些偶发失败的测试打了标签。","add_node_ids":["tag-flaky"],"add_link_ids":["tag-flaky->tag-tests"],"focus_node_id":"tag-flaky","note_zh":"进一步指出被标记的是哪类测试。"},{"step_no":3,"label":"场景","sentence_en":"Maya tagged the flaky tests in the CI dashboard.","sentence_zh":"Maya在持续集成面板中给这些偶发失败的测试打了标签。","add_node_ids":["tag-dashboard"],"add_link_ids":["tag-dashboard->tag-action"],"focus_node_id":"tag-dashboard","note_zh":"补充实际添加标签的操作界面。"}]}'
  ),
  (
    'tailor-primary',
    'tailor',
    'tailor',
    'tailor a tutorial',
    '根据特定人群定制',
    'We tailored the tutorial for remote interns.',
    '我们为远程实习生定制了这份教程。',
    'We carefully tailored the tutorial for remote interns during onboarding.',
    '入职培训期间，我们仔细地为远程实习生定制了这份教程。',
    'intern-onboarding',
    '{"schema_version":2,"root_action_id":"tailor-action","nodes":[{"id":"tailor-action","text":"tailored","kind":"action","label_zh":"调整教程以适合特定人群"},{"id":"tailor-team","text":"We","kind":"core","label_zh":"负责调整教程的团队"},{"id":"tailor-tutorial","text":"the tutorial","kind":"core","label_zh":"接受定制的教程"},{"id":"tailor-interns","text":"remote interns","kind":"core","label_zh":"教程所服务的远程实习生"},{"id":"tailor-carefully","text":"carefully","kind":"modifier","label_zh":"说明调整过程很审慎"},{"id":"tailor-onboarding","text":"during onboarding","kind":"modifier","label_zh":"教程定制所处的入职阶段"}],"links":[{"id":"tailor-action->tailor-team","from":"tailor-action","to":"tailor-team","kind":"core","relation_type":"actor","label_zh":"团队负责定制教程"},{"id":"tailor-action->tailor-tutorial","from":"tailor-action","to":"tailor-tutorial","kind":"core","relation_type":"target","label_zh":"教程是调整的对象"},{"id":"tailor-action->tailor-interns","from":"tailor-action","to":"tailor-interns","kind":"core","relation_type":"recipient","label_zh":"定制后的教程面向远程实习生"},{"id":"tailor-carefully->tailor-action","from":"tailor-carefully","to":"tailor-action","kind":"modifier","relation_type":"manner","label_zh":"团队以审慎方式进行调整"},{"id":"tailor-onboarding->tailor-action","from":"tailor-onboarding","to":"tailor-action","kind":"modifier","relation_type":"time","label_zh":"调整发生在入职培训期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We tailored the tutorial for remote interns.","sentence_zh":"我们为远程实习生定制了这份教程。","add_node_ids":["tailor-action","tailor-team","tailor-tutorial","tailor-interns"],"add_link_ids":["tailor-action->tailor-team","tailor-action->tailor-tutorial","tailor-action->tailor-interns"],"focus_node_id":"tailor-action","note_zh":"主干同时说明定制内容及其适用人群。"},{"step_no":2,"label":"方式","sentence_en":"We carefully tailored the tutorial for remote interns.","sentence_zh":"我们仔细地为远程实习生定制了这份教程。","add_node_ids":["tailor-carefully"],"add_link_ids":["tailor-carefully->tailor-action"],"focus_node_id":"tailor-carefully","note_zh":"加入团队调整教程时采用的态度。"},{"step_no":3,"label":"时间","sentence_en":"We carefully tailored the tutorial for remote interns during onboarding.","sentence_zh":"入职培训期间，我们仔细地为远程实习生定制了这份教程。","add_node_ids":["tailor-onboarding"],"add_link_ids":["tailor-onboarding->tailor-action"],"focus_node_id":"tailor-onboarding","note_zh":"最后明确这项工作的培训阶段。"}]}'
  ),
  (
    'take-primary',
    'take',
    'take',
    'take three hours',
    '花费一段时间',
    'The migration took three hours.',
    '这次迁移花了三个小时。',
    'The staging migration took only three hours.',
    '这次预发布环境迁移只花了三个小时。',
    'database-migration',
    '{"schema_version":2,"root_action_id":"take-action","nodes":[{"id":"take-action","text":"took","kind":"action","label_zh":"表示迁移耗费时间"},{"id":"take-migration","text":"The migration","kind":"core","label_zh":"需要耗时的迁移过程"},{"id":"take-hours","text":"three hours","kind":"core","label_zh":"迁移所花的时长"},{"id":"take-staging","text":"staging","kind":"modifier","label_zh":"限定为预发布环境的迁移"},{"id":"take-only","text":"only","kind":"modifier","label_zh":"强调三小时比预期短"}],"links":[{"id":"take-action->take-migration","from":"take-action","to":"take-migration","kind":"core","relation_type":"actor","label_zh":"迁移过程产生了时间消耗"},{"id":"take-action->take-hours","from":"take-action","to":"take-hours","kind":"core","relation_type":"content","label_zh":"耗费的具体时长是三小时"},{"id":"take-staging->take-migration","from":"take-staging","to":"take-migration","kind":"modifier","relation_type":"place","label_zh":"该迁移针对预发布环境"},{"id":"take-only->take-hours","from":"take-only","to":"take-hours","kind":"modifier","relation_type":"degree","label_zh":"三小时被强调为较短的用时"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The migration took three hours.","sentence_zh":"这次迁移花了三个小时。","add_node_ids":["take-action","take-migration","take-hours"],"add_link_ids":["take-action->take-migration","take-action->take-hours"],"focus_node_id":"take-action","note_zh":"直接给出过程及其耗时。"},{"step_no":2,"label":"场景","sentence_en":"The staging migration took three hours.","sentence_zh":"这次预发布环境迁移花了三个小时。","add_node_ids":["take-staging"],"add_link_ids":["take-staging->take-migration"],"focus_node_id":"take-staging","note_zh":"限定迁移运行的环境。"},{"step_no":3,"label":"程度","sentence_en":"The staging migration took only three hours.","sentence_zh":"这次预发布环境迁移只花了三个小时。","add_node_ids":["take-only"],"add_link_ids":["take-only->take-hours"],"focus_node_id":"take-only","note_zh":"用only突出实际耗时不长。"}]}'
  ),
  (
    'take-apart-primary',
    'take-apart',
    'take apart',
    'take a router apart',
    '把设备拆开',
    'Nina took apart the router.',
    'Nina把路由器拆开了。',
    'Nina took apart the old router on the repair bench.',
    'Nina在维修台上把那台旧路由器拆开了。',
    'hardware-repair',
    '{"schema_version":2,"root_action_id":"take-apart-action","nodes":[{"id":"take-apart-action","text":"took apart","kind":"action","label_zh":"拆解路由器"},{"id":"take-apart-nina","text":"Nina","kind":"core","label_zh":"动手拆设备的人"},{"id":"take-apart-router","text":"the router","kind":"core","label_zh":"被拆开的路由器"},{"id":"take-apart-old","text":"old","kind":"modifier","label_zh":"说明路由器已经老旧"},{"id":"take-apart-bench","text":"on the repair bench","kind":"modifier","label_zh":"拆解设备使用的工作台"}],"links":[{"id":"take-apart-action->take-apart-nina","from":"take-apart-action","to":"take-apart-nina","kind":"core","relation_type":"actor","label_zh":"Nina执行拆解"},{"id":"take-apart-action->take-apart-router","from":"take-apart-action","to":"take-apart-router","kind":"core","relation_type":"target","label_zh":"路由器承受拆解操作"},{"id":"take-apart-old->take-apart-router","from":"take-apart-old","to":"take-apart-router","kind":"modifier","relation_type":"quality","label_zh":"被拆的是一台旧路由器"},{"id":"take-apart-bench->take-apart-action","from":"take-apart-bench","to":"take-apart-action","kind":"modifier","relation_type":"place","label_zh":"拆解工作在维修台上进行"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Nina took apart the router.","sentence_zh":"Nina把路由器拆开了。","add_node_ids":["take-apart-action","take-apart-nina","take-apart-router"],"add_link_ids":["take-apart-action->take-apart-nina","take-apart-action->take-apart-router"],"focus_node_id":"take-apart-action","note_zh":"先建立人物拆开设备的核心画面。"},{"step_no":2,"label":"对象细节","sentence_en":"Nina took apart the old router.","sentence_zh":"Nina把那台旧路由器拆开了。","add_node_ids":["take-apart-old"],"add_link_ids":["take-apart-old->take-apart-router"],"focus_node_id":"take-apart-old","note_zh":"补充设备的新旧状态。"},{"step_no":3,"label":"场景","sentence_en":"Nina took apart the old router on the repair bench.","sentence_zh":"Nina在维修台上把那台旧路由器拆开了。","add_node_ids":["take-apart-bench"],"add_link_ids":["take-apart-bench->take-apart-action"],"focus_node_id":"take-apart-bench","note_zh":"加入适合硬件拆解的具体位置。"}]}'
  ),
  (
    'take-back-primary',
    'take-back',
    'take back',
    'take back a claim',
    '撤回先前的说法',
    'The vendor took back the claim.',
    '供应商撤回了那项主张。',
    'The vendor quietly took back the claim about unlimited retention.',
    '供应商悄然撤回了有关无限期保留的主张。',
    'vendor-proposal',
    '{"schema_version":2,"root_action_id":"take-back-action","nodes":[{"id":"take-back-action","text":"took back","kind":"action","label_zh":"撤回已经提出的说法"},{"id":"take-back-vendor","text":"The vendor","kind":"core","label_zh":"收回说法的供应商"},{"id":"take-back-claim","text":"the claim","kind":"core","label_zh":"被撤回的主张"},{"id":"take-back-retention","text":"about unlimited retention","kind":"modifier","label_zh":"指出主张涉及无限期保留"},{"id":"take-back-quietly","text":"quietly","kind":"modifier","label_zh":"说明撤回过程并未声张"}],"links":[{"id":"take-back-action->take-back-vendor","from":"take-back-action","to":"take-back-vendor","kind":"core","relation_type":"actor","label_zh":"供应商作出撤回决定"},{"id":"take-back-action->take-back-claim","from":"take-back-action","to":"take-back-claim","kind":"core","relation_type":"target","label_zh":"先前的主张被收回"},{"id":"take-back-retention->take-back-claim","from":"take-back-retention","to":"take-back-claim","kind":"modifier","relation_type":"scope","label_zh":"该主张讨论的是无限期保留"},{"id":"take-back-quietly->take-back-action","from":"take-back-quietly","to":"take-back-action","kind":"modifier","relation_type":"manner","label_zh":"供应商低调地完成撤回"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The vendor took back the claim.","sentence_zh":"供应商撤回了那项主张。","add_node_ids":["take-back-action","take-back-vendor","take-back-claim"],"add_link_ids":["take-back-action->take-back-vendor","take-back-action->take-back-claim"],"focus_node_id":"take-back-action","note_zh":"主干呈现供应商撤回说法。"},{"step_no":2,"label":"范围","sentence_en":"The vendor took back the claim about unlimited retention.","sentence_zh":"供应商撤回了有关无限期保留的主张。","add_node_ids":["take-back-retention"],"add_link_ids":["take-back-retention->take-back-claim"],"focus_node_id":"take-back-retention","note_zh":"明确被撤回主张所覆盖的议题。"},{"step_no":3,"label":"方式","sentence_en":"The vendor quietly took back the claim about unlimited retention.","sentence_zh":"供应商悄然撤回了有关无限期保留的主张。","add_node_ids":["take-back-quietly"],"add_link_ids":["take-back-quietly->take-back-action"],"focus_node_id":"take-back-quietly","note_zh":"增加撤回时低调处理的意味。"}]}'
  ),
  (
    'take-down-primary',
    'take-down',
    'take down',
    'take down an error code',
    '把信息记录下来',
    'I took down the error code.',
    '我记下了错误代码。',
    'During the support call, I took down the error code from the screenshot.',
    '在支持通话期间，我记下了截图中的错误代码。',
    'support-call',
    '{"schema_version":2,"root_action_id":"take-down-action","nodes":[{"id":"take-down-action","text":"took down","kind":"action","label_zh":"记录错误代码"},{"id":"take-down-i","text":"I","kind":"core","label_zh":"负责记录代码的人"},{"id":"take-down-code","text":"the error code","kind":"core","label_zh":"被记下的错误代码"},{"id":"take-down-screenshot","text":"from the screenshot","kind":"modifier","label_zh":"说明代码来自截图"},{"id":"take-down-call","text":"During the support call","kind":"modifier","label_zh":"记录代码发生的通话时段"}],"links":[{"id":"take-down-action->take-down-i","from":"take-down-action","to":"take-down-i","kind":"core","relation_type":"actor","label_zh":"我执行了记录操作"},{"id":"take-down-action->take-down-code","from":"take-down-action","to":"take-down-code","kind":"core","relation_type":"content","label_zh":"记录下来的内容是错误代码"},{"id":"take-down-screenshot->take-down-code","from":"take-down-screenshot","to":"take-down-code","kind":"modifier","relation_type":"place","label_zh":"错误代码出现在截图中"},{"id":"take-down-call->take-down-action","from":"take-down-call","to":"take-down-action","kind":"modifier","relation_type":"time","label_zh":"记录动作发生在支持通话期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I took down the error code.","sentence_zh":"我记下了错误代码。","add_node_ids":["take-down-action","take-down-i","take-down-code"],"add_link_ids":["take-down-action->take-down-i","take-down-action->take-down-code"],"focus_node_id":"take-down-action","note_zh":"先表达把关键信息记下来。"},{"step_no":2,"label":"对象细节","sentence_en":"I took down the error code from the screenshot.","sentence_zh":"我记下了截图中的错误代码。","add_node_ids":["take-down-screenshot"],"add_link_ids":["take-down-screenshot->take-down-code"],"focus_node_id":"take-down-screenshot","note_zh":"交代错误代码的可见来源。"},{"step_no":3,"label":"时间","sentence_en":"During the support call, I took down the error code from the screenshot.","sentence_zh":"在支持通话期间，我记下了截图中的错误代码。","add_node_ids":["take-down-call"],"add_link_ids":["take-down-call->take-down-action"],"focus_node_id":"take-down-call","note_zh":"将记录操作放进客服沟通场景。"}]}'
  ),
  (
    'take-on-primary',
    'take-on',
    'take on',
    'take on an incident',
    '承担一项任务',
    'Priya took on the incident.',
    'Priya接手了这起事故。',
    'Priya took on the overnight incident without hesitation.',
    'Priya毫不犹豫地接手了这起夜间事故。',
    'incident-response',
    '{"schema_version":2,"root_action_id":"take-on-action","nodes":[{"id":"take-on-action","text":"took on","kind":"action","label_zh":"接手事故处理任务"},{"id":"take-on-priya","text":"Priya","kind":"core","label_zh":"承担事故处理的人"},{"id":"take-on-incident","text":"the incident","kind":"core","label_zh":"需要负责的事故"},{"id":"take-on-overnight","text":"overnight","kind":"modifier","label_zh":"说明事故发生在夜间"},{"id":"take-on-hesitation","text":"without hesitation","kind":"modifier","label_zh":"说明接手时没有犹豫"}],"links":[{"id":"take-on-action->take-on-priya","from":"take-on-action","to":"take-on-priya","kind":"core","relation_type":"actor","label_zh":"Priya承担处理责任"},{"id":"take-on-action->take-on-incident","from":"take-on-action","to":"take-on-incident","kind":"core","relation_type":"target","label_zh":"这起事故成为她负责的任务"},{"id":"take-on-overnight->take-on-incident","from":"take-on-overnight","to":"take-on-incident","kind":"modifier","relation_type":"time","label_zh":"该事故属于夜间事件"},{"id":"take-on-hesitation->take-on-action","from":"take-on-hesitation","to":"take-on-action","kind":"modifier","relation_type":"manner","label_zh":"Priya立即接受了这项责任"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Priya took on the incident.","sentence_zh":"Priya接手了这起事故。","add_node_ids":["take-on-action","take-on-priya","take-on-incident"],"add_link_ids":["take-on-action->take-on-priya","take-on-action->take-on-incident"],"focus_node_id":"take-on-action","note_zh":"核心意思是主动承担事故处理。"},{"step_no":2,"label":"时间","sentence_en":"Priya took on the overnight incident.","sentence_zh":"Priya接手了这起夜间事故。","add_node_ids":["take-on-overnight"],"add_link_ids":["take-on-overnight->take-on-incident"],"focus_node_id":"take-on-overnight","note_zh":"指出这是发生在夜间的事故。"},{"step_no":3,"label":"方式","sentence_en":"Priya took on the overnight incident without hesitation.","sentence_zh":"Priya毫不犹豫地接手了这起夜间事故。","add_node_ids":["take-on-hesitation"],"add_link_ids":["take-on-hesitation->take-on-action"],"focus_node_id":"take-on-hesitation","note_zh":"突出她接受责任时的果断。"}]}'
  ),
  (
    'take-over-primary',
    'take-over',
    'take over',
    'take over a deployment',
    '接手正在进行的工作',
    'Omar took over the deployment.',
    'Omar接手了部署工作。',
    'Omar smoothly took over the deployment during the release manager''s break.',
    '发布经理休息期间，Omar顺利接手了部署工作。',
    'release-handoff',
    '{"schema_version":2,"root_action_id":"take-over-action","nodes":[{"id":"take-over-action","text":"took over","kind":"action","label_zh":"接手部署工作"},{"id":"take-over-omar","text":"Omar","kind":"core","label_zh":"接管部署的人"},{"id":"take-over-deployment","text":"the deployment","kind":"core","label_zh":"被接手的部署任务"},{"id":"take-over-smoothly","text":"smoothly","kind":"modifier","label_zh":"说明交接过程顺畅"},{"id":"take-over-break","text":"during the release manager''s break","kind":"modifier","label_zh":"接手发生在发布经理休息时"}],"links":[{"id":"take-over-action->take-over-omar","from":"take-over-action","to":"take-over-omar","kind":"core","relation_type":"actor","label_zh":"Omar成为部署的接管者"},{"id":"take-over-action->take-over-deployment","from":"take-over-action","to":"take-over-deployment","kind":"core","relation_type":"target","label_zh":"部署工作转由Omar负责"},{"id":"take-over-smoothly->take-over-action","from":"take-over-smoothly","to":"take-over-action","kind":"modifier","relation_type":"manner","label_zh":"职责转交没有出现明显阻碍"},{"id":"take-over-break->take-over-action","from":"take-over-break","to":"take-over-action","kind":"modifier","relation_type":"time","label_zh":"接管安排在发布经理休息期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Omar took over the deployment.","sentence_zh":"Omar接手了部署工作。","add_node_ids":["take-over-action","take-over-omar","take-over-deployment"],"add_link_ids":["take-over-action->take-over-omar","take-over-action->take-over-deployment"],"focus_node_id":"take-over-action","note_zh":"先呈现部署责任的转移。"},{"step_no":2,"label":"方式","sentence_en":"Omar smoothly took over the deployment.","sentence_zh":"Omar顺利接手了部署工作。","add_node_ids":["take-over-smoothly"],"add_link_ids":["take-over-smoothly->take-over-action"],"focus_node_id":"take-over-smoothly","note_zh":"说明这次交接进行得很顺畅。"},{"step_no":3,"label":"时间","sentence_en":"Omar smoothly took over the deployment during the release manager''s break.","sentence_zh":"发布经理休息期间，Omar顺利接手了部署工作。","add_node_ids":["take-over-break"],"add_link_ids":["take-over-break->take-over-action"],"focus_node_id":"take-over-break","note_zh":"补全临时交接发生的时间背景。"}]}'
  ),
  (
    'take-up-primary',
    'take-up',
    'take up',
    'take up storage',
    '占用空间',
    'The logs took up 12 gigabytes.',
    '这些日志占用了十二GB空间。',
    'The debug logs took up 12 gigabytes on the build server.',
    '这些调试日志在构建服务器上占用了十二GB空间。',
    'build-server',
    '{"schema_version":2,"root_action_id":"take-up-action","nodes":[{"id":"take-up-action","text":"took up","kind":"action","label_zh":"占用了存储容量"},{"id":"take-up-logs","text":"The logs","kind":"core","label_zh":"产生空间占用的日志"},{"id":"take-up-space","text":"12 gigabytes","kind":"core","label_zh":"日志占用的容量"},{"id":"take-up-debug","text":"debug","kind":"modifier","label_zh":"限定为调试日志"},{"id":"take-up-server","text":"on the build server","kind":"modifier","label_zh":"存储占用发生的服务器"}],"links":[{"id":"take-up-action->take-up-logs","from":"take-up-action","to":"take-up-logs","kind":"core","relation_type":"actor","label_zh":"这些日志造成了空间占用"},{"id":"take-up-action->take-up-space","from":"take-up-action","to":"take-up-space","kind":"core","relation_type":"content","label_zh":"被占用的容量达到十二GB"},{"id":"take-up-debug->take-up-logs","from":"take-up-debug","to":"take-up-logs","kind":"modifier","relation_type":"category","label_zh":"所指的是用于调试的日志"},{"id":"take-up-server->take-up-action","from":"take-up-server","to":"take-up-action","kind":"modifier","relation_type":"place","label_zh":"空间被占用在构建服务器上"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The logs took up 12 gigabytes.","sentence_zh":"这些日志占用了十二GB空间。","add_node_ids":["take-up-action","take-up-logs","take-up-space"],"add_link_ids":["take-up-action->take-up-logs","take-up-action->take-up-space"],"focus_node_id":"take-up-action","note_zh":"用具体容量表达日志占用空间。"},{"step_no":2,"label":"对象细节","sentence_en":"The debug logs took up 12 gigabytes.","sentence_zh":"这些调试日志占用了十二GB空间。","add_node_ids":["take-up-debug"],"add_link_ids":["take-up-debug->take-up-logs"],"focus_node_id":"take-up-debug","note_zh":"明确造成占用的是调试日志。"},{"step_no":3,"label":"场景","sentence_en":"The debug logs took up 12 gigabytes on the build server.","sentence_zh":"这些调试日志在构建服务器上占用了十二GB空间。","add_node_ids":["take-up-server"],"add_link_ids":["take-up-server->take-up-action"],"focus_node_id":"take-up-server","note_zh":"指出受存储占用影响的具体机器。"}]}'
  ),
  (
    'talk-primary',
    'talk',
    'talk',
    'talk with a designer',
    '与某人交谈',
    'I talked with the designer.',
    '我和设计师谈了谈。',
    'I talked with the designer about the empty state over lunch.',
    '午餐时，我和设计师谈了空状态设计。',
    'design-discussion',
    '{"schema_version":2,"root_action_id":"talk-action","nodes":[{"id":"talk-action","text":"talked","kind":"action","label_zh":"进行面对面交流"},{"id":"talk-i","text":"I","kind":"core","label_zh":"发起交流的人"},{"id":"talk-designer","text":"the designer","kind":"core","label_zh":"参与交流的设计师"},{"id":"talk-empty-state","text":"the empty state","kind":"core","label_zh":"双方谈论的空状态设计"},{"id":"talk-lunch","text":"over lunch","kind":"modifier","label_zh":"交流安排在午餐期间"}],"links":[{"id":"talk-action->talk-i","from":"talk-action","to":"talk-i","kind":"core","relation_type":"actor","label_zh":"我参与并发起这次谈话"},{"id":"talk-action->talk-designer","from":"talk-action","to":"talk-designer","kind":"core","relation_type":"recipient","label_zh":"设计师是交谈的另一方"},{"id":"talk-action->talk-empty-state","from":"talk-action","to":"talk-empty-state","kind":"core","relation_type":"content","label_zh":"谈话围绕空状态展开"},{"id":"talk-lunch->talk-action","from":"talk-lunch","to":"talk-action","kind":"modifier","relation_type":"time","label_zh":"双方利用午餐时间交流"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I talked with the designer.","sentence_zh":"我和设计师谈了谈。","add_node_ids":["talk-action","talk-i","talk-designer"],"add_link_ids":["talk-action->talk-i","talk-action->talk-designer"],"focus_node_id":"talk-action","note_zh":"先建立两人交谈的关系。"},{"step_no":2,"label":"内容","sentence_en":"I talked with the designer about the empty state.","sentence_zh":"我和设计师谈了空状态设计。","add_node_ids":["talk-empty-state"],"add_link_ids":["talk-action->talk-empty-state"],"focus_node_id":"talk-empty-state","note_zh":"加入双方交流的具体设计问题。"},{"step_no":3,"label":"时间","sentence_en":"I talked with the designer about the empty state over lunch.","sentence_zh":"午餐时，我和设计师谈了空状态设计。","add_node_ids":["talk-lunch"],"add_link_ids":["talk-lunch->talk-action"],"focus_node_id":"talk-lunch","note_zh":"说明团队利用午餐时间完成沟通。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'talk-over-primary',
    'talk-over',
    'talk over',
    'talk over a rollback plan',
    '共同商量一项计划',
    'We talked over the rollback plan.',
    '我们商量了回滚方案。',
    'We talked over the rollback plan with security in a private channel.',
    '我们在私密频道中和安全团队商量了回滚方案。',
    'rollback-review',
    '{"schema_version":2,"root_action_id":"talk-over-action","nodes":[{"id":"talk-over-action","text":"talked over","kind":"action","label_zh":"详细商量回滚方案"},{"id":"talk-over-we","text":"We","kind":"core","label_zh":"参与方案讨论的团队"},{"id":"talk-over-plan","text":"the rollback plan","kind":"core","label_zh":"需要商量的回滚方案"},{"id":"talk-over-security","text":"security","kind":"core","label_zh":"共同评估方案的安全团队"},{"id":"talk-over-channel","text":"in a private channel","kind":"modifier","label_zh":"讨论使用的私密频道"}],"links":[{"id":"talk-over-action->talk-over-we","from":"talk-over-action","to":"talk-over-we","kind":"core","relation_type":"actor","label_zh":"我们参与了方案商议"},{"id":"talk-over-action->talk-over-plan","from":"talk-over-action","to":"talk-over-plan","kind":"core","relation_type":"content","label_zh":"商议内容是回滚方案"},{"id":"talk-over-action->talk-over-security","from":"talk-over-action","to":"talk-over-security","kind":"core","relation_type":"recipient","label_zh":"安全团队加入了这次商议"},{"id":"talk-over-channel->talk-over-action","from":"talk-over-channel","to":"talk-over-action","kind":"modifier","relation_type":"place","label_zh":"敏感讨论在私密频道中进行"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We talked over the rollback plan.","sentence_zh":"我们商量了回滚方案。","add_node_ids":["talk-over-action","talk-over-we","talk-over-plan"],"add_link_ids":["talk-over-action->talk-over-we","talk-over-action->talk-over-plan"],"focus_node_id":"talk-over-action","note_zh":"主干表达对方案进行充分讨论。"},{"step_no":2,"label":"对象","sentence_en":"We talked over the rollback plan with security.","sentence_zh":"我们和安全团队商量了回滚方案。","add_node_ids":["talk-over-security"],"add_link_ids":["talk-over-action->talk-over-security"],"focus_node_id":"talk-over-security","note_zh":"补入需要参与风险判断的团队。"},{"step_no":3,"label":"场景","sentence_en":"We talked over the rollback plan with security in a private channel.","sentence_zh":"我们在私密频道中和安全团队商量了回滚方案。","add_node_ids":["talk-over-channel"],"add_link_ids":["talk-over-channel->talk-over-action"],"focus_node_id":"talk-over-channel","note_zh":"说明敏感方案通过非公开频道讨论。"}]}'
  ),
  (
    'talk-up-primary',
    'talk-up',
    'talk up',
    'talk up a feature',
    '积极称赞并宣传',
    'Lena talked up the new search feature.',
    'Lena大力称赞了新的搜索功能。',
    'Lena talked up the new search feature to skeptical customers during every demo.',
    '每次演示时，Lena都会向持怀疑态度的客户大力宣传新的搜索功能。',
    'product-demo',
    '{"schema_version":2,"root_action_id":"talk-up-action","nodes":[{"id":"talk-up-action","text":"talked up","kind":"action","label_zh":"积极宣传功能优势"},{"id":"talk-up-lena","text":"Lena","kind":"core","label_zh":"负责推介功能的人"},{"id":"talk-up-feature","text":"the new search feature","kind":"core","label_zh":"受到称赞的新搜索功能"},{"id":"talk-up-customers","text":"skeptical customers","kind":"core","label_zh":"对功能持怀疑态度的客户"},{"id":"talk-up-demos","text":"during every demo","kind":"modifier","label_zh":"宣传反复出现的演示场合"}],"links":[{"id":"talk-up-action->talk-up-lena","from":"talk-up-action","to":"talk-up-lena","kind":"core","relation_type":"actor","label_zh":"Lena负责积极推介"},{"id":"talk-up-action->talk-up-feature","from":"talk-up-action","to":"talk-up-feature","kind":"core","relation_type":"target","label_zh":"新搜索功能是宣传重点"},{"id":"talk-up-action->talk-up-customers","from":"talk-up-action","to":"talk-up-customers","kind":"core","relation_type":"recipient","label_zh":"宣传面向尚未信服的客户"},{"id":"talk-up-demos->talk-up-action","from":"talk-up-demos","to":"talk-up-action","kind":"modifier","relation_type":"frequency","label_zh":"Lena在每次演示中都会推介该功能"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Lena talked up the new search feature.","sentence_zh":"Lena大力称赞了新的搜索功能。","add_node_ids":["talk-up-action","talk-up-lena","talk-up-feature"],"add_link_ids":["talk-up-action->talk-up-lena","talk-up-action->talk-up-feature"],"focus_node_id":"talk-up-action","note_zh":"先表现Lena积极宣传产品功能。"},{"step_no":2,"label":"对象","sentence_en":"Lena talked up the new search feature to skeptical customers.","sentence_zh":"Lena向持怀疑态度的客户大力宣传新的搜索功能。","add_node_ids":["talk-up-customers"],"add_link_ids":["talk-up-action->talk-up-customers"],"focus_node_id":"talk-up-customers","note_zh":"指出这番宣传主要说给谁听。"},{"step_no":3,"label":"频率","sentence_en":"Lena talked up the new search feature to skeptical customers during every demo.","sentence_zh":"每次演示时，Lena都会向持怀疑态度的客户大力宣传新的搜索功能。","add_node_ids":["talk-up-demos"],"add_link_ids":["talk-up-demos->talk-up-action"],"focus_node_id":"talk-up-demos","note_zh":"强调这种推介在演示中反复发生。"}]}'
  ),
  (
    'tap-into-primary',
    'tap-into',
    'tap into',
    'tap into motion sensors',
    '接入并利用某种资源',
    'The app taps into the phone''s motion sensors.',
    '这个应用接入了手机的运动传感器。',
    'The app taps into the phone''s motion sensors to detect sudden movement during workouts.',
    '这个应用在锻炼期间接入手机的运动传感器，以识别突然的移动。',
    'mobile-sensors',
    '{"schema_version":2,"root_action_id":"tap-into-action","nodes":[{"id":"tap-into-action","text":"taps into","kind":"action","label_zh":"接入手机传感器数据"},{"id":"tap-into-app","text":"The app","kind":"core","label_zh":"使用传感器的应用"},{"id":"tap-into-sensors","text":"the phone''s motion sensors","kind":"core","label_zh":"被应用利用的运动传感器"},{"id":"tap-into-detect","text":"detect","kind":"action","label_zh":"识别突然发生的移动"},{"id":"tap-into-movement","text":"sudden movement","kind":"core","label_zh":"需要识别的突然移动"},{"id":"tap-into-workouts","text":"during workouts","kind":"modifier","label_zh":"应用读取传感器的使用场景"}],"links":[{"id":"tap-into-action->tap-into-app","from":"tap-into-action","to":"tap-into-app","kind":"core","relation_type":"actor","label_zh":"应用主动接入传感器"},{"id":"tap-into-action->tap-into-sensors","from":"tap-into-action","to":"tap-into-sensors","kind":"core","relation_type":"target","label_zh":"应用利用手机的运动传感器"},{"id":"tap-into-detect->tap-into-app","from":"tap-into-detect","to":"tap-into-app","kind":"core","relation_type":"shared_actor","label_zh":"执行识别的仍是这个应用"},{"id":"tap-into-detect->tap-into-movement","from":"tap-into-detect","to":"tap-into-movement","kind":"core","relation_type":"target","label_zh":"识别操作针对突然移动"},{"id":"tap-into-detect->tap-into-action","from":"tap-into-detect","to":"tap-into-action","kind":"modifier","relation_type":"purpose","label_zh":"接入传感器是为了识别移动"},{"id":"tap-into-workouts->tap-into-action","from":"tap-into-workouts","to":"tap-into-action","kind":"modifier","relation_type":"time","label_zh":"传感器接入在锻炼期间启用"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The app taps into the phone''s motion sensors.","sentence_zh":"这个应用接入了手机的运动传感器。","add_node_ids":["tap-into-action","tap-into-app","tap-into-sensors"],"add_link_ids":["tap-into-action->tap-into-app","tap-into-action->tap-into-sensors"],"focus_node_id":"tap-into-action","note_zh":"先说明应用利用哪项设备能力。"},{"step_no":2,"label":"目的","sentence_en":"The app taps into the phone''s motion sensors to detect sudden movement.","sentence_zh":"这个应用接入手机的运动传感器，以识别突然的移动。","add_node_ids":["tap-into-detect","tap-into-movement"],"add_link_ids":["tap-into-detect->tap-into-app","tap-into-detect->tap-into-movement","tap-into-detect->tap-into-action"],"focus_node_id":"tap-into-detect","note_zh":"新增识别动作，解释接入传感器的目的。"},{"step_no":3,"label":"场景","sentence_en":"The app taps into the phone''s motion sensors to detect sudden movement during workouts.","sentence_zh":"这个应用在锻炼期间接入手机的运动传感器，以识别突然的移动。","add_node_ids":["tap-into-workouts"],"add_link_ids":["tap-into-workouts->tap-into-action"],"focus_node_id":"tap-into-workouts","note_zh":"将功能放入锻炼中的实际使用环境。"}]}'
  ),
  (
    'taper-off-primary',
    'taper-off',
    'taper off',
    'requests taper off',
    '数量逐渐减少',
    'Support requests tapered off.',
    '支持请求逐渐减少了。',
    'Support requests gradually tapered off after the hotfix.',
    '热修复发布后，支持请求慢慢减少了。',
    'post-hotfix-support',
    '{"schema_version":2,"root_action_id":"taper-off-action","nodes":[{"id":"taper-off-action","text":"tapered off","kind":"action","label_zh":"请求数量逐步下降"},{"id":"taper-off-requests","text":"Support requests","kind":"core","label_zh":"逐渐变少的支持请求"},{"id":"taper-off-hotfix","text":"after the hotfix","kind":"modifier","label_zh":"请求开始减少的修复节点"},{"id":"taper-off-gradually","text":"gradually","kind":"modifier","label_zh":"强调下降过程缓慢连续"}],"links":[{"id":"taper-off-action->taper-off-requests","from":"taper-off-action","to":"taper-off-requests","kind":"core","relation_type":"actor","label_zh":"支持请求呈现下降变化"},{"id":"taper-off-hotfix->taper-off-action","from":"taper-off-hotfix","to":"taper-off-action","kind":"modifier","relation_type":"time","label_zh":"下降出现在热修复发布之后"},{"id":"taper-off-gradually->taper-off-action","from":"taper-off-gradually","to":"taper-off-action","kind":"modifier","relation_type":"manner","label_zh":"请求不是骤减，而是逐步减少"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Support requests tapered off.","sentence_zh":"支持请求逐渐减少了。","add_node_ids":["taper-off-action","taper-off-requests"],"add_link_ids":["taper-off-action->taper-off-requests"],"focus_node_id":"taper-off-action","note_zh":"主干描写请求量由多到少的变化。"},{"step_no":2,"label":"时间","sentence_en":"Support requests tapered off after the hotfix.","sentence_zh":"热修复发布后，支持请求逐渐减少了。","add_node_ids":["taper-off-hotfix"],"add_link_ids":["taper-off-hotfix->taper-off-action"],"focus_node_id":"taper-off-hotfix","note_zh":"把下降趋势与修复后的时段联系起来。"},{"step_no":3,"label":"方式","sentence_en":"Support requests gradually tapered off after the hotfix.","sentence_zh":"热修复发布后，支持请求慢慢减少了。","add_node_ids":["taper-off-gradually"],"add_link_ids":["taper-off-gradually->taper-off-action"],"focus_node_id":"taper-off-gradually","note_zh":"进一步突出数量变化的渐进性。"}]}'
  ),
  (
    'target-primary',
    'target',
    'target',
    'target small teams',
    '把特定群体作为目标',
    'The campaign targets small teams.',
    '这项推广活动瞄准小型团队。',
    'The regional campaign targets small teams with outdated servers.',
    '这项地区性推广活动瞄准仍在使用旧服务器的小型团队。',
    'b2b-campaign',
    '{"schema_version":2,"root_action_id":"target-action","nodes":[{"id":"target-action","text":"targets","kind":"action","label_zh":"把小型团队设为推广重点"},{"id":"target-campaign","text":"The campaign","kind":"core","label_zh":"具有明确受众的推广活动"},{"id":"target-teams","text":"small teams","kind":"core","label_zh":"推广活动瞄准的小型团队"},{"id":"target-servers","text":"with outdated servers","kind":"modifier","label_zh":"说明这些团队仍在使用旧服务器"},{"id":"target-regional","text":"regional","kind":"modifier","label_zh":"限定为地区性推广活动"}],"links":[{"id":"target-action->target-campaign","from":"target-action","to":"target-campaign","kind":"core","relation_type":"actor","label_zh":"推广活动执行受众定位"},{"id":"target-action->target-teams","from":"target-action","to":"target-teams","kind":"core","relation_type":"target","label_zh":"小型团队是活动重点触达的人群"},{"id":"target-servers->target-teams","from":"target-servers","to":"target-teams","kind":"modifier","relation_type":"quality","label_zh":"目标团队具有服务器老旧的特点"},{"id":"target-regional->target-campaign","from":"target-regional","to":"target-campaign","kind":"modifier","relation_type":"scope","label_zh":"这项活动只覆盖特定地区"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The campaign targets small teams.","sentence_zh":"这项推广活动瞄准小型团队。","add_node_ids":["target-action","target-campaign","target-teams"],"add_link_ids":["target-action->target-campaign","target-action->target-teams"],"focus_node_id":"target-action","note_zh":"直接说明推广活动的目标群体。"},{"step_no":2,"label":"对象细节","sentence_en":"The campaign targets small teams with outdated servers.","sentence_zh":"这项推广活动瞄准仍在使用旧服务器的小型团队。","add_node_ids":["target-servers"],"add_link_ids":["target-servers->target-teams"],"focus_node_id":"target-servers","note_zh":"进一步筛选具有设备升级需求的团队。"},{"step_no":3,"label":"范围","sentence_en":"The regional campaign targets small teams with outdated servers.","sentence_zh":"这项地区性推广活动瞄准仍在使用旧服务器的小型团队。","add_node_ids":["target-regional"],"add_link_ids":["target-regional->target-campaign"],"focus_node_id":"target-regional","note_zh":"限定推广活动覆盖的地域范围。"}]}'
  ),
  (
    'taste-primary',
    'taste',
    'taste',
    'taste the sauce',
    '品尝食物以判断味道',
    'The chef tasted the sauce.',
    '厨师尝了尝酱汁。',
    'The chef tasted the spicy sauce before service.',
    '营业开始前，厨师尝了尝这份辣味酱汁。',
    'restaurant-kitchen',
    '{"schema_version":2,"root_action_id":"taste-action","nodes":[{"id":"taste-action","text":"tasted","kind":"action","label_zh":"品尝酱汁味道"},{"id":"taste-chef","text":"The chef","kind":"core","label_zh":"负责试味的厨师"},{"id":"taste-sauce","text":"the sauce","kind":"core","label_zh":"被品尝的酱汁"},{"id":"taste-spicy","text":"spicy","kind":"modifier","label_zh":"说明酱汁带有辣味"},{"id":"taste-service","text":"before service","kind":"modifier","label_zh":"品尝发生在开始营业前"}],"links":[{"id":"taste-action->taste-chef","from":"taste-action","to":"taste-chef","kind":"core","relation_type":"actor","label_zh":"厨师执行试味"},{"id":"taste-action->taste-sauce","from":"taste-action","to":"taste-sauce","kind":"core","relation_type":"target","label_zh":"酱汁接受味道检查"},{"id":"taste-spicy->taste-sauce","from":"taste-spicy","to":"taste-sauce","kind":"modifier","relation_type":"quality","label_zh":"这份酱汁的风味偏辣"},{"id":"taste-service->taste-action","from":"taste-service","to":"taste-action","kind":"modifier","relation_type":"time","label_zh":"厨师在营业开始前完成试味"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The chef tasted the sauce.","sentence_zh":"厨师尝了尝酱汁。","add_node_ids":["taste-action","taste-chef","taste-sauce"],"add_link_ids":["taste-action->taste-chef","taste-action->taste-sauce"],"focus_node_id":"taste-action","note_zh":"先呈现厨师检查味道的动作。"},{"step_no":2,"label":"对象细节","sentence_en":"The chef tasted the spicy sauce.","sentence_zh":"厨师尝了尝这份辣味酱汁。","add_node_ids":["taste-spicy"],"add_link_ids":["taste-spicy->taste-sauce"],"focus_node_id":"taste-spicy","note_zh":"补充酱汁最明显的风味特点。"},{"step_no":3,"label":"时间","sentence_en":"The chef tasted the spicy sauce before service.","sentence_zh":"营业开始前，厨师尝了尝这份辣味酱汁。","add_node_ids":["taste-service"],"add_link_ids":["taste-service->taste-action"],"focus_node_id":"taste-service","note_zh":"说明试味是开餐前的准备工作。"}]}'
  ),
  (
    'teach-primary',
    'teach',
    'teach',
    'teach interns Git rebasing',
    '向某人教授一项技能',
    'Ava taught the interns Git rebasing.',
    'Ava教实习生学习Git变基。',
    'Ava taught the interns Git rebasing through a live exercise on their first day.',
    '实习生入职第一天，Ava通过现场练习教他们学习Git变基。',
    'git-training',
    '{"schema_version":2,"root_action_id":"teach-action","nodes":[{"id":"teach-action","text":"taught","kind":"action","label_zh":"讲授Git变基技能"},{"id":"teach-ava","text":"Ava","kind":"core","label_zh":"负责技术培训的人"},{"id":"teach-interns","text":"the interns","kind":"core","label_zh":"学习变基操作的实习生"},{"id":"teach-rebasing","text":"Git rebasing","kind":"core","label_zh":"培训所讲授的技术内容"},{"id":"teach-exercise","text":"through a live exercise","kind":"modifier","label_zh":"使用现场练习进行教学"},{"id":"teach-first-day","text":"on their first day","kind":"modifier","label_zh":"培训安排在实习生入职首日"}],"links":[{"id":"teach-action->teach-ava","from":"teach-action","to":"teach-ava","kind":"core","relation_type":"actor","label_zh":"Ava承担教学工作"},{"id":"teach-action->teach-interns","from":"teach-action","to":"teach-interns","kind":"core","relation_type":"recipient","label_zh":"实习生接受这次技术教学"},{"id":"teach-action->teach-rebasing","from":"teach-action","to":"teach-rebasing","kind":"core","relation_type":"content","label_zh":"教学内容是Git变基"},{"id":"teach-exercise->teach-action","from":"teach-exercise","to":"teach-action","kind":"modifier","relation_type":"manner","label_zh":"Ava通过现场练习来讲解"},{"id":"teach-first-day->teach-action","from":"teach-first-day","to":"teach-action","kind":"modifier","relation_type":"time","label_zh":"课程在实习生第一天开展"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Ava taught the interns Git rebasing.","sentence_zh":"Ava教实习生学习Git变基。","add_node_ids":["teach-action","teach-ava","teach-interns","teach-rebasing"],"add_link_ids":["teach-action->teach-ava","teach-action->teach-interns","teach-action->teach-rebasing"],"focus_node_id":"teach-action","note_zh":"主干完整交代教学者、学习者和内容。"},{"step_no":2,"label":"方式","sentence_en":"Ava taught the interns Git rebasing through a live exercise.","sentence_zh":"Ava通过现场练习教实习生学习Git变基。","add_node_ids":["teach-exercise"],"add_link_ids":["teach-exercise->teach-action"],"focus_node_id":"teach-exercise","note_zh":"加入实践型的技术教学方法。"},{"step_no":3,"label":"时间","sentence_en":"Ava taught the interns Git rebasing through a live exercise on their first day.","sentence_zh":"实习生入职第一天，Ava通过现场练习教他们学习Git变基。","add_node_ids":["teach-first-day"],"add_link_ids":["teach-first-day->teach-action"],"focus_node_id":"teach-first-day","note_zh":"明确这项技能培训在何时进行。"}]}'
  ),
  (
    'tear-primary',
    'tear',
    'tear',
    'tear a label',
    '把材料撕破',
    'The cable tie tore the label.',
    '扎带撕破了标签。',
    'The cable tie tore the paper label during shipping.',
    '运输途中，扎带撕破了纸质标签。',
    'package-shipping',
    '{"schema_version":2,"root_action_id":"tear-action","nodes":[{"id":"tear-action","text":"tore","kind":"action","label_zh":"把标签刮扯破损"},{"id":"tear-tie","text":"The cable tie","kind":"core","label_zh":"造成标签破损的扎带"},{"id":"tear-label","text":"the label","kind":"core","label_zh":"被撕破的标签"},{"id":"tear-paper","text":"paper","kind":"modifier","label_zh":"说明标签由纸制成"},{"id":"tear-shipping","text":"during shipping","kind":"modifier","label_zh":"破损发生在运输途中"}],"links":[{"id":"tear-action->tear-tie","from":"tear-action","to":"tear-tie","kind":"core","relation_type":"actor","label_zh":"扎带造成了撕裂"},{"id":"tear-action->tear-label","from":"tear-action","to":"tear-label","kind":"core","relation_type":"target","label_zh":"标签承受了撕扯并破损"},{"id":"tear-paper->tear-label","from":"tear-paper","to":"tear-label","kind":"modifier","relation_type":"category","label_zh":"受损标签是纸质的"},{"id":"tear-shipping->tear-action","from":"tear-shipping","to":"tear-action","kind":"modifier","relation_type":"time","label_zh":"撕裂发生在包裹运输期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The cable tie tore the label.","sentence_zh":"扎带撕破了标签。","add_node_ids":["tear-action","tear-tie","tear-label"],"add_link_ids":["tear-action->tear-tie","tear-action->tear-label"],"focus_node_id":"tear-action","note_zh":"先展示扎带导致标签破损。"},{"step_no":2,"label":"对象细节","sentence_en":"The cable tie tore the paper label.","sentence_zh":"扎带撕破了纸质标签。","add_node_ids":["tear-paper"],"add_link_ids":["tear-paper->tear-label"],"focus_node_id":"tear-paper","note_zh":"补充标签容易被撕破的材质。"},{"step_no":3,"label":"时间","sentence_en":"The cable tie tore the paper label during shipping.","sentence_zh":"运输途中，扎带撕破了纸质标签。","add_node_ids":["tear-shipping"],"add_link_ids":["tear-shipping->tear-action"],"focus_node_id":"tear-shipping","note_zh":"交代包装破损发生的运输阶段。"}]}'
  ),
  (
    'tear-down-primary',
    'tear-down',
    'tear down',
    'tear down a sandbox',
    '销毁临时运行环境',
    'The test runner tore down the sandbox.',
    '测试程序销毁了隔离环境。',
    'The test runner automatically tore down the sandbox after each integration test.',
    '每次集成测试结束后，测试程序都会自动销毁隔离环境。',
    'integration-testing',
    '{"schema_version":2,"root_action_id":"tear-down-action","nodes":[{"id":"tear-down-action","text":"tore down","kind":"action","label_zh":"销毁临时测试环境"},{"id":"tear-down-runner","text":"The test runner","kind":"core","label_zh":"负责清理环境的测试程序"},{"id":"tear-down-sandbox","text":"the sandbox","kind":"core","label_zh":"被销毁的隔离环境"},{"id":"tear-down-automatically","text":"automatically","kind":"modifier","label_zh":"说明清理无需人工触发"},{"id":"tear-down-test","text":"after each integration test","kind":"modifier","label_zh":"每次集成测试后的清理时点"}],"links":[{"id":"tear-down-action->tear-down-runner","from":"tear-down-action","to":"tear-down-runner","kind":"core","relation_type":"actor","label_zh":"测试程序执行环境销毁"},{"id":"tear-down-action->tear-down-sandbox","from":"tear-down-action","to":"tear-down-sandbox","kind":"core","relation_type":"target","label_zh":"隔离环境在测试后被移除"},{"id":"tear-down-automatically->tear-down-action","from":"tear-down-automatically","to":"tear-down-action","kind":"modifier","relation_type":"manner","label_zh":"测试程序自行完成环境清理"},{"id":"tear-down-test->tear-down-action","from":"tear-down-test","to":"tear-down-action","kind":"modifier","relation_type":"sequence","label_zh":"环境销毁紧接在每次集成测试之后"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The test runner tore down the sandbox.","sentence_zh":"测试程序销毁了隔离环境。","add_node_ids":["tear-down-action","tear-down-runner","tear-down-sandbox"],"add_link_ids":["tear-down-action->tear-down-runner","tear-down-action->tear-down-sandbox"],"focus_node_id":"tear-down-action","note_zh":"主干表达测试资源被清理。"},{"step_no":2,"label":"方式","sentence_en":"The test runner automatically tore down the sandbox.","sentence_zh":"测试程序自动销毁了隔离环境。","add_node_ids":["tear-down-automatically"],"add_link_ids":["tear-down-automatically->tear-down-action"],"focus_node_id":"tear-down-automatically","note_zh":"说明资源清理由程序自动完成。"},{"step_no":3,"label":"顺序","sentence_en":"The test runner automatically tore down the sandbox after each integration test.","sentence_zh":"每次集成测试结束后，测试程序都会自动销毁隔离环境。","add_node_ids":["tear-down-test"],"add_link_ids":["tear-down-test->tear-down-action"],"focus_node_id":"tear-down-test","note_zh":"建立测试结束与环境清理的先后关系。"}]}'
  ),
  (
    'tell-primary',
    'tell',
    'tell',
    'tell someone the cache is stale',
    '把信息告诉某人',
    'The monitor told us the cache was stale.',
    '监控系统告诉我们缓存已经过期。',
    'The monitor clearly told us the cache was stale during the rollout.',
    '发布期间，监控系统明确告诉我们缓存已经过期。',
    'deployment-monitoring',
    '{"schema_version":2,"root_action_id":"tell-action","nodes":[{"id":"tell-action","text":"told","kind":"action","label_zh":"传达缓存状态信息"},{"id":"tell-monitor","text":"The monitor","kind":"core","label_zh":"发出状态提示的监控系统"},{"id":"tell-us","text":"us","kind":"core","label_zh":"收到提示的团队"},{"id":"tell-stale-state","text":"was","kind":"action","label_zh":"表示缓存处于过期状态"},{"id":"tell-cache","text":"the cache","kind":"core","label_zh":"状态被报告的缓存"},{"id":"tell-stale","text":"stale","kind":"core","label_zh":"缓存被报告为已经过期"},{"id":"tell-clearly","text":"clearly","kind":"modifier","label_zh":"说明提示内容表达清楚"},{"id":"tell-rollout","text":"during the rollout","kind":"modifier","label_zh":"监控发出提示的发布阶段"}],"links":[{"id":"tell-action->tell-monitor","from":"tell-action","to":"tell-monitor","kind":"core","relation_type":"actor","label_zh":"监控系统发出了提示"},{"id":"tell-action->tell-us","from":"tell-action","to":"tell-us","kind":"core","relation_type":"recipient","label_zh":"团队接收到状态信息"},{"id":"tell-action->tell-stale-state","from":"tell-action","to":"tell-stale-state","kind":"core","relation_type":"nested_action","label_zh":"提示内容是缓存已经过期"},{"id":"tell-stale-state->tell-cache","from":"tell-stale-state","to":"tell-cache","kind":"core","relation_type":"actor","label_zh":"处于该状态的是缓存"},{"id":"tell-stale-state->tell-stale","from":"tell-stale-state","to":"tell-stale","kind":"core","relation_type":"quality","label_zh":"缓存的具体状态是过期"},{"id":"tell-clearly->tell-action","from":"tell-clearly","to":"tell-action","kind":"modifier","relation_type":"manner","label_zh":"监控以明确方式传达信息"},{"id":"tell-rollout->tell-action","from":"tell-rollout","to":"tell-action","kind":"modifier","relation_type":"time","label_zh":"提示出现在系统发布期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The monitor told us the cache was stale.","sentence_zh":"监控系统告诉我们缓存已经过期。","add_node_ids":["tell-action","tell-monitor","tell-us","tell-stale-state","tell-cache","tell-stale"],"add_link_ids":["tell-action->tell-monitor","tell-action->tell-us","tell-action->tell-stale-state","tell-stale-state->tell-cache","tell-stale-state->tell-stale"],"focus_node_id":"tell-action","note_zh":"主干包含信息来源、接收者和完整提示内容。"},{"step_no":2,"label":"方式","sentence_en":"The monitor clearly told us the cache was stale.","sentence_zh":"监控系统明确告诉我们缓存已经过期。","add_node_ids":["tell-clearly"],"add_link_ids":["tell-clearly->tell-action"],"focus_node_id":"tell-clearly","note_zh":"加入提示表达清晰这一特点。"},{"step_no":3,"label":"时间","sentence_en":"The monitor clearly told us the cache was stale during the rollout.","sentence_zh":"发布期间，监控系统明确告诉我们缓存已经过期。","add_node_ids":["tell-rollout"],"add_link_ids":["tell-rollout->tell-action"],"focus_node_id":"tell-rollout","note_zh":"最后交代这项状态提示出现的发布阶段。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
