-- Generated verb paths batch batch-004.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'tend-primary',
    'tend',
    'tend',
    'tend to fail',
    '往往会；倾向于',
    'Small services tend to fail.',
    '小型服务往往容易出故障。',
    'Small services tend to fail quietly under burst traffic.',
    '小型服务在突发流量下往往会悄无声息地出故障。',
    'service-reliability',
    '{"schema_version":2,"root_action_id":"tend","nodes":[{"id":"tend","text":"tend","kind":"action","label_zh":"表现出通常会发生的倾向"},{"id":"small-services","text":"Small services","kind":"core","label_zh":"通常会出现这种情况的服务"},{"id":"fail","text":"fail","kind":"action","label_zh":"服务容易发生的故障"},{"id":"quietly","text":"quietly","kind":"modifier","label_zh":"故障发生时不易被察觉"},{"id":"under-burst-traffic","text":"under burst traffic","kind":"modifier","label_zh":"故障容易出现的流量条件"}],"links":[{"id":"tend->small-services","from":"tend","to":"small-services","kind":"core","relation_type":"actor","label_zh":"小型服务表现出这种倾向"},{"id":"tend->fail","from":"tend","to":"fail","kind":"core","relation_type":"nested_action","label_zh":"这种倾向表现为容易发生故障"},{"id":"fail->small-services","from":"fail","to":"small-services","kind":"core","relation_type":"shared_actor","label_zh":"发生故障的也是这些小型服务"},{"id":"quietly->fail","from":"quietly","to":"fail","kind":"modifier","relation_type":"manner","label_zh":"故障以不明显的方式发生"},{"id":"under-burst-traffic->fail","from":"under-burst-traffic","to":"fail","kind":"modifier","relation_type":"condition","label_zh":"突发流量是故障容易出现的条件"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Small services tend to fail.","sentence_zh":"小型服务往往容易出故障。","add_node_ids":["tend","small-services","fail"],"add_link_ids":["tend->small-services","tend->fail","fail->small-services"],"focus_node_id":"tend","note_zh":"先说明小型服务通常会出现什么情况。"},{"step_no":2,"label":"方式","sentence_en":"Small services tend to fail quietly.","sentence_zh":"小型服务往往会悄无声息地出故障。","add_node_ids":["quietly"],"add_link_ids":["quietly->fail"],"focus_node_id":"quietly","note_zh":"补充故障不易被察觉这一特点。"},{"step_no":3,"label":"条件","sentence_en":"Small services tend to fail quietly under burst traffic.","sentence_zh":"小型服务在突发流量下往往会悄无声息地出故障。","add_node_ids":["under-burst-traffic"],"add_link_ids":["under-burst-traffic->fail"],"focus_node_id":"under-burst-traffic","note_zh":"最后指出容易触发故障的流量条件。"}]}'
  ),
  (
    'terminate-primary',
    'terminate',
    'terminate',
    'terminate an idle worker',
    '终止运行',
    'The scheduler terminated the worker.',
    '调度器终止了这个工作进程。',
    'The scheduler terminated the idle worker after the worker''s lease expired.',
    '该工作进程的租约到期后，调度器终止了这个空闲进程。',
    'worker-lifecycle',
    '{"schema_version":2,"root_action_id":"terminated","nodes":[{"id":"terminated","text":"terminated","kind":"action","label_zh":"停止工作进程的运行"},{"id":"scheduler","text":"The scheduler","kind":"core","label_zh":"执行终止操作的调度器"},{"id":"worker","text":"worker","kind":"core","label_zh":"被停止的工作进程"},{"id":"idle","text":"idle","kind":"modifier","label_zh":"说明该进程当时处于空闲状态"},{"id":"expired","text":"expired","kind":"action","label_zh":"租约到达有效期末尾"},{"id":"worker-lease","text":"the worker''s lease","kind":"core","label_zh":"已经失效的进程租约"}],"links":[{"id":"terminated->scheduler","from":"terminated","to":"scheduler","kind":"core","relation_type":"actor","label_zh":"调度器执行了停止操作"},{"id":"terminated->worker","from":"terminated","to":"worker","kind":"core","relation_type":"target","label_zh":"停止操作作用于该工作进程"},{"id":"idle->worker","from":"idle","to":"worker","kind":"modifier","relation_type":"quality","label_zh":"该进程被终止时没有处理任务"},{"id":"expired->worker-lease","from":"expired","to":"worker-lease","kind":"core","relation_type":"actor","label_zh":"到期的是该进程的租约"},{"id":"expired->terminated","from":"expired","to":"terminated","kind":"modifier","relation_type":"time","label_zh":"租约到期后调度器才终止进程"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The scheduler terminated the worker.","sentence_zh":"调度器终止了这个工作进程。","add_node_ids":["terminated","scheduler","worker"],"add_link_ids":["terminated->scheduler","terminated->worker"],"focus_node_id":"terminated","note_zh":"先交代调度器停止了哪个进程。"},{"step_no":2,"label":"对象细节","sentence_en":"The scheduler terminated the idle worker.","sentence_zh":"调度器终止了这个空闲的工作进程。","add_node_ids":["idle"],"add_link_ids":["idle->worker"],"focus_node_id":"idle","note_zh":"说明被停止的进程当时没有工作。"},{"step_no":3,"label":"时间","sentence_en":"The scheduler terminated the idle worker after the worker''s lease expired.","sentence_zh":"该工作进程的租约到期后，调度器终止了这个空闲进程。","add_node_ids":["expired","worker-lease"],"add_link_ids":["expired->worker-lease","expired->terminated"],"focus_node_id":"expired","note_zh":"补充终止操作发生在租约到期之后。"}]}'
  ),
  (
    'test-primary',
    'test',
    'test',
    'test a migration script',
    '测试',
    'Maya tested the migration script.',
    'Maya 测试了迁移脚本。',
    'Maya tested the migration script against a sanitized production snapshot before approving the release.',
    'Maya 使用脱敏的生产数据快照测试了迁移脚本，然后才批准发布。',
    'database-migration',
    '{"schema_version":2,"root_action_id":"tested","nodes":[{"id":"tested","text":"tested","kind":"action","label_zh":"检查脚本能否正确运行"},{"id":"maya","text":"Maya","kind":"core","label_zh":"执行测试并决定是否发布的工程师"},{"id":"migration-script","text":"the migration script","kind":"core","label_zh":"接受检查的迁移脚本"},{"id":"against-snapshot","text":"against a sanitized production snapshot","kind":"modifier","label_zh":"测试所使用的数据样本"},{"id":"approving","text":"approving","kind":"action","label_zh":"允许发布继续进行"},{"id":"release","text":"the release","kind":"core","label_zh":"测试后获得批准的发布"}],"links":[{"id":"tested->maya","from":"tested","to":"maya","kind":"core","relation_type":"actor","label_zh":"Maya负责运行这次测试"},{"id":"tested->migration-script","from":"tested","to":"migration-script","kind":"core","relation_type":"target","label_zh":"测试针对迁移脚本进行"},{"id":"against-snapshot->tested","from":"against-snapshot","to":"tested","kind":"modifier","relation_type":"scope","label_zh":"测试以脱敏的生产快照作为数据样本"},{"id":"approving->release","from":"approving","to":"release","kind":"core","relation_type":"target","label_zh":"批准决定针对这次发布"},{"id":"approving->maya","from":"approving","to":"maya","kind":"core","relation_type":"shared_actor","label_zh":"批准发布的仍是完成测试的Maya"},{"id":"approving->tested","from":"approving","to":"tested","kind":"modifier","relation_type":"sequence","label_zh":"Maya先测试脚本，之后才批准发布"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Maya tested the migration script.","sentence_zh":"Maya 测试了迁移脚本。","add_node_ids":["tested","maya","migration-script"],"add_link_ids":["tested->maya","tested->migration-script"],"focus_node_id":"tested","note_zh":"先说明谁测试了哪个脚本。"},{"step_no":2,"label":"范围","sentence_en":"Maya tested the migration script against a sanitized production snapshot.","sentence_zh":"Maya 使用脱敏的生产数据快照测试了迁移脚本。","add_node_ids":["against-snapshot"],"add_link_ids":["against-snapshot->tested"],"focus_node_id":"against-snapshot","note_zh":"加入测试所依据的数据样本。"},{"step_no":3,"label":"时间","sentence_en":"Maya tested the migration script against a sanitized production snapshot before approving the release.","sentence_zh":"Maya 使用脱敏的生产数据快照测试了迁移脚本，然后才批准发布。","add_node_ids":["approving","release"],"add_link_ids":["approving->release","approving->maya","approving->tested"],"focus_node_id":"approving","note_zh":"说明发布获批之前已经完成了脚本测试。"}]}'
  ),
  (
    'testify-primary',
    'testify',
    'testify',
    'logs testify that',
    '证明；说明事实',
    'The audit logs testify that the admin revoked the token.',
    '审计日志证明管理员撤销了该令牌。',
    'The audit logs testify that the admin revoked the token at 2:14 a.m.',
    '审计日志证明管理员在凌晨两点十四分撤销了该令牌。',
    'security-audit',
    '{"schema_version":2,"root_action_id":"testify","nodes":[{"id":"testify","text":"testify","kind":"action","label_zh":"提供能够确认事实的证据"},{"id":"audit-logs","text":"The audit logs","kind":"core","label_zh":"提供证据的审计日志"},{"id":"revoked","text":"revoked","kind":"action","label_zh":"撤销令牌的有效状态"},{"id":"admin","text":"the admin","kind":"core","label_zh":"执行撤销操作的管理员"},{"id":"token","text":"the token","kind":"core","label_zh":"被管理员撤销的令牌"},{"id":"at-214","text":"at 2:14 a.m.","kind":"modifier","label_zh":"日志记录的具体撤销时间"}],"links":[{"id":"testify->audit-logs","from":"testify","to":"audit-logs","kind":"core","relation_type":"actor","label_zh":"审计日志提供了事实依据"},{"id":"testify->revoked","from":"testify","to":"revoked","kind":"core","relation_type":"content","label_zh":"日志证明的内容是管理员撤销了令牌"},{"id":"revoked->admin","from":"revoked","to":"admin","kind":"core","relation_type":"actor","label_zh":"管理员执行了令牌撤销"},{"id":"revoked->token","from":"revoked","to":"token","kind":"core","relation_type":"target","label_zh":"撤销操作作用于该令牌"},{"id":"at-214->revoked","from":"at-214","to":"revoked","kind":"modifier","relation_type":"time","label_zh":"令牌撤销发生在凌晨两点十四分"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The audit logs testify that the admin revoked the token.","sentence_zh":"审计日志证明管理员撤销了该令牌。","add_node_ids":["testify","audit-logs","revoked","admin","token"],"add_link_ids":["testify->audit-logs","testify->revoked","revoked->admin","revoked->token"],"focus_node_id":"testify","note_zh":"日志所证明的完整事件直接作为内容出现。"},{"step_no":2,"label":"时间","sentence_en":"The audit logs testify that the admin revoked the token at 2:14 a.m.","sentence_zh":"审计日志证明管理员在凌晨两点十四分撤销了该令牌。","add_node_ids":["at-214"],"add_link_ids":["at-214->revoked"],"focus_node_id":"at-214","note_zh":"加入日志能够确认的精确撤销时间。"}]}'
  ),
  (
    'text-primary',
    'text',
    'text',
    'text someone a code',
    '用短信发送',
    'Priya texted me the code.',
    'Priya 用短信把密码发给了我。',
    'Priya texted me the office door code when the courier arrived.',
    '快递员到达时，Priya 用短信把办公室门禁密码发给了我。',
    'office-delivery',
    '{"schema_version":2,"root_action_id":"texted","nodes":[{"id":"texted","text":"texted","kind":"action","label_zh":"通过短信发送信息"},{"id":"priya","text":"Priya","kind":"core","label_zh":"发送短信的人"},{"id":"me","text":"me","kind":"core","label_zh":"收到短信的人"},{"id":"code","text":"code","kind":"core","label_zh":"短信中发送的门禁信息"},{"id":"office-door","text":"office door","kind":"modifier","label_zh":"说明密码用于哪扇门"},{"id":"arrived","text":"arrived","kind":"action","label_zh":"快递员到达现场"},{"id":"courier","text":"the courier","kind":"core","label_zh":"抵达办公室的快递员"}],"links":[{"id":"texted->priya","from":"texted","to":"priya","kind":"core","relation_type":"actor","label_zh":"Priya发出了这条短信"},{"id":"texted->me","from":"texted","to":"me","kind":"core","relation_type":"recipient","label_zh":"短信发送给了我"},{"id":"texted->code","from":"texted","to":"code","kind":"core","relation_type":"content","label_zh":"短信内容是一个门禁密码"},{"id":"office-door->code","from":"office-door","to":"code","kind":"modifier","relation_type":"purpose","label_zh":"这个密码用于打开办公室门"},{"id":"arrived->courier","from":"arrived","to":"courier","kind":"core","relation_type":"actor","label_zh":"到达的人是快递员"},{"id":"arrived->texted","from":"arrived","to":"texted","kind":"modifier","relation_type":"time","label_zh":"快递员抵达时Priya发送了短信"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Priya texted me the code.","sentence_zh":"Priya 用短信把密码发给了我。","add_node_ids":["texted","priya","me","code"],"add_link_ids":["texted->priya","texted->me","texted->code"],"focus_node_id":"texted","note_zh":"先呈现短信的发送者、接收者和内容。"},{"step_no":2,"label":"对象细节","sentence_en":"Priya texted me the office door code.","sentence_zh":"Priya 用短信把办公室门禁密码发给了我。","add_node_ids":["office-door"],"add_link_ids":["office-door->code"],"focus_node_id":"office-door","note_zh":"明确这个密码的具体用途。"},{"step_no":3,"label":"时间","sentence_en":"Priya texted me the office door code when the courier arrived.","sentence_zh":"快递员到达时，Priya 用短信把办公室门禁密码发给了我。","add_node_ids":["arrived","courier"],"add_link_ids":["arrived->courier","arrived->texted"],"focus_node_id":"arrived","note_zh":"用快递员抵达这一事件标出发送时机。"}]}'
  ),
  (
    'thank-primary',
    'thank',
    'thank',
    'thank someone for documenting',
    '因某事感谢某人',
    'I thanked Lena.',
    '我感谢了 Lena。',
    'I thanked Lena for documenting the rollback steps so clearly.',
    '我感谢 Lena 把回滚步骤记录得如此清楚。',
    'incident-review',
    '{"schema_version":2,"root_action_id":"thanked","nodes":[{"id":"thanked","text":"thanked","kind":"action","label_zh":"表达感谢"},{"id":"i","text":"I","kind":"core","label_zh":"表达谢意的人"},{"id":"lena","text":"Lena","kind":"core","label_zh":"受到感谢并完成记录的人"},{"id":"documenting","text":"documenting","kind":"action","label_zh":"把回滚步骤记录下来"},{"id":"rollback-steps","text":"the rollback steps","kind":"core","label_zh":"Lena整理成文档的操作步骤"},{"id":"so-clearly","text":"so clearly","kind":"modifier","label_zh":"说明文档写得十分清楚"}],"links":[{"id":"thanked->i","from":"thanked","to":"i","kind":"core","relation_type":"actor","label_zh":"我表达了感谢"},{"id":"thanked->lena","from":"thanked","to":"lena","kind":"core","relation_type":"target","label_zh":"感谢是向Lena表达的"},{"id":"documenting->rollback-steps","from":"documenting","to":"rollback-steps","kind":"core","relation_type":"target","label_zh":"被记录的是回滚操作步骤"},{"id":"documenting->lena","from":"documenting","to":"lena","kind":"core","relation_type":"shared_actor","label_zh":"完成记录工作的正是受到感谢的Lena"},{"id":"documenting->thanked","from":"documenting","to":"thanked","kind":"modifier","relation_type":"reason","label_zh":"记录回滚步骤是我感谢她的原因"},{"id":"so-clearly->documenting","from":"so-clearly","to":"documenting","kind":"modifier","relation_type":"manner","label_zh":"回滚步骤被记录得非常清晰"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I thanked Lena.","sentence_zh":"我感谢了 Lena。","add_node_ids":["thanked","i","lena"],"add_link_ids":["thanked->i","thanked->lena"],"focus_node_id":"thanked","note_zh":"先说明谢意由谁向谁表达。"},{"step_no":2,"label":"原因","sentence_en":"I thanked Lena for documenting the rollback steps.","sentence_zh":"我感谢 Lena 记录了回滚步骤。","add_node_ids":["documenting","rollback-steps"],"add_link_ids":["documenting->rollback-steps","documenting->lena","documenting->thanked"],"focus_node_id":"documenting","note_zh":"补充值得感谢的具体工作。"},{"step_no":3,"label":"方式","sentence_en":"I thanked Lena for documenting the rollback steps so clearly.","sentence_zh":"我感谢 Lena 把回滚步骤记录得如此清楚。","add_node_ids":["so-clearly"],"add_link_ids":["so-clearly->documenting"],"focus_node_id":"so-clearly","note_zh":"进一步强调这份记录清晰易懂。"}]}'
  ),
  (
    'think-primary',
    'think',
    'think',
    'think a patch fixes something',
    '认为',
    'The reviewers think the patch fixes the race condition.',
    '审查人员认为这个补丁修复了竞态条件。',
    'The reviewers think the patch fixes the race condition without changing public API behavior.',
    '审查人员认为这个补丁修复了竞态条件，同时没有改变公开接口的行为。',
    'code-review',
    '{"schema_version":2,"root_action_id":"think","nodes":[{"id":"think","text":"think","kind":"action","label_zh":"形成对补丁效果的判断"},{"id":"reviewers","text":"The reviewers","kind":"core","label_zh":"作出判断的代码审查人员"},{"id":"fixes","text":"fixes","kind":"action","label_zh":"消除并发问题"},{"id":"patch","text":"the patch","kind":"core","label_zh":"被认为能够解决问题的改动"},{"id":"race-condition","text":"the race condition","kind":"core","label_zh":"补丁要解决的并发缺陷"},{"id":"changing","text":"changing","kind":"action","label_zh":"改变现有接口行为"},{"id":"api-behavior","text":"API behavior","kind":"core","label_zh":"补丁应保持不变的接口表现"},{"id":"public","text":"public","kind":"modifier","label_zh":"说明该接口行为对外部使用者可见"}],"links":[{"id":"think->reviewers","from":"think","to":"reviewers","kind":"core","relation_type":"actor","label_zh":"审查人员持有这一判断"},{"id":"think->fixes","from":"think","to":"fixes","kind":"core","relation_type":"content","label_zh":"判断的内容是补丁能够修复问题"},{"id":"fixes->patch","from":"fixes","to":"patch","kind":"core","relation_type":"actor","label_zh":"发挥修复作用的是该补丁"},{"id":"fixes->race-condition","from":"fixes","to":"race-condition","kind":"core","relation_type":"target","label_zh":"补丁解决的是竞态条件"},{"id":"changing->api-behavior","from":"changing","to":"api-behavior","kind":"core","relation_type":"target","label_zh":"可能受到改变的是接口行为"},{"id":"changing->patch","from":"changing","to":"patch","kind":"core","relation_type":"shared_actor","label_zh":"可能改变接口行为的也是该补丁"},{"id":"changing->fixes","from":"changing","to":"fixes","kind":"modifier","relation_type":"manner","label_zh":"补丁在不改变接口行为的情况下完成修复"},{"id":"public->api-behavior","from":"public","to":"api-behavior","kind":"modifier","relation_type":"scope","label_zh":"保持不变的是对外公开的接口行为"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The reviewers think the patch fixes the race condition.","sentence_zh":"审查人员认为这个补丁修复了竞态条件。","add_node_ids":["think","reviewers","fixes","patch","race-condition"],"add_link_ids":["think->reviewers","think->fixes","fixes->patch","fixes->race-condition"],"focus_node_id":"think","note_zh":"判断的内容由一个完整的修复事件构成。"},{"step_no":2,"label":"方式","sentence_en":"The reviewers think the patch fixes the race condition without changing API behavior.","sentence_zh":"审查人员认为这个补丁修复了竞态条件，同时没有改变接口行为。","add_node_ids":["changing","api-behavior"],"add_link_ids":["changing->api-behavior","changing->patch","changing->fixes"],"focus_node_id":"changing","note_zh":"说明补丁完成修复时避免了什么副作用。"},{"step_no":3,"label":"范围","sentence_en":"The reviewers think the patch fixes the race condition without changing public API behavior.","sentence_zh":"审查人员认为这个补丁修复了竞态条件，同时没有改变公开接口的行为。","add_node_ids":["public"],"add_link_ids":["public->api-behavior"],"focus_node_id":"public","note_zh":"把需要保持稳定的范围限定为公开接口。"}]}'
  ),
  (
    'think-over-primary',
    'think-over',
    'think over',
    'think over a proposal',
    '仔细考虑',
    'Nora thought over the proposal.',
    'Nora 仔细考虑了这份方案。',
    'Nora thought over the vendor''s revised proposal during her train ride home.',
    'Nora 在乘火车回家时仔细考虑了供应商修改后的方案。',
    'vendor-selection',
    '{"schema_version":2,"root_action_id":"thought-over","nodes":[{"id":"thought-over","text":"thought over","kind":"action","label_zh":"认真权衡方案内容"},{"id":"nora","text":"Nora","kind":"core","label_zh":"仔细考虑方案的人"},{"id":"proposal","text":"proposal","kind":"core","label_zh":"接受权衡的方案"},{"id":"revised","text":"revised","kind":"modifier","label_zh":"说明方案已经经过修改"},{"id":"vendor","text":"the vendor''s","kind":"modifier","label_zh":"指出方案由供应商提出"},{"id":"during-train-ride","text":"during her train ride home","kind":"modifier","label_zh":"Nora进行考虑的时间场景"}],"links":[{"id":"thought-over->nora","from":"thought-over","to":"nora","kind":"core","relation_type":"actor","label_zh":"Nora进行了细致权衡"},{"id":"thought-over->proposal","from":"thought-over","to":"proposal","kind":"core","relation_type":"target","label_zh":"她权衡的是这份方案"},{"id":"revised->proposal","from":"revised","to":"proposal","kind":"modifier","relation_type":"quality","label_zh":"这份方案是修改后的版本"},{"id":"vendor->proposal","from":"vendor","to":"proposal","kind":"modifier","relation_type":"ownership","label_zh":"方案来自正在评估的供应商"},{"id":"during-train-ride->thought-over","from":"during-train-ride","to":"thought-over","kind":"modifier","relation_type":"time","label_zh":"她在乘火车回家时考虑方案"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Nora thought over the proposal.","sentence_zh":"Nora 仔细考虑了这份方案。","add_node_ids":["thought-over","nora","proposal"],"add_link_ids":["thought-over->nora","thought-over->proposal"],"focus_node_id":"thought-over","note_zh":"先表达Nora对方案进行了认真权衡。"},{"step_no":2,"label":"对象细节","sentence_en":"Nora thought over the revised proposal.","sentence_zh":"Nora 仔细考虑了修改后的方案。","add_node_ids":["revised"],"add_link_ids":["revised->proposal"],"focus_node_id":"revised","note_zh":"说明她评估的是已经修改过的版本。"},{"step_no":3,"label":"对象细节","sentence_en":"Nora thought over the vendor''s revised proposal.","sentence_zh":"Nora 仔细考虑了供应商修改后的方案。","add_node_ids":["vendor"],"add_link_ids":["vendor->proposal"],"focus_node_id":"vendor","note_zh":"明确这份方案来自供应商。"},{"step_no":4,"label":"场景","sentence_en":"Nora thought over the vendor''s revised proposal during her train ride home.","sentence_zh":"Nora 在乘火车回家时仔细考虑了供应商修改后的方案。","add_node_ids":["during-train-ride"],"add_link_ids":["during-train-ride->thought-over"],"focus_node_id":"during-train-ride","note_zh":"加入她进行这番考虑的日常场景。"}]}'
  ),
  (
    'think-through-primary',
    'think-through',
    'think through',
    'think through a response',
    '全面考虑并想清楚',
    'We thought through the outage response.',
    '我们全面推演了故障应对方案。',
    'We thought through the outage response before enabling automatic failover.',
    '我们全面推演了故障应对方案，然后才启用自动故障切换。',
    'outage-planning',
    '{"schema_version":2,"root_action_id":"thought-through","nodes":[{"id":"thought-through","text":"thought through","kind":"action","label_zh":"系统地推演处理方案"},{"id":"we","text":"We","kind":"core","label_zh":"共同推演并启用切换的团队"},{"id":"outage-response","text":"the outage response","kind":"core","label_zh":"被完整推演的故障应对方案"},{"id":"enabling","text":"enabling","kind":"action","label_zh":"开启故障自动切换功能"},{"id":"failover","text":"failover","kind":"core","label_zh":"随后被启用的切换机制"},{"id":"automatic","text":"automatic","kind":"modifier","label_zh":"说明切换不需要人工触发"}],"links":[{"id":"thought-through->we","from":"thought-through","to":"we","kind":"core","relation_type":"actor","label_zh":"团队完成了全面推演"},{"id":"thought-through->outage-response","from":"thought-through","to":"outage-response","kind":"core","relation_type":"target","label_zh":"推演围绕故障应对方案展开"},{"id":"enabling->failover","from":"enabling","to":"failover","kind":"core","relation_type":"target","label_zh":"被开启的是故障切换机制"},{"id":"enabling->we","from":"enabling","to":"we","kind":"core","relation_type":"shared_actor","label_zh":"启用机制的仍是完成推演的团队"},{"id":"enabling->thought-through","from":"enabling","to":"thought-through","kind":"modifier","relation_type":"sequence","label_zh":"团队先想透应对方案，再启用切换"},{"id":"automatic->failover","from":"automatic","to":"failover","kind":"modifier","relation_type":"quality","label_zh":"该切换机制会自动运行"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We thought through the outage response.","sentence_zh":"我们全面推演了故障应对方案。","add_node_ids":["thought-through","we","outage-response"],"add_link_ids":["thought-through->we","thought-through->outage-response"],"focus_node_id":"thought-through","note_zh":"先说明团队把应对方案完整地想了一遍。"},{"step_no":2,"label":"时间","sentence_en":"We thought through the outage response before enabling failover.","sentence_zh":"我们全面推演了故障应对方案，然后才启用故障切换。","add_node_ids":["enabling","failover"],"add_link_ids":["enabling->failover","enabling->we","enabling->thought-through"],"focus_node_id":"enabling","note_zh":"表明启用切换前必须先完成推演。"},{"step_no":3,"label":"对象细节","sentence_en":"We thought through the outage response before enabling automatic failover.","sentence_zh":"我们全面推演了故障应对方案，然后才启用自动故障切换。","add_node_ids":["automatic"],"add_link_ids":["automatic->failover"],"focus_node_id":"automatic","note_zh":"明确随后开启的是自动切换机制。"}]}'
  ),
  (
    'threaten-primary',
    'threaten',
    'threaten',
    'threaten to crash workers',
    '可能导致严重后果；危及',
    'A cache entry threatened to crash every worker.',
    '一条缓存记录可能导致所有工作进程崩溃。',
    'A malformed cache entry threatened to crash every worker in the region.',
    '一条格式错误的缓存记录可能导致该区域内的所有工作进程崩溃。',
    'cache-corruption',
    '{"schema_version":2,"root_action_id":"threatened","nodes":[{"id":"threatened","text":"threatened","kind":"action","label_zh":"带来即将发生故障的风险"},{"id":"cache-entry","text":"A cache entry","kind":"core","label_zh":"造成崩溃风险的缓存记录"},{"id":"crash","text":"crash","kind":"action","label_zh":"使工作进程停止运行"},{"id":"workers","text":"every worker","kind":"core","label_zh":"可能全部崩溃的工作进程"},{"id":"malformed","text":"malformed","kind":"modifier","label_zh":"说明缓存记录的格式不正确"},{"id":"in-region","text":"in the region","kind":"modifier","label_zh":"可能受影响的工作进程所在范围"}],"links":[{"id":"threatened->cache-entry","from":"threatened","to":"cache-entry","kind":"core","relation_type":"actor","label_zh":"缓存记录带来了故障风险"},{"id":"threatened->crash","from":"threatened","to":"crash","kind":"core","relation_type":"nested_action","label_zh":"风险的具体后果是工作进程崩溃"},{"id":"crash->workers","from":"crash","to":"workers","kind":"core","relation_type":"target","label_zh":"崩溃风险波及每个工作进程"},{"id":"crash->cache-entry","from":"crash","to":"cache-entry","kind":"core","relation_type":"shared_actor","label_zh":"可能导致进程崩溃的也是该缓存记录"},{"id":"malformed->cache-entry","from":"malformed","to":"cache-entry","kind":"modifier","relation_type":"quality","label_zh":"缓存记录因格式错误而具有风险"},{"id":"in-region->workers","from":"in-region","to":"workers","kind":"modifier","relation_type":"scope","label_zh":"受威胁的是该区域内的全部进程"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A cache entry threatened to crash every worker.","sentence_zh":"一条缓存记录可能导致所有工作进程崩溃。","add_node_ids":["threatened","cache-entry","crash","workers"],"add_link_ids":["threatened->cache-entry","threatened->crash","crash->workers","crash->cache-entry"],"focus_node_id":"threatened","note_zh":"把风险及其可能造成的崩溃后果一起呈现。"},{"step_no":2,"label":"原因","sentence_en":"A malformed cache entry threatened to crash every worker.","sentence_zh":"一条格式错误的缓存记录可能导致所有工作进程崩溃。","add_node_ids":["malformed"],"add_link_ids":["malformed->cache-entry"],"focus_node_id":"malformed","note_zh":"指出风险来自记录格式异常。"},{"step_no":3,"label":"范围","sentence_en":"A malformed cache entry threatened to crash every worker in the region.","sentence_zh":"一条格式错误的缓存记录可能导致该区域内的所有工作进程崩溃。","add_node_ids":["in-region"],"add_link_ids":["in-region->workers"],"focus_node_id":"in-region","note_zh":"补充潜在影响覆盖的部署区域。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'thrive-primary',
    'thrive',
    'thrive',
    'a team thrives',
    '发展良好；表现出色',
    'The team thrived.',
    '这个团队发展得很好。',
    'The support team thrived after rotating on-call duties across three time zones.',
    '在三个时区之间轮换值班任务后，这个支持团队发展得很好。',
    'distributed-support',
    '{"schema_version":2,"root_action_id":"thrived","nodes":[{"id":"thrived","text":"thrived","kind":"action","label_zh":"团队保持高效并发展良好"},{"id":"team","text":"team","kind":"core","label_zh":"表现越来越好的团队"},{"id":"support","text":"support","kind":"modifier","label_zh":"说明团队负责客户支持工作"},{"id":"rotating","text":"rotating","kind":"action","label_zh":"轮换值班任务"},{"id":"on-call-duties","text":"on-call duties","kind":"core","label_zh":"在成员之间轮换的值班工作"},{"id":"across-zones","text":"across three time zones","kind":"modifier","label_zh":"值班轮换覆盖的时区范围"}],"links":[{"id":"thrived->team","from":"thrived","to":"team","kind":"core","relation_type":"actor","label_zh":"发展良好的是这个团队"},{"id":"support->team","from":"support","to":"team","kind":"modifier","relation_type":"category","label_zh":"该团队承担支持工作"},{"id":"rotating->on-call-duties","from":"rotating","to":"on-call-duties","kind":"core","relation_type":"target","label_zh":"轮换安排针对值班任务"},{"id":"rotating->team","from":"rotating","to":"team","kind":"core","relation_type":"shared_actor","label_zh":"实施值班轮换的也是这个支持团队"},{"id":"rotating->thrived","from":"rotating","to":"thrived","kind":"modifier","relation_type":"time","label_zh":"实行轮换后团队开始表现良好"},{"id":"across-zones->rotating","from":"across-zones","to":"rotating","kind":"modifier","relation_type":"scope","label_zh":"轮换安排跨越三个时区"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team thrived.","sentence_zh":"这个团队发展得很好。","add_node_ids":["thrived","team"],"add_link_ids":["thrived->team"],"focus_node_id":"thrived","note_zh":"先表达团队整体表现良好。"},{"step_no":2,"label":"对象细节","sentence_en":"The support team thrived.","sentence_zh":"这个支持团队发展得很好。","add_node_ids":["support"],"add_link_ids":["support->team"],"focus_node_id":"support","note_zh":"明确这是负责支持工作的团队。"},{"step_no":3,"label":"时间","sentence_en":"The support team thrived after rotating on-call duties.","sentence_zh":"轮换值班任务后，这个支持团队发展得很好。","add_node_ids":["rotating","on-call-duties"],"add_link_ids":["rotating->on-call-duties","rotating->team","rotating->thrived"],"focus_node_id":"rotating","note_zh":"加入团队改善值班安排这一背景。"},{"step_no":4,"label":"范围","sentence_en":"The support team thrived after rotating on-call duties across three time zones.","sentence_zh":"在三个时区之间轮换值班任务后，这个支持团队发展得很好。","add_node_ids":["across-zones"],"add_link_ids":["across-zones->rotating"],"focus_node_id":"across-zones","note_zh":"说明轮换安排覆盖了三个时区。"}]}'
  ),
  (
    'throttle-primary',
    'throttle',
    'throttle',
    'throttle incoming requests',
    '限制请求速率',
    'The gateway throttled requests.',
    '网关限制了请求速率。',
    'The gateway throttled anonymous requests to twenty per second during the launch.',
    '产品发布期间，网关把匿名请求限制为每秒二十次。',
    'api-launch',
    '{"schema_version":2,"root_action_id":"throttled","nodes":[{"id":"throttled","text":"throttled","kind":"action","label_zh":"限制请求进入系统的速度"},{"id":"gateway","text":"The gateway","kind":"core","label_zh":"执行限速的网关"},{"id":"requests","text":"requests","kind":"core","label_zh":"受到速率限制的请求"},{"id":"anonymous","text":"anonymous","kind":"modifier","label_zh":"说明请求没有登录身份"},{"id":"to-twenty","text":"to twenty per second","kind":"modifier","label_zh":"网关允许的最高请求速率"},{"id":"during-launch","text":"during the launch","kind":"modifier","label_zh":"实施限速的产品发布阶段"}],"links":[{"id":"throttled->gateway","from":"throttled","to":"gateway","kind":"core","relation_type":"actor","label_zh":"网关执行了请求限速"},{"id":"throttled->requests","from":"throttled","to":"requests","kind":"core","relation_type":"target","label_zh":"限速措施作用于进入的请求"},{"id":"anonymous->requests","from":"anonymous","to":"requests","kind":"modifier","relation_type":"category","label_zh":"受限制的是未认证请求"},{"id":"to-twenty->throttled","from":"to-twenty","to":"throttled","kind":"modifier","relation_type":"degree","label_zh":"请求速率被控制在每秒二十次"},{"id":"during-launch->throttled","from":"during-launch","to":"throttled","kind":"modifier","relation_type":"time","label_zh":"限速措施在发布期间生效"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The gateway throttled requests.","sentence_zh":"网关限制了请求速率。","add_node_ids":["throttled","gateway","requests"],"add_link_ids":["throttled->gateway","throttled->requests"],"focus_node_id":"throttled","note_zh":"先说明网关对请求进行了限速。"},{"step_no":2,"label":"范围","sentence_en":"The gateway throttled anonymous requests.","sentence_zh":"网关限制了匿名请求的速率。","add_node_ids":["anonymous"],"add_link_ids":["anonymous->requests"],"focus_node_id":"anonymous","note_zh":"限定速率控制针对未认证流量。"},{"step_no":3,"label":"程度","sentence_en":"The gateway throttled anonymous requests to twenty per second.","sentence_zh":"网关把匿名请求限制为每秒二十次。","add_node_ids":["to-twenty"],"add_link_ids":["to-twenty->throttled"],"focus_node_id":"to-twenty","note_zh":"给出网关实际执行的速率上限。"},{"step_no":4,"label":"时间","sentence_en":"The gateway throttled anonymous requests to twenty per second during the launch.","sentence_zh":"产品发布期间，网关把匿名请求限制为每秒二十次。","add_node_ids":["during-launch"],"add_link_ids":["during-launch->throttled"],"focus_node_id":"during-launch","note_zh":"说明这项限速措施在哪个阶段启用。"}]}'
  ),
  (
    'throw-error',
    'throw',
    'throw',
    'throw an error',
    '抛出错误',
    'The parser throws an error.',
    '解析器会抛出错误。',
    'The parser throws a descriptive error when the header contains an invalid timestamp.',
    '当请求头包含无效时间戳时，解析器会抛出一条描述清楚的错误。',
    'header-parsing',
    '{"schema_version":2,"root_action_id":"throws","nodes":[{"id":"throws","text":"throws","kind":"action","label_zh":"产生并报告程序错误"},{"id":"parser","text":"The parser","kind":"core","label_zh":"报告错误的解析器"},{"id":"error","text":"error","kind":"core","label_zh":"解析器产生的错误信息"},{"id":"descriptive","text":"descriptive","kind":"modifier","label_zh":"说明错误信息清楚描述了问题"},{"id":"contains","text":"contains","kind":"action","label_zh":"请求头中带有某项内容"},{"id":"header","text":"the header","kind":"core","label_zh":"包含时间戳的请求头"},{"id":"timestamp","text":"timestamp","kind":"core","label_zh":"导致解析失败的时间信息"},{"id":"invalid","text":"invalid","kind":"modifier","label_zh":"说明时间戳格式或取值不合法"}],"links":[{"id":"throws->parser","from":"throws","to":"parser","kind":"core","relation_type":"actor","label_zh":"解析器负责产生错误"},{"id":"throws->error","from":"throws","to":"error","kind":"core","relation_type":"target","label_zh":"解析失败时产生一条错误信息"},{"id":"descriptive->error","from":"descriptive","to":"error","kind":"modifier","relation_type":"quality","label_zh":"这条错误信息能够说明具体问题"},{"id":"contains->header","from":"contains","to":"header","kind":"core","relation_type":"actor","label_zh":"请求头携带了时间戳"},{"id":"contains->timestamp","from":"contains","to":"timestamp","kind":"core","relation_type":"target","label_zh":"请求头中包含的是时间戳"},{"id":"contains->throws","from":"contains","to":"throws","kind":"modifier","relation_type":"condition","label_zh":"请求头包含这种时间戳时解析器会报错"},{"id":"invalid->timestamp","from":"invalid","to":"timestamp","kind":"modifier","relation_type":"quality","label_zh":"触发错误的是不合法的时间戳"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The parser throws an error.","sentence_zh":"解析器会抛出错误。","add_node_ids":["throws","parser","error"],"add_link_ids":["throws->parser","throws->error"],"focus_node_id":"throws","note_zh":"先呈现解析器报告错误这一核心行为。"},{"step_no":2,"label":"对象细节","sentence_en":"The parser throws a descriptive error.","sentence_zh":"解析器会抛出一条描述清楚的错误。","add_node_ids":["descriptive"],"add_link_ids":["descriptive->error"],"focus_node_id":"descriptive","note_zh":"说明错误信息能够帮助定位问题。"},{"step_no":3,"label":"条件","sentence_en":"The parser throws a descriptive error when the header contains a timestamp.","sentence_zh":"当请求头包含时间戳时，解析器会抛出一条描述清楚的错误。","add_node_ids":["contains","header","timestamp"],"add_link_ids":["contains->header","contains->timestamp","contains->throws"],"focus_node_id":"contains","note_zh":"加入解析器产生错误时检查到的内容。"},{"step_no":4,"label":"对象细节","sentence_en":"The parser throws a descriptive error when the header contains an invalid timestamp.","sentence_zh":"当请求头包含无效时间戳时，解析器会抛出一条描述清楚的错误。","add_node_ids":["invalid"],"add_link_ids":["invalid->timestamp"],"focus_node_id":"invalid","note_zh":"明确只有不合法的时间戳会触发该错误。"}]}'
  ),
  (
    'throw-away-primary',
    'throw-away',
    'throw away',
    'throw away old snapshots',
    '删除不再需要的内容',
    'The retention job threw away snapshots.',
    '保留策略任务删除了快照。',
    'The retention job threw away duplicate snapshots older than thirty days.',
    '保留策略任务删除了保存超过三十天的重复快照。',
    'snapshot-retention',
    '{"schema_version":2,"root_action_id":"threw-away","nodes":[{"id":"threw-away","text":"threw away","kind":"action","label_zh":"移除不再需要的快照"},{"id":"job","text":"job","kind":"core","label_zh":"执行清理操作的自动任务"},{"id":"snapshots","text":"snapshots","kind":"core","label_zh":"被自动任务删除的数据快照"},{"id":"retention","text":"retention","kind":"modifier","label_zh":"说明该任务负责执行保留策略"},{"id":"duplicate","text":"duplicate","kind":"modifier","label_zh":"说明被清理的快照内容重复"},{"id":"older-than-thirty-days","text":"older than thirty days","kind":"modifier","label_zh":"快照被清理前必须超过的保存期限"}],"links":[{"id":"threw-away->job","from":"threw-away","to":"job","kind":"core","relation_type":"actor","label_zh":"自动任务执行了删除操作"},{"id":"threw-away->snapshots","from":"threw-away","to":"snapshots","kind":"core","relation_type":"target","label_zh":"删除操作作用于数据快照"},{"id":"retention->job","from":"retention","to":"job","kind":"modifier","relation_type":"purpose","label_zh":"这个任务用于落实数据保留规则"},{"id":"duplicate->snapshots","from":"duplicate","to":"snapshots","kind":"modifier","relation_type":"quality","label_zh":"被删除的是内容重复的快照"},{"id":"older-than-thirty-days->snapshots","from":"older-than-thirty-days","to":"snapshots","kind":"modifier","relation_type":"time","label_zh":"这些快照已经保存超过三十天"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The retention job threw away snapshots.","sentence_zh":"保留策略任务删除了快照。","add_node_ids":["threw-away","job","snapshots","retention"],"add_link_ids":["threw-away->job","threw-away->snapshots","retention->job"],"focus_node_id":"threw-away","note_zh":"先说明保留策略任务清理了数据快照。"},{"step_no":2,"label":"对象细节","sentence_en":"The retention job threw away duplicate snapshots.","sentence_zh":"保留策略任务删除了重复快照。","add_node_ids":["duplicate"],"add_link_ids":["duplicate->snapshots"],"focus_node_id":"duplicate","note_zh":"限定任务清理的是重复数据。"},{"step_no":3,"label":"时间","sentence_en":"The retention job threw away duplicate snapshots older than thirty days.","sentence_zh":"保留策略任务删除了保存超过三十天的重复快照。","add_node_ids":["older-than-thirty-days"],"add_link_ids":["older-than-thirty-days->snapshots"],"focus_node_id":"older-than-thirty-days","note_zh":"加入快照必须达到的保存时长。"}]}'
  ),
  (
    'throw-out-primary',
    'throw-out',
    'throw out',
    'throw out benchmark results',
    '否决；弃用',
    'The team threw out the results.',
    '团队弃用了这些结果。',
    'The team threw out the benchmark results because the test excluded mobile devices.',
    '由于测试遗漏了移动设备，团队弃用了这些基准测试结果。',
    'performance-review',
    '{"schema_version":2,"root_action_id":"threw-out","nodes":[{"id":"threw-out","text":"threw out","kind":"action","label_zh":"决定不采用一组结果"},{"id":"team","text":"The team","kind":"core","label_zh":"作出弃用决定的团队"},{"id":"results","text":"results","kind":"core","label_zh":"被判定不能采用的数据结果"},{"id":"benchmark","text":"benchmark","kind":"modifier","label_zh":"说明这些结果来自性能测试"},{"id":"excluded","text":"excluded","kind":"action","label_zh":"测试没有覆盖某类设备"},{"id":"test","text":"the test","kind":"core","label_zh":"产生数据覆盖问题的测试"},{"id":"devices","text":"devices","kind":"core","label_zh":"未被测试纳入的设备"},{"id":"mobile","text":"mobile","kind":"modifier","label_zh":"说明遗漏的是移动设备"}],"links":[{"id":"threw-out->team","from":"threw-out","to":"team","kind":"core","relation_type":"actor","label_zh":"团队决定弃用这些结果"},{"id":"threw-out->results","from":"threw-out","to":"results","kind":"core","relation_type":"target","label_zh":"弃用决定针对这组数据结果"},{"id":"benchmark->results","from":"benchmark","to":"results","kind":"modifier","relation_type":"category","label_zh":"这些数据是基准测试结果"},{"id":"excluded->test","from":"excluded","to":"test","kind":"core","relation_type":"actor","label_zh":"该测试遗漏了部分设备"},{"id":"excluded->devices","from":"excluded","to":"devices","kind":"core","relation_type":"target","label_zh":"未进入测试范围的是这些设备"},{"id":"excluded->threw-out","from":"excluded","to":"threw-out","kind":"modifier","relation_type":"reason","label_zh":"设备覆盖不完整导致团队弃用结果"},{"id":"mobile->devices","from":"mobile","to":"devices","kind":"modifier","relation_type":"category","label_zh":"遗漏的设备属于移动端"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The team threw out the results.","sentence_zh":"团队弃用了这些结果。","add_node_ids":["threw-out","team","results"],"add_link_ids":["threw-out->team","threw-out->results"],"focus_node_id":"threw-out","note_zh":"先说明团队决定不采用一组结果。"},{"step_no":2,"label":"对象细节","sentence_en":"The team threw out the benchmark results.","sentence_zh":"团队弃用了这些基准测试结果。","add_node_ids":["benchmark"],"add_link_ids":["benchmark->results"],"focus_node_id":"benchmark","note_zh":"明确被弃用的是性能测试数据。"},{"step_no":3,"label":"原因","sentence_en":"The team threw out the benchmark results because the test excluded devices.","sentence_zh":"由于测试遗漏了部分设备，团队弃用了这些基准测试结果。","add_node_ids":["excluded","test","devices"],"add_link_ids":["excluded->test","excluded->devices","excluded->threw-out"],"focus_node_id":"excluded","note_zh":"补充结果不能采用的覆盖问题。"},{"step_no":4,"label":"范围","sentence_en":"The team threw out the benchmark results because the test excluded mobile devices.","sentence_zh":"由于测试遗漏了移动设备，团队弃用了这些基准测试结果。","add_node_ids":["mobile"],"add_link_ids":["mobile->devices"],"focus_node_id":"mobile","note_zh":"具体指出测试遗漏了哪类设备。"}]}'
  ),
  (
    'tie-up-primary',
    'tie-up',
    'tie up',
    'tie up database replicas',
    '长时间占用',
    'A full database scan tied up two replicas.',
    '一次完整的数据库扫描占用了两个副本。',
    'A full database scan tied up two replicas for nearly an hour.',
    '一次完整的数据库扫描占用了两个副本将近一小时。',
    'database-capacity',
    '{"schema_version":2,"root_action_id":"tied-up","nodes":[{"id":"tied-up","text":"tied up","kind":"action","label_zh":"持续占用系统资源"},{"id":"scan","text":"A full database scan","kind":"core","label_zh":"造成资源占用的全库扫描"},{"id":"replicas","text":"two replicas","kind":"core","label_zh":"被扫描任务占用的两个副本"},{"id":"for-an-hour","text":"for nearly an hour","kind":"modifier","label_zh":"两个副本持续被占用的时长"}],"links":[{"id":"tied-up->scan","from":"tied-up","to":"scan","kind":"core","relation_type":"actor","label_zh":"全库扫描造成了资源占用"},{"id":"tied-up->replicas","from":"tied-up","to":"replicas","kind":"core","relation_type":"target","label_zh":"扫描持续占用了两个数据库副本"},{"id":"for-an-hour->tied-up","from":"for-an-hour","to":"tied-up","kind":"modifier","relation_type":"time","label_zh":"资源占用持续了接近一小时"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A full database scan tied up two replicas.","sentence_zh":"一次完整的数据库扫描占用了两个副本。","add_node_ids":["tied-up","scan","replicas"],"add_link_ids":["tied-up->scan","tied-up->replicas"],"focus_node_id":"tied-up","note_zh":"直接说明扫描任务占用了哪些数据库资源。"},{"step_no":2,"label":"时间","sentence_en":"A full database scan tied up two replicas for nearly an hour.","sentence_zh":"一次完整的数据库扫描占用了两个副本将近一小时。","add_node_ids":["for-an-hour"],"add_link_ids":["for-an-hour->tied-up"],"focus_node_id":"for-an-hour","note_zh":"补充资源无法用于其他工作的持续时间。"}]}'
  ),
  (
    'tighten-primary',
    'tighten',
    'tighten',
    'tighten deployment permissions',
    '加强限制；收紧',
    'We tightened permissions.',
    '我们收紧了权限。',
    'We tightened deployment permissions after a contractor exposed the staging key.',
    '一名承包人员泄露预发布环境密钥后，我们收紧了部署权限。',
    'access-control',
    '{"schema_version":2,"root_action_id":"tightened","nodes":[{"id":"tightened","text":"tightened","kind":"action","label_zh":"让访问限制更加严格"},{"id":"we","text":"We","kind":"core","label_zh":"调整权限规则的团队"},{"id":"permissions","text":"permissions","kind":"core","label_zh":"被收紧的访问权限"},{"id":"deployment","text":"deployment","kind":"modifier","label_zh":"说明权限控制的是部署操作"},{"id":"exposed","text":"exposed","kind":"action","label_zh":"意外泄露敏感密钥"},{"id":"contractor","text":"a contractor","kind":"core","label_zh":"造成密钥泄露的外部人员"},{"id":"key","text":"the key","kind":"core","label_zh":"被意外公开的敏感密钥"},{"id":"staging","text":"staging","kind":"modifier","label_zh":"说明密钥用于预发布环境"}],"links":[{"id":"tightened->we","from":"tightened","to":"we","kind":"core","relation_type":"actor","label_zh":"团队实施了更严格的限制"},{"id":"tightened->permissions","from":"tightened","to":"permissions","kind":"core","relation_type":"target","label_zh":"调整针对访问权限进行"},{"id":"deployment->permissions","from":"deployment","to":"permissions","kind":"modifier","relation_type":"scope","label_zh":"这些权限决定谁能执行部署"},{"id":"exposed->contractor","from":"exposed","to":"contractor","kind":"core","relation_type":"actor","label_zh":"一名承包人员泄露了密钥"},{"id":"exposed->key","from":"exposed","to":"key","kind":"core","relation_type":"target","label_zh":"遭到泄露的是环境密钥"},{"id":"exposed->tightened","from":"exposed","to":"tightened","kind":"modifier","relation_type":"time","label_zh":"密钥泄露后团队收紧了权限"},{"id":"staging->key","from":"staging","to":"key","kind":"modifier","relation_type":"purpose","label_zh":"这把密钥用于预发布环境"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We tightened permissions.","sentence_zh":"我们收紧了权限。","add_node_ids":["tightened","we","permissions"],"add_link_ids":["tightened->we","tightened->permissions"],"focus_node_id":"tightened","note_zh":"先表达团队让权限规则更加严格。"},{"step_no":2,"label":"范围","sentence_en":"We tightened deployment permissions.","sentence_zh":"我们收紧了部署权限。","add_node_ids":["deployment"],"add_link_ids":["deployment->permissions"],"focus_node_id":"deployment","note_zh":"明确调整针对部署操作。"},{"step_no":3,"label":"时间","sentence_en":"We tightened deployment permissions after a contractor exposed the key.","sentence_zh":"一名承包人员泄露密钥后，我们收紧了部署权限。","add_node_ids":["exposed","contractor","key"],"add_link_ids":["exposed->contractor","exposed->key","exposed->tightened"],"focus_node_id":"exposed","note_zh":"加入促使团队调整权限的安全事件。"},{"step_no":4,"label":"对象细节","sentence_en":"We tightened deployment permissions after a contractor exposed the staging key.","sentence_zh":"一名承包人员泄露预发布环境密钥后，我们收紧了部署权限。","add_node_ids":["staging"],"add_link_ids":["staging->key"],"focus_node_id":"staging","note_zh":"说明被泄露的密钥属于哪个环境。"}]}'
  ),
  (
    'time-primary',
    'time',
    'time',
    'time a backup',
    '测量所需时间',
    'Elena timed the backup.',
    'Elena 测量了备份所需的时间。',
    'Elena timed the backup during peak traffic to estimate its user impact.',
    'Elena 在流量高峰期测量了备份耗时，以评估它对使用者的影响。',
    'backup-performance',
    '{"schema_version":2,"root_action_id":"timed","nodes":[{"id":"timed","text":"timed","kind":"action","label_zh":"测量备份完成所需时间"},{"id":"elena","text":"Elena","kind":"core","label_zh":"记录耗时并评估影响的工程师"},{"id":"backup","text":"the backup","kind":"core","label_zh":"接受计时的备份过程"},{"id":"during-peak-traffic","text":"during peak traffic","kind":"modifier","label_zh":"进行计时测试时的负载场景"},{"id":"estimate","text":"estimate","kind":"action","label_zh":"评估备份对使用者的影响"},{"id":"user-impact","text":"its user impact","kind":"core","label_zh":"需要根据耗时估算的使用者影响"}],"links":[{"id":"timed->elena","from":"timed","to":"elena","kind":"core","relation_type":"actor","label_zh":"Elena负责测量备份耗时"},{"id":"timed->backup","from":"timed","to":"backup","kind":"core","relation_type":"target","label_zh":"计时针对备份过程进行"},{"id":"during-peak-traffic->timed","from":"during-peak-traffic","to":"timed","kind":"modifier","relation_type":"time","label_zh":"计时发生在系统流量高峰期"},{"id":"estimate->user-impact","from":"estimate","to":"user-impact","kind":"core","relation_type":"target","label_zh":"评估关注备份对使用者的影响"},{"id":"estimate->elena","from":"estimate","to":"elena","kind":"core","relation_type":"shared_actor","label_zh":"进行影响评估的仍是Elena"},{"id":"estimate->timed","from":"estimate","to":"timed","kind":"modifier","relation_type":"purpose","label_zh":"测量耗时是为了评估实际影响"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Elena timed the backup.","sentence_zh":"Elena 测量了备份所需的时间。","add_node_ids":["timed","elena","backup"],"add_link_ids":["timed->elena","timed->backup"],"focus_node_id":"timed","note_zh":"先说明Elena对备份过程进行了计时。"},{"step_no":2,"label":"场景","sentence_en":"Elena timed the backup during peak traffic.","sentence_zh":"Elena 在流量高峰期测量了备份所需的时间。","add_node_ids":["during-peak-traffic"],"add_link_ids":["during-peak-traffic->timed"],"focus_node_id":"during-peak-traffic","note_zh":"补充计时测试所处的高负载场景。"},{"step_no":3,"label":"目的","sentence_en":"Elena timed the backup during peak traffic to estimate its user impact.","sentence_zh":"Elena 在流量高峰期测量了备份耗时，以评估它对使用者的影响。","add_node_ids":["estimate","user-impact"],"add_link_ids":["estimate->user-impact","estimate->elena","estimate->timed"],"focus_node_id":"estimate","note_zh":"说明测量耗时是为了判断备份的实际影响。"}]}'
  ),
  (
    'timeout-primary',
    'timeout',
    'time out',
    'an upload times out',
    '因等待过久而超时',
    'The upload timed out.',
    '上传任务超时了。',
    'The upload timed out after the proxy closed the idle connection.',
    '代理关闭空闲连接后，上传任务超时了。',
    'proxy-upload',
    '{"schema_version":2,"root_action_id":"timed-out","nodes":[{"id":"timed-out","text":"timed out","kind":"action","label_zh":"上传因超过等待期限而失败"},{"id":"upload","text":"The upload","kind":"core","label_zh":"未能及时完成的上传任务"},{"id":"closed","text":"closed","kind":"action","label_zh":"代理关闭网络连接"},{"id":"proxy","text":"the proxy","kind":"core","label_zh":"主动关闭连接的代理服务"},{"id":"connection","text":"the connection","kind":"core","label_zh":"被代理关闭的网络连接"},{"id":"idle","text":"idle","kind":"modifier","label_zh":"说明连接当时没有数据活动"}],"links":[{"id":"timed-out->upload","from":"timed-out","to":"upload","kind":"core","relation_type":"actor","label_zh":"发生超时的是上传任务"},{"id":"closed->proxy","from":"closed","to":"proxy","kind":"core","relation_type":"actor","label_zh":"代理服务执行了关闭操作"},{"id":"closed->connection","from":"closed","to":"connection","kind":"core","relation_type":"target","label_zh":"关闭操作作用于网络连接"},{"id":"closed->timed-out","from":"closed","to":"timed-out","kind":"modifier","relation_type":"time","label_zh":"代理关闭连接后上传发生超时"},{"id":"idle->connection","from":"idle","to":"connection","kind":"modifier","relation_type":"quality","label_zh":"被关闭的连接当时处于空闲状态"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The upload timed out.","sentence_zh":"上传任务超时了。","add_node_ids":["timed-out","upload"],"add_link_ids":["timed-out->upload"],"focus_node_id":"timed-out","note_zh":"先表达上传没有在期限内完成。"},{"step_no":2,"label":"时间","sentence_en":"The upload timed out after the proxy closed the connection.","sentence_zh":"代理关闭连接后，上传任务超时了。","add_node_ids":["closed","proxy","connection"],"add_link_ids":["closed->proxy","closed->connection","closed->timed-out"],"focus_node_id":"closed","note_zh":"加入超时之前发生的连接关闭事件。"},{"step_no":3,"label":"对象细节","sentence_en":"The upload timed out after the proxy closed the idle connection.","sentence_zh":"代理关闭空闲连接后，上传任务超时了。","add_node_ids":["idle"],"add_link_ids":["idle->connection"],"focus_node_id":"idle","note_zh":"说明代理关闭的是被判定为空闲的连接。"}]}'
  ),
  (
    'tip-primary',
    'tip',
    'tip',
    'tip someone off',
    '向某人提示异常线索',
    'The latency spike tipped us off to a missing index.',
    '延迟突增提示我们可能缺少一个索引。',
    'The latency spike tipped us off to a missing index in the reporting database.',
    '延迟突增提示我们报表数据库中可能缺少一个索引。',
    'latency-diagnosis',
    '{"schema_version":2,"root_action_id":"tipped","nodes":[{"id":"tipped","text":"tipped","kind":"action","label_zh":"提供帮助发现问题的线索"},{"id":"latency-spike","text":"The latency spike","kind":"core","label_zh":"引起注意的延迟异常"},{"id":"us","text":"us","kind":"core","label_zh":"从异常中得到提示的团队"},{"id":"missing-index","text":"a missing index","kind":"core","label_zh":"延迟异常所提示的潜在问题"},{"id":"in-reporting-database","text":"in the reporting database","kind":"modifier","label_zh":"缺失索引所在的数据库"}],"links":[{"id":"tipped->latency-spike","from":"tipped","to":"latency-spike","kind":"core","relation_type":"actor","label_zh":"延迟突增提供了排查线索"},{"id":"tipped->us","from":"tipped","to":"us","kind":"core","relation_type":"recipient","label_zh":"团队从该异常中获得提示"},{"id":"tipped->missing-index","from":"tipped","to":"missing-index","kind":"core","relation_type":"content","label_zh":"线索指向一个缺失的索引"},{"id":"in-reporting-database->missing-index","from":"in-reporting-database","to":"missing-index","kind":"modifier","relation_type":"place","label_zh":"缺失的索引本应位于报表数据库中"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The latency spike tipped us off to a missing index.","sentence_zh":"延迟突增提示我们可能缺少一个索引。","add_node_ids":["tipped","latency-spike","us","missing-index"],"add_link_ids":["tipped->latency-spike","tipped->us","tipped->missing-index"],"focus_node_id":"tipped","note_zh":"延迟异常成为团队发现索引问题的线索。"},{"step_no":2,"label":"场景","sentence_en":"The latency spike tipped us off to a missing index in the reporting database.","sentence_zh":"延迟突增提示我们报表数据库中可能缺少一个索引。","add_node_ids":["in-reporting-database"],"add_link_ids":["in-reporting-database->missing-index"],"focus_node_id":"in-reporting-database","note_zh":"明确缺失索引所在的数据库。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
