-- Generated verb paths batch batch-010.
-- Generated under docs/verb-sentence-growth-standard.md.

PRAGMA foreign_keys = ON;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'whisper-primary',
    'whisper',
    'whisper',
    'whisper information',
    '轻声告诉某人某项信息',
    'Maya whispered the rollback code.',
    '玛雅轻声说出了回滚代码。',
    'Maya whispered the rollback code to Ben during the outage.',
    '故障期间，玛雅把回滚代码轻声告诉了本。',
    'quiet-rollback',
    '{"schema_version":2,"root_action_id":"whispered","nodes":[{"id":"whispered","text":"whispered","kind":"action","label_zh":"轻声说出回滚代码"},{"id":"maya","text":"Maya","kind":"core","label_zh":"说出代码的人"},{"id":"rollback-code","text":"the rollback code","kind":"core","label_zh":"被轻声告知的内容"},{"id":"ben","text":"Ben","kind":"core","label_zh":"听到代码的人"},{"id":"during-outage","text":"during the outage","kind":"modifier","label_zh":"轻声交谈发生的时间"}],"links":[{"id":"whispered->maya","from":"whispered","to":"maya","kind":"core","relation_type":"actor","label_zh":"Maya轻声说出信息"},{"id":"whispered->rollback-code","from":"whispered","to":"rollback-code","kind":"core","relation_type":"content","label_zh":"说出的内容是回滚代码"},{"id":"whispered->ben","from":"whispered","to":"ben","kind":"core","relation_type":"recipient","label_zh":"Ben是信息的接收者"},{"id":"during-outage->whispered","from":"during-outage","to":"whispered","kind":"modifier","relation_type":"time","label_zh":"故障期间发生了这次耳语"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Maya whispered the rollback code.","sentence_zh":"玛雅轻声说出了回滚代码。","add_node_ids":["whispered","maya","rollback-code"],"add_link_ids":["whispered->maya","whispered->rollback-code"],"focus_node_id":"whispered","note_zh":"先呈现轻声说出信息的核心画面。"},{"step_no":2,"label":"对象细节","sentence_en":"Maya whispered the rollback code to Ben.","sentence_zh":"玛雅把回滚代码轻声告诉了本。","add_node_ids":["ben"],"add_link_ids":["whispered->ben"],"focus_node_id":"ben","note_zh":"补充这句话是说给谁听的。"},{"step_no":3,"label":"时间","sentence_en":"Maya whispered the rollback code to Ben during the outage.","sentence_zh":"故障期间，玛雅把回滚代码轻声告诉了本。","add_node_ids":["during-outage"],"add_link_ids":["during-outage->whispered"],"focus_node_id":"during-outage","note_zh":"最后说明这次低声交流发生在故障期间。"}]}'
  ),
  (
    'will-primary',
    'will',
    'will',
    'will reduce',
    '将会产生某种结果',
    'The new cache will reduce database load.',
    '新缓存将会降低数据库负载。',
    'The new cache will reduce database load after we enable it.',
    '我们启用新缓存后，它将会降低数据库负载。',
    'cache-rollout',
    '{"schema_version":2,"root_action_id":"will-reduce","nodes":[{"id":"will-reduce","text":"will reduce","kind":"action","label_zh":"预计将降低数据库负载"},{"id":"new-cache","text":"The new cache","kind":"core","label_zh":"产生降低效果的新缓存"},{"id":"database-load","text":"database load","kind":"core","label_zh":"将被降低的系统负载"},{"id":"enable","text":"enable","kind":"action","label_zh":"启用新缓存"},{"id":"we","text":"we","kind":"core","label_zh":"执行启用操作的团队"},{"id":"it","text":"it","kind":"core","label_zh":"将被启用的新缓存"}],"links":[{"id":"will-reduce->new-cache","from":"will-reduce","to":"new-cache","kind":"core","relation_type":"actor","label_zh":"新缓存将带来负载下降"},{"id":"will-reduce->database-load","from":"will-reduce","to":"database-load","kind":"core","relation_type":"target","label_zh":"下降作用于数据库负载"},{"id":"enable->we","from":"enable","to":"we","kind":"core","relation_type":"actor","label_zh":"团队负责启用缓存"},{"id":"enable->it","from":"enable","to":"it","kind":"core","relation_type":"target","label_zh":"启用的对象是这套新缓存"},{"id":"enable->will-reduce","from":"enable","to":"will-reduce","kind":"modifier","relation_type":"time","label_zh":"负载下降预计在缓存启用后发生"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The new cache will reduce database load.","sentence_zh":"新缓存将会降低数据库负载。","add_node_ids":["will-reduce","new-cache","database-load"],"add_link_ids":["will-reduce->new-cache","will-reduce->database-load"],"focus_node_id":"will-reduce","note_zh":"will与reduce一起表达预期会出现的效果。"},{"step_no":2,"label":"时间","sentence_en":"The new cache will reduce database load after we enable it.","sentence_zh":"我们启用新缓存后，它将会降低数据库负载。","add_node_ids":["enable","we","it"],"add_link_ids":["enable->we","enable->it","enable->will-reduce"],"focus_node_id":"enable","note_zh":"加入启用动作，明确预期结果从何时开始。"}]}'
  ),
  (
    'win-primary',
    'win',
    'win',
    'win an award',
    '赢得奖项',
    'Our prototype won the accessibility award.',
    '我们的原型赢得了无障碍奖项。',
    'Our prototype won the accessibility award at Friday''s demo despite its rough visuals.',
    '尽管视觉效果还很粗糙，我们的原型仍在周五的演示会上赢得了无障碍奖项。',
    'accessibility-demo',
    '{"schema_version":2,"root_action_id":"won","nodes":[{"id":"won","text":"won","kind":"action","label_zh":"凭作品赢得奖项"},{"id":"our-prototype","text":"Our prototype","kind":"core","label_zh":"获得认可的原型"},{"id":"accessibility-award","text":"the accessibility award","kind":"core","label_zh":"原型赢得的奖项"},{"id":"at-fridays-demo","text":"at Friday''s demo","kind":"modifier","label_zh":"公布获奖结果的场合"},{"id":"despite-rough-visuals","text":"despite its rough visuals","kind":"modifier","label_zh":"未阻止原型获奖的不足"}],"links":[{"id":"won->our-prototype","from":"won","to":"our-prototype","kind":"core","relation_type":"actor","label_zh":"获奖的是团队的原型"},{"id":"won->accessibility-award","from":"won","to":"accessibility-award","kind":"core","relation_type":"target","label_zh":"赢得的是无障碍奖项"},{"id":"at-fridays-demo->won","from":"at-fridays-demo","to":"won","kind":"modifier","relation_type":"time","label_zh":"获奖消息出现在周五演示会上"},{"id":"despite-rough-visuals->won","from":"despite-rough-visuals","to":"won","kind":"modifier","relation_type":"condition","label_zh":"视觉效果粗糙并未妨碍获奖"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Our prototype won the accessibility award.","sentence_zh":"我们的原型赢得了无障碍奖项。","add_node_ids":["won","our-prototype","accessibility-award"],"add_link_ids":["won->our-prototype","won->accessibility-award"],"focus_node_id":"won","note_zh":"先说明原型获得了什么荣誉。"},{"step_no":2,"label":"场景","sentence_en":"Our prototype won the accessibility award at Friday''s demo.","sentence_zh":"我们的原型在周五的演示会上赢得了无障碍奖项。","add_node_ids":["at-fridays-demo"],"add_link_ids":["at-fridays-demo->won"],"focus_node_id":"at-fridays-demo","note_zh":"演示会为获奖提供了具体场景。"},{"step_no":3,"label":"条件","sentence_en":"Our prototype won the accessibility award at Friday''s demo despite its rough visuals.","sentence_zh":"尽管视觉效果还很粗糙，我们的原型仍在周五的演示会上赢得了无障碍奖项。","add_node_ids":["despite-rough-visuals"],"add_link_ids":["despite-rough-visuals->won"],"focus_node_id":"despite-rough-visuals","note_zh":"补上没有阻碍获奖的不利因素。"}]}'
  ),
  (
    'wind-primary',
    'wind',
    'wind',
    'wind a cable',
    '把线缆缠绕在物体周围',
    'Leo wound the cable.',
    '利奥缠好了线缆。',
    'Leo wound the cable around the stand before closing the case.',
    '利奥先把线缆缠在支架周围，然后才合上外壳。',
    'hardware-assembly',
    '{"schema_version":2,"root_action_id":"wound","nodes":[{"id":"wound","text":"wound","kind":"action","label_zh":"把线缆缠到支架上"},{"id":"leo","text":"Leo","kind":"core","label_zh":"整理线缆的人"},{"id":"cable","text":"the cable","kind":"core","label_zh":"被缠绕的线缆"},{"id":"around-stand","text":"around the stand","kind":"modifier","label_zh":"线缆环绕的位置"},{"id":"closing","text":"closing","kind":"action","label_zh":"合上设备外壳"},{"id":"case","text":"the case","kind":"core","label_zh":"随后被合上的外壳"}],"links":[{"id":"wound->leo","from":"wound","to":"leo","kind":"core","relation_type":"actor","label_zh":"Leo执行线缆缠绕"},{"id":"wound->cable","from":"wound","to":"cable","kind":"core","relation_type":"target","label_zh":"缠绕操作作用于线缆"},{"id":"around-stand->wound","from":"around-stand","to":"wound","kind":"modifier","relation_type":"place","label_zh":"线缆被绕在支架周围"},{"id":"closing->leo","from":"closing","to":"leo","kind":"core","relation_type":"actor","label_zh":"Leo也负责合上外壳"},{"id":"closing->case","from":"closing","to":"case","kind":"core","relation_type":"target","label_zh":"合上的对象是设备外壳"},{"id":"closing->wound","from":"closing","to":"wound","kind":"modifier","relation_type":"sequence","label_zh":"缠好线缆后才合上外壳"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Leo wound the cable.","sentence_zh":"利奥缠好了线缆。","add_node_ids":["wound","leo","cable"],"add_link_ids":["wound->leo","wound->cable"],"focus_node_id":"wound","note_zh":"主干突出线缆受到缠绕处理。"},{"step_no":2,"label":"场景","sentence_en":"Leo wound the cable around the stand.","sentence_zh":"利奥把线缆缠在了支架周围。","add_node_ids":["around-stand"],"add_link_ids":["around-stand->wound"],"focus_node_id":"around-stand","note_zh":"说明线缆具体绕着什么物体。"},{"step_no":3,"label":"顺序","sentence_en":"Leo wound the cable around the stand before closing the case.","sentence_zh":"利奥先把线缆缠在支架周围，然后才合上外壳。","add_node_ids":["closing","case"],"add_link_ids":["closing->leo","closing->case","closing->wound"],"focus_node_id":"closing","note_zh":"外壳关闭动作交代了装配顺序。"}]}'
  ),
  (
    'wind-down-primary',
    'wind-down',
    'wind down',
    'wind down after work',
    '结束紧张活动后逐渐放松',
    'Nora winds down.',
    '诺拉逐渐放松下来。',
    'Nora winds down with a podcast after the release goes live.',
    '版本上线后，诺拉听着播客逐渐放松下来。',
    'post-release-rest',
    '{"schema_version":2,"root_action_id":"winds-down","nodes":[{"id":"winds-down","text":"winds down","kind":"action","label_zh":"从发布压力中逐渐放松"},{"id":"nora","text":"Nora","kind":"core","label_zh":"准备放松的人"},{"id":"with-podcast","text":"with a podcast","kind":"modifier","label_zh":"帮助她放松的方式"},{"id":"goes-live","text":"goes live","kind":"action","label_zh":"版本正式上线"},{"id":"release","text":"the release","kind":"core","label_zh":"完成上线的版本"}],"links":[{"id":"winds-down->nora","from":"winds-down","to":"nora","kind":"core","relation_type":"actor","label_zh":"Nora逐渐进入放松状态"},{"id":"with-podcast->winds-down","from":"with-podcast","to":"winds-down","kind":"modifier","relation_type":"manner","label_zh":"她通过听播客来放松"},{"id":"goes-live->release","from":"goes-live","to":"release","kind":"core","relation_type":"actor","label_zh":"正式上线的是这个版本"},{"id":"goes-live->winds-down","from":"goes-live","to":"winds-down","kind":"modifier","relation_type":"time","label_zh":"版本上线后Nora才开始放松"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Nora winds down.","sentence_zh":"诺拉逐渐放松下来。","add_node_ids":["winds-down","nora"],"add_link_ids":["winds-down->nora"],"focus_node_id":"winds-down","note_zh":"先表达紧张状态逐步消退。"},{"step_no":2,"label":"方式","sentence_en":"Nora winds down with a podcast.","sentence_zh":"诺拉听着播客逐渐放松下来。","add_node_ids":["with-podcast"],"add_link_ids":["with-podcast->winds-down"],"focus_node_id":"with-podcast","note_zh":"播客说明她采用的放松方式。"},{"step_no":3,"label":"时间","sentence_en":"Nora winds down with a podcast after the release goes live.","sentence_zh":"版本上线后，诺拉听着播客逐渐放松下来。","add_node_ids":["goes-live","release"],"add_link_ids":["goes-live->release","goes-live->winds-down"],"focus_node_id":"goes-live","note_zh":"上线事件解释她何时结束紧张工作。"}]}'
  ),
  (
    'wind-up-primary',
    'wind-up',
    'wind up',
    'wind up doing something',
    '经过一番发展后最终做了某事',
    'The audit wound up exposing three expired certificates.',
    '这次审计最终发现了三张过期证书。',
    'The audit wound up exposing three expired certificates in the staging cluster.',
    '这次审计最终发现预发布集群中有三张过期证书。',
    'certificate-audit',
    '{"schema_version":2,"root_action_id":"wound-up","nodes":[{"id":"wound-up","text":"wound up","kind":"action","label_zh":"最终形成了意外结果"},{"id":"audit","text":"The audit","kind":"core","label_zh":"带来最终发现的审计"},{"id":"exposing","text":"exposing","kind":"action","label_zh":"揭示过期证书"},{"id":"expired-certificates","text":"three expired certificates","kind":"core","label_zh":"审计最终发现的问题"},{"id":"in-staging-cluster","text":"in the staging cluster","kind":"modifier","label_zh":"过期证书所在的环境"}],"links":[{"id":"wound-up->audit","from":"wound-up","to":"audit","kind":"core","relation_type":"actor","label_zh":"审计过程产生了最终结果"},{"id":"wound-up->exposing","from":"wound-up","to":"exposing","kind":"core","relation_type":"nested_action","label_zh":"最终结果是揭示证书问题"},{"id":"exposing->audit","from":"exposing","to":"audit","kind":"modifier","relation_type":"shared_actor","label_zh":"揭示问题的仍是这次审计"},{"id":"exposing->expired-certificates","from":"exposing","to":"expired-certificates","kind":"core","relation_type":"target","label_zh":"被揭示的是三张过期证书"},{"id":"in-staging-cluster->expired-certificates","from":"in-staging-cluster","to":"expired-certificates","kind":"modifier","relation_type":"place","label_zh":"这些证书位于预发布集群"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The audit wound up exposing three expired certificates.","sentence_zh":"这次审计最终发现了三张过期证书。","add_node_ids":["wound-up","audit","exposing","expired-certificates"],"add_link_ids":["wound-up->audit","wound-up->exposing","exposing->audit","exposing->expired-certificates"],"focus_node_id":"wound-up","note_zh":"wound up引出审计过程最终产生的发现。"},{"step_no":2,"label":"对象细节","sentence_en":"The audit wound up exposing three expired certificates in the staging cluster.","sentence_zh":"这次审计最终发现预发布集群中有三张过期证书。","add_node_ids":["in-staging-cluster"],"add_link_ids":["in-staging-cluster->expired-certificates"],"focus_node_id":"in-staging-cluster","note_zh":"补充证书问题出现在哪个环境中。"}]}'
  ),
  (
    'wipe-primary',
    'wipe',
    'wipe',
    'wipe data from a device',
    '从设备中清除数据',
    'Priya wiped the test data.',
    '普里娅清除了测试数据。',
    'Priya wiped the test data from the shared tablet before returning it.',
    '普里娅先清除共享平板中的测试数据，然后才归还它。',
    'shared-device-reset',
    '{"schema_version":2,"root_action_id":"wiped","nodes":[{"id":"wiped","text":"wiped","kind":"action","label_zh":"清除平板上的测试数据"},{"id":"priya","text":"Priya","kind":"core","label_zh":"执行数据清除的人"},{"id":"test-data","text":"the test data","kind":"core","label_zh":"被清除的数据"},{"id":"from-shared-tablet","text":"from the shared tablet","kind":"modifier","label_zh":"数据被清除的设备来源"},{"id":"returning","text":"returning","kind":"action","label_zh":"归还共享平板"},{"id":"it","text":"it","kind":"core","label_zh":"随后被归还的平板"}],"links":[{"id":"wiped->priya","from":"wiped","to":"priya","kind":"core","relation_type":"actor","label_zh":"Priya负责清除数据"},{"id":"wiped->test-data","from":"wiped","to":"test-data","kind":"core","relation_type":"target","label_zh":"清除操作针对测试数据"},{"id":"from-shared-tablet->wiped","from":"from-shared-tablet","to":"wiped","kind":"modifier","relation_type":"place","label_zh":"测试数据从共享平板中被移除"},{"id":"returning->priya","from":"returning","to":"priya","kind":"core","relation_type":"actor","label_zh":"归还平板的人也是Priya"},{"id":"returning->it","from":"returning","to":"it","kind":"core","relation_type":"target","label_zh":"归还的对象是那台共享平板"},{"id":"returning->wiped","from":"returning","to":"wiped","kind":"modifier","relation_type":"sequence","label_zh":"数据清除发生在归还平板之前"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Priya wiped the test data.","sentence_zh":"普里娅清除了测试数据。","add_node_ids":["wiped","priya","test-data"],"add_link_ids":["wiped->priya","wiped->test-data"],"focus_node_id":"wiped","note_zh":"先突出数据被彻底清除。"},{"step_no":2,"label":"场景","sentence_en":"Priya wiped the test data from the shared tablet.","sentence_zh":"普里娅清除了共享平板中的测试数据。","add_node_ids":["from-shared-tablet"],"add_link_ids":["from-shared-tablet->wiped"],"focus_node_id":"from-shared-tablet","note_zh":"指出测试数据原本存放的设备。"},{"step_no":3,"label":"顺序","sentence_en":"Priya wiped the test data from the shared tablet before returning it.","sentence_zh":"普里娅先清除共享平板中的测试数据，然后才归还它。","add_node_ids":["returning","it"],"add_link_ids":["returning->priya","returning->it","returning->wiped"],"focus_node_id":"returning","note_zh":"归还动作说明清除数据是交还设备前的步骤。"}]}'
  ),
  (
    'wish-primary',
    'wish',
    'wish',
    'wish something were possible',
    '希望现实情况有所不同',
    'I wish the installer supported offline mode.',
    '我希望这个安装程序支持离线模式。',
    'I wish the installer supported offline mode for remote sites during outages.',
    '我希望这个安装程序能在系统中断时为偏远站点提供离线模式。',
    'offline-installer',
    '{"schema_version":2,"root_action_id":"wish","nodes":[{"id":"wish","text":"wish","kind":"action","label_zh":"表达对安装程序的愿望"},{"id":"i","text":"I","kind":"core","label_zh":"提出愿望的人"},{"id":"supported","text":"supported","kind":"action","label_zh":"能够支持离线模式"},{"id":"installer","text":"the installer","kind":"core","label_zh":"希望具备新能力的安装程序"},{"id":"offline-mode","text":"offline mode","kind":"core","label_zh":"希望安装程序支持的功能"},{"id":"for-remote-sites","text":"for remote sites","kind":"modifier","label_zh":"离线模式要服务的使用场景"},{"id":"during-outages","text":"during outages","kind":"modifier","label_zh":"离线能力尤其重要的时间"}],"links":[{"id":"wish->i","from":"wish","to":"i","kind":"core","relation_type":"actor","label_zh":"我表达这一愿望"},{"id":"wish->supported","from":"wish","to":"supported","kind":"core","relation_type":"content","label_zh":"愿望内容是安装程序支持离线模式"},{"id":"supported->installer","from":"supported","to":"installer","kind":"core","relation_type":"actor","label_zh":"希望安装程序拥有支持能力"},{"id":"supported->offline-mode","from":"supported","to":"offline-mode","kind":"core","relation_type":"target","label_zh":"希望得到支持的是离线模式"},{"id":"for-remote-sites->offline-mode","from":"for-remote-sites","to":"offline-mode","kind":"modifier","relation_type":"purpose","label_zh":"离线模式用于偏远站点"},{"id":"during-outages->supported","from":"during-outages","to":"supported","kind":"modifier","relation_type":"time","label_zh":"系统中断时这种支持尤其有用"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I wish the installer supported offline mode.","sentence_zh":"我希望这个安装程序支持离线模式。","add_node_ids":["wish","i","supported","installer","offline-mode"],"add_link_ids":["wish->i","wish->supported","supported->installer","supported->offline-mode"],"focus_node_id":"wish","note_zh":"wish引出一个与当前现实不同的期待。"},{"step_no":2,"label":"目的","sentence_en":"I wish the installer supported offline mode for remote sites.","sentence_zh":"我希望这个安装程序能为偏远站点提供离线模式。","add_node_ids":["for-remote-sites"],"add_link_ids":["for-remote-sites->offline-mode"],"focus_node_id":"for-remote-sites","note_zh":"说明这项离线功能主要服务于哪些地点。"},{"step_no":3,"label":"时间","sentence_en":"I wish the installer supported offline mode for remote sites during outages.","sentence_zh":"我希望这个安装程序能在系统中断时为偏远站点提供离线模式。","add_node_ids":["during-outages"],"add_link_ids":["during-outages->supported"],"focus_node_id":"during-outages","note_zh":"加入最需要离线支持的具体时段。"}]}'
  ),
  (
    'withdraw-primary',
    'withdraw',
    'withdraw',
    'withdraw a proposal',
    '正式撤回已经提出的方案',
    'Elena withdrew her proposal.',
    '埃琳娜撤回了她的方案。',
    'Elena withdrew her proposal after Legal flagged a licensing conflict.',
    '法务指出许可证冲突后，埃琳娜撤回了她的方案。',
    'licensing-review',
    '{"schema_version":2,"root_action_id":"withdrew","nodes":[{"id":"withdrew","text":"withdrew","kind":"action","label_zh":"撤回已经提交的方案"},{"id":"elena","text":"Elena","kind":"core","label_zh":"决定撤回方案的人"},{"id":"her-proposal","text":"her proposal","kind":"core","label_zh":"被撤回的方案"},{"id":"flagged","text":"flagged","kind":"action","label_zh":"指出许可证冲突"},{"id":"legal","text":"Legal","kind":"core","label_zh":"发现合规问题的法务团队"},{"id":"licensing-conflict","text":"a licensing conflict","kind":"core","label_zh":"法务指出的问题"}],"links":[{"id":"withdrew->elena","from":"withdrew","to":"elena","kind":"core","relation_type":"actor","label_zh":"Elena作出撤回决定"},{"id":"withdrew->her-proposal","from":"withdrew","to":"her-proposal","kind":"core","relation_type":"target","label_zh":"撤回的是她自己的方案"},{"id":"flagged->legal","from":"flagged","to":"legal","kind":"core","relation_type":"actor","label_zh":"法务团队指出了问题"},{"id":"flagged->licensing-conflict","from":"flagged","to":"licensing-conflict","kind":"core","relation_type":"target","label_zh":"被指出的是许可证冲突"},{"id":"flagged->withdrew","from":"flagged","to":"withdrew","kind":"modifier","relation_type":"reason","label_zh":"发现许可证冲突促使她撤回方案"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Elena withdrew her proposal.","sentence_zh":"埃琳娜撤回了她的方案。","add_node_ids":["withdrew","elena","her-proposal"],"add_link_ids":["withdrew->elena","withdrew->her-proposal"],"focus_node_id":"withdrew","note_zh":"主干说明原先提出的方案不再继续。"},{"step_no":2,"label":"原因","sentence_en":"Elena withdrew her proposal after Legal flagged a licensing conflict.","sentence_zh":"法务指出许可证冲突后，埃琳娜撤回了她的方案。","add_node_ids":["flagged","legal","licensing-conflict"],"add_link_ids":["flagged->legal","flagged->licensing-conflict","flagged->withdrew"],"focus_node_id":"flagged","note_zh":"法务发现的问题解释了撤回决定。"}]}'
  ),
  (
    'wither-primary',
    'wither',
    'wither',
    'interest withers',
    '兴趣或热度逐渐衰退',
    'Interest withered.',
    '用户的兴趣逐渐消退了。',
    'Interest withered after the free trial ended because onboarding stayed unclear.',
    '免费试用结束后，由于新手引导一直不清楚，用户的兴趣逐渐消退了。',
    'beta-adoption',
    '{"schema_version":2,"root_action_id":"withered","nodes":[{"id":"withered","text":"withered","kind":"action","label_zh":"用户兴趣逐渐消退"},{"id":"interest","text":"Interest","kind":"core","label_zh":"发生衰退的关注度"},{"id":"ended","text":"ended","kind":"action","label_zh":"免费试用期结束"},{"id":"free-trial","text":"the free trial","kind":"core","label_zh":"结束的试用阶段"},{"id":"stayed","text":"stayed","kind":"action","label_zh":"引导说明一直不够清晰"},{"id":"onboarding","text":"onboarding","kind":"core","label_zh":"持续存在问题的新手引导"},{"id":"unclear","text":"unclear","kind":"modifier","label_zh":"新手引导保持的模糊状态"}],"links":[{"id":"withered->interest","from":"withered","to":"interest","kind":"core","relation_type":"actor","label_zh":"逐渐消退的是用户兴趣"},{"id":"ended->free-trial","from":"ended","to":"free-trial","kind":"core","relation_type":"actor","label_zh":"免费试用期走到终点"},{"id":"ended->withered","from":"ended","to":"withered","kind":"modifier","relation_type":"time","label_zh":"兴趣在试用结束后开始明显衰退"},{"id":"stayed->onboarding","from":"stayed","to":"onboarding","kind":"core","relation_type":"actor","label_zh":"新手引导持续处于某种状态"},{"id":"unclear->onboarding","from":"unclear","to":"onboarding","kind":"modifier","relation_type":"quality","label_zh":"新手引导一直缺乏清晰度"},{"id":"stayed->withered","from":"stayed","to":"withered","kind":"modifier","relation_type":"reason","label_zh":"引导始终不清楚导致兴趣衰退"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Interest withered.","sentence_zh":"用户的兴趣逐渐消退了。","add_node_ids":["withered","interest"],"add_link_ids":["withered->interest"],"focus_node_id":"withered","note_zh":"withered描写兴趣逐步失去活力。"},{"step_no":2,"label":"时间","sentence_en":"Interest withered after the free trial ended.","sentence_zh":"免费试用结束后，用户的兴趣逐渐消退了。","add_node_ids":["ended","free-trial"],"add_link_ids":["ended->free-trial","ended->withered"],"focus_node_id":"ended","note_zh":"试用期结束标出了兴趣下降的时间点。"},{"step_no":3,"label":"原因","sentence_en":"Interest withered after the free trial ended because onboarding stayed unclear.","sentence_zh":"免费试用结束后，由于新手引导一直不清楚，用户的兴趣逐渐消退了。","add_node_ids":["stayed","onboarding","unclear"],"add_link_ids":["stayed->onboarding","unclear->onboarding","stayed->withered"],"focus_node_id":"stayed","note_zh":"持续模糊的新手引导解释了热度为何下降。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO verb_paths (
  id,
  verb_id,
  verb,
  title,
  meaning_zh,
  core_sentence_en,
  core_sentence_zh,
  full_sentence_en,
  full_sentence_zh,
  scene,
  growth_json
) VALUES
  (
    'withstand-primary',
    'withstand',
    'withstand',
    'withstand extreme heat',
    '经受住强烈热量而不失效',
    'The enclosure withstood the heat.',
    '这个外壳经受住了高温。',
    'The enclosure withstood the heat for six hours during the burn-in test.',
    '在老化测试期间，这个外壳经受住了长达六小时的高温。',
    'enclosure-test',
    '{"schema_version":2,"root_action_id":"withstood","nodes":[{"id":"withstood","text":"withstood","kind":"action","label_zh":"在高温下保持完好"},{"id":"enclosure","text":"The enclosure","kind":"core","label_zh":"接受耐热测试的外壳"},{"id":"heat","text":"the heat","kind":"core","label_zh":"外壳承受的高温"},{"id":"for-six-hours","text":"for six hours","kind":"modifier","label_zh":"持续承受高温的时长"},{"id":"during-burn-in-test","text":"during the burn-in test","kind":"modifier","label_zh":"验证耐热能力的测试场景"}],"links":[{"id":"withstood->enclosure","from":"withstood","to":"enclosure","kind":"core","relation_type":"actor","label_zh":"设备外壳成功经受考验"},{"id":"withstood->heat","from":"withstood","to":"heat","kind":"core","relation_type":"target","label_zh":"外壳承受的是测试高温"},{"id":"for-six-hours->withstood","from":"for-six-hours","to":"withstood","kind":"modifier","relation_type":"degree","label_zh":"耐热状态持续了六小时"},{"id":"during-burn-in-test->withstood","from":"during-burn-in-test","to":"withstood","kind":"modifier","relation_type":"time","label_zh":"耐热表现出现在老化测试期间"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The enclosure withstood the heat.","sentence_zh":"这个外壳经受住了高温。","add_node_ids":["withstood","enclosure","heat"],"add_link_ids":["withstood->enclosure","withstood->heat"],"focus_node_id":"withstood","note_zh":"先说明外壳没有被高温破坏。"},{"step_no":2,"label":"程度","sentence_en":"The enclosure withstood the heat for six hours.","sentence_zh":"这个外壳经受住了长达六小时的高温。","add_node_ids":["for-six-hours"],"add_link_ids":["for-six-hours->withstood"],"focus_node_id":"for-six-hours","note_zh":"六小时体现了耐热能力的持续程度。"},{"step_no":3,"label":"场景","sentence_en":"The enclosure withstood the heat for six hours during the burn-in test.","sentence_zh":"在老化测试期间，这个外壳经受住了长达六小时的高温。","add_node_ids":["during-burn-in-test"],"add_link_ids":["during-burn-in-test->withstood"],"focus_node_id":"during-burn-in-test","note_zh":"补充得出这一结果的测试环境。"}]}'
  ),
  (
    'witness-primary',
    'witness',
    'witness',
    'witness a recovery',
    '亲眼见证某个事件发生',
    'The interns witnessed the server recover.',
    '实习生们亲眼见证了服务器恢复。',
    'The interns witnessed the server recover within two minutes after the failover completed.',
    '故障切换完成后，实习生们亲眼见证了服务器在两分钟内恢复。',
    'failover-recovery',
    '{"schema_version":2,"root_action_id":"witnessed","nodes":[{"id":"witnessed","text":"witnessed","kind":"action","label_zh":"亲眼看到服务器恢复"},{"id":"interns","text":"The interns","kind":"core","label_zh":"看到恢复过程的人"},{"id":"recover","text":"recover","kind":"action","label_zh":"服务器恢复正常"},{"id":"server","text":"the server","kind":"core","label_zh":"恢复运行的服务器"},{"id":"within-two-minutes","text":"within two minutes","kind":"modifier","label_zh":"服务器完成恢复所用的时间"},{"id":"completed","text":"completed","kind":"action","label_zh":"故障切换完成"},{"id":"failover","text":"the failover","kind":"core","label_zh":"先完成的故障切换流程"}],"links":[{"id":"witnessed->interns","from":"witnessed","to":"interns","kind":"core","relation_type":"actor","label_zh":"实习生亲眼观察了事件"},{"id":"witnessed->recover","from":"witnessed","to":"recover","kind":"core","relation_type":"content","label_zh":"他们看到的是服务器恢复过程"},{"id":"recover->server","from":"recover","to":"server","kind":"core","relation_type":"actor","label_zh":"恢复正常的是服务器"},{"id":"within-two-minutes->recover","from":"within-two-minutes","to":"recover","kind":"modifier","relation_type":"time","label_zh":"服务器在两分钟内完成恢复"},{"id":"completed->failover","from":"completed","to":"failover","kind":"core","relation_type":"actor","label_zh":"故障切换流程已经完成"},{"id":"completed->recover","from":"completed","to":"recover","kind":"modifier","relation_type":"sequence","label_zh":"服务器恢复发生在故障切换完成之后"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The interns witnessed the server recover.","sentence_zh":"实习生们亲眼见证了服务器恢复。","add_node_ids":["witnessed","interns","recover","server"],"add_link_ids":["witnessed->interns","witnessed->recover","recover->server"],"focus_node_id":"witnessed","note_zh":"witnessed强调他们直接看到了完整事件。"},{"step_no":2,"label":"时间","sentence_en":"The interns witnessed the server recover within two minutes.","sentence_zh":"实习生们亲眼见证了服务器在两分钟内恢复。","add_node_ids":["within-two-minutes"],"add_link_ids":["within-two-minutes->recover"],"focus_node_id":"within-two-minutes","note_zh":"两分钟限定的是服务器恢复所需的时间。"},{"step_no":3,"label":"顺序","sentence_en":"The interns witnessed the server recover within two minutes after the failover completed.","sentence_zh":"故障切换完成后，实习生们亲眼见证了服务器在两分钟内恢复。","add_node_ids":["completed","failover"],"add_link_ids":["completed->failover","completed->recover"],"focus_node_id":"completed","note_zh":"故障切换事件交代了恢复之前发生的步骤。"}]}'
  ),
  (
    'work-primary',
    'work',
    'work',
    'software works',
    '软件或设备能够正常运行',
    'The backup script works.',
    '这个备份脚本可以正常运行。',
    'The backup script works on older Linux hosts even without network access.',
    '即使无法访问网络，这个备份脚本也可以在较旧的Linux主机上运行。',
    'legacy-linux',
    '{"schema_version":2,"root_action_id":"works","nodes":[{"id":"works","text":"works","kind":"action","label_zh":"备份脚本能够正常运行"},{"id":"backup-script","text":"The backup script","kind":"core","label_zh":"经过兼容性验证的脚本"},{"id":"on-older-hosts","text":"on older Linux hosts","kind":"modifier","label_zh":"脚本可以运行的旧系统环境"},{"id":"without-network-access","text":"even without network access","kind":"modifier","label_zh":"脚本运行不依赖的条件"}],"links":[{"id":"works->backup-script","from":"works","to":"backup-script","kind":"core","relation_type":"actor","label_zh":"能够正常运行的是备份脚本"},{"id":"on-older-hosts->works","from":"on-older-hosts","to":"works","kind":"modifier","relation_type":"place","label_zh":"脚本在较旧的Linux主机上也能运行"},{"id":"without-network-access->works","from":"without-network-access","to":"works","kind":"modifier","relation_type":"condition","label_zh":"没有网络连接时脚本仍然可用"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"The backup script works.","sentence_zh":"这个备份脚本可以正常运行。","add_node_ids":["works","backup-script"],"add_link_ids":["works->backup-script"],"focus_node_id":"works","note_zh":"works在这里表示软件运行正常。"},{"step_no":2,"label":"场景","sentence_en":"The backup script works on older Linux hosts.","sentence_zh":"这个备份脚本可以在较旧的Linux主机上运行。","add_node_ids":["on-older-hosts"],"add_link_ids":["on-older-hosts->works"],"focus_node_id":"on-older-hosts","note_zh":"旧版Linux主机限定了兼容环境。"},{"step_no":3,"label":"条件","sentence_en":"The backup script works on older Linux hosts even without network access.","sentence_zh":"即使无法访问网络，这个备份脚本也可以在较旧的Linux主机上运行。","add_node_ids":["without-network-access"],"add_link_ids":["without-network-access->works"],"focus_node_id":"without-network-access","note_zh":"进一步说明脚本不联网也能工作。"}]}'
  ),
  (
    'work-on-primary',
    'work-on',
    'work on',
    'work on a plan',
    '投入时间处理某项任务',
    'Sam is working on the migration plan.',
    '萨姆正在处理迁移计划。',
    'Sam is working on the migration plan with the database team this week.',
    '萨姆本周正在与数据库团队一起处理迁移计划。',
    'migration-planning',
    '{"schema_version":2,"root_action_id":"working-on","nodes":[{"id":"working-on","text":"is working on","kind":"action","label_zh":"正在处理迁移计划"},{"id":"sam","text":"Sam","kind":"core","label_zh":"负责推进计划的人"},{"id":"migration-plan","text":"the migration plan","kind":"core","label_zh":"正在处理的工作内容"},{"id":"with-database-team","text":"with the database team","kind":"modifier","label_zh":"共同参与规划的团队"},{"id":"this-week","text":"this week","kind":"modifier","label_zh":"集中处理计划的时间"}],"links":[{"id":"working-on->sam","from":"working-on","to":"sam","kind":"core","relation_type":"actor","label_zh":"Sam正在投入这项工作"},{"id":"working-on->migration-plan","from":"working-on","to":"migration-plan","kind":"core","relation_type":"target","label_zh":"处理的内容是迁移计划"},{"id":"with-database-team->working-on","from":"with-database-team","to":"working-on","kind":"modifier","relation_type":"manner","label_zh":"Sam与数据库团队共同推进计划"},{"id":"this-week->working-on","from":"this-week","to":"working-on","kind":"modifier","relation_type":"time","label_zh":"这项规划工作安排在本周"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Sam is working on the migration plan.","sentence_zh":"萨姆正在处理迁移计划。","add_node_ids":["working-on","sam","migration-plan"],"add_link_ids":["working-on->sam","working-on->migration-plan"],"focus_node_id":"working-on","note_zh":"work on指持续投入精力处理具体任务。"},{"step_no":2,"label":"方式","sentence_en":"Sam is working on the migration plan with the database team.","sentence_zh":"萨姆正在与数据库团队一起处理迁移计划。","add_node_ids":["with-database-team"],"add_link_ids":["with-database-team->working-on"],"focus_node_id":"with-database-team","note_zh":"数据库团队说明计划如何协同推进。"},{"step_no":3,"label":"时间","sentence_en":"Sam is working on the migration plan with the database team this week.","sentence_zh":"萨姆本周正在与数据库团队一起处理迁移计划。","add_node_ids":["this-week"],"add_link_ids":["this-week->working-on"],"focus_node_id":"this-week","note_zh":"本周限定了这项工作的当前安排。"}]}'
  ),
  (
    'work-out-primary',
    'work-out',
    'work out',
    'work out a solution',
    '通过思考或讨论找到解决办法',
    'We worked out a safer deployment order.',
    '我们想出了一个更安全的部署顺序。',
    'We worked out a safer deployment order during the incident review by comparing both rollback logs.',
    '我们在事故复盘期间通过对比两份回滚日志，想出了一个更安全的部署顺序。',
    'deployment-review',
    '{"schema_version":2,"root_action_id":"worked-out","nodes":[{"id":"worked-out","text":"worked out","kind":"action","label_zh":"想出了更安全的部署顺序"},{"id":"we","text":"We","kind":"core","label_zh":"共同找到方案的团队"},{"id":"safer-order","text":"a safer deployment order","kind":"core","label_zh":"最终确定的部署安排"},{"id":"during-review","text":"during the incident review","kind":"modifier","label_zh":"找到方案的会议场景"},{"id":"comparing","text":"comparing","kind":"action","label_zh":"对比两份回滚日志"},{"id":"rollback-logs","text":"both rollback logs","kind":"core","label_zh":"用于对比的两份日志"}],"links":[{"id":"worked-out->we","from":"worked-out","to":"we","kind":"core","relation_type":"actor","label_zh":"团队共同推导出部署顺序"},{"id":"worked-out->safer-order","from":"worked-out","to":"safer-order","kind":"core","relation_type":"result","label_zh":"推导结果是更安全的部署顺序"},{"id":"during-review->worked-out","from":"during-review","to":"worked-out","kind":"modifier","relation_type":"time","label_zh":"方案是在事故复盘期间形成的"},{"id":"comparing->we","from":"comparing","to":"we","kind":"modifier","relation_type":"shared_actor","label_zh":"对比日志的也是同一个团队"},{"id":"comparing->rollback-logs","from":"comparing","to":"rollback-logs","kind":"core","relation_type":"target","label_zh":"团队对比了两份回滚日志"},{"id":"comparing->worked-out","from":"comparing","to":"worked-out","kind":"modifier","relation_type":"manner","label_zh":"团队通过对比日志得出部署顺序"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"We worked out a safer deployment order.","sentence_zh":"我们想出了一个更安全的部署顺序。","add_node_ids":["worked-out","we","safer-order"],"add_link_ids":["worked-out->we","worked-out->safer-order"],"focus_node_id":"worked-out","note_zh":"work out表示经过分析后得到可用方案。"},{"step_no":2,"label":"场景","sentence_en":"We worked out a safer deployment order during the incident review.","sentence_zh":"我们在事故复盘期间想出了一个更安全的部署顺序。","add_node_ids":["during-review"],"add_link_ids":["during-review->worked-out"],"focus_node_id":"during-review","note_zh":"事故复盘提供了形成方案的场景。"},{"step_no":3,"label":"方式","sentence_en":"We worked out a safer deployment order during the incident review by comparing both rollback logs.","sentence_zh":"我们在事故复盘期间通过对比两份回滚日志，想出了一个更安全的部署顺序。","add_node_ids":["comparing","rollback-logs"],"add_link_ids":["comparing->we","comparing->rollback-logs","comparing->worked-out"],"focus_node_id":"comparing","note_zh":"日志对比说明团队如何得出这个安排。"}]}'
  ),
  (
    'work-with-primary',
    'work-with',
    'work with',
    'work with a team',
    '与某个团队合作完成工作',
    'Ava works with the security team.',
    '艾娃与安全团队合作。',
    'Ava works with the security team to review vendor access each quarter.',
    '艾娃每季度都会与安全团队合作审查供应商访问权限。',
    'vendor-access-review',
    '{"schema_version":2,"root_action_id":"works-with","nodes":[{"id":"works-with","text":"works with","kind":"action","label_zh":"与安全团队开展合作"},{"id":"ava","text":"Ava","kind":"core","label_zh":"参与合作的员工"},{"id":"security-team","text":"the security team","kind":"core","label_zh":"与Ava合作的团队"},{"id":"review","text":"review","kind":"action","label_zh":"审查供应商访问权限"},{"id":"vendor-access","text":"vendor access","kind":"core","label_zh":"合作审查的权限范围"},{"id":"each-quarter","text":"each quarter","kind":"modifier","label_zh":"权限审查重复进行的频率"}],"links":[{"id":"works-with->ava","from":"works-with","to":"ava","kind":"core","relation_type":"actor","label_zh":"Ava参与这项跨团队合作"},{"id":"works-with->security-team","from":"works-with","to":"security-team","kind":"core","relation_type":"target","label_zh":"Ava的合作方是安全团队"},{"id":"review->vendor-access","from":"review","to":"vendor-access","kind":"core","relation_type":"target","label_zh":"双方审查供应商访问权限"},{"id":"review->ava","from":"review","to":"ava","kind":"modifier","relation_type":"shared_actor","label_zh":"Ava也参与权限审查"},{"id":"review->security-team","from":"review","to":"security-team","kind":"modifier","relation_type":"shared_actor","label_zh":"安全团队同样参与审查"},{"id":"review->works-with","from":"review","to":"works-with","kind":"modifier","relation_type":"purpose","label_zh":"双方合作是为了审查访问权限"},{"id":"each-quarter->review","from":"each-quarter","to":"review","kind":"modifier","relation_type":"frequency","label_zh":"权限审查每季度进行一次"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Ava works with the security team.","sentence_zh":"艾娃与安全团队合作。","add_node_ids":["works-with","ava","security-team"],"add_link_ids":["works-with->ava","works-with->security-team"],"focus_node_id":"works-with","note_zh":"work with直接点明合作关系。"},{"step_no":2,"label":"目的","sentence_en":"Ava works with the security team to review vendor access.","sentence_zh":"艾娃与安全团队合作审查供应商访问权限。","add_node_ids":["review","vendor-access"],"add_link_ids":["review->vendor-access","review->ava","review->security-team","review->works-with"],"focus_node_id":"review","note_zh":"审查权限说明双方合作要完成什么工作。"},{"step_no":3,"label":"频率","sentence_en":"Ava works with the security team to review vendor access each quarter.","sentence_zh":"艾娃每季度都会与安全团队合作审查供应商访问权限。","add_node_ids":["each-quarter"],"add_link_ids":["each-quarter->review"],"focus_node_id":"each-quarter","note_zh":"每季度说明权限审查的固定节奏。"}]}'
  ),
  (
    'worry-primary',
    'worry',
    'worry',
    'worry that something may happen',
    '担心可能发生不好的情况',
    'I worry that the queue may overflow.',
    '我担心队列可能会溢出。',
    'I worry that the queue may overflow during traffic spikes unless autoscaling starts sooner.',
    '我担心队列会在流量高峰期间溢出，除非自动扩缩容更早启动。',
    'queue-capacity',
    '{"schema_version":2,"root_action_id":"worry","nodes":[{"id":"worry","text":"worry","kind":"action","label_zh":"对队列溢出感到担心"},{"id":"i","text":"I","kind":"core","label_zh":"产生担忧的人"},{"id":"overflow","text":"may overflow","kind":"action","label_zh":"队列可能超过容量"},{"id":"queue","text":"the queue","kind":"core","label_zh":"可能发生溢出的队列"},{"id":"during-spikes","text":"during traffic spikes","kind":"modifier","label_zh":"溢出风险较高的时段"},{"id":"starts","text":"starts","kind":"action","label_zh":"自动扩缩容开始运行"},{"id":"autoscaling","text":"autoscaling","kind":"core","label_zh":"需要及时启动的扩缩容机制"},{"id":"sooner","text":"sooner","kind":"modifier","label_zh":"扩缩容需要提前启动的程度"}],"links":[{"id":"worry->i","from":"worry","to":"i","kind":"core","relation_type":"actor","label_zh":"我对风险感到担忧"},{"id":"worry->overflow","from":"worry","to":"overflow","kind":"core","relation_type":"content","label_zh":"担忧的内容是队列可能溢出"},{"id":"overflow->queue","from":"overflow","to":"queue","kind":"core","relation_type":"actor","label_zh":"可能溢出的是消息队列"},{"id":"during-spikes->overflow","from":"during-spikes","to":"overflow","kind":"modifier","relation_type":"time","label_zh":"流量高峰时溢出风险上升"},{"id":"starts->autoscaling","from":"starts","to":"autoscaling","kind":"core","relation_type":"actor","label_zh":"自动扩缩容机制需要启动"},{"id":"sooner->starts","from":"sooner","to":"starts","kind":"modifier","relation_type":"time","label_zh":"扩缩容需要比当前设置更早开始"},{"id":"starts->overflow","from":"starts","to":"overflow","kind":"modifier","relation_type":"condition","label_zh":"若扩缩容未提前启动，队列可能溢出"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I worry that the queue may overflow.","sentence_zh":"我担心队列可能会溢出。","add_node_ids":["worry","i","overflow","queue"],"add_link_ids":["worry->i","worry->overflow","overflow->queue"],"focus_node_id":"worry","note_zh":"worry引出一个尚未发生但令人不安的风险。"},{"step_no":2,"label":"时间","sentence_en":"I worry that the queue may overflow during traffic spikes.","sentence_zh":"我担心队列可能会在流量高峰期间溢出。","add_node_ids":["during-spikes"],"add_link_ids":["during-spikes->overflow"],"focus_node_id":"during-spikes","note_zh":"流量高峰限定了风险最明显的时段。"},{"step_no":3,"label":"条件","sentence_en":"I worry that the queue may overflow during traffic spikes unless autoscaling starts sooner.","sentence_zh":"我担心队列会在流量高峰期间溢出，除非自动扩缩容更早启动。","add_node_ids":["starts","autoscaling","sooner"],"add_link_ids":["starts->autoscaling","sooner->starts","starts->overflow"],"focus_node_id":"starts","note_zh":"自动扩缩容提前启动是避免溢出的关键条件。"}]}'
  ),
  (
    'would-primary',
    'would',
    'would',
    'would approve under a condition',
    '在假设条件成立时愿意批准',
    'I would approve the change.',
    '我会批准这项变更。',
    'I would approve the change if the tests passed, without another meeting.',
    '如果测试通过，我会直接批准这项变更，不再召开会议。',
    'conditional-approval',
    '{"schema_version":2,"root_action_id":"would-approve","nodes":[{"id":"would-approve","text":"would approve","kind":"action","label_zh":"在条件允许时愿意批准变更"},{"id":"i","text":"I","kind":"core","label_zh":"作出假设性批准的人"},{"id":"change","text":"the change","kind":"core","label_zh":"可能获得批准的变更"},{"id":"passed","text":"passed","kind":"action","label_zh":"测试全部通过"},{"id":"tests","text":"the tests","kind":"core","label_zh":"必须通过的验证项目"},{"id":"without-meeting","text":"without another meeting","kind":"modifier","label_zh":"批准不需要增加的流程"}],"links":[{"id":"would-approve->i","from":"would-approve","to":"i","kind":"core","relation_type":"actor","label_zh":"我愿意在条件满足时批准"},{"id":"would-approve->change","from":"would-approve","to":"change","kind":"core","relation_type":"target","label_zh":"可能批准的是这项变更"},{"id":"passed->tests","from":"passed","to":"tests","kind":"core","relation_type":"actor","label_zh":"需要达到要求的是测试结果"},{"id":"passed->would-approve","from":"passed","to":"would-approve","kind":"modifier","relation_type":"condition","label_zh":"测试通过是批准变更的前提"},{"id":"without-meeting->would-approve","from":"without-meeting","to":"would-approve","kind":"modifier","relation_type":"manner","label_zh":"批准可以不再召开会议"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"I would approve the change.","sentence_zh":"我会批准这项变更。","add_node_ids":["would-approve","i","change"],"add_link_ids":["would-approve->i","would-approve->change"],"focus_node_id":"would-approve","note_zh":"would让批准带有假设或保留意味。"},{"step_no":2,"label":"条件","sentence_en":"I would approve the change if the tests passed.","sentence_zh":"如果测试通过，我会批准这项变更。","add_node_ids":["passed","tests"],"add_link_ids":["passed->tests","passed->would-approve"],"focus_node_id":"passed","note_zh":"测试通过明确了批准决定成立的条件。"},{"step_no":3,"label":"方式","sentence_en":"I would approve the change if the tests passed, without another meeting.","sentence_zh":"如果测试通过，我会直接批准这项变更，不再召开会议。","add_node_ids":["without-meeting"],"add_link_ids":["without-meeting->would-approve"],"focus_node_id":"without-meeting","note_zh":"最后说明批准无需增加一次会议。"}]}'
  ),
  (
    'wrap-up-primary',
    'wrap-up',
    'wrap up',
    'wrap up a review',
    '完成并结束一项讨论或工作',
    'Dana wrapped up the sprint review.',
    '达娜结束了迭代评审。',
    'Dana wrapped up the sprint review with three action items before lunch.',
    '达娜在午餐前结束了迭代评审，并确定了三项后续任务。',
    'sprint-review',
    '{"schema_version":2,"root_action_id":"wrapped-up","nodes":[{"id":"wrapped-up","text":"wrapped up","kind":"action","label_zh":"完成并结束迭代评审"},{"id":"dana","text":"Dana","kind":"core","label_zh":"主持收尾的人"},{"id":"sprint-review","text":"the sprint review","kind":"core","label_zh":"被完成的评审会议"},{"id":"with-action-items","text":"with three action items","kind":"modifier","label_zh":"评审结束时形成的任务成果"},{"id":"before-lunch","text":"before lunch","kind":"modifier","label_zh":"评审完成的时间界限"}],"links":[{"id":"wrapped-up->dana","from":"wrapped-up","to":"dana","kind":"core","relation_type":"actor","label_zh":"Dana负责结束评审"},{"id":"wrapped-up->sprint-review","from":"wrapped-up","to":"sprint-review","kind":"core","relation_type":"target","label_zh":"完成的是迭代评审"},{"id":"with-action-items->wrapped-up","from":"with-action-items","to":"wrapped-up","kind":"modifier","relation_type":"result","label_zh":"评审收尾时留下了三项后续任务"},{"id":"before-lunch->wrapped-up","from":"before-lunch","to":"wrapped-up","kind":"modifier","relation_type":"time","label_zh":"评审在午餐前完成"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"Dana wrapped up the sprint review.","sentence_zh":"达娜结束了迭代评审。","add_node_ids":["wrapped-up","dana","sprint-review"],"add_link_ids":["wrapped-up->dana","wrapped-up->sprint-review"],"focus_node_id":"wrapped-up","note_zh":"wrap up表示把评审完整收尾。"},{"step_no":2,"label":"结果","sentence_en":"Dana wrapped up the sprint review with three action items.","sentence_zh":"达娜结束了迭代评审，并确定了三项后续任务。","add_node_ids":["with-action-items"],"add_link_ids":["with-action-items->wrapped-up"],"focus_node_id":"with-action-items","note_zh":"三项后续任务是评审收尾时形成的成果。"},{"step_no":3,"label":"时间","sentence_en":"Dana wrapped up the sprint review with three action items before lunch.","sentence_zh":"达娜在午餐前结束了迭代评审，并确定了三项后续任务。","add_node_ids":["before-lunch"],"add_link_ids":["before-lunch->wrapped-up"],"focus_node_id":"before-lunch","note_zh":"午餐前给评审收尾设置了明确界限。"}]}'
  ),
  (
    'wreck-primary',
    'wreck',
    'wreck',
    'wreck a system',
    '严重破坏系统或数据',
    'A bad migration wrecked the search index.',
    '一次错误的迁移毁坏了搜索索引。',
    'A bad migration wrecked the search index in production within minutes.',
    '一次错误的迁移在几分钟内毁坏了线上环境中的搜索索引。',
    'failed-migration',
    '{"schema_version":2,"root_action_id":"wrecked","nodes":[{"id":"wrecked","text":"wrecked","kind":"action","label_zh":"严重破坏搜索索引"},{"id":"bad-migration","text":"A bad migration","kind":"core","label_zh":"造成破坏的错误迁移"},{"id":"search-index","text":"the search index","kind":"core","label_zh":"遭到严重损坏的索引"},{"id":"in-production","text":"in production","kind":"modifier","label_zh":"索引受损的线上环境"},{"id":"within-minutes","text":"within minutes","kind":"modifier","label_zh":"破坏迅速发生的时间范围"}],"links":[{"id":"wrecked->bad-migration","from":"wrecked","to":"bad-migration","kind":"core","relation_type":"actor","label_zh":"错误迁移造成了严重破坏"},{"id":"wrecked->search-index","from":"wrecked","to":"search-index","kind":"core","relation_type":"target","label_zh":"被破坏的是搜索索引"},{"id":"in-production->wrecked","from":"in-production","to":"wrecked","kind":"modifier","relation_type":"place","label_zh":"破坏发生在线上系统中"},{"id":"within-minutes->wrecked","from":"within-minutes","to":"wrecked","kind":"modifier","relation_type":"time","label_zh":"索引在几分钟内迅速受损"}],"steps":[{"step_no":1,"label":"主干","sentence_en":"A bad migration wrecked the search index.","sentence_zh":"一次错误的迁移毁坏了搜索索引。","add_node_ids":["wrecked","bad-migration","search-index"],"add_link_ids":["wrecked->bad-migration","wrecked->search-index"],"focus_node_id":"wrecked","note_zh":"wrecked强调索引受到严重而非轻微的破坏。"},{"step_no":2,"label":"场景","sentence_en":"A bad migration wrecked the search index in production.","sentence_zh":"一次错误的迁移毁坏了线上环境中的搜索索引。","add_node_ids":["in-production"],"add_link_ids":["in-production->wrecked"],"focus_node_id":"in-production","note_zh":"线上环境说明事故影响了实际服务。"},{"step_no":3,"label":"时间","sentence_en":"A bad migration wrecked the search index in production within minutes.","sentence_zh":"一次错误的迁移在几分钟内毁坏了线上环境中的搜索索引。","add_node_ids":["within-minutes"],"add_link_ids":["within-minutes->wrecked"],"focus_node_id":"within-minutes","note_zh":"几分钟突出破坏发生得非常迅速。"}]}'
  )
ON CONFLICT(id) DO UPDATE SET
  verb_id = excluded.verb_id,
  verb = excluded.verb,
  title = excluded.title,
  meaning_zh = excluded.meaning_zh,
  core_sentence_en = excluded.core_sentence_en,
  core_sentence_zh = excluded.core_sentence_zh,
  full_sentence_en = excluded.full_sentence_en,
  full_sentence_zh = excluded.full_sentence_zh,
  scene = excluded.scene,
  growth_json = excluded.growth_json,
  updated_at = CURRENT_TIMESTAMP;
